### PR TITLE
[webgl]Fix conv2d when width is odd.

### PR DESCRIPTION
**Pull request by lina128**
Fix https://github.com/tensorflow/tfjs/issues/4844.

Background:
This bug is not recently introduced, it seems it has been existing since the beginning. The algorithm that special handle packed x with odd number of cols. The algorithm assumes xTexData.shape's height, width and inChannels are same as x.shape. However, they can be different, in which case, the texShape is wrong, so the result is wrong. Imagine the input image x has a shape [3, 3, 1]. When we call conv2D for the first time, it is not packed, so we use the algorithm in the if condition in `conv2dByMatMul`, x is reshaped to [1, 9, 1]. When the texture is uploaded to GPU, it is packed, xTexData.shape is [1, 9, 1] and xTexData.texShape is [10, 2]. When we call conv2D for the second time, x is packed, so we use the algorithm in the else condition. x is shallowly reshaped to [1, 12, 1], and xTexData.shape is shallowly mutated to [1, 10, 1], texShape is still [10, 2], which result in 2 data missing. Imagine a case where x is already packed. Its xTexData.shape will be [3, 3, 1] and xTexData.texShape will be [12, 2]. For the else condition, x is shallowly reshaped to [3, 4, 1], and xTexData.shape is shallowly mutated to [3, 4, 1], texShape is still [12, 2], no data is lost.

Given that the algorithm in the else condition assumes shape match between x and xTexData, the fix is to check this assumption and only use the algorithm when shapes match.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5264)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
The changes look good, but I have a high level question, what is the relationship relationship between odd cols failure vs shape difference of x and xTexData?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5264#-:-MdXSKgDCILU84BunjEw:br3svd6)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

**Review by lina128 — COMMENTED** [review]
odd cols failure happens in the else condition in the conv2dByMatMul method. The algorithm manually mutates x and xTexData's shape without actually doing reshape. The mutation assumes and only works when when x and xTexData's shapes are the same, otherwise, the xTexData.shape, xTexData.texShape, and x.shape are all messed up, see my explanation in the PR description. This will require an actual reshape to fix it. WebGL's reshape for packed data runs a packedReshape program. Now, why texShape and shape mismatch will result in data missing, I don't know exactly in which step it happens, it's hard to inspect GPU textures step by step, I'm guessing data is lost when calling `acquireTexture(texShape, ...)`, which calls `createPackedMatrixTexture` with calculated width and height from texShape.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5264#-:-MdY50af7yxTaIG0ZhL3:bbfpmpl)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

**Review by pyu10055 — COMMENTED** [review]
Thank you for the in-depth analysis, LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5264#-:-Mdlr2QU0zmsouFhYZtd:b-87yiop)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5264)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever)

**Review by pyu10055 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5264#-:-MdlrFpI8nJE6CcNwe5I:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever)

**Pull request merged**
