### PR TITLE
[webgl] Build tfjs-backend-webgl with Bazel

### PR DESCRIPTION
**Pull request by mattsoulanille**
Build and test tfjs-backend-webgl with Bazel. This PR reintroduces changes that were reverted in #5476 and applies #5425 on top of them, fixing the issue where webgl tests ran on the cpu instead of in the webgl backend.

This PR is a work in progress. Some tests are still failing and the local tests must be run with ibazel or the browser never runs them.

Testing with Bazel causes the tests in #5632 to run again, but the tests appear to be broken. This PR disables them so they can be fixed independently of migrating WebGL to Bazel.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5562)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
tfjs-converter tests are failing (?)
```
Traceback (most recent call last):
  File "test_pip_package.py", line 30, in <module>
    import tensorflow.compat.v2 as tf
  File "/tmp/tmp.G99DSuz1UU/lib/python2.7/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/tmp/tmp.G99DSuz1UU/lib/python2.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
ImportError: No module named tools
```

**Comment by mattsoulanille** [comment]
Adding @lina128 as well since @ahmedsabie wrote many of the initial commits of this PR.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5562)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @mattsoulanille)

___
*[package.json, line 24 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5562#-Mk3xw24CBKpSEQ6C3VW:-Mk3xw24CBKpSEQ6C3VX:b-pux2uu) ([raw file](https://github.com/tensorflow/tfjs/blob/c15dac0aa2a54ba711ecaa63baad23a3dfb38c5c/package.json#L24)):*
> ```
> 0.0.5
> ```
0.0.6
___
*[tfjs-backend-webgl/BUILD.bazel, line 28 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5562#-Mk3yiEkCdlntWhRhtyT:-Mk3yiEkCdlntWhRhtyU:b7jinbl) ([raw file](https://github.com/tensorflow/tfjs/blob/c15dac0aa2a54ba711ecaa63baad23a3dfb38c5c/tfjs-backend-webgl/BUILD.bazel#L28)):*
> ```Starlark
>     entry_point = "//tfjs-backend-webgl/src:index.ts",
>     external = [
>         "node-fetch",
> ```

Why does it need node-fetch?
___
*[tfjs-backend-webgl/BUILD.bazel, line 29 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5562#-Mk3yy3N5jRpQ-a7ySTV:-Mk3yy3N5jRpQ-a7ySTW:bgep4m2) ([raw file](https://github.com/tensorflow/tfjs/blob/c15dac0aa2a54ba711ecaa63baad23a3dfb38c5c/tfjs-backend-webgl/BUILD.bazel#L29)):*
> ```
> util
> ```
Why does it need util?
___
*[tfjs-backend-webgl/BUILD.bazel, line 31 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5562#-Mk3yu0s1b_PDk7aNyuX:-Mk3yu0s1b_PDk7aNyuY:bhjr48) ([raw file](https://github.com/tensorflow/tfjs/blob/c15dac0aa2a54ba711ecaa63baad23a3dfb38c5c/tfjs-backend-webgl/BUILD.bazel#L31)):*
> ```
> @tensorflow/tfjs-core"
> ```
Why does it need tfjs-core?

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5562)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[package.json, line 24 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5562#-Mk3xw24CBKpSEQ6C3VW:-Mk9juRH1vKhIUR1fCuo:bjq5ydv) ([raw file](https://github.com/tensorflow/tfjs/blob/c15dac0aa2a54ba711ecaa63baad23a3dfb38c5c/package.json#L24)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> 0.0.5
> ```
0.0.6
</blockquote></details>

Nice catch! @types/webgl2 was added to the root package.json before that fix was written.
___
*[tfjs-backend-webgl/BUILD.bazel, line 28 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5562#-Mk3yiEkCdlntWhRhtyT:-Mk9o8ml8icLdvTn2A9a:bx8vgk8) ([raw file](https://github.com/tensorflow/tfjs/blob/c15dac0aa2a54ba711ecaa63baad23a3dfb38c5c/tfjs-backend-webgl/BUILD.bazel#L28)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Why does it need node-fetch?
</blockquote></details>

I don't think we actually do. Removed.
___
*[tfjs-backend-webgl/BUILD.bazel, line 29 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5562#-Mk3yy3N5jRpQ-a7ySTV:-Mk9oBHQ-cuEIv7aCYFN:b-2den1) ([raw file](https://github.com/tensorflow/tfjs/blob/c15dac0aa2a54ba711ecaa63baad23a3dfb38c5c/tfjs-backend-webgl/BUILD.bazel#L29)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> util
> ```
Why does it need util?
</blockquote></details>

I don't think we do. Removed.
___
*[tfjs-backend-webgl/BUILD.bazel, line 31 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5562#-Mk3yu0s1b_PDk7aNyuX:-Mk9nsXc5J7udf_W_pi8:buuor1m) ([raw file](https://github.com/tensorflow/tfjs/blob/c15dac0aa2a54ba711ecaa63baad23a3dfb38c5c/tfjs-backend-webgl/BUILD.bazel#L31)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> @tensorflow/tfjs-core"
> ```
Why does it need tfjs-core?
</blockquote></details>

It's [listed in the original karma file](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/rollup.config.js#L84). I think it's necessary to make sure this bundle doesn't also include all of `@tensorflow/tfjs-core`, since it import several things from core.


I took another look at the original rollup file, and it looks like the [node bundle](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/rollup.config.js#L113) and the [browser bundles](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/rollup.config.js#L84) have different externs. Do you know why that is?

**Review by lina128 — APPROVED** [review]
Thank you Matt!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5562#-:-MkDSVZB6H9WGxKv8kP-:b-t3m4wf)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @mattsoulanille)

___
*[tfjs-backend-webgl/BUILD.bazel, line 31 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5562#-Mk3yu0s1b_PDk7aNyuX:-MkDSClx-MICCwJos5wh:bpmo0yd) ([raw file](https://github.com/tensorflow/tfjs/blob/c15dac0aa2a54ba711ecaa63baad23a3dfb38c5c/tfjs-backend-webgl/BUILD.bazel#L31)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

It's [listed in the original karma file](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/rollup.config.js#L84). I think it's necessary to make sure this bundle doesn't also include all of `@tensorflow/tfjs-core`, since it import several things from core.


I took another look at the original rollup file, and it looks like the [node bundle](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/rollup.config.js#L113) and the [browser bundles](https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/rollup.config.js#L84) have different externs. Do you know why that is?
</blockquote></details>

Ah, right. For the node bundle, maybe it doesn't care size, so it just include in the bundle as oppose to external?

**Pull request merged**
