### PR TITLE
Update karma-browserstack-launcher to 1.6.0

### PR DESCRIPTION
**Pull request by mattsoulanille**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4300)

### CODE REVIEW

**Review by tafsiri — APPROVED** [review]
LGTM thanks Matt! I just added Na for visibility. Ping me on chat with the results of the nightly run but this looks pretty good.

> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4300#-:-MN--4h7BqnG5oroF2l3:b-dgxu6)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @tafsiri)

**Comment by mattsoulanille** [comment]
Thanks! I had to update the test cloudbuild files for nightly. Sent you the nightly cloudbuild run on chat.

**Review by tafsiri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4300)* status: 0 of 1 approvals obtained (waiting on @lina128 and @mattsoulanille)

___
*[tfjs-core/karma.conf.js, line 103 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4300#-MN-5VUV-eS6Fil9Ct4y:-MN-5VUV-eS6Fil9Ct4z:b-vekqt) ([raw file](https://github.com/tensorflow/tfjs/blob/4971dd4350e7791bc09b9e29649b79a4c3817479/tfjs-core/karma.conf.js#L103)):*
> ```JavaScript
>     ...extraConfig,
>     browsers: ['Chrome'],
>     port: 9896,
> ```

this port setting should be moved to the browserstackConfig section. The webworkerConfig sets its own port which is also hard coded in the test. See https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/worker_test.ts#L31 for how it is used. 

This suggests to me that we should move all of these higher up (into the browserstackConfig object or devConfig object if there) so that they can be overridden where necessary.

**Comment by mattsoulanille** [comment]
That makes sense. I forgot that webworker tests need to make an http request to launch the webworker. I've moved 'port' to 'browserstackConfig' wherever 'browserstackConfig' is present. If you just think this should be done in core, we can revert 9219053.

[Nightly run](https://console.cloud.google.com/cloud-build/builds/53bd5e80-928d-4431-8e77-09d3d3597979?project=834911136599)

**Review by tafsiri — APPROVED** [review]
Great. LGTM

> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4300#-:-MN-PiddD2VoPruDRhUk:b-43rb0y)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @mattsoulanille)

**Review by lina128 — COMMENTED** [review]
Looks great! Thank you Matt!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4300#-:-MN-kORv5YqOh2GR2jKZ:bc24d17)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @mattsoulanille)

**Pull request merged**
