### PR TITLE
[webgpu] Fix access mode for storage address space

### PR DESCRIPTION
**Pull request by haoyunfeix**
BUG
Due to WGSL Spec(https://www.w3.org/TR/WGSL/#address-space), storage
address space only supported read_write and read access modes.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6607)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
@qjia7 @xhcao @axinging @gyagp PTAL

**Review by gyagp — APPROVED** [review]
LGTM

**Review by qjia7 — APPROVED** [review]
LGTM, thanks.

Here https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgpu/src/matmul_packed_webgpu.ts#L180 you missed one to change `let` -> `const` in your last PR. Can you add it in this PR too?

**Comment by haoyunfeix** [comment]
@qjia7 Done.PTAL

**Pull request merged**
