### PR TITLE
Add a Bazel test_suite to organize tests

### PR DESCRIPTION
**Pull request by mattsoulanille**
Create a test_suite target named `tests` in each package and a test_suite in the root of the repository that runs all the tests for all the Bazel packages. WebGPU is excluded at the moment because it is in alpha.

Running `yarn test` at the root of the repository will run the tests.

This target is just for developer convenience.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6550)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
@pyu10055 PTAL when you get a chance. Thanks!

**Comment by mattsoulanille** [comment]
Reassigning reviewers since Ping is busy.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6550)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn and @mattsoulanille)

___
*[`tfjs-core/package.json` line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6550#-N5GRrLs0d5__zYXxuza:-N5GRrLs0d5__zYXxuzb:b-f4fg9u) ([raw file](https://github.com/tensorflow/tfjs/blob/878bf3ac6f9a995b9e9449ea61e901b5669d31eb/tfjs-core/package.json#L37)):*
> ```JSON
>     "coverage": "bazel coverage :tfjs-core_node_test",
>     "test": "bazel test :tests --test_output=all",
>     "test-dev": "ibazel test :tfjs-core_test :test_snippets_test :tfjs-core_node_test tfjs-core_async_backends_test --test_output=all",
> ```

should the dev and browser targets have their own test suite?

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6550)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfjs-core/package.json` line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6550#-N5GRrLs0d5__zYXxuza:-N5GUQp67Bk_uCZzSb0z:b-v9r6of) ([raw file](https://github.com/tensorflow/tfjs/blob/878bf3ac6f9a995b9e9449ea61e901b5669d31eb/tfjs-core/package.json#L37)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should the dev and browser targets have their own test suite?
</blockquote></details>

Dev should use the main test suite, and browsers probably don't need one.

**Pull request merged**
