### PR TITLE
[layers] allow conversion of weight only keras H5 file that lacks keras version info

### PR DESCRIPTION
**Pull request by pyu10055**
fixed https://github.com/tensorflow/tfjs/issues/7349

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7359)

### CODE REVIEW

**Review by Linchenn — APPROVED** [review]

**Review by santimirandarp — COMMENTED** [review]
sgtm

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7359#-:-NNuZQqu0MVtJ1vhf3KZ:bb7ohn6)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille)

**Review by mattsoulanille — APPROVED** [review]

**Comment by santimirandarp** [comment]
I added this changes manually to my local copy, I am not sure if this would run, because of this line (line 100):

```python
  keras_version = as_text(h5file.attrs['keras_version'])
```
Even though the previous error is caught, this one wont, because "keras_version" does not exist maybe? (sorry I  don't know much python). But I added the previous code and it still fails unless I hard code `keras_version="2.0"`.

**Comment by pyu10055** [comment]
> ```python
> as_text(h5file.attrs['keras_version'])
> ```

The code originally fails here, I have tested this change, the weight file can now be converted. 
Please be sure you have apply the change locally, and if it still errors out, please share the stack trace here.

**Comment by santimirandarp** [comment]
Oops. I'll test soon and report back! Thank you

**Pull request merged**
