### PR TITLE
Add Kernel SparseFillEmptyRows for CPU and WebGL backend

### PR DESCRIPTION
**Pull request by ahmedsabie**
ref #4838
TensorFlow python version is defined  [here](https://www.tensorflow.org/api_docs/python/tf/sparse/fill_empty_rows)
c++ kernel definition is  [here](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/core/kernels/sparse_fill_empty_rows_op.cc)

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4992)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you Ahmed, congrats on the first PR.
Please add reference for original issue in the PR description.
The PR looks great, just couple minor comments.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4992#-:-MZFJ4Jb3XWVAwLvK6Z1:b-y2bu2a)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFBwzr-u3oGWDF-ltS:-MZFBwzr-u3oGWDF-ltT:b-4qq80v) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts#L24)):*
> ```XML
>     values: number[], denseShape: number[], defaultValue: number):
>     [TypedArray, number[], number[], boolean[], number[]] {
>   const N = indicesShape[0];
> ```

in typescript, variable starts with lowercase, you can call it `indicesCount`
___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFDcgG-GdhbupAnqJK:-MZFDcgG-GdhbupAnqJL:bk7zqlx) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts#L39)):*
> ```XML
>     const outputIndices =
>         util.getArrayFromDType(indicesDType, 0 * rank) as TypedArray;
>     const outputValues: number[] = [];
> ```

You should treat the outputValue the same way as outputIndices, create a TypeArray with the same dtype as inputValue, instead of forcing it as Int32Array.
___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts, line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFEj3f8lcE-Vk_SGMB:-MZFEj3f8lcE-Vk_SGMC:bw8crmi) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts#L51)):*
> ```XML
>   for (let i = 0; i < N; ++i) {
>     // indices is a 2d tensor with shape of [N, rank]
>     const row = indices[i * rank + 0];
> ```

no need to add 0 here.
___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFGxdk4Ia4AlS6yzhg:-MZFGxdk4Ia4AlS6yzhh:bfpvdam) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts#L101)):*
> ```XML
>     for (let i = 0; i < N; ++i) {
>       // indices is a 2d tensor with shape of [N, rank]
>       const row = indices[i * rank + 0];
> ```

+ 0 is not needed
___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts, line 122 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFH7_UBMRFIpOZQXHR:-MZFH7_UBMRFIpOZQXHS:bao27lv) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts#L122)):*
> ```XML
>         // Just need to set the row index in the right location.
>         // outputIndices is a 2d tensor with shape of [N, rank]
> ```

remove the empty line here
___
*[tfjs-core/src/kernel_names.ts, line 773 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZF9puO2fHR1yvg4s5j:-MZF9puPDtdyUoq73erS:b-q9r1tg) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/kernel_names.ts#L773)):*
> ```XML
>     Pick<NamedTensorInfoMap, 'indices'|'values'|'denseShape'>;
> export interface SparseFillEmptyRowsAttrs {
>   defaultValue: number;
> ```

defaultValue should also be part of the input. https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/core/ops/sparse_ops.cc#L598
___
*[tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts, line 72 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFAmHB3_4iCnc0jXec:-MZFAmHB3_4iCnc0jXed:b-djotuy) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts#L72)):*
> ```
>  *     0] for rows missing from the input sparse tensor. output indices: 2-D.
>  *     the indices of the filled sparse tensor.
> ```
remove the output indices part, since it has been explained in the return section
___
*[tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts, line 108 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFB9Kk6XqrOHFSjghs:-MZFB9Kk6XqrOHFSjght:b79pm08) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts#L108)):*
> ```XML
>     denseShape: $denseShape
>   };
>   const attrs: SparseFillEmptyRowsAttrs = {defaultValue};
> ```

move the defaultValue to inputs interface to be more aligned with TF definition.

**Review by lina128 — COMMENTED** [review]
Great job Ahmed! And congratulations on your first PR!
Can you update the PR title to `Add Kernel SparseFillEmptyRowsConfig for CPU and WebGL backend`.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4992#-:-MZFRx-UAr2pZnz0wS64:b-yax3ik)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFV5yFAlsqKmoVAUmN:-MZFV5yFAlsqKmoVAUmO:b7cr7rt) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows.ts#L47)):*
> ```XML
>   const $indices = backend.data.get(indices.dataId).values as TypedArray;
>   const $values =
>       Array.from(backend.data.get(values.dataId).values as TypedArray);
> ```

Do you need Array.from? 
___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFDcgG-GdhbupAnqJK:-MZFdGSD8QtojbEQv92s:b32v57) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts#L39)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

You should treat the outputValue the same way as outputIndices, create a TypeArray with the same dtype as inputValue, instead of forcing it as Int32Array.
</blockquote></details>

+1
___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts, line 95 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFfgF4ETpE8K7p0D8d:-MZFfgF4ETpE8K7p0D8e:b-artiky) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts#L95)):*
> ```XML
>     const outputIndices =
>         util.getArrayFromDType(indicesDType, nFull * rank) as TypedArray;
>     const outputValues: number[] = new Array(nFull);
> ```

Same as above, use TypedArray.
___
*[tfjs-backend-webgl/src/kernels/SparseFillEmptyRows.ts, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFgRvpEY1CnyfHqiMf:-MZFgRvpEY1CnyfHqiMg:b-3y516m) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-webgl/src/kernels/SparseFillEmptyRows.ts#L46)):*
> ```XML
>   const $indices = backend.readSync(indices.dataId).values as TypedArray;
>   const $values =
>       Array.from(backend.readSync(values.dataId).values as TypedArray);
> ```

No need to use Array.from for values.
___
*[tfjs-core/src/kernel_names.ts, line 773 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZF9puO2fHR1yvg4s5j:-MZFgXeS5cUj005SUev-:bhb3unz) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/kernel_names.ts#L773)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

defaultValue should also be part of the input. https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/core/ops/sparse_ops.cc#L598
</blockquote></details>

If it's not a tensor, shouldn't it be attr? See nonMaxSuppression for example: https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/kernel_names.ts#L598

I think engine expect inputs to be NamedTensorMap
___
*[tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts, line 108 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFB9Kk6XqrOHFSjghs:-MZF_yJTCUZEC3yXqrO3:b-me2wfb) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts#L108)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

move the defaultValue to inputs interface to be more aligned with TF definition.
</blockquote></details>

If defaultValue is not tensor, it should be attribute, isn't that our convention?

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4992)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts, line 108 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFB9Kk6XqrOHFSjghs:-MZFlYcq0cBAotVXFrsu:b-egt0sp) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts#L108)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

If defaultValue is not tensor, it should be attribute, isn't that our convention?
</blockquote></details>

The defaultValue is part of the inputs (a scalar tensor) in TF definition, when we make it into number in the API, it would force graph executor to call readSync, which is the main problem for WebGPU issues.
If it is attribute in the Graph, then the value won't need readSync.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4992)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts, line 108 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFB9Kk6XqrOHFSjghs:-MZFopDz9_tyU0rTbmbg:b1ltq9u) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts#L108)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

The defaultValue is part of the inputs (a scalar tensor) in TF definition, when we make it into number in the API, it would force graph executor to call readSync, which is the main problem for WebGPU issues.
If it is attribute in the Graph, then the value won't need readSync.
</blockquote></details>

Changing the convention in this single op doesn't help solve that problem. Do we have a plan to fix this issue for all impacted ops?

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4992)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFBwzr-u3oGWDF-ltS:-MZIecCGBN8KRWQaacVC:b-k73z76) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts#L24)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

in typescript, variable starts with lowercase, you can call it `indicesCount`
</blockquote></details>

thanks
___
*[tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts, line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFEj3f8lcE-Vk_SGMB:-MZIefSP6WQ1tCU999Lx:bujqfi5) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-backend-cpu/src/kernels/SparseFillEmptyRows_impl.ts#L51)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

no need to add 0 here.
</blockquote></details>

resolved
___
*[tfjs-core/src/kernel_names.ts, line 773 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZF9puO2fHR1yvg4s5j:-MZIepcI1SkLbrm3ie9-:bokq1ne) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/kernel_names.ts#L773)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

If it's not a tensor, shouldn't it be attr? See nonMaxSuppression for example: https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/kernel_names.ts#L598

I think engine expect inputs to be NamedTensorMap
</blockquote></details>

any inputs to the node is a tensor in the TF kernel definition. In this case the default value is a scalar tensor.
___
*[tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts, line 108 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFB9Kk6XqrOHFSjghs:-MZIdIlx6hktANJEBD6O:b8canqj) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts#L108)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Changing the convention in this single op doesn't help solve that problem. Do we have a plan to fix this issue for all impacted ops?
</blockquote></details>

I believe one of the modularization goals is to tie our kernels to the TF op definition. I think we will need to fix other op APIs that deviate from TF, we should allow all kernel inputs to be tensors. I know it is a large set of ops we need to fix, but I think it is the right direction.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4992)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts, line 108 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4992#-MZFB9Kk6XqrOHFSjghs:-MZJASbH3gJVPr8XArig:b4bs5nr) ([raw file](https://github.com/tensorflow/tfjs/blob/5f344ebfe2a7a837169b31cbeb50c768dcef7a8f/tfjs-core/src/ops/sparse/sparse_fill_empty_rows.ts#L108)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I believe one of the modularization goals is to tie our kernels to the TF op definition. I think we will need to fix other op APIs that deviate from TF, we should allow all kernel inputs to be tensors. I know it is a large set of ops we need to fix, but I think it is the right direction.
</blockquote></details>

Got it. Good to know we are going to fix this.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4992)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4992#-:-MZK-La1ARAgBBNJSToa:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie)

**Pull request merged**
