### PR TITLE
[browserstack benchmark tool] Move CodeSnippet from backend to frontend

### PR DESCRIPTION
**Pull request by Linchenn**
This PR moves CodeSnippet to benchmark from backend to frontend, and, let the frontend to pass the CodeSnippet to the backend, which allows frontend to customize the CodeSnippet, instead of fix CodeSnippet at backend. 

Previously, CodeSnippet is hard-coded in benchmark_model.js at backend, which will be executed by BrowserStack instances. 

 **After this PR, we could add UI elements to enable users to edit codeSnippet (at frontend)**.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6738)

### CODE REVIEW

**Comment by Linchenn** [comment]
@pyu10055 Thank you for the suggestion! It is updated and is ready for reviewing.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6738)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Review by pyu10055 — APPROVED** [review]
thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6738#-:-N97mXXqAY5aXahGtqWB:bd5l6mr)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Review by lina128 — APPROVED** [review]
Thank you for the refactoring! Looks great!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6738#-:-N9E3JO4DkqKHQjX42o-:b-cesubn)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
