### PR TITLE
[webgpu] Calculating coords use i32 to avoid precision issue

### PR DESCRIPTION
**Pull request by axinging**
For general cases, we can cast i32 to f32. However, when calculating coords, if the coords is too big,
cast may result in precission issue. Now dot supports vecN<i32> and vecN<f32> as input (https://github.com/gpuweb/gpuweb/issues/2231), we should use vecN<i32> directly.

This also fix conformance fail of model benchmark=posenet&inputSize=1024&architecture=ResNet50.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5806)

### CODE REVIEW

**Comment by gyagp** [comment]
dot(vecN<i32>, vecN<i32>) has been implemented in Tint, so we can directly use it. 
For daily test, we can live with failure for a period of time, until the feature is available in Chrome Dev.

**Comment by axinging** [comment]
@gyagp  @qjia7 @xhcao @haoyunfeix , ptal.

**Review by qjia7 — APPROVED** [review]
LGTM

**Comment by qjia7** [comment]
@mattsoulanille @lina128 @pyu10055 Please help merge it, thanks.

**Pull request merged**
