### PR TITLE
Update tfjs-node to 1.2.9.

### PR DESCRIPTION
**Pull request by kangyizhang**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/1983)

### CODE REVIEW

**Comment by nsthorat** [comment]
Looks like we need to update the kernels from this PR: https://github.com/tensorflow/tfjs/pull/1829

cc @dsmilkov

**Comment by kangyizhang** [comment]
@nsthorat yes I'm working on it. Seems like it needs two part of changes:
1. add default value for mask params
2. normalization of out of range begin/end and negative strides makes TF C api shows different result. Filed https://github.com/tensorflow/tfjs/issues/1984

**Comment by dsmilkov** [comment]
I just pushed to this branch and made all tests to pass - you should be good to go. For the diff see commit: https://github.com/tensorflow/tfjs/pull/1983/commits/62903237bd5c86dee3c4ed112393854f6ab7d1c7

**Comment by kangyizhang** [comment]
@googlebot I consent

**Comment by kangyizhang** [comment]
@googlebot I consent.

**Pull request merged**
