### PR TITLE
Add broadcast args

### PR DESCRIPTION
**Pull request by drubinstein**
As per the issue I raised #4624, I added support for [BroadcastArgs](https://www.tensorflow.org/api_docs/python/tf/raw_ops/BroadcastArgs?hl=ca) based on the XLA implementation in [tensorflow](https://github.com/tensorflow/tensorflow/blob/dec8e0b11f4f87693b67e125e67dfbc68d26c205/tensorflow/compiler/tf2xla/kernels/bcast_ops.cc#L32) which eventually calls [Bcast](https://github.com/tensorflow/tensorflow/blob/dec8e0b11f4f87693b67e125e67dfbc68d26c205/tensorflow/core/util/bcast.h#L135). The result should match to what Bcast sets as _output.

To match the tensorflow documentation, this function takes two tensors and returns a tensor.

The integration tests were based on me running the following in python:
```
import tensorflow as tf
tf.raw_ops.BroadcastArgs(s0=[1,1], s1=[1,1], name=None)
tf.raw_ops.BroadcastArgs(s0=[1,1], s1=[4,2], name=None)
tf.raw_ops.BroadcastArgs(s0=[1,6], s1=[3,1], name=None)
tf.raw_ops.BroadcastArgs(s0=[1,6], s1=[3,1,1,1], name=None)
tf.raw_ops.BroadcastArgs(s0=[1,6,-1], s1=[3,1,1,1], name=None)
tf.raw_ops.BroadcastArgs(s0=[1,2], s1=[1,3], name=None)
tf.raw_ops.BroadcastArgs(s0=[[1,1],[1,1]], s1=[[1,1],[1,1]], name=None)
``` 

I have one performance concern that I'd like guidance on if possible. I'm making heavy use of `arraySync` inside this function which I fear may lead to stalls during runtime. Are there any recommendations to fix this issue?

Thanks for the review.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4636)

### CODE REVIEW

**Comment by drubinstein** [comment]
@googlebot I signed it! and we'll verify it.

**Comment by drubinstein** [comment]
@lina128 How do I go about getting permissions to see the cloud build logs so I can fix the errors.

**Review by lina128 — COMMENTED** [review]
You should be able to access the Cloudbuild logs after joining our [discussion](https://groups.google.com/a/tensorflow.org/g/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/g/tfjs-announce) Google group.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4636#-:-MSjB8967hZe9f1_RDBq:b-lemvgw)* status: 0 of 1 approvals obtained

**Comment by drubinstein** [comment]
Thanks. I can now view it.

**Comment by drubinstein** [comment]
So I'm having trouble finding a way to remove the `arraySync` calls from the new op I'm adding. Any advice? I'm not sure if it's okay for me to make the op async. If it is, I can convert to that.

**Review by lina128 — COMMENTED** [review]
Hi @drubinstein thank you for the contribution! I left some comments below.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4636#-:-MTMmb8nC9kY6ajt7RA8:b5guae)* status: 0 of 1 approvals obtained (waiting on @drubinstein)

___
*[tfjs-converter/python/tensorflowjs/op_list/transformation.json, line 234 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MTMmngJ9m1FwGnVUsYm:-MTMmngJ9m1FwGnVUsYn:bvrunkp) ([raw file](https://github.com/tensorflow/tfjs/blob/9d0f66c2be0ae41fd3fbc1bd0460b1dc42d4cec1/tfjs-converter/python/tensorflowjs/op_list/transformation.json#L234)):*
> ```JSON
>       {
>         "start": 0,
>         "name": "shape1",
> ```

Use name "s0", to be consistent with TF op pbtxt: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt
___
*[tfjs-converter/python/tensorflowjs/op_list/transformation.json, line 239 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MTMmyW68azrGIDw2Zlf:-MTMmyW68azrGIDw2Zlg:b-dq9gg7) ([raw file](https://github.com/tensorflow/tfjs/blob/9d0f66c2be0ae41fd3fbc1bd0460b1dc42d4cec1/tfjs-converter/python/tensorflowjs/op_list/transformation.json#L239)):*
> ```JSON
>       {
>         "start": 1,
>         "name": "shape2",
> ```

Use name "s1"
___
*[tfjs-converter/src/operations/executors/transformation_executor.ts, line 109 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MTMoylb9BgAntglXRmN:-MTMoylb9BgAntglXRmO:b32wv6) ([raw file](https://github.com/tensorflow/tfjs/blob/9d0f66c2be0ae41fd3fbc1bd0460b1dc42d4cec1/tfjs-converter/src/operations/executors/transformation_executor.ts#L109)):*
> ```XML
>         case 'BroadcastArgs': {
>           return [tfOps.broadcastArgs(
>               getParamValue('shape1', node, tensorMap, context) as Tensor,
> ```

s0
___
*[tfjs-converter/src/operations/executors/transformation_executor.ts, line 110 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MTMozQK1R4mhr-jq_Ph:-MTMozQK1R4mhr-jq_Pi:b32wv7) ([raw file](https://github.com/tensorflow/tfjs/blob/9d0f66c2be0ae41fd3fbc1bd0460b1dc42d4cec1/tfjs-converter/src/operations/executors/transformation_executor.ts#L110)):*
> ```XML
>           return [tfOps.broadcastArgs(
>               getParamValue('shape1', node, tensorMap, context) as Tensor,
>               getParamValue('shape2', node, tensorMap, context) as Tensor)];
> ```

s1
___
*[tfjs-converter/src/operations/op_list/transformation.ts, line 144 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MTMpq4ACK6_SvTBfBan:-MTMpq4ACK6_SvTBfBao:b7ye8ld) ([raw file](https://github.com/tensorflow/tfjs/blob/9d0f66c2be0ae41fd3fbc1bd0460b1dc42d4cec1/tfjs-converter/src/operations/op_list/transformation.ts#L144)):*
> ```XML
>     'category': 'transformation',
>     'inputs': [
>       {'start': 0, 'name': 'shape1', 'type': 'tensor'},
> ```

shape1 -> s0
___
*[tfjs-converter/src/operations/op_list/transformation.ts, line 145 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MTMpqp92AH0-UedJYDp:-MTMpqp92AH0-UedJYDq:bmmsitf) ([raw file](https://github.com/tensorflow/tfjs/blob/9d0f66c2be0ae41fd3fbc1bd0460b1dc42d4cec1/tfjs-converter/src/operations/op_list/transformation.ts#L145)):*
> ```XML
>     'inputs': [
>       {'start': 0, 'name': 'shape1', 'type': 'tensor'},
>       {'start': 1, 'name': 'shape2', 'type': 'tensor'},
> ```

shape2 -> s1
___
*[tfjs-core/src/kernel_names.ts, line 148 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MTMpwMR4pZ6WYuBQ0RV:-MTMpwMR4pZ6WYuBQ0RW:bi0ecye) ([raw file](https://github.com/tensorflow/tfjs/blob/9d0f66c2be0ae41fd3fbc1bd0460b1dc42d4cec1/tfjs-core/src/kernel_names.ts#L148)):*
> ```XML
> 
> export const BroadcastArgs = 'BroadcastArgs';
> export type BroadcastArgsInputs = Pick<NamedTensorInfoMap, 'shape1'|'shape2'>;
> ```

's0'|'s1'
___
*[tfjs-core/src/ops/broadcast_args.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MTMq15p4Nai7ebflR6V:-MTMq15p4Nai7ebflR6W:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs/blob/9d0f66c2be0ae41fd3fbc1bd0460b1dc42d4cec1/tfjs-core/src/ops/broadcast_args.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2020 Google LLC. All Rights Reserved.
> ```

2021
___
*[tfjs-core/src/ops/broadcast_args.ts, line 41 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MTMqpxI2nZUn4pTPxWg:-MTMqpxJ8hmKx4J5G2Rs:b-m8yepv) ([raw file](https://github.com/tensorflow/tfjs/blob/9d0f66c2be0ae41fd3fbc1bd0460b1dc42d4cec1/tfjs-core/src/ops/broadcast_args.ts#L41)):*
> ```XML
>  * @doc {heading: 'Tensors', subheading: 'Transformations'}
>  */
> function broadcastArgs_<R extends Rank>(
> ```

For the implementation, I wonder can you use assertAndGetBroadcastShape method from broadcast_util.ts?

**Comment by drubinstein** [comment]
Thanks for the review @lina128 . Good call on using `assertAndGetBroadcastShape`. That implements the same logic I reimplemented. I changed what I wrote to use it. Unfortunately, it expects `number[]` as an argument which would require the op to use `arraySync` or `dataSync` which is not allowed in a collection of tests. Not sure what the policy of marking ops as async here, but would that be okay?

**Review by lina128 — COMMENTED** [review]
Hi @drubinstein , in this case, can you move the implementation to kernels of cpu/webgl/wasm backends? The data access in kernels is synchronous.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4636#-:-MUodcFtEpn3LIqSH4DF:bao5r03)* status: 0 of 1 approvals obtained (waiting on @drubinstein)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4636)* status: 0 of 1 approvals obtained (waiting on @drubinstein)

___
*[tfjs-backend-cpu/src/kernels/BroadcastArgs.ts, line 3 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MgwB0OrBUZlzdB12G2q:-MgwB0OrBUZlzdB12G2r:b-c42xa4) ([raw file](https://github.com/tensorflow/tfjs/blob/0c19eb454a213874a4458567166dcacff3a251d7/tfjs-backend-cpu/src/kernels/BroadcastArgs.ts#L3)):*
> ```
> 2020
> ```
2021
___
*[tfjs-core/src/ops/broadcast_args_test.ts, line 3 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MgwBRnrC77HRqE4taDb:-MgwBRnrC77HRqE4taDc:b9tf8u3) ([raw file](https://github.com/tensorflow/tfjs/blob/0c19eb454a213874a4458567166dcacff3a251d7/tfjs-core/src/ops/broadcast_args_test.ts#L3)):*
> ```
> 2018
> ```
2021
___
*[tfjs-node/src/kernels/BroadcastArgs.ts, line 3 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4636#-MgwFHlm89y706yxxyZM:-MgwFHlm89y706yxxyZN:bi64k2q) ([raw file](https://github.com/tensorflow/tfjs/blob/0c19eb454a213874a4458567166dcacff3a251d7/tfjs-node/src/kernels/BroadcastArgs.ts#L3)):*
> ```
> 2020 
> ```
2021

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4636#-:-Mgxcn8y1aCvtdUyxfsL:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @drubinstein)

**Pull request merged**
