### PR TITLE
Bump version to 0.11.7

### PR DESCRIPTION
**Pull request by caisq**
Dependency versions:
tfjs-core: 0.11.6 --> 0.11.9
tfjs-layer: 0.6.6 --> 0.6.7
tfjs-converter: 0.4.1 --> 0.4.3

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/456)

### CODE REVIEW

**Comment by caisq** [comment]
This PR is not ready yet. I need to update tfjs-converter first.

**Comment by nsthorat** [comment]
Yep was just about to say that :)

**Comment by caisq** [comment]
Done. Ready now.

**Comment by nsthorat** [comment]
https://github.com/tensorflow/tfjs-converter/blob/master/package.json this still points to 0.11.8

**Comment by caisq** [comment]
Ah - good catch, @nsthorat . Sent out https://github.com/tensorflow/tfjs-converter/pull/159

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: :shipit: complete! 1 of 1 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/456#-:-LFVOwfD5Zza6ORWpmkO:b-jbsf8z)*

**Pull request merged**
