### PR TITLE
Add multiple device and model benchmarking capability and fix Firestore API key reference in cloudbuild

### PR DESCRIPTION
**Pull request by ClaireXP**
Refactored the code to allow pre-configured benchmark configs to include multiple models and multiple backends. Also fixed the Firestore API key in Pantheon and updated the reference to the key in the cloudbuild file.

Ready for review! @lina128 @mattsoulanille @keithlwill 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5391)

### CODE REVIEW

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5391)* status: 0 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 173 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5391#-MfinOmQ-LTzJ-ijHQ4y:-MfinOmQ-LTzJ-ijHQ4z:bypzi84) ([raw file](https://github.com/tensorflow/tfjs/blob/58f657013a09523a5317aac3ef2d7ac50ee794ca/e2e/benchmarks/browserstack-benchmark/app.js#L173)):*
> ```
> if (cliArgs?.firestore) pushToFirestore(fulfilled);
> ```
Nice idea factoring this out
___
*[e2e/benchmarks/browserstack-benchmark/cloudbuild.yml, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5391#-MfinmeX1ej2ls2wkYlk:-MfinmeX1ej2ls2wkYll:bbftc14) ([raw file](https://github.com/tensorflow/tfjs/blob/58f657013a09523a5317aac3ef2d7ac50ee794ca/e2e/benchmarks/browserstack-benchmark/cloudbuild.yml#L26)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> availableSecrets:
>   secretManager:
>     versionName: projects/834911136599/secrets/FIREBASE_KEY/versions/latest
>     env: 'FIREBASE_KEY'
> ```
</details>

Can you describe this change in the PR's description? 
___
*[e2e/benchmarks/browserstack-benchmark/firestore.js, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5391#-MfioDeODvIObejbN9LC:-MfioDeODvIObejbN9LD:b-x73usq) ([raw file](https://github.com/tensorflow/tfjs/blob/58f657013a09523a5317aac3ef2d7ac50ee794ca/e2e/benchmarks/browserstack-benchmark/firestore.js#L49)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>       .then(() => {console.log('Signed into Firebase with anonymous account.')})
>       .catch((error) => {
>         console.log(`Error code: ${error.code}`);
>         throw `Error message: ${error.message}`;
> ```
</details>

If you're using an async function, you can use a try / catch block here instead of .then / .catch.
___
*[e2e/benchmarks/browserstack-benchmark/firestore.js, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mfio5kq1ozP7SKFFohi:-Mfio5kq1ozP7SKFFohj:b-60oimz) ([raw file](https://github.com/tensorflow/tfjs/blob/58f657013a09523a5317aac3ef2d7ac50ee794ca/e2e/benchmarks/browserstack-benchmark/firestore.js#L56)):*
> ```
>   db = firebase.firestore().collection('BenchmarkResults');
> ```
Since this is now assigned in an async function after awaiting something, it will be undefined at the time it's exported and may also be undefined at the time it's used (although this is unlikely since we only push after benchmarks are complete).

There isn't a good way to go from async back to synchronous code. One option is to have this async function return the database. Then, we can assign `db = runFirestore(...)`. The type of `db` will be `Promise<Collection>` (assuming Collection is the firestore collection), and to use `db`, you'll have to do `(await db).someDatabaseMethod()`.

That's not a great interface. Perhaps Firebase allows you to create the `db` object before authenticating, and we can do it outside of this function?

**Review by ClaireXP — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5391)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[e2e/benchmarks/browserstack-benchmark/cloudbuild.yml, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5391#-MfinmeX1ej2ls2wkYlk:-MfjK1ot3KtI9WEBkKk0:b-zhzsk1) ([raw file](https://github.com/tensorflow/tfjs/blob/58f657013a09523a5317aac3ef2d7ac50ee794ca/e2e/benchmarks/browserstack-benchmark/cloudbuild.yml#L26)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> availableSecrets:
>   secretManager:
>     versionName: projects/834911136599/secrets/FIREBASE_KEY/versions/latest
>     env: 'FIREBASE_KEY'
> ```
Can you describe this change in the PR's description? 
</blockquote></details>

Changed the PR title to be more descriptive.
___
*[e2e/benchmarks/browserstack-benchmark/firestore.js, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5391#-MfioDeODvIObejbN9LC:-MfjK0Yv3HkrNalUyD70:b-896fja) ([raw file](https://github.com/tensorflow/tfjs/blob/58f657013a09523a5317aac3ef2d7ac50ee794ca/e2e/benchmarks/browserstack-benchmark/firestore.js#L49)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>       .then(() => {console.log('Signed into Firebase with anonymous account.')})
>       .catch((error) => {
>         console.log(`Error code: ${error.code}`);
>         throw `Error message: ${error.message}`;
> ```
If you're using an async function, you can use a try / catch block here instead of .then / .catch.
</blockquote></details>

Done!
___
*[e2e/benchmarks/browserstack-benchmark/firestore.js, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mfio5kq1ozP7SKFFohi:-MfjIKod8_dWdvQc8Q18:b-c4ri1d) ([raw file](https://github.com/tensorflow/tfjs/blob/58f657013a09523a5317aac3ef2d7ac50ee794ca/e2e/benchmarks/browserstack-benchmark/firestore.js#L56)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>   db = firebase.firestore().collection('BenchmarkResults');
> ```
Since this is now assigned in an async function after awaiting something, it will be undefined at the time it's exported and may also be undefined at the time it's used (although this is unlikely since we only push after benchmarks are complete).

There isn't a good way to go from async back to synchronous code. One option is to have this async function return the database. Then, we can assign `db = runFirestore(...)`. The type of `db` will be `Promise<Collection>` (assuming Collection is the firestore collection), and to use `db`, you'll have to do `(await db).someDatabaseMethod()`.

That's not a great interface. Perhaps Firebase allows you to create the `db` object before authenticating, and we can do it outside of this function?
</blockquote></details>

Firebase was not happy when I tried to rearrange. Something I realized was that firestore was being authenticated even when I did not run the --firestore argument. To fix this, I thought the best approach would be to call the function in the main app.js in relation to the --firestore argument. That way the db creation could be awaited. I also refactored the tests to support this. Let me know if you have any comments or suggestions regarding this method!

**Review by lina128 — APPROVED** [review]
Great work, thank you @clairexp !

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5391#-:-MfnA1Hb4lD2duc9U6n_:bw63kll)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP and @mattsoulanille)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 180 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mfn8sLx2ADyRxEGpyM8:-Mfn8sLy0mZHEEwFKNlZ:b-7tpexa) ([raw file](https://github.com/tensorflow/tfjs/blob/3107fd724cf41649f48b167610e3caa02e96b373/e2e/benchmarks/browserstack-benchmark/app.js#L180)):*
> ```
> pushToFirestore(fulfilled);
> ```
Always surround code for conditions with curly braces.
```
if (...) {
   // even if it's one line.
}
```
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 322 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mfn9HtO9HmcoV7Evbfr:-Mfn9HtO9HmcoV7Evbfs:be7vbpg) ([raw file](https://github.com/tensorflow/tfjs/blob/3107fd724cf41649f48b167610e3caa02e96b373/e2e/benchmarks/browserstack-benchmark/app.js#L322)):*
> ```JavaScript
> }
> 
> /** Sets up the local or remote envirnment for benchmarking. */
> ```

typo: environment
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 325 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mfn9T5YBNWJqVUJS4bJ:-Mfn9T5YBNWJqVUJS4bK:b-ow0m7y) ([raw file](https://github.com/tensorflow/tfjs/blob/3107fd724cf41649f48b167610e3caa02e96b373/e2e/benchmarks/browserstack-benchmark/app.js#L325)):*
> ```
> db = await runFirestore(firebaseConfig);
> ```
curly braces
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 326 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mfn9Vkl26NJ76_HuBF4:-Mfn9Vkl26NJ76_HuBF5:b-7biemu) ([raw file](https://github.com/tensorflow/tfjs/blob/3107fd724cf41649f48b167610e3caa02e96b373/e2e/benchmarks/browserstack-benchmark/app.js#L326)):*
> ```
> runServer();
> ```
curly braces
___
*[e2e/benchmarks/browserstack-benchmark/firestore.js, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5391#-MfioDeODvIObejbN9LC:-Mfn9khPAmh_Hklmtl8x:bjy48c4) ([raw file](https://github.com/tensorflow/tfjs/blob/58f657013a09523a5317aac3ef2d7ac50ee794ca/e2e/benchmarks/browserstack-benchmark/firestore.js#L49)):*
<details><summary><i>Previously, ClaireXP (Claire) wrote…</i></summary><blockquote>

Done!
</blockquote></details>

Nice refactor. This removes a side effect.

**Review by ClaireXP — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5391)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP, @lina128, and @mattsoulanille)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 180 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mfn8sLx2ADyRxEGpyM8:-MfoVpvB78WS5o78DdXC:b5qpkbx) ([raw file](https://github.com/tensorflow/tfjs/blob/3107fd724cf41649f48b167610e3caa02e96b373/e2e/benchmarks/browserstack-benchmark/app.js#L180)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> pushToFirestore(fulfilled);
> ```
Always surround code for conditions with curly braces.
```
if (...) {
   // even if it's one line.
}
```
</blockquote></details>

Will do. Thanks for letting me know!
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 322 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mfn9HtO9HmcoV7Evbfr:-MfoVvsy6RFWBybGeD_y:b-886gsx) ([raw file](https://github.com/tensorflow/tfjs/blob/3107fd724cf41649f48b167610e3caa02e96b373/e2e/benchmarks/browserstack-benchmark/app.js#L322)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

typo: environment
</blockquote></details>

Fixed

**Review by mattsoulanille — APPROVED** [review]
LGTM with just a few nits remaining. Thanks!

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5391#-:-Mg6UsIr3Me9bqDpOdkF:b-nvqrea)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 325 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5391#-MfmysY_47IHZGiOrVVe:-MfmysY_47IHZGiOrVVf:bk23loz) ([raw file](https://github.com/tensorflow/tfjs/blob/3107fd724cf41649f48b167610e3caa02e96b373/e2e/benchmarks/browserstack-benchmark/app.js#L325)):*
> ```
>   if (cliArgs.firestore) db = await runFirestore(firebaseConfig);
> ```
This looks like a good solution to the async firestore setup problem. We may want to rename `runFirestore` to `setupFirestore` or something else.
___
*[e2e/benchmarks/browserstack-benchmark/firestore.js, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mfio5kq1ozP7SKFFohi:-Mg6TkkW4rV33D_soqOV:bcckl18) ([raw file](https://github.com/tensorflow/tfjs/blob/58f657013a09523a5317aac3ef2d7ac50ee794ca/e2e/benchmarks/browserstack-benchmark/firestore.js#L56)):*
<details><summary><i>Previously, ClaireXP (Claire) wrote…</i></summary><blockquote>

Firebase was not happy when I tried to rearrange. Something I realized was that firestore was being authenticated even when I did not run the --firestore argument. To fix this, I thought the best approach would be to call the function in the main app.js in relation to the --firestore argument. That way the db creation could be awaited. I also refactored the tests to support this. Let me know if you have any comments or suggestions regarding this method!
</blockquote></details>

Looks like a good solution!

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5391)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 113 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mg6dYTYC4MiJnUzUsVE:-Mg6dYTYC4MiJnUzUsVF:bwaxqu8) ([raw file](https://github.com/tensorflow/tfjs/blob/fd18e01f34950f4a0f96da21819f183e408ed9cb/e2e/benchmarks/browserstack-benchmark/app.js#L113)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>       const result = await benchmark({
>         'benchmark': {
>           'model': model,
>           'numRuns': benchmarkInfo.numRuns,
>           'backend': backend
>         },
>         'browsers': config.browsers
>       });
> ```
</details>

The async calls are executed in sequence, not in parallel, is it intended?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5391)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/firestore.js, line 44 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mg6e-R6ANdf0oyLKn94:-Mg6e-R6ANdf0oyLKn95:b-k6bsnu) ([raw file](https://github.com/tensorflow/tfjs/blob/fd18e01f34950f4a0f96da21819f183e408ed9cb/e2e/benchmarks/browserstack-benchmark/firestore.js#L44)):*
> ```
>     /* Reference to the "BenchmarkResults" collection on firestore that contains
>      * the benchmark results. */
> ```
Should be // (for annotation) not /* ... */ (for doccomment)
___
*[e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json, line 6 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mg6eF5R2J9wfEMaxNzc:-Mg6eF5R2J9wfEMaxNzd:b-djun2n) ([raw file](https://github.com/tensorflow/tfjs/blob/fd18e01f34950f4a0f96da21819f183e408ed9cb/e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json#L6)):*
> ```
> wasm
> ```
Can we test webgl?
___
*[e2e/benchmarks/browserstack-benchmark/README.md, line 55 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mg6eQFA3WvrTLYkc9RJ:-Mg6eQFA3WvrTLYkc9RK:b-s265vb) ([raw file](https://github.com/tensorflow/tfjs/blob/fd18e01f34950f4a0f96da21819f183e408ed9cb/e2e/benchmarks/browserstack-benchmark/README.md#L55)):*
> ```
>         "model": ["model_name"], //List of one or more custom or official models
>         "numRuns": positive_integer,
>         "backend": ["backend_name"] //List of one or more backends
> ```
If there are multiple models and multiple backends, what will the behavior be?

**Review by ClaireXP — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5391)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 113 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mg6dYTYC4MiJnUzUsVE:-Mg6sOBl404178FJ8A5o:br3h0cd) ([raw file](https://github.com/tensorflow/tfjs/blob/fd18e01f34950f4a0f96da21819f183e408ed9cb/e2e/benchmarks/browserstack-benchmark/app.js#L113)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>       const result = await benchmark({
>         'benchmark': {
>           'model': model,
>           'numRuns': benchmarkInfo.numRuns,
>           'backend': backend
>         },
>         'browsers': config.browsers
>       });
> ```
The async calls are executed in sequence, not in parallel, is it intended?
</blockquote></details>

Yes. We don't want too many benchmarks to be sent at once. The async controls the number of sent benchmarks regardless of the number of backend-model combinations because it runs benchmarks for one backend-model combination at a time.
___
*[e2e/benchmarks/browserstack-benchmark/firestore.js, line 44 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mg6e-R6ANdf0oyLKn94:-Mg6t78L9cUKUxVSOz-2:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/fd18e01f34950f4a0f96da21819f183e408ed9cb/e2e/benchmarks/browserstack-benchmark/firestore.js#L44)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>     /* Reference to the "BenchmarkResults" collection on firestore that contains
>      * the benchmark results. */
> ```
Should be // (for annotation) not /* ... */ (for doccomment)
</blockquote></details>

Done.
___
*[e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json, line 6 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mg6eF5R2J9wfEMaxNzc:-Mg6t8949YuvrV7WGmtT:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/fd18e01f34950f4a0f96da21819f183e408ed9cb/e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json#L6)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> wasm
> ```
Can we test webgl?
</blockquote></details>

Done.
___
*[e2e/benchmarks/browserstack-benchmark/README.md, line 55 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5391#-Mg6eQFA3WvrTLYkc9RJ:-Mg6t9bN4IrSmIpKQMIp:b8fk02q) ([raw file](https://github.com/tensorflow/tfjs/blob/fd18e01f34950f4a0f96da21819f183e408ed9cb/e2e/benchmarks/browserstack-benchmark/README.md#L55)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
>         "model": ["model_name"], //List of one or more custom or official models
>         "numRuns": positive_integer,
>         "backend": ["backend_name"] //List of one or more backends
> ```
If there are multiple models and multiple backends, what will the behavior be?
</blockquote></details>

Added another description to clarify in the README. Will also add another description to the bluedoc

**Pull request merged**
