### PR TITLE
Fix GCP Timeout for BrowserStack Nightly Benchmarks

### PR DESCRIPTION
**Pull request by ClaireXP**
@keithlwill @lina128 @mattsoulanille

- Created function to delete Firebase instance to prevent Firebase from hanging, which prevents node process from ending
- Converted pushing to firestore function to async to prevent Firebase instance from being deleted before all results are pushed
- Increased cloudbuild timeout to account for webgl backend
- Increased max number of parallel tests from 7 to 9 for better optimization with retry capabilities and to lessen chance of a timeout

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5423)

### CODE REVIEW

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Looks good! Just one question about error handling (and two nits). Thanks!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5423#-:-MgCJUsWC9Vekl6-PS3Y:b-wr4gnv)* status: 0 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 187 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5423#-MgCCpuoBdkRgdzXF8Z4:-MgCCpuoBdkRgdzXF8Z5:b-7raq4s) ([raw file](https://github.com/tensorflow/tfjs/blob/e2b0530349dbbf45d8f1b0a0797523d22caa3c8b/e2e/benchmarks/browserstack-benchmark/app.js#L187)):*
> ```
>   } else if (cliArgs?.firestore) {
>     await pushToFirestore(fulfilled);
> ```
Nit: Are `--firestore` and `--outfile` exclusive (can't work together)? If so, we should throw an error while parsing arguments if both are passed. Otherwise, we may have a bug since this will write to a file but won't push to firestore when both args are passed.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 324 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5423#-MgCDdtpBjyC-YfvWeOL:-MgCDdtq0UJa-6TKvCS8:bi1xmj8) ([raw file](https://github.com/tensorflow/tfjs/blob/e2b0530349dbbf45d8f1b0a0797523d22caa3c8b/e2e/benchmarks/browserstack-benchmark/app.js#L324)):*
> ```
>  await Promise.allSettled(firestoreResults);
> ```
This hides errors that might occur when calling `addResultsToFirestore`. Should we use `Promise.all` instead, or is this intentional as part of the command line interface? If it's intentional, we should return the result of `Promise.allSettled` so we can handle the errors later.
___
*[e2e/benchmarks/browserstack-benchmark/firestore.js, line 81 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5423#-MgCIJixExuxPFtvehK1:-MgCIJiyDP5mGCdsEGBW:b-rmvqcc) ([raw file](https://github.com/tensorflow/tfjs/blob/e2b0530349dbbf45d8f1b0a0797523d22caa3c8b/e2e/benchmarks/browserstack-benchmark/firestore.js#L81)):*
> ```
>    throw new Error(err);
> ```
Nit: Does firestore not throw `Error` objects, and you have to wrap them in `Error` yourself? That's odd.

**Review by lina128 — APPROVED** [review]
LGTM. Please also wait for Matt's approval.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5423#-:-MgCkWSbBFSe7n9LaY0x:b8zu2wv)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP and @mattsoulanille)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 324 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5423#-MgCDdtpBjyC-YfvWeOL:-MgCjr7N81Np2Mna_Zrz:bw7zon3) ([raw file](https://github.com/tensorflow/tfjs/blob/e2b0530349dbbf45d8f1b0a0797523d22caa3c8b/e2e/benchmarks/browserstack-benchmark/app.js#L324)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>  await Promise.allSettled(firestoreResults);
> ```
This hides errors that might occur when calling `addResultsToFirestore`. Should we use `Promise.all` instead, or is this intentional as part of the command line interface? If it's intentional, we should return the result of `Promise.allSettled` so we can handle the errors later.
</blockquote></details>

I prefer Promise.allSettled, so that one failure doesn't block others. Given that we don't have a mechanism to backfill failures and this is not a critical service, I'm fine to have some failures occasionally.

**Review by mattsoulanille — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5423)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 324 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5423#-MgCDdtpBjyC-YfvWeOL:-MgD-7W55ntpzKdaSMmN:bnrwnks) ([raw file](https://github.com/tensorflow/tfjs/blob/e2b0530349dbbf45d8f1b0a0797523d22caa3c8b/e2e/benchmarks/browserstack-benchmark/app.js#L324)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

I prefer Promise.allSettled, so that one failure doesn't block others. Given that we don't have a mechanism to backfill failures and this is not a critical service, I'm fine to have some failures occasionally.
</blockquote></details>

Sounds good to me! We can return the result of `Promise.allSettled`, but I'd say this is a nit now.

**Comment by mattsoulanille** [comment]
LGTM modulo nits! Feel free to merge, @ClaireXP .

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5423#-:-MgD3SaMEGCMAC03iMHM:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

**Pull request merged**
