### PR TITLE
tfjs-node: add 2.0 api

### LINKED ISSUE #4193: C Tensorflow core changes in 2.4
"C-API functions TF_StringDecode, TF_StringEncode, and TF_StringEncodedSize are no longer relevant and have been removed; see core/platform/ctstring.h for string access/modification in C."

This change has breaking building from source for tfjs-node-gpu.

```
  tfjs_backend.cc
  tfjs_binding.cc
  win_delay_load_hook.cc
C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\binding\tfjs_backend.cc(216,18): error C3861: TF_StringEncodedSize: идентификатор не найден [C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\build\tfjs_binding.vcxproj]
C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\binding\tfjs_backend.cc(241,9): error C3861: TF_StringEncode: идентификатор не найден [C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\build\tfjs_binding.vcxproj]
C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\binding\tfjs_backend.cc(374,5): error C3861: TF_StringDecode: идентификатор не найден [C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\build\tfjs_binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\trading\\node_modules\\@tensorflow\\tfjs-node-gpu\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--build-from-source" "--module=C:\\dev\\trading\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v6\\tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=C:\\dev\\trading\\node_modules\\@tensorflow\\tfjs-node-gpu\\lib\\napi-v6" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=6" "--node_napi_label=napi-v6"
gyp ERR! cwd C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu
gyp ERR! node -v v12.19.0
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\node_modules\node-gyp\bin\node-gyp.js build --build-from-source --module=C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v6\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v6 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\dev\\trading\\node_modules\\@tensorflow\\tfjs-node-gpu\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--build-from-source"
node-pre-gyp ERR! cwd C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu
node-pre-gyp ERR! node -v v12.19.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\node_modules\node-gyp\bin\node-gyp.js build --build-from-source --module=C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v6\tfjs_binding.node --module_name=tfjs_binding --module_path=C:\dev\trading\node_modules\@tensorflow\tfjs-node-gpu\lib\napi-v6 --napi_version=7 --node_abi_napi=napi --napi_build_version=6 --node_napi_label=napi-v6' (1)
error Command failed with exit code 1.
```

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version: 2.7.0
- CUDA/cuDNN version: 10.1, 7.6

**Describe the problem**
Can't build bindings

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Run: .\bazel.exe build --config=cuda --define=no_tensorflow_py_deps=true --config=opt --config=monolithic //tensorflow/tools/lib_package:libtensorflow
2. Extract tar to deps
3. Run node-pre-gyp rebuild

### PR DESCRIPTION
**Pull request by WenheLI**
Fix #4193 
This PR aligns TF_String methods to tf2.4.x. So that it could use the latest version of tf binary.
One more thing, how to build and distribute new binary for tf 2.4.x

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
Thank you Wenhe for looking into supporting TF 2.4.0.
 Tensorflow C lib is published here https://www.tensorflow.org/install/lang_c

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810#-:-MVqh1qT8KzP12k2V1gu:b8gk1dd)* status: 0 of 1 approvals obtained

**Review by pyu10055 — COMMENTED** [review]
I believe the intallation script will download the library based on the version:
https://github.com/tensorflow/tfjs/blob/master/tfjs-node/scripts/deps-constants.js#L25

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810#-:-MVqhSNX-bPDIWu3KwwL:b7pcwem)* status: 0 of 1 approvals obtained

**Review by pyu10055 — COMMENTED** [review]
I also see malloc OOM error when running the tests:

```
0x10a3a5e00) malloc: can't allocate region
:*** mach_vm_map(size=2594937344880762880, flags: 40000100) failed (error code=3)
node(76183,0x10a3a5e00) malloc: *** set a breakpoint in malloc_error_break to debug

<--- Last few GCs --->

[76183:0x110008000]     3126 ms: Mark-sweep 129.2 (158.6) -> 112.9 (153.9) MB, 2.3 / 0.1 ms  (+ 2.0 ms in 42 steps since start of marking, biggest step 0.1 ms, walltime since start of marking 30 ms) (average mu = 0.995, current mu = 0.997) finalize increm[76183:0x110008000]     3431 ms: Scavenge 127.7 (153.9) -> 114.2 (153.9) MB, 1.5 / 0.0 ms  (average mu = 0.995, current mu = 0.997) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x37e4b03c08d1 <JSObject>
    0: builtin exit frame: tensorDataSync(this=0x37e4b5626759 <Object map = 0x37e4ba8d1919>,5965,0x37e4b5626759 <Object map = 0x37e4ba8d1919>)

    1: readSync [0x37e4a43aec11] [tfjs/tfjs-node/src/nodejs_kernel_backend.ts:245] [bytecode=0x37e4e4bfdb11 offset=100](this=0x37e4ba810921 <NodeJSKernelBackend map = 0x37e4c8129dd9>,0x37e416325b51 <Object map = 0x37e4b5a80439>)
    2: /* ...

FATAL ERROR: v8::ArrayBuffer::New Allocation failed - process out of memory
 1: 0x1011bdf85 node::Abort() (.cold.1) [emsdk/node/12.18.1_64bit/bin/node]
 2: 0x10009d119 node::Abort() [emsdk/node/12.18.1_64bit/bin/node]
 3: 0x10009d27f node::OnFatalError(char const*, char const*) [emsdk/node/12.18.1_64bit/bin/node]
 4: 0x1001de7b7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [emsdk/node/12.18.1_64bit/bin/node]
```

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810#-:-MVqyRkn3MLMFJ3At6gi:burs602)* status: 0 of 1 approvals obtained

**Comment by WenheLI** [comment]
@pyu10055  - I saw the following log in CI after changing the version:
```
Step #58 - "yarn-tfjs-node-gpu": node-pre-gyp http GET https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v7/0.0.0/GPU-linux-0.0.0.tar.gz
Step #58 - "yarn-tfjs-node-gpu": node-pre-gyp http 404 https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v7/0.0.0/GPU-linux-0.0.0.tar.gz
```
Does this mean the current binary not exist?

Besides, I did not see the OOM you posted> May I know how to reproduce it?

**Review by pyu10055 — COMMENTED** [review]
yes, I believe you can build the binary locally.
I saw the OOM error when I run `yarn test`

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810#-:-MWP_uD00RijG6nN-c2S:bae46g)* status: 0 of 1 approvals obtained

**Comment by WenheLI** [comment]
@pyu10055 - Get the OOM fixed. And I have run the unit test locally.  Everything passed except for some tests related to `NaN` case. I'm not sure if they are related to this commits. ( As this commits are mainly about string tensor and NaN is definitely not a string )

Like this one:
```
sign test-tensorflow {} accepts a tensor-like object
  Message:
    Error: Arrays differ: actual[2] = NaN, expected[2] = 0.
    Actual:   1,0,NaN,-1.
    Expected: 1,0,0,-1.
```

I have checked with the master branch. The `NaN` is treated as 0. 
IMO, this seems to be a breaking change between tf2.x and tf1.x.

**Comment by WenheLI** [comment]
Besides, I think the static server of the tf binaries does not host correct binary resources for tf2.x.
After downloading & extracting from this [url](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.4.1.tar.gz), I got a set of `dylib` files instead of `so` files. That's the main reason for CI not building successfully.

**Review by pyu10055 — COMMENTED** [review]
Thank you WenHe, You are correct, the 2.4.1 binaries has issues, I have tested 2.4.0 the binaries works on mac/linux platforms, but windows build is missing headers, I will raise the issue internally, and hopefully 2.5.0 will comes out sometime this week.

For the failed NaN test, thank you for pointing out the issue with NaN handling, I have filed internal bugs, I am not sure if fix will get into the 2.5.0 release. We might need to disable these tests for TFJS before they are fixed upstream.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810#-:-MWyvEsj3iQQfAvJy58V:b-49jyxi)* status: 0 of 1 approvals obtained

**Review by pyu10055 — COMMENTED** [review]
Just verified that, the NaN propagation behavior changes in 2.4.0 is intended, it will consistently return NaN. @wenheli I guess we can disable those failing tests for tfjs-node, and we will create another PR to align TFJS behavior with TF. I have created an issue for that.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810#-:-MWzigtyDgerI2l4ZpFx:b-e6y8qt)* status: 0 of 1 approvals obtained

**Comment by WenheLI** [comment]
> Just verified that, the NaN propagation behavior changes in 2.4.0 is intended, it will consistently return NaN. @WenheLI I guess we can disable those failing tests for tfjs-node, and we will create another PR to align TFJS behavior with TF. I have created an issue for that.
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810#-:-MWzigtyDgerI2l4ZpFx:b-e6y8qt)_ status: 0 of 1 approvals obtained

Get it! So for this PR, we need to wait for the 2.5.0 release and disable NaN unit tests.

**Comment by jumrz** [comment]
hi, can you go ahead with 2.5.0-rc0 ?

**Comment by WenheLI** [comment]
@pyu10055 - This PR is ready to review. And will draft another PR after this is landed to fix align NaN issue.

**Review by pyu10055 — COMMENTED** [review]
@wenheli 2.4.1 binaries has been updated, I think we can merge this PR. Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810#-:-MXroKsrACf2t7k0iSIy:b-rzxej9)* status: 0 of 1 approvals obtained

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4810)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
