### PR TITLE
Add support to NonMaxSuppressionV5

### PR DESCRIPTION
**Pull request by lina128**
FEATURE Add support to NonMaxSuppressionV5: add arg softNmsSigma and implementation to nonMaxSuppression op.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2524)

### CODE REVIEW

**Comment by lina128** [comment]
Thank you for the review Nikhil! I only made sure it matches with TensorFlow c++ code. I will test the python version and let you know. Good catch :)

**Comment by lina128** [comment]
> Great work Na! Are there any TF tests for NMSV5 we can include here?
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2524#-:-Lvl8XDI4CKM7EuFuzxi:b-1g9qhr)_ status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128 and @pyu10055)
> 
> _[tfjs-core/src/ops/image_ops.ts, line 237 at r1](https://reviewable.io/reviews/tensorflow/tfjs/2524#-Lvl9dCrC9qM6TJLLyqj:-Lvl9dCsAYGGwnttRczS:bxvym5q) ([raw file](https://github.com/tensorflow/tfjs/blob/28b872df8597a495120dd57e4944a9c39461d78c/tfjs-core/src/ops/image_ops.ts#L237)):_
> 
> > ```
> >     scoreThreshold = Number.NEGATIVE_INFINITY;
> >   }
> >   if (softNmsSigma == null) {
> > ```
> 
> make sure softNmsSigma is between 0 and 1?

Thank you for the review, Ping! Added the check.

**Comment by lina128** [comment]
> Great work on this Na! I don't have any major comments, this fits very well in line with our style :)
> 
> Just want to double check: you've made sure this matches TensorFlow python by testing in a colab or something of that sort?
> 
> > Reviewed 8 of 8 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2524#-:-Lvka5fY0MIR6aUTlfTd:b-chfk7a)_ status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128, @nsthorat, and @pyu10055)
> 
> _[tfjs-core/src/backends/array_util.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/2524#-LvkXLNg6bBpFknCG2u_:-LvkXLNg6bBpFknCG2ua:bb6ht2j) ([raw file](https://github.com/tensorflow/tfjs/blob/28b872df8597a495120dd57e4944a9c39461d78c/tfjs-core/src/backends/array_util.ts#L3)):_
> 
> > ```
> > /**
> >  * @license
> >  * Copyright 2018 Google LLC. All Rights Reserved.
> > ```
> 
> 2019
> 
> _[tfjs-core/src/backends/array_util_test.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/2524#-LvkYg_y35wM7yeXCbvb:-LvkYg_z4xkCzEgUlMQ7:bb6ht2j) ([raw file](https://github.com/tensorflow/tfjs/blob/28b872df8597a495120dd57e4944a9c39461d78c/tfjs-core/src/backends/array_util_test.ts#L3)):_
> 
> > ```
> > /**
> >  * @license
> >  * Copyright 2018 Google LLC. All Rights Reserved.
> > ```
> 
> 2019
> 
> _[tfjs-core/src/ops/image_ops.ts, line 148 at r1](https://reviewable.io/reviews/tensorflow/tfjs/2524#-LvkXxM9Cr1t8Rig5Zbd:-LvkXxM9Cr1t8Rig5Zbe:b-alm98y) ([raw file](https://github.com/tensorflow/tfjs/blob/28b872df8597a495120dd57e4944a9c39461d78c/tfjs-core/src/ops/image_ops.ts#L148)):_
> 
> > ```
> > /**
> >  * Performs non maximum suppression of bounding boxes based on
> >  * iou (intersection over union). This op also supports a Soft-NMS mode (c.f.
> > ```
> 
> nit: put a break line before the new sentence

Done

**Comment by lina128** [comment]
@nsthorat and @pyu10055 , the python version outputs the same result as the added test in image_ops_test.ts > 'select from three clusters with SoftNMS', here is the Colab link for the Python result: https://colab.research.google.com/drive/1ivLrOjw70UccrM6ENszizE1mb1mGB7RF

**Comment by mattyao1984** [comment]
Hi, I am using the latest version of tfjs and still getting this error from my browser
image

**Comment by lina128** [comment]
> Hi, I am using the latest version of tfjs and still getting this error from my browser
> image

Hi @mattyao1984, this PR implemented the cpu kernel and gpu kernel for NonMaxSuppressionV5 op, and this change is included in tfjs-core 1.5.1 and tfjs 1.5.1. But we haven't included the op in tfjs-converter yet. We will do another release tomorrow to include everything. Stay tuned.

**Comment by mattyao1984** [comment]
@lina128 Thanks!

**Pull request merged**
