### PR TITLE
[camera-stream] Fix for iOS Landscape Mode

### PR DESCRIPTION
**Pull request by nicholasio**
This is a fix for #2987 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3041)

### CODE REVIEW

**Comment by nicholasio** [comment]
@googlebot I signed it!

**Comment by tafsiri** [comment]
@nicholasio also it looks like the CLA check failed. You might have different email addresses associated with the commit vs your github?

**Comment by nicholasio** [comment]
@tafsiri Thanks for the review. I think those make sense and I think you're right about swapping width/height params.

I'll address your feedback later today and will trying figure out the CLA check.

**Comment by nicholasio** [comment]
@tafsiri I made a couple of updates to add support for a rotation param instead of "landscape". Regarding android, disregard that, I was able to reproduce the same issue on android.

Regarding the target shape I don't think it's necessary to change, we're rotating the texture but the tensor shape should match whatever the input shape for the model is. 

Still pending the tests, but let me know if there's anything else you wanted to see.

**Comment by nicholasio** [comment]
@googlebot I fixed it

**Comment by nicholasio** [comment]
@tafsiri I notice one thing on Android. if the app starts on landscape mode by default, the bug does not happen and no rotation is needed. However, if the app starts in portrait and then you rotate you phone to landscape mode it bug shows up.

Shouldn't change anything in this PR as it's up to the application choose the rotation they want to use.

**Comment by tafsiri** [comment]
> Regarding the target shape I don't think it's necessary to change, we're rotating the texture but the tensor shape should match whatever the input shape for the model is.

I think this depends on how the user specifies the target shape, so that is what I think the tests can catch and we could add some logic to warn about. When rotating a non square image 90 degrees, the aspect ratio of the target shape will be different from the input shape. Could you add tests for rotating non square images as that is closer to the expected use case.

**Comment by nicholasio** [comment]
@tafsiri Sure, will add a few more tests to cover this scenario

**Comment by fhenri42** [comment]
Hey we are facing the same issue, do you have any news on when this PR will be merged ?

**Comment by rthadur** [comment]
@nicholasio gentle ping for update ?

**Comment by nicholasio** [comment]
I'll try to set some time aside to get this over the finish line, which at this point seems to be only adding a couple more tests. In the meantime we are already using this PR on an app successfully.

> iss

If you want to try this out you can add this `postinstall`script which only overrides the react-native package.

```
    "postinstall": "git clone https://github.com/nicholasio/tfjs.git tfjs-fork && (cd tfjs-fork/tfjs-react-native && git checkout fix/ios-landscape-mode && yarn && yarn build) && cp -rf tfjs-fork/tfjs-react-native/dist node_modules/@tensorflow/tfjs-react-native && rm -rf ./tfjs-fork"
```

Doing this way only requires you to compile the react-native package and not everything.

**Comment by DanielRHarris** [comment]
Hi, any update on this?

**Comment by dhiogocorrea** [comment]
Hello! Any updates ? Thanks . @nicholasio @rthadur

**Comment by nicholasio** [comment]
> Looks like some other folks are also asking about this issue. I will prioritize it and take a closer look this or next week. Will create another PR based on this. Thanks @nicholasio!

Looks like you got this covered! Excited to see this fix started to make it's way into master.

I have a production app that I can help test once you've got a PR open.

**Pull request closed without merging**
