### PR TITLE
webgpu: Optimize Conv2DBackpropInput

### PR DESCRIPTION
**Pull request by qjia7**
PERF

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5155)

### CODE REVIEW

**Comment by qjia7** [comment]
@kainino0x @lina128 @jinjingforever Please take a look, thanks.
See ~2x speedup for total time of Conv2dBackpropInput in blazePose on TGL.

**Review by kainino0x — APPROVED** [review]
I don't know what the semantics of this op are, so I can't review the actual behavior, but LGTM. Cool to see that the mm_matMul design we added forever ago is still turning out to be useful (though of course maybe in the long run there would be a more maintainable design - the implicit dependency of mm_matMul on mm_readA/mm_readB/mm_write certainly doesn't make for very clear, readable code.)

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5155#-:-Mb8n4dh4xUrAyDSZN8o:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained

**Comment by qjia7** [comment]
Sorry, I forgot to submit the change of `flags_webgpu.ts`. Please take another look. Thanks.

**Review by lina128 — APPROVED** [review]
Lgtm

**Pull request merged**
