### PR TITLE
Add dilation2d to webgl.

### PR DESCRIPTION
**Pull request by lina128**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4334)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4334)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @pyu10055)

___
*[tfjs-backend-webgl/src/setup_test.ts, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4334#-MNoNm30EItInUrFzbpp:-MNoNm30EItInUrFzbpq:b-9tbdaj) ([raw file](https://github.com/tensorflow/tfjs/blob/5a931aa5b38d1cac07bd12d26ebd4b9317855350/tfjs-backend-webgl/src/setup_test.ts#L26)):*
> ```XML
> const customInclude = (testName: string) => {
>   const toExclude =
>       ['isBrowser: false', 'tensor in worker', 'dilation gradient'];
> ```

why dilation gradient needs to be excluded? if it is not implemented in WebGL can it be forward to cpu?

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4334)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @pyu10055)

___
*[tfjs-backend-webgl/src/dilation_gpu.ts, line 52 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4334#-MNoOb7K5uH8MDFlhGvk:-MNoOb7K5uH8MDFlhGvl:bjxr2f7) ([raw file](https://github.com/tensorflow/tfjs/blob/5a931aa5b38d1cac07bd12d26ebd4b9317855350/tfjs-backend-webgl/src/dilation_gpu.ts#L52)):*
> ```XML
>         int batch = coords.x;
>         int d1 = coords.w;
>         ivec2 outCorner =
> ```

should it be named outTopLeftCorner to be clearer?

**Review by annxingyuan — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4334#-:-MNxfPRvAB_65Cs0EVp2:bb6ywmx)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, and @lina128)

**Review by annxingyuan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4334)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @pyu10055)

___
*[tfjs-backend-webgl/src/setup_test.ts, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4334#-MNoNm30EItInUrFzbpp:-MNxfcjY1tZ11ItWt5vN:bbocecu) ([raw file](https://github.com/tensorflow/tfjs/blob/5a931aa5b38d1cac07bd12d26ebd4b9317855350/tfjs-backend-webgl/src/setup_test.ts#L26)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why dilation gradient needs to be excluded? if it is not implemented in WebGL can it be forward to cpu?
</blockquote></details>

Na and I discussed - the gradient implementation would be a bit complicated in WebGL because it involves accumulation and so requires multiple passes.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4334)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, and @lina128)

___
*[tfjs-backend-webgl/src/setup_test.ts, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4334#-MNoNm30EItInUrFzbpp:-MNyHcXqDjKu2XW285sJ:bp7vbga) ([raw file](https://github.com/tensorflow/tfjs/blob/5a931aa5b38d1cac07bd12d26ebd4b9317855350/tfjs-backend-webgl/src/setup_test.ts#L26)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Na and I discussed - the gradient implementation would be a bit complicated in WebGL because it involves accumulation and so requires multiple passes. 
</blockquote></details>

sounds good.

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4334)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, and @lina128)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4334)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[tfjs-backend-webgl/src/dilation_gpu.ts, line 52 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4334#-MNoOb7K5uH8MDFlhGvk:-MNyNnc71eiyboWcZbx8:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/5a931aa5b38d1cac07bd12d26ebd4b9317855350/tfjs-backend-webgl/src/dilation_gpu.ts#L52)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should it be named outTopLeftCorner to be clearer?
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/setup_test.ts, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4334#-MNoNm30EItInUrFzbpp:-MNyM22aBSpPmoJxRrXI:by7ys0y) ([raw file](https://github.com/tensorflow/tfjs/blob/5a931aa5b38d1cac07bd12d26ebd4b9317855350/tfjs-backend-webgl/src/setup_test.ts#L26)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

sounds good.
</blockquote></details>

As Ann said, it is complicated, because of this line of code: https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-cpu/src/kernels/Dilation2DBackpropInput.ts#L109

It requires accumulation of values, and on top of that requires computing value from a point and setting value to a different point. The latter requirement may not be possible with webgl. WebGPU will be able to solve this problem, by storing values as flat array and allowing setting value to any position.

Regarding to why not forward to cpu, according to Ann, it is the consensus from the past in situation like this, we rather not implement it instead of forwarding to cpu. So I'm just following the rule for code base consistency.

**Pull request merged**
