### PR TITLE
[webgl] Add default arguments to CropAndResize.

### PR DESCRIPTION
**Pull request by annxingyuan**
I think they were unintentionally removed by https://github.com/tensorflow/tfjs/pull/4265

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4407)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
Hi Ann, can you add these two lines in webgl kernel CropAndResize, similar as in cpu kernel:
```
  const $method = method || 'bilinear';
  const $extrapolationValue = extrapolationValue || 0;
```

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4407#-:-MObodULASWWqgSupeam:b735y9q)* status: 0 of 1 approvals obtained (waiting on @lina128)

**Review by lina128 — COMMENTED** [review]
Also, add a test for method is null and extrapolationValue is null.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4407#-:-MObp2GD9VHXih4eRp13:bf9ec2c)* status: 0 of 1 approvals obtained

**Review by annxingyuan — COMMENTED** [review]
Done - please take another look.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4407#-:-MOg25ks8R5_Hcix7L2y:b5ppbwj)* status: 0 of 1 approvals obtained

**Review by lina128 — APPROVED** [review]
Thank you Ann!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4407#-:-MOgxMDr9eG7d71CMjW3:b87y7r0)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
