### PR TITLE
Fix release script not updating all package.jsons

### PR DESCRIPTION
**Pull request by mattsoulanille**
release-tfjs updated only the root package.json of each package, but e2e tests have some other package.json files that must be updated as well. Fix this by updating all package.json files in each package so that they use the npm release versions instead of `link:` dependencies.

Also fix e2e running integration tests at the same time as generating files for integration tests.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7542)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
[CI including verdaccio tests](https://console.cloud.google.com/cloud-build/builds/1f5ada78-da61-462b-8cdb-3c6bf614b126?project=834911136599)

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7542)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @chunnienc and @mattsoulanille)

___
*[`scripts/release-tfjs.ts` line 228 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7542#-NS87D2OCRaHOHQODK3V:-NS87D2OCRaHOHQODK3W:bjhcb6r) ([raw file](https://github.com/tensorflow/tfjs/blob/ed30c48567dea456cc743651b88814e10ff67410/scripts/release-tfjs.ts#L228)):*
> ```XML
>             $(`find ${packagePath} -name package.json -not -path \'*/node_modules/*\'`)
>             .split('\n');
>       for (const packageJsonPath of subpackages) {
> ```

might be good to output the log what packages are affected in this step

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7542)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @chunnienc and @pyu10055)

___
*[`scripts/release-tfjs.ts` line 228 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7542#-NS87D2OCRaHOHQODK3V:-NSD61dD4cs7PnU1-sTS:b-896fja) ([raw file](https://github.com/tensorflow/tfjs/blob/2b74f8a7fc7030765c7dd58301df8bf2cd6cb063/scripts/release-tfjs.ts#L228)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

might be good to output the log what packages are affected in this step
</blockquote></details>

Done!

**Comment by mattsoulanille** [comment]
[New CI](https://console.cloud.google.com/cloud-build/builds/aa8d25e1-6027-45a8-acc3-5097e4963f73?project=834911136599)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7542)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @chunnienc)

**Comment by chunnienc** [comment]
You may choose a compute engine instance with higher memory if OOM is the cause. As I tried `bazel-tests` does not use a lot of memory, so the memory usage of `nightly-verdaccio-test` itself can be close to the limit.

**Comment by mattsoulanille** [comment]
I looked on the supported [cloudbuild instances](https://cloud.google.com/build/pricing), and the largest one has 32gb of memory. We can get more with a private pool, but that requires more setup and costs more.

**Comment by chunnienc** [comment]
How about unparallelize some tasks in nightly-verdaccio-test?

**Review by Linchenn — APPROVED** [review]

**Comment by mattsoulanille** [comment]
> How about unparallelize some tasks in nightly-verdaccio-test?

In another PR, I prevent bazel tests from running at the same time as verdaccio nightly. This seems to fix it. If we enable remote build execution in CI, we may be able to re-parallelize them.

**Comment by chunnienc** [comment]
Originally I thought some parallel bash commands in `nightly-verdaccio-test` may be the cause of high memory usage, like running pip installs and webpack builds at the same time. But it turns out that the peak memory usage on my machine was less than 5GB, and `bazel-tests` uses less than 3GB mem.

**Pull request merged**
