### PR TITLE
fix: typo in docs

### PR DESCRIPTION
**Pull request by amandeepmittal**
Change `an` to `and`.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2109)

### CODE REVIEW

**Comment by amandeepmittal** [comment]
@googlebot I signed it!

**Comment by tafsiri** [comment]
Thanks @amandeepmittal for the fix! It looks like the CLA signing didn't work, could you try again, also I think the emails you have added for cla signing need to match the email on the commit. Give it a try again and i can re-trigger the scan.

**Comment by amandeepmittal** [comment]
Hi @tafsiri 

Thanks for the info. I've added my Github email as the alternate email for the CLA. I am not sure if will this work or not. If you think it will, can you please re-trigger the scan? Otherwise, I can close the PR and you can issue the fix.

**Comment by tafsiri** [comment]
@googlebot check CLA

**Comment by tafsiri** [comment]
@amandeepmittal thanks that worked!

**Comment by amandeepmittal** [comment]
@tafsiri thank you 👍

**Pull request merged**
