### PR TITLE
Implement InitializeTableV2

### PR DESCRIPTION
**Pull request by mattsoulanille**
Implement the [InitializeTableV2](https://www.tensorflow.org/api_docs/python/tf/raw_ops/InitializeTableV2) and [InitializeTable](https://www.tensorflow.org/api_docs/python/tf/raw_ops/InitializeTable) ops.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6985)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
From the description in the docs and from some quick testing in Python, this appears to be identical to[ LookupTableImportV2](https://www.tensorflow.org/api_docs/python/tf/raw_ops/LookupTableImportV2), but I'm not completely sure of this, though, so please let me know if I'm wrong. Thanks!

**Review by pyu10055 — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6985)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Review by pyu10055 — COMMENTED** [review]
thanks Matt!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6985#-:-NFW--TYE7Li0Iv_zGmB:b4ir4d7)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6985#-:-NFgEAMW5XZjWrh7CZD6:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
