### PR TITLE
Enable WebGL's conv2dWithIm2Row to process multiple batches

### PR DESCRIPTION
**Pull request by Linchenn**
Currently, WebGL's conv2d and fusedConv2d use the brute force way (the third branch, unpacked) to process the cases that batch size is 1. This PR enables enables `conv2dWithIm2Row` in WebGL's conv2d/fusedConv2d to process muti-batch cases, which has better performance because of packing and img2col.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6442)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
great work, thank you Lin! 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6442#-:-N30UoQ3Bfaxyd_OOkkl:bp884jg)* status: 0 of 1 approvals obtained (waiting on @Linchenn)

___
*[`tfjs-backend-webgl/src/kernels/Conv2D_impl.ts` line 331 at r3](https://reviewable.io/reviews/tensorflow/tfjs/6442#-N30UaUX88jB8biqTKJm:-N30UaUX88jB8biqTKJn:b-kayzzv) ([raw file](https://github.com/tensorflow/tfjs/blob/8736df7815203dcd48e5e3881d31c503b3523d61/tfjs-backend-webgl/src/kernels/Conv2D_impl.ts#L331)):*
> ```XML
>       isChannelsLast ? w2Row.shape as [number, number, number] :
>                        im2ColReshaped.shape as [number, number, number],
>       isChannelsLast ? [convInfo.batchSize, numCols, convInfo.outChannels] :
> ```

for filter should this batchSize be 1?

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6442)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfjs-backend-webgl/src/kernels/Conv2D_impl.ts` line 331 at r3](https://reviewable.io/reviews/tensorflow/tfjs/6442#-N30UaUX88jB8biqTKJm:-N30ViQ38mfTiBnmJo27:bk771pm) ([raw file](https://github.com/tensorflow/tfjs/blob/8736df7815203dcd48e5e3881d31c503b3523d61/tfjs-backend-webgl/src/kernels/Conv2D_impl.ts#L331)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

for filter should this batchSize be 1?
</blockquote></details>

Yeah, the filter is `w2Row` and its batch size is defined as 1 at https://github.com/tensorflow/tfjs/pull/6442/files#diff-27365b7383c15a63666a8249f716ddc2b9b3d46b8201f0206e340827b8845a1eL295-L299.

The third argument here is the shape for the output, which needs to have the size of`convInfo.batchSize`.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6442)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by qjia7 — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
