### PR TITLE
[react-native] Add option to TensorCamera to not use custom shaders to resize camera image texture

### PR DESCRIPTION
**Pull request by jinjingforever**
This will help solve the problem where it is hard to figure out camera texture sizes for all kinds of devices/camera preview sizes. See code comments below for more details.

Tested with an expo project with movenet that I plan to check into tfjs-examples repo after this PR is merged.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5626)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5626)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[tfjs-react-native/src/camera/camera_webgl_util.ts, line 183 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5626#-MjeRgXRCFN7Z2j_aD5P:-MjeRgXRCFN7Z2j_aD5Q:bmnrzac) ([raw file](https://github.com/tensorflow/tfjs/blob/ecce391b26d0fe9d4c51b0d4083b4e9dfb0a0db6/tfjs-react-native/src/camera/camera_webgl_util.ts#L183)):*
> ```XML
>   const {program, vao, vertices, uniformLocations} = useCustomShadersToResize ?
>       resizeProgram(gl, inputDims, outputDims, alignCorners, interpolation) :
>       drawTextureProgram(gl, false, true);
> ```

why it needs flip vertically?
___
*[tfjs-react-native/src/camera/camera_webgl_util.ts, line 198 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5626#-MjeRQQW6BqrogKIe6vd:-MjeRQQW6BqrogKIe6ve:b-1i1f1h) ([raw file](https://github.com/tensorflow/tfjs/blob/ecce391b26d0fe9d4c51b0d4083b4e9dfb0a0db6/tfjs-react-native/src/camera/camera_webgl_util.ts#L198)):*
> ```
>         interpolation === 'nearest_neighbor' ? gl.NEAREST : gl.LINEAR;
> ```
Is the gl.LINEAR same as bilinear filter? does the test cover that?

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5626)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[tfjs-react-native/src/camera/camera.ts, line 145 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5626#-MjeRxYd11-jAGQtQOdi:-MjeRxYd11-jAGQtQOdj:btjexr6) ([raw file](https://github.com/tensorflow/tfjs/blob/ecce391b26d0fe9d4c51b0d4083b4e9dfb0a0db6/tfjs-react-native/src/camera/camera.ts#L145)):*
> ```XML
> export function fromTexture(
>     gl: WebGL2RenderingContext, texture: WebGLTexture, sourceDims: Dimensions,
>     targetShape: Dimensions, useCustomShadersToResize = true,
> ```

should it set to false by default, given the new method is superior?
___
*[tfjs-react-native/src/camera/camera_stream.tsx, line 80 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5626#-MjeRro44K7AKxDukThy:-MjeRro44K7AKxDukThz:b-fheqb2) ([raw file](https://github.com/tensorflow/tfjs/blob/ecce391b26d0fe9d4c51b0d4083b4e9dfb0a0db6/tfjs-react-native/src/camera/camera_stream.tsx#L80)):*
> ```XML
>  *   - If it is set to false (default and recommended), the resize will be done
>  *     by the underlying GL system when drawing the camera image texture to the
>  *     target output texture with TEXTURE_MIN_FILTER/TEXTURE_MAX_FILTER set to
> ```

TEXTURE_MAG_FILTER?

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5626)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5626)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-react-native/src/camera/camera.ts, line 145 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5626#-MjeRxYd11-jAGQtQOdi:-MjeYA2m5-QFZi3XTtmA:b-4k0685) ([raw file](https://github.com/tensorflow/tfjs/blob/ecce391b26d0fe9d4c51b0d4083b4e9dfb0a0db6/tfjs-react-native/src/camera/camera.ts#L145)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should it set to false by default, given the new method is superior?
</blockquote></details>

Good point! Done.
___
*[tfjs-react-native/src/camera/camera_stream.tsx, line 80 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5626#-MjeRro44K7AKxDukThy:-MjeYOV73sQA4Ap6N7MZ:b-k1x4ki) ([raw file](https://github.com/tensorflow/tfjs/blob/ecce391b26d0fe9d4c51b0d4083b4e9dfb0a0db6/tfjs-react-native/src/camera/camera_stream.tsx#L80)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

TEXTURE_MAG_FILTER?
</blockquote></details>

Nice catch! Done
___
*[tfjs-react-native/src/camera/camera_webgl_util.ts, line 183 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5626#-MjeRgXRCFN7Z2j_aD5P:-MjeYRJqDP-AaYFXQObG:b-x4ujt) ([raw file](https://github.com/tensorflow/tfjs/blob/ecce391b26d0fe9d4c51b0d4083b4e9dfb0a0db6/tfjs-react-native/src/camera/camera_webgl_util.ts#L183)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why it needs flip vertically?
</blockquote></details>

For some reason the texture produced from camera is upside-down:)
___
*[tfjs-react-native/src/camera/camera_webgl_util.ts, line 198 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5626#-MjeRQQW6BqrogKIe6vd:-MjeZCzNCZT4z2bnPYSQ:b-4ss5or) ([raw file](https://github.com/tensorflow/tfjs/blob/ecce391b26d0fe9d4c51b0d4083b4e9dfb0a0db6/tfjs-react-native/src/camera/camera_webgl_util.ts#L198)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
>         interpolation === 'nearest_neighbor' ? gl.NEAREST : gl.LINEAR;
> ```
Is the gl.LINEAR same as bilinear filter? does the test cover that?
</blockquote></details>

From [here](https://www.khronos.org/opengl/wiki/Sampler_Object), it says 

```
Setting GL_TEXTURE_MAG_FILTER and MIN_FILTERs to GL_LINEAR will create monolinear filtering in a 1D texture, bilinear filtering in a 2D texture, ...
```

The tests are actually only covering the custom shaders in `resize_bilinear_program_info.ts` and `resize_nearest_neigbor_program_info.ts`.  For the new mode, we will just reply on the the underlying GL implementations.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5626)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Pull request merged**
