### PR TITLE
Stack

### PR DESCRIPTION
**Pull request by lina128**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4291)

### CODE REVIEW

**Review by tafsiri — CHANGES_REQUESTED** [review]
Nice!

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4291#-:-MMpwDqj5g22RcGPcukE:b-83sjoh)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, @mattsoulanille, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Concat.ts, line 44 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpuSUnBKcXpf1a5ZXA:-MMpuSUnBKcXpf1a5ZXB:ble8327) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-cpu/src/kernels/Concat.ts#L44)):*
> ```XML
>   const $inputs = inputs.filter(t => util.sizeFromShape(t.shape) > 0);
>   if ($inputs.length === 1) {
>     return identity({inputs: {x: $inputs[0]}, backend});
> ```

Nice catch, is there a test (for concat) that would catch the issue with the previous implementation? If not and since you had to change this across backends could you add a test to catch regressions?
___
*[tfjs-backend-cpu/src/kernels/Pack.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpvG6k2lpBmJLBMji7:-MMpvG6lBAfk-LfT81wW:bwro9if) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-cpu/src/kernels/Pack.ts#L39)):*
> ```XML
>   const dtype = inputs[0].dtype;
> 
>   util.assert(axis <= rank, () => 'Axis must be <= rank of the tensor');
> ```

I think this input validation  (and the validation below can just stay in the op). There doesn't seem to be any manipulation if axis in the kernel itself.
___
*[tfjs-backend-wasm/src/kernels/Concat.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpvfay3_C6DP-Ddg5A:-MMpvbA28GUPZ2XhaIbp:bedlh9z) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-wasm/src/kernels/Concat.ts#L39)):*
> ```XML
>   const $inputs = inputs.filter(t => util.sizeFromShape(t.shape) > 0);
>   if ($inputs.length === 1) {
>     const inVals = backend.typedArrayFromHeap($inputs[0]);
> ```

call identity here instead
___
*[tfjs-backend-wasm/src/kernels/Pack.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpvo5L-9ZC2WvtnJXA:-MMpvo5L-9ZC2WvtnJXB:b-4yrdsy) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-wasm/src/kernels/Pack.ts#L39)):*
> ```XML
>   const dtype = inputs[0].dtype;
> 
>   util.assert(axis <= rank, () => 'Axis must be <= rank of the tensor');
> ```

same as above the validation can stay in the op.
___
*[tfjs-backend-webgl/src/kernels/Pack.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpvtIe6tXsN5Da82mK:-MMpvtIe6tXsN5Da82mL:b-4yrdsy) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-webgl/src/kernels/Pack.ts#L39)):*
> ```XML
>   const dtype = inputs[0].dtype;
> 
>   util.assert(axis <= rank, () => 'Axis must be <= rank of the tensor');
> ```

same as above the validation can stay in the op.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4291)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @mattsoulanille, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Concat.ts, line 44 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpuSUnBKcXpf1a5ZXA:-MMqPgSU7wjx8w_Z2n57:b-m4rnkb) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-cpu/src/kernels/Concat.ts#L44)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Nice catch, is there a test (for concat) that would catch the issue with the previous implementation? If not and since you had to change this across backends could you add a test to catch regressions?
</blockquote></details>

Added a test. The test passed with this PR and failed with code before this PR.
___
*[tfjs-backend-cpu/src/kernels/Pack.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpvG6k2lpBmJLBMji7:-MMqQQDo4WM_m3DHyUYA:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-cpu/src/kernels/Pack.ts#L39)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

I think this input validation  (and the validation below can just stay in the op). There doesn't seem to be any manipulation if axis in the kernel itself.
</blockquote></details>

Done.
___
*[tfjs-backend-wasm/src/kernels/Concat.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpvfay3_C6DP-Ddg5A:-MMqQRDoEq0xlqERCEEL:bh9iyd5) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-wasm/src/kernels/Concat.ts#L39)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

call identity here instead
</blockquote></details>

Tried identity, it complained memory leak. I think that's because identity created a new dataId in wasm backend, whereas here it already created a new dataId stored in out. 
___
*[tfjs-backend-wasm/src/kernels/Pack.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpvo5L-9ZC2WvtnJXA:-MMqQrgTDGHNxJPcJamO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-wasm/src/kernels/Pack.ts#L39)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

same as above the validation can stay in the op.
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/kernels/Pack.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpvtIe6tXsN5Da82mK:-MMqR5b5AGp812or52Vu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-webgl/src/kernels/Pack.ts#L39)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

same as above the validation can stay in the op.
</blockquote></details>

Done.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4291)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @mattsoulanille, and @tafsiri)

___
*[tfjs-backend-wasm/src/kernels/Concat.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MMpvfay3_C6DP-Ddg5A:-MMqmcnt3RTulUhQausg:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/592db46065d36e0c17f5743a9a038985918907d2/tfjs-backend-wasm/src/kernels/Concat.ts#L39)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Tried identity, it complained memory leak. I think that's because identity created a new dataId in wasm backend, whereas here it already created a new dataId stored in out. 
</blockquote></details>

Done.

**Review by tafsiri — APPROVED** [review]
LGTM. Thanks!

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4291#-:-MN-8DCt8id-v1PUnrib:b-tx3rjn)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, @mattsoulanille, and @tafsiri)

___
*[tfjs-core/src/ops/concat_test.ts, line 583 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MN-7gDRA81C889AV4gF:-MN-7gDRA81C889AV4gG:b-3kqmms) ([raw file](https://github.com/tensorflow/tfjs/blob/6c5abc1fd0189aea04122fb62c69fb5ad5a5e5d3/tfjs-core/src/ops/concat_test.ts#L583)):*
> ```XML
> 
> describeWithFlags('memory test', ALL_ENVS, () => {
>   it('does not directly return input.', async () => {
> ```

maybe rename this to "returns a new tensor when op is effectively a no-op"

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4291)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @mattsoulanille, and @tafsiri)

___
*[tfjs-core/src/ops/concat_test.ts, line 583 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4291#-MN-7gDRA81C889AV4gF:-MN-j5p32jsr1R2QUlfw:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6c5abc1fd0189aea04122fb62c69fb5ad5a5e5d3/tfjs-core/src/ops/concat_test.ts#L583)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

maybe rename this to "returns a new tensor when op is effectively a no-op"
</blockquote></details>

Done.

**Pull request merged**
