### PR TITLE
[tfjs-core] attempt to fix bugs related to sampling and output coordi…

### PR DESCRIPTION
**Pull request by xianrenb**
…nates, matmul, sum, argmax/argmin and decode

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2116)

### CODE REVIEW

**Comment by xianrenb** [comment]
This is my attempt to fix some problems.
My view may be incorrect, but I believe that resultUV from the vertex shader ranges from 0.0 to 1.0, so the boundary pixel may get 1.0, output coordinates should be adjusted as so.
On the other hand, the sampler should not use maximum value of 1.0.

[https://www.khronos.org/opengl/wiki/Rectangle_Texture](https://www.khronos.org/opengl/wiki/Rectangle_Texture)

> When using rectangle samplers, all texture lookup functions automatically use non-normalized texture coordinates. This means that the values of the texture coordinates refer specifically to texels in texel space. The value 12.5 is halfway between the thirteenth and fourteenth texel (remember: 0-base indices).

Therefore, I believe halfCR is not required and I added adjuv() to adjust the value.

**Comment by xianrenb** [comment]
After reading [https://stackoverflow.com/questions/7272579/iphone-opengl-es-2-0-pixel-perfect-textures/7272871#7272871](https://stackoverflow.com/questions/7272579/iphone-opengl-es-2-0-pixel-perfect-textures/7272871#7272871), I think that I was wrong.
"halfCR" should be used.

**Comment by xianrenb** [comment]
Based on the results of previous tests, I think my previous view may not be totally incorrect.
I think there are actually two kinds of WebGL implementations.
One is assuming texture pixel centers being integers, and the other assuming pixel centers being halfway between integers.
Therefore, I updated the code to use vec2(0.25) to adjust instead.

**Comment by nsthorat** [comment]
@xianreb is there an issue that this is fixing or can you explain what you're seeing that this resolves?

**Comment by xianrenb** [comment]
@nsthorat Originally, I found the GPU backend accuracy/performance was not matching CPU backend on my computer. I started analyzing the tfjs-core code and found there may be some potential problems and tried to fix that. I am not sure whether these changes are actually fixing these potential problems or not, but the new code did pass the tests. Maybe some of them are unnecessary or totally irrelevant.

Later, I found that the main cause was the max texture size as mentioned in [https://github.com/tensorflow/tfjs/issues/510](https://github.com/tensorflow/tfjs/issues/510). Either the GPU reported the wrong max texture size, or it did not work correctly when max texture size was used.

**Comment by jenperson** [comment]
This PR is being closed because it hasn't been updated in 3 years.

**Pull request closed without merging**
