### PR TITLE
Test running tfjs-tflite in a webworker

### PR DESCRIPTION
**Pull request by mattsoulanille**
Add a new test `//tfjs-tflite/src/worker_test` to test running tflite in a webworker. The test runs a simple model that just adds the two inputs together.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6844)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
This is working locally, but fails on BrowserStack. Possibly related to missing files.

**Comment by mattsoulanille** [comment]
[Direct link to worker test](https://source.cloud.google.com/results/invocations/3b83114d-ec70-43b6-909e-7ddc485225b5/targets;query=worker_test/%2F%2Ftfjs-tflite%2Fsrc:bs_chrome_mac_worker_test/tests)

**Review by jinjingforever — APPROVED** [review]
Nice! Thank you Matt!

**Review by lina128 — APPROVED** [review]
Thank you Matt! This is great!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6844#-:-NCa9xBr4q9m2QnUXyg_:b-4pllt5)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
