### PR TITLE
 Added tan.cc tan.ts file

### PR DESCRIPTION
**Pull request by carrycooldude**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.
I added a new tan kernel

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826)

### CODE REVIEW

**Comment by carrycooldude** [comment]
Why mine checks are failing?

**Review by pyu10055 — COMMENTED** [review]
Can you access the build logs?
o see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

Step #19 - "buildifier-tfjs-backend-wasm": ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Step #19 - "buildifier-tfjs-backend-wasm": 'yarn bazel:format-check' failed!
Step #19 - "buildifier-tfjs-backend-wasm": Please run 'yarn bazel:format'.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826#-:-MWQ11Fj1TEnkJOzRpuK:b-q67770)* status: 0 of 1 approvals obtained

**Comment by carrycooldude** [comment]
image
After Running this 
This error is coming...

**Review by pyu10055 — COMMENTED** [review]
You need to cd to the tfjs-backend-wasm directory:
```
cd tfjs-backend-wasm
yarn
yarn bazel:format
```

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826#-:-MWUyY1ZDxpRiNpIWaZb:bsue4yd)* status: 0 of 1 approvals obtained

**Comment by carrycooldude** [comment]
Yes I got it but even after that I have same check problem

**Comment by carrycooldude** [comment]
[image: Screenshot from 2021-03-23 23-28-51.png]
*This is the Output*

**Comment by carrycooldude** [comment]
> You need to cd to the tfjs-backend-wasm directory:
> 
> ```
> cd tfjs-backend-wasm
> yarn
> yarn bazel:format
> ```
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826#-:-MWUyY1ZDxpRiNpIWaZb:bsue4yd)_ status: 0 of 1 approvals obtained
Screenshot from 2021-03-23 23-28-51

**Comment by carrycooldude** [comment]
Even I didn't understand I have done the same Updated on [Sinh PR](https://github.com/tensorflow/tfjs/pull/4845)
Why It doesn't clear the checks of tan branch

**Review by pyu10055 — CHANGES_REQUESTED** [review]
You can see the details of the failed test when you join either our discussion or announcement mailing list, the links are in the description area of this PR.
There is another issue for this PR:

```
Step #14 - "build-tfjs-backend-wasm": ERROR: /workspace/tfjs-backend-wasm/src/cc/BUILD:1071:16: Compiling tfjs-backend-wasm/src/cc/kernels/Tan.cc failed: undeclared inclusion(s) in rule '//tfjs-backend-wasm/src/cc:Tan':
Step #14 - "build-tfjs-backend-wasm": this rule is missing dependency declarations for the following files included by 'tfjs-backend-wasm/src/cc/kernels/Tan.cc':
Step #14 - "build-tfjs-backend-wasm":   'tfjs-backend-wasm/src/cc/unary.h'
Step #14 - "build-tfjs-backend-wasm": Target //tfjs-backend-wasm/src/cc:tfjs-backend-wasm.js failed to build
```

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826#-:-MX2twB3AGwT6KjRd4Pa:b-ajn79n)* status: 0 of 1 approvals obtained (waiting on @carrycooldude)

___
*[tfjs-backend-wasm/src/cc/kernels/Tan.cc, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX2uMuA6lYqfu3-uC-G:-MX2uMuA6lYqfu3-uC-H:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs/blob/fea443b95c92d5ac7417cb95dc490fd523807a5c/tfjs-backend-wasm/src/cc/kernels/Tan.cc#L1)):*
> ```cpp
> /* Copyright 2019 Google LLC. All Rights Reserved.
> ```

2021
___
*[tfjs-backend-wasm/src/kernels/Tan.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX2uOTz66gX3BdEEOdm:-MX2uOTz66gX3BdEEOdn:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs/blob/fea443b95c92d5ac7417cb95dc490fd523807a5c/tfjs-backend-wasm/src/kernels/Tan.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2019 Google LLC. All Rights Reserved.
> ```

2021

**Comment by carrycooldude** [comment]
> You can see the details of the failed test when you join either our discussion or announcement mailing list, the links are in the description area of this PR.
> There is another issue for this PR:
> 
> ```
> Step #14 - "build-tfjs-backend-wasm": ERROR: /workspace/tfjs-backend-wasm/src/cc/BUILD:1071:16: Compiling tfjs-backend-wasm/src/cc/kernels/Tan.cc failed: undeclared inclusion(s) in rule '//tfjs-backend-wasm/src/cc:Tan':
> Step #14 - "build-tfjs-backend-wasm": this rule is missing dependency declarations for the following files included by 'tfjs-backend-wasm/src/cc/kernels/Tan.cc':
> Step #14 - "build-tfjs-backend-wasm":   'tfjs-backend-wasm/src/cc/unary.h'
> Step #14 - "build-tfjs-backend-wasm": Target //tfjs-backend-wasm/src/cc:tfjs-backend-wasm.js failed to build
> ```
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826#-:-MX2twB3AGwT6KjRd4Pa:b-ajn79n)_ status: 0 of 1 approvals obtained (waiting on @carrycooldude)
> 
> _[tfjs-backend-wasm/src/cc/kernels/Tan.cc, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX2uMuA6lYqfu3-uC-G:-MX2uMuA6lYqfu3-uC-H:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs/blob/fea443b95c92d5ac7417cb95dc490fd523807a5c/tfjs-backend-wasm/src/cc/kernels/Tan.cc#L1)):_
> 
> > ```c++
> > /* Copyright 2019 Google LLC. All Rights Reserved.
> > ```
> 
> 2021
> 
> _[tfjs-backend-wasm/src/kernels/Tan.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX2uOTz66gX3BdEEOdm:-MX2uOTz66gX3BdEEOdn:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs/blob/fea443b95c92d5ac7417cb95dc490fd523807a5c/tfjs-backend-wasm/src/kernels/Tan.ts#L3)):_
> 
> > ```
> > /**
> >  * @license
> >  * Copyright 2019 Google LLC. All Rights Reserved.
> > ```
> 
> 2021
How to include <xnnpack.h> file???

**Comment by carrycooldude** [comment]
> > You can see the details of the failed test when you join either our discussion or announcement mailing list, the links are in the description area of this PR.
> > There is another issue for this PR:
> > ```
> > Step #14 - "build-tfjs-backend-wasm": ERROR: /workspace/tfjs-backend-wasm/src/cc/BUILD:1071:16: Compiling tfjs-backend-wasm/src/cc/kernels/Tan.cc failed: undeclared inclusion(s) in rule '//tfjs-backend-wasm/src/cc:Tan':
> > Step #14 - "build-tfjs-backend-wasm": this rule is missing dependency declarations for the following files included by 'tfjs-backend-wasm/src/cc/kernels/Tan.cc':
> > Step #14 - "build-tfjs-backend-wasm":   'tfjs-backend-wasm/src/cc/unary.h'
> > Step #14 - "build-tfjs-backend-wasm": Target //tfjs-backend-wasm/src/cc:tfjs-backend-wasm.js failed to build
> > ```
> > 
> > 
> > > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826#-:-MX2twB3AGwT6KjRd4Pa:b-ajn79n)_ status: 0 of 1 approvals obtained (waiting on @carrycooldude)
> > 
> > 
> > _[tfjs-backend-wasm/src/cc/kernels/Tan.cc, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX2uMuA6lYqfu3-uC-G:-MX2uMuA6lYqfu3-uC-H:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs/blob/fea443b95c92d5ac7417cb95dc490fd523807a5c/tfjs-backend-wasm/src/cc/kernels/Tan.cc#L1)):_
> > > ```c++
> > > /* Copyright 2019 Google LLC. All Rights Reserved.
> > > ```
> > 
> > 
> > 2021
> > _[tfjs-backend-wasm/src/kernels/Tan.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX2uOTz66gX3BdEEOdm:-MX2uOTz66gX3BdEEOdn:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs/blob/fea443b95c92d5ac7417cb95dc490fd523807a5c/tfjs-backend-wasm/src/kernels/Tan.ts#L3)):_
> > > ```
> > > /**
> > >  * @license
> > >  * Copyright 2019 Google LLC. All Rights Reserved.
> > > ```
> > 
> > 
> > 2021
> > How to include <xnnpack.h> file???

Screenshot from 2021-03-31 00-10-54

> This is the error which I am getting even though in WORKSPACE file I having the  remote of xnnpack but the error is throwing

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826)* status: 0 of 1 approvals obtained (waiting on @carrycooldude)

___
*[.vscode/c_cpp_properties.json, line 15 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX89d6u-jHq8zvtLWAD:-MX89d6u-jHq8zvtLWAE:bkfrxqo) ([raw file](https://github.com/tensorflow/tfjs/blob/c6b856ab8a92cf1b7536f45daef66fe84f37324f/.vscode/c_cpp_properties.json#L15)):*
> ```JSON
>         }
>     ],
>     "version": 4
> ```

please avoid committing personal vscode settings to the repo.
___
*[.vscode/settings.json, line 145 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX89lPfBmNfVIPaRJib:-MX89lPfBmNfVIPaRJic:bkfrxqo) ([raw file](https://github.com/tensorflow/tfjs/blob/c6b856ab8a92cf1b7536f45daef66fe84f37324f/.vscode/settings.json#L145)):*
> ```JSON
>   },
>   "editor.formatOnSave": true,
>   "C_Cpp.errorSquiggles": "Disabled"
> ```

please avoid committing personal vscode settings to the repo.
___
*[tfjs-backend-wasm/src/cc/BUILD, line 1044 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX89q898NGMT7x5ekrH:-MX89q898NGMT7x5ekrI:b-uxtn0m) ([raw file](https://github.com/tensorflow/tfjs/blob/c6b856ab8a92cf1b7536f45daef66fe84f37324f/tfjs-backend-wasm/src/cc/BUILD#L1044)):*
> ```Starlark
>     srcs = ["kernels/Tan.cc"],
>     deps = [
>         ":backend",
> ```

You need to include the :unary lib.

```
tfjs_cc_library(
    name = "Tan",
    srcs = ["kernels/Tan.cc"],
    deps = [
        ":backend",
        ":unary",
    ],
)
```
___
*[tfjs-backend-wasm/src/kernels/Tan.ts, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4826#-MX2uOTz66gX3BdEEOdm:-MX89ywS97kh1j3K6VHC:b-7pqith) ([raw file](https://github.com/tensorflow/tfjs/blob/fea443b95c92d5ac7417cb95dc490fd523807a5c/tfjs-backend-wasm/src/kernels/Tan.ts#L3)):*
<details><summary><i>Previously, carrycooldude (Kartikey Rawat) wrote…</i></summary><blockquote>

> > > ```
> > > /**
> > >  * @license
> > >  * Copyright 2019 Google LLC. All Rights Reserved.
> > > ```
> > > 

> > 
> > 
> > 2021
> > How to include <xnnpack.h> file???
> > 

Screenshot from 2021-03-31 00-10-54


> This is the error which I am getting even though in WORKSPACE file I having the  remote of xnnpack but the error is throwing
> 
</blockquote></details>

I am not sure about the vsocode setup, but we usually use command line for compilation:
```
yarn build-deps
yarn build
yarn test
```

**Review by pyu10055 — COMMENTED** [review]
Thanks, looks like the tests are passing, once you revert the changes to the vscode setting files, we could merge it in. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826#-:-MXcm5bLDTUf1AIabhMi:b-m759l8)* status: 0 of 1 approvals obtained (waiting on @carrycooldude)

**Comment by carrycooldude** [comment]
> Thanks, looks like the tests are passing, once you revert the changes to the vscode setting files, we could merge it in.
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826#-:-MXcm5bLDTUf1AIabhMi:b-m759l8)_ status: 0 of 1 approvals obtained (waiting on @carrycooldude)

I revert the changes

**Comment by carrycooldude** [comment]
I already done that

**Review by pyu10055 — COMMENTED** [review]
Looks like there are still some minor changes to ,vscode/c_cpp_properties.json and .vscode/settings.json, tfjs-backend-wasm/.vscode/cpp_properites.json files 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4826#-:-MXh6tM62ORnFNh-0yN6:b-1kdxmp)* status: 0 of 1 approvals obtained (waiting on @carrycooldude)

**Comment by carrycooldude** [comment]
I made the changes...

**Review by pyu10055 — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
