### PR TITLE
webgpu: Remove bufSize from GPUData

### PR DESCRIPTION
**Pull request by qjia7**
The buffer size and usage are the attributes of GPUBuffer. So bufSize doesn't need to be provided extra in GPUData.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

### CODE REVIEW

**Review by xhcao — APPROVED** [review]
LGTM

**Review by gyagp — APPROVED** [review]
LGTM

**Comment by Linchenn** [comment]
Is `bufSize` still needed in 
```
export interface GPUData {
  tensorRef: Tensor;
  texture?: WebGLTexture;
  buffer?: GPUBuffer;
  texShape?: [number, number];
  bufSize?: number;
}
```

**Comment by Linchenn** [comment]
Could you help update this doc, https://github.com/tensorflow/tfjs/blob/master/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md? Or, it could be in a separate pr.

**Comment by gyagp** [comment]
> Is `bufSize` still needed in
> 
> ```
> export interface GPUData {
>   tensorRef: Tensor;
>   texture?: WebGLTexture;
>   buffer?: GPUBuffer;
>   texShape?: [number, number];
>   bufSize?: number;
> }
> ```

Jiajia's PR only changes the API, which may impact the upcoming release. We will do the related refactoring after holidays.

**Review by Linchenn — APPROVED** [review]
Thanks! LGTM

**Comment by qjia7** [comment]
> Could you help update this doc, https://github.com/tensorflow/tfjs/blob/master/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md? Or, it could be in a separate pr.

PR https://github.com/tensorflow/tfjs/pull/7651 fixes it. Thanks.

**Comment by Linchenn** [comment]
> Is `bufSize` still needed in
> 
> ```
> export interface GPUData {
>   tensorRef: Tensor;
>   texture?: WebGLTexture;
>   buffer?: GPUBuffer;
>   texShape?: [number, number];
>   bufSize?: number;
> }
> ```

@qjia7

**Comment by qjia7** [comment]
> > Is `bufSize` still needed in
> > ```
> > export interface GPUData {
> >   tensorRef: Tensor;
> >   texture?: WebGLTexture;
> >   buffer?: GPUBuffer;
> >   texShape?: [number, number];
> >   bufSize?: number;
> > }
> > ```
> 
> @qjia7

`bufSize` is not needed anymore in `GPUData`. You can get the size from `buffer.size`. See here https://www.w3.org/TR/webgpu/#gpubuffer. size is one of the properties of GPUBuffer.

**Comment by Linchenn** [comment]
Thanks!

**Pull request merged**
