### PR TITLE
Fix mistakes

### PR DESCRIPTION
**Pull request by ivan-pan**
I corrected some mistakes such as `channeLast` (instead of `channelsLast`). Do check carefully whether I got everything right.

**Note:** `**Input shape:**` is not rendered correctly on the [website](https://js.tensorflow.org/api/latest/), where it is shown as “_Input shape:_*” rather than “**Input shape:**”.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6793)

### CODE REVIEW

**Review by jenperson — APPROVED** [review]
Excellent work! Thanks for taking the time to improve TensorFlow.js!

**Review by jenperson — CHANGES_REQUESTED** [review]
> Reviewed 2 of 71 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6793)* status: 0 of 1 approvals obtained (waiting on @ivan-pan)

___
*[`tfjs-core/src/ops/string/string_n_grams.ts` line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6793#-NAoJV31DpmMj61_Zabv:-NAoJV31DpmMj61_Zabw:bvei5rb) ([raw file](https://github.com/tensorflow/tfjs/blob/8ba77c6a5986076d5554400efd15392a961ea970/tfjs-core/src/ops/string/string_n_grams.ts#L54)):*
> ```XML
>  * @param padWidth: The number of padding elements to add to each side of each
>  *     sequence. Note that padding will never be greater than `nGramWidths`-1
>  *     regardless of this value. If `padWidth`=-1 , then add max(`nGramWidths`)-1
> ```

This line exceeds the maximum line length of 80. The easiest way might be to cut off at the comma and add that to the next line. Or the beginning of the sentence.
___
*[`tfjs-data/src/readers.ts` line 210 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6793#-NAoKvNbAggvhnE4RGC7:-NAoKvNbAggvhnE4RGC8:bv4asm8) ([raw file](https://github.com/tensorflow/tfjs/blob/8ba77c6a5986076d5554400efd15392a961ea970/tfjs-data/src/readers.ts#L210)):*
> ```XML
> 
> /**
>  * Create an iterator that generates `Tensor`s from webcam video stream. This API
> ```

Line exceeds 80
___
*[`tfjs-data/src/readers.ts` line 246 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6793#-NAoKxY790Dl3nXXdsM1:-NAoKxY790Dl3nXXdsM2:bv4asm8) ([raw file](https://github.com/tensorflow/tfjs/blob/8ba77c6a5986076d5554400efd15392a961ea970/tfjs-data/src/readers.ts#L246)):*
> ```XML
> 
> /**
>  * Create an iterator that generates frequency-domain spectrogram `Tensor`s from
> ```

Line exceeds 80
___
*[`tfjs-layers/src/exports_layers.ts` line 1499 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6793#-NAoLQ2E2bskDjAsARIq:-NAoLQ2E2bskDjAsARIr:b-tqa4ie) ([raw file](https://github.com/tensorflow/tfjs/blob/8ba77c6a5986076d5554400efd15392a961ea970/tfjs-layers/src/exports_layers.ts#L1499)):*
> ```XML
>  *   keyword argument of `RNN.call` method. This requires that the `cell.call`
>  *   method accepts the same keyword argument `constants`. Such constants
>  *   can be used to condition the cell transformation on additional static inputs
> ```

Line exceeds 80

**Comment by jenperson** [comment]
It looks like the code fails presubmit due to the length of some of the lines exceeding 80. These are the three that were flagged during the build process. Please check the other lines on which text was added to make sure they don't exceed  80 characters.

**Review by jenperson — APPROVED** [review]

**Review by pyu10055 — APPROVED** [review]
> Reviewed 71 of 71 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6793)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ivan-pan)

**Pull request merged**
