### PR TITLE
[DRAFT] Update TypeScript to 4.4.2

### PR DESCRIPTION
**Pull request by mattsoulanille**
This PR updates TypeScript from 3.5.3 to 4.4.2. It is still a work in progress:

- [x] tfjs-converter: ~Tests need to be rewritten to avoid [spying on properties of imported objects](https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/src/operations/executors/basic_math_executor_test.ts#L52-L59)~ This is done.
- [x] tfjs-vis: ~There's a test failure with TypeScript 4.4.2~: This is now fixed
```
Chrome 92.0.4515.159 (Linux x86_64) perClassAccuracy renders histogram FAILED
	Error: Expected 0 to be 1.
	    at <Jasmine>
	    at src/show/tensor_test.ts:32:61 <- src/show/tensor_test.js:58:65
	    at Generator.next (<anonymous>)
	    at fulfilled (src/show/tensor_test.js:40:58)
```

- [x] tfjs (union package): Depends on converter
- [x] tfjs-node(-gpu), e2e: Depends on tfjs union.
- [x] tfjs-backend-webgpu: Done.
- [ ] tfjs-react-native: Haven't tried this package yet.

These changes will let us add the `useUnknownInCatchVariables` and `noImplicitOverride` flags to the tsconfig (in a separate PR).

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5561)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
Thank you so much for go through this and get our code to be ts 4 compatible. 

> Reviewed 2 of 3 files at r2, 2 of 2 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 6 of 7 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, 2 of 2 files at r10, 33 of 41 files at r11, 2 of 2 files at r12, 1 of 2 files at r13, 16 of 16 files at r15, 3 of 3 files at r16, 2 of 2 files at r17, 4 of 4 files at r18, 4 of 4 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5561#-:-Mo-YQSI0mxN-kihlVas:bxrrxts)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-converter/src/operations/executors/dynamic_executor.ts, line 53 at r20](https://reviewable.io/reviews/tensorflow/tfjs/5561#-Mo-WreI0Jz7EmKnZ-sY:-Mo-WreJBIW-Nj2sKhUv:b26j0mx) ([raw file](https://github.com/tensorflow/tfjs/blob/acf92c9a542cf5fbcb91db6802cc39e509f4476f/tfjs-converter/src/operations/executors/dynamic_executor.ts#L53)):*
> ```XML
> export const executeOp: InternalOpAsyncExecutor = async(
>     node: Node, tensorMap: NamedTensorsMap,
>     context: ExecutionContext, _resourceManager,
> ```

why the _resourceManager starts with `_`, should the _resourceManager to have a type?
___
*[tfjs-data/src/iterators/microphone_iterator_test.ts, line 34 at r20](https://reviewable.io/reviews/tensorflow/tfjs/5561#-Mo-XwknE4wABHf0AtId:-Mo-XwknE4wABHf0AtIe:b-91xlq4) ([raw file](https://github.com/tensorflow/tfjs/blob/acf92c9a542cf5fbcb91db6802cc39e509f4476f/tfjs-data/src/iterators/microphone_iterator_test.ts#L34)):*
> ```XML
>       const result = await microphoneIterator.next();
>       expect(result.done).toBeFalsy();
>       // tslint:disable-next-line:no-any
> ```

the `any lint ignore` should be removed, also apply for the cases in rest of the file.

**Review by mattsoulanille — COMMENTED** [review]
Thanks for the review! 

I've discovered that this is a breaking change for typescript 3.5 users. When I try to compile an app that depends on tfjs-core and backend-cpu that uses TypeScript 3.5.3, I see the following:
```
node_modules/@tensorflow/tfjs-core/dist/engine.d.ts:127:9 - error TS1086: An accessor cannot be declared in an ambient context.

127     get backend(): KernelBackend;
            ~~~~~~~
...
```

Compiling the downstream app with TS 3.7 and above results in no issues. Should we release this with version 4.0.0?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5561#-:-MoGIbBt15FZGZ7bR52A:b-id9h3b)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-converter/src/operations/executors/dynamic_executor.ts, line 53 at r20](https://reviewable.io/reviews/tensorflow/tfjs/5561#-Mo-WreI0Jz7EmKnZ-sY:-MoABxOKB-0PS5Vj8kVe:b-hs6own) ([raw file](https://github.com/tensorflow/tfjs/blob/acf92c9a542cf5fbcb91db6802cc39e509f4476f/tfjs-converter/src/operations/executors/dynamic_executor.ts#L53)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why the _resourceManager starts with `_`, should the _resourceManager to have a type?
</blockquote></details>

I put an underscore in front of resourceManager because it's unused, but that's actually against the style guide. Fixed.

I also added its type, although we could actually remove the types from all these function arguments since they are specified by InternalOpAsyncExecutor (although I'm not sure if this would be against the style guide).
___
*[tfjs-data/src/iterators/microphone_iterator_test.ts, line 34 at r20](https://reviewable.io/reviews/tensorflow/tfjs/5561#-Mo-XwknE4wABHf0AtId:-MoGIVo50OjBRsUhcPZT:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/acf92c9a542cf5fbcb91db6802cc39e509f4476f/tfjs-data/src/iterators/microphone_iterator_test.ts#L34)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

the `any lint ignore` should be removed, also apply for the cases in rest of the file.
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
I agree if it is breaking for 3.5.x, we should either figure out a work around, or do a major release.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5561#-:-MoHEeIyAbUHpLQ7CEJE:bgbkii8)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — COMMENTED** [review]
not sure if this is the solution:
https://github.com/storybookjs/storybook/issues/9463

can you try `readonly hackend(): KernelBackend;`?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5561#-:-MoHG1Nk9JGTeV_GjKxm:b-uk0zn4)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by mattsoulanille — COMMENTED** [review]
Unfortunately, that solution only works if you're providing manually written declaration files, since it requires editing them.

This might not be a hugely breaking change. Users can upgrade to 3.6.2, which has fewer breaking changes from 3.5.3 than 3.7 has. Alternatively, they can add `skipLibCheck: true` to their tsconfigs, which isn't recommended but does fix / hide the issue.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5561#-:-MoZbrk90Gtvlo71iRxf:bkhgcml)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5561)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Comment by mattsoulanille** [comment]
Superseded by #6346.

**Pull request closed without merging**
