### PR TITLE
[Refactoring] Clean up recurrent cells and layers getConfig

### PR DESCRIPTION
**Pull request by dikatok**
The purpose of this PR is to clean up the `getConfig` method related to `recurrent` and `convolutional_recurrent` layers and cells for better readability.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3880)

### CODE REVIEW

**Comment by dikatok** [comment]
Regarding recurrent_test.ts, the actual changes are in the following lines:

https://github.com/tensorflow/tfjs/blob/315b68bfe7a5a6280ef841c33861f701b5d169d0/tfjs-layers/src/layers/recurrent_test.ts#L1549

https://github.com/tensorflow/tfjs/blob/315b68bfe7a5a6280ef841c33861f701b5d169d0/tfjs-layers/src/layers/recurrent_test.ts#L1564

Not quite sure why a lot of formatting occurred.

**Review by pyu10055 — COMMENTED** [review]
Thank you for refactoring, on high level can you explain your approach to eliminate the manual hierarchical construction of the config?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3880#-:-MHCETA66aZhvhSHhGkU:b15kojo)* status: 0 of 1 approvals obtained

**Comment by dikatok** [comment]
> Thank you for refactoring, on high level can you explain your approach to eliminate the manual hierarchical construction of the config?
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3880#-:-MHCETA66aZhvhSHhGkU:b15kojo)_ status: 0 of 1 approvals obtained

Sure, here are my observations.

1. Layer `getConfig` is simply re-exposing the respective cell's `getConfig` + specific recurrent configs (`returnSequences`, `returnState`, `stateful`, etc). We can achieve the same by merging the underlying cell config and layer config, instead of repeating them.
Cautionary needs to be taken during the merge though, to avoid core config such as `layerName` to be replaced.

2. Since now we can delegate export of cell configs to themselves, we can also remove `getConfig` overrides from each RNN layers (LSTM, GRU, Stacked, ConvLSTM) and let the superclass which in this case RNN to handle it.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for explanation, overall your change looks good to me.
Can you add tests that verify the config generated in the new way matches to the config generated by original code? thanks

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3880#-:-MHJI5ym2paJPevYQaxj:b-4lpbzl)* status: 0 of 1 approvals obtained (waiting on @dikatok)

___
*[tfjs-layers/src/layers/recurrent_test.ts, line 1564 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3880#-MHJHmpJ-K7GJEqWgPHj:-MHJHmpJ-K7GJEqWgPHk:b-b9kurw) ([raw file](https://github.com/tensorflow/tfjs/blob/315b68bfe7a5a6280ef841c33861f701b5d169d0/tfjs-layers/src/layers/recurrent_test.ts#L1564)):*
> ```XML
>     const yPrime = layer.apply(x) as Tensor;
>     expectTensorsClose(yPrime, y);
>     expect(layerPrime.getConfig()['recurrentActivation'])
> ```

can you test against a constant config, comparing two same type of layers does not seem to guarantee no change to the exist behavior.

**Comment by dikatok** [comment]
> Thank you for explanation, overall your change looks good to me.
> Can you add tests that verify the config generated in the new way matches to the config generated by original code? thanks
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3880#-:-MHJI5ym2paJPevYQaxj:b-4lpbzl)_ status: 0 of 1 approvals obtained (waiting on @dikatok)
> 
> _[tfjs-layers/src/layers/recurrent_test.ts, line 1564 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3880#-MHJHmpJ-K7GJEqWgPHj:-MHJHmpJ-K7GJEqWgPHk:b-b9kurw) ([raw file](https://github.com/tensorflow/tfjs/blob/315b68bfe7a5a6280ef841c33861f701b5d169d0/tfjs-layers/src/layers/recurrent_test.ts#L1564)):_
> 
> > ```
> >     const yPrime = layer.apply(x) as Tensor;
> >     expectTensorsClose(yPrime, y);
> >     expect(layerPrime.getConfig()['recurrentActivation'])
> > ```
> 
> can you test against a constant config, comparing two same type of layers does not seem to guarantee no change to the exist behavior.

Added the requested tests, all values were generated from the previous version of the code. I think the new tests resolve your last comment as well?

**Comment by dikatok** [comment]
@pyu10055 friendly ping 🦝

**Review by pyu10055 — APPROVED** [review]
Thanks you for the refactoring!

> Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3880#-:-MIKGI3y-dqmp24lyCBn:b-b0ggo6)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3880)* status: 0 of 1 approvals obtained (waiting on @dikatok)

___
*[tfjs-layers/src/layers/recurrent_test.ts, line 1564 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3880#-MHJHmpJ-K7GJEqWgPHj:-MIKGNn61PuPH7S5cTcQ:b-arhccf) ([raw file](https://github.com/tensorflow/tfjs/blob/315b68bfe7a5a6280ef841c33861f701b5d169d0/tfjs-layers/src/layers/recurrent_test.ts#L1564)):*
<details><summary><i>Previously, dikatok (Andika Tanuwijaya) wrote…</i></summary><blockquote>

Added the requested tests, all values were generated from the previous version of the code. I think the new tests resolve your last comment as well? 
</blockquote></details>

thank you for adding the detail tests.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3880)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @dikatok)

**Pull request merged**
