### PR TITLE
Setup optimization target deices/browsers

### PR DESCRIPTION
**Pull request by Linchenn**
This PR updates the list of the combinations of devices and browsers. The list currently is used only for our nightly-benchmark, and I **will use the devices/browsers in this list as WebGL optimization targets**. 

Specifically, the list will have 6 combinations on desktop/laptop and 17 combinations on mobile:
1. Windows
1.1 Win 11: Chrome, Firefox, Edge
1.2 Win 7: Firefox
2. Mac - Monterey: Safari, Chrome
3. Andriod
image

4. iOS
image

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6722)

### CODE REVIEW

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6722)* status: 0 of 1 approvals obtained

___
*[`e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json` line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6722#-N8fKRjPAC9W68vVNYTH:-N8fKRjPAC9W68vVNYTI:brmgn9e) ([raw file](https://github.com/tensorflow/tfjs/blob/c3584a237a909b865a0dea100b36608f7e344ec7/e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json#L33)):*
> ```JSON
>       "device": null
>     },
>     "Windows_7_1": {
> ```

I don't know why it originally has this target for win7. Should we remove it?

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6722)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn, @mattsoulanille, and @pyu10055)

___
*[`e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json` line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6722#-N8fKRjPAC9W68vVNYTH:-N8jDw2j35dS7AohUt_a:b-tjbx4u) ([raw file](https://github.com/tensorflow/tfjs/blob/1a3f1e2b2da1a977f2adcc848663712de7b46235/e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json#L33)):*
<details><summary><i>Previously, Linchenn wrote…</i></summary><blockquote>

I don't know why it originally has this target for win7. Should we remove it?
</blockquote></details>

I think this is to capture the lowest os version that we support. We should add lowest os version test for ios and android too. Can be in a separate PR.

**Review by mattsoulanille — APPROVED** [review]
LGTM

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6722#-:-N8jEy7i5QO2V9Qmgwd3:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @Linchenn and @pyu10055)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6722)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @Linchenn)

___
*[`e2e/benchmarks/browserstack-benchmark/index.js` line 40 at r3](https://reviewable.io/reviews/tensorflow/tfjs/6722#-N8jjKzW8Ri0s0z7V0Ud:-N8jjKzW8Ri0s0z7V0Ue:b-zhba0p) ([raw file](https://github.com/tensorflow/tfjs/blob/30a683c92747c58e6b1c4e8a1c8472b4e135a9e7/e2e/benchmarks/browserstack-benchmark/index.js#L40)):*
> ```JavaScript
>     base: 'BrowserStack',
>     browser: 'chrome',
>     browser_version: '15.3',
> ```

is `15.3` the latest version of chrome? Or it is for safari? the latest of chrome should b 103+
___
*[`e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json` line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6722#-N8fKRjPAC9W68vVNYTH:-N8jjmel0SnUtiB3QdZ4:bckb7sq) ([raw file](https://github.com/tensorflow/tfjs/blob/1a3f1e2b2da1a977f2adcc848663712de7b46235/e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json#L33)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

I think this is to capture the lowest os version that we support. We should add lowest os version test for ios and android too. Can be in a separate PR.
</blockquote></details>

The firefox version is also very low, the latest is around 103+

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6722)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @Linchenn)

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6722)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @pyu10055)

___
*[`e2e/benchmarks/browserstack-benchmark/index.js` line 40 at r3](https://reviewable.io/reviews/tensorflow/tfjs/6722#-N8jjKzW8Ri0s0z7V0Ud:-N8jm_oC7h4YuPEGxHke:b-bw8e14) ([raw file](https://github.com/tensorflow/tfjs/blob/30a683c92747c58e6b1c4e8a1c8472b4e135a9e7/e2e/benchmarks/browserstack-benchmark/index.js#L40)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is `15.3` the latest version of chrome? Or it is for safari? the latest of chrome should b 103+
</blockquote></details>

Updated.
___
*[`e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json` line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6722#-N8fKRjPAC9W68vVNYTH:-N8jmMJ4DNxdR40eqpeE:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/1a3f1e2b2da1a977f2adcc848663712de7b46235/e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json#L33)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

The firefox version is also very low, the latest is around 103+
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6722)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @pyu10055)

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6722)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @pyu10055)

___
*[`e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json` line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6722#-N8fKRjPAC9W68vVNYTH:-N8kML-tBT80O5TMqUg9:bv0iq7z) ([raw file](https://github.com/tensorflow/tfjs/blob/1a3f1e2b2da1a977f2adcc848663712de7b46235/e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json#L33)):*
<details><summary><i>Previously, Linchenn wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thank you Na, Matt and Ping. Just synced with Ping, I will separate this list into two lists in a separate PR: one list contains lowest os version/devices that we support (this will be included in nightly benchmark), while another list contains the most popular devices/browsers (will be included in both nightly benchmark and benchmark for optimization)

**Pull request merged**
