### PR TITLE
[layers] [webgl] fixed failing nightly tests

### PR DESCRIPTION
**Pull request by pyu10055**
1. enabled windows tests for layers
2. updated windows chrome version to latest, it was locked at version 77 which is way behind.
3. fixed NaN propagation test failures for webgl
4. disabled threshold ostu method tests due to shader compilation error.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6001)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6001)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-layers/BUILD.bazel, line 55 at r13](https://reviewable.io/reviews/tensorflow/tfjs/6001#-Mt9bEPj9V678MB4LvaU:-Mt9bEPj9V678MB4LvaV:bnz2mpn) ([raw file](https://github.com/tensorflow/tfjs/blob/a71a4368f3e3722299c2f714e4837be4cf8b8efa/tfjs-layers/BUILD.bazel#L55)):*
> ```Starlark
>         "bs_chrome_mac",
>         "bs_firefox_mac",
>         "bs_android_9",
> ```

Why is it removed?



_Code quote:_
```Starlark
bs_android_9
```
___
*[tfjs-layers/src/losses_test.ts, line 294 at r13](https://reviewable.io/reviews/tensorflow/tfjs/6001#-Mt9bLqh4CKk-ogxAC4o:-Mt9bLqh4CKk-ogxAC4p:b-kus9pg) ([raw file](https://github.com/tensorflow/tfjs/blob/2a0186e73810c7e22ec7865bcca4034cf3ef7eed/tfjs-layers/src/losses_test.ts#L294)):*
> ```XML
> });
> 
> describeMathCPUAndWebGL2('categoricalCrossentropy', () => {
> ```

Does it not work with WebGL1?



_Code quote:_
```XML
WebGL2
```

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6001)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-layers/BUILD.bazel, line 55 at r13](https://reviewable.io/reviews/tensorflow/tfjs/6001#-Mt9bEPj9V678MB4LvaU:-Mt9dkzt6Rk39UnASm_A:bqysacd) ([raw file](https://github.com/tensorflow/tfjs/blob/a71a4368f3e3722299c2f714e4837be4cf8b8efa/tfjs-layers/BUILD.bazel#L55)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Why is it removed?
</blockquote></details>

it is very flaky and run model training on the android devices might not be our priority.
___
*[tfjs-layers/src/losses_test.ts, line 294 at r13](https://reviewable.io/reviews/tensorflow/tfjs/6001#-Mt9bLqh4CKk-ogxAC4o:-Mt9dxZW-C674rkT7RSA:b32wsm) ([raw file](https://github.com/tensorflow/tfjs/blob/2a0186e73810c7e22ec7865bcca4034cf3ef7eed/tfjs-layers/src/losses_test.ts#L294)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Does it not work with WebGL1?
</blockquote></details>

no

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6001)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-layers/src/losses_test.ts, line 294 at r13](https://reviewable.io/reviews/tensorflow/tfjs/6001#-Mt9bLqh4CKk-ogxAC4o:-Mt9e-p111WF15MhQ-hJ:b-be6j4c) ([raw file](https://github.com/tensorflow/tfjs/blob/2a0186e73810c7e22ec7865bcca4034cf3ef7eed/tfjs-layers/src/losses_test.ts#L294)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

no
</blockquote></details>

webgl resolution is too low.

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6001)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-layers/src/losses_test.ts, line 294 at r13](https://reviewable.io/reviews/tensorflow/tfjs/6001#-Mt9bLqh4CKk-ogxAC4o:-Mt9e3lf8zSScYPWt-4i:b-f91lej) ([raw file](https://github.com/tensorflow/tfjs/blob/2a0186e73810c7e22ec7865bcca4034cf3ef7eed/tfjs-layers/src/losses_test.ts#L294)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

webgl resolution is too low.
</blockquote></details>

webgl 1

**Review by lina128 — APPROVED** [review]
Thank you for the fix, Ping! LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6001#-:-Mt9ehMSD8zBHKIt22tZ:b-djjadw)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-layers/BUILD.bazel, line 55 at r13](https://reviewable.io/reviews/tensorflow/tfjs/6001#-Mt9bEPj9V678MB4LvaU:-Mt9eTFJ9Kx4dkbOsx0f:b-4hvi0m) ([raw file](https://github.com/tensorflow/tfjs/blob/a71a4368f3e3722299c2f714e4837be4cf8b8efa/tfjs-layers/BUILD.bazel#L55)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

it is very flaky and run model training on the android devices might not be our priority.
</blockquote></details>

Got it.
___
*[tfjs-layers/src/losses_test.ts, line 294 at r13](https://reviewable.io/reviews/tensorflow/tfjs/6001#-Mt9bLqh4CKk-ogxAC4o:-Mt9efMo6Wyym9KZtPKU:b-4hvi0m) ([raw file](https://github.com/tensorflow/tfjs/blob/2a0186e73810c7e22ec7865bcca4034cf3ef7eed/tfjs-layers/src/losses_test.ts#L294)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

webgl 1
</blockquote></details>

Got it.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6001)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-layers/BUILD.bazel, line 55 at r13](https://reviewable.io/reviews/tensorflow/tfjs/6001#-Mt9bEPj9V678MB4LvaU:-Mt9euHn1HnqiMSMoU37:b4wkhoz) ([raw file](https://github.com/tensorflow/tfjs/blob/a71a4368f3e3722299c2f714e4837be4cf8b8efa/tfjs-layers/BUILD.bazel#L55)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Got it.
</blockquote></details>

nit: Can you add annotation for future reference?

**Pull request merged**
