### PR TITLE
Support loading sharded models with bundleResourceIO

### PR DESCRIPTION
**Pull request by tafsiri**
Addresses https://github.com/tensorflow/tfjs/issues/3962 and https://github.com/tensorflow/tfjs/issues/3197

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4113)

### CODE REVIEW

**Comment by tafsiri** [comment]
Also add support for tfjs-react-native to the release notes script.

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4113)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @lina128, @pyu10055, and @tafsiri)

___
*[tfjs-react-native/integration_rn59/android/app/build.gradle, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4113#-MK_t34E9mDUatw-4kyS:-MK_t34E9mDUatw-4kyT:brk7xlj) ([raw file](https://github.com/tensorflow/tfjs/blob/1c1ce7649272580bb0e52b58267afbaf551773b5/tfjs-react-native/integration_rn59/android/app/build.gradle#L39)):*
> ```Gradle
>  *
>  *   // whether to bundle JS and assets in debug mode
>  *   bundleInDebug: false,/
> ```

Remove / ?

**Review by pyu10055 — APPROVED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4113)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @pyu10055, and @tafsiri)

___
*[tfjs-react-native/integration_rn59/android/app/build.gradle, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4113#-MKevlD79KrSj7WnmWEH:-MKevlD79KrSj7WnmWEI:bgbxquy) ([raw file](https://github.com/tensorflow/tfjs/blob/1c1ce7649272580bb0e52b58267afbaf551773b5/tfjs-react-native/integration_rn59/android/app/build.gradle#L93)):*
> ```Gradle
> 
> project.ext.react = [
>     entryFile: "index.js",
> ```

should the comma be removed?

**Review by tafsiri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4113)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @pyu10055)

___
*[tfjs-react-native/integration_rn59/android/app/build.gradle, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4113#-MK_t34E9mDUatw-4kyS:-MKfkbjVCbrmRuJDhmRd:b-r0l2zw) ([raw file](https://github.com/tensorflow/tfjs/blob/1c1ce7649272580bb0e52b58267afbaf551773b5/tfjs-react-native/integration_rn59/android/app/build.gradle#L39)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Remove / ?
</blockquote></details>

Its actually really handy to quickly enable and disable when testing a prod build on the phone.
___
*[tfjs-react-native/integration_rn59/android/app/build.gradle, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4113#-MKevlD79KrSj7WnmWEH:-MKfkoRO5BC99okHmhUo:biiidbb) ([raw file](https://github.com/tensorflow/tfjs/blob/1c1ce7649272580bb0e52b58267afbaf551773b5/tfjs-react-native/integration_rn59/android/app/build.gradle#L93)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should the comma be removed?
</blockquote></details>

Leaving it in makes switching from dev to prod builds on the phone easier.

**Pull request merged**
