### PR TITLE
wasm backend add LogicalNot, LogicalOr, LogicalXor

### PR DESCRIPTION
**Pull request by homfen**
1. wasm backend support LogicalNot, LogicalOr, LogicalXor
2. update bazel version(5.1.1) for macos 12.3

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6431)

### CODE REVIEW

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Thanks for the PR, @homfen. It looks like your editor has changed the format of several files in this PR, making it difficult to review due to the large number of changes. Could you please update this PR so it doesn't make formatting changes? Once it's updated, I'll review it for content. Thanks!

**Comment by homfen** [comment]
@mattsoulanille updated

**Review by mattsoulanille — COMMENTED** [review]
Thanks for the update. I had several comments on this PR, but I didn't know the right solutions to them. I didn't want to point you towards a bad solution, so I ended up addressing them and making the changes myself. I've committed them to this PR.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6431#-:-N3QOQQc3WErKcdMQzq6:b-3n539b)* status: 0 of 1 approvals obtained (waiting on @homfen)

___
*[`tfjs-backend-wasm/src/cc/binary.h` line 35 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6431#-N3QOtaL9n8mN--fI5Ik:-N3QOtaL9n8mN--fI5Il:bg1g8zl) ([raw file](https://github.com/tensorflow/tfjs/blob/ce05f55b68a7330c05807c9d829e354c90c28f74/tfjs-backend-wasm/src/cc/binary.h#L35)):*
> ```objc
> template <class I, class O>
> void binary_not(const I *a_buf, const size_t a_size, O *out_buf, O operation(I),
>                 const size_t *a_shape_ptr, const size_t a_rank);
> ```

This template is likely not necessary, since unary functions are very simple.
___
*[`tfjs-backend-wasm/src/cc/binary.h` line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6431#-N3QOvz69NrrWKovAAwy:-N3QOvz69NrrWKovAAwz:b77b5ki) ([raw file](https://github.com/tensorflow/tfjs/blob/ce05f55b68a7330c05807c9d829e354c90c28f74/tfjs-backend-wasm/src/cc/binary.h#L68)):*
> ```objc
> 
> void compare_not(const int a_id, const size_t *a_shape_ptr,
>                  const size_t a_shape_len, const int out_id,
> ```

This should be defined in unary.h



_Code quote:_
```objc
void compare_not(const int a_id, const size_t *a_shape_ptr,
                 const size_t a_shape_len, const int out_id,
                 bool operation(bool));
```
___
*[`tfjs-backend-wasm/src/cc/binary.cc` line 83 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6431#-N3QR8D8-P9esjVfypob:-N3QR8D8-P9esjVfypoc:b-5xb9tp) ([raw file](https://github.com/tensorflow/tfjs/blob/ce05f55b68a7330c05807c9d829e354c90c28f74/tfjs-backend-wasm/src/cc/binary.cc#L83)):*
> ```cpp
> 
> template <class I, class O>
> void binary_not(const I *a_buf, const size_t a_size, O *out_buf,
> ```

I don't think unary ops can be broadcast, so this logic shouldn't be necessary.



_Code quote:_
```cpp
template <class I, class O>
void binary_not(const I *a_buf, const size_t a_size, O *out_buf,
                O operation(I), const size_t *a_shape_ptr,
                const size_t a_rank) {
  std::vector<size_t> a_shape(a_shape_ptr, a_shape_ptr + a_rank);
  const std::vector<size_t> result_strides =
      tfjs::util::compute_strides(a_shape);
  const size_t result_size = tfjs::util::size_from_shape(a_shape);
  const std::vector<size_t> a_strides = tfjs::util::compute_strides(a_shape);
  const std::vector<size_t> a_broadcast_dims =
      tfjs::util::get_broadcast_dims(a_shape, a_shape);

  if (a_broadcast_dims.size() == 0) {
    for (size_t i = 0; i < result_size; ++i) {
      out_buf[i] = operation(a_buf[i % a_size]);
    }
  } else {
    for (size_t i = 0; i < result_size; ++i) {
      const std::vector<size_t> loc =
          tfjs::util::offset_to_loc(i, result_strides);

      std::vector<size_t> a_loc =
          std::vector<size_t>(loc.end() - a_rank, loc.end());
      for (size_t j = 0; j < a_broadcast_dims.size(); ++j) {
        const size_t d = a_broadcast_dims[j];
        a_loc[d] = 0;
      }
      const size_t a_idx = tfjs::util::loc_to_offset(a_loc, a_strides);

      out_buf[i] = operation(a_buf[a_idx]);
    }
  }
}
```

**Review by mattsoulanille — APPROVED** [review]
LGTM

> Reviewed 13 of 14 files at r1, 5 of 8 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6431#-:-N3QUjiu-0nqi73PjGa1:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6431)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @homfen)

___
*[`tfjs-backend-wasm/src/cc/kernels/LogicalNot.cc` line 1 at r5](https://reviewable.io/reviews/tensorflow/tfjs/6431#-N3Qk3Li7J7tAPB4mQAT:-N3Qk3Li7J7tAPB4mQAU:bb6ht37) ([raw file](https://github.com/tensorflow/tfjs/blob/3afe0b51dd315a7e8d9d9cf4e254d3bcde6064ca/tfjs-backend-wasm/src/cc/kernels/LogicalNot.cc#L1)):*
> ```cpp
> /* Copyright 2019 Google LLC. All Rights Reserved.
> ```

2022



_Code quote:_
```cpp
2019
```

**Pull request merged**
