### PR TITLE
Build tfjs-backend-webgpu with Bazel

### PR DESCRIPTION
**Pull request by haoyunfeix**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5362)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
Thanks for starting on this conversion! However, I think this PR may need to wait for `tfjs-converter` to be converted to Bazel, since it depends on converter. You can track the progress of converter at #5388, but I'll ping this PR when converter is merged.

**Comment by mattsoulanille** [comment]
Looks like this failed Bazel lint. If you run `yarn bazel:format` (and maybe also `yarn bazel:lint-fix`), it should fix the issues.

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Thanks for taking on this migration!

A few steps have been added to the migration doc since this PR was first created, so there are a few things that need to be done before it can be merged. You can take a look at the [Notes for Reviewing PRs](https://github.com/tensorflow/tfjs/blob/master/BAZEL_MIGRATION.md#notes-for-reviewing-prs) section of the migration doc for a quick list, or see below.

× The package should be added to `BAZEL_PACKAGES` in e2e/ and scripts/.
✓ The npm package includes the readme and all other necessary files.
✓ The generated bundles look correct when comparing their visualizations against the current bundles' visualizations.
✓ The package can be omitted from the link package since it is not used in any downstream packages.
✓ No browser tests are currently supposed to run in nightly CI since BrowserStack does not yet support Chrome flags.
✓ Tests include all test files and correctly run on the webgpu backend.
× The cloudbuild.yml file can be removed since tests will run in Bazel (actually, no tests are currently configured because BrowserStack doesn't support Chrome flags yet, but it will still build). Also, remove the package from `/scripts/package_dependencies.json`.
✓ package.json rules look good. A few ones that may be unused could perhaps be removed.
✓ pkg_npm rule is tagged with "ci".
✓ build-npm script looks good.
✓ Bundle file sizes look good.
× tfjs-backend-webgpu should be added to the repo-wide tslint tsconfig.

Thanks!

> Reviewed 13 of 15 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5362#-:-Mo-oGj4C0-h7SB5k60Z:by39aq4)* status: 0 of 1 approvals obtained (waiting on @haoyunfeix)

___
*[tfjs-backend-webgpu/BUILD.bazel, line 40 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0ZNA52Q8rv6VuSow-:-Mo0ZNA52Q8rv6VuSow0:bge9lu7) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/BUILD.bazel#L40)):*
> ```
>         "@npm//@webgpu/types",
> ```
This dependency might not be necessary.
___
*[tfjs-backend-webgpu/BUILD.bazel, line 118 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0lROU0h5hXvM7VPnY:-Mo0lROU0h5hXvM7VPnZ:bt7qt76) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/BUILD.bazel#L118)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> js_library(
>     name = "package_json",
>     srcs = [
>         ":package.json",
>     ],
> )
> ```
</details>

I don't think any other targets depend on this.
___
*[tfjs-backend-webgpu/package.json, line 17 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0dmJCEPOFFAJJAucR:-Mo0dmJCEPOFFAJJAucS:bw9lzzy) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L17)):*
> ```
>     "build-link-package-core": "cd ../link-package-core && yarn build",
>     "build-deps": "yarn build-link-package-core",
>     "build-deps-ci": "yarn build-link-package-core",
> ```
These are no longer necessary since Bazel handles building deps.
___
*[tfjs-backend-webgpu/package.json, line 21 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0dsHV9bH_WBriaJFW:-Mo0dsHV9bH_WBriaJFX:b-7yr4g0) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L21)):*
> ```
>     "link-local": "yalc link",
>     "publish-local": "rimraf dist/ && yarn build && rollup -c && yalc push",
> ```
I'm not sure these are used anymore.
___
*[tfjs-backend-webgpu/package.json, line 22 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0duoL4Bm1bDOAeFk1:-Mo0duoL4Bm1bDOAeFk2:bah071q) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L22)):*
> ```
>  "publish-local": "rimraf dist/ && yarn build && rollup -c && yalc push",
> ```
Same with this. I don't think it's used.
___
*[tfjs-backend-webgpu/package.json, line 26 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0dzzeDzoYVd5zhsiN:-Mo0dzzf4vB5hQHzyhAh:bnqq4jx) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L26)):*
> ```
>     "test-ci": "./scripts/test-ci.sh",
> ```
This can probably be removed since tests will be run by Bazel. The `test-ci.sh` script can be removed as well.
___
*[tfjs-backend-webgpu/package.json, line 28 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0e4TMAHegD--Kwtj1:-Mo0e4TMAHegD--Kwtj2:b-43zbxc) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L28)):*
> ```
>     "unlink-local": "yalc remove"
> ```
I think this is unused.
___
*[tfjs-backend-webgpu/package.json, line 66 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0eCreDVLRefVdCDpv:-Mo0eCreDVLRefVdCDpw:b6n9s7u) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L66)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>   },
>   "sideEffects": [
>     "./dist/register_all_kernels.js",
>     "./dist/flags_webgpu.js",
>     "./dist/index.js",
>     "./dist/register_all_kernels.mjs",
>     "./dist/flags_webgpu.mjs",
>     "./dist/index.mjs",
>     "./src/register_all_kernels.mjs",
>     "./src/flags_webgpu.mjs",
>     "./src/index.mjs"
>   ]
> }
> ```
</details>

If tfjs-backend-webgpu is bundled correctly without sideEffects specified (i.e. the bundler determines the side effects), then we can probably leave them out, which is usually a better and less error-prone approach.
___
*[tfjs-backend-webgpu/src/BUILD.bazel, line 55 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0fe184QKAoUVzV5Ti:-Mo0fe184QKAoUVzV5Tj:badh23r) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/src/BUILD.bazel#L55)):*
> ```
>         "@npm//@types",
> ```
This can probably be removed.
___
*[tfjs-backend-webgpu/src/BUILD.bazel, line 92 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0g6ro94nI6iRPs6qx:-Mo0g6ro94nI6iRPs6qy:bkhn9v5) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/src/BUILD.bazel#L92)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         # webworker tests call 'require('@tensorflow/tfjs')', which
>         # is external to the test bundle.
>         # Note: This is not a bazel target. It's just a string.
>         "@tensorflow/tfjs",
>         "worker_threads",
> ```
</details>

Since #5784, webworker tests are no longer part of the shared test suite (they only run in core now since they only test with the cpu backend anyway), so these lines can probably be removed.
___
*[tools/tfjs_web_test.bzl, line 81 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0jfuVEklyeplpZdQL:-Mo0jfuVEklyeplpZdQM:b-o1dmjb) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tools/tfjs_web_test.bzl#L81)):*
> ```
>         browser = browsers[0] if browsers[0] == "chrome_webgpu" else "",
> ```
Instead of using the first browser in the browsers list, it would be better to add an argument to the `tfjs_web_test` macro that specifies which browser to use locally:

```starlark
def tfjs_web_test(name, ci = True, args = [], local_browser = "", **kwargs):
    ...
     _make_karma_config(
        ...
        browser = local_browser
    )
```
___
*[tools/tfjs_web_test.bzl, line 97 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0kGA0CQi_-i_4I_ox:-Mo0kGA0CQi_-i_4I_oy:b6e9lvr) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tools/tfjs_web_test.bzl#L97)):*
> ```
>         if browser == "chrome_webgpu":
>             continue
> ```
The above change also lets you avoid this check, since the `chrome_webgpu` browser will be passed in `local_browser` instead of `browsers`.

A potential TODO for me is to rewrite this macro to use [`karma_web_test_suite`](https://bazelbuild.github.io/rules_nodejs/Karma.html#karma_web_test_suite) instead of `karma_web_test`.

**Review by haoyunfeix — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5362)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-backend-webgpu/BUILD.bazel, line 40 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0ZNA52Q8rv6VuSow-:-Mo3YdlT1ZGwzG9mDk5d:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/BUILD.bazel#L40)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>         "@npm//@webgpu/types",
> ```
This dependency might not be necessary.
</blockquote></details>

Done.
___
*[tfjs-backend-webgpu/BUILD.bazel, line 118 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0lROU0h5hXvM7VPnY:-Mo3YgWs5j1YErf0g1jV:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/BUILD.bazel#L118)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> js_library(
>     name = "package_json",
>     srcs = [
>         ":package.json",
>     ],
> )
> ```
I don't think any other targets depend on this.
</blockquote></details>

Done.
___
*[tfjs-backend-webgpu/package.json, line 17 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0dmJCEPOFFAJJAucR:-Mo3Yi6oE-p2axo1wPKR:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L17)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     "build-link-package-core": "cd ../link-package-core && yarn build",
>     "build-deps": "yarn build-link-package-core",
>     "build-deps-ci": "yarn build-link-package-core",
> ```
These are no longer necessary since Bazel handles building deps.
</blockquote></details>

Done.
___
*[tfjs-backend-webgpu/package.json, line 21 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0dsHV9bH_WBriaJFW:-Mo3Yj498ZkfEDvVgjY3:b-3rm8pd) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L21)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     "link-local": "yalc link",
>     "publish-local": "rimraf dist/ && yarn build && rollup -c && yalc push",
> ```
I'm not sure these are used anymore.
</blockquote></details>

Sometimes I need to link local changes to demos which using dependencies of WebGPU, for example "`@tensorflow/tfjs-backend-webgpu": "^0.0.1-alpha.8"`, `yarn yalc link` is recommend to deal with this.
___
*[tfjs-backend-webgpu/package.json, line 22 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0duoL4Bm1bDOAeFk1:-Mo3_Ydo65NtLgdpVj_G:b2nreh6) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L22)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>  "publish-local": "rimraf dist/ && yarn build && rollup -c && yalc push",
> ```
Same with this. I don't think it's used.
</blockquote></details>

Same as above.
___
*[tfjs-backend-webgpu/package.json, line 26 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0dzzeDzoYVd5zhsiN:-Mo3_c7R0jHYw2nJoFvq:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L26)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     "test-ci": "./scripts/test-ci.sh",
> ```
This can probably be removed since tests will be run by Bazel. The `test-ci.sh` script can be removed as well.
</blockquote></details>

Done.
___
*[tfjs-backend-webgpu/package.json, line 28 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0e4TMAHegD--Kwtj1:-Mo3_dED5ZfKcudTt00s:b2nreh6) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L28)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     "unlink-local": "yalc remove"
> ```
I think this is unused.
</blockquote></details>

Same as above.
___
*[tfjs-backend-webgpu/package.json, line 66 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0eCreDVLRefVdCDpv:-Mo3_hE68yblFejdtgdD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L66)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>   },
>   "sideEffects": [
>     "./dist/register_all_kernels.js",
>     "./dist/flags_webgpu.js",
>     "./dist/index.js",
>     "./dist/register_all_kernels.mjs",
>     "./dist/flags_webgpu.mjs",
>     "./dist/index.mjs",
>     "./src/register_all_kernels.mjs",
>     "./src/flags_webgpu.mjs",
>     "./src/index.mjs"
>   ]
> }
> ```
If tfjs-backend-webgpu is bundled correctly without sideEffects specified (i.e. the bundler determines the side effects), then we can probably leave them out, which is usually a better and less error-prone approach.
</blockquote></details>

Done.
___
*[tfjs-backend-webgpu/src/BUILD.bazel, line 55 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0fe184QKAoUVzV5Ti:-Mo3_jFDD4J0ee8VcL4M:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/src/BUILD.bazel#L55)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>         "@npm//@types",
> ```
This can probably be removed.
</blockquote></details>

Done.
___
*[tfjs-backend-webgpu/src/BUILD.bazel, line 92 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0g6ro94nI6iRPs6qx:-Mo3_kbY0r665GH-ng1u:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/src/BUILD.bazel#L92)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>         # webworker tests call 'require('@tensorflow/tfjs')', which
>         # is external to the test bundle.
>         # Note: This is not a bazel target. It's just a string.
>         "@tensorflow/tfjs",
>         "worker_threads",
> ```
Since #5784, webworker tests are no longer part of the shared test suite (they only run in core now since they only test with the cpu backend anyway), so these lines can probably be removed.
</blockquote></details>

Done.
___
*[tools/tfjs_web_test.bzl, line 81 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0jfuVEklyeplpZdQL:-Mo3_ma2B5QUffhL3OgA:b-e8mv58) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tools/tfjs_web_test.bzl#L81)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>         browser = browsers[0] if browsers[0] == "chrome_webgpu" else "",
> ```
Instead of using the first browser in the browsers list, it would be better to add an argument to the `tfjs_web_test` macro that specifies which browser to use locally:

```starlark
def tfjs_web_test(name, ci = True, args = [], local_browser = "", **kwargs):
    ...
     _make_karma_config(
        ...
        browser = local_browser
    )
```
</blockquote></details>

Good idea! I changed a little by using local_browser in kwargs, so that it won't have to change others tfjs_web_test usage.
And I added a point that if local_browser is defined then browserstack testing will skip.
___
*[tools/tfjs_web_test.bzl, line 97 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0kGA0CQi_-i_4I_ox:-Mo3ak4o6XuA0RwL-TID:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tools/tfjs_web_test.bzl#L97)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>         if browser == "chrome_webgpu":
>             continue
> ```
The above change also lets you avoid this check, since the `chrome_webgpu` browser will be passed in `local_browser` instead of `browsers`.

A potential TODO for me is to rewrite this macro to use [`karma_web_test_suite`](https://bazelbuild.github.io/rules_nodejs/Karma.html#karma_web_test_suite) instead of `karma_web_test`.
</blockquote></details>

Done.

**Comment by haoyunfeix** [comment]
@qjia7 @axinging @xhcao @gyagp @mattsoulanille PTAL, Thanks.

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Thanks for the changes! I have two more comments, and then I think it will be ready to be merged.

> Reviewed 11 of 12 files at r5, 3 of 3 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5362#-:-Mo51JOs1S9a-jx4FQRW:b-5h1og)* status: 0 of 1 approvals obtained (waiting on @haoyunfeix)

___
*[tfjs-backend-webgpu/package.json, line 21 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0dsHV9bH_WBriaJFW:-Mo4qpUZEbLjaPXdZhIJ:by9vkk) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L21)):*
<details><summary><i>Previously, haoyunfeix (Hao Yunfei) wrote…</i></summary><blockquote>

Sometimes I need to link local changes to demos which using dependencies of WebGPU, for example "`@tensorflow/tfjs-backend-webgpu": "^0.0.1-alpha.8"`, `yarn yalc link` is recommend to deal with this.
</blockquote></details>

In that case, we will need to modify this, since Bazel puts its outputs in `dist/bin/tfjs-backend-webgpu/tfjs-backend-webgpu_pkg/` instead of in `tfjs-backend-webgpu/dist`.

Maybe something like this would work: `yarn build && cd ../dist/bin/tfjs-backend-webgpu/tfjs-backend-webgpu_pkg && yalc link` (or with `yalc push`). 

I'm not sure if the above command will work correctly across `bazel clean`s, since I think that causes Bazel to delete the output directory and symlink a new one in its place. Depending on how yalc works, you may need to re-run it every time you run `bazel clean`, but it should work correctly across `bazel build`s.
___
*[tools/tfjs_web_test.bzl, line 81 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0jfuVEklyeplpZdQL:-Mo50AK_42nLZcvi1ybN:bv85abd) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tools/tfjs_web_test.bzl#L81)):*
<details><summary><i>Previously, haoyunfeix (Hao Yunfei) wrote…</i></summary><blockquote>

Good idea! I changed a little by using local_browser in kwargs, so that it won't have to change others tfjs_web_test usage.
And I added a point that if local_browser is defined then browserstack testing will skip.
</blockquote></details>

Thanks! This looks good, but I think we should still let BrowserStack browsers run even if a local_browser is specified. This will be useful  when BrowserStack supports changing Chrome arguments because then we'll want to test backend-webgpu locally and on BrowserStack. Until then, we can pass `browsers = []` when using `tfjs_web_test` to disable BrowserStack tests.

**Review by mattsoulanille — APPROVED** [review]
LGTM with one nit about yalc. I'll merge this as soon as possible, though, and the yalc nit can be fixed in another tiny PR if it doesn't make it into this one.

> Reviewed 3 of 4 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5362#-:-MoK8NmK1JhY9IZ3usvt:b88ghnz)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[tfjs-backend-webgpu/package.json, line 21 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5362#-Mo0dsHV9bH_WBriaJFW:-MoK7YOSAkvpvgJaWlIJ:bpwq6n6) ([raw file](https://github.com/tensorflow/tfjs/blob/638c1c997c584239ddfff34c4f2b4555e454a2c4/tfjs-backend-webgpu/package.json#L21)):*
<details><summary><i>Previously, haoyunfeix (Hao Yunfei) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nit: I read up a bit on Yalc and did some experiments. Using `yalc link` in this package will not work with Bazel since Bazel does not use node_modules to find @tensorflow-scoped dependencies. That means linking @tensorflow/tfjs-core will not work.

On the other hand, if you want to build @tensorflow/tfjs-backend-webgpu and then test it in another package, `cd ../dist/bin/tfjs-backend-webgpu/tfjs-backend-webgpu_pkg && yalc publish` should work correctly.

**Comment by mattsoulanille** [comment]
Looks like one of our Cloudbuild triggers happened twice for some reason? I'm going to re-run it.

**Pull request merged**
