### PR TITLE
webgl: Support uniforms for pack/unpack programs

### PR DESCRIPTION
**Pull request by qjia7**
BUG: #5205

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5835)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
Thank you Jiajia! LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5835#-:-MoKfnwY0g5U4Hf-HIPj:b-6v9dsh)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by lina128 — COMMENTED** [review]
Jiajia, how do you test the change?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5835#-:-MoKgDi712vxerxqrBit:bri1wbj)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by qjia7 — COMMENTED** [review]
Firstly, I will make sure all `yarn test` are `pass` enabling/disabling `WEBGL_USE_SHAPES_UNIFORMS`.
Secondly, I tested mesh_128 model in benchmarks, which includes 5 `PackProgram` binarys and 5 `UnpackProgram` binarys in `binaryCache` in `backend_webgl.ts` when enable  `WEBGL_USE_SHAPES_UNIFORMS`. With this PR, only 1 `PackProgram` binary and 1 `UnpackProgram` binary are left.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5835#-:-MoM6EGZ4tYGoBgjhw42:b8w4kh0)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5835)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)

**Comment by qjia7** [comment]
Please help merge it if no more comments.

**Pull request merged**
