### PR TITLE
Fix nightly benchmark

### PR DESCRIPTION
**Pull request by Linchenn**
This PR:
1. If a certain benchmark target fails, records the error, instead of throwing out an error and terminate the program.
2. Adds delays between initiating runners to resolve executable's race condition (`spawn ETXTBSY` error).
3. Update model list.
4. Increase timeout to 4h (then, it starts at 3am and ends at 7am). Even though it could not complete within 4h, we do not want it to take too much time.
5.  Removes `wasm` backend, because we do not have enough to complete benchmarking `webgl` backend now.

I have [run](https://pantheon.corp.google.com/cloud-build/builds;region=global/d107dd4e-f598-4be2-8685-cf7ac4b7c3ac;step=1?project=learnjs-174218) it with timeout 3h and it worked, even though it was terminated because of timeout:
```bash
cd e2e/benchmarks/browserstack-benchmark/
gcloud builds submit ../../../ --config=cloudbuild.yml
```

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6771)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
Thank you for fixing these hard bugs, this is great!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6771#-:-N9rBPtOEXmIT7H39agn:b1nxrbn)* status: 0 of 1 approvals obtained (waiting on @Linchenn and @pyu10055)

___
*[`e2e/benchmarks/browserstack-benchmark/app.js` line 247 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6771#-N9rCB6_9QgbzxvEFyTa:-N9rCB6_9QgbzxvEFyTb:buws484) ([raw file](https://github.com/tensorflow/tfjs/blob/9570c46239df9cf542505741081072529b9fd810/e2e/benchmarks/browserstack-benchmark/app.js#L247)):*
> ```JavaScript
>   const numFailed = cliArgs.maxTries - triesLeft;
>   // The delay increase exponentially when benchmark fails.
>   const delayInitiatingRunnerTimeMs = tabIndex * (3 ** numFailed) * 1000;
> ```

Just for my understanding, if numFailed is 0, you basically just insert a setTimeout(fn, 0), right?



_Code quote:_
```JavaScript
numFailed
```
___
*[`e2e/benchmarks/browserstack-benchmark/app.js` line 247 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6771#-N9rCLPyAlPOuxdU88MT:-N9rCLPyAlPOuxdU88MU:b3kqt) ([raw file](https://github.com/tensorflow/tfjs/blob/9570c46239df9cf542505741081072529b9fd810/e2e/benchmarks/browserstack-benchmark/app.js#L247)):*
> ```JavaScript
>   const numFailed = cliArgs.maxTries - triesLeft;
>   // The delay increase exponentially when benchmark fails.
>   const delayInitiatingRunnerTimeMs = tabIndex * (3 ** numFailed) * 1000;
> ```

*



_Code quote:_
```JavaScript
**
```

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6771)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`e2e/benchmarks/browserstack-benchmark/app.js` line 247 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6771#-N9rCLPyAlPOuxdU88MT:-N9rD9LE25RJsCjk_t3Q:beujq8g) ([raw file](https://github.com/tensorflow/tfjs/blob/9570c46239df9cf542505741081072529b9fd810/e2e/benchmarks/browserstack-benchmark/app.js#L247)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

*
</blockquote></details>

`a**n` is used as `a to the power of n` here. 
___
*[`e2e/benchmarks/browserstack-benchmark/app.js` line 247 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6771#-N9rCB6_9QgbzxvEFyTa:-N9rDTsNENcT6upQRpKL:b-rgdm9k) ([raw file](https://github.com/tensorflow/tfjs/blob/9570c46239df9cf542505741081072529b9fd810/e2e/benchmarks/browserstack-benchmark/app.js#L247)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Just for my understanding, if numFailed is 0, you basically just insert a setTimeout(fn, 0), right?
</blockquote></details>

If `numFailed ` is 0, then `3 ** numFailed` will be `1`.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6771)* status: 0 of 1 approvals obtained (waiting on @lina128 and @Linchenn)

___
*[`e2e/benchmarks/browserstack-benchmark/cloudbuild.yml` line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6771#-N9rJMR26lAI0BAWocVT:-N9rJMR26lAI0BAWocVU:b3uajwd) ([raw file](https://github.com/tensorflow/tfjs/blob/efe8c28c6f2c6fdf471930a5e65a90baaa7f2926/e2e/benchmarks/browserstack-benchmark/cloudbuild.yml#L26)):*
> ```YAML
>     - versionName: projects/834911136599/secrets/FIREBASE_KEY/versions/latest
>       env: 'FIREBASE_KEY'
> timeout: 14400s
> ```

does this work with the cloud instance time limit? I think Matt mention we are on 1 hour limit right now.

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6771)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`e2e/benchmarks/browserstack-benchmark/cloudbuild.yml` line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6771#-N9rJMR26lAI0BAWocVT:-N9rM1ME2H3ATlLxipPF:baf54ff) ([raw file](https://github.com/tensorflow/tfjs/blob/efe8c28c6f2c6fdf471930a5e65a90baaa7f2926/e2e/benchmarks/browserstack-benchmark/cloudbuild.yml#L26)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

does this work with the cloud instance time limit? I think Matt mention we are on 1 hour limit right now.
</blockquote></details>

Done. Let me check with Matt about the cloud instance time limit later, and we can keep it as 1h for now.

**Comment by Linchenn** [comment]
FYI, just removed rolling back the browser version for win11 and I am fixing it in https://github.com/tensorflow/tfjs/pull/6772 to enable software WebGL. After it, win11 with the latest chrome works.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6771)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6771#-:-NAG4GyF8dOMQ17XRGwF:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

**Pull request merged**
