### PR TITLE
webgpu: Add conv2dByMatMul

### PR DESCRIPTION
**Pull request by qjia7**
PERF

With this change, the PoseNet demo increases 1 fps.

Meanwhile, this patch unifies the behavior between
dispatchLayout and dispatch thread identification values.
y -> column
x -> row

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2242)

### CODE REVIEW

**Comment by qjia7** [comment]
@annxingyuan @kainino0x Please take a look.
I don't have the permission to look at the failures. Not sure what they are. But all the local tests pass and the PoseNet demo works well.

**Comment by qjia7** [comment]
Solved the `yarn lint` error. Please take a look.

**Comment by annxingyuan** [comment]
Thank you @qjia7 ! Could you just explain a bit more what you mean by "unifies the behavior between dispatchLayout and dispatch thread identification values"?

**Comment by qjia7** [comment]
In the matmul algorithm, we directly use globalRow = gl_GlobalInvocationID.y and globalCol = gl_GlobalInvocationId.x. I think globalRow is in the range of [0, outputShape[1]) and globalCol is in the range of [0, outputShape[2]). So the correct mapping between dispatchLayout and outputShape should be dispatchLayout = {x: [2], y: [1], z[0]} so that gl_GlobalInvocationID.x can correspond to outputShape[2] and gl_GlobalInvocationID.y can correspond to OutputShape[1].

If we don't do this change from `this.dispatchLayout = {x: [1], y:[2], z:[0]}` to `this.dispatchLayout = {x: [2], y:[1], z[0]}`, the PoseNet demo won't get correct result.

**Pull request merged**
