### PR TITLE
Allow user to provide metadata and store in model.json

### PR DESCRIPTION
**Pull request by lina128**
Fixed https://github.com/tensorflow/tfjs/issues/3987

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4187)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you Na, one concern is backward compatibility, model.json files that are generated by previous version, it is signature cannot be loaded properly (in graph executor). It would be good to check the tfjs version and retrieve signature from metadata if it is before than 2.7.0

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4187#-:-MLOQD5p72eqAS_3xOx6:b8hyad4)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[e2e/integration_tests/metadata.py, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLONBvSE1E483RrLs1o:-MLONBvSE1E483RrLs1p:bb6ht35) ([raw file](https://github.com/tensorflow/tfjs/blob/f93b588ddd47dc1c9b9920fcb2937391665f9729/e2e/integration_tests/metadata.py#L2)):*
> ```Python
> # @license
> # Copyright 2019 Google LLC. All Rights Reserved.
> ```

2020
___
*[e2e/integration_tests/metadata.py, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLON4yG-JqnXNfF-seB:-MLON4yG-JqnXNfF-seC:b1c8hi2) ([raw file](https://github.com/tensorflow/tfjs/blob/f93b588ddd47dc1c9b9920fcb2937391665f9729/e2e/integration_tests/metadata.py#L53)):*
> ```Python
> _tmp_dir = os.path.join(curr_dir, 'metadata')
> 
> def _test_model_with_metadata():
> ```

rename the method to _create_model_with_metadata, since this file does not test anything.
___
*[e2e/integration_tests/metadata.py, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLOM3sz9-hx0qhvWfil:-MLOM3sz9-hx0qhvWfim:b3k7h9q) ([raw file](https://github.com/tensorflow/tfjs/blob/f93b588ddd47dc1c9b9920fcb2937391665f9729/e2e/integration_tests/metadata.py#L66)):*
> ```Python
>   with open(metadata2_path, 'w') as f:
>     f.write(json.dumps(metadata2))
>   metadata_option = 'metadata1:'+metadata1_path+';'+'metadata2:'+metadata2_path
> ```

our other parameter uses comma as separator, is it possible to be consistent with that?
___
*[tfjs-converter/python/tensorflowjs/converters/converter.py, line 734 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLONZ5DA0P2zGg76uRI:-MLONZ5DA0P2zGg76uRJ:b-5m80xz) ([raw file](https://github.com/tensorflow/tfjs/blob/f93b588ddd47dc1c9b9920fcb2937391665f9729/tfjs-converter/python/tensorflowjs/converters/converter.py#L734)):*
> ```Python
>       type=str,
>       help='Attach user defined metadata in format key:path/metadata.json '
>       'Separate multiple metadata files by semicolon.'
> ```

will comma as separator work?

**Review by lina128 — COMMENTED** [review]
Thanks for the review, Ping, especially the backward compatibility, nice catch! I added version checking and added an e2e test to load old model version. PTAL.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4187#-:-MLP-lnnB2FCy6cV4uMR:b-hmnbwl)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[e2e/integration_tests/metadata.py, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLONBvSE1E483RrLs1o:-MLOfVIO5_sWRGY4uqG3:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/f93b588ddd47dc1c9b9920fcb2937391665f9729/e2e/integration_tests/metadata.py#L2)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2020
</blockquote></details>

Done.
___
*[e2e/integration_tests/metadata.py, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLON4yG-JqnXNfF-seB:-MLOfUx48kJnT-myfeeA:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/f93b588ddd47dc1c9b9920fcb2937391665f9729/e2e/integration_tests/metadata.py#L53)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

rename the method to _create_model_with_metadata, since this file does not test anything.
</blockquote></details>

Done.
___
*[e2e/integration_tests/metadata.py, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLOM3sz9-hx0qhvWfil:-MLOfUPz2OOWLgarhNWT:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/f93b588ddd47dc1c9b9920fcb2937391665f9729/e2e/integration_tests/metadata.py#L66)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

our other parameter uses comma as separator, is it possible to be consistent with that?
</blockquote></details>

Done.
___
*[tfjs-converter/python/tensorflowjs/converters/converter.py, line 734 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLONZ5DA0P2zGg76uRI:-MLOfbC4A0Q05R0Gdrs3:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/f93b588ddd47dc1c9b9920fcb2937391665f9729/tfjs-converter/python/tensorflowjs/converters/converter.py#L734)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

will comma as separator work?
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
Thank you Na, great work. LGTMed with just a couple minor comments.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4187#-:-MLPxs0I7O0lAnr1_co7:b-ql0dms)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[e2e/integration_tests/load_predict_test.ts, line 84 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLPxk347o3TZZySLMLp:-MLPxk347o3TZZySLMLq:bbg35z4) ([raw file](https://github.com/tensorflow/tfjs/blob/07498ec180e8728014c77b76ba73488d1a792294/e2e/integration_tests/load_predict_test.ts#L84)):*
> ```XML
>       const model = await tfconverter.loadGraphModel(
>           `${KARMA_SERVER}/load_predict_data/graph_model/model.json`);
>       const result = await model.executeAsync({'Placeholder': a}) as tfc.Tensor;
> ```

without signature the model can still run, better to verify `model.signature` is correct for both cases.
___
*[tfjs-converter/python/tensorflowjs/converters/wizard.py, line 582 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLPvls0EHh9C8BY5OUI:-MLPvls0EHh9C8BY5OUJ:b-7s4tn4) ([raw file](https://github.com/tensorflow/tfjs/blob/07498ec180e8728014c77b76ba73488d1a792294/tfjs-converter/python/tensorflowjs/converters/wizard.py#L582)):*
> ```Python
>                      'Provide your own metadata in the form: \n'
>                      'metadata_key:path/metadata.json \n'
>                      'Separate multiple metadata by semicolon.'
> ```

comma
___
*[tfjs-converter/src/executor/graph_model.ts, line 196 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLPwk8eD6yK1POrFC5f:-MLPwk8eD6yK1POrFC5g:b-b88o4k) ([raw file](https://github.com/tensorflow/tfjs/blob/07498ec180e8728014c77b76ba73488d1a792294/tfjs-converter/src/executor/graph_model.ts#L196)):*
> ```XML
> 
>       return false;
>     } else {
> ```

nit, just `return true;` for less lines.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4187)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[e2e/integration_tests/load_predict_test.ts, line 84 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLPxk347o3TZZySLMLp:-MLQC8Sv4l8mDfbfWc6n:b-vzo9h5) ([raw file](https://github.com/tensorflow/tfjs/blob/07498ec180e8728014c77b76ba73488d1a792294/e2e/integration_tests/load_predict_test.ts#L84)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

without signature the model can still run, better to verify `model.signature` is correct for both cases.
</blockquote></details>

model signature is not exposed. Should we expose it, any concern it can be mutated? TF exposes this field.
___
*[tfjs-converter/python/tensorflowjs/converters/wizard.py, line 582 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLPvls0EHh9C8BY5OUI:-MLQDHb10LxLQs0oOdNi:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/07498ec180e8728014c77b76ba73488d1a792294/tfjs-converter/python/tensorflowjs/converters/wizard.py#L582)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

comma
</blockquote></details>

Done.
___
*[tfjs-converter/src/executor/graph_model.ts, line 196 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLPwk8eD6yK1POrFC5f:-MLQDV8c4IwKMClSLDdl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/07498ec180e8728014c77b76ba73488d1a792294/tfjs-converter/src/executor/graph_model.ts#L196)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

nit, just `return true;` for less lines.
</blockquote></details>

Done.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4187)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[e2e/integration_tests/load_predict_test.ts, line 84 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4187#-MLPxk347o3TZZySLMLp:-MLiapISCnmPOU3RJnlo:b-lzoo2e) ([raw file](https://github.com/tensorflow/tfjs/blob/07498ec180e8728014c77b76ba73488d1a792294/e2e/integration_tests/load_predict_test.ts#L84)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

model signature is not exposed. Should we expose it, any concern it can be mutated? TF exposes this field.
</blockquote></details>

can we expose it as a getter field to avoid mutation?

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4187)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
