### PR TITLE
[wasm] Add DenseBincount kernel

### PR DESCRIPTION
**Pull request by chunnienc**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7267)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7267)* status: 0 of 1 approvals obtained (waiting on @chunnienc and @Linchenn)

___
*[`tfjs-backend-wasm/src/cc/kernels/DenseBincount.cc` line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7267#-NLcX5dOD5BGhlahlJFd:-NLcX5dOD5BGhlahlJFe:b-3zs89s) ([raw file](https://github.com/tensorflow/tfjs/blob/d7ccaa4a626b2bb921d6ec5fcaa54dcb53f06fa3/tfjs-backend-wasm/src/cc/kernels/DenseBincount.cc#L32)):*
> ```cpp
> 
> template <typename T>
> inline void Bincount1D(const int32_t* x_buf, int32_t x_len, int32_t size,
> ```

this function could be shared with bincount op, should these two function be separated in a new file?
___
*[`tfjs-backend-wasm/src/cc/kernels/DenseBincount.cc` line 60 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7267#-NLcV_LA2pKUWgiSsKfy:-NLcV_LA2pKUWgiSsKfz:bklfbrz) ([raw file](https://github.com/tensorflow/tfjs/blob/d7ccaa4a626b2bb921d6ec5fcaa54dcb53f06fa3/tfjs-backend-wasm/src/cc/kernels/DenseBincount.cc#L60)):*
> ```cpp
>                        bool binary_output, T* out_buf) {
>   for (int32_t i = 0; i < x_shape_0; ++i) {
>     Bincount1D(x_buf + i * x_shape_1, x_shape_1, size,
> ```

good refactoring, nicely done!

**Comment by chunnienc** [comment]
> this function could be shared with bincount op, should these two function be separated in a new file?
I will move them to Bincount.h in the PR adding the bincount op/kernel later.

**Review by Linchenn — APPROVED** [review]
LGTM!

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7267)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @chunnienc)

**Pull request merged**
