### PR TITLE
[core] Add basic implementation of einsum

### LINKED ISSUE #2349: Unsupported Op: Einsum
#### Describe the problem or feature request
When converting the Albert_base model, I saw:
ValueError: Unsupported Ops in the model before optimization
Einsum
#### Code to reproduce the bug
tensorflowjs_converter --signature_name tokens --input_format=tf_hub 'https://tfhub.dev/google/albert_base/2' ./web_model
@annxingyuan

### PR DESCRIPTION
**Pull request by caisq**
A step towards fixing #2349 

- Adds kernel implementations for the cpu and webgl backends.
- Limitations are documented in the op doc string.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903)

### CODE REVIEW

**Review by pyu10055 — DISMISSED** [review]
Thank you very much for add this useful op. On the high level, I think it would be good to move the generic method to a common file that allows share and at the same time not preventing each backend to register its own.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903#-:-MXY-wmABg8yl_ojA5ik:b-swhe63)* status: 0 of 1 approvals obtained (waiting on @caisq and @lina128)

___
*[tfjs-core/src/ops/einsum.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXf69t1TJWV0yR08yN:-MXXf69t1TJWV0yR08yO:bufstah) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L69)):*
> ```
> Limitations
> ```
Should transpose be supported 'ij=>ji' ?
___
*[tfjs-core/src/ops/einsum.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXgvD54f0JnIKNsK-g:-MXXgd7F9DF2dJgNM_I6:b7m7s0s) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L93)):*
> ```
> .
> ```
should check if there is only one '->' in the equation.
___
*[tfjs-core/src/ops/einsum.ts, line 131 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXiiZI0FONCCU8T4t3:-MXXiiZI0FONCCU8T4t4:bi1aie3) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L131)):*
> ```XML
>           `Support for duplicate axes in input is not implemented yet.`);
>     }
>     if (inputTerms.indexOf('...') !== -1) {
> ```

should this check move to the before the dims parsing? otherwise, this would probably trigger duplication check error.
___
*[tfjs-core/src/ops/einsum.ts, line 160 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXzDzS4GcxL9ZwAm9k:-MXXzDzT3SYdtLs3KCWk:bq97ao1) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L160)):*
> ```XML
>   let out: Tensor|null = null;
>   let numDimsRemaining = allDims.length;
>   for (let i = 0; i < nSteps; ++i) {
> ```

I think this would be a good common implementation, but we should allow each backend to implements is own more efficient version, for example tfjs-node could directly executed this op on the tf-core. Is possible to follow the new op guideline https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md
@lina128 what is the best way to share the common behavior across backend right now?
___
*[tfjs-core/src/ops/einsum.ts, line 206 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXkpVJ7Di0gG3sryLs:-MXXkpVJ7Di0gG3sryLt:bhkhafm) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L206)):*
> ```XML
> 
> /**
>  * Checks that the dimension sizes from different input tensors match the
> ```

does einsum support broadcasting (i.e. matric A[2x2] * Scaler B)?
___
*[tfjs-core/src/ops/einsum.ts, line 252 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXnJyh6u4xfrQz0djt:-MXXnJyh6u4xfrQz0dju:bbulx9q) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L252)):*
> ```XML
>     nSteps = 1;
>   } else {
>     nSteps = summedDims.length + 1;
> ```

seems both conditions have nsteps = summedDims.length + 1 ?
___
*[tfjs-core/src/ops/einsum_test.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXY-7jgD1QLRUgIB214:-MXY-7jgD1QLRUgIB215:bpvs9vr) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum_test.ts#L69)):*
> ```XML
>   });
> 
>   it('2d matrix sum over rows', async () => {
> ```

columns?

**Review by caisq — COMMENTED** [review]
Thanks for the comments!

Looking forward to hearing from @lina128 and you about how to utilize the tensorflow native einsum kernel in tfjs-node.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903#-:-MX_9PTm3OurSQvsEGh4:b-n00h9p)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-core/src/ops/einsum.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXf69t1TJWV0yR08yN:-MXY28ZzEm3zRqBUYBa1:b-3xunj7) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L69)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> Limitations
> ```
Should transpose be supported 'ij=>ji' ?
</blockquote></details>

transpose is already supported. As you can see in the unit tests.
___
*[tfjs-core/src/ops/einsum.ts, line 93 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXgvD54f0JnIKNsK-g:-MXZ3flR8hNwLXG9i9Jk:b-xw8v18) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L93)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> .
> ```
should check if there is only one '->' in the equation.
</blockquote></details>

Done, and added unit test.
___
*[tfjs-core/src/ops/einsum.ts, line 131 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXiiZI0FONCCU8T4t3:-MX_0RBx-LA3BcXMLmJY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L131)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should this check move to the before the dims parsing? otherwise, this would probably trigger duplication check error.
</blockquote></details>

Done.
___
*[tfjs-core/src/ops/einsum.ts, line 160 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXzDzS4GcxL9ZwAm9k:-MX_2bcyAkIkMGdmnWZO:b-matkmq) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L160)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I think this would be a good common implementation, but we should allow each backend to implements is own more efficient version, for example tfjs-node could directly executed this op on the tf-core. Is possible to follow the new op guideline https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING_MISSING_OP.md
@lina128 what is the best way to share the common behavior across backend right now?
</blockquote></details>

@lina128 Yes, I agree tfjs-node should use the kernel from tensorflow. This implementation is simple and allows us to avoid the heavy work of writing a GPU shader kernel for einsum. 

Please let me know what the most efficient way to make tfjs-node use the tensorflow kernel is.
___
*[tfjs-core/src/ops/einsum.ts, line 206 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXkpVJ7Di0gG3sryLs:-MX_4s-C4_GOCdt38eOE:b-xylltz) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L206)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

does einsum support broadcasting (i.e. matric A[2x2] * Scaler B)?
</blockquote></details>

Yes, np.einsum and tf.einsum support that. But for this implementation, falls into the documented limitation that "Summation over >1 axes is not implemented for >1 input tensors yet."

But I did add a few unit tests to cover some cases involving scalar inputs
___
*[tfjs-core/src/ops/einsum.ts, line 252 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXnJyh6u4xfrQz0djt:-MX_958NBPzu_8-JZgWk:b2c3d6w) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L252)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

seems both conditions have nsteps = summedDims.length + 1 ?
</blockquote></details>

Right. I consolidated the logic branches.
___
*[tfjs-core/src/ops/einsum_test.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXY-7jgD1QLRUgIB214:-MX_9M900Qq8HdV_F2PW:b-ri5h79) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum_test.ts#L69)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

columns?
</blockquote></details>

Done fixing the test names.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-core/src/ops/einsum.ts, line 160 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXzDzS4GcxL9ZwAm9k:-MXcGvlg3fqRtiqqkbGf:bj0nry1) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L160)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

@lina128 Yes, I agree tfjs-node should use the kernel from tensorflow. This implementation is simple and allows us to avoid the heavy work of writing a GPU shader kernel for einsum. 

Please let me know what the most efficient way to make tfjs-node use the tensorflow kernel is.
</blockquote></details>

Hi Shanqing, here the implementation is at op level, if you can move the implementation to kernel level, then Node backend can uses its own implementation, something like this: https://github.com/tensorflow/tfjs/blob/master/tfjs-node/src/kernels/DepthToSpace.ts. For attr and input_arg, reference tf's ops.pbtxt: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt

For the other three backends (Cpu, WebGL, WASM), you can extract two helper functions to share, one for the `decodeEquation`, one for the `getSteps`,  these should be in `tfjs-core/src/backends`, then each backend's EinSum kernel's body will be similar to the below for loop, except instead of call Engine, you just import the corresponding kernels. Admittedly, this is a little bit of repetitive, but it opens the door for backend-specific implementation, so that in the future WASM may use XNNPack implementation and WebGL may have its own shader that fuses the kernels.

**Review by lina128 — COMMENTED** [review]
Overall looks great, thank you Shanqing! Once the WebGL error is solved, I'm ready to LGTM.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903#-:-MXi2ipXEuNEvrYrcyB4:b2dhu17)* status: 0 of 1 approvals obtained (waiting on @caisq and @pyu10055)

___
*[tfjs-backend-cpu/src/kernels/Einsum.ts, line 3 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXhqmO12vmsQ0CBYjJZ:-MXhqmO29vZuuo5fYzxp:bb6ht36) ([raw file](https://github.com/tensorflow/tfjs/blob/c2afaf39c12efab21d61b52a012549ae796c2962/tfjs-backend-cpu/src/kernels/Einsum.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2020 Google LLC. All Rights Reserved.
> ```

2021
___
*[tfjs-core/src/kernel_names.ts, line 330 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXi2VYR0n6aXstyMBsT:-MXi2VYR0n6aXstyMBsU:b-ltngco) ([raw file](https://github.com/tensorflow/tfjs/blob/c2afaf39c12efab21d61b52a012549ae796c2962/tfjs-core/src/kernel_names.ts#L330)):*
> ```XML
> export interface EinsumAttrs {
>   equation: string;
>   N: number;
> ```

If only equation is needed, then we can remove N and dtype?

**Review by caisq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-backend-cpu/src/kernels/Einsum.ts, line 3 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXhqmO12vmsQ0CBYjJZ:-MXiIwV2-P8JdTLcdEv-:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/c2afaf39c12efab21d61b52a012549ae796c2962/tfjs-backend-cpu/src/kernels/Einsum.ts#L3)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[tfjs-core/src/kernel_names.ts, line 330 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXi2VYR0n6aXstyMBsT:-MXiIzisAQt9Vb8AOvQw:b-ffw4pq) ([raw file](https://github.com/tensorflow/tfjs/blob/c2afaf39c12efab21d61b52a012549ae796c2962/tfjs-core/src/kernel_names.ts#L330)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

If only equation is needed, then we can remove N and dtype?
</blockquote></details>

N is actually used. See einsum.ts in tfjs-core. It is also more consistent with the tensorflow ops.pbtxt to keep it.
___
*[tfjs-core/src/ops/einsum.ts, line 160 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXzDzS4GcxL9ZwAm9k:-MXiIs7l8RtuKF7k8LCx:b-2dyn3k) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L160)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Hi Shanqing, here the implementation is at op level, if you can move the implementation to kernel level, then Node backend can uses its own implementation, something like this: https://github.com/tensorflow/tfjs/blob/master/tfjs-node/src/kernels/DepthToSpace.ts. For attr and input_arg, reference tf's ops.pbtxt: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt

For the other three backends (Cpu, WebGL, WASM), you can extract two helper functions to share, one for the `decodeEquation`, one for the `getSteps`,  these should be in `tfjs-core/src/backends`, then each backend's EinSum kernel's body will be similar to the below for loop, except instead of call Engine, you just import the corresponding kernels. Admittedly, this is a little bit of repetitive, but it opens the door for backend-specific implementation, so that in the future WASM may use XNNPack implementation and WebGL may have its own shader that fuses the kernels.
</blockquote></details>

Done. Thanks for the explanations.

**Review by lina128 — APPROVED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903#-:-MXiNmZpDa4Vua8ZDe8Q:b-85i648)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @caisq, @lina128, and @pyu10055)

___
*[tfjs-core/src/kernel_names.ts, line 330 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXi2VYR0n6aXstyMBsT:-MXiMex5ElVVO86pEDQc:bj0js8j) ([raw file](https://github.com/tensorflow/tfjs/blob/c2afaf39c12efab21d61b52a012549ae796c2962/tfjs-core/src/kernel_names.ts#L330)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

N is actually used. See einsum.ts in tfjs-core. It is also more consistent with the tensorflow ops.pbtxt to keep it.
</blockquote></details>

I see that in einsum.ts in tfjs-core, N is just to set the attr, but it is not used in any logic, is that right? For dtype in attrs, our convention seems don't need to match unless it is used in any logic, otherwise we don't add it in the interface.

**Review by caisq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-core/src/kernel_names.ts, line 330 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXi2VYR0n6aXstyMBsT:-MXjFOqZ9V9GpFrQvQtB:bhnwwbi) ([raw file](https://github.com/tensorflow/tfjs/blob/c2afaf39c12efab21d61b52a012549ae796c2962/tfjs-core/src/kernel_names.ts#L330)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

I see that in einsum.ts in tfjs-core, N is just to set the attr, but it is not used in any logic, is that right? For dtype in attrs, our convention seems don't need to match unless it is used in any logic, otherwise we don't add it in the interface.
</blockquote></details>

That's right. Done removing attrs and dtype.

**Review by caisq — COMMENTED** [review]
Thanks for the review, @lina128 !

@pyu10055 let me know if you have any further comments.

 
 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903#-:-MXjKjha2KY1gPse5gNK:be738op)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

**Review by pyu10055 — APPROVED** [review]
Thank you, LGTMed.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903#-:-MXjjTna1YTQ5oulozyf:b4x28df)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @caisq, @lina128, and @pyu10055)

___
*[tfjs-core/src/ops/einsum.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXf69t1TJWV0yR08yN:-MXbqVFI1lYii8h_vAJ3:bpmv2wj) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L69)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

transpose is already supported. As you can see in the unit tests.
</blockquote></details>

cool, mind adding an example for transpose?

**Review by caisq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4903)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-core/src/ops/einsum.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4903#-MXXf69t1TJWV0yR08yN:-MXlcz4v1FTSVfxahf44:baih0jh) ([raw file](https://github.com/tensorflow/tfjs/blob/92ac5cb0c77f37d0dfc13c73b836976846328995/tfjs-core/src/ops/einsum.ts#L69)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

cool, mind adding an example for transpose?
</blockquote></details>

Done. Added two examples, one for transposing a 2D tensor and one for batch matrix transpose on a 3D tensor.

**Pull request merged**
