### PR TITLE
[browserstack benchmark tool] Add a html to present benchmark results

### PR DESCRIPTION
**Pull request by Linchenn**
For browserstack benchmark tool, when you run:
`node app.js --benchmark='./preconfigured_browser.json'  --cloud --outfile`,  the program will benchmark all models on devices configured in `preconfigured_browser.json` file and then write down the benchmark results into a json file `benchmark_results.json`, which is too large to be readable.

This PR:
1. lets the program write the benchmark results into a javascript variable (in `benchmark_results.js`), instead of a json file (`benchmark_results.json`). Then the benchmark results could be loaded easily to the html file.
2. add a html file, which loads `benchmark_results.js` and renders the benchmark results into a table.

Then, whenever complete `node app.js --benchmark='./preconfigured_browser.json'  --cloud --outfile`, users no longer need to read benchmark_results.json, and, they could simply open `benchmark_results.html` to see the results.

## Preview
image

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6740)

(For developers only: if want to use typescript to re-write this, could continue on https://github.com/tensorflow/tfjs/pull/6741)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
LGTM

**Review by pyu10055 — COMMENTED** [review]
Thanks, can you allow either json or html to be generated?
maybe use a command line flag?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6740#-:-N9DiNFd8UldwKQd1jFo:bwoie7j)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by Linchenn — COMMENTED** [review]
Great catch! 
Updated `outfile` argument. Thank you!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6740#-:-N9DnSPn7QJQIq0oEpVg:b-6fxhmq)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by pyu10055 — APPROVED** [review]
awesome, thanks

> Reviewed 1 of 2 files at r2, 1 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6740#-:-N9DoDbZAx5Su68x6umn:bl8jpbv)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
