### PR TITLE
Add npmVersion command line argument to benchmark NPM versions

### PR DESCRIPTION
**Pull request by wrighkv1**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

### CODE REVIEW

**Review by mattsoulanille — APPROVED** [review]
LGTM with a nit to add the new flag to the readme. Thanks!

**Review by Linchenn — CHANGES_REQUESTED** [review]
Thanks! Could you help also add some descriptions here? https://github.com/tensorflow/tfjs/blob/master/e2e/benchmarks/browserstack-benchmark/README.md?plain=1#L143

**Comment by wrighkv1** [comment]
Updated readme with description

**Review by Linchenn — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
