### PR TITLE
Add retry benchmark capabilities and jasmine tests

### PR DESCRIPTION
**Pull request by ClaireXP**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5367)

### CODE REVIEW

**Comment by ClaireXP** [comment]
@keithlwill @lina128 @mattsoulanille Ready for review!

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5367)* status: 0 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ36Kp2yCC9hqOUkJB:-MfJ36Kp2yCC9hqOUkJC:b-6nfuby) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L127)):*
> ```
>  let results = [];
> ```
Why the change to `let`?
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 137 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ3Uok53mHtvcGyTZz:-MfJ3Uok53mHtvcGyT_-:b-yxxe5f) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L137)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>      if (cliArgs?.maxBenchmarks && numActiveBenchmarks >= cliArgs.maxBenchmarks) {
>        numActiveBenchmarks = 0;
>        await Promise.allSettled(results);
>      }
> ```
</details>

Nit: I think this got indented.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 139 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ3d4NEWmFxBoxuC02:-MfJ3d4NEWmFxBoxuC03:b-mqxi1w) ([raw file](https://github.com/tensorflow/tfjs/blob/233054a1653583d8a54cd519384cd88b048fc7bb/e2e/benchmarks/browserstack-benchmark/app.js#L139)):*
> ```
>   if (cliArgs?.outfile) {
>     await write('./benchmark_results.json', fulfilled);
> ```
Are we writing to the outfile somewhere else now?
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 162 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfIt9HrA3P4ifS9g7DJ:-MfIt9HrA3P4ifS9g7DK:bz1wqd4) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L162)):*
> ```
> async function getOneBenchmarkResult(
> ```
Nice job keeping the retries functionality separate from the actual running of the benchmark. You could go even further by making this function fully generic and pure if you want (i.e. only pass in a function to retry and the max times to try it and don't use `cliArgs`), but it looks like we'll only need retries in one place, so this more specific implementation should work.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 164 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfIy2k3EndZHvx-xtZ8:-MfIy2k3EndZHvx-xtZ9:b-u4jdfr) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L164)):*
> ```
>   return new Promise(async (resolve, reject) => {
> ```
You won't need this promise if you use the `try-catch` pattern described in a later comment. The `try-catch` pattern would also let you use recursion instead of a loop if you want.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 166 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfIx6fn301kE_CE5C7J:-MfIx6fn301kE_CE5C7K:b-gleglr) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L166)):*
> ```
> cliArgs ?.maxTries
> ```
No space before `?`.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfIxMZwAKVFyu48Ucpr:-MfIxMZx0hANdwv_OvkL:b48onkn) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L185)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
>     while (!complete) {
>       result = await runOneBenchmark(tabId)
>                    // Runs steps after promise has been resolved
>                    .then((value) => {
>                      console.log(`Benchmark ${tabId} succeeded.`);
>                      complete = true;
>                      resolve(value);
>                      return value;
>                    })
>                    // Runs steps after promise has been rejected
>                    .catch((err) => {
>                      if (triesLeft > 0) {
>                        console.log(`${tabId} benchmark failed. Retrying. ${
>                            triesLeft} tries left...`);
>                        triesLeft--;
>                      } else {
>                        console.log(`${tabId} benchmark failed.`);
>                        complete = true;
>                        reject(err);
>                      }
>                      return err;
>                    });
> ```
</details>

Since you're already in an async function, it may be easier to read if you use the `try-catch` pattern instead:
```
try {
  const result = await runOneBenchmark(...); // An error gets thrown if `runOneBenchmark` rejects.
  ...
  return result;
catch (err) {
  if (...) {
    ...
  } else {
    throw err;
  }
}
```
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 288 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfIzCy-DmxR6cD-7tQq:-MfIzCy-DmxR6cD-7tQr:bdjk6ch) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L288)):*
> ```
> parser.add_argument('--maxTries', {
> ```
Nice! It's good to make this configurable.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 105 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ2WVHCMZRhouh4lMy:-MfJ2WVHCMZRhouh4lMz:byftvd9) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L105)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     // Bypasses Browserstack with preset failed mock results
>     failMockRunOneBenchmark =
>         jasmine.createSpy('mockRunOneBenchmark').and.callFake((tabId) => {
>           return Promise.reject(`Error: ${tabId} failed.`);
>         });
> ```
</details>

If this is only used in one spec, it can be defined in the spec instead of in `beforeEach`.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ1AsT8DwyTLblEJYH:-MfJ1AsUCpXwouWupJVk:b-eayldg) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L127)):*
> ```
> checks runOneBenchmark mock and end value of promise all
> ```
The spec description is easier to read if it describes the behavior that's being tested instead of how the test is written.

Maybe something like:

'benchmark' benchmarks each browser
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 153 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ-xT30mpRC4fjFfQF:-MfJ-xT30mpRC4fjFfQG:b-6hs0vf) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L153)):*
> ```
> checks getOneBenchmarkResult mock and result of failed results
> ```
Same here as in the above spec description. Describing the behavior that's being tested would be easier to understand.

Maybe something like "getOneBenchmark rejects if a benchmark consistently fails"
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 158 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfIzdjy4g8BDX_TjAvC:-MfIzdjy4g8BDX_TjAvD:b6ll1zs) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L158)):*
> ```
>   .toBeRejectedWith(`Error: iPhone_XS_1 failed.`);
> ```
Always good to check that it fails with the expected error. Nice!
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 164 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ-hA_BXNZTahrxzYv:-MfJ-hAaEXuVfYnnqAE_:b-u9osrr) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L164)):*
> ```
> checks getOneBenchmarkResult mock and result of successful results
> ```
Same here as in the above spec description. Describing the behavior that's being tested would be easier to understand.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 176 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ2Bz5C8XxkCRqU7Ob:-MfJ2Bz5C8XxkCRqU7Oc:b-l9tcfl) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L176)):*
> ```JavaScript
>        expect(succeedBenchmarkResult).toEqual(mockResults.iPhone_XS_1);
>      });
> ```

It would be good to test `getOneBenchmarkResult` with a mock that fails once and then succeeds.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 179 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ-QoU7V2sGsWaIiab:-MfJ-QoU7V2sGsWaIiac:b7t42zx) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L179)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>   it('checks that the benchmark function is called', () => {
>     runBenchmarkFromFile(testingConfig, mockBenchmark);
>     expect(mockBenchmark).toHaveBeenCalled();
>   });
>   it('checks that the benchmark is being run with the correct JSON', () => {
>     runBenchmarkFromFile(testingConfig, mockBenchmark);
>     expect(mockBenchmark).toHaveBeenCalledWith(testingConfig);
>   });
> ```
</details>

The first test is redundant with the second, and we can delete it.

**Review by ClaireXP — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5367)* status: 0 of 1 approvals obtained (waiting on @ClaireXP, @lina128, and @mattsoulanille)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ36Kp2yCC9hqOUkJB:-Mfmkd_6EY6gQtXLobmG:b-mk67p) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L127)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>  let results = [];
> ```
Why the change to `let`?
</blockquote></details>

Changed it back
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 137 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ3Uok53mHtvcGyTZz:-Mfmkz_yBzF5dVbTUVCK:b-4sk4ac) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L137)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>      if (cliArgs?.maxBenchmarks && numActiveBenchmarks >= cliArgs.maxBenchmarks) {
>        numActiveBenchmarks = 0;
>        await Promise.allSettled(results);
>      }
> ```
Nit: I think this got indented.
</blockquote></details>

Removed indentation-- thanks for pointing it out!
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 139 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ3d4NEWmFxBoxuC02:-Mfml5f4C_oHADvyJJ25:b-jwvbt3) ([raw file](https://github.com/tensorflow/tfjs/blob/233054a1653583d8a54cd519384cd88b048fc7bb/e2e/benchmarks/browserstack-benchmark/app.js#L139)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>   if (cliArgs?.outfile) {
>     await write('./benchmark_results.json', fulfilled);
> ```
Are we writing to the outfile somewhere else now?
</blockquote></details>

That was also an indent error
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 166 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfIx6fn301kE_CE5C7J:-MfmlMa_2FdHwzotih-Q:ba3dfob) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L166)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> cliArgs ?.maxTries
> ```
No space before `?`.
</blockquote></details>

Removed
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfIxMZwAKVFyu48Ucpr:-MfmlOwB5RyrRgPEA8tr:b-896fja) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L185)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     while (!complete) {
>       result = await runOneBenchmark(tabId)
>                    // Runs steps after promise has been resolved
>                    .then((value) => {
>                      console.log(`Benchmark ${tabId} succeeded.`);
>                      complete = true;
>                      resolve(value);
>                      return value;
>                    })
>                    // Runs steps after promise has been rejected
>                    .catch((err) => {
>                      if (triesLeft > 0) {
>                        console.log(`${tabId} benchmark failed. Retrying. ${
>                            triesLeft} tries left...`);
>                        triesLeft--;
>                      } else {
>                        console.log(`${tabId} benchmark failed.`);
>                        complete = true;
>                        reject(err);
>                      }
>                      return err;
>                    });
> ```
Since you're already in an async function, it may be easier to read if you use the `try-catch` pattern instead:
```
try {
  const result = await runOneBenchmark(...); // An error gets thrown if `runOneBenchmark` rejects.
  ...
  return result;
catch (err) {
  if (...) {
    ...
  } else {
    throw err;
  }
}
```
</blockquote></details>

Done!
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 105 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ2WVHCMZRhouh4lMy:-MfmlX-N5kyWotvgSoXN:b-1ynsew) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L105)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     // Bypasses Browserstack with preset failed mock results
>     failMockRunOneBenchmark =
>         jasmine.createSpy('mockRunOneBenchmark').and.callFake((tabId) => {
>           return Promise.reject(`Error: ${tabId} failed.`);
>         });
> ```
If this is only used in one spec, it can be defined in the spec instead of in `beforeEach`.
</blockquote></details>

The additional third test case where it fails and then succeeds now uses failMockRunOneBenchmark as well
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ1AsT8DwyTLblEJYH:-Mfmlvv5BboHmrhLsnne:b-4hvi0z) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L127)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> checks runOneBenchmark mock and end value of promise all
> ```
The spec description is easier to read if it describes the behavior that's being tested instead of how the test is written.

Maybe something like:

'benchmark' benchmarks each browser
</blockquote></details>

Got it!
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 176 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ2Bz5C8XxkCRqU7Ob:-Mfmm56W7T0UZ65X5-bk:bqmjwcm) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L176)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

It would be good to test `getOneBenchmarkResult` with a mock that fails once and then succeeds.
</blockquote></details>

Added!
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 179 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ-QoU7V2sGsWaIiab:-Mfmm72J6YI8imkvoicL:b-k7mx83) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L179)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>   it('checks that the benchmark function is called', () => {
>     runBenchmarkFromFile(testingConfig, mockBenchmark);
>     expect(mockBenchmark).toHaveBeenCalled();
>   });
>   it('checks that the benchmark is being run with the correct JSON', () => {
>     runBenchmarkFromFile(testingConfig, mockBenchmark);
>     expect(mockBenchmark).toHaveBeenCalledWith(testingConfig);
>   });
> ```
The first test is redundant with the second, and we can delete it.
</blockquote></details>

Deleted!

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5367)* status: 0 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ36Kp2yCC9hqOUkJB:-MfmqZugAjofUxg4PYXk:b-vyuzs1) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L127)):*
<details><summary><i>Previously, ClaireXP (Claire) wrote…</i></summary><blockquote>

Changed it back
</blockquote></details>

I think the commit that changes it back hasn't been pushed yet?
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 105 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ2WVHCMZRhouh4lMy:-Mfmr6Tj-LbO6l9yUro7:bp7vbfx) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L105)):*
<details><summary><i>Previously, ClaireXP (Claire) wrote…</i></summary><blockquote>

The additional third test case where it fails and then succeeds now uses failMockRunOneBenchmark as well
</blockquote></details>

sounds good!
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 178 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfmrqKI4LX2VDvki1AI:-MfmrqKI4LX2VDvki1AJ:b-38yku6) ([raw file](https://github.com/tensorflow/tfjs/blob/26a9960b9a6dc1ef2742f1551dc369b1267543d4/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L178)):*
> ```
>  failMockRunOneBenchmark, mockRunOneBenchmark
> ```
I see that you're passing two functions to simulate having a single function that fails once and then succeeds. There's a way to do this with Jasmine with just one function:

```js
let called = false;
const spy = jasmine.createSpy('the spy');
spy.and.callFake(() => {
  if (called) {
    return Promise.resolve('success');
  }
  called = true;
  return Promise.reject(new Error('Some error'));
});
```
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 195 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfmtH1t9FS5NWUzavJr:-MfmtH1t9FS5NWUzavJs:bu6rgl6) ([raw file](https://github.com/tensorflow/tfjs/blob/26a9960b9a6dc1ef2742f1551dc369b1267543d4/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L195)):*
> ```
> expect(mockRunOneBenchmark.calls.count()).toEqual(1);
> ```
Nice idea checking that it's only called once. We don't want to run the same benchmark twice if we don't have to.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5367)* status: 0 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 186 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfnNTBc12m4Kp8YlsKe:-MfnNTBc12m4Kp8YlsKf:b-6fqjg5) ([raw file](https://github.com/tensorflow/tfjs/blob/3210654d67f303701974228eb683f48eba2c772c/e2e/benchmarks/browserstack-benchmark/app.js#L186)):*
> ```
> retyOneBenchmark = runBrowserStackBenchmark
> ```
Is this only for testing?

**Review by ClaireXP — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5367)* status: 0 of 1 approvals obtained (waiting on @lina128 and @mattsoulanille)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 127 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ36Kp2yCC9hqOUkJB:-MfrsuVF8e9Lq4wgeAZB:b6l3ffd) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app.js#L127)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

I think the commit that changes it back hasn't been pushed yet?
</blockquote></details>

Fixed it for real this time :smiley: 
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 186 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfnNTBc12m4Kp8YlsKe:-Mfrt9wZADbMp60H2Jjh:bgfjti4) ([raw file](https://github.com/tensorflow/tfjs/blob/3210654d67f303701974228eb683f48eba2c772c/e2e/benchmarks/browserstack-benchmark/app.js#L186)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> retyOneBenchmark = runBrowserStackBenchmark
> ```
Is this only for testing?
</blockquote></details>

It was, but I re-designed the testing as Matt suggested and was able to get rid of it.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 164 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfJ-hA_BXNZTahrxzYv:-MfrtSwFCKA-4LaTT0JY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/19c8bafaee1a51b55b634b206a9baef293ee9737/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L164)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> checks getOneBenchmarkResult mock and result of successful results
> ```
Same here as in the above spec description. Describing the behavior that's being tested would be easier to understand.
</blockquote></details>

Done.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 178 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5367#-MfmrqKI4LX2VDvki1AI:-MfrtUsR7oR5xy57L4Nd:bk6w2jh) ([raw file](https://github.com/tensorflow/tfjs/blob/26a9960b9a6dc1ef2742f1551dc369b1267543d4/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L178)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>  failMockRunOneBenchmark, mockRunOneBenchmark
> ```
I see that you're passing two functions to simulate having a single function that fails once and then succeeds. There's a way to do this with Jasmine with just one function:

```js
let called = false;
const spy = jasmine.createSpy('the spy');
spy.and.callFake(() => {
  if (called) {
    return Promise.resolve('success');
  }
  called = true;
  return Promise.reject(new Error('Some error'));
});
```
</blockquote></details>

Thanks for sharing! I've implemented this

**Review by lina128 — APPROVED** [review]
LGTM

**Review by mattsoulanille — APPROVED** [review]
LGTM

> Reviewed 1 of 1 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5367#-:-Mg6W4TcAkwMfxZT41_V:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
