### PR TITLE
Add data to union package and bump version to 0.14.0

### PR DESCRIPTION
**Pull request by kangyizhang**
Add tfjs-data@0.1.1 into union package.

Please notice that data api is exported as tf.data

#### Description

---

##### For repository owners only:

Please remember to apply all applicable tags to your pull request.
Tags: FEATURE, BREAKING, BUG, PERF, DEV, DOC, SECURITY

For more info see: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/941)

### CODE REVIEW

**Comment by nsthorat** [comment]
Question for folks, @kangyizhang, @dsmilkov: we've been informally keeping the union version in sync with the core version, maybe we should release a minor of core?

**Comment by dsmilkov** [comment]
Sounds good - ping this thread when you release 0.14 in core.

**Comment by kangyizhang** [comment]
Sounds good. I'll release new tfjs-data depending on tfjs-core@0.14.0 and then update this PR.

**Comment by nsthorat** [comment]
Released:
- tfjs-core 0.14.0
- tfjs-layers 0.9.0
- tfjs-converter 0.7.0

**Pull request merged**
