### PR TITLE
Create a separate 'link-package-core' for packages that only need core

### PR DESCRIPTION
**Pull request by mattsoulanille**
This PR creates another link package for packages that only need tfjs-core and tfjs-backend-cpu, named 'link-package-core'. It also removes leaf dependencies (i.e. tfjs-tflite) from the link package since no packaged depend on them.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5436)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
Thank you Matt! I suggest rename `link-package-webgpu` to `link-package-core` or `link-package-core-only`, other than that LGTM!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5436#-:-MgIPhU12geMBstYy2EG:b-lnw3ky)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[link-package-webgpu/package.json, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5436#-MgIMRptE9NEtaOuBChQ:-MgIMRpuBHgStPiMW6zl:bsur2qv) ([raw file](https://github.com/tensorflow/tfjs/blob/2bff9ec7975eed84e74c6eb9e132a1bb4e40b7a8/link-package-webgpu/package.json#L2)):*
> ```
> "name": "link-package-webgpu",
> ```
This file seems not webgpu specific, can we name it `link-package-core-only`?
___
*[tfjs-converter/package.json, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5436#-MgIOKMqExgSiXmBdtKy:-MgIOKMr5A7hrPgl-bE2:bxzqyr6) ([raw file](https://github.com/tensorflow/tfjs/blob/2bff9ec7975eed84e74c6eb9e132a1bb4e40b7a8/tfjs-converter/package.json#L18)):*
> ```
> link-package-webgpu
> ```
This is an example where name it `link-package-core-only` reads better.
___
*[tfjs-converter/package.json, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5436#-MgIOWVy31KsUx7MbPiw:-MgIOWVy31KsUx7MbPix:bbjs9a0) ([raw file](https://github.com/tensorflow/tfjs/blob/2bff9ec7975eed84e74c6eb9e132a1bb4e40b7a8/tfjs-converter/package.json#L25)):*
> ```
> /link-package-webgpu
> ```
If we have to do this for all the migrated library, can you update the migration doc too? Can be in a separate PR.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5436)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[link-package/package.json, line 15 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5436#-MgISWPs-7puDo8dl7dC:-MgISWPs-7puDo8dl7dD:bv2bkjy) ([raw file](https://github.com/tensorflow/tfjs/blob/2bff9ec7975eed84e74c6eb9e132a1bb4e40b7a8/link-package/package.json#L15)):*
> ```
> /link-package-webgpu/node_modules/@tensorfl
> ```
For this to work, for ci, you probably need to add a cloudbuild step to yarn install link-package-webgpu first. For local, it needs to be done manually.

**Comment by qjia7** [comment]
@mattsoulanille I think the issue is not specific to webgpu. WebGL should have the similar problem. My confusion is that should the backend (webgl or webgpu) building trigger  `tfjs-tflite` to build? You can find the webgl is doing the same thing https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/package.json#L57 to call `"cd ../link-package && yarn build"`. If `tfjs-tflite` is a MUST, we shouldn't change the current logic. And we need to add this prerequired tool `wget` to public doc to tell developers what they should install before to build webgpu. Otherwise, we should fix it in a common way, not specific for webgpu.

**Review by lina128 — APPROVED** [review]
LGTM

**Comment by qjia7** [comment]
I like your new change, thanks.

**Pull request merged**
