### PR TITLE
Make converter hashtable test not overly specific

### PR DESCRIPTION
**Pull request by mattsoulanille**
tfjs-converter's saved model conversion test for hashtable depends on the exact names of the hashtable weights it saves, but these names are generated and may change between versions of TF. This was observed when syncing into google3, which is using tf 2.12. This PR prevents the test from checking the name of the hashtable weights.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7249)

### CODE REVIEW

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7249)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille and @pyu10055)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py` line 563 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7249#-NL2xCba2Wx-uhzUzKV-:-NL2xCba2Wx-uhzUzKV0:b9x845x) ([raw file](https://github.com/tensorflow/tfjs/blob/511108e1a87a2b9380eb6689c306bcfbfcbf7f89/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py#L563)):*
> ```Python
>     self.assertEqual(weights_manifest['weights'][2]['dtype'], 'int32')
> 
>     self.assertEqual(weights_manifest, expected_weights_manifest)
> ```

`self.assertEqual(weights_manifest, expected_weights_manifest)`
Is this duplicated with your additions?

**Review by Linchenn — APPROVED** [review]
LGTM!

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7249)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn and @mattsoulanille)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py` line 556 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7249#-NL3SvzTAK9VkWS6N-Yg:-NL3SvzU5OeQeuOjlmJa:b-8gzw45) ([raw file](https://github.com/tensorflow/tfjs/blob/511108e1a87a2b9380eb6689c306bcfbfcbf7f89/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py#L556)):*
> ```Python
>     self.assertEqual(weights_manifest['paths'], ['group1-shard1of1.bin'])
>     self.assertEqual(weights_manifest['weights'][0],
>                      {'name': 'unknown_0', 'shape': [], 'dtype': 'int32'})
> ```

should skip name for weights[0] too?

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7249)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn and @pyu10055)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py` line 556 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7249#-NL3SvzTAK9VkWS6N-Yg:-NL3aMm44GGh0WNOURNI:b-uzd555) ([raw file](https://github.com/tensorflow/tfjs/blob/511108e1a87a2b9380eb6689c306bcfbfcbf7f89/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2_test.py#L556)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should skip name for weights[0] too?
</blockquote></details>

Only the two weights with numbers for names were affected by tf 2.12, so I think it's okay to still check weights[0]. I can change this if you want, though.

**Review by Linchenn — APPROVED** [review]

**Review by pyu10055 — APPROVED** [review]

**Pull request merged**
