### PR TITLE
 [tfjs-converter] Bazel build migration

### PR DESCRIPTION
**Pull request by pyu10055**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5388)

### CODE REVIEW

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> Reviewed 1 of 40 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5388)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-converter/python/tensorflowjs/BUILD, line 168 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mfj3e2F2wKWwbT1H59v:-Mfj3e2GATLaLZFOAbsB:b-j50zzn) ([raw file](https://github.com/tensorflow/tfjs/blob/9d60b8b4b400013f267cbffb830e0b53ee651aea/tfjs-converter/python/tensorflowjs/BUILD#L168)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> # A filegroup BUILD target that includes all the op list json files in the
> # the op_list/ folder. The op_list folder itself is a symbolic link to the
> # actual op_list folder under src/.
> filegroup(
>     name = "op_list_jsons",
>     srcs = glob(["op_list/*.json"]),
> )
> ```
</details>


Looks like this is failing:
```
FileNotFoundError: [Errno 2] No such file or directory: '/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/bin/tfjs-converter/python/tensorflowjs/resource_loader_test.runfiles/tfjs/tfjs-converter/python/tensorflowjs/op_list'
```

Quick comment on why this is failing before I do a full review:

I added an `op_list` filegroup to a new BUILD.bazel file in the op_list directory in my PR because I didn't see this one. We can remove it and change the `.ts` op generator to point to this filegroup, or we can keep it, remove this one, and change the python targets to point to it.

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5388)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-converter/python/tensorflowjs/BUILD, line 168 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mfj3e2F2wKWwbT1H59v:-Mfn5Dsb6lSzXPYMgYFB:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/9d60b8b4b400013f267cbffb830e0b53ee651aea/tfjs-converter/python/tensorflowjs/BUILD#L168)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> # A filegroup BUILD target that includes all the op list json files in the
> # the op_list/ folder. The op_list folder itself is a symbolic link to the
> # actual op_list folder under src/.
> filegroup(
>     name = "op_list_jsons",
>     srcs = glob(["op_list/*.json"]),
> )
> ```

Looks like this is failing:
```
FileNotFoundError: [Errno 2] No such file or directory: '/builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/tfjs/bazel-out/k8-fastbuild/bin/tfjs-converter/python/tensorflowjs/resource_loader_test.runfiles/tfjs/tfjs-converter/python/tensorflowjs/op_list'
```

Quick comment on why this is failing before I do a full review:

I added an `op_list` filegroup to a new BUILD.bazel file in the op_list directory in my PR because I didn't see this one. We can remove it and change the `.ts` op generator to point to this filegroup, or we can keep it, remove this one, and change the python targets to point to it.
</blockquote></details>

Done.

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5388)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-converter/python/tensorflowjs/BUILD, line 168 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mfj3e2F2wKWwbT1H59v:-MggJVUGEt4OgoYQWd6s:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/9d60b8b4b400013f267cbffb830e0b53ee651aea/tfjs-converter/python/tensorflowjs/BUILD#L168)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> Reviewed 11 of 29 files at r1, 33 of 40 files at r2, 2 of 3 files at r3, 2 of 4 files at r4, 1 of 2 files at r5, 3 of 4 files at r6, 2 of 3 files at r7, 10 of 13 files at r11, 2 of 3 files at r12, 4 of 6 files at r13, 2 of 2 files at r15, 1 of 1 files at r21, 1 of 1 files at r22, 1 of 1 files at r23, 1 of 1 files at r24, 2 of 2 files at r25.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5388)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[WORKSPACE, line 265 at r13](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MglAsxJDqS4GDyJgZ6z:-MglAsxJDqS4GDyJgZ7-:b-w345dk) ([raw file](https://github.com/tensorflow/tfjs/blob/57660acb9f5894124f362da012513740f6bbf889/WORKSPACE#L265)):*
<details><summary><i alt="summary">Quoted 42 lines of code…</i></summary>

> ```
> http_archive(
>     name = "python3_interpreter",
>     build_file_content = """
> exports_files(["python3_bin"])
> filegroup(
>     name = "files",
>     srcs = glob(["bazel_install_py3/**"], exclude = ["**/* *"]),
>     visibility = ["//visibility:public"],
> )
> """,
>     patch_cmds = [
>         "mkdir $(pwd)/bazel_install_py3",
>         _py3_configure,
>         "make",
>         "make install",
>         "ln -s bazel_install_py3/bin/python3 python3_bin",
>     ],
>     sha256 = "fb1a1114ebfe9e97199603c6083e20b236a0e007a2c51f29283ffb50c1420fb2",
>     strip_prefix = "Python-3.8.11",
>     urls = ["https://www.python.org/ftp/python/3.8.11/Python-3.8.11.tar.xz"],
> )
> http_archive(
>     name = "python2_interpreter",
>     build_file_content = """
> exports_files(["python_bin"])
> filegroup(
>     name = "files",
>     srcs = glob(["bazel_install_py2/**"], exclude = ["**/* *"]),
>     visibility = ["//visibility:public"],
> )
> """,
>     patch_cmds = [
>         "mkdir $(pwd)/bazel_install_py2",
>         _py2_configure,
>         "make",
>         "make install",
>         "ln -s bazel_install_py2/bin/python python_bin",
>     ],
>     sha256 = "a4f05a0720ce0fd92626f0278b6b433eee9a6173ddf2bced7957dfb599a5ece1",
>     strip_prefix = "Python-2.7.13",
>     urls = ["https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tgz"],
> )
> ```
</details>

Downloading and building python will likely take a while the first time, but should be fine on subsequent builds. It would probably be better to autodetect the installed python versions, but I'm not sure how to do that. [Maybe this will work](https://github.com/bazelbuild/rules_python/blob/929d5a13d4eb1b930086d9353fc6f2d6ad306e43/proposals/2019-02-12-design-for-a-python-toolchain.md#default-toolchain), but I think we may have already tried it. My only concern about building python (and I think you voiced this as well) is whether or not it can be cached in CI so CI doesn't have to build python every time it runs.
___
*[link-package/package.json, line 9 at r13](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MglCBiKDZ-O6ARhdNN9:-MglCBiKDZ-O6ARhdNNA:b-s5spwl) ([raw file](https://github.com/tensorflow/tfjs/blob/57660acb9f5894124f362da012513740f6bbf889/link-package/package.json#L9)):*
> ```
>   "build": "yarn build-link-package-core && yarn build-backend-webgl && yarn reinstall",
> ```
You may need to add converter here again. I think another PR changed the same line.
___
*[link-package/yarn.lock, line 33 at r13](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MglCJinAS_senSjhsq8:-MglCJinAS_senSjhsq9:bj4ph5i) ([raw file](https://github.com/tensorflow/tfjs/blob/57660acb9f5894124f362da012513740f6bbf889/link-package/yarn.lock#L33)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
> <<<<<<< HEAD
>     "@tensorflow/tfjs-backend-cpu" "link:../../../Library/Caches/Yarn/v6/npm-@tensorflow-tfjs-backend-webgl-0.0.0-11c2195e-d2b9-4fc0-88c6-7ca981154613-1627511367479/node_modules/@tensorflow/link-package/node_modules/@tensorflow/tfjs-backend-cpu"
> =======
>     "@tensorflow/tfjs-backend-cpu" "link:../../.cache/yarn/v6/npm-@tensorflow-tfjs-backend-webgl-0.0.0-7bd291f1-1a02-4b56-b1f6-06782c5cd20f-1628181296214/node_modules/@tensorflow/link-package/node_modules/@tensorflow/tfjs-backend-cpu"
> >>>>>>> master
>     "@types/offscreencanvas" "~2019.3.0"
>     "@types/seedrandom" "2.4.27"
>     "@types/webgl-ext" "0.0.30"
>     "@types/webgl2" "0.0.5"
>     seedrandom "2.4.3"
> <<<<<<< HEAD
> "@tensorflow/tfjs-converter@file:../dist/bin/tfjs-converter/tfjs-converter_pkg":
>   version "0.0.0"
> "@tensorflow/tfjs-core@file:../dist/bin/tfjs-core/tfjs-core_pkg":
> =======
> "@tensorflow/tfjs-core@link:../link-package-core/node_modules/@tensorflow/tfjs-core":
> >>>>>>> master
> ```
</details>

Merge markers. You can remove and regenerate this file.
___
*[scripts/make-version.js, line 73 at r13](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MglCYYG5yB5J475izR5:-MglCYYG5yB5J475izR6:b-uvwph8) ([raw file](https://github.com/tensorflow/tfjs/blob/57660acb9f5894124f362da012513740f6bbf889/scripts/make-version.js#L73)):*
> ```
>     const newValue = data.replace(
>         /version\ =\ \"[0-9]+\.[0-9]+\.[0-9]+\"/g, `version = "${version}"`);
>     fs.writeFileSync(buildFilename, newValue, 'utf-8');
> ```
Nit: It would be better to do this with stamping. You can pass the version as an environment variable and then have it find and replace a string with the version in the variable. [Rules_nodejs supports this](https://bazelbuild.github.io/rules_nodejs/stamping.html) but I'm not sure if rules_python does.
___
*[tfjs/browserstack.err, line 1 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MfmwociAW6oSytlxhDK:-Mfmwocj93FfKam2mbTn:b-k6gwt0) ([raw file](https://github.com/tensorflow/tfjs/blob/b77be6094afaae9288eadfd10968759579c05ec6/tfjs/browserstack.err#L1)):*
> ```
> [object Object]
> ```
Accidental file I think
___
*[tfjs-converter/.gitignore, line 1 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mfmx6pACdtqHF6lmYNc:-Mfmx6pACdtqHF6lmYNd:b-raj1od) ([raw file](https://github.com/tensorflow/tfjs/blob/b77be6094afaae9288eadfd10968759579c05ec6/tfjs-converter/.gitignore#L1)):*
> ```
> bazel-*
> ```
This should probably go in the root .gitignore, although I'm not sure if it's necessary since we configure `dist` to be the bazel output directory.
___
*[tfjs-converter/BUILD.bazel, line 74 at r24](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MgrM7Nv4t_P5V-6K0mY:-MgrM7Nv4t_P5V-6K0mZ:bln8ld5) ([raw file](https://github.com/tensorflow/tfjs/blob/380663d06e4cfb521ac72cbd260f32f1a61e992e/tfjs-converter/BUILD.bazel#L74)):*
<details><summary><i alt="summary">Quoted 26 lines of code…</i></summary>

> ```
> filegroup(
>     name = "es6_sources",
>     srcs = [
>         "//tfjs-converter/src:tfjs-converter_lib",
>         "//tfjs-converter/src:tfjs-converter_src_lib",
>     ],
>     output_group = "es6_sources",
> )
> filegroup(
>     name = "es5_sources",
>     srcs = [
>         "//tfjs-converter/src:tfjs-converter_lib",
>         "//tfjs-converter/src:tfjs-converter_src_lib",
>     ],
>     output_group = "es5_sources",
> )
> copy_to_dist(
>     name = "copy_src_to_dist",
>     srcs = [
>         ":es5_sources",
>         ":es6_sources",
>         "//tfjs-converter/src:tfjs-converter_lib",
>         "//tfjs-converter/src:tfjs-converter_src_lib",
>     ],
>     root = "src",
> )
> ```
</details>

Some recent changes have changed how we package for npm. See the [migration doc](https://github.com/tensorflow/tfjs/blob/master/BAZEL_MIGRATION.md#package-for-npm) for more details, but essentially instead of these two filegroups and `copy_to_dist`, we use `copy_ts_library_to_dist`, which renames the `.mjs` files to `.js`. This is consistent with what the yarn infra publishes to npm.
___
*[tfjs-converter/BUILD.bazel, line 106 at r24](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MgrMm9f1qQRqeezw0Nw:-MgrMm9g2geaR0r4Jw8i:bu4zx5r) ([raw file](https://github.com/tensorflow/tfjs/blob/380663d06e4cfb521ac72cbd260f32f1a61e992e/tfjs-converter/BUILD.bazel#L106)):*
> ```
>         ":tf-converter",
>         ":tf-converter.es2017",
> ```
With the new (original) npm package format, we need the node bundle again. Add `tf-converter.node` to include it.
___
*[tfjs-converter/BUILD.bazel, line 127 at r24](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MgrN4Us60t2nL83Y7iO:-MgrN4Ut0cLZVDYHhM5r:b-19ubf7) ([raw file](https://github.com/tensorflow/tfjs/blob/380663d06e4cfb521ac72cbd260f32f1a61e992e/tfjs-converter/BUILD.bazel#L127)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> js_library(
>     name = "package_json",
>     package_name = "tfjs-converter",
>     srcs = [
>         ":package.json",
>     ],
> )
> ```
</details>

Nit: This may not be needed if converter only has node tests. You can access the file directly with `package.json` instead of `:package_json` in rules that depend on it.
___
*[tfjs-converter/BUILD.bazel, line 117 at r25](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mh-zRlz86tpIzJWFEq9:-Mh-zRlz86tpIzJWFEqA:b-16zkyl) ([raw file](https://github.com/tensorflow/tfjs/blob/30f6163f1d9f4c123390b4446ad1fb81849eb525/tfjs-converter/BUILD.bazel#L117)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> pkg_npm(
>     name = "tfjs-converter_pkg",
>     srcs = ["package.json"],
>     tags = ["ci"],
>     deps = [
>         ":copy_bundles",
>         ":copy_src_to_dist",
>         "//tfjs-converter/metadata:kernels_to_ops",
>     ],
> )
> ```
</details>


You should add the README file to this pkg_npm rule's deps so it gets published to npm. I'll do this for the other packages, since they're missing it too, and I'll add this to the migration doc.
___
*[tfjs-converter/cloudbuild.yml, line 35 at r24](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MgrQOszDMYAdCfYGRHk:-MgrQOszDMYAdCfYGRHl:bm0jatq) ([raw file](https://github.com/tensorflow/tfjs/blob/2300fa52079bf163accd7c3865cd3b4da2fc0b8f/tfjs-converter/cloudbuild.yml#L35)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> # Lint.
> - name: 'node:10'
>   dir: 'tfjs-converter'
>   entrypoint: 'yarn'
>   id: 'lint'
>   args: ['lint']
>   waitFor: ['yarn', 'build-deps']
> ```
</details>

Do we still want to lint? We're not linting globally yet.
___
*[tfjs-converter/package.json, line 5 at r25](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mh-xA_n468WiE2x-DST:-Mh-xA_n468WiE2x-DSU:b-lph4o3) ([raw file](https://github.com/tensorflow/tfjs/blob/30f6163f1d9f4c123390b4446ad1fb81849eb525/tfjs-converter/package.json#L5)):*
> ```
>   "main": "dist/index.js",
>   "jsnext:main": "dist/index.mjs",
>   "module": "dist/index.mjs",
> ```
We should revert these back to their original values since we'll be publishing the same format with Bazel as yarn creates. For reference, it used to be:
```
  "main": "dist/tf-converter.node.js",
  "jsnext:main": "dist/index.js",
  "module": "dist/index.js",
```
___
*[tfjs-converter/package.json, line 64 at r25](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mh-xZy6BvLRtzvw34zZ:-Mh-xZy6BvLRtzvw34z_:bpiyhad) ([raw file](https://github.com/tensorflow/tfjs/blob/30f6163f1d9f4c123390b4446ad1fb81849eb525/tfjs-converter/package.json#L64)):*
> ```
>     "publish-npm": "npm publish",
> ```
This should be changed to `bazel run :tfjs-converter_package.publish` since the publishing script relies on this for publishing Bazel packages.
___
*[tfjs-converter/python/BUILD, line 87 at r25](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mh0-VqM7I6-9EYexc_S:-Mh0-VqM7I6-9EYexc_T:b-4tps92) ([raw file](https://github.com/tensorflow/tfjs/blob/30f6163f1d9f4c123390b4446ad1fb81849eb525/tfjs-converter/python/BUILD#L87)):*
> ```
> version = "0.0.0",
> ```
It would be great if this could be a [stamp](https://bazelbuild.github.io/rules_nodejs/stamping.html#stamping) instead of hard-coded, but it looks like [that isn't how rules_python does things](https://github.com/bazelbuild/rules_python/blob/main/python/packaging.bzl#L232-L235).
___
*[tfjs-converter/python/build-pip-package.sh, line 153 at r25](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mh00vKS-s0Qwe5XXzyX:-Mh00vKT7uypfTGLAozf:b-jnzf5g) ([raw file](https://github.com/tensorflow/tfjs/blob/30f6163f1d9f4c123390b4446ad1fb81849eb525/tfjs-converter/python/build-pip-package.sh#L153)):*
> ```
>   #bazel build ${VENV_PYTHON_BIN}_wheel
> ```
Can this be deleted?

Do we ever run this script outside of CI? Right now, it just copies the bazel outputs and doesn't build the wheel itself. Should we make that a flag so its functionality is more obvious and to prevent people from being confused when they run it and it doesn't build anything? (Or we could rename it.)
___
*[tfjs-converter/python/tensorflowjs/BUILD, line 7 at r25](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mh01y_w8hG1WUbAsi3q:-Mh01y_w8hG1WUbAsi3r:b-lpxcym) ([raw file](https://github.com/tensorflow/tfjs/blob/30f6163f1d9f4c123390b4446ad1fb81849eb525/tfjs-converter/python/tensorflowjs/BUILD#L7)):*
> ```
> "//tfjs-converter/python/tensorflowjs:__subpackages__",
> ```
Do we use copybara on this file, i.e. does it need to work in google3? If so, we probably have to update copybara.

If this isn't needed in google3, we should rename it to `BUILD.bazel` to make that clear (same with the other `BUILD` files).
___
*[tfjs-converter/python/tensorflowjs/BUILD, line 88 at r25](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mh02q8-3tUOiTR_aX1N:-Mh02q8-3tUOiTR_aX1O:b1m8uit) ([raw file](https://github.com/tensorflow/tfjs/blob/30f6163f1d9f4c123390b4446ad1fb81849eb525/tfjs-converter/python/tensorflowjs/BUILD#L88)):*
> ```
>         "//tfjs-converter/python/tensorflowjs:expect_numpy_installed",
>         "//tfjs-converter/python/tensorflowjs:expect_tensorflow_installed",
> ```
These targets are defined in the same BUILD file as they are used, so they can just be
```
    ":expect_numpy_installed",
    ":expect_tensorflow_installed",
```

Same with many other targets in this file.
___
*[tfjs-converter/python/tensorflowjs/converters/BUILD, line 232 at r25](https://reviewable.io/reviews/tensorflow/tfjs/5388#-Mh03xtb4cEtFNqtErWV:-Mh03xtb4cEtFNqtErWW:bac39ys) ([raw file](https://github.com/tensorflow/tfjs/blob/30f6163f1d9f4c123390b4446ad1fb81849eb525/tfjs-converter/python/tensorflowjs/converters/BUILD#L232)):*
> ```
>         #"//third_party/py/h5py",
>         #"//third_party/py/tensorflow",
> ```
nit: remove?

**Review by pyu10055 — COMMENTED** [review]
1. I have updated the release doc, thanks

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5388#-:-Mi8woxW18BFMiz9GktF:b5lfksl)* status: 0 of 1 approvals obtained

**Review by mattsoulanille — COMMENTED** [review]
Thanks! This looks good to me. I'm having some trouble getting Python to run the tests on my laptop, but it passes CI and runs on my desktop, so this is almost definitely a misconfiguration on my side. I have two minor nits about the package.json file.

> Reviewed 3 of 16 files at r26, 12 of 12 files at r29.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5388#-:-MiNEDsO1pUNF_MutW80:bqu70bn)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-converter/package.json, line 21 at r29](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MiNKKbzEYblWMV0Yt4W:-MiNKKbzEYblWMV0Yt4X:b-zcirnf) ([raw file](https://github.com/tensorflow/tfjs/blob/cc194ebc3e0e1a6572dbf7b216087a0acb3defc8/tfjs-converter/package.json#L21)):*
> ```
> devDependencies
> ```
Nit: Add `@bazel/bazelisk` here too so bazel commands run from yarn use a version of bazel provided by yarn.
___
*[tfjs-converter/package.json, line 65 at r29](https://reviewable.io/reviews/tensorflow/tfjs/5388#-MiNJqSL69kCtWucEdOd:-MiNJqSL69kCtWucEdOe:bz89asu) ([raw file](https://github.com/tensorflow/tfjs/blob/cc194ebc3e0e1a6572dbf7b216087a0acb3defc8/tfjs-converter/package.json#L65)):*
> ```
> "test": "bazel test :tfjs-converter_test :test_snippets_test",
> ```
Nit: In the other Bazel packages, I've been trying to make `yarn test` run all the tests for a package, since caching makes this fast after the first run. Should we also run python tests here, e.g. `bazel test :tfjs-converter_test :test_snippets_test python/...`?

**Review by mattsoulanille — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5388#-:-MiNL5Rg6s_USyNPUfMO:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Pull request merged**
