### PR TITLE
[webgpu] Add support for Range

### PR DESCRIPTION
**Pull request by haoyunfeix**
FEATURE

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4924)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
@qjia7 @axinging @xhcao @gyagp PTAL

**Comment by qjia7** [comment]
@haoyunfeix Can any cases pass? Do you need to modify the `setup_test.ts` file?

**Review by haoyunfeix — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4924#-:-MY8vPPqD-KebvY1mEyl:b-896fix)* status: 0 of 1 approvals obtained

**Review by qjia7 — APPROVED** [review]
@lina128 @jinjingforever take a look, thanks.

**Review by jinjingforever — APPROVED** [review]

**Pull request merged**
