### PR TITLE
[webgpu] Fix string comparison fail

### PR DESCRIPTION
**Pull request by axinging**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5149)

### CODE REVIEW

**Review by qjia7 — APPROVED** [review]
@pyu10055 @lina128 take a look, thanks.
This is related with #5135 .

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5149#-:-Mb8wXb03mzWeMTEbrg7:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @pyu10055)

**Review by lina128 — COMMENTED** [review]
What about gatherND? 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5149#-:-Mb8xh8Z1hkmgXaGm269:b-lplumc)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @pyu10055)

**Comment by axinging** [comment]
@lina128,  add gatherND and not equal and equal.
@qjia7

**Review by lina128 — COMMENTED** [review]
I still can't see gatherND change.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5149#-:-MbCeRJ-6aRmSK6Xr7El:bc9ltyr)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — COMMENTED** [review]
missing gatherND delegation to cpu impl

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5149#-:-MbDnetWEsZPIqt42BCB:bwv4dat)* status: :shipit: complete! 2 of 1 approvals obtained

**Comment by axinging** [comment]
@lina128  @pyu10055, GatherND updated, PTAL.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5149)* status: :shipit: complete! 3 of 1 approvals obtained

**Pull request merged**
