### PR TITLE
[webgpu] Add fusedConv2d kernel

### PR DESCRIPTION
**Pull request by axinging**
FEATURE
Fix: https://github.com/tensorflow/tfjs/issues/2362

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2448)

### CODE REVIEW

**Comment by annxingyuan** [comment]
@axinging Thank you! Our build is failing because you are trying to import `fused_util` from within `backend_webgpu`, but it only exists within core. 

Could you instead import `Activation` from `backend_util`? 

Also, please export `FusedConv2DConfig` from `backend_util` (currently it only exports `Activation`). Then in `backend_webgpu` you can import `FusedConv2DConfig` from `@tensorflow/tfjs-core/dist/fused_util`, adding a TODO to import it from `backend_util` upon the next release of core.

**Comment by annxingyuan** [comment]
Hi @axinging - is this ready for another look? Would you mind merging master into your branch and resolving any conflicts? Thank you!

**Comment by axinging** [comment]
Done，@annxingyuan

**Comment by annxingyuan** [comment]
@axinging thanks! could you do one more thing: in backend_util.ts, export {Activation, FusedConv2DConfig, FusedBatchMatMulConfig}. then they will be available with the next release of core.

**Comment by axinging** [comment]
> @axinging thanks! could you do one more thing: in backend_util.ts, export {Activation, FusedConv2DConfig, FusedBatchMatMulConfig}. then they will be available with the next release of core.

Thanks @annxingyuan, it is ready now. Sorry I forget to update the backend_util in my last commit.

**Pull request merged**
