### PR TITLE
fix: tensor class import for hermes

### LINKED ISSUE #6526: tfjs does not work with hermes engine
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 12.2.1 (21D62), M1
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.18.0
- Browser version: NA
- Tensorflow.js Converter Version: NA

**Describe the current behavior**

When using tfjs for React Native, tfjs does not work when using [hermes JavaScript engine](https://hermesengine.dev/). It works with the default `jsc` engine.

It fails at `instanceof Tensor` assertion, even though the `constructor` is correctly identified as `Tensor`:
Screenshot 2022-06-11 at 4 54 15 PM

Screenshot 2022-06-11 at 6 54 02 PM copy

**Describe the expected behavior**

tfjs should run without errors when using `hermes` engine.

**Standalone code to reproduce the issue**

Minimum reproduction repo: https://github.com/paradite/tfjs-hermes-bug

- Install dependencies with `yarn` (it is not necessary to setup tfjs git submodule)
- Run `npm run tfjs:node`
  - Runs tfjs code with Node.js
  - Prints "result 2" without error
- Run `npm run tfjs:buildrun`
  - Bundles tfjs code with Metro
  - Runs tfjs code with Hermes
  - Gives the error "Uncaught Error: Argument 'x' passed to 'argMax' must be a Tensor or TensorLike, but got 'e'"

**Other info / logs**

I have tried a hacky fix and it seems to work:

Instead of using 

```jsx
if (x instanceof Tensor) {
    assertDtype(parseAsDtype, x.dtype, argName, functionName);
    return x;
}
```

, use 

```jsx
if (x instanceof Tensor || x.constructor.name === 'Tensor') {
    assertDtype(parseAsDtype, x.dtype, argName, functionName);
    return x;
}
```

### PR DESCRIPTION
**Pull request by paradite**
Fixes #6526 using suggestion in https://github.com/tensorflow/tfjs/issues/5972#issuecomment-1107360396

The fix has been verified using my reproduction repo: https://github.com/paradite/tfjs-hermes-bug

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

### CODE REVIEW

**Comment by paradite** [comment]
Hi @pyu10055 the CI passed but merging requires linear history so I merged master into the branch. 

Let me know if it is okay for me to update, or tfjs team can help to update the PR.

**Comment by paradite** [comment]
Hi @pyu10055 can help to review the PR? More people are experiencing the issue. Thanks!

**Comment by paradite** [comment]
hi @mattsoulanille @pyu10055, please help to review the PR. It would help with people using React Native which is using hermes by default now: https://reactnative.dev/docs/hermes

> Hermes is used by default by React Native and no additional configuration is required to enable it.

Others are also reporting the issue: #7977

**Review by mattsoulanille — APPROVED** [review]
LGTM. Thanks!

**Comment by mattsoulanille** [comment]
@pyu10055 Please take a look when you get a chance. Thanks!

**Pull request merged**
