### PR TITLE
[benchmarks] Add new type hierarchies to benchmarks/types.ts

### PR DESCRIPTION
**Pull request by caisq**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/1444)

### CODE REVIEW

**Comment by caisq** [comment]
Gentle ping @ other reviews.

**Comment by caisq** [comment]
Gentle ping @davidsoergel for suggestions on schema design for fast database access.

**Comment by nsthorat** [comment]
FYI you can index on fields with indexOn: https://firebase.google.com/docs/database/security/indexing-data

and it looks like you can do it on non-flat structures:
https://groups.google.com/forum/#!topic/firebase-talk/m3k51DOyfrs

You can use this tool to find out what the right rules are:
https://firebase.google.com/docs/database/usage/profile

**Comment by annxingyuan** [comment]
> Plot metric vs time, given constraints (e.g. which model, which environment)

I feel like this is our primary use case. Would it be possible to achieve this using `indexOn` ([docs](https://firebase.google.com/docs/database/security/indexing-data)) and keeping the data hierarchical by date?

**Comment by davidsoergel** [comment]
From what I understand, no.  `indexOn` can improve query performance, but it does not make new kinds of queries possible.  Realtime Database provides no query syntax that allows filtering within subtrees (https://firebase.google.com/docs/database/web/lists-of-data).

The top-level object in this PR is, I think,

    /** Benchmark logs from multiple days. */
    export type BenchmarkHistory = {
      [datetime: string]: SuiteLog
    };

Given this hierarchical schema, you **can**
* Select all SuiteLogs within a given date range, and load them fully.
* Select all SuiteLogs that meet a condition nested somewhere within them (e.g., a certain metric is present), and load them fully.  (In our case, this will generally cause loading the entire database).
* *Within a given SuiteLog*, select all TaskGroupLogs that meet a certain condition
* *Within a given TaskGroupLog*, select all MultiEnvironmentTaskLogs that meet a certain condition
* (etc.)

You **cannot**
* Select all TaskLogs that meet a certain condition--i.e., filtering on taskName or time range, and including TaskLogs nested within different SuiteLogs / TaskGroupLogs / MultiEnvironmentTaskLogs.

That last thing is exactly what you need for the primary use case.  If you think it's possible and I'm misunderstanding something, can you show the query that would achieve what you need using the RTDB ordering and filtering functions?

**Comment by davidsoergel** [comment]
Oh, maybe I confounded your question about a hierarchical schema with the question of which database to use.  It may still be possible to do what you want using a hierarchical schema *in Firestore*.  (I don't see any reason to do that, though.)

**Comment by caisq** [comment]
@davidsoergel I agree with @annxingyuan that the most common benchmark type is "selecting a certain date range of a given benchmark". For instance: "select all benchmarks results between 2019-04-01 and 2019-08-01 for the benchmark called MobileNetV2.predict". 

Can this be achieved through reorganizing the schema we have here from datetime-first to benchmark-first?

**Comment by caisq** [comment]
@davidsoergel Ah - just saw your gist. Catching up. Sorry.

**Comment by davidsoergel** [comment]
NP.  To be clear, yes you could rearrange the hierarchy to be metric-first to make the common query more efficient-- at the cost of the other query types, which would still require loading the whole db.

**Comment by annxingyuan** [comment]
Benchmark-first makes sense to me!

**Comment by davidsoergel** [comment]
If you're committed to maintaining a hierarchical structure, then yes, metrics-first is best for the primary use case.  But, I'm missing why you want to force the data into a hierarchy at all, when it is not naturally hierarchical.

For RTDB, the first best practice listed at https://firebase.google.com/docs/database/web/structure-data is 'avoid nesting data'.  For Firestore, the pros/cons at https://firebase.google.com/docs/firestore/manage-data/structure-data point in the same direction as well.

**Comment by davidsoergel** [comment]
Oops the comment that taskType is redundant is obsolete— we agreed that’s
on purpose.

**Pull request merged**
