### PR TITLE
Add Kernel SearchSorted for CPU and WebGL backend

### PR DESCRIPTION
**Pull request by ahmedsabie**
Based on [TF implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/searchsorted_op.cc)

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6349)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you Ahmed, couple high level question:
1. Should converter support this op for graph model?
2. shall we also support the LowerBound and UpperBound op, given that the functionality is there.


Thanks

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6349#-:-N0XfeMM3pWT0wjbnPes:bbza7xj)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[`tfjs-backend-webgl/src/search_sorted_gpu.ts` line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0XgE_aEfurUszgyAnU:-N0XgE_aEfurUszgyAnV:bj5ydyz) ([raw file](https://github.com/tensorflow/tfjs/blob/43e63d5d64d124aaf19fd43aa2563795d1fd85b4/tfjs-backend-webgl/src/search_sorted_gpu.ts#L36)):*
> ```XML
>          int right = numInputs;
>          int mid;
>          while (left < right) {
> ```

seems `while` is not supported in WebGL1

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6349)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfjs-backend-webgl/src/search_sorted_gpu.ts` line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0Xq9y69w6rhMuU0vNJ:-N0Xq9y69w6rhMuU0vNK:bmyrzde) ([raw file](https://github.com/tensorflow/tfjs/blob/43e63d5d64d124aaf19fd43aa2563795d1fd85b4/tfjs-backend-webgl/src/search_sorted_gpu.ts#L38)):*
> ```XML
>          while (left < right) {
>            mid = (left + right) / 2;
>            if (getSortedSequence(batch, mid) < value) {
> ```

Where is this method implemented?

**Review by ahmedsabie — COMMENTED** [review]
1. Yes that will be a separate PR
2. Yes that can be a simple forward to this OP, will add after

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6349#-:-N0bRwCK7_HeCv0wEuN4:bibhdw5)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`tfjs-backend-webgl/src/search_sorted_gpu.ts` line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0XgE_aEfurUszgyAnU:-N0bS2KB-UF1pSX1EvD6:b-886gsx) ([raw file](https://github.com/tensorflow/tfjs/blob/43e63d5d64d124aaf19fd43aa2563795d1fd85b4/tfjs-backend-webgl/src/search_sorted_gpu.ts#L36)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

seems `while` is not supported in WebGL1
</blockquote></details>

Fixed
___
*[`tfjs-backend-webgl/src/search_sorted_gpu.ts` line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0Xq9y69w6rhMuU0vNJ:-N0bS3xn1sWGkMWe5ki1:bb5vjr8) ([raw file](https://github.com/tensorflow/tfjs/blob/43e63d5d64d124aaf19fd43aa2563795d1fd85b4/tfjs-backend-webgl/src/search_sorted_gpu.ts#L38)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Where is this method implemented?
</blockquote></details>

C++ STL lower_bound and upper_bound which is based on iterators but this implementation is adjusted to indices

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6349)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[`tfjs-backend-webgl/src/search_sorted_gpu.ts` line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0Xq9y69w6rhMuU0vNJ:-N0blAtLDnGQAvGcwQdZ:bhast1h) ([raw file](https://github.com/tensorflow/tfjs/blob/43e63d5d64d124aaf19fd43aa2563795d1fd85b4/tfjs-backend-webgl/src/search_sorted_gpu.ts#L38)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

C++ STL lower_bound and upper_bound which is based on iterators but this implementation is adjusted to indices
</blockquote></details>

The method `getSortedSequence(batch, mid)` is a custom implementation written by us right? Is it in our codebase or this PR? Or is it provided as a GPU method?



_Code quote:_
```XML
getSortedSequence(
```

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6349)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`tfjs-backend-webgl/src/search_sorted_gpu.ts` line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0Xq9y69w6rhMuU0vNJ:-N0cD2xy2emKRGzPoS9F:bscybno) ([raw file](https://github.com/tensorflow/tfjs/blob/43e63d5d64d124aaf19fd43aa2563795d1fd85b4/tfjs-backend-webgl/src/search_sorted_gpu.ts#L38)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

The method `getSortedSequence(batch, mid)` is a custom implementation written by us right? Is it in our codebase or this PR? Or is it provided as a GPU method?
</blockquote></details>

The accessor  functions are implemented by our shader compiler, basically for any input tensor named 'x' to the program, a 'getX' function is generated. SortedSequence is one of the inputs to this program

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6349)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[`tfjs-backend-webgl/src/search_sorted_gpu.ts` line 43 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0cGEWeAHgT4fEu7IWV:-N0cGEWeAHgT4fEu7IWW:b-t0qa1i) ([raw file](https://github.com/tensorflow/tfjs/blob/28470cab328f8f951ecec45e4e5d52198fc5d264/tfjs-backend-webgl/src/search_sorted_gpu.ts#L43)):*
> ```XML
>                                                               webGL1LoopHead;
>     this.userCode = `
>        int lowerBound(int batch, float value) {
> ```

If the side part of the shader key, you can only interpolate the function needed by the `side` parameter into the shader? 
___
*[`tfjs-core/src/ops/search_sorted.ts` line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0cGnpG2dig4ofxXCz6:-N0cGnpG2dig4ofxXCz7:bb6ht37) ([raw file](https://github.com/tensorflow/tfjs/blob/43e63d5d64d124aaf19fd43aa2563795d1fd85b4/tfjs-core/src/ops/search_sorted.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2021 Google LLC. All Rights Reserved.
> ```

2022

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6349#-:-N0fw8-A1M2nKN7jBVqc:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[`tfjs-backend-webgl/src/search_sorted_gpu.ts` line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0Xq9y69w6rhMuU0vNJ:-N0fw-PGCFNHQ6w1gUOJ:b-tcyw3s) ([raw file](https://github.com/tensorflow/tfjs/blob/43e63d5d64d124aaf19fd43aa2563795d1fd85b4/tfjs-backend-webgl/src/search_sorted_gpu.ts#L38)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

The accessor  functions are implemented by our shader compiler, basically for any input tensor named 'x' to the program, a 'getX' function is generated. SortedSequence is one of the inputs to this program
</blockquote></details>

Ah, I didn't realize sortedSequence is the input name. Thanks.

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6349)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[`tfjs-backend-webgl/src/search_sorted_gpu.ts` line 43 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0cGEWeAHgT4fEu7IWV:-N0gLoQA7RzBs_kEA_zI:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/28470cab328f8f951ecec45e4e5d52198fc5d264/tfjs-backend-webgl/src/search_sorted_gpu.ts#L43)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

If the side part of the shader key, you can only interpolate the function needed by the `side` parameter into the shader? 
</blockquote></details>

Done.
___
*[`tfjs-core/src/ops/search_sorted.ts` line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6349#-N0cGnpG2dig4ofxXCz6:-N0gLqKj5CRkdvgWikTl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/43e63d5d64d124aaf19fd43aa2563795d1fd85b4/tfjs-core/src/ops/search_sorted.ts#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2022
</blockquote></details>

Done.

**Pull request merged**
