### PR TITLE
[browserstack benchmark tool] Enable code snippet benchmark

### PR DESCRIPTION
**Pull request by Linchenn**
This PR enable code snippet benchmark.

If you have a code snippet and want to benchmark on multiple devices, you could follow the steps:
## Step1: Add your code snippet
Open `e2e/benchmarks/browserstack-benchmark/benchmark_models.js` and update [`benchmarkCodeSnippet` ](https://github.com/tensorflow/tfjs/pull/6704/files#diff-a7c2ef12f0f2bc1a6cabb45bc9850aa68d10644cd2786e6505456e5537dccadbR92)with your code snippet.

## Step2: Run the server and benchmark
1. Follow the step1~3 of [Benchmark usage](https://github.com/tensorflow/tfjs/tree/master/e2e/benchmarks/browserstack-benchmark#usage) to start your local server.
2. Select `codeSnippet` in `model name`:
image
4. Config the browsers and devices and benchmark.

## Example usage
This already populates code snippet to benchmark `conv2d` and got the following results:
image

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6704)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6704)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn and @pyu10055)

___
*[`e2e/benchmarks/browserstack-benchmark/benchmark_models.js` line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6704#-N8UsX4d1MOo2BMX9H3t:-N8UsX4d1MOo2BMX9H3u:b-g0cv71) ([raw file](https://github.com/tensorflow/tfjs/blob/99027804343f28a87ab0b77b5dc443c3e4de784a/e2e/benchmarks/browserstack-benchmark/benchmark_models.js#L96)):*
> ```JavaScript
>   const filter = tf.randomUniform([3, 3, 3, 3], 0, 1000);
>   const predict = () => {
>     /* Please put your code snippet to benchmark here. */
> ```

This will require code change to test custom written code snippet, right? In the future, we can consider dynamic load JS file to test custom written code. Just a thought.



_Code quote:_
```JavaScript
* Please put your code snippet to benchmark here. 
```

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6704)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`e2e/benchmarks/browserstack-benchmark/benchmark_models.js` line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6704#-N8UsX4d1MOo2BMX9H3t:-N8UuQHuApmORXN05JPi:b-wuhoif) ([raw file](https://github.com/tensorflow/tfjs/blob/99027804343f28a87ab0b77b5dc443c3e4de784a/e2e/benchmarks/browserstack-benchmark/benchmark_models.js#L96)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This will require code change to test custom written code snippet, right? In the future, we can consider dynamic load JS file to test custom written code. Just a thought.
</blockquote></details>

Yes, this requires code changes. 

Great catch, loading JS file would support users to input code snippet on the UI (users input code snippet (as string) on UI -> the `app.js` could generate a JS file with the code snippet -> the `benchmark_model.js` could call functions from the newly generated JS file).

Another way to support inputting code snippet on the UI is that we could generate `benchmark_model.js` file directly with customized code snippet.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6704)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @Linchenn)

___
*[`e2e/benchmarks/browserstack-benchmark/benchmark_models.js` line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6704#-N8UsX4d1MOo2BMX9H3t:-N8VV-_152cO4SFiGyG3:b-cquyax) ([raw file](https://github.com/tensorflow/tfjs/blob/99027804343f28a87ab0b77b5dc443c3e4de784a/e2e/benchmarks/browserstack-benchmark/benchmark_models.js#L96)):*
<details><summary><i>Previously, Linchenn wrote…</i></summary><blockquote>

Yes, this requires code changes. 

Great catch, loading JS file would support users to input code snippet on the UI (users input code snippet (as string) on UI -> the `app.js` could generate a JS file with the code snippet -> the `benchmark_model.js` could call functions from the newly generated JS file).

Another way to support inputting code snippet on the UI is that we could generate `benchmark_model.js` file directly with customized code snippet.
</blockquote></details>

can we do similar things as our API website, where users can edit and run code snippet?
___
*[`e2e/benchmarks/browserstack-benchmark/benchmark_models.js` line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs/6704#-N8VVT-5D-qBgv4y-PRM:-N8VVT-5D-qBgv4y-PRN:b-gwd1u7) ([raw file](https://github.com/tensorflow/tfjs/blob/c7374e0c99794327567ae0e6490ab8da9681f7ae/e2e/benchmarks/browserstack-benchmark/benchmark_models.js#L106)):*
> ```JavaScript
>   };
> 
>   // Wramp up.
> ```

warm up

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6704)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`e2e/benchmarks/browserstack-benchmark/benchmark_models.js` line 96 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6704#-N8UsX4d1MOo2BMX9H3t:-N8VacA5ADoQffa2oXPC:b-idw2az) ([raw file](https://github.com/tensorflow/tfjs/blob/99027804343f28a87ab0b77b5dc443c3e4de784a/e2e/benchmarks/browserstack-benchmark/benchmark_models.js#L96)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can we do similar things as our API website, where users can edit and run code snippet?
</blockquote></details>

yes, in the next step, users could edit code snippets for both benchmarking and environment configuring. 

I also tried the following codes:
```js
const a = [];
eval('a.push(1)'); // It works and `a` becomes `[1]`;
```
This means, the codeSnippet-string within in `eval` function is run under the context of `eval`. As a result, the 'code snippet' feature could also be introduced to our online local benchmark tool by calling `eval`.
___
*[`e2e/benchmarks/browserstack-benchmark/benchmark_models.js` line 106 at r3](https://reviewable.io/reviews/tensorflow/tfjs/6704#-N8VVT-5D-qBgv4y-PRM:-N8VceGH7TudzBhXU8wZ:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/c7374e0c99794327567ae0e6490ab8da9681f7ae/e2e/benchmarks/browserstack-benchmark/benchmark_models.js#L106)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

warm up
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]

**Pull request merged**
