### PR TITLE
Add bincount and denseBincount op.

### PR DESCRIPTION
**Pull request by lina128**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4348)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for implementing those two ops!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4348#-:-MNoOyWh02Gdi2FNcztX:bfqcm84)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-backend-cpu/src/kernels/DenseBincount_impl.ts, line 20 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyLVKCByxGXHdEUz0p:-MNyLVKCByxGXHdEUz0q:bsf6twr) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-backend-cpu/src/kernels/DenseBincount_impl.ts#L20)):*
> ```XML
> import {buffer, DataType, Rank, TensorBuffer, TypedArray, util} from '@tensorflow/tfjs-core';
> 
> export function bincountImpl(
> ```

should this file be named as bincount_impl.ts? 
___
*[tfjs-converter/python/tensorflowjs/op_list/control.json, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyO1tX4VMBqTi0-aNg:-MNyO1tX4VMBqTi0-aNh:b-41wvk7) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/python/tensorflowjs/op_list/control.json#L3)):*
> ```JSON
> [
>   {
>     "tfOpName": "EmptyTensorList",
> ```

Is this from the other PR?
___
*[tfjs-converter/src/metadata_test.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyO8pb9VuJ4ImGTRXV:-MNyO8pb9VuJ4ImGTRXW:b-v8xcxf) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/src/metadata_test.ts#L32)):*
> ```XML
>     const knownUnmappedKernels = [
>       'Const',
>       'EmptyTensorList',
> ```

from the other PR?
___
*[tfjs-converter/src/operations/executors/control_executor.ts, line 273 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOE5c9PuZLPiyZSRl:-MNyOE5c9PuZLPiyZSRm:b-2guby3) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/src/operations/executors/control_executor.ts#L273)):*
> ```XML
>     }
>     case 'TensorListReserve':
>     case 'EmptyTensorList': {
> ```

same here
___
*[tfjs-converter/src/operations/executors/control_executor_test.ts, line 693 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOIhYExTf3FjjXtZf:-MNyOIhYExTf3FjjXtZg:b-2guby3) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/src/operations/executors/control_executor_test.ts#L693)):*
> ```XML
>   });
> 
>   describe('EmptyTensorList', () => {
> ```

same here
___
*[tfjs-converter/src/operations/op_list/control.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOS6g-CYXIMP2K7yB:-MNyOS6g-CYXIMP2K7yC:b-2guby3) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/src/operations/op_list/control.ts#L21)):*
> ```XML
> export const json: OpMapper[] = [
>   {
>     'tfOpName': 'EmptyTensorList',
> ```

same here
___
*[tfjs-core/src/ops/bincount.ts, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOfUo7XSqTp0z0jvy:-MNyOfUo7XSqTp0z0jvz:b-u47hxq) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-core/src/ops/bincount.ts#L53)):*
> ```XML
>   util.assert(
>       $x.dtype === 'int32',
>       () => `Error in denseBincount: input ` +
> ```

bincount?
___
*[tfjs-core/src/ops/bincount.ts, line 57 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOjIaB52lGVo_yVaY:-MNyOjIaB52lGVo_yVaZ:b-iik3kx) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-core/src/ops/bincount.ts#L57)):*
> ```XML
>   util.assert(size >= 0, () => `size must be non-negative, but got ${size}.`);
> 
>   const inputs: BincountInputs = {x: $x, weights: $weights};
> ```

should you check the size matches weight dimension (except when the weight is zero sized)?
___
*[tfjs-core/src/ops/dense_bincount.ts, line 62 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyP2Ky8Sr_e7X6Noj2:-MNyP2Ky8Sr_e7X6Noj3:bgh64yx) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-core/src/ops/dense_bincount.ts#L62)):*
> ```XML
>       () => `Error in denseBincount: input must be at most rank 2, but got ` +
>           `rank ${$x.rank}.`);
>   util.assert(size >= 0, () => `size must be non-negative, but got ${size}.`);
> ```

similar to bin count, should weight shape matches the size?
___
*[tfjs-core/src/ops/dilation2d.ts, line 59 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyPBDMELzkMPWRO5no:-MNyPBDMELzkMPWRO5np:b-fmuw7l) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-core/src/ops/dilation2d.ts#L59)):*
> ```XML
>  *     greater than 1, then all values of `strides` must be 1.
>  *
>  * @doc {heading: 'Operations', subheading: 'Convolution'}
> ```

from another PR?

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4348)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4348)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-converter/python/tensorflowjs/op_list/control.json, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyO1tX4VMBqTi0-aNg:-MNyvhLp116U65APuzWp:bvp3kap) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/python/tensorflowjs/op_list/control.json#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Is this from the other PR?
</blockquote></details>

Merged other PRs, now these files have no change.
___
*[tfjs-converter/src/metadata_test.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyO8pb9VuJ4ImGTRXV:-MNyvly0D6HF18x1FpV4:bmg7g7r) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/src/metadata_test.ts#L32)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

from the other PR?
</blockquote></details>

Merged other PRs, now this file has no change.
___
*[tfjs-converter/src/operations/executors/control_executor.ts, line 273 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOE5c9PuZLPiyZSRl:-MNyvpem2CouhOFpec9Y:bmg7g7r) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/src/operations/executors/control_executor.ts#L273)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Merged other PRs, now this file has no change.
___
*[tfjs-converter/src/operations/executors/control_executor_test.ts, line 693 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOIhYExTf3FjjXtZf:-MNyvraX4ejywdpBgSZX:bmg7g7r) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/src/operations/executors/control_executor_test.ts#L693)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Merged other PRs, now this file has no change.
___
*[tfjs-converter/src/operations/op_list/control.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOS6g-CYXIMP2K7yB:-MNyvsc77HJFqfwUrIg-:bmg7g7r) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-converter/src/operations/op_list/control.ts#L21)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

same here
</blockquote></details>

Merged other PRs, now this file has no change.
___
*[tfjs-core/src/ops/bincount.ts, line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOfUo7XSqTp0z0jvy:-MNyQhHeAcTZXT8oxu18:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-core/src/ops/bincount.ts#L53)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

bincount?
</blockquote></details>

Done.
___
*[tfjs-core/src/ops/bincount.ts, line 57 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOjIaB52lGVo_yVaY:-MNySX4sBUM9OT8MmSqI:b-kx0a7i) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-core/src/ops/bincount.ts#L57)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should you check the size matches weight dimension (except when the weight is zero sized)?
</blockquote></details>

Done. Added tests too.
___
*[tfjs-core/src/ops/dense_bincount.ts, line 62 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyP2Ky8Sr_e7X6Noj2:-MNyS_3m7dD_2lRpObNw:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-core/src/ops/dense_bincount.ts#L62)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

similar to bin count, should weight shape matches the size?
</blockquote></details>

Done.
___
*[tfjs-core/src/ops/dilation2d.ts, line 59 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyPBDMELzkMPWRO5no:-MNyvwfs8Os5TX0w1UOC:b-1eul6i) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-core/src/ops/dilation2d.ts#L59)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

from another PR?
</blockquote></details>

Just realized before subheading is wrong, fix it in this PR.
___
*[tfjs-backend-cpu/src/kernels/DenseBincount_impl.ts, line 20 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyLVKCByxGXHdEUz0p:-MNyQJkR7ahM0Uew6oL9:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-backend-cpu/src/kernels/DenseBincount_impl.ts#L20)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should this file be named as bincount_impl.ts? 
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4348)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-core/src/ops/bincount.ts, line 57 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MNyOjIaB52lGVo_yVaY:-MNzK0ts-4ipSog_D0rM:bruk3x3) ([raw file](https://github.com/tensorflow/tfjs/blob/3c3448e5b78aafdfac1bd45957b6a39aaa626ee0/tfjs-core/src/ops/bincount.ts#L57)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Done. Added tests too.
</blockquote></details>

the size of the weight should be same as the size attribute not the input size?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4348)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-backend-cpu/src/kernels/Bincount_impl.ts, line 36 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MO-6pzF5pwEc0EfGpHn:-MO-6pzG9sjAvrI9d7T7:bm1kl66) ([raw file](https://github.com/tensorflow/tfjs/blob/d76c6cbfdb8dbf257d9427ac9b2a89b5f3a34a05/tfjs-backend-cpu/src/kernels/Bincount_impl.ts#L36)):*
> ```XML
>     }
> 
>     if (weightsSize > 0) {
> ```

Hi Ping, as discussed offline, I've changed the behavior to align with TF c++ implementation. For 1d, it will set weights to be zero for out of range reference. @pyu10055 
___
*[tfjs-backend-cpu/src/kernels/Bincount_impl.ts, line 72 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4348#-MO-72BV5B_KpAF-DcSu:-MO-72BV5B_KpAF-DcSv:biykv0d) ([raw file](https://github.com/tensorflow/tfjs/blob/d76c6cbfdb8dbf257d9427ac9b2a89b5f3a34a05/tfjs-backend-cpu/src/kernels/Bincount_impl.ts#L72)):*
> ```XML
>       } else {
>         if (weightsBuf.size > 0) {
>           // The behavior here is different than bincountImpl above. We don't
> ```

Added doccomment about the different behavior between TF c++ implementation and TFJS. @pyu10055

**Pull request merged**
