### PR TITLE
Move e2e custom bundling test into regression tests/nightly

### PR DESCRIPTION
**Pull request by tafsiri**
This PR does a few things to reduce flakiness of e2e test suite as well as increase the speed of e2e for PRs:

- Move the custom bundle test into regression/nightly. This primarily speeds up the regular PR tests by not building tfjs-backend-wasm
- Restrict the custom bundle test to chrome. It was flaky on mobile safari probably due to webworker loading, and we primarily want to test the presence of kernels not the correctness of the model and ability to run without an error. Testing in chrome is sufficient to meet our needs here.
- Doing the above required refactoring the tests to use describeWithFlags (and testenvs) rather than describe (which can still be used for namespacing tests). This standardizes our testing approach with what is used in the other packages and makes configuring the environment more deterministic and should also better isolate tests.

Logs for passing nightly are here (ran multiple to test flakiness): 
- https://pantheon.corp.google.com/cloud-build/builds/23c9c825-46d3-4734-b691-a461cb72df79;step=2?project=learnjs-174218
- https://pantheon.corp.google.com/cloud-build/builds/05b58b00-dc2a-4157-b3ea-a6f17929202e?project=learnjs-174218

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3983)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
This is great, thank you Yannick!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3983#-:-MIV1sVY1HGoFy0L8iRS:b-xxo11l)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128, @pyu10055, and @tafsiri)

___
*[e2e/integration_tests/backends_test.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIUxrhh6r0UBu7GbWi2:-MIUxrhh6r0UBu7GbWi3:b-nezwgq) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/integration_tests/backends_test.ts#L34)):*
> ```
> tfc.findBackend('webgl') !== null && tfc.findBackend('cpu') !== null
> ```
Is just having tfc.findBackend('webgl') !== null && tfc.findBackend('cpu') !== null enough for the predicate? 
___
*[e2e/integration_tests/backends_test.ts, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIUyOf2C6_VLdmcaSvn:-MIUyOf2C6_VLdmcaSvo:b-p9gb7s) ([raw file](https://github.com/tensorflow/tfjs/blob/f111dc03a87ab7664688011812beba4691bae455/e2e/integration_tests/backends_test.ts#L55)):*
> ```XML
>       // input moved to cpu.
> 
>       // Because input is moved to cpu, data should be deleted from webgl.
> ```

Add back this last word?
___
*[e2e/integration_tests/backends_test.ts, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIUyU-ODITwi0pbbORS:-MIUyU-ODITwi0pbbORT:b-z7s7zq) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/integration_tests/backends_test.ts#L101)):*
> ```XML
>         // input moved to webgl.
> 
>         // Because input is moved to webgl, data should be deleted from
> ```

This is not complete sentence.
___
*[e2e/integration_tests/setup_test.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIV1k7b0UQ3Z65SE5PS:-MIV1k7b0UQ3Z65SE5PT:b-h4q6h1) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/integration_tests/setup_test.ts#L19)):*
> ```XML
> 
> // Import core for side effects (e.g. flag registration)
> import '@tensorflow/tfjs-core';
> ```

Should we also register the backends here and remove the import in each test file?
import '@tensorflow/tfjs-backend-cpu';
import '@tensorflow/tfjs-backend-webgl';
___
*[e2e/script_tag_tests/symbols_and_basic_api_test.js, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIUzuBp9E84dx7idsBC:-MIUzuBp9E84dx7idsBD:bsx239r) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/script_tag_tests/symbols_and_basic_api_test.js#L49)):*
> ```JavaScript
> 
> describe('ops', () => {
>   tf.setBackend('cpu');
> ```

await tf.setBackend('cpu');

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3983)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128, @pyu10055, and @tafsiri)

___
*[e2e/integration_tests/memory_leak_test.ts, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIV2sGxCNv8Ell7XW45:-MIV2sGxCNv8Ell7XW46:bi8ol7k) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/integration_tests/memory_leak_test.ts#L65)):*
> ```XML
> 
> describeWithFlags(
>     `${SMOKE} A custom op that calls unmodularized kernels and modularized ` +
> ```

Shall we follow the pattern in other test files too? Use SMOKE OR REGRESSION in describe, and then use describeWithFlags inside?

**Review by tafsiri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3983)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[e2e/integration_tests/backends_test.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIUxrhh6r0UBu7GbWi2:-MIWlbGFDkngLjA3xjl_:bp7y7dy) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/integration_tests/backends_test.ts#L34)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> tfc.findBackend('webgl') !== null && tfc.findBackend('cpu') !== null
> ```
Is just having tfc.findBackend('webgl') !== null && tfc.findBackend('cpu') !== null enough for the predicate? 
</blockquote></details>

The first part will make sure not to run this twice under essentially the same conditions (since this will involve both the 
___
*[e2e/integration_tests/backends_test.ts, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIUyOf2C6_VLdmcaSvn:-MIWlya_9mo3crR0nCjo:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/f111dc03a87ab7664688011812beba4691bae455/e2e/integration_tests/backends_test.ts#L55)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Add back this last word?
</blockquote></details>

Done.
___
*[e2e/integration_tests/backends_test.ts, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIUyU-ODITwi0pbbORS:-MIWm26D1kyZcaLU1ujs:b-g362ds) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/integration_tests/backends_test.ts#L101)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This is not complete sentence.
</blockquote></details>

Fixed (what an odd set of truncations.
___
*[e2e/integration_tests/memory_leak_test.ts, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIV2sGxCNv8Ell7XW45:-MIWmAyW45tdh3tUxysS:b-3by624) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/integration_tests/memory_leak_test.ts#L65)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Shall we follow the pattern in other test files too? Use SMOKE OR REGRESSION in describe, and then use describeWithFlags inside?
</blockquote></details>

So tbh i'm not a huge fan of the nesting of describes in these tests (there seem to be a relatively small number of tests for the depth of assertions). One downside to the mixing is that if you ever initialze some tensor related thing in the describe scope it will be out of sync with the inner describeWithFlags, so it creates one extra thing to thing about. I had a version of this PR where I un-nested everything but decided to make the change smaller.
___
*[e2e/integration_tests/setup_test.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIV1k7b0UQ3Z65SE5PS:-MIWmnKN4KepBdtWRdwA:b-ort14j) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/integration_tests/setup_test.ts#L19)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should we also register the backends here and remove the import in each test file?
import '@tensorflow/tfjs-backend-cpu';
import '@tensorflow/tfjs-backend-webgl';

</blockquote></details>

I think those should stay in each individual test file, makes them a bit more self contained.
___
*[e2e/script_tag_tests/symbols_and_basic_api_test.js, line 49 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3983#-MIUzuBp9E84dx7idsBC:-MIWn7EF9mp5s_79oLwW:bb7f2mf) ([raw file](https://github.com/tensorflow/tfjs/blob/2c5043484c1744247e6ed1e7cdf7886e45121dea/e2e/script_tag_tests/symbols_and_basic_api_test.js#L49)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

await tf.setBackend('cpu');
</blockquote></details>

done

**Comment by pyu10055** [comment]
LGTM, Thanks Yannick!

**Pull request merged**
