### PR TITLE
Update tfjs-node to 1.2.11.

### PR DESCRIPTION
**Pull request by kangyizhang**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2160)

### CODE REVIEW

**Comment by caisq** [comment]
@kangyizhang this will make the browser and Node.js versions go out of sync. Is that okay? @nsthorat

**Comment by nsthorat** [comment]
Preferably we would do a full version release but given that it's a pain I think it's okay for this one. Maybe we can do a minor version bump everywhere to avoid them skewing more since we've done a lot?

**Comment by kangyizhang** [comment]
@caisq I'll send PRs to release all packages.

**Comment by caisq** [comment]
Thanks, @kangyizhang I personally prefer keeping versions consistent.

**Pull request closed without merging**
