### PR TITLE
initial version of gradients for prod

### PR DESCRIPTION
**Pull request by iislucas**
Initial implementation of gradients for `prod` operator:

Fixes: https://github.com/tensorflow/tfjs/issues/2587

Tested locally with: 

```
$ yarn run tslint -p tsconfig_tslint.json
$ cd tfjs-core
$ yarn run bazel test --test_output=streamed :tfjs-core_test :test_snippets_test :tfjs-core_node_test :tfjs-core_async_backends_test src:worker_node_test src:worker_test --//:grep=prod
```

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6216)

### CODE REVIEW

**Review by iislucas — COMMENTED** [review]
> Does the cumprod uses prod gradient?

No, I don't think so (I would do it just with mul & div I think). But I also needed gradients for prod so I needed to add it.  I need einsum gradients also... so that might come next  :) 

> yours look much simpler than TF prodGrad implementation ... can help to explain?

I thought I knew, but as I look at it more, I'm confused. I need to think about this more, I'm pretty sure I've made a mistake... 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6216#-:-Mxzj1CR6Qo0N4TDfdG_:b-8tx1yw)* status: 0 of 1 approvals obtained

**Review by iislucas — COMMENTED** [review]
Actually, I'm sure I've made a mistake... I'll come back to you on this with an update. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6216#-:-My43aY82lf_rOiDT3p4:bwus65r)* status: 0 of 1 approvals obtained

**Review by iislucas — COMMENTED** [review]
OK, I went back to this I re-implemented it using, cumprod, as originally planned (in my new baby brain fuzz state I had gotten myself confused and thought I had a massive simplification, but I didn't). 

To debug, I also made a tinkerable/easier to debug/tweak version in: https://codesandbox.io/s/iislucas-tfjs-prod-grad-example-n7i7ug?file=/src/index.ts

I think tests pass now, and I have the use-case from the c-implementation as a test case also. 

PTAL.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6216#-:-MzRYLfM6ZUPVMJPrMZb:b-ipgbcl)* status: 0 of 1 approvals obtained

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Cool, thank you for implementing this, looks like the c code support multiple axis as you have also addressed in your implementation.

The implementation looks very easy to following. I just have couple minor comments. Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6216#-:-MzasPeJ-9dktTSOHmvJ:b-b399uj)* status: 0 of 1 approvals obtained (waiting on @iislucas)

___
*[tfjs-core/src/gradients/Prod_grad.ts, line 29 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6216#-MzawAee1lIf12kY1qJR:-MzawAee1lIf12kY1qJS:b-x8xryc) ([raw file](https://github.com/tensorflow/tfjs/blob/8a46fd6c44619c60a81846887bd6f775a0da2578/tfjs-core/src/gradients/Prod_grad.ts#L29)):*
> ```XML
> // Works on a single axis.
> function prodGradFn_(x: Tensor, dy: Tensor, axis: number): Tensor {
>   // The gradent tensor (dy) has a set of axis removed, so we create re-shaped
> ```

couple typo: `gradient` and `set of axes`
___
*[tfjs-core/src/ops/prod_test.ts, line 112 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6216#-Mzawe1L1iJgwkTkr_Tz:-Mzawe1L1iJgwkTkr_U-:boge0sn) ([raw file](https://github.com/tensorflow/tfjs/blob/8a46fd6c44619c60a81846887bd6f775a0da2578/tfjs-core/src/ops/prod_test.ts#L112)):*
> ```XML
>   // Illustrative example from the C++ implementation for comparison. See:
>   // https://github.com/tensorflow/tensorflow/blob/5dee95f8bafe3f342693d2135da451283b1fbaec/tensorflow/cc/gradients/math_grad.cc
>   it('gradients: prod(multi-dimensional tensor with zeros)', async () => {
> ```

can you add a test that covers multiple reduction axes? thanks

**Review by iislucas — COMMENTED** [review]
Thanks! Done.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6216#-:-MzflaEGEJ_JmWo8VwjN:b4855pb)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-core/src/gradients/Prod_grad.ts, line 29 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6216#-MzawAee1lIf12kY1qJR:-MzflGHPDcWgmkm_BSeo:bc36c1r) ([raw file](https://github.com/tensorflow/tfjs/blob/8a46fd6c44619c60a81846887bd6f775a0da2578/tfjs-core/src/gradients/Prod_grad.ts#L29)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

couple typo: `gradient` and `set of axes`
</blockquote></details>

oops, yes, I had axis instead of axes in several places. fixed. 

DONE.
___
*[tfjs-core/src/ops/prod_test.ts, line 112 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6216#-Mzawe1L1iJgwkTkr_Tz:-MzflRg54CYKhTGLnsxB:b-61xeq0) ([raw file](https://github.com/tensorflow/tfjs/blob/8a46fd6c44619c60a81846887bd6f775a0da2578/tfjs-core/src/ops/prod_test.ts#L112)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you add a test that covers multiple reduction axes? thanks
</blockquote></details>

There was one that worked on all axes already, but I added one also for working on two axes at once also.

**Review by iislucas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6216)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-core/src/ops/prod_test.ts, line 112 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6216#-Mzawe1L1iJgwkTkr_Tz:-Mzfpt4eELnIcBffO_Vp:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/8a46fd6c44619c60a81846887bd6f775a0da2578/tfjs-core/src/ops/prod_test.ts#L112)):*
<details><summary><i>Previously, iislucas (iislucas) wrote…</i></summary><blockquote>

There was one that worked on all axes already, but I added one also for working on two axes at once also. 
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6216)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
