### PR TITLE
webgpu: Fix shader compile error when using fused conv2d

### PR DESCRIPTION
**Pull request by qjia7**
BUG

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4521)

### CODE REVIEW

**Comment by qjia7** [comment]
cc @axinging @xhcao This patch will fix the shader compilation error. However, it exposes another issue. The new added test is failed on both webgl and webgpu backend. The expectation is from cpu result. It seems that there is other bug in the shader for webgl/webgpu. Feel free to provide your opinions for this. Thanks.

**Comment by qjia7** [comment]
> cc @axinging @xhcao This patch will fix the shader compilation error. However, it exposes another issue. The new added test is failed on both webgl and webgpu backend. The expectation is from cpu result. It seems that there is other bug in the shader for webgl/webgpu. Feel free to provide your opinions for this. Thanks.

Just tried the latest webgl code, it can pass. Will pick the corresponding fix to webgpu. Thanks.

**Comment by qjia7** [comment]
> > cc @axinging @xhcao This patch will fix the shader compilation error. However, it exposes another issue. The new added test is failed on both webgl and webgpu backend. The expectation is from cpu result. It seems that there is other bug in the shader for webgl/webgpu. Feel free to provide your opinions for this. Thanks.
> 
> Just tried the latest webgl code, it can pass. Will pick the corresponding fix to webgpu. Thanks.

**Comment by qjia7** [comment]
> cc @axinging @xhcao This patch will fix the shader compilation error. However, it exposes another issue. The new added test is failed on both webgl and webgpu backend. The expectation is from cpu result. It seems that there is other bug in the shader for webgl/webgpu. Feel free to provide your opinions for this. Thanks.

It turns out it's my test case issue. I used different `generateCaseInputs`. Sorry for the noise.

**Comment by qjia7** [comment]
@kainino0x @lina128 Please take a look, thanks.

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4521#-:-MQumIur9iCSHRhd3rvV:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @kainino0x)

**Review by kainino0x — APPROVED** [review]

**Pull request merged**
