### PR TITLE
[Fixed] Run CI on a single machine by generating cloudbuild files

### PR DESCRIPTION
**Pull request by mattsoulanille**
The [previous PR](https://github.com/tensorflow/tfjs/pull/4147) was reverted because it broke CI. This PR includes the previous PR's changes as a single commit and includes fixes in the commits following it.

Instead of running each CI test on a separate Google Cloud machine, generate a cloudbuild.yml file to test all affected packages on a single machine. The benifits of this strategy include the following:
* Fewer machines are required for a single test (2 instead of up to 12), so queuing should happen much less often.
* Packages only need to be built once, instead of once per machine.
* Multithreaded steps have access to more cores.

When CI is run, the root cloudbuild.yml is launched on Google Cloud. This file has only three steps: Install yarn dependencies, run `yarn generate-cloudbuild-for-packages`, and run `run-build.sh`. The second step finds what packages were affected by the change and combines their cloudbuild.yml files into a single `cloudbuild_generated.yml` file, and the third step launches the generated build on Google Cloud. The steps in the generated build are set to `waitFor` each other according to the dependency tree `scripts/package_dependencies.json`, and each package's `build-deps` step is removed in favor of waiting for its dependencies to be built.

Each package's cloudbuild file still works as expected, and there are two new yarn commands at the root:
* `yarn test-packages` tests all packages affected by a change. It performs the same steps as CI.
* `yarn generate-cloudbuild-for-packages [PACKAGE]...` generates the cloudbuild file to test each `PACKAGE` and packages it might affect. If given no packages, it detects what packages have been changed in the current PR.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
Great work!!! Very clean and thorough. Thank you Matt!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186#-:-MLOYGec1VMj2FBTAxa3:b-gu5vr0)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128, @mattsoulanille, @pyu10055, and @tafsiri)

___
*[scripts/generate_cloudbuild.js, line 103 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4186#-MLOXGqA4vN38vn97kAE:-MLOXGqA4vN38vn97kAF:byttuw3) ([raw file](https://github.com/tensorflow/tfjs/blob/1474e3bc95d54f00d29cd8b48ddb423f3984e800/scripts/generate_cloudbuild.js#L103)):*
> ```JavaScript
>     // If there are no such nodes, then the graph has a cycle.
>     if (emptyNodes.length === 0) {
>       // TODO(msoulanille): Include the cycle in the error message?
> ```

Seems this TODO is implemented below, you can remove the TODO.
___
*[scripts/find_packages_with_diff.js, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4186#-MLOWxS98I1qNWWwWdEp:-MLOWxS98I1qNWWwWdEq:b-bzgycu) ([raw file](https://github.com/tensorflow/tfjs/blob/1474e3bc95d54f00d29cd8b48ddb423f3984e800/scripts/find_packages_with_diff.js#L25)):*
> ```JavaScript
> const filesAllowlistToTriggerBuild = [
>   'cloudbuild.yml', 'package.json', 'tsconfig.json', 'tslint.json',
>   'scripts/find_packages_with_diff.js', 'scripts/run-build.sh'
> ```

Should we add 'scripts/generate_cloudbuild.js' to this list?

**Review by mattsoulanille — COMMENTED** [review]
Thanks, Na!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186#-:-MLP4Jnl3RlXPP8MsQbL:b-xz48tw)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128, @pyu10055, and @tafsiri)

___
*[scripts/generate_cloudbuild.js, line 103 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4186#-MLOXGqA4vN38vn97kAE:-MLP4PIf8IgPjW_wkm0d:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/207ca57053776d29db632e04b4fd3eae528fae78/scripts/generate_cloudbuild.js#L103)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Seems this TODO is implemented below, you can remove the TODO.
</blockquote></details>

Done.
___
*[scripts/find_packages_with_diff.js, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4186#-MLOWxS98I1qNWWwWdEp:-MLP4OjQAPf1wWn1SX4D:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/207ca57053776d29db632e04b4fd3eae528fae78/scripts/find_packages_with_diff.js#L25)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should we add 'scripts/generate_cloudbuild.js' to this list?
</blockquote></details>

Done.

**Comment by mattsoulanille** [comment]
`test-browser` in tfjs-layers sometimes fails to parse `tfjs-core/dist/tf-core.node.js`. On one run, it has said that a comment is not terminated, and in another, that a string is not terminated. Perhaps `tfjs-core/dist/tf-core.node.js` is being written while the test is being run, but I've looked through all the in-progress steps from the following builds and found nothing that would be writing to it.

Example builds that have failed:

https://console.cloud.google.com/cloud-build/builds/6b149616-e500-48b8-8f96-f5c54a4ba8c9?project=834911136599

https://console.cloud.google.com/cloud-build/builds/efd36d73-321a-4598-936b-d7dba2e0a713?project=834911136599

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128, @mattsoulanille, @pyu10055, and @tafsiri)

___
*[scripts/cloudbuild_tfjs_core_expected.yml, line 95 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4186#-MLPsgV99H9e9HLLbMqI:-MLPsgV99H9e9HLLbMqJ:b-o6xc4) ([raw file](https://github.com/tensorflow/tfjs/blob/383b8fb392c7c4b4c87f02dbc35a5cb3aa232e5e/scripts/cloudbuild_tfjs_core_expected.yml#L95)):*
> ```YAML
>     waitFor:
>       - yarn-common
>       - yarn-tfjs-core
> ```

many of the waitFor seems to be duplicated? for example tfjs-backend-cpu waits for yarn-tfjs-backend-cpu, which has already waited for yarn-tfjs-core? Should these duplication be cleaned up?

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128, @pyu10055, and @tafsiri)

___
*[scripts/cloudbuild_tfjs_core_expected.yml, line 95 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4186#-MLPsgV99H9e9HLLbMqI:-MLT9AMQ8kDK247fo7Gl:bl9w784) ([raw file](https://github.com/tensorflow/tfjs/blob/383b8fb392c7c4b4c87f02dbc35a5cb3aa232e5e/scripts/cloudbuild_tfjs_core_expected.yml#L95)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

many of the waitFor seems to be duplicated? for example tfjs-backend-cpu waits for yarn-tfjs-backend-cpu, which has already waited for yarn-tfjs-core? Should these duplication be cleaned up?
</blockquote></details>

We could trim each step's dependencies down to the smallest set possible in generate_cloudbuild.js, but I think it's best to maintain a 1:1 relationship with the contents of package_dependencies.json, which is derived from the package.json files. It might be confusing if dependencies seemingly don't show up in a given step in the generated file, even if they're present transitively.

As a side note, we might eventually want to use the package.json files directly instead of keeping a separate 'package_dependencies.json' file up-to-date, but that can come in a later commit.

**Review by lina128 — COMMENTED** [review]
Hi Matt, it seems it stops when test-webgpu-tfjs-backend-webgpu starts. It build deps again in the test-ci.sh. Since we migrate to dynamic cloudbuild approach, all the build steps should be controlled by cloudbuild file, not by shell scripts. Can you refactor test-webgpu cloudbuild steps? Basically, moving yarn lint and yarn build-deps from test-ci.sh to cloudbuild.yml.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186#-:-MLQ1gdk2MST74IUu6S8:bcxcdle)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128, @pyu10055, and @tafsiri)

**Comment by mattsoulanille** [comment]
Thanks so much, Na! I was looking for packages that were rebuilding dependencies, but I must have missed that one. I'll refactor it.

**Comment by mattsoulanille** [comment]
Just pushed the refactor. Individual cloudbuild tests for tfjs-backend-webgpu still work: 

https://console.cloud.google.com/cloud-build/builds/6cefa934-740d-4058-86f5-ade5d2d5d470?project=834911136599

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128 and @tafsiri)

**Comment by mattsoulanille** [comment]
I think the [current build failure](https://console.cloud.google.com/cloud-build/builds/ec9a6396-15f8-4fe4-ae56-5f797155a96c?project=834911136599) might actually be a bug in tfjs-layers. I get the same error when I run the [tfjs-layers cloudbuild](https://console.cloud.google.com/cloud-build/builds/833cfa9f-6fe5-4fe5-b04e-e98e5f98a158?project=834911136599) by itself.

**Review by lina128 — COMMENTED** [review]
Why does tfjs-layers nightly build pass?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186#-:-MLTreccCnJ8NQDOtqrk:b8qxa7f)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128 and @tafsiri)

**Comment by tafsiri** [comment]
FWIW i'm seeing the same error in layers on a different PR.

**Comment by tafsiri** [comment]
The change triggering the failure in the layers tests has been reverted so you should be able to sync this with HEAD and see it pass.

**Review by tafsiri — COMMENTED** [review]
> Reviewed 3 of 7 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128, @mattsoulanille, and @tafsiri)

___
*[package.json, line 31 at r6](https://reviewable.io/reviews/tensorflow/tfjs/4186#-MLn6q2o6ZPsXfpbe9JK:-MLn6q2p1eGNT_vpfcFw:b-234oh9) ([raw file](https://github.com/tensorflow/tfjs/blob/8e05f35e4540351ed65193842e3e70642c39dcb0/package.json#L31)):*
> ```JSON
>     "test-release-notes": "ts-node -s ./scripts/release_notes/run_tests.ts",
>     "update-tfjs-lockfiles": "ts-node -s ./scripts/update-tfjs-lockfiles",
>     "update-cloudbuild-tests": "yarn generate-cloudbuild-for-packages tfjs-node && cp cloudbuild_generated.yml scripts/cloudbuild_tfjs_node_expected.yml && yarn generate-cloudbuild-for-packages tfjs-core && cp cloudbuild_generated.yml scripts/cloudbuild_tfjs_core_expected.yml"
> ```

Are these files all generated in the top level folder? I.e. why not have `yarn generate-cloudbuild-for-packages tfjs-node` write the file into tfjs-node (and then you don't need the cp command)? I'm mainly thinking of the potential for overlapping state if someone is running this manually. What do you think?

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128 and @tafsiri)

___
*[package.json, line 31 at r6](https://reviewable.io/reviews/tensorflow/tfjs/4186#-MLn6q2o6ZPsXfpbe9JK:-MLn9IR980t7wm9JnWzT:bubj7mg) ([raw file](https://github.com/tensorflow/tfjs/blob/085d57dc6af48e97d608bfb0ea7ad810f438f680/package.json#L31)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Are these files all generated in the top level folder? I.e. why not have `yarn generate-cloudbuild-for-packages tfjs-node` write the file into tfjs-node (and then you don't need the cp command)? I'm mainly thinking of the potential for overlapping state if someone is running this manually. What do you think?
</blockquote></details>

generate_cloudbuild_for_packages must be run in the project's root directory, but I've added a flag to it to change the output location and name. update-cloudbuild-tests no longer overwrites cloudbuild_generated.yml.

**Review by tafsiri — APPROVED** [review]
Thanks Matt! LGTM (reviewed the last two commits). 

> Reviewed 1 of 7 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4186#-:-MLnE5_VDrnOV9F5YT5X:bha8qme)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @lina128 and @tafsiri)

**Comment by mattsoulanille** [comment]
Thanks for the review, Yannick! I'll submit once the presubmits pass.

**Pull request merged**
