### PR TITLE
Add command to set-url

### PR DESCRIPTION
**Pull request by kangyizhang**
When creating /tmp/tfjs-release/tfjs the default remote url might be `https://github.com/xxxx.git`, which does not use ssh. Set it to `git@github.com/xxxx.git` before push.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/1787)

### CODE REVIEW

**Comment by nsthorat** [comment]
Just curious you couldn't get this to work with the regular https? It should work in either mode.

**Comment by kangyizhang** [comment]
No. When it's https, it asks for username and password in terminal, which breaks the release script.

**Comment by nsthorat** [comment]
You can fix that with a global git login, changing the time to live of the login. I would prefer you do that to doing this change.

**Comment by nsthorat** [comment]
Can we close this out?

**Comment by kangyizhang** [comment]
Yes.

**Pull request closed without merging**
