### PR TITLE
Remove return statement from optimize_graph

### PR DESCRIPTION
**Pull request by dhruvin2910**
Fixed a typo

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4188)

### CODE REVIEW

**Comment by dhruvin2910** [comment]
@googlebot I signed it!

**Comment by dhruvin2910** [comment]
I just found out from the docstring that it wasn't supposed to return anything at all. Let me know if I should remove return altogether.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for spotting this issue, I agree the return line should be removed.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4188#-:-MLOLJBLBdqF9E6wGD6x:b-dwfop0)* status: 0 of 1 approvals obtained (waiting on @dhruvin2910)

___
*[tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py, line 210 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4188#-MLOLAgO-vc6tq8t7EaC:-MLOLAgPBVbyGnD3iK3j:b-kabiji) ([raw file](https://github.com/tensorflow/tfjs/blob/6ca9fb8058df8f48a621a7a5378d1ccaf3c9b2a0/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L210)):*
> ```Python
>       initializer_graph_def)
> 
>   return optimized_graph
> ```

Actually it would be better to remove this line.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4188)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @dhruvin2910)

**Pull request merged**
