### PR TITLE
Changed the function conditionalRounding to function round,function round will default truncate value.

### LINKED ISSUE #4271: [tfjs-core] Error: The output # of rows (11.4) must be an integer when running pool test
**System information**
- TensorFlow.js version (use command below):
"@tensorflow-core": "^2.7.0" 

**Describe the current behavior**
When running [this pool test](https://brucedai.github.io/report-bug/unset_roundingMode_param.html), error happened 

**Describe the expected behavior**
None error, and the output # of rows is an integer (11) computed with below Python code of [AVERAGE_POOL_2D test](https://android.googlesource.com/platform/frameworks/ml/+/refs/tags/android-cts-11.0_r1/nn/runtime/test/specs/V1_0/avg_pool_float_2.mod.py) from NNAPI  CTS.

```python
row = 52
std = 5
flt = 100
pad = 50
output_row = (row + 2 * pad - flt + std) // std #L35
```

**Standalone code to reproduce the issue**
Here's a [test case](https://brucedai.github.io/report-bug/unset_roundingMode_param.html).

**Other info / logs** Include any logs or source code that would be helpful to
When calling function `conditionalRound`, none value (undefined) was passed to the second **roundingMode** paramter, so as the first **value** paramter being not an integer (11.4), the value wasn't rounded. 
```ts
/**
 * Rounds a value depending on the rounding mode
 * @param value
 * @param roundingMode
 */
function conditionalRound(
    value: number, roundingMode?: 'floor'|'round'|'ceil') {
  if (!roundingMode) {
    return value;
  }
  switch (roundingMode) {
    case 'round':
      // used for Caffe Conv
      return Math.round(value);
    case 'ceil':
      // used for Caffe Pool
      return Math.ceil(value);
    case 'floor':
      return Math.floor(value);
    default:
      throw new Error(`Unknown roundingMode ${roundingMode}`);
  }
}
```
Traced that when calling function **conv_util.computePool2DInfo** of [tfjs-core/src/ops/pool.ts#L85](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/pool.ts#L85), none value (undefined) was passed to the sixth **roundingMode** parameter .
```ts
  const convInfo = conv_util.computePool2DInfo(
      x4D.shape, windowShape, strides, dilations, pad);
```
According to [**computePool2DInfo** definitions](https://github.com/tensorflow/tfjs/blob/4d81b29a13cb67a0fae67833890cac326ca4d720/tfjs-core/src/ops/conv_util.ts#L119):
```ts
export function computePool2DInfo(
    inShape: [number, number, number, number],
    filterSize: [number, number]|number, strides: number|[number, number],
    dilations: number|[number, number], pad: 'same'|'valid'|number,
    roundingMode?: 'floor'|'round'|'ceil',
    dataFormat: 'channelsFirst'|'channelsLast' = 'channelsLast')
```

### PR DESCRIPTION
**Pull request by BruceDai**
This PR is to fix #4271. @lina128 PTAL, thanks

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4282)

### CODE REVIEW

**Comment by BruceDai** [comment]
@googlebot I signed it!

**Review by lina128 — COMMENTED** [review]
Hi Bruce, thank you for contributing the PR. We don't know whether it's necessary to add dimRoundingMode to pool's public api yet, can we first see if this issue can be solved within pool's implementation? Can you add a test that will generate fractional outputs first?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4282#-:-MMqnF-i-HlhdPLYUzNs:b-cyene3)* status: 0 of 1 approvals obtained (waiting on @lina128)

**Review by lina128 — COMMENTED** [review]
Hi Bruce, I ran the test you added in this PR, it serves the purpose well, can you also add expected value? Also can you also add this test to conv2d_test.ts?
```
it('x=[1,2,2,3] f=[1,1] s=2 p=1 fractional outputs default rounding',
     async () => {
       const inputDepth = 3;
       const inShape: [number, number, number, number] = [1, 2, 2, inputDepth];
       const outputDepth = 1;
       const fSize = 1;

       const x = tf.tensor4d([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], inShape);
       const w =
           tf.tensor4d([2, 2, 1], [fSize, fSize, inputDepth, outputDepth]);
       const pad = 1;
       const strides = 2;

       const result = tf.conv2d(x, w, strides, pad);

       expect(result.shape).toEqual([1, 2, 2, 1]);
       expectArraysClose(await result.data(), [0, 0, 0, 54]);
     });
```
Here's the result, running equivalent test in tf python: https://colab.research.google.com/drive/17GIAyGkKzOaPgLZZGYS7e0ctGb--dwtN?usp=sharing

I suspect tf default rounding model is truncate value (default behavior of c++), and this proved my guess: I changed default rounding mode to Math.trunc(value) in tfjs (https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/conv_util.ts#L581), then it passed the test above. So can you:
(1) Instead of adding a param to public api, change the internal behavior of rounding? 
(2) Change the name from `conditionalRounding` to `round`, because the behavior will always round.
(3) Remove int assertions after each reference of `conditionalRounding`, because it is unnecessary.
(4) Add above test to conv2d_test.ts, also for the new test in pool_test.ts, make sure test result.data.

Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4282#-:-MMrJaXr5j0fj30cJ1AC:b-xejpux)* status: 0 of 1 approvals obtained (waiting on @lina128)

**Comment by BruceDai** [comment]
@lina128 Thanks, I've updated the pr according to your suggestion. Please take a review again, thanks.

**Review by lina128 — CHANGES_REQUESTED** [review]
Hi @brucedai , the PR is almost good to go. I left some comments to fix tests. Also, can you change all the doccomment about dimRoundingMode? Search for `@param dimRoundingMode`, change to something like this: A string from: 'ceil', 'round', 'floor'. If none is provided, it will default to truncate.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4282#-:-MMyREf52tS-GA8h41zh:by5ss6m)* status: 0 of 1 approvals obtained (waiting on @BruceDai)

___
*[tfjs-core/src/ops/conv2d_test.ts, line 441 at r5](https://reviewable.io/reviews/tensorflow/tfjs/4282#-MMyPNURAIi8TLHL4JZi:-MMyPNUS1xlTQsCwPApn:b-vqfz7h) ([raw file](https://github.com/tensorflow/tfjs/blob/c43bbfec8f7adeef034960dd30de6d6d76c9c336/tfjs-core/src/ops/conv2d_test.ts#L441)):*
> ```XML
>       const x = tf.tensor4d([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], inShape);
>       const w = tf.tensor4d([2, 2, 1], [fSize, fSize, inputDepth, outputDepth]);
>       const pad = 1;
> ```

I see that the test for Node backend is failing. The Node backend (calling TF c++ under the hood) only accepts 'same'|'valid'|explicit_padding. Can you change this line to:
```
const pad = [[0, 0], [1, 1], [1, 1], [0, 0]] as tf.backend_util.ExplicitPadding;
``
```

___
*[tfjs-core/src/ops/pool_test.ts, line 84 at r5](https://reviewable.io/reviews/tensorflow/tfjs/4282#-MMyQsHj2pvEBtFjPpZN:-MMyQsHj2pvEBtFjPpZO:b-q0sz5o) ([raw file](https://github.com/tensorflow/tfjs/blob/c43bbfec8f7adeef034960dd30de6d6d76c9c336/tfjs-core/src/ops/pool_test.ts#L84)):*
> ```XML
>   });
> 
>   it('max x=[2,2,3] f=[1,1] s=2 p=1 fractional outputs default rounding',
> ```

Add this test to ignore list in Node backend, because tf.pool doesn't support explicit_padding yet.

Add this line `pool test-tensorflow {} max x=[2,2,3] f=[1,1] s=2 p=1 fractional outputs default rounding` here: https://github.com/tensorflow/tfjs/blob/master/tfjs-node/src/run_tests.ts#L85
___
*[tfjs-core/src/ops/pool_test.ts, line 161 at r5](https://reviewable.io/reviews/tensorflow/tfjs/4282#-MMyRBv84yZ9Lmw7-yQO:-MMyRBv84yZ9Lmw7-yQP:b-qp6xwc) ([raw file](https://github.com/tensorflow/tfjs/blob/c43bbfec8f7adeef034960dd30de6d6d76c9c336/tfjs-core/src/ops/pool_test.ts#L161)):*
> ```XML
>   });
> 
>   it('avg x=[2,2,3] f=[1,1] s=2 p=1 fractional outputs default rounding',
> ```

Add this test to ignore list too: pool test-tensorflow {} avg x=[2,2,3] f=[1,1] s=2 p=1 fractional outputs default rounding

**Comment by BruceDai** [comment]
@lina128 Updated. PTAL, thanks.

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4282)* status: 0 of 1 approvals obtained (waiting on @BruceDai)

___
*[tfjs-node/src/run_tests.ts, line 85 at r6](https://reviewable.io/reviews/tensorflow/tfjs/4282#-MN-nwhVE6K53sKJZzsU:-MN-nwhVE6K53sKJZzsV:b-hbn4e7) ([raw file](https://github.com/tensorflow/tfjs/blob/ba981dba08161e7fa7b25febc00f9aaf086a6de2/tfjs-node/src/run_tests.ts#L85)):*
> ```XML
>   // libtensorflow does not yet support tf.matmul with broadcast
>   'broadcast with unequal batch dims', 'broadcast with unequal ranks',
>   'pool test-tensorflow {} max x=[2,2,3] f=[1,1] s=2 p=1 fractional outputs default rounding',
> ```

I see lint error in CI:
ERROR: (max-line-length) /workspace/tfjs-node/src/run_tests.ts[85, 1]: Exceeds maximum line length of 80
ERROR: (max-line-length) /workspace/tfjs-node/src/run_tests.ts[86, 1]: Exceeds maximum line length of 80

Please add lint-disable text on top of each of two lines:
`// tslint:disable-next-line:max-line-length`

**Comment by BruceDai** [comment]
@lina128 Fixed lint issuse. PTAL, thanks.

**Review by lina128 — APPROVED** [review]
LGTM, thank you Bruce!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4282#-:-MN21aun1WpHLWawWhWW:b-slnm76)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @BruceDai)

**Pull request merged**
