### PR TITLE
[webgpu] fix type dismatch in matmul_packed_webgpu

### PR DESCRIPTION
**Pull request by haoyunfeix**
BUG

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5812)

### CODE REVIEW

**Comment by gyagp** [comment]
Title should be mismatch instead of dismatch.

**Comment by qjia7** [comment]
We meet more and more such kind of type casting error. The previous one is #5767. The root case is that we don't check the data's type and just write it as a `f32` data. And our helper functions all force casting all type to `f32`. However, our inputs accept `f32` and `i32`. It makes the data casting a mess. We need to do below cleanup:
either 1) treat all data as f32 and only accept `f32` in shader like the webgl one.
or 2) choose the correct data type to do the calculation. This means if the inputs are `i32`, then all helper functions and main body are using `i32`. Otherwise, all helper functions and main body are using `f32`. No type casting happens in the shader. 

@gyagp @xhcao @axinging What's your opinion?
cc @lina128 @pyu10055

**Comment by gyagp** [comment]
Synced with Jiajia, we will try first approach.

**Comment by lina128** [comment]
First approach sounds good to me. If we are going to support quantization in the future, it may be a different set of functions any way.

**Pull request closed without merging**
