### PR TITLE
[core] Fix undefined `expect` in test_util

### PR DESCRIPTION
**Pull request by haoyunfeix**
expect().nothing() should only be called in jasmine test framework, add
if condition to avoid calling outside of the framework.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6671)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
@qjia7 @gyagp PTAL

**Review by qjia7 — APPROVED** [review]
LGTM, thanks.

**Review by gyagp — APPROVED** [review]
LGTM

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6671)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @mattsoulanille)

**Pull request merged**
