### PR TITLE
Add document for how to build a pure gpu pipeline.

### PR DESCRIPTION
**Pull request by lina128**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6088)

### CODE REVIEW

**Review by jinjingforever — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6088)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

*[a discussion](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYF5t7EsDRNWJikuPA:-MuYF5t7EsDRNWJikuPB:bk5za71) (no related file):*
This is very useful! Is it going to linked from the main README? I think we should?

---
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYEzmn358egY14fSp5:-MuYEzmoE7091lSFrYe0:b-r7iygt) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L1)):*
> ```Markdown
> # Optimization Topic - How to write a high performance GPU pipeline.
> ```

nit: remove period



_Code quote:_
```Markdown
.
```
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYDaZO0eYXyafmSwH5:-MuYDaZO0eYXyafmSwH6:byb6o4f) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L3)):*
> ```Markdown
> # Optimization Topic - How to write a high performance GPU pipeline.
> This document shows how to write a high performance GPU pipeline with TF.js. What we often encounter in a GPU pipeline is that, there are often
> some ML steps (e.g. taking some inputs, running a model and get outputs)
> ```

getting



_Code quote:_
```Markdown
get
```
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 57 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYEjsD1tv5MapFqhoE:-MuYEjsEDcJYhho3FsQu:b-my5fu8) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L57)):*
> ```Markdown
> processing steps need to compute where in the texture to get the right data. The `texShape` field has the `[height, width]` information of the
> texture, which can be used to compute to get the coordination of the texel
> to get data.
> ```

nit: which can be used to compute the texel coordination to get data



_Code quote:_
```Markdown
texture, which can be used to compute to get the coordination of the texel
to get data.
```

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6088)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYGSNs821rhZZooAjo:-MuYGSNs821rhZZooAjp:bl3g534) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L2)):*
> ```Markdown
> # Optimization Topic - How to write a high performance GPU pipeline.
> This document shows how to write a high performance GPU pipeline with TF.js. What we often encounter in a GPU pipeline is that, there are often
> ```

A typical ML pipeline is composed of some ML steps ...



_Code quote:_
```Markdown
What we often encounter in a GPU pipeline is that, there are often
```
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 4 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYGYqw6BBGSdh8h_ms:-MuYGYqw6BBGSdh8h_mt:bmuvkyc) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L4)):*
> ```Markdown
> This document shows how to write a high performance GPU pipeline with TF.js. What we often encounter in a GPU pipeline is that, there are often
> some ML steps (e.g. taking some inputs, running a model and get outputs)
> and non-ML steps (e.g. image processing, rendering, etc.). The generarl
> ```

general rule of thumb
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 5 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYGdqZDAotngdwHse7:-MuYGdqZDAotngdwHse8:b-qj2dpa) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L5)):*
> ```Markdown
> some ML steps (e.g. taking some inputs, running a model and get outputs)
> and non-ML steps (e.g. image processing, rendering, etc.). The generarl
> idea is that if the whole pipeline can run on GPU without ever syncing to
> ```

without downloading any data to CPU
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYGkJ76bZF2veFWiL6:-MuYGkJ76bZF2veFWiL7:bhoqbax) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L6)):*
> ```Markdown
> and non-ML steps (e.g. image processing, rendering, etc.). The generarl
> idea is that if the whole pipeline can run on GPU without ever syncing to
> CPU, it is usually much faster than a broken pipeline where some steps
> ```

than a fragmented pipeline that requires data transfer between CPU and GPU.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 14 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYH2v_9SUmYyMK7Fxc:-MuYH2v_9SUmYyMK7Fxd:bt190g8) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L14)):*
> ```Markdown
> API that allows data to stay in GPU. Our users are pretty faimilar with
> `tensor.dataSync()` and `tensor.data()`, however both will download data from GPU to CPU. In the latest release, we have added `tensor.dataToGPU()`,
> which returns a `GPUData` type. This object contains a `texture` field, a
> ```

maybe good to show the interface with inline comments than a block of text here.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYHES93AYW6ygdMZ5r:-MuYHES93AYW6ygdMZ5s:bz94vuq) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L18)):*
> ```Markdown
> texture and the `tensorRef` field holds the tensor that contains this texture and related tensor information.
> 
> The example below is pretty much self explained. We get the tensor texture by calling `dataToGPU()`. Here the tensor has a shape of
> ```

The example below shows how to get the tensor texture by calling 'dataToGPU()'



_Code quote:_
```Markdown
The example below is pretty much self explained.
```
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYKWqoAk1WkkNPZ1P6:-MuYKWqoAk1WkkNPZ1P7:bt5v3yb) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L25)):*
> ```Markdown
> // Getting the texture that holds the data on GPU.
> const data =
>       tensor.dataToGPU({customTexShape: [videoHeight, videoWidth]});
> ```

can you add example on how customTexShape should be used?
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYJuey7ZkMEoQCbAm3:-MuYJuey7ZkMEoQCbAm4:b-kh2hcq) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L42)):*
> ```Markdown
> 
> ```
>     000|001   010|011   020|021
> ```

dense format does not pack two dimensions, only the last dimension, better to draw horizontally
000|001|002|003 ...
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYKIVqAyCRPbI4sKFu:-MuYKIVqAyCRPbI4sKFv:bpmmug7) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L54)):*
> ```Markdown
> way we store the data aligns with how image is stored, therefore if the
> downstream processing assumes the texture is an image, it doesn't need to
> do any additional coordination conversion. Each texel is mapped to a CSS pixel in an image. However, if the tensor has other shapes, downstream
> ```

what is `CSS pixel`?
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYKnio3GZqcGi1pCb9:-MuYKnio3GZqcGi1pCbA:b-4g3fij) ([raw file](https://github.com/tensorflow/tfjs/blob/fe4d749a0dc7d716806f679980dc322ce17dab32/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L55)):*
> ```Markdown
> downstream processing assumes the texture is an image, it doesn't need to
> do any additional coordination conversion. Each texel is mapped to a CSS pixel in an image. However, if the tensor has other shapes, downstream
> processing steps need to compute where in the texture to get the right data. The `texShape` field has the `[height, width]` information of the
> ```

good to give an example on how to use the linear index to compute the width/height/channel

**Review by lina128 — COMMENTED** [review]
Thank you both for the review!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6088#-:-MulXtG7-26guvjB_CxF:biawstc)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @pyu10055)

___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYEzmn358egY14fSp5:-MulLfuZ7DKeiSrof_9Q:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L1)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

nit: remove period
</blockquote></details>

Done.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 2 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYGSNs821rhZZooAjo:-MulLuksDVZSEhD0FQ5n:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L2)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

A typical ML pipeline is composed of some ML steps ...
</blockquote></details>

Done.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYDaZO0eYXyafmSwH5:-MulLv1l-C5872TCqpaD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L3)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

getting
</blockquote></details>

Done.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 4 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYGYqw6BBGSdh8h_ms:-MulM-Mt6LWVMP2JFLQl:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L4)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

general rule of thumb
</blockquote></details>

Done.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 5 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYGdqZDAotngdwHse7:-MulM4yuAnsIPNoDfAo4:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L5)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

without downloading any data to CPU
</blockquote></details>

Done.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYGkJ76bZF2veFWiL6:-MulMENK4Jn6YfSJtltK:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L6)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

than a fragmented pipeline that requires data transfer between CPU and GPU.
</blockquote></details>

Done.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 14 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYH2v_9SUmYyMK7Fxc:-MulNylO55RiQROAsviB:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L14)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

maybe good to show the interface with inline comments than a block of text here.
</blockquote></details>

Done.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYHES93AYW6ygdMZ5r:-MulO8Uf93APkYaIF6u9:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L18)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

The example below shows how to get the tensor texture by calling 'dataToGPU()'
</blockquote></details>

Done.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYJuey7ZkMEoQCbAm3:-MulOjtN3Si06hBwjNhc:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L42)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

dense format does not pack two dimensions, only the last dimension, better to draw horizontally
000|001|002|003 ...
</blockquote></details>

Done.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYKIVqAyCRPbI4sKFu:-MulOqvEDtX6Q_TVu0IL:b-hgw3jl) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L54)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

what is `CSS pixel`?
</blockquote></details>

Added link.
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 55 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYKnio3GZqcGi1pCb9:-MulXQ3l6OQPKMPPTmmj:bjcr6pj) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L55)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

good to give an example on how to use the linear index to compute the width/height/channel
</blockquote></details>

This is really case by case. 
___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 57 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MuYEjsD1tv5MapFqhoE:-MulXfDG1vpKRKg_5T4p:b-oy22xc) ([raw file](https://github.com/tensorflow/tfjs/blob/6a54ef22b249a74f38928262bdfced8abf2dd63c/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L57)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

nit: which can be used to compute the texel coordination to get data
</blockquote></details>

Thanks, reworded.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6088)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @pyu10055)

___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MumCXNbEMIls8-y1rj4:-MumCXNbEMIls8-y1rj5:b-q8t4a9) ([raw file](https://github.com/tensorflow/tfjs/blob/0c9f03515f7a3d5df38c1082b34d2abf11bf6ddb/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L26)):*
> ```Markdown
>       tensor.dataToGPU({customTexShape: [videoHeight, videoWidth]});
> 
> // Once we have the texture, we can bind it and pass it to the downstream /// webgl processing steps to use the texture.
> ```

split the line?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6088)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @pyu10055)

___
*[docs/OPTIMIZATION_PURE_GPU_PIPELINE.md, line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs/6088#-MumCXNbEMIls8-y1rj4:-MumMtWl-xTADPYYUH8t:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/0c9f03515f7a3d5df38c1082b34d2abf11bf6ddb/docs/OPTIMIZATION_PURE_GPU_PIPELINE.md#L26)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

split the line? 
</blockquote></details>

Done.

**Pull request merged**
