### PR TITLE
Add doc for how to contribute missing ops.

### PR DESCRIPTION
**Pull request by lina128**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4023)

### CODE REVIEW

**Review by jinjingforever — COMMENTED** [review]
Thank you Na for writing this! Very helpful

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4023#-:-MIuhX0rAhB_J7lEV2K4:b1mz5tn)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, @pyu10055, and @tafsiri)

___
*[CONTRIBUTING_MISSING_OP.md, line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIubYKHDP7rQx8X3U6T:-MIubYKHDP7rQx8X3U6U:b-pa6hcx) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L6)):*
> ```Markdown
> **Prerequisite**
> 1. The op should already be supported in [TF](https://www.tensorflow.org/api_docs/python/tf/all_symbols) api.
> 2. The op should not have been supported in TF.js.
> ```

It might be helpful to link this to some files so people can check if the the op has been supported by tfjs?
___
*[CONTRIBUTING_MISSING_OP.md, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIudQXx8jI9Q2svt6Yh:-MIudQXx8jI9Q2svt6Yi:bgczhmr) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L21)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>  The op file should have below elements:
>     1. License information.
>     2. Doccomment.
>     3. Input validations, if any.
>     4. Delegate the execution to the right kernel through `ENGINE.runKernel()`.
>   In addition, for the kernel delegation to work properly, in `kernel_names.ts`
>   file, define:
>     1. kernel name.
>     2. input type.
>     3. attribute type.
> ```
</details>


nit: Looks like this part is not indented properly: https://screenshot.googleplex.com/9JxeDV2hJxovp6X. I think you can try adding 2 more spaces to the beginning of each line
___
*[CONTRIBUTING_MISSING_OP.md, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIueDctD5gpNHsY0dLt:-MIueDctD5gpNHsY0dLu:be4v5pj) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L34)):*
> ```Markdown
>      return false;
>    }
> ```

Remove extra blank line
___
*[CONTRIBUTING_MISSING_OP.md, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIue03xCub7imwlp3_H:-MIue03xCub7imwlp3_I:bgoyq64) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L47)):*
> ```
> **cpu backend**
> In `run_tests.ts`, `customInclude` method, add:
> ```
>    // Not implemented yet.
>    if (testName.includes(test_name)) {
>      return false;
>    }
> ```
> **webgl backend**
> In `setup_test.ts`, `customInclude` method, add:
> ```
>    // Not implemented yet.
>    if (testName.includes(test_name)) {
>      return false;
>    }
> ```
> **node backend**
> In `run_tests.ts`, `IGNORE_LIST`, add test_name to the list.
> ```

Similar problem. Try adding 4 spaces to the beginning of each line.
___
*[CONTRIBUTING_MISSING_OP.md, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIueYJO7NQYRBreg3P0:-MIueYJO7NQYRBreg3P1:b3eze0s) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L56)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>  The kernel file should have below elements:
>   1. License information.
>   2. The kernel implementation, and export it.
>   3. Export a `kernelConfig`.
> ```
</details>


The list here is a little bit broken: https://screenshot.googleplex.com/7DK3Zb3ebtvoEGc. Similar fix as above.
___
*[CONTRIBUTING_MISSING_OP.md, line 58 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuhCOd462RnsuyKS7B:-MIuhCOd462RnsuyKS7C:b34vn5g) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L58)):*
> ```Markdown
>   3. Export a `kernelConfig`.
> 
> 2. Register the kernel in `register_all_kernels.ts` in the corresponding backend.
> ```

Just curious: at what point should we remove the test names from the exclusion list mentioned above? Is it the author's responsibility or ours?
___
*[CONTRIBUTING_MISSING_OP.md, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIugatqE5ujptVoUSNa:-MIugatqE5ujptVoUSNb:b-306qff) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L61)):*
> ```Markdown
> 
> ### Step 3. Add the op to Converter’s executor.
> 1. Add op mapping in the op list json files, use your best judgement to assign an op category: `tfjs-converter/src/operations/op_list/{corresponding_op_category}.ts`
> ```

Might also be helpful to mention where to find the official op/inputs name (I only know this [place](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/ops), but there might be more)
___
*[CONTRIBUTING_MISSING_OP.md, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIufUMM9YvInHkdXELN:-MIufUMM9YvInHkdXELO:btieo45) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L66)):*
> ```Markdown
> 
> 3. Find the corresponding executor for the op and add the op to the switch, the executors are in `tfjs-converter/src/operations/executors`.
> ```

Probably need to add test in the corresponding test file for the executor?

**Review by tafsiri — COMMENTED** [review]
Great stuff, took a first pass at adding some comments.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4023#-:-MIukB2A0WXF78y86-E-:bd8fl8n)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, @pyu10055, and @tafsiri)

___
*[CONTRIBUTING_MISSING_OP.md, line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIubYKHDP7rQx8X3U6T:-MIuism10D_01fFEG7FF:b4wwvyr) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L6)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

It might be helpful to link this to some files so people can check if the the op has been supported by tfjs?
</blockquote></details>

+1 You can link to to the github folder for 'ops' in core.
___
*[CONTRIBUTING_MISSING_OP.md, line 11 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuilh53v2swS58Sh7m:-MIuilh53v2swS58Sh7n:bbhxqfu) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L11)):*
> ```Markdown
> 1. Create a new op in `tfjs-core/ops` directory.
> 
>   The op file should have below elements:
> ```

nit: should have the following elements
___
*[CONTRIBUTING_MISSING_OP.md, line 13 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuicYy8H_x_gIk57tn:-MIuicYy8H_x_gIk57to:bvqk095) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L13)):*
> ```Markdown
>   The op file should have below elements:
>     1. License information.
>     2. Doccomment.
> ```

nit spacing, also, change this to "JSDoc comment"
___
*[CONTRIBUTING_MISSING_OP.md, line 58 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuhCOd462RnsuyKS7B:-MIujDuG5Kk_0kfEdSqq:b857sbj) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L58)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Just curious: at what point should we remove the test names from the exclusion list mentioned above? Is it the author's responsibility or ours?
</blockquote></details>

+1 I would actually have them start by removing the exclusion for the backend they are implementing a kernel for. That way they start with a failing test that they need to make pass.
___
*[CONTRIBUTING_MISSING_OP.md, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIugatqE5ujptVoUSNa:-MIujXm24nsqiuw1twva:b-v62fkr) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L61)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Might also be helpful to mention where to find the official op/inputs name (I only know this [place](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/core/ops), but there might be more)
</blockquote></details>

Yeah I wonder if a bit more detail in this sentence might help, disambiguating the TensorFlow op from the TFJS op one is mapping too would be helpful. I would also link to one of the files as an example.
___
*[CONTRIBUTING_MISSING_OP.md, line 63 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIujuDeB6fkCPR8DYjI:-MIujuDeB6fkCPR8DYjJ:b-z5j63x) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L63)):*
> ```Markdown
> 1. Add op mapping in the op list json files, use your best judgement to assign an op category: `tfjs-converter/src/operations/op_list/{corresponding_op_category}.ts`
> 
> 2. Auto generates corresponding json file by running following command in directory tfjs-converter: `yarn gen-json`. Check that the json object is generated in `python/tensorflowjs/op_list/{corresponding_op_group}.json`
> ```

How would you describe this file (i know it corresponds) in some way to the op mapping file above, but what you would call this one.
___
*[CONTRIBUTING_MISSING_OP.md, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuk50WDJBwTRa_ZM6u:-MIuk50WDJBwTRa_ZM6v:bcqgip0) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L65)):*
> ```Markdown
> 2. Auto generates corresponding json file by running following command in directory tfjs-converter: `yarn gen-json`. Check that the json object is generated in `python/tensorflowjs/op_list/{corresponding_op_group}.json`
> 
> 3. Find the corresponding executor for the op and add the op to the switch, the executors are in `tfjs-converter/src/operations/executors`.
> ```

add an example link (or link to the folder of executors)

**Review by lina128 — COMMENTED** [review]
Thank you for the detailed review! @jinjingforever and @tafsiri  Please take another look. Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4023#-:-MIurin7Ah_ue01IlqTX:brhawab)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @pyu10055, and @tafsiri)

___
*[CONTRIBUTING_MISSING_OP.md, line 6 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIubYKHDP7rQx8X3U6T:-MIulDiKDv11flOUDjxO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L6)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

+1 You can link to to the github folder for 'ops' in core.
</blockquote></details>

Done.
___
*[CONTRIBUTING_MISSING_OP.md, line 11 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuilh53v2swS58Sh7m:-MIulK1764E_PA-ASuXW:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L11)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

nit: should have the following elements
</blockquote></details>

Done.
___
*[CONTRIBUTING_MISSING_OP.md, line 13 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuicYy8H_x_gIk57tn:-MIuldzN1vsqLmdnk4YO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L13)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

nit spacing, also, change this to "JSDoc comment"
</blockquote></details>

Done.
___
*[CONTRIBUTING_MISSING_OP.md, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIudQXx8jI9Q2svt6Yh:-MIumjh88Alij81yVTED:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L21)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

> ```
>  The op file should have below elements:
>     1. License information.
>     2. Doccomment.
>     3. Input validations, if any.
>     4. Delegate the execution to the right kernel through `ENGINE.runKernel()`.
>   In addition, for the kernel delegation to work properly, in `kernel_names.ts`
>   file, define:
>     1. kernel name.
>     2. input type.
>     3. attribute type.
> ```

nit: Looks like this part is not indented properly: https://screenshot.googleplex.com/9JxeDV2hJxovp6X. I think you can try adding 2 more spaces to the beginning of each line
</blockquote></details>

Done.
___
*[CONTRIBUTING_MISSING_OP.md, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIueDctD5gpNHsY0dLt:-MIumpTWCanqhKS93334:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L34)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Remove extra blank line
</blockquote></details>

Done.
___
*[CONTRIBUTING_MISSING_OP.md, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIue03xCub7imwlp3_H:-MIun4N_Bb0r0sWA9P9w:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L47)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

> ```
> **cpu backend**
> In `run_tests.ts`, `customInclude` method, add:
> ```
>    // Not implemented yet.
>    if (testName.includes(test_name)) {
>      return false;
>    }
> ```
> **webgl backend**
> In `setup_test.ts`, `customInclude` method, add:
> ```
>    // Not implemented yet.
>    if (testName.includes(test_name)) {
>      return false;
>    }
> ```
> **node backend**
> In `run_tests.ts`, `IGNORE_LIST`, add test_name to the list.
> ```

Similar problem. Try adding 4 spaces to the beginning of each line.
</blockquote></details>

Done.
___
*[CONTRIBUTING_MISSING_OP.md, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIueYJO7NQYRBreg3P0:-MIunG5T9Q4ZPPfer0Ad:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L56)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

> ```
>  The kernel file should have below elements:
>   1. License information.
>   2. The kernel implementation, and export it.
>   3. Export a `kernelConfig`.
> ```

The list here is a little bit broken: https://screenshot.googleplex.com/7DK3Zb3ebtvoEGc. Similar fix as above.

</blockquote></details>

Done.
___
*[CONTRIBUTING_MISSING_OP.md, line 58 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuhCOd462RnsuyKS7B:-MIund7M3KPsWP32PWIe:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L58)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

+1 I would actually have them start by removing the exclusion for the backend they are implementing a kernel for. That way they start with a failing test that they need to make pass.
</blockquote></details>

Done.
___
*[CONTRIBUTING_MISSING_OP.md, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIugatqE5ujptVoUSNa:-MIuorN--E1_JsM5kSun:b8kub8v) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L61)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Yeah I wonder if a bit more detail in this sentence might help, disambiguating the TensorFlow op from the TFJS op one is mapping too would be helpful. I would also link to one of the files as an example.
</blockquote></details>

Done. Added link to the c++ op api.
___
*[CONTRIBUTING_MISSING_OP.md, line 63 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIujuDeB6fkCPR8DYjI:-MIupJhR-VEk_Q33pS6b:b7m64m6) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L63)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

How would you describe this file (i know it corresponds) in some way to the op mapping file above, but what you would call this one.
</blockquote></details>

Does it need a name?
___
*[CONTRIBUTING_MISSING_OP.md, line 65 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuk50WDJBwTRa_ZM6u:-MIupjiX0l4MNQHoJorj:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L65)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

add an example link (or link to the folder of executors)
</blockquote></details>

Done.
___
*[CONTRIBUTING_MISSING_OP.md, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIufUMM9YvInHkdXELN:-MIuqOPc3Dvc3AWES46T:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L66)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Probably need to add test in the corresponding test file for the executor?
</blockquote></details>

Done.

**Review by jinjingforever — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4023#-:-MIut-Vy0Gp-qsv6LZql:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @pyu10055, and @tafsiri)

**Review by tafsiri — APPROVED** [review]
LGTM. One comment/question about WASM test exclusion.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4023#-:-MIuyQse4aSxgHa9zFY2:b-gp6sja)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @pyu10055)

___
*[CONTRIBUTING_MISSING_OP.md, line 63 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIujuDeB6fkCPR8DYjI:-MIuxwvm3QEmETDm4LLd:b3tgvxp) ([raw file](https://github.com/tensorflow/tfjs/blob/401ba614ae39b5720935f18f217f4b9649f36ba7/CONTRIBUTING_MISSING_OP.md#L63)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Does it need a name?
</blockquote></details>

Not really, but reading this even i don't know what this is for. Make it clear might help us all :). If there is a reasonable name for it, i'd add it else no worries to leave this as is.
___
*[CONTRIBUTING_MISSING_OP.md, line 50 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuxnjF5HJ9psvNWiLm:-MIuxnjF5HJ9psvNWiLn:b5m7oyr) ([raw file](https://github.com/tensorflow/tfjs/blob/d1529e748d7e5319eb430a2c58fd8e8ff638eb37/CONTRIBUTING_MISSING_OP.md#L50)):*
> ```Markdown
> 
> In `run_tests.ts`, `IGNORE_LIST`, add test_name to the list.
> ```

Does the WASM backend need the op excluded from tests or does it work via including specific things? (if so how might that affect the steps below, in particular the test setup modification).

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4023)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, @pyu10055, and @tafsiri)

___
*[CONTRIBUTING_MISSING_OP.md, line 50 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIuxnjF5HJ9psvNWiLm:-MIv29nd02_ehhIojlRr:b-nd51nw) ([raw file](https://github.com/tensorflow/tfjs/blob/d1529e748d7e5319eb430a2c58fd8e8ff638eb37/CONTRIBUTING_MISSING_OP.md#L50)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Does the WASM backend need the op excluded from tests or does it work via including specific things? (if so how might that affect the steps below, in particular the test setup modification).
</blockquote></details>

It works via including specific things. Ah, nice catch. Added instruction to add test for wasm backend.

**Review by pyu10055 — COMMENTED** [review]
Thanks this is great!

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4023#-:-MIyP2Xd7BJslxuBDNTd:b8jg9ay)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, @pyu10055, and @tafsiri)

___
*[CONTRIBUTING_MISSING_OP.md, line 5 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIyQ-fO5wfnqJV7U2QR:-MIyQ-fO5wfnqJV7U2QS:bu2l0su) ([raw file](https://github.com/tensorflow/tfjs/blob/a96c52d4ba3aeadec5bc2927f419a5562c0b365f/CONTRIBUTING_MISSING_OP.md#L5)):*
> ```
> https://www.tensorflow.org/api_docs/python/tf/all_symbols
> ```
I think we are more aligned with TF raw_ops https://www.tensorflow.org/api_docs/python/tf/raw_ops
___
*[CONTRIBUTING_MISSING_OP.md, line 9 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIyQ8lH-RzLuk8wnf-H:-MIyQ8lH-RzLuk8wnf-I:b80b406) ([raw file](https://github.com/tensorflow/tfjs/blob/a96c52d4ba3aeadec5bc2927f419a5562c0b365f/CONTRIBUTING_MISSING_OP.md#L9)):*
> ```Markdown
> 
> **Implementation Details**
> 1. Create a new op in `tfjs-core/ops` directory.
> ```

It would be better to provide a link to an existing op PR as example, maybe jingjin's unqiue OP
___
*[CONTRIBUTING_MISSING_OP.md, line 29 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4023#-MIyQYiSAMpTRhIFqZK6:-MIyQYiSAMpTRhIFqZK7:b-3plukh) ([raw file](https://github.com/tensorflow/tfjs/blob/a96c52d4ba3aeadec5bc2927f419a5562c0b365f/CONTRIBUTING_MISSING_OP.md#L29)):*
> ```Markdown
> **cpu backend**
> 
> In `run_tests.ts`, `customInclude` method, add:
> ```

If the idea is that users will implement all backend in a single PR, should the test fail first for all backend? (TDD type of process)

**Pull request merged**
