### PR TITLE
e2e tests for custom bundles

### PR DESCRIPTION
**Pull request by tafsiri**
Adds an e2e test for making customb bundle programs.

The user journey is building a custom app with blazeface. user code => create custom tfjs modules => create custom bundle => load in browser and test.

Currently uses wasm as the backend and webpack as the builder. I tried for a long time to get rollup working as well but can't build an app using rollup and wasm (excluding all the custom bundle stuff, just a regular app). So i gave up and just followed the starter project example in tfjs-backend-wasm. 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3938)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3938)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[e2e/custom_bundle/blazeface/app.js, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNo_405wP37s6aBgBw:-MHNo_405wP37s6aBgBx:b-nhxyu4) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/custom_bundle/blazeface/app.js#L25)):*
> ```JavaScript
> import '@tensorflow/tfjs-core/dist/public/chained_ops/div';
> 
> import * as blazeface from '@tensorflow-models/blazeface';
> ```

Curious, blazeface installs its version of tfjs-core, and then tfjs installs its version of tfjs-core, are there two copies of tfjs-core in node_modules, one under blazeface, one in top level. Is it resolved in the webpack (the last part in that file)?
___
*[e2e/custom_bundle/blazeface/custom_tfjs_blazeface/custom_tfjs.js, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNqfrz5Rko9zydgkLX:-MHNqfrz5Rko9zydgkLY:blwdu8b) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/custom_bundle/blazeface/custom_tfjs_blazeface/custom_tfjs.js#L1)):*
> ```JavaScript
> 
> ```

nit: Maybe for auto-generated code, we should insert an annotation, this file is auto-generated?
___
*[e2e/integration_tests/custom_bundle_test.ts, line 62 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNljOL-28dDKNV41NJ:-MHNljOL-28dDKNV41NK:b-uebilr) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/integration_tests/custom_bundle_test.ts#L62)):*
> ```XML
>       ]));
> 
>       expect(result.predictions.length).toEqual(0);
> ```

Can we also compare the prediction result of full vs custom bundle?
___
*[e2e/scripts/run-custom-builds.sh, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNrUvn59c-eE1SrQ7I:-MHNrUvn59c-eE1SrQ7J:bthossi) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/scripts/run-custom-builds.sh#L18)):*
> ```Shell
> # ==============================================================================
> 
> # Go to e2e root
> ```

Add this at the beginning:
```
# Start in scripts/ even if run from root directory
cd "$(dirname "$0")"
```
Then you can safely do:
```
cd ..
e2e_root_path=$PWD
```
___
*[e2e/scripts/run-custom-builds.sh, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNrmm6E_xBkxNWD8gr:-MHNrmm7DMqegJR2tNO-:bwj8gzm) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/scripts/run-custom-builds.sh#L25)):*
> ```Shell
> cd custom_bundle/blazeface
> yarn
> yarn make-custom-tfjs-modules
> ```

Should we gitignore the auto-generated files?
___
*[e2e/scripts/test.sh, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNm_bP6n8zOR3tJCyd:-MHNm_bP6n8zOR3tJCye:b-r42j1e) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/scripts/test.sh#L34)):*
> ```Shell
>     TAGS="${TAGS},#REGRESSION"
> fi
> ```

Add if "$TAGS" == *"#SMOKE"*, and add ./scripts/run-custom-builds.sh, this explicitly express the setups for each tag.

**Review by tafsiri — COMMENTED** [review]
Thanks @lina128 for your review, I made some fixes and left some comments for you to take a look at.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3938#-:-MHRp9I9EP2C-iomjvKT:b-79skd7)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[e2e/custom_bundle/blazeface/app.js, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNo_405wP37s6aBgBw:-MHRlIxq7aiDvFwCGQWr:b-bay33q) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/custom_bundle/blazeface/app.js#L25)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Curious, blazeface installs its version of tfjs-core, and then tfjs installs its version of tfjs-core, are there two copies of tfjs-core in node_modules, one under blazeface, one in top level. Is it resolved in the webpack (the last part in that file)?
</blockquote></details>

tfjs-core is a peerDependency (and devDependency) in blazeface, so it doesn't get installed just by installation of blazeface. 
___
*[e2e/custom_bundle/blazeface/custom_tfjs_blazeface/custom_tfjs.js, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNqfrz5Rko9zydgkLX:-MHRljpCEcoCVVfzqkHv:b-qd0qdm) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/custom_bundle/blazeface/custom_tfjs_blazeface/custom_tfjs.js#L1)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

nit: Maybe for auto-generated code, we should insert an annotation, this file is auto-generated?
</blockquote></details>

Good idea! Done
___
*[e2e/integration_tests/custom_bundle_test.ts, line 62 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNljOL-28dDKNV41NJ:-MHRmFbP84jyA2YL5QFD:b77rxh5) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/integration_tests/custom_bundle_test.ts#L62)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can we also compare the prediction result of full vs custom bundle?
</blockquote></details>

In this case it is the same as there are no predictions. I did think about going down the route of setting up a test image and comparing values for real data, but feel like I don't want to replicate tests in blazeface that might drift over time. Here we mainly test that it can run an inference without error. WDYT?

Comparing the two build would also add some complexity because in WASM you need a code change in the program itself (because of setWasmPaths/how the backend needs to be imported), so we would actually need two different programs.

However I added a TODO to revisit this once CPU has modularized the ops for blazeface. With the two implementations we will be able to better see if the generated tool can handle the difference. 
___
*[e2e/scripts/run-custom-builds.sh, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNrmm6E_xBkxNWD8gr:-MHRma1u-HYAUnZbjmhs:brr7wy1) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/scripts/run-custom-builds.sh#L25)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should we gitignore the auto-generated files?
</blockquote></details>

good question. part o me likes the idea of being able to review them if they change over time because of a change in the tool. e.g. it enable you to give the suggestion about adding the generate file notice at the top of these files! :)
___
*[e2e/scripts/test.sh, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNm_bP6n8zOR3tJCyd:-MHRnmaUA0cdTBcYOtgq:b-ns008o) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/scripts/test.sh#L34)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Add if "$TAGS" == *"#SMOKE"*, and add ./scripts/run-custom-builds.sh, this explicitly express the setups for each tag.
</blockquote></details>

Done. PTAL

**Review by tafsiri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3938)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan and @lina128)

___
*[e2e/scripts/run-custom-builds.sh, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNrUvn59c-eE1SrQ7I:-MHWZMWb92UPHHVKzltP:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/scripts/run-custom-builds.sh#L18)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Add this at the beginning:
```
# Start in scripts/ even if run from root directory
cd "$(dirname "$0")"
```
Then you can safely do:
```
cd ..
e2e_root_path=$PWD
```
</blockquote></details>

Done

**Review by lina128 — APPROVED** [review]
This is a great addition to the e2e suite. Thank you Yannick! LGTM!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3938#-:-MHXKoSB3o4lGptcB45M:bfn2fer)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[e2e/custom_bundle/blazeface/app.js, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNo_405wP37s6aBgBw:-MHTAQQV8bjj7SBztQst:bq0k0j) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/custom_bundle/blazeface/app.js#L25)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

tfjs-core is a peerDependency (and devDependency) in blazeface, so it doesn't get installed just by installation of blazeface. 
</blockquote></details>

Got it. Thanks for the explanation Yannick.
___
*[e2e/integration_tests/custom_bundle_test.ts, line 62 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNljOL-28dDKNV41NJ:-MHTAnYb5PnJGMe4A6aq:b-h5vsvu) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/integration_tests/custom_bundle_test.ts#L62)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

In this case it is the same as there are no predictions. I did think about going down the route of setting up a test image and comparing values for real data, but feel like I don't want to replicate tests in blazeface that might drift over time. Here we mainly test that it can run an inference without error. WDYT?

Comparing the two build would also add some complexity because in WASM you need a code change in the program itself (because of setWasmPaths/how the backend needs to be imported), so we would actually need two different programs.

However I added a TODO to revisit this once CPU has modularized the ops for blazeface. With the two implementations we will be able to better see if the generated tool can handle the difference. 
</blockquote></details>

Make sense. As long as we can separate no prediction and no-op/error, then it's fine not checking the output.
___
*[e2e/scripts/run-custom-builds.sh, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNrmm6E_xBkxNWD8gr:-MHXKaXxDEOeX8RZQcTY:b92awpi) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/scripts/run-custom-builds.sh#L25)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

good question. part o me likes the idea of being able to review them if they change over time because of a change in the tool. e.g. it enable you to give the suggestion about adding the generate file notice at the top of these files! :)
</blockquote></details>

Use it as golden and compare overtime makes sense.

**Review by annxingyuan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3938)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[e2e/custom_bundle/blazeface/app.js, line 44 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHkd-aa9AioPCmBhXAG:-MHkd-aa9AioPCmBhXAH:brz5axn) ([raw file](https://github.com/tensorflow/tfjs/blob/e9dc41bf5f7da782c04ef339d32cde1a9c219419/e2e/custom_bundle/blazeface/app.js#L44)):*
> ```JavaScript
>   tf.env().set('WASM_HAS_MULTITHREAD_SUPPORT', false);
>   self.postMessage({msg: true, payload: 'in worker main function'});
>   await tf.ready();
> ```

could do `await tf.setBackend('wasm')` and then I think you wouldn't need to call tf.ready()
___
*[e2e/custom_bundle/blazeface/app.js, line 66 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHke2Cb6wxWwUjsU1cB:-MHke2Cb6wxWwUjsU1cC:bpymb53) ([raw file](https://github.com/tensorflow/tfjs/blob/e9dc41bf5f7da782c04ef339d32cde1a9c219419/e2e/custom_bundle/blazeface/app.js#L66)):*
> ```JavaScript
>       tf.ones([100, 100, 3]), false /*returnTensors*/);
> 
>   self.postMessage({
> ```

would you be able to add a comment about how you expect numKernels / kernelNames below to compare to numKernels / kernelNames above?
___
*[e2e/integration_tests/custom_bundle_test.ts, line 35 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHkhOPbEU5LEcq79tta:-MHkhOPc89nNwESIa-Je:b-dlbdiu) ([raw file](https://github.com/tensorflow/tfjs/blob/e9dc41bf5f7da782c04ef339d32cde1a9c219419/e2e/integration_tests/custom_bundle_test.ts#L35)):*
> ```XML
>     beforeAll(async () => {
>       const [webpackFull, webpackCustom] = await Promise.all([
>         fetch(getBundleUrl('blazeface', false, 'webpack')).then(r => r.text()),
> ```

could you name the second argument
___
*[e2e/integration_tests/custom_bundle_test.ts, line 64 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHkhvwe0gJa1T-sj5QI:-MHkhvwe0gJa1T-sj5QJ:b-dw5ete) ([raw file](https://github.com/tensorflow/tfjs/blob/e9dc41bf5f7da782c04ef339d32cde1a9c219419/e2e/integration_tests/custom_bundle_test.ts#L64)):*
> ```XML
>       // TODO(yassogba) revisit the question of comparing the output of full
>       // and custom bundle on real inputs once CPU has modularized the blazeface
>       // kernels.
> ```

would it make sense to pass in an image containing a face rather than tf.ones and just check that `result.predictions.length` is equal to 1? we wouldn't need to check values, just that a prediction is returned. in the blazeface repo in tfjs-models there's a stubbed image array that contains a face: https://github.com/tensorflow/tfjs-models/blob/master/blazeface/src/test_util.ts

**Review by tafsiri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3938)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[e2e/custom_bundle/blazeface/app.js, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNo_405wP37s6aBgBw:-MHl5oRe0eysQN4tFlPu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/custom_bundle/blazeface/app.js#L25)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Got it. Thanks for the explanation Yannick.
</blockquote></details>

Done.
___
*[e2e/custom_bundle/blazeface/app.js, line 44 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHkd-aa9AioPCmBhXAG:-MHl5pJS93ZkgxBql_IK:bnjop93) ([raw file](https://github.com/tensorflow/tfjs/blob/e9dc41bf5f7da782c04ef339d32cde1a9c219419/e2e/custom_bundle/blazeface/app.js#L44)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

could do `await tf.setBackend('wasm')` and then I think you wouldn't need to call tf.ready()
</blockquote></details>

True. I think I prefer tf.ready as this part can stay consistent regardless of how the backend is set (including in a setup with multiple available backends where we don't want to set it explicitly).
___
*[e2e/custom_bundle/blazeface/app.js, line 66 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHke2Cb6wxWwUjsU1cB:-MHl6Mez3q1zsDxnFX37:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/e9dc41bf5f7da782c04ef339d32cde1a9c219419/e2e/custom_bundle/blazeface/app.js#L66)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

would you be able to add a comment about how you expect numKernels / kernelNames below to compare to numKernels / kernelNames above?
</blockquote></details>

Done.
___
*[e2e/integration_tests/custom_bundle_test.ts, line 62 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHNljOL-28dDKNV41NJ:-MHl8WDG1-X7gJ9ILIWO:b-cwltbh) ([raw file](https://github.com/tensorflow/tfjs/blob/4c87499e33dec0518d8b592c8ee996ea7340b96b/e2e/integration_tests/custom_bundle_test.ts#L62)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Make sense. As long as we can separate no prediction and no-op/error, then it's fine not checking the output.
</blockquote></details>

Resolved with Ann's suggestion above. We have some test data that asserts that there should be exactly one prediction (but we don't try to assert anything about the correctness of said prediction).
___
*[e2e/integration_tests/custom_bundle_test.ts, line 35 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHkhOPbEU5LEcq79tta:-MHl6iE4-n0B4dcYgdnn:b18pye7) ([raw file](https://github.com/tensorflow/tfjs/blob/e9dc41bf5f7da782c04ef339d32cde1a9c219419/e2e/integration_tests/custom_bundle_test.ts#L35)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

could you name the second argument
</blockquote></details>

done, here and above
___
*[e2e/integration_tests/custom_bundle_test.ts, line 64 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3938#-MHkhvwe0gJa1T-sj5QI:-MHl8Sj77MZCHFzzM9NU:bixqer5) ([raw file](https://github.com/tensorflow/tfjs/blob/e9dc41bf5f7da782c04ef339d32cde1a9c219419/e2e/integration_tests/custom_bundle_test.ts#L64)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

would it make sense to pass in an image containing a face rather than tf.ones and just check that `result.predictions.length` is equal to 1? we wouldn't need to check values, just that a prediction is returned. in the blazeface repo in tfjs-models there's a stubbed image array that contains a face: https://github.com/tensorflow/tfjs-models/blob/master/blazeface/src/test_util.ts
</blockquote></details>

Great suggestion. Done!

**Pull request merged**
