### PR TITLE
Add Unique op

### PR DESCRIPTION
**Pull request by jinjingforever**
This is for issue #1866 (per Ping's suggestion)

- To match the TF implementation, the op supports int32, bool, and string. In theory it also supports floats, but I guess it is not that useful in practice.
- The op API also accepts an "axis" parameter, but it is not used now. It is there to support UniqueV2 that we might want to support in the future.
- For now, the webgl backend will forwarded calculations to cpu backend.
- Hook it up with converter. Please check if there is anything that I missed.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
Hi Jing, a high level question, is uniqueV2 a more generic case of unique? If so, it is probably a better idea to implement uniqueV2, which will be able to handle unique. Otherwise, if you implement uniqueV2 later, the more specific implementation here may be thrown away, which is a waste of effort. WDYT?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007#-:-MIaatJ02unECVuVu6QP:b-70tzqe)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @lina128, @pyu10055, and @tafsiri)

**Review by pyu10055 — COMMENTED** [review]
Thank Jing! This is a great addition. I agree with Na, add support both unique and uniqueV2 would be great. You can take a look at the TF core implmentation https://source.corp.google.com/piper///depot/google3/third_party/tensorflow/core/kernels/unique_op.cc?q=uniquev2%20&sq=package:piper%20file:%2F%2Fdepot%2Fgoogle3%20-file:google3%2Fexperimental 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007#-:-MIapzM26UZZfvxmt2Mg:b-75kjlx)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Unique.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MIe14Hy3N73HQGk7OsQ:-MIe14Hy3N73HQGk7OsR:b-38lzde) ([raw file](https://github.com/tensorflow/tfjs/blob/4c0f754898b9e85189803b61b81a3b3f2134445b/tfjs-backend-webgl/src/kernels/Unique.ts#L31)):*
> ```XML
> 
>   // For now, always forward calculation to the CPU backend.
>   const values = backend.readSync(x.dataId);
> ```

Can you throw a warning in the console that this kernel is calling readSync? readSync locks the UI.

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Unique.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MIe14Hy3N73HQGk7OsQ:-MIeXJ2SAYRqEhaKSukf:b8t96f9) ([raw file](https://github.com/tensorflow/tfjs/blob/4c0f754898b9e85189803b61b81a3b3f2134445b/tfjs-backend-webgl/src/kernels/Unique.ts#L31)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Can you throw a warning in the console that this kernel is calling readSync? readSync locks the UI.
</blockquote></details>

can this function be async?

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007)* status: 0 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Unique.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MIe14Hy3N73HQGk7OsQ:-MIeaZ9L8pFuaGgFJpQ7:bwhpnlf) ([raw file](https://github.com/tensorflow/tfjs/blob/4c0f754898b9e85189803b61b81a3b3f2134445b/tfjs-backend-webgl/src/kernels/Unique.ts#L31)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can this function be async?
</blockquote></details>

We don't support async kernels yet so I don't think we can call async read here. Although it would be great to profile unique in the context of a model on the WebGL backend.

**Review by jinjingforever — COMMENTED** [review]
Thanks for comments and pointers! I updated the implementations to support UniqueV2. 

PTAL

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007#-:-MIfZ-7DB0YSCU6I-5yp:bisefzt)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Unique.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MIe14Hy3N73HQGk7OsQ:-MIfZAEUERwzWNKfNWBA:b-zf7lca) ([raw file](https://github.com/tensorflow/tfjs/blob/4c0f754898b9e85189803b61b81a3b3f2134445b/tfjs-backend-webgl/src/kernels/Unique.ts#L31)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

We don't support async kernels yet so I don't think we can call async read here. Although it would be great to profile unique in the context of a model on the WebGL backend.
</blockquote></details>

Added the warning. I will ping you guys offline about profiling. Thanks!

**Review by pyu10055 — CHANGES_REQUESTED** [review]
thanks for adding axis support.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007#-:-MItolsvBwsFiCjVlO5o:b5zmsfc)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 27 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItJlPz578Vhp0Fqf6z:-MItJlPz578Vhp0Fqf7-:b-8ocyyx) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L27)):*
> ```XML
> } {
>   // Normalize and validate axis.
>   const $axis = util.parseAxisParam(axis, shape)[0];
> ```

need to make sure axis is less than rank of the tensor, c++ also supports negative axis, which is counting from the end.
___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 39 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItkpdm0S82cL-bbkRz:-MItkpdn8MXVSCTnJgIr:bbs0yo9) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L39)):*
> ```XML
>   // For example, for a 4D tensor with shape=[2, 3, 5, 4] and axis=2, the
>   // newShape would be: [2*3, 5, 4].
>   const newShape = [1, shape[0], 1];
> ```

do we need to make sure shape is at least 1D?
___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 63 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItnCu61N7eJZR6ZR-s:-MItnCu61N7eJZR6ZR-t:b-7b84t4) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L63)):*
> ```XML
>     // Extract values along the axis.
>     let element: string;
>     if (is1DTensor) {
> ```

do you need to special handle 1D case? should the m and n both are 1?
___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 73 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItnWdh9cqrP1QWb_-6:-MItnWdh9cqrP1QWb_-7:b3buzm6) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L73)):*
> ```XML
>         }
>       }
>       element = axisValues.toString();
> ```

this depends on the implementation of array toString method, maybe better to implement your own to ensure future compatibility.
___
*[tfjs-backend-webgl/src/kernels/Unique.ts, line 35 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItICZ3CsQX1sGEVa8q:-MItICZ3CsQX1sGEVa8r:bpo8xvj) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-webgl/src/kernels/Unique.ts#L35)):*
> ```XML
>   // For now, always forward calculation to the CPU backend.
>   console.warn(
>       'WARNING: ', 'UI might be locked temparaily as data is being downloaded');
> ```

typo: temporarily
___
*[tfjs-core/src/ops/unique_test.ts, line 65 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItIP54A-Cc1jT2d6JT:-MItIP54A-Cc1jT2d6JU:b-vi5cli) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-core/src/ops/unique_test.ts#L65)):*
> ```XML
>   });
> 
>   it('2d tensor with axis=1', async () => {
> ```

can you add 3d tensor tests as well? thanks

**Review by jinjingforever — COMMENTED** [review]
Thanks for the review Ping! PTAL

(Also added some code comments in unique_impl.ts to hopefully explain the algorithm better) 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007#-:-MIun2Vk0_yZzonynyOA:bnnv865)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 27 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItJlPz578Vhp0Fqf6z:-MIu7dTF-CEvSfpurfzO:bhrsroo) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L27)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

need to make sure axis is less than rank of the tensor, c++ also supports negative axis, which is counting from the end.
</blockquote></details>

Thanks. Actually the [parseAxisParam](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/util.ts#L339) function does the checks you mentioned already:) It also handles negative axis.
___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 39 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItkpdm0S82cL-bbkRz:-MIu9DPQ6a9Rt0grsQ6l:b-aphrxx) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L39)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

do we need to make sure shape is at least 1D?
</blockquote></details>

Done. Added an assert in the op
___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 63 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItnCu61N7eJZR6ZR-s:-MIu9MSl74lmfJ1DhVmM:b9tautq) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L63)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

do you need to special handle 1D case? should the m and n both are 1?
</blockquote></details>

You are correct, but given that 1D input is probably the most common, it might help to improve its performance by directly setting the element value instead of going through creating an array and adding one element (below) 
___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 73 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItnWdh9cqrP1QWb_-6:-MIuA-kwEe8W5vSiJJ0K:b-7qmo62) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L73)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this depends on the implementation of array toString method, maybe better to implement your own to ensure future compatibility.
</blockquote></details>

Good point. Done
___
*[tfjs-backend-webgl/src/kernels/Unique.ts, line 35 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItICZ3CsQX1sGEVa8q:-MIuADy6DVQ6lC-DV5-N:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-webgl/src/kernels/Unique.ts#L35)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

typo: temporarily
</blockquote></details>

Done
___
*[tfjs-core/src/ops/unique_test.ts, line 65 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItIP54A-Cc1jT2d6JT:-MIumzyT6fUIYhQqVUf1:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-core/src/ops/unique_test.ts#L65)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you add 3d tensor tests as well? thanks
</blockquote></details>

Done.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 27 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItJlPz578Vhp0Fqf6z:-MIvnHl5-hOnl8wGT_7A:bpfwa8y) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L27)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Thanks. Actually the [parseAxisParam](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/util.ts#L339) function does the checks you mentioned already:) It also handles negative axis.
</blockquote></details>

nice, thanks!
___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 73 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItnWdh9cqrP1QWb_-6:-MIvnhN72Y4HatfIXwGB:bk51qoa) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L73)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Good point. Done
</blockquote></details>

For strings arrays ['a,b', 'c'] and ['a', 'b,c'], their value would be the same?

**Review by jinjingforever — COMMENTED** [review]
Thank you Ping! PTAL.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007#-:-MIyk5Sj4gpYSFboilUM:b-f23koe)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Unique_impl.ts, line 73 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4007#-MItnWdh9cqrP1QWb_-6:-MIyh4ZPBic-WNoCDXPb:b-iaou6k) ([raw file](https://github.com/tensorflow/tfjs/blob/bcb46bda31b080dd5c39ee3162de805e8dd4e5b9/tfjs-backend-cpu/src/kernels/Unique_impl.ts#L73)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

For strings arrays ['a,b', 'c'] and ['a', 'b,c'], their value would be the same?
</blockquote></details>

We are actually ok here because the "values" stored in inputBuffer are raw byte arrays instead of actual strings. I added a test to make sure this works.

Your comment also reminded me that the code at the end of this method (convert string back to bytes) are not necessary because outputBuffer.values are bytes too:) Removed.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 10 of 22 files at r1, 8 of 12 files at r2, 1 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4007)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

**Pull request merged**
