### PR TITLE
[webgl] Add fix for underflow / overflow in divisor.

### PR DESCRIPTION
**Pull request by annxingyuan**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3981)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
Thanks for the fix, on high level, is the assumption that for mean op the divisor is on cpu until div op is executed. By allow div op to handle overflow it can fix mean op as well?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3981#-:-MIKhHi925MI2p0s_jik:b-1pjpgt)* status: 0 of 1 approvals obtained (waiting on @annxingyuan)

___
*[tfjs-backend-webgl/src/kernels/Div.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3981#-MIKgsro7uonBwTIx94B:-MIKgsro7uonBwTIx94C:biy0i73) ([raw file](https://github.com/tensorflow/tfjs/blob/c4ebd5b502547619ff87a3b38ed806f527c529ee/tfjs-backend-webgl/src/kernels/Div.ts#L56)):*
> ```XML
> `;
> 
> function getDivStages(
> ```

can you add a description on what this method is trying to accomplish? thanks
___
*[tfjs-backend-webgl/src/kernels/Div.ts, line 63 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3981#-MIKgeMx8gE4TciUe4HY:-MIKgeMx8gE4TciUe4HZ:brzn4ah) ([raw file](https://github.com/tensorflow/tfjs/blob/c4ebd5b502547619ff87a3b38ed806f527c529ee/tfjs-backend-webgl/src/kernels/Div.ts#L63)):*
> ```XML
>     const divisorVal = backend.texData.get(divisor.dataId).values[0] as number;
>     let max = divisorVal;
>     while (!webgl_util.canBeRepresented(max)) {
> ```

is there concern about underflow?

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3981)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-backend-webgl/src/kernels/Div.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3981#-MIKgsro7uonBwTIx94B:-MIOgaVK0G1KKtoXvavD:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/719246c3f3a3a652bf0e4decf759a9b167736495/tfjs-backend-webgl/src/kernels/Div.ts#L56)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you add a description on what this method is trying to accomplish? thanks
</blockquote></details>

Done
___
*[tfjs-backend-webgl/src/kernels/Div.ts, line 63 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3981#-MIKgeMx8gE4TciUe4HY:-MIOkRFo4YTNlDQlN_vS:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/719246c3f3a3a652bf0e4decf759a9b167736495/tfjs-backend-webgl/src/kernels/Div.ts#L63)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is there concern about underflow?
</blockquote></details>

Done

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3981)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @pyu10055)

___
*[tfjs-backend-webgl/src/kernels/Div.ts, line 73 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3981#-MIPUAly9VuMy10LeAw6:-MIPUAlzD4C0jM7tqJWp:b-f48bo3) ([raw file](https://github.com/tensorflow/tfjs/blob/c368f6592e95b9af1f04e54729560e0a07eb6275/tfjs-backend-webgl/src/kernels/Div.ts#L73)):*
> ```XML
>     let max = divisorVal;
>     while (!webgl_util.canBeRepresented(max)) {
>       max = Math.sqrt(max);
> ```

should the abs value of divisorValue used here to take care of negative numbers?

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3981)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-backend-webgl/src/kernels/Div.ts, line 73 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3981#-MIPUAly9VuMy10LeAw6:-MIQJWaJ8wXFjb4brQeS:b-1aklue) ([raw file](https://github.com/tensorflow/tfjs/blob/c368f6592e95b9af1f04e54729560e0a07eb6275/tfjs-backend-webgl/src/kernels/Div.ts#L73)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should the abs value of divisorValue used here to take care of negative numbers?
</blockquote></details>

Done

thanks for the catch :)

**Comment by annxingyuan** [comment]
Hi @pyu10055 - thanks for the reviews. I've added a test of mean - LMK what you think.

**Pull request closed without merging**
