### PR TITLE
[webgpu] Bump @webgpu/types to 0.1.16

### PR DESCRIPTION
**Pull request by haoyunfeix**
Use dispatchWorkgroup() instead of dispatch()

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6388)

### CODE REVIEW

**Review by gyagp — COMMENTED** [review]
LGTM

**Comment by haoyunfeix** [comment]
@mattsoulanille @lina128 PTAL

**Review by qjia7 — APPROVED** [review]
LGTM, thanks.

**Comment by qjia7** [comment]
@lina128 @mattsoulanille Need another approve to merge this PR. Thanks.

**Review by mattsoulanille — APPROVED** [review]
LGTM

**Comment by haoyunfeix** [comment]
@mattsoulanille, the presubmit checking seems blocked by the tfjs-automl testing on Firefox 100.0(MacOS 10.13), do you have any idea to fix this or could you please merge this PR by hand?

```
Step #2 - "run-cloudbuild": Step #12 - "test-browser-tfjs-automl": ...[33m19 05 2022 01:07:06.444:WARN [Firefox 100.0 (Mac OS 10.13)]: [39mDisconnected (0 times) reconnect failed before timeout of 2000ms (ping timeout)
Step #2 - "run-cloudbuild": Step #12 - "test-browser-tfjs-automl": Firefox 100.0 (Mac OS 10.13) ERROR
Step #2 - "run-cloudbuild": Step #12 - "test-browser-tfjs-automl":   Disconnected reconnect failed before timeout of 2000ms (ping timeout)
```

**Pull request merged**
