### PR TITLE
Cosh branch

### PR DESCRIPTION
**Pull request by carrycooldude**
> I just pushed a P.R for cosh ops.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5260)

### CODE REVIEW

**Comment by carrycooldude** [comment]
cc: @shivaylamba @pyu10055 @lina128

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Thanks for the contribution! This looks good. The only changes I think are needed are to revert`package.json` and `yarn.lock`, since it seems a few unneeded changes were made to them.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5260#-:-MdOPWhO8cnxK4aeJoxt:blxtd5s)* status: 0 of 1 approvals obtained (waiting on @carrycooldude)

___
*[tfjs-backend-wasm/package.json, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5260#-MdOOvcvE5J-NYZ8yNwE:-MdOOvcvE5J-NYZ8yNwF:b-cd5ah8) ([raw file](https://github.com/tensorflow/tfjs/blob/17c5b73341ee43a86cafb6be9e58fd19a69f539c/tfjs-backend-wasm/package.json#L48)):*
> ```
>     "@bazel/typescript": "^3.6.0",
> ```
This dependency should not be necessary because we manage `@bazel` scoped dependencies using the root package.json
___
*[tfjs-backend-wasm/package.json, line 59 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5260#-MdOOfSbBsNwMod-sO53:-MdOOfSbBsNwMod-sO54:b26obiz) ([raw file](https://github.com/tensorflow/tfjs/blob/17c5b73341ee43a86cafb6be9e58fd19a69f539c/tfjs-backend-wasm/package.json#L59)):*
> ```
>     "@tensorflow/tfjs-core": "^3.7.0",
> ```

This change from `link:../tfjs-core` to `^3.7.0` is why the CI tests are failing.

**Review by mattsoulanille — APPROVED** [review]
LGTM! Thanks. I'll merge once the tests pass.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5260#-:-MdOW79262kW01szH0ZY:b-p034nt)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by carrycooldude** [comment]
Thanks @mattsoulanille for those tips

**Pull request merged**
