### PR TITLE
webgpu: Optimize AvgPool when filter size = input size

### PR DESCRIPTION
**Pull request by qjia7**
AvgPool is very poor in cityscapes architecture in DeepLabV3.
With this change, AvgPool becomes 3.07 ms from 24.77 ms on TGL.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6762)

### CODE REVIEW

**Review by Linchenn — APPROVED** [review]
Thank you Jiajia! This perf improvement looks pretty great!

I am not sure if I understand correctly: this change gains performance because WebGPU's `mean` (`reduce`) op is optimized by workgroup? If I am right, I think I could not apply this idea to WebGL because [`mean` op](https://github.com/tensorflow/tfjs/blob/0f3b0d2a7ae0a019b17cb1d8d6e50be0a900b709/tfjs-backend-webgl/src/mean_gpu.ts#L21) and [`pool` op](https://github.com/tensorflow/tfjs/blob/0f3b0d2a7ae0a019b17cb1d8d6e50be0a900b709/tfjs-backend-webgl/src/pool_gpu.ts#L130) have similar implementations. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6762#-:-N9n2-rp0cMx-fsJmAGp:b-rn9lml)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gyagp and @qjia7)

___
*[`tfjs-backend-webgpu/src/kernels/AvgPool.ts` line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6762#-N9n1eIU06lUS4d9v5GI:-N9n1eIU06lUS4d9v5GJ:b-6osq9b) ([raw file](https://github.com/tensorflow/tfjs/blob/8498c51231cd1c8edccca95a84926e53b079c014/tfjs-backend-webgpu/src/kernels/AvgPool.ts#L61)):*
> ```XML
>         transpose({inputs: {x: reshapeX}, backend, attrs: {perm: [1, 0]}});
>     const meanX = mean(
>         {inputs: {x: transposeX}, backend, attrs: {keepDims: false, axis: 1}});
> ```

Could we avoid `transpose` op here? Then we do meanX on axis 0, like:
```js
const meanX = mean(
        {inputs: {x: transposeX}, backend, attrs: {keepDims: false, axis: 0}});
```



_Code quote:_
```XML
    const transposeX =
        transpose({inputs: {x: reshapeX}, backend, attrs: {perm: [1, 0]}});
    const meanX = mean(
        {inputs: {x: transposeX}, backend, attrs: {keepDims: false, axis: 1}});
```

**Review by qjia7 — COMMENTED** [review]
That's one reason. Another reason is that using `reduce` makes the data accessing contiguous in memory.
For webgl, I remember @pyu10055 ever said that `webgl reduction op are using parallel algorithm that reduce the array in multiple shader calls.`. So maybe using `reduce` is still faster than the current `pool2d` algorithm. You can have a try. But for current AvgPool op in this model, webgpu does behave much slower than webgl. But after the optimization, it becomes better.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6762#-:-N9oUFDp62M5VZdvrtB3:b-apc67d)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gyagp and @Linchenn)

___
*[`tfjs-backend-webgpu/src/kernels/AvgPool.ts` line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6762#-N9n1eIU06lUS4d9v5GI:-N9oU2vC4_lKuEec1WKc:boyexbg) ([raw file](https://github.com/tensorflow/tfjs/blob/8498c51231cd1c8edccca95a84926e53b079c014/tfjs-backend-webgpu/src/kernels/AvgPool.ts#L61)):*
<details><summary><i>Previously, Linchenn wrote…</i></summary><blockquote>

Could we avoid `transpose` op here? Then we do meanX on axis 0, like:
```js
const meanX = mean(
        {inputs: {x: transposeX}, backend, attrs: {keepDims: false, axis: 0}});
```

</blockquote></details>

Done. Thanks.

**Review by Linchenn — APPROVED** [review]
Thank you for detailed explanation! LGTM!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6762#-:-N9r04us8iGIGBjEAw-2:b-6rdwvi)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gyagp and @Linchenn)

**Review by gyagp — APPROVED** [review]
LGTM

**Pull request merged**
