### PR TITLE
[webgpu] Fix wrongly used u32 of WGSL

### PR DESCRIPTION
**Pull request by axinging**
With this change, when the real coord < 0, 0.0 will be returned. However, without this change, when the real coord < 0, 0.0 will also be returned.  This is why existing case can not catch this error.

Below is explanation for without this change. For example:
 ```
// Before this PR, coordCol  is of type u32.
let coordCol = outCol * uniforms.stride[1] + uniforms.dilation[1] * WCol - uniforms.pad[1];
```
When the real result of right side < 0, coordCol (of type u32) will be interpreted as a very big data, this big data will fail the check done by coordsInBounds4D, so 0.0 will be returned.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5559)

### CODE REVIEW

**Comment by axinging** [comment]
@qjia7 @haoyunfeix @xhcao @gyagp , PTAL

**Review by qjia7 — APPROVED** [review]

**Comment by qjia7** [comment]
@kainino0x @lina128 take a look, thanks.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5559)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @axinging and @kainino0x)

___
*[tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts, line 312 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5559#-MiS4vbzCBeINtIW-FLL:-MiS4vbzCBeINtIW-FLM:b-fxmkz1) ([raw file](https://github.com/tensorflow/tfjs/blob/2de340479a45d45d8f3709528442880fc6cbe5a7/tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts#L312)):*
> ```
>  if (coordRow < 0) {
> ```
If coordRow < 0, is this an error? Why handle it silently?

**Comment by axinging** [comment]
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5559)_ status: :shipit: complete! 1 of 1 approvals obtained (waiting on @axinging and @kainino0x)
> 
> _[tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts, line 312 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5559#-MiS4vbzCBeINtIW-FLL:-MiS4vbzCBeINtIW-FLM:b-fxmkz1) ([raw file](https://github.com/tensorflow/tfjs/blob/2de340479a45d45d8f3709528442880fc6cbe5a7/tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts#L312)):_
> 
> > ```
> >  if (coordRow < 0) {
> > ```
> 
> If coordRow < 0, is this an error? Why handle it silently?

coordRow < 0 happens when padding is applied during computing convolution. This is intended behavior, can not report error.

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5559)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @axinging)

___
*[tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts, line 312 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5559#-MiS4vbzCBeINtIW-FLL:-MiUiFq74IEZQNelNqM6:b-3zacc5) ([raw file](https://github.com/tensorflow/tfjs/blob/2de340479a45d45d8f3709528442880fc6cbe5a7/tfjs-backend-webgpu/src/kernels/conv2d_mm_vec4_webgpu.ts#L312)):*
<details><summary><i>Previously, axinging (Xu Xing) wrote…</i></summary><blockquote>

coordRow < 0 happens when padding is applied during computing convolution. This is intended behavior, can not report error.
</blockquote></details>

Ah, right. If it's uint, then it will get a large number, which is incorrect. Got it. Thanks.

**Pull request merged**
