### PR TITLE
[webg] Fix memleak in modularized reduce.

### PR DESCRIPTION
**Pull request by annxingyuan**
This fixes https://github.com/tensorflow/tfjs/issues/3869.

The leak happens because we call reduce recursively without cleaning up intermediate outputs. This PR changes max to call reduce iteratively and cleans up intermediate outputs along the way. 

The tests I added actually fail in master because of our check in engine for leaked dataIds. We didn't happen to have a max test with a large enough dimension to trigger multiple reductions. 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3872)

### CODE REVIEW

**Comment by tafsiri** [comment]
@annxingyuan before reviewing this in detail would you be able to outline in the PR description where the mem leak is in the existing code and any thoughts on why the mem leak checker doesn't catch this?

**Comment by annxingyuan** [comment]
@tafsiri yes - I added some notes in the description - let me know if anything is unclear!

**Review by tafsiri — APPROVED** [review]
Great description and fix! Left a few suggested changes. But LGTM! Thanks for digging into this. 

> Reviewed 5 of 6 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3872#-:-MGJYxp05DunxDTrPyyh:b-s5w3ag)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernel_utils/reduce.ts, line 25 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3872#-MGJXAE-8uWAbt6UQ-hv:-MGJXAE06tTqzUudM2Lw:b-d5srfs) ([raw file](https://github.com/tensorflow/tfjs/blob/cd48f7e16c82bb8e06c2bc4d5ef03eda7f826f1f/tfjs-backend-webgl/src/kernel_utils/reduce.ts#L25)):*
> ```XML
> type ReduceTypes = 'all'|'any'|'max'|'min'|'sum'|'prod';
> 
> function getReductionSizes(inShape: number[]):
> ```

Would you be able to add a comment for this function? It would add some flavour to the notion of multiple reductions being needed to get the overall reduction done effectively.
___
*[tfjs-backend-webgl/src/kernels/Max_test.ts, line 23 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3872#-MGJYWVDB0KDDkvqvQyj:-MGJYWVECcCGVMZCXydj:b-d7zuum) ([raw file](https://github.com/tensorflow/tfjs/blob/cd48f7e16c82bb8e06c2bc4d5ef03eda7f826f1f/tfjs-backend-webgl/src/kernels/Max_test.ts#L23)):*
> ```XML
> 
> describeWithFlags('Max', ALL_ENVS, () => {
>   it('does not have memory leak.', async () => {
> ```

Could you name this something like "does not have memory leak when calling reduce multiple times" to help future us remember why this test is here in addition to the general test in core.
___
*[tfjs-core/src/ops/max_test.ts, line 36 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3872#-MGJYlS86tEGx2ukHleS:-MGJYlS91pUiklS2_Qo5:b-oe76m3) ([raw file](https://github.com/tensorflow/tfjs/blob/cd48f7e16c82bb8e06c2bc4d5ef03eda7f826f1f/tfjs-core/src/ops/max_test.ts#L36)):*
> ```XML
> 
>   it('with a large dimension', async () => {
>     const aData = new Float32Array(100);
> ```

would making this a bit bigger (say 100x100) (e.g. tf.ones([100, 100])) be better for catching problems in implementations that may have larger effective window sizes

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3872)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernel_utils/reduce.ts, line 38 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3872#-MGJkdOj6cj5KtkYPmEt:-MGJkdOj6cj5KtkYPmEu:b-jjplrq) ([raw file](https://github.com/tensorflow/tfjs/blob/0d2679b5748a2920e59124a206c2182f59387935/tfjs-backend-webgl/src/kernel_utils/reduce.ts#L38)):*
> ```XML
>   }
> 
>   return reduce(output, dtype, reductionType, backend);
> ```

Hi Ann, I wonder instead of changing to iterative approach, can we do this in recursive approach, something like:
```
const result = reduce(output, dtype, reductionType, backend);
backend.disposeData(output.dataId);
return result;
```

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3872)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @tafsiri)

___
*[tfjs-backend-webgl/src/kernel_utils/reduce.ts, line 38 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3872#-MGJkdOj6cj5KtkYPmEt:-MGJvO0TD0kN3-yHhKcB:bwr58jn) ([raw file](https://github.com/tensorflow/tfjs/blob/0d2679b5748a2920e59124a206c2182f59387935/tfjs-backend-webgl/src/kernel_utils/reduce.ts#L38)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Hi Ann, I wonder instead of changing to iterative approach, can we do this in recursive approach, something like:
```
const result = reduce(output, dtype, reductionType, backend);
backend.disposeData(output.dataId);
return result;
```
</blockquote></details>

Hi Na, I think that could result in disposing the input tensor? Also the iterative approach aligns with other kernels such as cumsum.

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3872)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @tafsiri)

___
*[tfjs-backend-webgl/src/kernel_utils/reduce.ts, line 38 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3872#-MGJkdOj6cj5KtkYPmEt:-MGK6kg95qpbPRkhfKLl:bjmln7h) ([raw file](https://github.com/tensorflow/tfjs/blob/0d2679b5748a2920e59124a206c2182f59387935/tfjs-backend-webgl/src/kernel_utils/reduce.ts#L38)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Hi Na, I think that could result in disposing the input tensor? Also the iterative approach aligns with other kernels such as cumsum. 
</blockquote></details>

Discussed offline - this approach does not dispose the input tensor, but the iterative approach aligns with other cumulation kernels in WebGL.

**Pull request merged**
