### PR TITLE
Add support for SparseFillEmptyRows conversion

### PR DESCRIPTION
**Pull request by ahmedsabie**
ref #4838

Added SparseFillEmptyRows op support for the graph model executor.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5005)

### CODE REVIEW

**Review by pyu10055 — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5005)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-converter/src/operations/executors/sparse_executor.ts, line 64 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5005#-MZPBdjXCD41NQczpkac:-MZPBdjY1JSPu99BnNqp:b-6usb0w) ([raw file](https://github.com/tensorflow/tfjs/blob/0218dcf889177175bd1888db77507433641ce23c/tfjs-converter/src/operations/executors/sparse_executor.ts#L64)):*
> ```XML
>     };
> 
> export const CATEGORY = 'sparse';
> ```

thank you for fixing this.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5005)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-converter/src/operations/executors/sparse_executor_test.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5005#-MZPCjMwCgotixPvQYLi:-MZPCjMwCgotixPvQYLj:byodmok) ([raw file](https://github.com/tensorflow/tfjs/blob/0218dcf889177175bd1888db77507433641ce23c/tfjs-converter/src/operations/executors/sparse_executor_test.ts#L32)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   const inputIndices = [tfOps.tensor2d(
>       [0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 2, 3], [5, 3], 'int32')];
>   const inputShape = [tfOps.tensor1d([2, 3, 6], 'int32')];
>   const newShape = [tfOps.tensor1d([9, -1], 'int32')];
> ```
</details>

It would be better to move these variables to the test itself.

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5005#-:-MZPIhC_1F-tntyHU7AR:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5005)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie)

**Pull request merged**
