### PR TITLE
Add kernel SparseSegmentMean for CPU and WebGL backend

### PR DESCRIPTION
**Pull request by ahmedsabie**
ref #4838
TensorFlow python version is defined  [here](https://www.tensorflow.org/api_docs/python/tf/sparse/segment_mean)
c++ kernel definition (SparseSegmentReductionMeanOp) is  [here](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/core/kernels/segment_reduction_ops_impl.h)

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5025)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5025)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5025#-MZpYC-IEl3Ee-DKmk-w:-MZpYC-JDdvM9tfBbyb1:b-5n89nc) ([raw file](https://github.com/tensorflow/tfjs/blob/3606e1ee4cb5fadea1e8bd1f537d87acdf27030e/tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts#L23)):*
> ```XML
>     input: TypedArray, inputShape: number[], inputDType: DataType,
>     indices: TypedArray, segmentIds: TypedArray, isMean = false,
>     defaultValue = 0, numSegments?: number): [TypedArray, number[]] {
> ```

numSegments is never supplied, should we remove the parameter and associated logic until it is need for other ops?
___
*[tfjs-core/src/ops/sparse/sparse_segment_mean_test.ts, line 114 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5025#-MZpXCp-9dTeBXJBormk:-MZpXCp-9dTeBXJBorml:b-r1liai) ([raw file](https://github.com/tensorflow/tfjs/blob/3606e1ee4cb5fadea1e8bd1f537d87acdf27030e/tfjs-core/src/ops/sparse/sparse_segment_mean_test.ts#L114)):*
> ```XML
>   });
> 
>   it('indices invalid 1', async () => {
> ```

rename the invalid x for indices and segment to a meaningful description.
i.e. indices < 0
indices > value dimension[0]
etc..

**Review by pyu10055 — COMMENTED** [review]
Thanks, great work!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5025#-:-MZpYMwT9FuziUNa06yj:bpqfb7f)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5025)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5025#-MZpYC-IEl3Ee-DKmk-w:-MZsmJBIE3stpaFZK70h:b-5xk92l) ([raw file](https://github.com/tensorflow/tfjs/blob/3606e1ee4cb5fadea1e8bd1f537d87acdf27030e/tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts#L23)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

numSegments is never supplied, should we remove the parameter and associated logic until it is need for other ops?
</blockquote></details>

That's a good idea since then those other ops would have the tests necessary to check that numSegments is working correctly

**Review by pyu10055 — APPROVED** [review]
> Reviewed 9 of 11 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5025)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

**Pull request merged**
