### PR TITLE
webgpu: separate struct members with commas

### PR DESCRIPTION
**Pull request by xhcao**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6279)

### CODE REVIEW

**Comment by xhcao** [comment]
@qjia7 @axinging @haoyunfeix @gyagp Please take a look, thank you.
tint had changed the separation of struct members from semicolon to commas, https://dawn-review.googlesource.com/c/tint/+/84380
Will print lots of logs as below,
warning: use of deprecated language feature: struct members should be separated with commas

**Review by gyagp — APPROVED** [review]
LGTM

**Comment by xhcao** [comment]
I do not know why this patch had changed many `import` states' location. Do anyone the cause?

**Comment by gyagp** [comment]
> I do not know why this patch had changed many `import` states' location. Do anyone the cause?

clang-format?

**Review by qjia7 — APPROVED** [review]
LGTM, thanks.

cc @lina128 @pyu10055

**Pull request merged**
