### PR TITLE
Added Photils to Demos & Applications

### PR DESCRIPTION
**Pull request by scheckmedia**
Photils uses Tensorflow.js in combination with the ResNet50 to extract features from an image. The dimension of a feature will be reduced to 64 dimensions and used for a lookup in a database.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/523)

### CODE REVIEW

**Comment by scheckmedia** [comment]
Hi, now I signed the CLA :)

**Comment by nsthorat** [comment]
Hi @scheckmedia thanks for the PR. Just tried out the link but I can't seem to get it to work. Is there an about page / explanation you could provide about what this is and how to use it?

**Comment by scheckmedia** [comment]
Hi @nsthorat, recently I've tested the app (mobile and dekstop) but for me it works. I've recored a video where you can see how the app should work. 

[Demo-Video](https://drive.google.com/file/d/1zZIIPDhwqNQyzlAoxiGvByMTGh_ajmfd/view?usp=sharing)

**Comment by scheckmedia** [comment]
We also published a little explanation for the Auto-Tagger, which uses Tensorflowjs in standard mode.
[https://github.com/scheckmedia/photos#-auto-tagger](https://github.com/scheckmedia/photos#-auto-tagger)

**Pull request closed without merging**
