### PR TITLE
Modularize the remaining unary ops in cpu backend

### PR DESCRIPTION
**Pull request by jinjingforever**
Most ops are fairly simple, taking advantage of newly created unaryKernelFunc helper function.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3946)

### CODE REVIEW

**Review by tafsiri — CHANGES_REQUESTED** [review]
Great stuff, left a couple of small comments on documentation and a larger one on supporting complex outputs from unary ops. 

> Reviewed 38 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3946#-:-MHlO8EL4MudvrPjOeI7:bxcgv8d)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Clip.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlIAhf8Po5ffSM1Jaz:-MHlIAhf8Po5ffSM1Jb-:bqw3swn) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/kernels/Clip.ts#L24)):*
> ```XML
> export const clipKernelFunc = unaryKernelFunc(ClipByValue, (x, attrs) => {
>   const clipAttrs = attrs as {} as ClipByValueAttrs;
>   return x > clipAttrs.clipValueMax ?
> ```

lets use an if statement here to avoid nesting ternaries below.
___
*[tfjs-backend-cpu/src/utils/binary_types.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlJpBe5TivWVCxjqSp:-MHlJpBe5TivWVCxjqSq:bid71z) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/binary_types.ts#L19)):*
> ```XML
> 
> import {DataType, NamedAttrMap, TypedArray} from '@tensorflow/tfjs-core';
> ```

As we add more of these I think its worth adding a comment explaining the naming convention, (i.e. ...Operation vs ...KernelImpl), looking at this diff had me wondering why there isn't a SimpleUnaryKernelImpl
___
*[tfjs-backend-cpu/src/utils/binary_types.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlRotu8LWcbdKnC184:-MHlRotu8LWcbdKnC185:brnl0wz) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/binary_types.ts#L22)):*
> ```XML
> export type SimpleUnaryOperation = (x: number, attrs?: NamedAttrMap) => number;
> export type ComplexUnaryOperation =
>     (real: number, imag: number, attrs?: NamedAttrMap) => number;
> ```

This suggests all complex unary operations will produce real numbers (as opposed to producing complex numbers) right? I think in the abs example you have in this PR that is true, but I do believe other kernels would define complex results for complex inputs. I tried the following in a python colab

```python
real_part = tf.random.uniform([3,4,5])
input_tensor = tf.complex(real=real_part, imag=tf.zeros_like(real_part))
print(input_tensor.dtype)
res = tf.sin(input_tensor)
print(res.dtype)
res
```

and got the following result 

```
<dtype: 'complex64'>
<dtype: 'complex64'>
<tf.Tensor: shape=(3, 4, 5), dtype=complex64, numpy=
array([[[0.38650748+0.j, 0.533613  +0.j, 0.62358844+0.j, 0.35709518+0.j,
         0.11534068+0.j],
  ... (results continue)
```

I think we want to leave room for supporting this kind of op as well
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlKY9J-Am6EiBBtB2X:-MHlKY9J-Am6EiBBtB2Y:b-o6xdyo) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/kernel_utils.ts#L33)):*
> ```XML
>  * @param op A `SimpleUnaryOperation` for the kernel.
>  * @param dtype Optional. If set, the result has this dtype. Otherwise, the
>  *     result has the same dtype as the first input. This is mainly used in
> ```

nit: same as the input (remove first since there is only one input)
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlOJ2FAFrEvNq64rvN:-MHlOJ2FAFrEvNq64rvO:bgqdsxo) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/kernel_utils.ts#L51)):*
> ```XML
>     if (x.dtype === 'complex64') {
>       util.assert(
>           opComplex !== undefined, () => `no complex op defined for ${name}`);
> ```

use != null to cover both null and undefined.
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlRgBH7lPUOxcTdk9L:-MHlL4MO2hKDpX5M3Mus:b146ms0) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/kernel_utils.ts#L61)):*
> ```XML
>       }
>     }
>     return cpuBackend.makeTensorInfo(x.shape, dtype || x.dtype, newValues);
> ```

If the result of the operation is supposed to be a complex tensor I don't think this will construct it in the right way (i think it would need to go through the complex kernel util), this is related to my comment above on the ComplexUnaryOperation type.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3946)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Abs.ts, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHleo9dBD6O_NQ5sktf:-MHleo9fDyCHQ5AYsvOA:brjes6d) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/kernels/Abs.ts#L23)):*
> ```XML
> 
> export const absKernelFunc = unaryKernelFunc(
>     Abs, (x) => Math.abs(x), 'float32', (real, imag) => Math.hypot(real, imag));
> ```

I suggest we don't use unaryKernelFunc for abs, because complexAbs seems not return a complex and we don't know whether this can be generalized to other unary ops.
___
*[tfjs-backend-cpu/src/kernels/Abs.ts, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlgIpYAd-XdGKMHy95:-MHlgIpZ-b714xiF8cCU:bi9m4b1) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/kernels/Abs.ts#L23)):*
> ```XML
> 
> export const absKernelFunc = unaryKernelFunc(
>     Abs, (x) => Math.abs(x), 'float32', (real, imag) => Math.hypot(real, imag));
> ```

Can we change all x to xi for the passed in function? It denotes that the operation will apply on each element of x. Otherwise, it is confusing, given x represents tensor/tensorInfo most of the time.
___
*[tfjs-backend-cpu/src/utils/binary_types.ts, line 20 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlhfy-BZhBanxO2sw2:-MHlhfy-BZhBanxO2sw3:bsuyiak) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/binary_types.ts#L20)):*
> ```XML
> import {DataType, NamedAttrMap, TypedArray} from '@tensorflow/tfjs-core';
> 
> export type SimpleUnaryOperation = (x: number, attrs?: NamedAttrMap) => number;
> ```

Should these be in a separate file? unary_types.ts
___
*[tfjs-backend-cpu/src/utils/binary_types.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlRotu8LWcbdKnC184:-MHlhXBo3BDI-8CmMvu7:b32v57) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/binary_types.ts#L22)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

This suggests all complex unary operations will produce real numbers (as opposed to producing complex numbers) right? I think in the abs example you have in this PR that is true, but I do believe other kernels would define complex results for complex inputs. I tried the following in a python colab

```python
real_part = tf.random.uniform([3,4,5])
input_tensor = tf.complex(real=real_part, imag=tf.zeros_like(real_part))
print(input_tensor.dtype)
res = tf.sin(input_tensor)
print(res.dtype)
res
```

and got the following result 

```
<dtype: 'complex64'>
<dtype: 'complex64'>
<tf.Tensor: shape=(3, 4, 5), dtype=complex64, numpy=
array([[[0.38650748+0.j, 0.533613  +0.j, 0.62358844+0.j, 0.35709518+0.j,
         0.11534068+0.j],
  ... (results continue)
```

I think we want to leave room for supporting this kind of op as well
</blockquote></details>

+1
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 45 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHldbVTEpJ8aBpx8c7U:-MHldbVTEpJ8aBpx8c7V:b11xnq1) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/kernel_utils.ts#L45)):*
> ```XML
>     const cpuBackend = backend as MathBackendCPU;
> 
>     const values = cpuBackend.readSync(x.dataId) as TypedArray;
> ```

This generates new array if type is complex64, an expensive step. I wonder whether we can refactor to just iterate through the underlying real and imag.
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHld3J6Bh90l312e4S_:-MHld3J6Bh90l312e4Sa:b-bzngod) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/kernel_utils.ts#L48)):*
> ```XML
>     const xSize = util.sizeFromShape(x.shape);
>     const newValues =
>         dtype === 'bool' ? new Uint8Array(xSize) : new Float32Array(xSize);
> ```

Can we use util.getArrayFromDType? Also what if dtype is null but x.dtype is 'bool'?
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHle-BD6b-0gU1PGww2:-MHle-BD6b-0gU1PGww3:b-6a5l) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/kernel_utils.ts#L56)):*
> ```XML
>       }
>     } else {
>       assertNotComplex(x, name);
> ```

Do we need this assertion?
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlRgBH7lPUOxcTdk9L:-MHlfW_a1gdn7K8BjYNC:b8kk8ah) ([raw file](https://github.com/tensorflow/tfjs/blob/510d2a9947679f97ce52aac8552cb87b5c5d5f0d/tfjs-backend-cpu/src/utils/kernel_utils.ts#L61)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

If the result of the operation is supposed to be a complex tensor I don't think this will construct it in the right way (i think it would need to go through the complex kernel util), this is related to my comment above on the ComplexUnaryOperation type.
</blockquote></details>

If complexAbs is the only one that deal with complex64, I suggest we don't generalize it for now. We can just leave opComplex out.

**Review by jinjingforever — COMMENTED** [review]
Thanks Yannick and Na! As suggested, I removed the logic of handling complex numbers from unaryKernelFunc. I also update Abs.ts to NOT use unaryKernelFunc, and refactored the code to operate on the underlying data directly (instead of using readSync and merge real and imag values into a single new array).

PTAL 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3946#-:-MHmmOUC0SyjFpQSiRak:b-kqem8o)* status: 0 of 1 approvals obtained (waiting on @lina128 and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Abs.ts, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHleo9dBD6O_NQ5sktf:-MHmUPRe-HQtmt6zQZef:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/kernels/Abs.ts#L23)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

I suggest we don't use unaryKernelFunc for abs, because complexAbs seems not return a complex and we don't know whether this can be generalized to other unary ops.
</blockquote></details>

Done
___
*[tfjs-backend-cpu/src/kernels/Abs.ts, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlgIpYAd-XdGKMHy95:-MHmHo939qmCyYjcpmlI:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/kernels/Abs.ts#L23)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can we change all x to xi for the passed in function? It denotes that the operation will apply on each element of x. Otherwise, it is confusing, given x represents tensor/tensorInfo most of the time.
</blockquote></details>

Done
___
*[tfjs-backend-cpu/src/kernels/Clip.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlIAhf8Po5ffSM1Jaz:-MHmIW_i9tzrbqPLUtZB:bs7wumx) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/kernels/Clip.ts#L24)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

lets use an if statement here to avoid nesting ternaries below.
</blockquote></details>

Done. 
___
*[tfjs-backend-cpu/src/utils/binary_types.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlJpBe5TivWVCxjqSp:-MHmJCWG3e8LQlkXxZIP:b-hcr1k4) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/utils/binary_types.ts#L19)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

As we add more of these I think its worth adding a comment explaining the naming convention, (i.e. ...Operation vs ...KernelImpl), looking at this diff had me wondering why there isn't a SimpleUnaryKernelImpl
</blockquote></details>

Good point! Now I moved SimpleUnaryOperation to unary_types.ts. Will add more comments when it becomes more complex.
___
*[tfjs-backend-cpu/src/utils/binary_types.ts, line 20 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlhfy-BZhBanxO2sw2:-MHmJORG-hvQr-jGzVMy:bm4qzni) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/utils/binary_types.ts#L20)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should these be in a separate file? unary_types.ts
</blockquote></details>

Good catch! Done
___
*[tfjs-backend-cpu/src/utils/binary_types.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlRotu8LWcbdKnC184:-MHmURFT9tOqMGYvOaDp:btxlt0d) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/utils/binary_types.ts#L22)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Ack. Removed the generic logic of handling complex numberfs. Will add as needed in the future
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlKY9J-Am6EiBBtB2X:-MHmK3_qCwZeA6ojFh8b:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/utils/kernel_utils.ts#L33)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

nit: same as the input (remove first since there is only one input)
</blockquote></details>

Done
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 45 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHldbVTEpJ8aBpx8c7U:-MHmUAHE0B3ZAFD0nHKK:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/utils/kernel_utils.ts#L45)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This generates new array if type is complex64, an expensive step. I wonder whether we can refactor to just iterate through the underlying real and imag.
</blockquote></details>

Done
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHld3J6Bh90l312e4S_:-MHmNoOXAo4gMhuDrH4I:b-sl2qqk) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/utils/kernel_utils.ts#L48)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can we use util.getArrayFromDType? Also what if dtype is null but x.dtype is 'bool'?
</blockquote></details>

Done. Introduced $dtype which is "dtype || x.dtype" to make types consistent. Also added a check to make sure we are not operating on strings.
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlOJ2FAFrEvNq64rvN:-MHmOy-nEyyjqogBG1ZQ:b7l5dqg) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/utils/kernel_utils.ts#L51)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

use != null to cover both null and undefined.
</blockquote></details>

Ack (this part is removed)
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHle-BD6b-0gU1PGww2:-MHmP3VEC2PApAdVQmlO:b-lutgkz) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/utils/kernel_utils.ts#L56)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Do we need this assertion?
</blockquote></details>

Ack (this part is removed. Keeping this to make sure inputs are not complex numbers)
___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHlRgBH7lPUOxcTdk9L:-MHmUDL0BpRWlm0SNhyY:b6dr004) ([raw file](https://github.com/tensorflow/tfjs/blob/b963a53f485c4561534e1eac153686a3bd5f3664/tfjs-backend-cpu/src/utils/kernel_utils.ts#L61)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

If complexAbs is the only one that deal with complex64, I suggest we don't generalize it for now. We can just leave opComplex out.
</blockquote></details>

Done. Removed the generic logic of handling complex numbers. Will add as needed in the future.

**Review by lina128 — APPROVED** [review]
Great work, this PR is very clean and really expedite the modularization effort, thank you Jing!!!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3946#-:-MHoG_uV6RgBoW1xuNU2:b-feecln)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-cpu/src/utils/kernel_utils.ts, line 39 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3946#-MHoG6FlBATzjFfzHSIl:-MHoG6Fm8mtHtOMmw1uO:bnnx2ul) ([raw file](https://github.com/tensorflow/tfjs/blob/a6056dcccc8047533c228233a25b6b598891653b/tfjs-backend-cpu/src/utils/kernel_utils.ts#L39)):*
> ```XML
>  *     inputs.
>  */
> export function unaryKernelFunc(
> ```

Let's seperate this into another file, unary_utils.ts, because this file is going to be renamed to binary_utils.ts.

**Review by tafsiri — APPROVED** [review]
:clap: 

> Reviewed 39 of 39 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3946#-:-MHqOjpEDliyj1Vt4rrc:bc0irgz)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

**Pull request merged**
