### PR TITLE
[WASM] Add Greater, GreaterEqual kernels

### PR DESCRIPTION
**Pull request by sapphi-red**
Added `Greater`, `GreaterEqual` kernels

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2543)

### CODE REVIEW

**Comment by sapphi-red** [comment]
Thank you for the review.
I changed the code.
Does my commit match your intention?

**Comment by nsthorat** [comment]
Sending some comments, first check out the CI that's failing, you can find details if you click on "details" in the checks above:

image

More details are here:
https://github.com/tensorflow/tfjs/blob/master/CONTRIBUTING.md

**Comment by nsthorat** [comment]
In this case it looks like a flaky test so I'm going to rerun this :)

**Comment by sapphi-red** [comment]
I fixed and merged changes from master branch!

**Comment by nsthorat** [comment]
@sapphi-red really great work!

**Pull request merged**
