### PR TITLE
Some numpy type usages are deprecated

### PR DESCRIPTION
**Pull request by rthadur**
Fixes https://github.com/tensorflow/tfjs/issues/6610

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6625)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6625)* status: 0 of 1 approvals obtained (waiting on @rthadur)

___
*[`tfjs-converter/python/tensorflowjs/read_weights.py` line 28 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6625#-N7HO6QK3ZIy2RlUcAB9:-N7HO6QL25CeGZJDtbKC:b-iyntph) ([raw file](https://github.com/tensorflow/tfjs/blob/c5c5d9f61af4000909aad6df5eb5462e06511dcf/tfjs-converter/python/tensorflowjs/read_weights.py#L28)):*
> ```Python
> 
> _INPUT_DTYPES = [np.float16, np.float32, np.int32, np.complex64,
>                  np.uint8, np.uint16, np.object, np.bool]
> ```

np.uint and np.uint16 is not deprecated and there is no equivalent definition in python yet.



_Code quote:_
```Python
np.uint8, np.uint16
```

**Review by pyu10055 — APPROVED** [review]

**Review by Linchenn — CHANGES_REQUESTED** [review]
Thank you Rajeshwar!

I found `np.bool` and `np.object` also appear in the following files:
```
tfjs-converter/python/tensorflowjs/quantization_test.py
tfjs-converter/python/tensorflowjs/write_weights.py
tfjs-converter/python/tensorflowjs/write_weights_test.py
```

Could you help update them as well?

**Comment by rthadur** [comment]
> write_weights.py

Done , thank you Lin.

**Review by Linchenn — APPROVED** [review]
Thank you!

**Pull request merged**
