### PR TITLE
Use LRU cache for cachedSorted and cachedRecipientCounts

### PR DESCRIPTION
**Pull request by Linchenn**
Currently, the cachedSorted and cachedRecipientCounts in tfjs-layers keep caching without any boundaries, causing memory leak for Layers model ([Issue](https://github.com/tensorflow/tfjs/issues/6019)). This PR is trying to apply LRU cache to them, to set the max number of entries to be cached.

For the implementation of LRU cache, this PR utilizes the feature `A Map object iterates its elements in insertion order`, so it's O(1)  time for `put` and `get` methods.

References:
*  https://stackoverflow.com/questions/996505/lru-cache-implementation-in-javascript/46432113#46432113 
*  https://medium.com/sparkles-blog/a-simple-lru-cache-in-typescript-cba0d9807c40

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6303)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Great work, thank you Lin. Overall looks good, just a couple comments below.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6303#-:-N-3dWUb0qnoHBVENq8K:b-g2clvn)* status: 0 of 1 approvals obtained (waiting on @Linchenn)

___
*[tfjs-core/src/flags.ts, line 84 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-3b64E9a9XjUJ_FESi:-N-3b64E9a9XjUJ_FESj:bfcjwua) ([raw file](https://github.com/tensorflow/tfjs/blob/2377aa033986c6101dc79001365ee2ec4de8941a/tfjs-core/src/flags.ts#L84)):*
> ```XML
> 
> /** The max number of entries for the LRU cache. */
> ENV.registerFlag('LRU_CACHE_MAX_ENTRIES', () => 100);
> ```

you should define this flag in tfjs-layers package.
the name might need to be more meaningful, i.e.
TOPOLOGICAL_SORT_CACHE_MAX_ENTRIES
___
*[tfjs-layers/src/engine/executor.ts, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-3bcXe2U28n6PKpIbc:-N-3bcXe2U28n6PKpIbd:b-sa80mt) ([raw file](https://github.com/tensorflow/tfjs/blob/2377aa033986c6101dc79001365ee2ec4de8941a/tfjs-layers/src/engine/executor.ts#L185)):*
> ```XML
> }
> 
> export class LruCache<T> {
> ```

it would be good to move this class into a different file.
___
*[tfjs-layers/src/engine/executor.ts, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-3d9wq9IcujUwcDC6n:-N-3d9wr-o3WiSNL9MrI:b-tgpx6s) ([raw file](https://github.com/tensorflow/tfjs/blob/2377aa033986c6101dc79001365ee2ec4de8941a/tfjs-layers/src/engine/executor.ts#L291)):*
> ```XML
> 
>   // Check cache.
>   const fetchAndFeedKey =
> ```

The other question is, whether the order of the outputTensors and feedDict entries matters?
If not, we might want to sort the names before formulate the key, to avoid duplicated entries in the cache for the same input/output pairs.

**Review by Linchenn — COMMENTED** [review]
Thank you Ping!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6303#-:-N-AOFcj1mi_j6xyUx_g:b-t1trzh)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-core/src/flags.ts, line 84 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-3b64E9a9XjUJ_FESi:-N-AO6wZ9UFNpB9KqfJD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/2377aa033986c6101dc79001365ee2ec4de8941a/tfjs-core/src/flags.ts#L84)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you should define this flag in tfjs-layers package.
the name might need to be more meaningful, i.e.
TOPOLOGICAL_SORT_CACHE_MAX_ENTRIES
</blockquote></details>

Done.
___
*[tfjs-layers/src/engine/executor.ts, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-3bcXe2U28n6PKpIbc:-N-AOEJW6Z1q1Dl575pb:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/2377aa033986c6101dc79001365ee2ec4de8941a/tfjs-layers/src/engine/executor.ts#L185)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

it would be good to move this class into a different file.
</blockquote></details>

Done.
___
*[tfjs-layers/src/engine/executor.ts, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-3d9wq9IcujUwcDC6n:-N-AO9nI976JZG-fsXq3:b-qm5jff) ([raw file](https://github.com/tensorflow/tfjs/blob/2377aa033986c6101dc79001365ee2ec4de8941a/tfjs-layers/src/engine/executor.ts#L291)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

The other question is, whether the order of the outputTensors and feedDict entries matters?
If not, we might want to sort the names before formulate the key, to avoid duplicated entries in the cache for the same input/output pairs.
</blockquote></details>

Created a new issue for this, https://github.com/tensorflow/tfjs/issues/6312.

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6303)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-layers/src/utils/executor_utils.ts, line 24 at r3](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-OOktM-WJ28M6DyJYQ:-N-Owdzt8sSflz9xavKl:bjv4cv4) ([raw file](https://github.com/tensorflow/tfjs/blob/21d0d6b5a7dd952f45c013f35d887add1238d5c0/tfjs-layers/src/utils/executor_utils.ts#L24)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

If users update this flag in the runtime, it would not have impact on the the size of the cache.
Is it possible to update the maxEntries value when the flag is updated?
</blockquote></details>

Used the flag's setHook to update the `maxEntries`. 

FYI, currently, `cachedRecipientCounts` uses the default value (100)  to initialize `maxEntries`, instead of using the flag; otherwise there would be a circular dependence (registerFlag needs to refer to `cachedRecipientCounts` instance to set the hook, while `cachedRecipientCounts` needs the registerFlag to initialize `maxEntries`).

Thank you Ping for finding this out!

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6303)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

*[a discussion](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-PKBD575Gixho1SzH3:-N-PKBD575Gixho1SzH4:b-jy48l7) (no related file):*
@pyu10055 Added `updateCacheMaxEntries` as the hook function to update the two caches.

---

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6303)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn)

___
*[python_packages.bzl, line 54 at r6](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-Yrht24H4sRdcR5ea4:-N-Yrht24H4sRdcR5ea5:bfk0zac) ([raw file](https://github.com/tensorflow/tfjs/blob/5769ed99e3723d9e0eaa81c6d8dcbe28e8b4a4b4/python_packages.bzl#L54)):*
> ```Starlark
> 
> PYTHON_PACKAGES = dict({
>     "darwin_amd64": struct(
> ```

revert this change?

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6303)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[python_packages.bzl, line 54 at r6](https://reviewable.io/reviews/tensorflow/tfjs/6303#-N-Yrht24H4sRdcR5ea4:-N-YuZe35F6qtxGl6Kq2:bf4bzi7) ([raw file](https://github.com/tensorflow/tfjs/blob/5769ed99e3723d9e0eaa81c6d8dcbe28e8b4a4b4/python_packages.bzl#L54)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

revert this change?
</blockquote></details>

Done. Thank you Ping!

**Pull request merged**
