### PR TITLE
Update WASM README about setting up cross-origin isolation

### PR DESCRIPTION
**Pull request by jinjingforever**
After this PR is merged, I will add the similar paragraph to the tflite web related READMEs. Thanks!

Also, to make our demos on google storage to work with this, we will need to set up a load balancer where custom headers
can be added (see more [here](https://cloud.google.com/load-balancing/docs/custom-headers#response-options-storage)). The object metadata I mentioned the other day doesn't support arbitrary HTTP headers.

(related to #5137)

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5169)

### CODE REVIEW

**Comment by gyagp** [comment]
One question: We have an internal web server to host e2e benchmark for daily test. Do we need to change e2e/benchmarks/local-benchmark/index.html (adding crossorigin) as below to make it work? 

  <script src="https://unpkg.com/@tensorflow/tfjs-core@latest/dist/tf-core.js" crossorigin></script>
  <script src="https://unpkg.com/@tensorflow/tfjs-backend-cpu@latest/dist/tf-backend-cpu.js" crossorigin></script>
  <script src="https://unpkg.com/@tensorflow/tfjs-backend-webgl@latest/dist/tf-backend-webgl.js" crossorigin></script>
  <script src="https://unpkg.com/@tensorflow/tfjs-layers@latest/dist/tf-layers.js" crossorigin></script>
  <script src="https://unpkg.com/@tensorflow/tfjs-converter@latest/dist/tf-converter.js" crossorigin></script>
  <script src="https://unpkg.com/@tensorflow/tfjs-backend-wasm@latest/dist/tf-backend-wasm.js" crossorigin></script>
  <script src="https://unpkg.com/@tensorflow/tfjs-automl@latest/dist/tf-automl.js" crossorigin></script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/universal-sentence-encoder" crossorigin></script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/speech-commands" crossorigin> </script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/posenet@2" crossorigin></script>
  <script src="https://cdn.jsdelivr.net/npm/@tensorflow-models/body-pix@2" crossorigin></script>

**Comment by jinjingforever** [comment]
Hi Yang,

I think you are correct. Since both unpkg and jsdelivr send the CORS header, the "crossorigin" need to be added to the script tag so they are being loaded in cors mode. I will clarify this in the README. Thanks!

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5169)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[tfjs-backend-wasm/README.md, line 66 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5169#-Mbb7vOJA9bpsvTLOxVs:-Mbb7vOJA9bpsvTLOxVt:b-x9hq73) ([raw file](https://github.com/tensorflow/tfjs/blob/ef17f0bcf3938831bb27748eb46c328d990d240d/tfjs-backend-wasm/README.md#L66)):*
> ```Markdown
>    you are good to go. No more steps are needed.
> 
> 1. If you are loading the WASM backend from your own or other third-party
> ```

Does it mean if you are using jsdelivr nothing you need to do? If so should this bullet be a note before all the steps?
___
*[tfjs-backend-wasm/README.md, line 75 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5169#-Mbb8KSH6PrnfnqejsVt:-Mbb8KSH6PrnfnqejsVu:b-jf3fs3) ([raw file](https://github.com/tensorflow/tfjs/blob/ef17f0bcf3938831bb27748eb46c328d990d240d/tfjs-backend-wasm/README.md#L75)):*
> ```Markdown
>    - CORP header:
> 
>      - If the resource is loaded from the *same origin* as your main site,
> ```

might be good to provide an example for each.

**Review by jinjingforever — COMMENTED** [review]
Thanks! Please also take a look at https://github.com/tensorflow/tfjs-models/pull/747 when you get a chance. Thank you!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5169#-:-MbbrNjt5_SFbVQWjxd6:bbs1e0z)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-backend-wasm/README.md, line 66 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5169#-Mbb7vOJA9bpsvTLOxVs:-MbbpmPACRynUPVMYk0U:b-ti74bg) ([raw file](https://github.com/tensorflow/tfjs/blob/ef17f0bcf3938831bb27748eb46c328d990d240d/tfjs-backend-wasm/README.md#L66)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Does it mean if you are using jsdelivr nothing you need to do? If so should this bullet be a note before all the steps?
</blockquote></details>

Good point! I combined this with the jsdelivr paragraph into a single step to make things more clear.
___
*[tfjs-backend-wasm/README.md, line 75 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5169#-Mbb8KSH6PrnfnqejsVt:-MbbrMrLCTD_EwRUou5i:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/ef17f0bcf3938831bb27748eb46c328d990d240d/tfjs-backend-wasm/README.md#L75)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

might be good to provide an example for each.
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
Thanks, very nice instructions.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5169#-:-MbckRWn6z8iZl5hw_WY:b-7jfjwy)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Pull request merged**
