### PR TITLE
[webgl] Modularize MaxPool, MaxPoolBackprop, AvgPool, AvgPoolBackprop webgl kernels

### PR DESCRIPTION
**Pull request by jinjingforever**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3984)

### CODE REVIEW

**Review by tafsiri — APPROVED** [review]
Lookin good. Just a couple of fixes to match the input validation strategy in cpu.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3984#-:-MIQhWXJ5ESEK451vBqJ:b7s2ort)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/AvgPool.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MIQgEpZ5cVek8XQNw-t:-MIQgEpZ5cVek8XQNw-u:b-xseq1v) ([raw file](https://github.com/tensorflow/tfjs/blob/2ad8b0188ddacb7d9eb86f40f7d2a37e6a2fbf3c/tfjs-backend-webgl/src/kernels/AvgPool.ts#L34)):*
> ```XML
>   const dilations = 1;
> 
>   util.assert(
> ```

This looks like it might just belong in the op since the attrs it asserts are untransformed.
___
*[tfjs-backend-webgl/src/kernels/MaxPool.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MIQgcSH7U7M77BiDd8r:-MIQgcSH7U7M77BiDd8s:bnj7hl0) ([raw file](https://github.com/tensorflow/tfjs/blob/2ad8b0188ddacb7d9eb86f40f7d2a37e6a2fbf3c/tfjs-backend-webgl/src/kernels/MaxPool.ts#L34)):*
> ```XML
>   const dilations = 1;
> 
>   util.assert(
> ```

same as above

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3984)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, and @lina128)

___
*[tfjs-backend-webgl/src/kernels/AvgPool.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MIQgEpZ5cVek8XQNw-t:-MIQneS59auD9-I4daM7:b-mpy6u7) ([raw file](https://github.com/tensorflow/tfjs/blob/2ad8b0188ddacb7d9eb86f40f7d2a37e6a2fbf3c/tfjs-backend-webgl/src/kernels/AvgPool.ts#L34)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

This looks like it might just belong in the op since the attrs it asserts are untransformed.
</blockquote></details>

Thank you Yannick! 

I asked @lina128 offline about this particular assert in my previous PR and we decided to leave it here because "dilations" (which is not coming from attrs) is technically mutated. I can imagine that the assert might be useful if for example somebody changed dilations to some other number here. Any thoughts/preferences on this?

Thanks!

**Review by tafsiri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3984)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan and @lina128)

___
*[tfjs-backend-webgl/src/kernels/AvgPool.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MIQgEpZ5cVek8XQNw-t:-MIRQjWY0aJj9tdggXrv:b-y75dvw) ([raw file](https://github.com/tensorflow/tfjs/blob/2ad8b0188ddacb7d9eb86f40f7d2a37e6a2fbf3c/tfjs-backend-webgl/src/kernels/AvgPool.ts#L34)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Thank you Yannick! 

I asked @lina128 offline about this particular assert in my previous PR and we decided to leave it here because "dilations" (which is not coming from attrs) is technically mutated. I can imagine that the assert might be useful if for example somebody changed dilations to some other number here. Any thoughts/preferences on this?

Thanks!
</blockquote></details>

Ah okay i see what you mean. No strong pref on my end so feel free to leave it in for documentation/robustness to future change purposes (though an alternative would be to assert dilation is 1 and have a comment for the rest). If we ever do a systematic exploration (or see them show up in profiles) of the cost of assertions and find them expensive we can revisit it.

**Review by annxingyuan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3984)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, and @lina128)

___
*[tfjs-backend-webgl/src/kernels/AvgPool.ts, line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MITvVoKAgSj8ktHYBMs:-MITvVoKAgSj8ktHYBMt:b-upbj1a) ([raw file](https://github.com/tensorflow/tfjs/blob/9fc4ec2cb6d4b2173374096d3ac8b43063c11523/tfjs-backend-webgl/src/kernels/AvgPool.ts#L38)):*
> ```XML
>       () => 'Error in avgPool: Either strides or dilations must be 1. ' +
>           `Got strides ${strides} and dilations '${dilations}'`);
> ```

IIUC, the avgPool op includes an optimization in the forwardFunc of cloning the input in the case of a 1x1 convolution. Should we try to include that in this kernel, or add a TODO item to include it? Same for them axPool kernel below.
___
*[tfjs-backend-webgl/src/kernels/AvgPool.ts, line 40 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MITv3iS5ppJix1K2a9M:-MITv3iS5ppJix1K2a9N:b-utlx97) ([raw file](https://github.com/tensorflow/tfjs/blob/9fc4ec2cb6d4b2173374096d3ac8b43063c11523/tfjs-backend-webgl/src/kernels/AvgPool.ts#L40)):*
> ```XML
> 
>   const convInfo = backend_util.computePool2DInfo(
>       x.shape as [number, number, number, number], filterSize, strides,
> ```

I noticed that the avgPool op reshapes inputs to be 4D, and then shapes them back at the end of the op - should this be handled by the kernels instead? Same for the maxPool kernel below. 

Sorry if this was already discussed in the avgPool CPU PR!
___
*[tfjs-backend-webgl/src/kernels/MaxPool.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MITutzD3_3N0oBz3pb4:-MITutzD3_3N0oBz3pb5:b1z1da) ([raw file](https://github.com/tensorflow/tfjs/blob/9fc4ec2cb6d4b2173374096d3ac8b43063c11523/tfjs-backend-webgl/src/kernels/MaxPool.ts#L42)):*
> ```XML
>       x.shape as [number, number, number, number], filterSize, strides,
>       dilations, pad, dimRoundingMode);
>   const program = new Pool2DProgram(convInfo, 'max', false);
> ```

name this variable

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3984)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan and @lina128)

___
*[tfjs-backend-webgl/src/kernels/AvgPool.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MIQgEpZ5cVek8XQNw-t:-MIUrRGS7UtBQfwMAUTD:bnfsj7n) ([raw file](https://github.com/tensorflow/tfjs/blob/9fc4ec2cb6d4b2173374096d3ac8b43063c11523/tfjs-backend-webgl/src/kernels/AvgPool.ts#L34)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Ah okay i see what you mean. No strong pref on my end so feel free to leave it in for documentation/robustness to future change purposes (though an alternative would be to assert dilation is 1 and have a comment for the rest). If we ever do a systematic exploration (or see them show up in profiles) of the cost of assertions and find them expensive we can revisit it.
</blockquote></details>

SG. Thank you!
___
*[tfjs-backend-webgl/src/kernels/AvgPool.ts, line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MITvVoKAgSj8ktHYBMs:-MIUrSmK0k4VAQj9hRAZ:b-djcuki) ([raw file](https://github.com/tensorflow/tfjs/blob/9fc4ec2cb6d4b2173374096d3ac8b43063c11523/tfjs-backend-webgl/src/kernels/AvgPool.ts#L38)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

IIUC, the avgPool op includes an optimization in the forwardFunc of cloning the input in the case of a 1x1 convolution. Should we try to include that in this kernel, or add a TODO item to include it? Same for them axPool kernel below.
</blockquote></details>

Good catch! I included that in CPU backend but forgot here.. 

I added an Identity kernel (very similar to CPU) and used it here.
___
*[tfjs-backend-webgl/src/kernels/AvgPool.ts, line 40 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MITv3iS5ppJix1K2a9M:-MIUrtWO16UiENMv0nCD:bekgypm) ([raw file](https://github.com/tensorflow/tfjs/blob/9fc4ec2cb6d4b2173374096d3ac8b43063c11523/tfjs-backend-webgl/src/kernels/AvgPool.ts#L40)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

I noticed that the avgPool op reshapes inputs to be 4D, and then shapes them back at the end of the op - should this be handled by the kernels instead? Same for the maxPool kernel below. 

Sorry if this was already discussed in the avgPool CPU PR!
</blockquote></details>

Thanks! I had some discussion with @lina128 (please correct me if I am wrong). Looks like the [official TF document](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool2d) says that it expects a 4D tensor as the input. To match that, our kernel should in theory expect a 4D tensor as well, which means it is probably better to put the 3D->4D transformation outside kernel.  
___
*[tfjs-backend-webgl/src/kernels/MaxPool.ts, line 42 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3984#-MITutzD3_3N0oBz3pb4:-MIUrsIDCieQeBTUAwd-:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/9fc4ec2cb6d4b2173374096d3ac8b43063c11523/tfjs-backend-webgl/src/kernels/MaxPool.ts#L42)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

name this variable
</blockquote></details>

Done

**Pull request merged**
