### PR TITLE
[tflite] Download TFLite wasm files using http_archive

### PR DESCRIPTION
**Pull request by mattsoulanille**
Download `tfjs-tflite` wasm files using an `http_archive` instead of a genrule bash script.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5915)

### CODE REVIEW

**Review by jinjingforever — COMMENTED** [review]
Very nice! Thanks Matt! 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5915#-:-MpwMY0S3sxb3EfJ3Jjg:b-b7r9cn)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-tflite/scripts/tflite_repositories.bzl, line 7 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5915#-MpwMp2g8K4WOzxpX6-d:-MpwMp2g8K4WOzxpX6-e:bxlszjx) ([raw file](https://github.com/tensorflow/tfjs/blob/d4749b58c12f3df3f458f5cefdb4837c6e79788a/tfjs-tflite/scripts/tflite_repositories.bzl#L7)):*
> ```
> 0.0.5
> ```

nit: is it possible to change this version number to a parameter to tflite_repositories rule?

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5915)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-tflite/scripts/tflite_repositories.bzl, line 7 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5915#-MpwMp2g8K4WOzxpX6-d:-MpwQ-F89DraIuQGhZYd:bv49brw) ([raw file](https://github.com/tensorflow/tfjs/blob/d4749b58c12f3df3f458f5cefdb4837c6e79788a/tfjs-tflite/scripts/tflite_repositories.bzl#L7)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

> ```
> 0.0.5
> ```

nit: is it possible to change this version number to a parameter to tflite_repositories rule?  
</blockquote></details>

FYI, I just submitted a [PR](https://github.com/tensorflow/tfjs/pull/5911) that bumped this to 0.0.6.

**Review by mattsoulanille — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5915#-:-MpxktD6BLygwWr_zVUy:b-9qdoz3)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[tfjs-tflite/scripts/tflite_repositories.bzl, line 7 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5915#-MpwMp2g8K4WOzxpX6-d:-MpxkvCE5cJKF0CWXHLG:b-s8pmfs) ([raw file](https://github.com/tensorflow/tfjs/blob/d4749b58c12f3df3f458f5cefdb4837c6e79788a/tfjs-tflite/scripts/tflite_repositories.bzl#L7)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

FYI, I just submitted a [PR](https://github.com/tensorflow/tfjs/pull/5911) that bumped this to 0.0.6. 
</blockquote></details>

I added this as a parameter to the function. It can be configured by changing the default value here or by passing in a value in the WORKSPACE file. Is that enough configuration, or does the script ever need to be called with different versions for different types of builds? That's more difficult to do with Bazel.

**Review by jinjingforever — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5915)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-tflite/scripts/tflite_repositories.bzl, line 7 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5915#-MpwMp2g8K4WOzxpX6-d:-MpxmyIZ9ue-D5CaZsye:b3dqn9y) ([raw file](https://github.com/tensorflow/tfjs/blob/d4749b58c12f3df3f458f5cefdb4837c6e79788a/tfjs-tflite/scripts/tflite_repositories.bzl#L7)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

I added this as a parameter to the function. It can be configured by changing the default value here or by passing in a value in the WORKSPACE file. Is that enough configuration, or does the script ever need to be called with different versions for different types of builds? That's more difficult to do with Bazel.
</blockquote></details>

Yes this should be good enough! thank you!

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5915)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever)

___
*[tfjs-tflite/scripts/tflite_repositories.bzl, line 7 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5915#-MpwMp2g8K4WOzxpX6-d:-MqFvYwE1CXUPUKH3FP_:b1tyitx) ([raw file](https://github.com/tensorflow/tfjs/blob/d4749b58c12f3df3f458f5cefdb4837c6e79788a/tfjs-tflite/scripts/tflite_repositories.bzl#L7)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Yes this should be good enough! thank you!
</blockquote></details>

I forgot to include the SHAs for the different versions. This should be fixed now. I also have a few other fixes that I'll send in a different PR, but for now, I'll merge this once it's green. Thanks again!

**Comment by mattsoulanille** [comment]
Do not merge this yet. It breaks the demo.

**Comment by mattsoulanille** [comment]
Fixed by #7124

**Pull request closed without merging**
