### PR TITLE
Use node's util.types.isUint8Array etc for isTypedArray

### LINKED ISSUE #7175: tfjs raises an error in Jest(unit testing) environment and Node.js runtime
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

👍 

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js): I used `@tensorflow-models/coco-ssd` package to experiment with object detection
- OS Platform and Distribution: WSL with Ubuntu 22.04
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 
  ```
    "Node.js": "v18.12.1",
    "@tensorflow-models/coco-ssd": "2.2.2",
    "@tensorflow/tfjs-node": "4.1.0"
    "typescript": "4.8.4"
    "@types/jest": "^29.2.4",
    "@types/node": "18.11.13",
    "jest": "^29.3.1",
  ```
- Browser version: N/A
- Tensorflow.js Converter Version: I don't know

**Describe the current behavior**

tensorflow js internals throw the following error when it used within jest test case.

```
tensor2d() requires values to be number[][] or flat/TypedArray
```

**Describe the expected behavior**

Tests should pass.

The code works, it only fails in Jest.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

### `index.ts`

```typescript
import type { Buffer } from "node:buffer";
import { node as tfNode } from "@tensorflow/tfjs-node";
import { load as loadCocoSsd } from "@tensorflow-models/coco-ssd";

export async function detectObjects(imgBuf: Buffer) {
  const model = await loadCocoSsd();

  const img = new Uint8Array(imgBuf.buffer);
  const imgTensor = tfNode.decodeImage(img);
  const objects = await model.detect(imgTensor);
  return objects;
}
```

### `index.spec.ts`

```typescript
import { describe, it, expect } from "@jest/globals";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { detectObjects } from ".";

describe("test index module", () => {
  it("should pass object detection test", async () => {
    const peopleImgFilePath = path.join(
      __dirname,
      "assets",
      "brooke-cagle-g1Kr4Ozfoac-unsplash.jpg"
    );
    const imgBuf = await readFile(peopleImgFilePath);

    const detectedObjects = await detectObjects(imgBuf);
    expect(detectedObjects).toEqual([]);
  });
});
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

### Traceback

```
tensor2d() requires values to be number[][] or flat/TypedArray

      at Object.tensor2d (../../tfjs-core/src/ops/tensor2d.ts:57:11)
      at ../../node_modules/@tensorflow-models/coco-ssd/dist/coco-ssd.node.js:618:45
      at ../../node_modules/@tensorflow/tfjs/tfjs-core/src/engine.ts:469:20
      at Engine.Object.<anonymous>.Engine.scopedRun (../../node_modules/@tensorflow/tfjs/tfjs-core/src/engine.ts:480:19)
      at Engine.Object.<anonymous>.Engine.tidy (../../node_modules/@tensorflow/tfjs/tfjs-core/src/engine.ts:467:17)
      at Object.tidy (../../tfjs-core/src/globals.ts:192:17)
      at ObjectDetection.<anonymous> (../../node_modules/@tensorflow-models/coco-ssd/dist/coco-ssd.node.js:617:42)
      at step (../../node_modules/@tensorflow-models/coco-ssd/dist/coco-ssd.node.js:71:23)
      at Object.next (../../node_modules/@tensorflow-models/coco-ssd/dist/coco-ssd.node.js:52:53)
      at fulfilled (../../node_modules/@tensorflow-models/coco-ssd/dist/coco-ssd.node.js:42:58)
```

Potentially relates to #545

### PR DESCRIPTION
**Pull request by mattsoulanille**
isTypedArray is implemented with `instanceof`, which does not work in jest (https://github.com/facebook/jest/issues/11864). Instead, use node's builtin `util.types.isUint8Array`, `util.types.isFloat32Array`, etc to perform this check.

Fixes #7175.
This may also address #7064, but it does not fix the root cause.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7181)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7181)* status: 0 of 1 approvals obtained (waiting on @Linchenn and @mattsoulanille)

___
*[`tfjs-core/src/util.ts` line 135 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7181#-NJMI-AL860EjMXH8O8a:-NJMI-AL860EjMXH8O8b:b-a5093d) ([raw file](https://github.com/tensorflow/tfjs/blob/6e687545b56b69ec3c7e5af1b8c78fa052f7f92d/tfjs-core/src/util.ts#L135)):*
> ```XML
> }
> 
> export function isTypedArray(a: {}): a is Float32Array|Int32Array|Uint8Array|
> ```

please add a test to ensure it fixes the problem for different platforms. thanks

**Review by Linchenn — APPROVED** [review]
LGTM

**Review by mattsoulanille — COMMENTED** [review]
Thanks for the review!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7181#-:-NJMtKtwC45qn5VizVhM:b-9qdoz3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfjs-core/src/util.ts` line 135 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7181#-NJMI-AL860EjMXH8O8a:-NJMtG5R7mF6kzKti5zU:b-q952bo) ([raw file](https://github.com/tensorflow/tfjs/blob/6e687545b56b69ec3c7e5af1b8c78fa052f7f92d/tfjs-core/src/util.ts#L135)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

please add a test to ensure it fixes the problem for different platforms. thanks
</blockquote></details>

Tests added

**Review by pyu10055 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7181)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
