### PR TITLE
Support input size for e2e

### PR DESCRIPTION
**Pull request by axinging**
Currently this only works on posenet.
Also add blazeface model.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4576)

Step 0, default: 
step0-default

Step 1, blazeface: 
step1-blaze-inputsize

Step 2, posenet: 
step2-posenet-inputsize

Step 3, default again:
step3-default-mobilenet

### CODE REVIEW

**Comment by axinging** [comment]
PTAL, @pyu10055 @lina128

@qjia7 @haoyunfeix @xhcao

**Review by lina128 — COMMENTED** [review]
Hi @axinging , this looks great! Can you attach a screenshot of the UI in the PR description? Thank you.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4576#-:-MRVzJO8-qdL6eWFHUCG:bokt6ok)* status: 0 of 1 approvals obtained (waiting on @axinging and @pyu10055)

___
*[e2e/benchmarks/local-benchmark/index.html, line 614 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4576#-MRVyeKG65h7rLaaFF4H:-MRVyeKG65h7rLaaFF4I:bxu4pd6) ([raw file](https://github.com/tensorflow/tfjs/blob/520f71881c27e6dc593529d0081f1cf355c8002d/e2e/benchmarks/local-benchmark/index.html#L614)):*
> ```HTML
>       modelParameterFolder = gui.addFolder('Model Parameters');
>       const benchmark = benchmarks[state.benchmark];
>       if (typeof benchmark['supportedInput'] !== 'undefined') {
> ```

Why not `if(benchmark['supportedInput'] != null`, this will handle both null and undefined.

**Comment by axinging** [comment]
> Hi @axinging , this looks great! Can you attach a screenshot of the UI in the PR description? Thank you.
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4576#-:-MRVzJO8-qdL6eWFHUCG:bokt6ok)_ status: 0 of 1 approvals obtained (waiting on @axinging and @pyu10055)
> 
> _[e2e/benchmarks/local-benchmark/index.html, line 614 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4576#-MRVyeKG65h7rLaaFF4H:-MRVyeKG65h7rLaaFF4I:bxu4pd6) ([raw file](https://github.com/tensorflow/tfjs/blob/520f71881c27e6dc593529d0081f1cf355c8002d/e2e/benchmarks/local-benchmark/index.html#L614)):_
> 
> > ```
> >       modelParameterFolder = gui.addFolder('Model Parameters');
> >       const benchmark = benchmarks[state.benchmark];
> >       if (typeof benchmark['supportedInput'] !== 'undefined') {
> > ```
> 
> Why not `if(benchmark['supportedInput'] != null`, this will handle both null and undefined.




> Hi @axinging , this looks great! Can you attach a screenshot of the UI in the PR description? Thank you.
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4576#-:-MRVzJO8-qdL6eWFHUCG:bokt6ok)_ status: 0 of 1 approvals obtained (waiting on @axinging and @pyu10055)
> 
> _[e2e/benchmarks/local-benchmark/index.html, line 614 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4576#-MRVyeKG65h7rLaaFF4H:-MRVyeKG65h7rLaaFF4I:bxu4pd6) ([raw file](https://github.com/tensorflow/tfjs/blob/520f71881c27e6dc593529d0081f1cf355c8002d/e2e/benchmarks/local-benchmark/index.html#L614)):_
> 
> > ```
> >       modelParameterFolder = gui.addFolder('Model Parameters');
> >       const benchmark = benchmarks[state.benchmark];
> >       if (typeof benchmark['supportedInput'] !== 'undefined') {
> > ```
> 
> Why not `if(benchmark['supportedInput'] != null`, this will handle both null and undefined.

Thanks @lina128. updated, also add 4 screenshots. PTAL

BTW, I also move this logic into isInputSizeSupported, so the change is here:
https://github.com/tensorflow/tfjs/pull/4576/commits/0ab81f70b3034844c013d96a992c13307b7949c7#diff-622e3e249bd7bb5327a80ac8034614cdec1761a725466edce4dd57439d734fb8L549

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4576)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @axinging, @lina128, and @pyu10055)

___
*[e2e/benchmarks/local-benchmark/index.html, line 549 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4576#-MRXZLR2CgsRdEqOMuqI:-MRXZLR2CgsRdEqOMuqJ:bz5q8f6) ([raw file](https://github.com/tensorflow/tfjs/blob/ba0ee701c43c7195aa43791607e1f48fe3427d26/e2e/benchmarks/local-benchmark/index.html#L549)):*
> ```HTML
>     function isInputSizeSupported() {
>       const benchmark = benchmarks[state.benchmark];
>       if (typeof benchmark['supportedInput'] != 'undefined') {
> ```

You don't need typeof. You can just write it like this: `if(benchmark['supportedInput'] != null) { return true; }` This will cover both null and undefined.

**Comment by axinging** [comment]
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4576)_ status: :shipit: complete! 1 of 1 approvals obtained (waiting on @axinging, @lina128, and @pyu10055)
> 
> _[e2e/benchmarks/local-benchmark/index.html, line 549 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4576#-MRXZLR2CgsRdEqOMuqI:-MRXZLR2CgsRdEqOMuqJ:bz5q8f6) ([raw file](https://github.com/tensorflow/tfjs/blob/ba0ee701c43c7195aa43791607e1f48fe3427d26/e2e/benchmarks/local-benchmark/index.html#L549)):_
> 
> > ```
> >     function isInputSizeSupported() {
> >       const benchmark = benchmarks[state.benchmark];
> >       if (typeof benchmark['supportedInput'] != 'undefined') {
> > ```
> 
> You don't need typeof. You can just write it like this: `if(benchmark['supportedInput'] != null) { return true; }` This will cover both null and undefined.

Haha, Thanks @lina, it 's interesting that when I comment out typeof, there is a blank input box for mobilenet_v2, this is abnormal. I will do more investigation about this.

Also, I create a fiddle which used to understand the difference: https://jsfiddle.net/0y67o51m/1/

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4576)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[e2e/benchmarks/local-benchmark/index.html, line 549 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4576#-MRXZLR2CgsRdEqOMuqI:-MRXcrDH6av38TLGJU6M:b2c0zcb) ([raw file](https://github.com/tensorflow/tfjs/blob/ba0ee701c43c7195aa43791607e1f48fe3427d26/e2e/benchmarks/local-benchmark/index.html#L549)):*
<details><summary><i>Previously, axinging (Xu Xing) wrote…</i></summary><blockquote>

Sorry for the typo, done @lina128 , PTAL 
</blockquote></details>

LGTM, thanks!

**Pull request merged**
