### PR TITLE
Add kernel StringSplit for CPU and WebGL backend

### PR DESCRIPTION
**Pull request by ahmedsabie**
ref #4838
TensorFlow python version is defined  [here](https://www.tensorflow.org/api_docs/python/tf/strings/split)
c++ kernel definition is  [here](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/core/kernels/string_split_op.cc)

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5089)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5089)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-cpu/src/kernels/StringSplit_impl.ts, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5089#-Ma0pTD787KDe5_-P6Qs:-Ma0pTD787KDe5_-P6Qt:bgk16tn) ([raw file](https://github.com/tensorflow/tfjs/blob/86cf4034fff14ab2a96411cf312fc8b1f6744a56/tfjs-backend-cpu/src/kernels/StringSplit_impl.ts#L25)):*
> ```XML
>     return [];
>   }
>   if (delimiters.length === 0) {
> ```

add some comments on what to expect when the delimiter is 0, 1, or n length.
i.e. when the delimiter is empty, the input string will be fully split into characters.
___
*[tfjs-core/src/ops/string/string_split.ts, line 40 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5089#-Ma0nzOi8ea2yFAWmhJ_:-Ma0nzOi8ea2yFAWmhJa:b-hc5jfv) ([raw file](https://github.com/tensorflow/tfjs/blob/86cf4034fff14ab2a96411cf312fc8b1f6744a56/tfjs-core/src/ops/string/string_split.ts#L40)):*
> ```XML
>  * ```js
>  * const result = tf.string.stringSplit(['hello world',  'a b c'], ' ');
>  * console.log(result);
> ```

this log is not needed, since each component is printed out later.
___
*[tfjs-core/src/ops/string/string_split.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5089#-Ma0oW87AFFAyNdo3NHC:-Ma0oW87AFFAyNdo3NHD:b-eejmsb) ([raw file](https://github.com/tensorflow/tfjs/blob/86cf4034fff14ab2a96411cf312fc8b1f6744a56/tfjs-core/src/ops/string/string_split.ts#L47)):*
> ```XML
>  * @param input: 1-D. Strings to split.
>  * @param delimiter: 0-D. Delimiter characters, or empty string.
>  * @param skipEmpty: If True , skip the empty strings from the result.
> ```

use lowercase `true`,  and add default value is `true`

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5089)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-backend-cpu/src/kernels/StringSplit_impl.ts, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5089#-Ma0pTD787KDe5_-P6Qs:-Ma1pc9A0c_mq_iTcxrM:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/86cf4034fff14ab2a96411cf312fc8b1f6744a56/tfjs-backend-cpu/src/kernels/StringSplit_impl.ts#L25)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

add some comments on what to expect when the delimiter is 0, 1, or n length.
i.e. when the delimiter is empty, the input string will be fully split into characters.
</blockquote></details>

Done.
___
*[tfjs-core/src/ops/string/string_split.ts, line 40 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5089#-Ma0nzOi8ea2yFAWmhJ_:-Ma1pdYf2KedhGLixtAL:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/86cf4034fff14ab2a96411cf312fc8b1f6744a56/tfjs-core/src/ops/string/string_split.ts#L40)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

this log is not needed, since each component is printed out later.
</blockquote></details>

Done.
___
*[tfjs-core/src/ops/string/string_split.ts, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5089#-Ma0oW87AFFAyNdo3NHC:-Ma1peIuE2ZNe9y0WxMu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/86cf4034fff14ab2a96411cf312fc8b1f6744a56/tfjs-core/src/ops/string/string_split.ts#L47)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

use lowercase `true`,  and add default value is `true`
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 11 of 13 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5089)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5089)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
