### PR TITLE
gatherND range check

### PR DESCRIPTION
**Pull request by hrbigelow**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

`tf.gatherND` does not report `0` for out of bounds indices on webgl backend, as is reported in the [docs](https://js.tensorflow.org/api/latest/#gatherND) and demonstrated [here](https://github.com/hrbigelow/tfjs-tests).  Tensorflow (python) does report '0' for out of bounds on GPU.

This PR adds the out-of-bounds check for the webgl backend, as well as three unit tests (for 1D, 2D and 3D).

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6464)

### CODE REVIEW

**Comment by hrbigelow** [comment]
Just one quick note - I realize this change will slow down `gatherND` by some constant factor, so one thought would be to add a default argument `setOutOfBoundsZero=false` to the API or something.  But figured it is very important to keep the API consistent with main Tensorflow.  Please let me know if you'd like me to add that.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for the fix and detailed test example.
Can you add a test for this change to ensure it would not be broken in the future. thanks.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6464#-:-N3Q-y1oElTaab14weSg:b5e43jm)* status: 0 of 1 approvals obtained (waiting on @hrbigelow and @mattsoulanille)

___
*[`tfjs-backend-webgl/src/gather_nd_gpu.ts` line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6464#-N3Q08f26aqNXJUHASmC:-N3Q08f26aqNXJUHASmD:bacxhkv) ([raw file](https://github.com/tensorflow/tfjs/blob/4065f0cdedc8404762ce66873af9a03227e30ccb/tfjs-backend-webgl/src/gather_nd_gpu.ts#L32)):*
> ```XML
>     const strideString = this.sliceDim > 1 ? 'strides[j]' : 'strides';
>     const paramsShapeType = getCoordsDataType(paramsShape.length);
>     const paramsShapeString = paramsShape.length > 1 ? 'paramsShape[j]' : 'paramsShape';
> ```

if length <= 1, should it be`paramsShape[0]` ?

**Review by mattsoulanille — COMMENTED** [review]
LGTM. Thanks for helping TFJS better match the [TensorFlow API](https://www.tensorflow.org/api_docs/python/tf/gather_nd) for gather_nd.

> Reviewed 1 of 2 files at r2, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6464#-:-N3VOBsV-BAVcIXLgkjK:b-p8wi4h)* status: 0 of 1 approvals obtained (waiting on @hrbigelow and @pyu10055)

**Review by pyu10055 — COMMENTED** [review]
cool, I think it works given the string interpolation will take care of the array.
Can you add a test that capture the out of bound scenario, similar to the example you shared.

you can create a new GatherNd_test.ts similar to `/tfjs-backend-webgl/src/kernels/TopK_test.ts`

Thanks

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6464#-:-N3VNqLe83GsO2zqNjku:b-l58d0p)* status: :shipit: complete! 1 of 1 approvals obtained

___
*[`tfjs-backend-webgl/src/gather_nd_gpu.ts` line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6464#-N3Q08f26aqNXJUHASmC:-N3VNfbm4VfCzhqSmc4P:b-6dka5p) ([raw file](https://github.com/tensorflow/tfjs/blob/4065f0cdedc8404762ce66873af9a03227e30ccb/tfjs-backend-webgl/src/gather_nd_gpu.ts#L32)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

if length <= 1, should it be`paramsShape[0]` ?
</blockquote></details>

I see, when interpolated into string `[1]` produce just `1`

**Comment by mattsoulanille** [comment]
This is odd. The root level `yarn install` failed in [CI tests for this PR](https://console.cloud.google.com/cloud-build/builds/25381b1a-bad9-41ec-bf7a-610fbc12521b;step=0?project=learnjs-174218).
```
yarn install v1.22.15
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@bazel/buildifier/-/buildifier-5.1.0.tgz: Request failed \"502 Bad Gateway\"".
info If you think this is a bug, please open a bug report with the information provided in "/workspace/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
I'll re-run them.

**Comment by hrbigelow** [comment]
> cool, I think it works given the string interpolation will take care of the array. Can you add a test that capture the out of bound scenario, similar to the example you shared.
> 
> you can create a new GatherNd_test.ts similar to `/tfjs-backend-webgl/src/kernels/TopK_test.ts`
> 
> Thanks
> 

Hi Peng, I created three tests in tfjs-backend-webgl/src/webgl_ops_test.ts included in this PR, to confirm that it returns 0 for out-of-bounds indices.  The tests cover 1D, 2D and 3D cases.  Is this the proper file to put these tests?

Thank you,

Henry

**Pull request merged**
