### PR TITLE
Allow up to TF-Hub==0.12

### PR DESCRIPTION
**Pull request by chongkong**
Current latest version of tf-hub is 0.12 (released in Apr 14) and there seems no breaking changes: https://github.com/tensorflow/hub/releases.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5152)

### CODE REVIEW

**Comment by chongkong** [comment]
FYI: tensorflow/tfx#3812

**Review by pyu10055 — COMMENTED** [review]
Thanks for the contribution, this would require us to disable support of python 2.x, we will discuss internally and get back to you.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5152#-:-Mb7SyaW3P3hcQ3H6LsX:b6883rf)* status: 0 of 1 approvals obtained

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5152)* status: 0 of 1 approvals obtained (waiting on @chongkong)

___
*[tfjs-converter/python/requirements.txt, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5152#-Mb7WN8Q6yDylS7A1Ws0:-Mb7WN8R3Etzk12e8Rul:bog2k98) ([raw file](https://github.com/tensorflow/tfjs/blob/40ddf6c1cb246063e9c51bcc385d8711d5d707d9/tfjs-converter/python/requirements.txt#L3)):*
> ```vimhelp
> tensorflow>=2.1.0,<3
> six>=1.12.0,<2
> tensorflow-hub>=0.7.0,<0.13
> ```

can we use python version condition?
```
tensorflow-hub >=0.7.0,<0.10 if python_version < 3.0.0
tensorflow-hub >=0.7.0,<0.13 if python_version >= 3.0.0
```

**Comment by chongkong** [comment]
Sorry for the confusion. Please not use Reviewable but github review. Fixed as your suggestion.

**Review by pyu10055 — APPROVED** [review]
thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5152#-:-MbCbZMO1ZuakprDqt1Z:bd5l6mr)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @chongkong)

**Pull request merged**
