### PR TITLE
Fix bug where a model with empty weights fails to load

### PR DESCRIPTION
**Pull request by thekevinscott**
First draft at addressing #7865.

This slightly refactors the `Container.loadWeights` function by pulling the "is this model a keras model" into a standalone function. That function will first assert that the model has non-empty weights before checking the first weight's name (which is subsequently used to determine keras-ness or not).

This also adds a unit test in `model_save_test.ts` enforcing that a model with empty weights can still be loaded.

### CODE REVIEW

**Review by fengwuyao — APPROVED** [review]
Looks good to me. Thanks!

**Review by pyu10055 — APPROVED** [review]

**Comment by thekevinscott** [comment]
Just merged in latest master. Is there something I need to do prior to merge, or is this in y'all's hands now?

**Review by Neilblaze — APPROVED** [review]

**Pull request merged**
