### PR TITLE
Make Tensor explicitly implement TensorInfo

### PR DESCRIPTION
**Pull request by mattsoulanille**
Tensor is assignable to TensorInfo, but it does not explicitly implement it. This property is assumed to be true by many of the gradients in core, which return Tensors as TensorInfos

https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/gradients/Dilation2D_grad.ts#L30

This commit makes Tensor explicitly implement TensorInfo.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7007)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
I'm not sure if this is desirable. Do we want `Tensor` to implement `TensorInfo`? If not, then we may want to convert the `Tensor`s returned by gradients into `TensorInfo`s.

**Comment by mattsoulanille** [comment]
Even if we don't want `Tensor` to implement `TensorInfo`, we should still merge part of this PR, because we currently have duplicate definitions of DataId in [tensor.ts](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/tensor.ts#L249) and [kernel_registry.ts](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/kernel_registry.ts#L30), which this PR fixes.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7007)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by mattsoulanille** [comment]
> I'm not sure if this is desirable. Do we want `Tensor` to implement `TensorInfo`? If not, then we may want to convert the `Tensor`s returned by gradients into `TensorInfo`s.

@pyu10055 Does this sound okay? I'm not totally sure we want this behavior, even though it's the current state of things (although not explicitly required by an `implements`). What do you think?

**Review by pyu10055 — APPROVED** [review]
given our current usage of Tensor as TensorInfo, I think your change improve the sharing of the code. thanks

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7007#-:-NFzJLieCuAppgHhhBDC:b-265ijw)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7007#-:-NFzKQRR9qhdX5SZ7oZ-:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
