### PR TITLE
[core] Remove fromPixelsAsync

### PR DESCRIPTION
**Pull request by annxingyuan**
This fixes https://github.com/tensorflow/tfjs/issues/4210

Reference PR: https://github.com/tensorflow/tfjs/pull/4139

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4211)

### CODE REVIEW

**Comment by annxingyuan** [comment]
FYI @shaoboyan @qjia7 - I apologize - I did not think through the implications of adding fromPixelsAsync to our public API - it's not that I don't think it's a good idea, however introducing a pattern for asynchronous kernels should have gone through the entire team's review, and in my haste to approve the PR I failed to get everyone's feedback. I'm moving fromPixelsAsync to WebGPU for now - but feel free to submit a PR that adds it to the core API - maybe with support in CPU/WebGL so we can make sure that the pattern works across backends.

Wherever you are depending on fromPixelsAsync, you should be able to just change the way you're importing the op and everything will still work.

Thanks and sorry again for the back and forth!

**Review by tafsiri — APPROVED** [review]
Thanks Ann! LGTM. Let's wait on Matthews pr to merge before trying to merge this one. 

> Reviewed 6 of 7 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4211#-:-MLnRRCA9ckBfpcCY-yi:b-uestx0)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @tafsiri)

**Comment by shaoboyan** [comment]
@annxingyuan  Ack and agree with adding async kernel needs more design. This patch used the simplest way to do this.

**Comment by shaoboyan** [comment]
@annxingyuan  
Hi, Ann,
Now I can back to add the fromPixelAsync again. I'd like to double check the steps to add it.
Do you think I should split the original patch to :
1. Add fromPixelAsync in tensor-core with the form ``` await kernel.kernelFunc(
      {inputs, attrs, backend: ENGINE.backend}) as Tensor3D;```
2. Add support for webgpu backend to support this fromPixelAsync kernel
3. Support more backends.

Or your concern is that the form ``` await kernel.kernelFunc(
      {inputs, attrs, backend: ENGINE.backend}) as Tensor3D;``` to support async kernel is not formal and you want a formal mechanism(e.g. something like ENGINE.runKernel)?

cc @qjia7 too.

**Comment by qjia7** [comment]
> @annxingyuan
> Hi, Ann,
> Now I can back to add the fromPixelAsync again. I'd like to double check the steps to add it.
> Do you think I should split the original patch to :
> 
> 1. Add fromPixelAsync in tensor-core with the form ` await kernel.kernelFunc( {inputs, attrs, backend: ENGINE.backend}) as Tensor3D;`
> 2. Add support for webgpu backend to support this fromPixelAsync kernel
> 3. Support more backends.
> 
> Or your concern is that the form ` await kernel.kernelFunc( {inputs, attrs, backend: ENGINE.backend}) as Tensor3D;` to support async kernel is not formal and you want a formal mechanism(e.g. something like ENGINE.runKernel)?
> 
> cc @qjia7 too.

Ping @annxingyuan . Hi Ann, could you help to clarify Shaobo's question? Thanks.

**Pull request merged**
