### PR TITLE
webgpu: Remove uniform buffer when not needed

### PR DESCRIPTION
**Pull request by qjia7**
PERF

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3321)

### CODE REVIEW

**Comment by qjia7** [comment]
@annxingyuan @kainino0x Please take a look. Thanks.
This change will slightly improve the perf of resnet model.

**Comment by qjia7** [comment]
> nit: Consider inverting from `noUniform` to `needsUniform`
> nit: Consider describing what's actually in the uniform if it's simple to do so. (Is it the shapes?`needsShapesUniform`?)

Yes. It's the shape. Change it to `needsShapesUniforms`. Previously, I used `noUniform` was because in this case I could make it optional and I didn't need to change many other programs.

**Comment by qjia7** [comment]
Please take another look. Not sure why the bots fail.

**Comment by kainino0x** [comment]
> Change it to `needsShapesUniforms`. Previously, I used `noUniform` was because in this case I could make it optional and I didn't need to change many other programs.

Ah, I didn't realize this. Sorry that required a change to so many files.

If you think it would be better to keep it as an optional `noShapeUniforms` to avoid affecting so many files, please feel free (I'm neutral).

**Pull request merged**
