### PR TITLE
Adds --benchmarks command line argument 

### PR DESCRIPTION
**Pull request by keithlwill**
"preconfigured_browser.json" is in the same format that would be generated by the browser. Load this configuration from an already made JSON and it can be sent off for benchmarking

README updated, Jasmine tests included 

@mattsoulanille @lina128 @ClaireXP

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243)

### CODE REVIEW

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Great work! There are a few things related to argparse and testing best-practices that I've detailed, but the overall structure looks good.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243#-:-McpC8Ln1ItD4W2kqtHv:b-xd0qel)* status: 0 of 1 approvals obtained (waiting on @keithlwill)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 144 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5243#-Mcp6mfP7nWU-bC9cwty:-Mcp6mfQ0f4RdZEBZ7Pu:b-3n9ozs) ([raw file](https://github.com/tensorflow/tfjs/blob/30baf58f5a60ad1f20a311495cf8372cc4abaa75/e2e/benchmarks/browserstack-benchmark/app.js#L144)):*
> ```
>         if(process.argv.includes('--benchmarks')) {
>           console.log(benchmarkResult);
>         }
> ```
It would be better to check if the argument parser has the `--benchmarks` argument than to check if `--benchmarks` appears in `process.argv`.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 166 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5243#-Mcp701ZB3gxlkOE6o7g:-Mcp701ZB3gxlkOE6o7h:bfx4xen) ([raw file](https://github.com/tensorflow/tfjs/blob/30baf58f5a60ad1f20a311495cf8372cc4abaa75/e2e/benchmarks/browserstack-benchmark/app.js#L166)):*
> ```
>   parser.add_argument(
>     '--benchmarks', {help: 'Run a preconfigured benchmark', action: 'store_true'});
> ```

Nit: It would be nice if this argument could be passed a file name instead of having the file hard-coded, but that's not technically necessary for our purposes.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 185 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5243#-Mcp7S706-qrAaGy-Q99:-Mcp7S706-qrAaGy-Q9A:bickecg) ([raw file](https://github.com/tensorflow/tfjs/blob/30baf58f5a60ad1f20a311495cf8372cc4abaa75/e2e/benchmarks/browserstack-benchmark/app.js#L185)):*
> ```
>   if(process.argv.includes('--benchmarks')) {
>     const config = require('./preconfigured_browser.json');
>     runBenchmarkFromFile(config);
> ```
Similar to above, it's better to check if the argument parser has the `--benchmarks` argument than to check if `--benchmarks` appears in `process.argv.`

Take a look at the [argparse example](https://www.npmjs.com/package/argparse#example) for more details. I recommend copy-pasting the example into a `test.js` file and running it with node (`node test.js --foo hello`) to see how argparse parses different arguments.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5243#-McpATzK96uHFAdgZdqu:-McpATzL5amlRQwa7QpO:b-cjyqya) ([raw file](https://github.com/tensorflow/tfjs/blob/30baf58f5a60ad1f20a311495cf8372cc4abaa75/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L46)):*
> ```
> mockBenchmark = jasmine.createSpy('mockBenchmark');
> ```
This should likely go in `beforeEach` instead of `beforeAll` because you want a fresh copy (with a reset counter of how many times it's been called) for each test.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5243#-Mcp9VZi4MAUi-xf7aVe:-Mcp9VZi4MAUi-xf7aVf:bn1rkfa) ([raw file](https://github.com/tensorflow/tfjs/blob/30baf58f5a60ad1f20a311495cf8372cc4abaa75/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L47)):*
> ```
> 
>     testingConfig = require('./test_config.json');
> ```
Setting this up before the test is a good idea, but it should be in [`beforeEach`](https://jasmine.github.io/api/3.7/global.html#beforeEach) instead of `beforeAll` just to make sure it's always set to the expected contents before the test is run (in case one of the tests changes it accidentally).

An example of how to use beforeEach can be found on this page: https://jasmine.github.io/tutorials/your_first_suite
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5243#-McpAmDc48uBosBDw31s:-McpAmDc48uBosBDw31t:b-2rpx0d) ([raw file](https://github.com/tensorflow/tfjs/blob/30baf58f5a60ad1f20a311495cf8372cc4abaa75/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L48)):*
> ```
> runBenchmarkFromFile(testingConfig, mockBenchmark);
> ```

Since this is the function you're testing, it should go in each spec (`it`) that uses it instead of `beforeAll`. That means we'll run it twice instead of once because we have two specs that use it, but that's fine. While normal code should be DRY (Don't Repeat Yourself), test code should be DAMP (Descriptive and Meaningful Phrases), meaning it should be easy to understand what an individual spec does without reading other code, even if it makes the test's code longer as a result.

I'll link some more info in chat
___
*[e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json, line 10 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5243#-McpBmKs5-fXA-Aid_NB:-McpBmKs5-fXA-Aid_NC:b754aq2) ([raw file](https://github.com/tensorflow/tfjs/blob/30baf58f5a60ad1f20a311495cf8372cc4abaa75/e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json#L10)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
> {
>   "summaryTabId": "Summary_1",
>   "benchmark": { "model": "face_detector", "numRuns": 10, "backend": "wasm" },
>   "browsers": {
>     "iPhone_12_1": {
>       "base": "BrowserStack",
>       "browser": "iphone",
>       "browser_version": "null",
>       "os": "ios",
>       "os_version": "14",
>       "device": "iPhone 12"
>     },
>     "Google_Pixel_5_1": {
>       "base": "BrowserStack",
>       "browser": "android",
>       "browser_version": "null",
>       "os": "android",
>       "os_version": "11.0",
>       "device": "Google Pixel 5"
>     }
>   }
> }
> ```
</details>

Looks good, and we can change this file without having to update the tests. Nice!

We will likely need to change this schema in a future PR to allow for running multiple benchmarks, but I think that PR requires some of the Promise changes Claire has been working on. When we decide on a new schema that allows for multiple benchmarks, we should document it in the design doc.

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Nice work on the test code! Just a few small changes and I think this will be ready.

> Reviewed 2 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243#-:-McuWmzM8s4Df_vxuOCh:b3c8188)* status: 0 of 1 approvals obtained (waiting on @keithlwill)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 166 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5243#-McuUltqBGaNZfm17aFE:-McuUltqBGaNZfm17aFF:bbapte5) ([raw file](https://github.com/tensorflow/tfjs/blob/8653ff9f26b37432c004827b2f8b71c3e14ecd3e/e2e/benchmarks/browserstack-benchmark/app.js#L166)):*
> ```
> return parser.parse_args();
> ```
Nice!
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 178 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5243#-McuUtZ4DuPflKytqAhm:-McuUtZ4DuPflKytqAhn:b-cui2ec) ([raw file](https://github.com/tensorflow/tfjs/blob/8653ff9f26b37432c004827b2f8b71c3e14ecd3e/e2e/benchmarks/browserstack-benchmark/app.js#L178)):*
> ```
>  args
> ```
The `args` variable should be declared so node knows what scope it's in.

You can declare it at the top of the file with `let args;` if you want other functions to have access to it once it's assigned or you can declare it here with `const args = ...`.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 4 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5243#-McuVWmU7JeRSmVSbcCs:-McuVWmU7JeRSmVSbcCt:bsagpja) ([raw file](https://github.com/tensorflow/tfjs/blob/8653ff9f26b37432c004827b2f8b71c3e14ecd3e/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L4)):*
> ```
> const app = require('./app.js');
> const runBenchmarkFromFile = app.runBenchmarkFromFile;
> ```
Nit: It's more common to import this in one step as `const {runBenchmarkFromFile} = require('./app.js')`.

**Comment by keithlwill** [comment]
Don't know how I let that declaration slip. Fixed! @mattsoulanille

**Review by mattsoulanille — COMMENTED** [review]
LGTM!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243#-:-McupWESC1XkeqcJR1Wq:b-85i648)* status: 0 of 1 approvals obtained

**Review by mattsoulanille — APPROVED** [review]
:lgtm_strong: (Forgot to actually approve)

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243#-:-Mcuq19M401pTarr2ZRs:b-ftat4s)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243)* status: 0 of 1 approvals obtained (waiting on @keithlwill and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 37 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5243#-Md2pheB5uj6hDgTK9g1:-Md2pheB5uj6hDgTK9g2:b-c6mss1) ([raw file](https://github.com/tensorflow/tfjs/blob/d7218f4b30dac99d8fc10cf71719b7fc065d7aab/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L37)):*
> ```
> describe("Testing the --benchmarks argument", () => {
> ```
Sorry I didn't catch this in my first review, but the specs under this `describe` can probably be merged into the `benchmark app cli` `describe`. `describe` is usually used to define tests for a whole file while `it` defines an individual test. 

I recommend merging the master branch and fixing merge conflicts first. Then, you can move these tests to be in the single `describe`above.

**Comment by keithlwill** [comment]
@mattsoulanille conflicts have been resolved

**Review by mattsoulanille — APPROVED** [review]
> Reviewed 4 of 13 files at r4, 3 of 11 files at r5.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @keithlwill)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 232 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5243#-Md3c3nCEs29YlQhTTq5:-Md3c3nCEs29YlQhTTq6:b-os9apj) ([raw file](https://github.com/tensorflow/tfjs/blob/1efb9df47967deaf79cff48ac59320d48e02e17b/e2e/benchmarks/browserstack-benchmark/app.js#L232)):*
> ```
> /preconfigured_browser.json
> ```
Is it better to provide path to the file?

**Review by lina128 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @keithlwill)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 211 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5243#-MdJBDmN3FLQko-BUMXD:-MdJBDmN3FLQko-BUMXE:biu2sr4) ([raw file](https://github.com/tensorflow/tfjs/blob/c5341bb7e7084f18ffef2053bc9ff6cc414ad7bf/e2e/benchmarks/browserstack-benchmark/app.js#L211)):*
> ```
> benchmarks
> ```
nit: configFile
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 221 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5243#-MdJB1CQAH26V7pWRZMq:-MdJB1CQAH26V7pWRZMr:bclbleh) ([raw file](https://github.com/tensorflow/tfjs/blob/c5341bb7e7084f18ffef2053bc9ff6cc414ad7bf/e2e/benchmarks/browserstack-benchmark/app.js#L221)):*
> ```
> file
> ```
nit: filePath
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 223 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5243#-MdJA_5v9q93sCKDOqyg:-MdJA_5v9q93sCKDOqyh:b-8aq4vz) ([raw file](https://github.com/tensorflow/tfjs/blob/c5341bb7e7084f18ffef2053bc9ff6cc414ad7bf/e2e/benchmarks/browserstack-benchmark/app.js#L223)):*
> ```
> console.log(file);
> ```
Remove?
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 233 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5243#-MdJ9ZlX-zPnnf1w6Z1q:-MdJ9ZlX-zPnnf1w6Z1r:bclbleh) ([raw file](https://github.com/tensorflow/tfjs/blob/c5341bb7e7084f18ffef2053bc9ff6cc414ad7bf/e2e/benchmarks/browserstack-benchmark/app.js#L233)):*
> ```
> file
> ```
nit: filePath
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 234 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5243#-MdJBR8P8KoHHFvA-gxM:-MdJBR8P8KoHHFvA-gxN:b-rl15b) ([raw file](https://github.com/tensorflow/tfjs/blob/c5341bb7e7084f18ffef2053bc9ff6cc414ad7bf/e2e/benchmarks/browserstack-benchmark/app.js#L234)):*
> ```
> file
> ```
Do you need to resolve the filePath?
___
*[e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json, line 8 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5243#-MdJ9oQJ5fTDdJD7o1CL:-MdJ9oQJ5fTDdJD7o1CM:bba5s1j) ([raw file](https://github.com/tensorflow/tfjs/blob/c5341bb7e7084f18ffef2053bc9ff6cc414ad7bf/e2e/benchmarks/browserstack-benchmark/preconfigured_browser.json#L8)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
> {
>   "summaryTabId": "Summary_1",
>   "benchmark": { "model": "face_detector", "numRuns": 10, "backend": "wasm" },
>   "browsers": {
>     "iPhone_12_1": {
>       "base": "BrowserStack",
>       "browser": "iphone",
>       "browser_version": "null",
>       "os": "ios",
>       "os_version": "14",
>       "device": "iPhone 12"
>     },
>     "Google_Pixel_5_1": {
>       "base": "BrowserStack",
>       "browser": "android",
>       "browser_version": "null",
>       "os": "android",
>       "os_version": "11.0",
>       "device": "Google Pixel 5"
>     }
>   }
> }
> ```
</details>

Should this file be ignored in gitignore?

**Review by keithlwill — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @keithlwill and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 232 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5243#-Md3c3nCEs29YlQhTTq5:-MdNy2vt2SvEme9b-cad:b-ms1ba) ([raw file](https://github.com/tensorflow/tfjs/blob/1efb9df47967deaf79cff48ac59320d48e02e17b/e2e/benchmarks/browserstack-benchmark/app.js#L232)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> /preconfigured_browser.json
> ```
Is it better to provide path to the file?
</blockquote></details>

Path can now be provided on command line
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 211 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5243#-MdJBDmN3FLQko-BUMXD:-MdNxT4fCFN1fx5l_Joa:bqq6g0z) ([raw file](https://github.com/tensorflow/tfjs/blob/c5341bb7e7084f18ffef2053bc9ff6cc414ad7bf/e2e/benchmarks/browserstack-benchmark/app.js#L211)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> benchmarks
> ```
nit: configFile
</blockquote></details>

The project design doc says to name the argument "benchmarks" but I do not mind changing it later if we need to
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 223 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5243#-MdJA_5v9q93sCKDOqyg:-MdNxs8p2BnZIM982PtA:bqbfii1) ([raw file](https://github.com/tensorflow/tfjs/blob/c5341bb7e7084f18ffef2053bc9ff6cc414ad7bf/e2e/benchmarks/browserstack-benchmark/app.js#L223)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> console.log(file);
> ```
Remove?
</blockquote></details>

Accidentally left in from debugging, thanks for pointing that out 
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 234 at r6](https://reviewable.io/reviews/tensorflow/tfjs/5243#-MdJBR8P8KoHHFvA-gxM:-MdNy1Ko8_UnyW5I8K9B:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/c5341bb7e7084f18ffef2053bc9ff6cc414ad7bf/e2e/benchmarks/browserstack-benchmark/app.js#L234)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> file
> ```
Do you need to resolve the filePath?
</blockquote></details>

Done.

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5243#-:-MdUAmEi6EWEB6CMUjx_:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @keithlwill and @lina128)

**Pull request merged**
