### PR TITLE
[converter] Pin python2 protobuf version to 3.17.3

### PR DESCRIPTION
**Pull request by mattsoulanille**
Fix tfjs-converter test failure in nightly and presubmit CI.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5635)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5635)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-converter/python/BUILD, line 83 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5635#-Mjl0Ldg413J1Tc7ikKc:-Mjl0Ldg413J1Tc7ikKd:bkm0dg) ([raw file](https://github.com/tensorflow/tfjs/blob/9159fda6ac35324c4a9f0b41857a110341817cc4/tfjs-converter/python/BUILD#L83)):*
> ```Starlark
>         "six>=1.12.0,<2",
>         "tensorflow-hub>=0.7.0,<0.10",
>         "tensorflow-hub>=0.7.0,<0.13",
> ```

you need to remove the line "tensorflow-hub>=0.7.0,<0.10",
___
*[tfjs-converter/python/BUILD, line 132 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5635#-Mjl0UbDAnHdvBxT8sua:-Mjl0UbDAnHdvBxT8sub:bkm2lj) ([raw file](https://github.com/tensorflow/tfjs/blob/9159fda6ac35324c4a9f0b41857a110341817cc4/tfjs-converter/python/BUILD#L132)):*
> ```Starlark
>         "six>=1.12.0,<2",
>         "tensorflow-hub>=0.7.0,<0.10",
>         "tensorflow-hub>=0.7.0,<0.13",
> ```

you need to remove the line "tensorflow-hub>=0.7.0,<0.13",

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5635)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5635)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-converter/python/BUILD, line 83 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5635#-Mjl0Ldg413J1Tc7ikKc:-Mjl1EEbD-wbmtAu9g-T:b-ucfknh) ([raw file](https://github.com/tensorflow/tfjs/blob/9159fda6ac35324c4a9f0b41857a110341817cc4/tfjs-converter/python/BUILD#L83)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you need to remove the line "tensorflow-hub>=0.7.0,<0.10",
</blockquote></details>

Thanks!
___
*[tfjs-converter/python/BUILD, line 132 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5635#-Mjl0UbDAnHdvBxT8sua:-Mjl1FecAlVp5rj2WSYD:byvnd9f) ([raw file](https://github.com/tensorflow/tfjs/blob/9159fda6ac35324c4a9f0b41857a110341817cc4/tfjs-converter/python/BUILD#L132)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you need to remove the line "tensorflow-hub>=0.7.0,<0.13",
</blockquote></details>

Thank you. Fixed!

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5635)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Pull request merged**
