### PR TITLE
[node] Add `SummaryFileWriter.histogram` TensorBoard logging

### PR DESCRIPTION
**Pull request by MaximeKjaer**
I'm opening this WIP PR, in which I have a partial implementation of a Node.js counterpart to [`tf.summary.histogram`](https://www.tensorflow.org/api_docs/python/tf/summary/histogram). This PR is in WIP status, as I've hit a small blocker, and would like to ask how I can continue from here.

To compare my implementation to a correct one, I first tried to generate a histogram of 10 normal distributions, each shifted by `i / 10` in Python. This gave me this result in TensorBoard:

image

Now, if I try to generate the same histogram using my Node.js implementation, I get the following result, which is obviously wrong:

image

I'm fairly confident that the values produced by my implementation of the `bucket` function are correct. The [Python implementation](https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/histogram/summary_v2.py) describes that the values should be as follows:

```py
"""
A histogram summary stores a list of buckets. Each bucket is encoded as
a triple `[left_edge, right_edge, count]`. Thus, a full histogram is
encoded as a tensor of dimension `[k, 3]`.
In general, the value of `k` (the number of buckets) will be a constant,
like 30. There are two edge cases: if there is no data, then there are
no buckets (the shape is `[0, 3]`); and if there is data but all points
have the same value, then there is one bucket whose left and right
endpoints are the same (the shape is `[1, 3]`).
"""
```

I think my  `buckets` implementation conforms to that; for instance, for a single normal distribution of 1000 values, centered around 0, the `buckets` function returns a `float32` tensor of shape `[30, 3]` containing the following values:

```js
[
  [ -3.3594160079956055, -3.141984701156616, 2 ],
  [ -3.141984701156616, -2.924553394317627, 4 ],
  [ -2.924553394317627, -2.7071220874786377, 2 ],
  [ -2.7071220874786377, -2.4896907806396484, 3 ],
  [ -2.4896907806396484, -2.27225923538208, 3 ],
  [ -2.27225923538208, -2.05482816696167, 10 ],
  [ -2.05482816696167, -1.8373967409133911, 10 ],
  [ -1.8373967409133911, -1.6199654340744019, 23 ],
  [ -1.6199654340744019, -1.4025341272354126, 21 ],
  [ -1.4025341272354126, -1.1851027011871338, 27 ],
  [ -1.1851027011871338, -0.9676713943481445, 52 ],
  [ -0.9676713943481445, -0.7502400875091553, 70 ],
  [ -0.7502400875091553, -0.532808780670166, 77 ],
  [ -0.532808780670166, -0.31537747383117676, 70 ],
  [ -0.31537747383117676, -0.0979461669921875, 81 ],
  [ -0.0979461669921875, 0.11948513984680176, 101 ],
  [ 0.11948513984680176, 0.336916446685791, 87 ],
  [ 0.336916446685791, 0.5543477535247803, 77 ],
  [ 0.5543477535247803, 0.7717790603637695, 76 ],
  [ 0.7717790603637695, 0.9892106056213379, 62 ],
  [ 0.9892106056213379, 1.206641674041748, 30 ],
  [ 1.206641674041748, 1.4240732192993164, 29 ],
  [ 1.4240732192993164, 1.6415042877197266, 28 ],
  [ 1.6415042877197266, 1.858935832977295, 23 ],
  [ 1.858935832977295, 2.076366901397705, 14 ],
  [ 2.076366901397705, 2.2937984466552734, 6 ],
  [ 2.2937984466552734, 2.5112295150756836, 4 ],
  [ 2.5112295150756836, 2.728661060333252, 4 ],
  [ 2.728661060333252, 2.946092128753662, 1 ],
  [ 2.946092128753662, 3.1635234355926514, 3 ]
]
```

The sum of the counts is indeed 1000, and the values do seem to follow a normal distribution around 0. So if I'm passing the correct values to the backend, I'm wondering why the visualization in TensorBoard is so wrong.

What I think could be wrong is that I'm casting to `float32` instead of `float64` like in the Python implementation. Could this be the problem? If that is the case, since TensorFlow.js doesn't support `float64` yet, how could I proceed?

Related: #1903.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5079)

### CODE REVIEW

**Comment by MaximeKjaer** [comment]
Some progress after debugging it a little bit:

image

So the Node.js implementation is now able to output the same histograms as I was generating from Python :tada: The problem wasn't that I was using a wrong type for the op, it's that I didn't understand that the op was already taking care of the "bucketization", and so placing the data into buckets was happening twice, which lead to nonsensical graphs.

However, I still have a question: how could we support different numbers of buckets? The [op description](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt#L58548-L58591) does not offer this as a parameter. Would I have to write another kernel than the one available in libtensorflow?

**Comment by MaximeKjaer** [comment]
More progress: using `WriteSummary` instead of `WriteHistogramSummary` means I can implement my own `buckets` algorithm. Using the `WriteSummary` op required setting up protobuf serialization of messages to the C++ backend, but also gives me more control. See screenshot below, where I now have support for a custom number of buckets, and custom descriptions.

image

**Comment by MaximeKjaer** [comment]
Seems like this now fully works! This PR is ready for review. 

Having added the ability to serialize metadata about the graphs with protobuf should make it possible to easily add support for description of scalar values (currently, it throws an error if we try to pass a description). Having a template for the histogram should also make it easier to implement the other missing TensorBoard features, like images, audio, etc. I'd be willing to implement those, but for now I'll keep the PR to this one feature.

**Comment by MaximeKjaer** [comment]
Tests seem to currently be failing because the CI has trouble building the yargs dependency. This looks like a transient error.

**Comment by MaximeKjaer** [comment]
Friendly ping @pyu10055 and @lina128. I saw in #5108 that the current team of maintainers isn't specialized in the Node.js development, but please do let me know if there anything I can do to help with the review of this PR. I'll gladly answer questions, add documentation or tests to help the review process.

This feature would be very nice to have for a research project on which I am working. This implementation also paves the way for feature parity with Python TF when it comes to TensorBoard support, which I think would be quite nice to have!

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for the great contribution, a high level question, should histogram writer be hooked into training callback?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5079#-:-Mb8zBRMDil5agD0BgN1:b-skrf7t)* status: 0 of 1 approvals obtained (waiting on @MaximeKjaer)

___
*[tfjs-node/src/nodejs_kernel_backend.ts, line 621 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5079#-Mb8yQ5F-G-PNIO8_34p:-Mb8yQ5G2oNzkvZrqDZv:bu5fhn5) ([raw file](https://github.com/tensorflow/tfjs/blob/34414c8725e27dd8af42653708ba06684cac476a/tfjs-node/src/nodejs_kernel_backend.ts#L621)):*
> ```XML
>     // implementation. See
>     // https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/histogram/summary_v2.py
>     bucketCount = bucketCount !== undefined ? bucketCount : 30;
> ```

verify bucketCount to be positive and throw error if not.
___
*[tfjs-node/src/tensorboard_test.ts, line 155 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5079#-Mb8u196-T8iu1JMY-ZH:-Mb8u196-T8iu1JMY-ZI:bquket6) ([raw file](https://github.com/tensorflow/tfjs/blob/34414c8725e27dd8af42653708ba06684cac476a/tfjs-node/src/tensorboard_test.ts#L155)):*
> ```XML
>   });
> 
>   describe('SummaryFileWriter.histogram', () => {
> ```

it would be good to capture the erroneous test case (empty logdir). 
___
*[tfjs-node/src/tensorboard_test.ts, line 162 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5079#-Mb8tXHE--jug54-LE49:-Mb8tXHF8dlvBuc6hafP:b-1t6442) ([raw file](https://github.com/tensorflow/tfjs/blob/34414c8725e27dd8af42653708ba06684cac476a/tfjs-node/src/tensorboard_test.ts#L162)):*
> ```
> scalars
> ```
histograms?

**Review by MaximeKjaer — COMMENTED** [review]
That's a good point, I hadn't implemented that. I've now added a callback for training, which prints histogram of model weights. Here are the results of a small training example (the one from the test I added, except I ran it for 60 iterations to get a better visualization).



> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5079#-:-MbCGvaH1JbipY03liJz:brkeqyk)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-node/src/nodejs_kernel_backend.ts, line 621 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5079#-Mb8yQ5F-G-PNIO8_34p:-MbCGCun1X_p8Vnatrtd:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/34414c8725e27dd8af42653708ba06684cac476a/tfjs-node/src/nodejs_kernel_backend.ts#L621)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

verify bucketCount to be positive and throw error if not.
</blockquote></details>

Done.
___
*[tfjs-node/src/tensorboard_test.ts, line 155 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5079#-Mb8u196-T8iu1JMY-ZH:-MbCGG7F3pwaeNztmTKd:b6z6oj) ([raw file](https://github.com/tensorflow/tfjs/blob/34414c8725e27dd8af42653708ba06684cac476a/tfjs-node/src/tensorboard_test.ts#L155)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

it would be good to capture the erroneous test case (empty logdir). 
</blockquote></details>

Isn't this already being tested for, by `empty logdir leads to error`?
___
*[tfjs-node/src/tensorboard_test.ts, line 162 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5079#-Mb8tXHE--jug54-LE49:-MbCGFf59lTvjJo83uI0:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/34414c8725e27dd8af42653708ba06684cac476a/tfjs-node/src/tensorboard_test.ts#L162)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> scalars
> ```
histograms?
</blockquote></details>

Done.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5079)* status: 0 of 1 approvals obtained (waiting on @MaximeKjaer)

___
*[tfjs-node/src/callbacks.ts, line 260 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5079#-MbCpxiO-c5pskhcifve:-MbCpxiO-c5pskhcifvf:b-vqv7d5) ([raw file](https://github.com/tensorflow/tfjs/blob/4fd047b385121aa3e9b6d7af842ee6249fb46595/tfjs-node/src/callbacks.ts#L260)):*
> ```XML
>     }
>     util.assert(
>         this.args.histogramFreq >= 0 &&
> ```

reverse the logic order, `Number.isInteger(this.args.histogramFreq) && this.args.histogramFreq >= 0`
___
*[tfjs-node/src/callbacks.ts, line 267 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5079#-MbDklg4DOJZNtZPHlXD:-MbDklg4DOJZNtZPHlXE:btvjwnr) ([raw file](https://github.com/tensorflow/tfjs/blob/4fd047b385121aa3e9b6d7af842ee6249fb46595/tfjs-node/src/callbacks.ts#L267)):*
> ```XML
>   }
> 
>   setModel(model: LayersModel): void {
> ```

It is not clear to me how would users set the model through this method?
___
*[tfjs-node/src/nodejs_kernel_backend.ts, line 623 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5079#-MbCqFmR8J10WlCBDOgu:-MbCqFmR8J10WlCBDOgv:b-ihor82) ([raw file](https://github.com/tensorflow/tfjs/blob/4fd047b385121aa3e9b6d7af842ee6249fb46595/tfjs-node/src/nodejs_kernel_backend.ts#L623)):*
> ```XML
>     bucketCount = bucketCount !== undefined ? bucketCount : 30;
>     util.assert(
>         bucketCount > 0 && Number.isInteger(bucketCount),
> ```

reverse the order `Number.isInteger(bucketCount) && bucketCount > 0`

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5079)* status: 0 of 1 approvals obtained (waiting on @MaximeKjaer)

___
*[tfjs-node/src/callbacks.ts, line 267 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5079#-MbDklg4DOJZNtZPHlXD:-MbDkx21CP7SDci9x0IH:b63qmk9) ([raw file](https://github.com/tensorflow/tfjs/blob/4fd047b385121aa3e9b6d7af842ee6249fb46595/tfjs-node/src/callbacks.ts#L267)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

It is not clear to me how would users set the model through this method?
</blockquote></details>

I don't see this method is called in the model training tests

**Review by MaximeKjaer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5079)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-node/src/callbacks.ts, line 260 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5079#-MbCpxiO-c5pskhcifve:-MbDscjO9A_w6i9puqOj:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/4fd047b385121aa3e9b6d7af842ee6249fb46595/tfjs-node/src/callbacks.ts#L260)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

reverse the logic order, `Number.isInteger(this.args.histogramFreq) && this.args.histogramFreq >= 0`
</blockquote></details>

Done.
___
*[tfjs-node/src/callbacks.ts, line 267 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5079#-MbDklg4DOJZNtZPHlXD:-MbDpl6JD3XAKrYruNF5:bpruhz3) ([raw file](https://github.com/tensorflow/tfjs/blob/4fd047b385121aa3e9b6d7af842ee6249fb46595/tfjs-node/src/callbacks.ts#L267)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I don't see this method is called in the model training tests
</blockquote></details>

It's inherited from `BaseCallback`, and is called [from here](https://github.com/tensorflow/tfjs/blob/master/tfjs-layers/src/engine/training_dataset.ts#L383). I don't think it's really supposed to be called by the users, it seems to be more for internal use.

I've added a comment to address this point.
___
*[tfjs-node/src/nodejs_kernel_backend.ts, line 623 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5079#-MbCqFmR8J10WlCBDOgu:-MbDsbZy-7yQaFgO3pyj:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/4fd047b385121aa3e9b6d7af842ee6249fb46595/tfjs-node/src/nodejs_kernel_backend.ts#L623)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

reverse the order `Number.isInteger(bucketCount) && bucketCount > 0`
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5079)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @MaximeKjaer and @pyu10055)

___
*[tfjs-node/src/callbacks.ts, line 267 at r5](https://reviewable.io/reviews/tensorflow/tfjs/5079#-MbDklg4DOJZNtZPHlXD:-MbHlRCk4Wl3O0dns8DD:bmvddru) ([raw file](https://github.com/tensorflow/tfjs/blob/4fd047b385121aa3e9b6d7af842ee6249fb46595/tfjs-node/src/callbacks.ts#L267)):*
<details><summary><i>Previously, MaximeKjaer (Maxime Kjaer) wrote…</i></summary><blockquote>

It's inherited from `BaseCallback`, and is called [from here](https://github.com/tensorflow/tfjs/blob/master/tfjs-layers/src/engine/training_dataset.ts#L383). I don't think it's really supposed to be called by the users, it seems to be more for internal use.

I've added a comment to address this point.
</blockquote></details>

got it, thanks for the explanation.

**Review by lina128 — APPROVED** [review]
Thank you for the contribution @MaximeKjaer, this is great!

**Pull request merged**
