### PR TITLE
Run Karma Chrome tests headlessly

### PR DESCRIPTION
**Pull request by mattsoulanille**
Avoid opening a bunch of browser pages when running karma chrome tests where possible. This excludes WebGPU on Linux because headless webgpu is not supported on linux yet.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6997)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
See this in action by running `yarn test` in the root of the repository. No browser windows should open, unless you add `--//:headless=true`.

**Comment by mattsoulanille** [comment]
@lina128 Can you please test this on your Mac? I'm pretty sure it works, but not completely sure. Thanks!

**Review by lina128 — COMMENTED** [review]
Passed and no window popup.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6997#-:-NFue65aE9C7x-3jNUWp:b-2z907t)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

**Review by lina128 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6997#-:-NFueF0oB_CjjMDm-5u7:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever)

**Comment by mattsoulanille** [comment]
Thanks! Offline, we also found that `yarn test` in the root of the repo fails due to wasm C compilation on Mac, which is a separate issue I'll fix in a different PR. We tested the `tfjs-core` package with `yarn test` instead.

**Review by jinjingforever — APPROVED** [review]

**Pull request merged**
