### PR TITLE
Fix `yarn build` command under tfjs-backend-webgl folder

### PR DESCRIPTION
**Pull request by haoyunfeix**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5379)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
I submit this PR because when I execute `yarn && yarn build` in tfjs-backend-webgl folder, "bazel is not found" error occurs.

But I tried this on another Windows machine, `yarn` in other folder (e.g. tfjs-core) will install bazel.exe to `C:\tools` and add to system PATH, so command `bazel build` could execute correctly. 

I don't know why there is difference between two machines but that is not a blocker for me for present.

**Comment by qjia7** [comment]
I met the similar error `bazel is not found`. So I manfully download a bazel.exe and add it into the `PATH` env. Then I can proceed. 
@haoyunfeix if the PR is ready for review, please change the state from `Draft` to `Active`.

**Comment by haoyunfeix** [comment]
@ahmedsabie PTAL. Do you think this is an issue?

**Review by mattsoulanille — APPROVED** [review]
LGTM. Thanks for catching this!

**Pull request merged**
