### PR TITLE
improve perf of packed depthwise conv2d

### PR DESCRIPTION
**Pull request by pyu10055**
This is achieved in two ways:
1. eliminate unnecessary read of the texture when padding is odd and dilation is 1)
2. localized the dot prod accumulation inside the loop, this reduce the cache miss on GPU. observed 30% improvement for certain models with 5x5 filter and 100% gain on android mid end phone.

The accuracy issue is still happening, which on mac both pack and unpack shaders have the same accuracy issues comparing to CPU, but their result matches.
On windows, the unpack shader matches with CPU result, which pack version differs. 
But the error rate seems to be compatible with the conv2d vs cpu error rate.

refer https://github.com/tensorflow/tfjs/issues/1679
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4909)

### CODE REVIEW

**Review by annxingyuan — APPROVED** [review]
Wowwwww ping i'm so impressed... and really glad to see this flag finally get turned on... 2 years later!!!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4909#-:-MXmMZ0J6SpGDJVNDUgk:b-nmp88o)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts, line 182 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4909#-MXmLILz-Q3MLBRgdNap:-MXmLILz-Q3MLBRgdNaq:bh3j5bf) ([raw file](https://github.com/tensorflow/tfjs/blob/3fbab1501a9dbf32c69ee9b8da27c6102d9d23a9/tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts#L182)):*
> ```XML
>               } else {
>                 if (nextTexelOffset === 1) {
>                   mainLoop += `
> ```

Could add a note about the logic behind this branching?
___
*[tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts, line 282 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4909#-MXmMQhT8Pd30rRF0NJ5:-MXmMQhT8Pd30rRF0NJ6:bu1pf6c) ([raw file](https://github.com/tensorflow/tfjs/blob/3fbab1501a9dbf32c69ee9b8da27c6102d9d23a9/tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts#L282)):*
> ```XML
>             mainLoop += `
>               vec4 wTexelR${r}C${c + 1} = getW(${r}, ${c + 1}, d1, q);
>               dotProd += vec4(xR${r}C${c + 1}.xy * wTexelR${r}C${c + 1}.xz, xR${
> ```

I guess creating temporary vars for the `xy`/`zw` didn't resolve the windows issue?
___
*[tfjs-backend-webgl/src/flags_webgl.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4909#-MXmLZr2CwEBTDnVU_uo:-MXmLZr2CwEBTDnVU_up:b-ra0xjj) ([raw file](https://github.com/tensorflow/tfjs/blob/3fbab1501a9dbf32c69ee9b8da27c6102d9d23a9/tfjs-backend-webgl/src/flags_webgl.ts#L66)):*
> ```XML
> /** Whether we will pack the depthwise conv op. */
> // TODO: https://github.com/tensorflow/tfjs/issues/1679
> ENV.registerFlag('WEBGL_PACK_DEPTHWISECONV', () => true);
> ```

:partying_face:

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4909)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @pyu10055)

___
*[tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts, line 182 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4909#-MXmLILz-Q3MLBRgdNap:-MXmQlW54dVShbksQFaY:b-7tfmjp) ([raw file](https://github.com/tensorflow/tfjs/blob/3fbab1501a9dbf32c69ee9b8da27c6102d9d23a9/tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts#L182)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Could add a note about the logic behind this branching?
</blockquote></details>

added
___
*[tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts, line 282 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4909#-MXmMQhT8Pd30rRF0NJ5:-MXmQo1T7WubTF77kGZV:beeeg83) ([raw file](https://github.com/tensorflow/tfjs/blob/3fbab1501a9dbf32c69ee9b8da27c6102d9d23a9/tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts#L282)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

I guess creating temporary vars for the `xy`/`zw` didn't resolve the windows issue?
</blockquote></details>

no, I tried many combinations, temp variable, even accumulate the 4 channels separately with 4 floats. I have not yet find a way to improve accuracy.
but there are some interesting observation, I have used a fixed weight, when the weight is power of 2, no accuracy loss is observed. I am not sure
if that is caused by the multiplication or the addition.

**Review by lina128 — APPROVED** [review]
Thank you Ping, this is great!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4909#-:-MXmwUMCBJdD5v7XoiR0:bl50nje)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan and @pyu10055)

___
*[tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4909#-MXmvaVm47kBn-4T-yhQ:-MXmvaVm47kBn-4T-yhR:bih6p0f) ([raw file](https://github.com/tensorflow/tfjs/blob/3fbab1501a9dbf32c69ee9b8da27c6102d9d23a9/tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts#L66)):*
> ```XML
>      */
>     for (let r = 0; r < filterHeight; r++) {
>       for (let texelC = 0; texelC < (texelsAcross / 2 + 1); texelC++) {
> ```

Will this condition be calculated in every iteration?
___
*[tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts, line 182 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4909#-MXmLILz-Q3MLBRgdNap:-MXmuzSg6eOvh0YPorBX:b-zbveei) ([raw file](https://github.com/tensorflow/tfjs/blob/3fbab1501a9dbf32c69ee9b8da27c6102d9d23a9/tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts#L182)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

added
</blockquote></details>

I couldn't see the note.
___
*[tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts, line 282 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4909#-MXmMQhT8Pd30rRF0NJ5:-MXmwhvBCPjgsSmiEcwX:bv11pdh) ([raw file](https://github.com/tensorflow/tfjs/blob/3fbab1501a9dbf32c69ee9b8da27c6102d9d23a9/tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts#L282)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

no, I tried many combinations, temp variable, even accumulate the 4 channels separately with 4 floats. I have not yet find a way to improve accuracy.
but there are some interesting observation, I have used a fixed weight, when the weight is power of 2, no accuracy loss is observed. I am not sure
if that is caused by the multiplication or the addition.
</blockquote></details>

Can you add a note about why do the localized dot production, I'm guessing this may help other shaders that have similar logic?

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4909)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan and @pyu10055)

___
*[tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts, line 360 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4909#-MY6FHVd8LKskOIyuz7x:-MY6FHVd8LKskOIyuz7y:bjn9303) ([raw file](https://github.com/tensorflow/tfjs/blob/5ebdaca977e17a110bea0e37c1a24d5b17d52f17/tfjs-backend-webgl/src/conv_packed_gpu_depthwise.ts#L360)):*
> ```XML
> 
>         //intialize dotProd with a small epsilon seems to reduce GPU accuracy loss.
>         vec4 dotProd = vec4(0.000000000000001);
> ```

This is counterintuitive, accuracy is improved by imposing a small error. Curious why :)

**Pull request merged**
