### PR TITLE
[wasm] Add acos and acosh kernels

### PR DESCRIPTION
**Pull request by chunnienc**
This PR also updates the atan kernel's behavior: it can take i32/bool tensor and return the output in the same dtype.
This change is to make the behavior of wasm kernels align with cpu and webgl kernels, although the outputs of these kernels are subtly different now.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256)* status: 0 of 1 approvals obtained (waiting on @chunnienc)

___
*[`tfjs-backend-wasm/src/cc/kernels/Acosh.cc` line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7256#-NLMhu7lCVz4h-7fN9ZE:-NLMhu7lCVz4h-7fN9ZF:br2wht4) ([raw file](https://github.com/tensorflow/tfjs/blob/45c540182ca1467b7c962fbea73df1fc8acf20db/tfjs-backend-wasm/src/cc/kernels/Acosh.cc#L51)):*
> ```cpp
>       break;
>     case DType::int32:
>       unary_i32(x_id, out_id, acosh_impl<int>);
> ```

I am not sure what would i32 and bool result represent for acos and acosh, are there any tests in tensorflow that target these output dtypes?

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Looks almost ready to be merged. I just have a few comments on the output types of acos and acosh. Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256#-:-NLMoXtN--CTpZBn5vUR:b-cyxldi)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfjs-backend-wasm/src/cc/kernels/Acosh.cc` line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7256#-NLMhu7lCVz4h-7fN9ZE:-NLMlJuy1UeRwbhXzJP0:b-7bxgj6) ([raw file](https://github.com/tensorflow/tfjs/blob/45c540182ca1467b7c962fbea73df1fc8acf20db/tfjs-backend-wasm/src/cc/kernels/Acosh.cc#L51)):*
Bool does not seem to be supported by TF `Acos`:

```
>>> ibool = tf.constant([True, False])
>>> tf.raw_ops.Acos(x=ibool)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/msoulanille/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
    return f(**kwargs)
  File "/home/msoulanille/.local/lib/python3.10/site-packages/tensorflow/python/ops/gen_math_ops.py", line 184, in acos
    _ops.raise_from_not_ok_status(e, name)
  File "/home/msoulanille/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of bool is not in the list of allowed values: bfloat16, half, float, double, int8, int16, int32, int64, complex64, complex128
	; NodeDef: {{node Acos}}; Op<name=Acos; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT8, DT_INT16, DT_INT32, DT_INT64, DT_COMPLEX64, DT_COMPLEX128]> [Op:Acos]
```

However, int is supported:
```
>>> input = tf.constant([0, 1, -1], dtype='int32')
>>> tf.raw_ops.Acos(x=input)
<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 3], dtype=int32)>
```
Docs: https://www.tensorflow.org/api_docs/python/tf/raw_ops/Acos#returns

For `Acosh`, bool is not supported (similar error message), and surprisingly, int is also not supported.
Docs: https://www.tensorflow.org/api_docs/python/tf/raw_ops/Acosh
___
*[`tfjs-backend-wasm/src/cc/kernels/Atan.cc` line 51 at r2](https://reviewable.io/reviews/tensorflow/tfjs/7256#-NLMoH8TAChpUr2TI21Q:-NLMoH8TAChpUr2TI21R:b-ibimxf) ([raw file](https://github.com/tensorflow/tfjs/blob/c1de872216f86f231c23f72e8997ec71aef7bbac/tfjs-backend-wasm/src/cc/kernels/Atan.cc#L51)):*
> ```cpp
>       break;
>     case DType::int32:
>       unary_i32(x_id, out_id, atan_impl<int>);
> ```

Nice catch. I think I missed that the output type is the same as the input type in my last review. 
https://www.tensorflow.org/api_docs/python/tf/raw_ops/Atan



_Code quote:_
```cpp
      unary_i32(x_id, out_id, atan_impl<int>);
```

**Comment by chunnienc** [comment]
> Collaborator

No, I'd say the current behavior of acos and acosh on int32 and bool are undefined, and our cpu and webgl can return different results for int32 and bool types: https://jsfiddle.net/nas437md/ (you can try to modify the dtype to int32 and bool). What I'm trying to do is to make the wasm kernel "do something" instead of throwing an error, so that it somehow behaves in a simiarly across different kernels. 

These are not the only kernels/ops having this issue, I was playing around with different backend recently and there are various problems with int32 and bool type:
1.Backends returns different results (like acos and acosh in cpu and webgl)
2. The coverage are different (like neg - cpu and webgl accepts bool dtype, but there is no wasm implementation)
3. Not well documented - our [public API doc](https://js.tensorflow.org/api/latest/?_gl=1*tb6ms6*_ga*ODM3NTQ0MTA1LjE2Njk3NTQyNDU.*_ga_W0YLR4190T*MTY3MzI4OTUwNC4yMi4xLjE2NzMyODk3NzQuMC4wLjA.) has no information about how it works with int32 and bool type

Sadly, there are no tests for behaviors with unexpected dtypes now. I'm still thinking about various way to deal with this issue.

**Review by pyu10055 — COMMENTED** [review]
Yeah, I agree there are definitely inconsistent right now with our backends and thank you for digging into this. 
In general I think if WASM can mimic TF CPU behavior would be great, typically GPU behave slightly differently even for TF, due to GPU shader cannot throw errors.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256#-:-NLMsV2V3LcsCNpYDOsq:brfpba6)* status: 0 of 1 approvals obtained

**Comment by chunnienc** [comment]
> Yeah, I agree there are definitely inconsistent right now with our backends and thank you for digging into this. In general I think if WASM can mimic TF CPU behavior would be great, typically GPU behave slightly differently even for TF, due to GPU shader cannot throw errors.
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256#-:-NLMsV2V3LcsCNpYDOsq:brfpba6)_ status: 0 of 1 approvals obtained

For atan, acos, and acosh, our CPU backend accepts float32, int32, and bool. And that is the implementation in this PR .

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[`tfjs-backend-wasm/src/cc/kernels/Acosh.cc` line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7256#-NLMhu7lCVz4h-7fN9ZE:-NLNMYYu92Xm4JQ5paPw:bofda7q) ([raw file](https://github.com/tensorflow/tfjs/blob/45c540182ca1467b7c962fbea73df1fc8acf20db/tfjs-backend-wasm/src/cc/kernels/Acosh.cc#L51)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

Bool does not seem to be supported by TF `Acos`:

```
>>> ibool = tf.constant([True, False])
>>> tf.raw_ops.Acos(x=ibool)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/msoulanille/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_export.py", line 412, in wrapper
    return f(**kwargs)
  File "/home/msoulanille/.local/lib/python3.10/site-packages/tensorflow/python/ops/gen_math_ops.py", line 184, in acos
    _ops.raise_from_not_ok_status(e, name)
  File "/home/msoulanille/.local/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7209, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of bool is not in the list of allowed values: bfloat16, half, float, double, int8, int16, int32, int64, complex64, complex128
	; NodeDef: {{node Acos}}; Op<name=Acos; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_INT8, DT_INT16, DT_INT32, DT_INT64, DT_COMPLEX64, DT_COMPLEX128]> [Op:Acos]
```

However, int is supported:
```
>>> input = tf.constant([0, 1, -1], dtype='int32')
>>> tf.raw_ops.Acos(x=input)
<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 0, 3], dtype=int32)>
```
Docs: https://www.tensorflow.org/api_docs/python/tf/raw_ops/Acos#returns

For `Acosh`, bool is not supported (similar error message), and surprisingly, int is also not supported.
Docs: https://www.tensorflow.org/api_docs/python/tf/raw_ops/Acosh
</blockquote></details>

As Matt pointed out, for acos we should throw errors for bool, and for acosh we should throw errors for both bool and int

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[`tfjs-backend-wasm/src/cc/kernels/Acosh.cc` line 51 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7256#-NLMhu7lCVz4h-7fN9ZE:-NLNNjdLD3uOQNl0DCsj:b-gua1eu) ([raw file](https://github.com/tensorflow/tfjs/blob/45c540182ca1467b7c962fbea73df1fc8acf20db/tfjs-backend-wasm/src/cc/kernels/Acosh.cc#L51)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

As Matt pointed out, for acos we should throw errors for bool, and for acosh we should throw errors for both bool and int
</blockquote></details>

I think our current cpu backend, unary just convert the value to the tensor dtype directly using typed array, the behavior is bit different from TensorFlow implementation, for most part it is ok. Since WASM has better control on the conversion, I would prefer more align with TensorFlow. thanks

**Comment by chunnienc** [comment]
I removed the implementations for unexpected dtypes for these ops. It will dump an warning message in the console but not thrown an error. No framework-level changes in this PR. If we want to align the behavior more with TF, we may need some changes in tfjs-core for dtype checks (like what op cos has).

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

**Review by pyu10055 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256#-:-NLNom0yCZkRv0JuC5r2:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by mattsoulanille — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7256#-:-NLRhI9J8DB2j4s_XVJ9:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
