### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/273)

### CODE REVIEW

**Comment by DanielRuf** [comment]
I signed it!

**Comment by DanielRuf** [comment]
Waiting for Node.js 10.1.0, see https://github.com/nodejs/node/issues/20258

**Comment by DanielRuf** [comment]
Looks good so far.

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/273#-:-LC4E7BIEYeawsC6TEz9:b-jbsf8z)*

**Pull request merged**
