### PR TITLE
[wasm] Add Conv3D kernels

### PR DESCRIPTION
**Pull request by chunnienc**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7466)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7466)* status: 0 of 1 approvals obtained (waiting on @chunnienc, @Linchenn, and @mattsoulanille)

___
*[`tfjs-backend-wasm/src/cc/kernels/AvgPool3DGrad.cc` line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7466#-NQR3w1S5mMr3MZ0wRLo:-NQR3w1S5mMr3MZ0wRLp:bt35jpy) ([raw file](https://github.com/tensorflow/tfjs/blob/7e11b80ee75d0cdfd9a04b9abd04bc800259ad1f/tfjs-backend-wasm/src/cc/kernels/AvgPool3DGrad.cc#L68)):*
> ```cpp
>           .effective_filter_height = effective_filter_height,
>           .effective_filter_width = effective_filter_width,
>           .pad_front = effective_filter_depth - 1 - pad_front,
> ```

are these change related?
___
*[`tfjs-backend-wasm/src/cc/kernels/MaxPool3DGrad.cc` line 88 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7466#-NQR46G05ro4ltpaBPDc:-NQR46G05ro4ltpaBPDd:b-2guby3) ([raw file](https://github.com/tensorflow/tfjs/blob/7e11b80ee75d0cdfd9a04b9abd04bc800259ad1f/tfjs-backend-wasm/src/cc/kernels/MaxPool3DGrad.cc#L88)):*
> ```cpp
>       [](const std::pair<float, int>& data) { return data.second; });
> 
>   pool3d_info.pad_front = effective_filter_depth - 1 - pad_front;
> ```

same here

**Comment by chunnienc** [comment]
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7466)_ status: 0 of 1 approvals obtained (waiting on @chunnienc, @Linchenn, and @mattsoulanille)
> 
> _[`tfjs-backend-wasm/src/cc/kernels/AvgPool3DGrad.cc` line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7466#-NQR3w1S5mMr3MZ0wRLo:-NQR3w1S5mMr3MZ0wRLp:bt35jpy) ([raw file](https://github.com/tensorflow/tfjs/blob/7e11b80ee75d0cdfd9a04b9abd04bc800259ad1f/tfjs-backend-wasm/src/cc/kernels/AvgPool3DGrad.cc#L68)):_
> 
> > ```c++
> >           .effective_filter_height = effective_filter_height,
> >           .effective_filter_width = effective_filter_width,
> >           .pad_front = effective_filter_depth - 1 - pad_front,
> > ```
> 
> are these change related?
> 
> _[`tfjs-backend-wasm/src/cc/kernels/MaxPool3DGrad.cc` line 88 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7466#-NQR46G05ro4ltpaBPDc:-NQR46G05ro4ltpaBPDd:b-2guby3) ([raw file](https://github.com/tensorflow/tfjs/blob/7e11b80ee75d0cdfd9a04b9abd04bc800259ad1f/tfjs-backend-wasm/src/cc/kernels/MaxPool3DGrad.cc#L88)):_
> 
> > ```c++
> >       [](const std::pair<float, int>& data) { return data.second; });
> > 
> >   pool3d_info.pad_front = effective_filter_depth - 1 - pad_front;
> > ```
> 
> same here

This PR adds a new Conv3d backprop impl with forward conv info, which computes the new pad for backprop in the backprop function. The pool3d part is changed to align with this new style of defining backprop function with conv/pool info computed in JS.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7466)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @chunnienc, @Linchenn, and @mattsoulanille)

**Review by mattsoulanille — APPROVED** [review]
LGTM

> Reviewed 3 of 13 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7466#-:-NQSM_qHEfzAj03O7uSJ:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @chunnienc, @Linchenn, and @pyu10055)

___
*[`tfjs-backend-wasm/src/cc/conv3d_impl.h` line 100 at r2](https://reviewable.io/reviews/tensorflow/tfjs/7466#-NQSJ3qH1YsjvCOp-OJA:-NQSJ3qH1YsjvCOp-OJB:btsh1fq) ([raw file](https://github.com/tensorflow/tfjs/blob/fd6cf73b20de88261151b8c62fe8e711eb8b8774/tfjs-backend-wasm/src/cc/conv3d_impl.h#L100)):*
> ```objc
>             for (int yc = 0; yc < info.out_width; ++yc) {
>               int xc_corner = yc * info.stride_width - info.pad_left;
>               for (int wc = 0; wc < info.filter_width; ++wc) {
> ```

Nit: Would you get better CPU cache hits if you put the filter width and height loops right next to each other, since filter is contiguous in memory? Right now, they're separated by the output width loop. I'm not an expert at this, so I could be totally wrong.


Actually, this might be better to do in a different PR, since this one appears to be directly implementing the CPU backend's algorithm in WASM.



_Code quote:_
```objc
          for (int wr = 0; wr < info.filter_height; ++wr) {
            int xr = xr_corner + wr * info.dilation_height;
            if (xr < 0 || xr >= info.in_height) {
              continue;
            }

            for (int yc = 0; yc < info.out_width; ++yc) {
              int xc_corner = yc * info.stride_width - info.pad_left;
              for (int wc = 0; wc < info.filter_width; ++wc) {
```
___
*[`tfjs-backend-wasm/src/cc/kernels/AvgPool3DGrad.cc` line 68 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7466#-NQR3w1S5mMr3MZ0wRLo:-NQSM8vz3S8AoNudLenq:bjfpqax) ([raw file](https://github.com/tensorflow/tfjs/blob/7e11b80ee75d0cdfd9a04b9abd04bc800259ad1f/tfjs-backend-wasm/src/cc/kernels/AvgPool3DGrad.cc#L68)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

are these change related?
</blockquote></details>

This is factoring out the pad calculations to pool3d_impl.h

**Comment by mattsoulanille** [comment]
@pyu10055 I'm not sure why Reviewable requested your review again when I submitted mine. I don't see any relevant changes since your last review.

**Pull request merged**
