### PR TITLE
Modularize more ops in webgl backend

### PR DESCRIPTION
**Pull request by jinjingforever**
- Sin, Tan, Atan2, BatchNorm, multiply
- Export KernelFunc from them (plus Cos)
- Slightly refactor some methods in backend_webgl.ts to make them work better with kernels.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3932)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3932)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 874 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKHBpEBAhnynR9DgWY:-MHKHBpEBAhnynR9DgWZ:bih5dpi) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/backend_webgl.ts#L874)):*
> ```XML
>   // TODO(jingjin): delete this method when batchMetMul (which uses multiply
>   // here) is modularized.
>   multiply(a: Tensor, b: Tensor): Tensor {
> ```

Multiply may need to be modularized along with Complex, because this.complex needs also be modularized in this method. For context, see this PR: https://github.com/tensorflow/tfjs/pull/3868
In a nutshell, the underlying data structure for Complex will change, so kernels affected by that change needs to modularize together. Other than that, we should not leave implementation in backend_webgl if they are modularized, batchMatMul can call tf.mul(...), so that we decouple any dependency on multiply in this file.
___
*[tfjs-backend-webgl/src/kernels/Atan2.ts, line 28 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKJJ13E8Qscx3gb7Yo:-MHKJJ13E8Qscx3gb7Yp:b-tg2qzt) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Atan2.ts#L28)):*
> ```XML
>     (params: {inputs: Atan2Inputs, backend: MathBackendWebGL}) =>
>         TensorInfo | TensorInfo[] = ({inputs, backend}) => {
>           const {a, b} = inputs;
> ```

Just some thoughts: I wonder if it's possible to abstract this kernelFunc to a method createBinaryKernelFunc(a, b, program, packedProgram), to be shared by all binary ops. Similar to cpu. Well, there may be more nuance in Webgl than Cpu, I'll leave it to @annxingyuan and @tafsiri to shed some light on this. Or we can keep modularizing and if we see a pattern, refactor later. Either way is fine by me.
___
*[tfjs-backend-webgl/src/kernels/BatchNorm.ts, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKLJuUBbXm1XrRandI:-MHKLJuV2iN6YrjTutkA:bpug2vk) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/BatchNorm.ts#L29)):*
> ```XML
>   attrs: FusedBatchNormAttrs
> }) => TensorInfo | TensorInfo[] = ({inputs, backend, attrs}) => {
>   const {x, mean, variance, offset, scale} = inputs;
> ```

There's some transform code at the op level, we need to duplicate them here, because the inputs and attributes passed in are raw form (without the transform). For example, varianceEpsilon may be null, in this case, it should be set to 0.001. Take a look at the transform code in this part: https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/batchnorm.ts#L63-L89 After modularization, the transform code at the op level should be removed. 
___
*[tfjs-backend-webgl/src/kernels/Multiply_impl.ts, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKMnly9pCbSjbcMsGO:-MHKMnly9pCbSjbcMsGP:b-hgzpaa) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Multiply_impl.ts#L54)):*
> ```XML
>   }
> 
>   if (backend.shouldExecuteOnCPU([a, b]) && a instanceof Tensor &&
> ```

CPU has changed Complex.complexTensor to complexTensorInfo, I wonder if it's better to migrate WebGL in the same order, i.e. Complex along with Multiply.
___
*[tfjs-backend-webgl/src/kernels/Sin.ts, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKNeBJDHUiczZB1CFd:-MHKNeBJDHUiczZB1CFe:bkdgxjh) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Sin.ts#L26)):*
> ```XML
>     (params: {inputs: SinInputs, backend: MathBackendWebGL}) =>
>         TensorInfo | TensorInfo[] = ({inputs, backend}) => {
>           const {x} = inputs;
> ```

Should we make a createUnaryKernelFunc(...) for all the unary ops?

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3932)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Atan2.ts, line 28 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKJJ13E8Qscx3gb7Yo:-MHLhXBd3NMgJFmZocAY:b-8k3mrm) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Atan2.ts#L28)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Just some thoughts: I wonder if it's possible to abstract this kernelFunc to a method createBinaryKernelFunc(a, b, program, packedProgram), to be shared by all binary ops. Similar to cpu. Well, there may be more nuance in Webgl than Cpu, I'll leave it to @annxingyuan and @tafsiri to shed some light on this. Or we can keep modularizing and if we see a pattern, refactor later. Either way is fine by me.
</blockquote></details>

Creating an abstracted helper method sounds good to me! The only nuance in WebGL is that some of the binary kernels have packed implementations (backend_webgl.ts has a packedBinaryOp helper to deal with this specifically), which we would need to account for. Up to you whether to create that helper method in this PR or a follow-up PR. 
___
*[tfjs-backend-webgl/src/kernels/Cos.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHLiPYy0FEKgBoXG-a-:-MHLiPYy0FEKgBoXG-a0:b19uy8n) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Cos.ts#L24)):*
> ```XML
> 
> export const cosKernelFunc:
>     (params: {inputs: CosInputs, backend: MathBackendWebGL}) =>
> ```

nit: we've been calling this 'args' rather than 'params' elsewhere (e.g. WASM kernels)
___
*[tfjs-backend-webgl/src/kernels/Multiply_impl.ts, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHLir836dvhjYS9ilTF:-MHLir836dvhjYS9ilTG:bdwd2bq) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Multiply_impl.ts#L54)):*
> ```XML
>   }
> 
>   if (backend.shouldExecuteOnCPU([a, b]) && a instanceof Tensor &&
> ```

why introduce the instanceof tensor checks here? 
___
*[tfjs-backend-webgl/src/kernels/Sin.ts, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKNeBJDHUiczZB1CFd:-MHLkALl6iBJ61G3bbKQ:bb7ohn6) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Sin.ts#L26)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should we make a createUnaryKernelFunc(...) for all the unary ops?
</blockquote></details>

sgtm

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3932)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 874 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKHBpEBAhnynR9DgWY:-MHNnSqh9MwJyUkZ89um:b5j3iku) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/backend_webgl.ts#L874)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Multiply may need to be modularized along with Complex, because this.complex needs also be modularized in this method. For context, see this PR: https://github.com/tensorflow/tfjs/pull/3868
In a nutshell, the underlying data structure for Complex will change, so kernels affected by that change needs to modularize together. Other than that, we should not leave implementation in backend_webgl if they are modularized, batchMatMul can call tf.mul(...), so that we decouple any dependency on multiply in this file.
</blockquote></details>

Thanks for the info! Just realized that this is a more involved changes than I thought:) Will do multiply+complex in another PR after I learn more about this topic. Thanks!
___
*[tfjs-backend-webgl/src/kernels/Atan2.ts, line 28 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKJJ13E8Qscx3gb7Yo:-MHNnyfhAjqOkhBVggZ0:b5jluwv) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Atan2.ts#L28)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Creating an abstracted helper method sounds good to me! The only nuance in WebGL is that some of the binary kernels have packed implementations (backend_webgl.ts has a packedBinaryOp helper to deal with this specifically), which we would need to account for. Up to you whether to create that helper method in this PR or a follow-up PR. 
</blockquote></details>

Added unaryKernelFunc and binaryKernelFunc in kernel_funcs_utils.ts (see above, similar to #3919 from Na). Please see if those would work. Will also add the logic to handle complex64 data type in upcoming PRs.
___
*[tfjs-backend-webgl/src/kernels/BatchNorm.ts, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKLJuUBbXm1XrRandI:-MHNoHnMDa3_quzqj7Xx:bum9t47) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/BatchNorm.ts#L29)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

There's some transform code at the op level, we need to duplicate them here, because the inputs and attributes passed in are raw form (without the transform). For example, varianceEpsilon may be null, in this case, it should be set to 0.001. Take a look at the transform code in this part: https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/ops/batchnorm.ts#L63-L89 After modularization, the transform code at the op level should be removed. 
</blockquote></details>

Thanks for the discussion offline! Looks like this will also need reshape to be modularized and Ann has a PR (#3910) for that already. I will modularize batchNorm after that PR is merged. Removed from this PR for now.
___
*[tfjs-backend-webgl/src/kernels/Cos.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHLiPYy0FEKgBoXG-a-:-MHNoj_b8D5JiG6eRR4W:bb6sh2i) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Cos.ts#L24)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

nit: we've been calling this 'args' rather than 'params' elsewhere (e.g. WASM kernels)
</blockquote></details>

Ack.
___
*[tfjs-backend-webgl/src/kernels/Multiply_impl.ts, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKMnly9pCbSjbcMsGO:-MHNomzS5HSQD2z4iO8P:bg00dbi) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Multiply_impl.ts#L54)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

CPU has changed Complex.complexTensor to complexTensorInfo, I wonder if it's better to migrate WebGL in the same order, i.e. Complex along with Multiply.
</blockquote></details>

Agree. Will do.
___
*[tfjs-backend-webgl/src/kernels/Multiply_impl.ts, line 54 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHLir836dvhjYS9ilTF:-MHNooCW829X2h2VuRGS:b4c394w) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Multiply_impl.ts#L54)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

why introduce the instanceof tensor checks here? 
</blockquote></details>

Ack. Will clean this up when I modularize multiply+complex in another PR.
___
*[tfjs-backend-webgl/src/kernels/Sin.ts, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHKNeBJDHUiczZB1CFd:-MHNoypb20TU0g6kDhJf:bd3olye) ([raw file](https://github.com/tensorflow/tfjs/blob/f08c241c98001595aed48fe30136cff0e12e77dd/tfjs-backend-webgl/src/kernels/Sin.ts#L26)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

Done. See kernel_funcs_utils.ts.

**Review by tafsiri — CHANGES_REQUESTED** [review]
> Reviewed 9 of 57 files at r2, 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3932)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Div.ts, line 25 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHNqgwE3chllimGMTf0:-MHNqgwF9NVM0BWqObma:bjt853b) ([raw file](https://github.com/tensorflow/tfjs/blob/d26b70a3b47045b3b8dbb6602074b933c473a7dc/tfjs-backend-webgl/src/kernels/Div.ts#L25)):*
> ```XML
> 
> export const divKernelFunc =
>     binaryKernelFunc(binaryop_gpu.DIV, binaryop_packed_gpu.DIV, true);
> ```

use a named constant for true or add a /* name of arg */ comment inline for readability
___
*[tfjs-backend-webgl/src/kernels/SquaredDifference.ts, line 22 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHNr6fd2rQB0CDb25Z8:-MHNr6fd2rQB0CDb25Z9:bv8ey8) ([raw file](https://github.com/tensorflow/tfjs/blob/d26b70a3b47045b3b8dbb6602074b933c473a7dc/tfjs-backend-webgl/src/kernels/SquaredDifference.ts#L22)):*
> ```XML
> import {binaryKernelFunc} from '../kernel_utils/kernel_funcs_utils';
> 
> const SQUARED_DIFFERENCE = 'return (a - b) * (a - b);';
> ```

Question about conventions for these snippets. Other files like square above define this in unaryop_gpu, are they reused and this one is not. Is this an opportunity for unifying the pattern. I have a slight preference for this style where the snippet lives with the kernel definition. I could go either way, but thing they should be consistent if possible.

 cc @annxingyuan

**Review by jinjingforever — COMMENTED** [review]
Thanks Yannick! Will wait for Ann's opinion on where to put op snippets.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3932#-:-MHNtEvL7l4L55UVnWAM:b-1otcc0)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Div.ts, line 25 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHNqgwE3chllimGMTf0:-MHNszwDAXGd0W8nOJk0:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/d26b70a3b47045b3b8dbb6602074b933c473a7dc/tfjs-backend-webgl/src/kernels/Div.ts#L25)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

use a named constant for true or add a /* name of arg */ comment inline for readability
</blockquote></details>

Done

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3932)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/SquaredDifference.ts, line 22 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHNr6fd2rQB0CDb25Z8:-MHODFqU-LB4bW3TrWEV:b-vpj0jr) ([raw file](https://github.com/tensorflow/tfjs/blob/d26b70a3b47045b3b8dbb6602074b933c473a7dc/tfjs-backend-webgl/src/kernels/SquaredDifference.ts#L22)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Question about conventions for these snippets. Other files like square above define this in unaryop_gpu, are they reused and this one is not. Is this an opportunity for unifying the pattern. I have a slight preference for this style where the snippet lives with the kernel definition. I could go either way, but thing they should be consistent if possible.

 cc @annxingyuan 
</blockquote></details>

Putting the snippets in the file SGTM!

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3932)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/SquaredDifference.ts, line 22 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3932#-MHNr6fd2rQB0CDb25Z8:-MHOPFWY1zSMHAAyLdTW:boyexb3) ([raw file](https://github.com/tensorflow/tfjs/blob/d26b70a3b47045b3b8dbb6602074b933c473a7dc/tfjs-backend-webgl/src/kernels/SquaredDifference.ts#L22)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Putting the snippets in the file SGTM! 
</blockquote></details>

Done. Thanks!

**Review by tafsiri — APPROVED** [review]
LGTM!

> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3932#-:-MHRdO3q5FJwswGRkV9m:b-85i648)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

**Pull request merged**
