### PR TITLE
[webgpu] Unify expression naming in shaders

### PR DESCRIPTION
**Pull request by haoyunfeix**
cum_webgpu: Remove unnecessary workgroupSizeX
depthwise_conv2d_nchw_shared_webgpu: Unify flatWorkgroupSize name
matmul_packed_webgpu: First letter lowercase

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6941)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
@qjia7 @xhcao @axinging @gyagp PTAL

**Review by qjia7 — APPROVED** [review]
LGTM with one nit.

Nit: missed this one https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgpu/src/transpose_shared_webgpu.ts#L45 ?

**Review by gyagp — APPROVED** [review]
LGTM

**Review by qjia7 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
