### PR TITLE
[webgl] Modularize oneHot and cropAndResize

### PR DESCRIPTION
**Pull request by tafsiri**
Also introduce a codemod tool (adapted from the one used to modularize the node.js backend) to help speed up refactoring. 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4243)

### CODE REVIEW

**Comment by tafsiri** [comment]
I think CI is filing for an unrelated reason so i'll mark this as ready for review now.

**Comment by mattsoulanille** [comment]
Confirmed that CI is failing due to unrelated reasons. I forgot to include dependencies of reverse dependencies in the cloudbuild.yml generator. The fix is in [this PR](https://github.com/tensorflow/tfjs/pull/4231), which should be merged after tests pass.

**Review by annxingyuan — APPROVED** [review]
This is awesome Yannick! My only comment is - do you think we should include the kernel generator in the codebase? I can't imagine a user ever needing it, and it seems that it would be obsolete once we're done modularizing. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4243#-:-MMHcCjl2E0uYPJHQPNI:b-he4m5g)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan and @mattsoulanille)

**Comment by mattsoulanille** [comment]
This looks great! I assume it's not merged yet because we were thinking of using unaryKernelFunc.

**Comment by tafsiri** [comment]
@annxingyuan I put it in the scripts folder so that others on the team can use it. Once we are done with modularizing we can delete it.

@mattsoulanille in this case i was not going to use unaryKernelFunc, those helpers are for simple unary funcs with no attributes. These two kernels have attributes.

**Pull request merged**
