### PR TITLE
Update README to make things more clear to run the cartoonizer demo

### PR DESCRIPTION
**Pull request by jinjingforever**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5271)

### CODE REVIEW

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5271)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5271)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

___
*[tfjs-tflite/demo/README.md, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5271#-MdXUfWq2O7NS_N-H1uu:-MdXUfWr52A0dUeRrRkV:bd4erxt) ([raw file](https://github.com/tensorflow/tfjs/blob/065e7dae6612fbc813d64c29d06f34f7980f449b/tfjs-tflite/demo/README.md#L23)):*
> ```Markdown
> Make sure `gsutil` is installed. It will be used by the script below.
> Follow the installation instructions [here][gsutil]. You can skip the
> "Setting Up Credentialsto Access Protected Data" section.
> ```

typo? Credentials ?

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5271)* status: 0 of 1 approvals obtained (waiting on @jinjingforever)

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5271)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-tflite/demo/README.md, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5271#-MdXUfWq2O7NS_N-H1uu:-MdYHgYeD9-p4FofPQMp:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/065e7dae6612fbc813d64c29d06f34f7980f449b/tfjs-tflite/demo/README.md#L23)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

typo? Credentials ?
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5271)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Pull request merged**
