### PR TITLE
Add Prod kernel to WASM backend.

### PR DESCRIPTION
**Pull request by miaowzhang**
This PR is about #3849 (No Prod kernel in WASM).

I have added the implementation of **Prod kernel** for the tfjs-backend-wasm. The commit has passed the standard test (yarn test, including op::Prod), and verified on my iOS/Android phone and WeChat miniprogram.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4138)

### CODE REVIEW

**Comment by miaowzhang** [comment]
@googlebot I signed it!

**Comment by miaowzhang** [comment]
@annxingyuan @tafsiri Please take a look if you have time. Thanks.

**Review by tafsiri — COMMENTED** [review]
Thanks for the contribution. This structurally looks good to me. @annxingyuan could you review.

meta-note for Ann, I think the pattern for transpose used here (similar to max) would also benefit from having a similar refCount/disposeIntermediate as the other backends. Not for this Pr but something to consider for future.

> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4138#-:-MKproQdCK6PNKq7CtjY:b-6yxgoa)* status: 0 of 1 approvals obtained (waiting on @annxingyuan)

**Review by annxingyuan — APPROVED** [review]
Thanks @miaowzhang !

**Pull request merged**
