### PR TITLE
Edited issue template for concision

### PR DESCRIPTION
**Pull request by Git-Good**
Improved readability and comprehension.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/88)

### CODE REVIEW

**Comment by Git-Good** [comment]
I signed the CLA

**Comment by nsthorat** [comment]
:lgtm_strong:

Looks good, couple small things then I will merge it. In generally I like the more concise language.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[ISSUE_TEMPLATE.md, line 3 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs/88#-L9FvIrYATKfomptBGIq:-L9FvIrYATKfomptBGIr:b-73e64h) ([raw file](https://github.com/tensorflow/tfjs/blob/9441d273266a9bac634f8b8413ee7f171ef5096f/ISSUE_TEMPLATE.md#L3)):*
> ```Markdown
> To get help from the community, check out our [Google group](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs).
> 
> Else, submit an issue based on the following template. 
> ```

s/Else/Otherwise

---

*[ISSUE_TEMPLATE.md, line 5 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs/88#-L9FvLCz4OZDLZ53bOdC:-L9FvLCz4OZDLZ53bOdD:b-cn04c9) ([raw file](https://github.com/tensorflow/tfjs/blob/9441d273266a9bac634f8b8413ee7f171ef5096f/ISSUE_TEMPLATE.md#L5)):*
> ```Markdown
> Else, submit an issue based on the following template. 
> 
> Issue Template:
> ```

I would just remove this line

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs/88#-:-L9FvM90BSffD2F_ITM3:bcooemd)*

**Comment by nsthorat** [comment]
:lgtm_strong:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs/88#-:-L9IL3ZF0AbAaIOL3kXB:b-jbsf8z)*

**Comment by nsthorat** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[ISSUE_TEMPLATE.md, line 5 at r1](https://beta.reviewable.io/reviews/tensorflow/tfjs/88#-L9FvLCz4OZDLZ53bOdC:-L9ILAIfBjIFYCunLzqp:b-t4gsb8) ([raw file](https://github.com/tensorflow/tfjs/blob/9441d273266a9bac634f8b8413ee7f171ef5096f/ISSUE_TEMPLATE.md#L5)):*
<details><summary><i>Previously, nsthorat (Nikhil Thorat) wrote…</i></summary><blockquote>

I would just remove this line
</blockquote></details>

Sorry, I actually meant remove this "Issue Template" line :) Then I will merge, apologies for the round trip!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/tensorflow/tfjs/88)*

**Comment by caisq** [comment]
Ping @nsthorat?

**Comment by nsthorat** [comment]
Waiting for the removal of "Issue Template:" but maybe I should just merge and I'll do it.

**Comment by caisq** [comment]
@nsthorat FYI, you can apply edits to a PR on GitHub. Let me know if you need help finding out how to do that.

**Comment by nsthorat** [comment]
Done.

**Pull request merged**
