### PR TITLE
[tfjs-core] Performance issue with tf.signal.stft (#4623)

### PR DESCRIPTION
**Pull request by harangp**
PERF

Removing performance bottleneck from stft.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4790)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
Thanks for the contribution, the STFT test are failing with these change, can you help to explain your changes?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4790#-:-MVIuHxeDyd8pBjspc2N:b-76wq4i)* status: 0 of 1 approvals obtained

**Comment by harangp** [comment]
Yes. As I noted in the PERF bug report, I noticed, that both rfft and fft has batch support, so I simply removed the split / combine and the associated for loop. Initial test showed, that we got back the same results as the original rfft produced. As it turns out, for the unit test, it does not hold it's case, while the split tensor the rfft returns:
```
Tensor
    [1 + 0j, 0 + -1j, -1 + 0j]
```
While for the batched version it returns this:
```
Tensor
    [[1 + 0j, -0.5 + -0.8660254j],
     [1 + 0j, -0.5 + -0.8660254j],
     [1 + 0j, -0.5 + -0.8660254j]]
```
Which is obviously not right. I debuged the code, and it seams that the tf.spectral.fft() function (called by rfft()) returns this tensor:
```
Tensor
    [[1 + 0j, -0.5 + -0.8660254j, -0.5 + 0.8660254j],
     [1 + 0j, -0.5 + -0.8660254j, -0.5 + 0.8660254j],
     [1 + 0j, -0.5 + -0.8660254j, -0.5 + 0.8660254j]]
```
which is in line with the (wrong) result. I'd like to get to the bottom of this. There must be a reason FFT behaves differently in this case. Thanks for your patience.

**Comment by harangp** [comment]
There was a typo using an important variable invoking rfft. I corrected it, tests run locally without errors. Please recheck,

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4790)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by pyu10055 — APPROVED** [review]
thank you!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4790#-:-MWb_ZX44mi34F2DWqWk:bsv417h)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
