### PR TITLE
[debugger] Bare minimum of tfjs debugger angular app

### PR DESCRIPTION
**Pull request by jinjingforever**
- Create a bare minimum Angular app for tfjs debugger with rxjs store and material design set up (very similar to playground)
- Hook it up with CI.
- Set up scripts to manually deploy to firebase hosting (live and preview) and github action for automatically deploying to firebase hosting when PR is merged.

See the preview [here](https://tfjs-debugger--20211105-120241-41osmv7c.web.app/) which is generated by `yarn deploy-firebase-dev`. 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5820)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
Thanks! couple high level questions:
1. should this use bazel for build?
2. should it be in the tfjs mono repo or in the sig-tfjs repo?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5820#-:-Mo-nTQtA_XylWyTANu7:bjr7xxv)* status: 0 of 1 approvals obtained

**Review by jinjingforever — COMMENTED** [review]
1. I actually considered using bazel but I didn't do it due to two reasons:
   - This project is fairly independent (e.g. it will mostly load packages dynamically) so I don't see too much value using bazel.
   - It is fairly complex to set things up with bazel. The angular CLI seems to work fairly well out of the box.

2. I don't have a strong opinion for this. But now I think you are right that this might be better in `sig-tfjs`:) Please let me know your decision and I can move it there if needed. Also, if we move it to sig-tfjs then we probably can continue using angular CLI to build it for now.

Thank you for the questions!  

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5820#-:-Mo097v99G0FQNMN0mwr:b-onr5is)* status: 0 of 1 approvals obtained

**Review by pyu10055 — COMMENTED** [review]
cool, I think sig-tfjs makes sense, and eventually we shall move benchmark tool there too. We can create a sub-directory (i.e. toolings?)

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5820#-:-Mo0OGhnERVYNQWC-NW4:b-dacur9)* status: 0 of 1 approvals obtained

**Review by jinjingforever — COMMENTED** [review]
SGTM! Will send you a PR there. Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5820#-:-Mo0TeaSADdIli_SR0rU:berxcrp)* status: 0 of 1 approvals obtained

**Pull request closed without merging**
