### PR TITLE
Fix TS development on Apple silicon

### PR DESCRIPTION
**Pull request by mattsoulanille**
Upgrade Bazel version to 4.2.2 (supported by m1), rules_nodejs to 4.6.1 (required for node 16.13.2), and node to 16.13.2 (same as our CI docker image and required for m1 compatibility).

tfjs-backend-wasm is fixed in #6098.

Still not working:
* tfjs-converter python. #6089 may fix this if you have a working python2.7 homebrew install.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6090)

### CODE REVIEW

**Review by pyu10055 — APPROVED** [review]
Thanks for fixing for M1. I assume we won't check in this PR untile your PR is merged, right?

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6090#-:-MuwphDwAf2HJC3LjDS1:bmo1zid)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Review by mattsoulanille — COMMENTED** [review]
Thanks for the review! I moved the WASM fixes into a separate PR #6098 , so this PR is no longer blocked.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6090#-:-Mv-hjNc0V_1rVqiqGiq:b-c3dqun)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Comment by lina128** [comment]
Tested on M1X, all tests passed except WASM, which is expected.

**Review by lina128 — APPROVED** [review]
Thank you Matt.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6090#-:-Mv5ekpc23y9k_f3p-y4:b-t3m4w2)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
