### PR TITLE
Subject: Add swish activation function support (#1804)

### PR DESCRIPTION
**Pull request by Triforcey**
Body:
FEATURE

Created Swish activation function class and unit tests

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3879)

### CODE REVIEW

**Review by caisq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3879)* status: 0 of 1 approvals obtained (waiting on @caisq and @Triforcey)

___
*[tfjs-layers/src/activations.ts, line 224 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3879#-MGOqNt_-CAH3ZR9GAgH:-MGOqNt_-CAH3ZR9GAgI:b-x8gq13) ([raw file](https://github.com/tensorflow/tfjs/blob/d68938fc2861bde025c6caa1ac30751eac2d6c96/tfjs-layers/src/activations.ts#L224)):*
> ```
> alpha = 1
> ```

Is this necessary? Can you provide links to related document or code? I haven't seen the Swish activation with this parameter before. Also it appears to be not used anywhere or exposed to the public API.

**Comment by Triforcey** [comment]
Yes, that variable is a part of the function's definition. It is referenced as β here: https://en.wikipedia.org/wiki/Swish_function. I still need to expose this to the API as a trainable parameter. I'm going to do that. I would appreciate any pointers you may have on how to go about doing that.

**Comment by Triforcey** [comment]
Okay, sounds good. Thank you for your assistance.

**Comment by caisq** [comment]
@rthadur @pyu10055 feel free to merge the PR when you're comfortable.

**Pull request merged**
