### PR TITLE
[wasm] Add AvgPool3D and MaxPool3D kernels

### PR DESCRIPTION
**Pull request by chunnienc**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7294)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7294)* status: 0 of 1 approvals obtained (waiting on @chunnienc and @mattsoulanille)

___
*[`tfjs-backend-wasm/src/cc/pool3d_impl.h` line 1 at r2](https://reviewable.io/reviews/tensorflow/tfjs/7294#-NMVXZsa2zn_7TA32gYr:-NMVXZsa2zn_7TA32gYs:bfu1bh6) ([raw file](https://github.com/tensorflow/tfjs/blob/97932762eac43e5122ef711b288bcfa40ed66e85/tfjs-backend-wasm/src/cc/pool3d_impl.h#L1)):*
> ```objc
> #ifdef __EMSCRIPTEN__
> ```

missing copyright header?
___
*[`tfjs-backend-wasm/src/cc/pool3d_impl.cc` line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7294#-NMVWqtK5tGiI3lTE6BJ:-NMVWqtK5tGiI3lTE6BK:b53d2th) ([raw file](https://github.com/tensorflow/tfjs/blob/193fdadcdce3f2ba0f8346834c41965452e04316/tfjs-backend-wasm/src/cc/pool3d_impl.cc#L1)):*
> ```cpp
> #ifdef __EMSCRIPTEN__
> ```

missing copyright header
___
*[`tfjs-backend-wasm/src/cc/pool3d_impl.cc` line 45 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7294#-NMVZ28710Saa87I_njW:-NMVZ28710Saa87I_njX:b-jrmqeh) ([raw file](https://github.com/tensorflow/tfjs/blob/193fdadcdce3f2ba0f8346834c41965452e04316/tfjs-backend-wasm/src/cc/pool3d_impl.cc#L45)):*
> ```cpp
> };
> template <typename OUT, typename IN, typename T>
> inline void Pool3DImpl(
> ```

is this method used? seems to be a simplified version of NDHWCPool3DImpl?

**Comment by chunnienc** [comment]
Added license header. I should have deleted the file `pool3d_impl.cc`.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7294)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @chunnienc and @mattsoulanille)

___
*[`tfjs-backend-wasm/src/cc/pool3d_impl.h` line 32 at r3](https://reviewable.io/reviews/tensorflow/tfjs/7294#-NMVf8yb2N9Vf06DHx46:-NMVf8yb2N9Vf06DHx47:b-m681bo) ([raw file](https://github.com/tensorflow/tfjs/blob/54525da43ed220cee522889e9516f4395d0beed8/tfjs-backend-wasm/src/cc/pool3d_impl.h#L32)):*
> ```objc
>     return v;
>   }
>   return (v % d + v) % d;
> ```

this does not guarantee non negative, right?
maybe the method name need to be updated to better reflect the logic?
___
*[`tfjs-backend-wasm/src/cc/pool3d_impl.h` line 78 at r3](https://reviewable.io/reviews/tensorflow/tfjs/7294#-NMVfbJA38nDRTuIgUUR:-NMVfbJA38nDRTuIgUUS:bi5anmh) ([raw file](https://github.com/tensorflow/tfjs/blob/54525da43ed220cee522889e9516f4395d0beed8/tfjs-backend-wasm/src/cc/pool3d_impl.h#L78)):*
> ```objc
> };
> template <typename IN, typename OUT, typename FI, typename FAP, typename FAG>
> inline void NDHWCPool3DImpl(const IN* x_buf, OUT* out_buf,
> ```

like the code sharing across ops.

**Comment by chunnienc** [comment]
> this does not guarantee non negative, right?
> maybe the method name need to be updated to better reflect the logic?

This method is intended to get the non-negative modulo. But you're right, the implementation was wrong. Fixed, thanks for the review and pointing out.

**Review by mattsoulanille — APPROVED** [review]
> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7294)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @chunnienc)

___
*[`tfjs-backend-wasm/src/cc/pool3d_impl.h` line 120 at r3](https://reviewable.io/reviews/tensorflow/tfjs/7294#-NMVgmdy0qsd4B-en2PK:-NMVgmdy0qsd4B-en2PL:b-e800ut) ([raw file](https://github.com/tensorflow/tfjs/blob/54525da43ed220cee522889e9516f4395d0beed8/tfjs-backend-wasm/src/cc/pool3d_impl.h#L120)):*
> ```objc
>             int out_offset =
>                 info.out_offset(batch, y_depth, y_row, y_col, channel);
>             out_buf[out_offset] = filter_aggregate(filter_data);
> ```

Thinking about future improvements, addition (in AvgPool3D) is associative, so I wonder if this could be parallelized or vectorized by xnnpack. That might not matter if this op is not the main source of slowness in models, though. 



_Code quote:_
```objc
                  filter_apply(filter_data, x_buf[x_offset]);
                }
              }
            }
            int out_offset =
                info.out_offset(batch, y_depth, y_row, y_col, channel);
            out_buf[out_offset] = filter_aggregate(filter_data);
```

**Review by pyu10055 — APPROVED** [review]
> dition (in AvgPool3D) is associative, so I wonder if this could be parallelized or vectorized by xnnpack. That might not mat
LGTM

> Reviewed 8 of 9 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7294#-:-NMVpn9_-AFjU9gtHrtv:bgdosjh)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @chunnienc)

___
*[`tfjs-backend-wasm/src/cc/pool3d_impl.h` line 120 at r3](https://reviewable.io/reviews/tensorflow/tfjs/7294#-NMVgmdy0qsd4B-en2PK:-NMVppV_28nhpumPqm4d:b-w16iw3) ([raw file](https://github.com/tensorflow/tfjs/blob/54525da43ed220cee522889e9516f4395d0beed8/tfjs-backend-wasm/src/cc/pool3d_impl.h#L120)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

Thinking about future improvements, addition (in AvgPool3D) is associative, so I wonder if this could be parallelized or vectorized by xnnpack. That might not matter if this op is not the main source of slowness in models, though. 
</blockquote></details>

does Xnnpack have pooling op?

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7294)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @chunnienc)

___
*[`tfjs-backend-wasm/src/cc/pool3d_impl.h` line 120 at r3](https://reviewable.io/reviews/tensorflow/tfjs/7294#-NMVgmdy0qsd4B-en2PK:-NMW6hDs1JjVlyYP6BVN:bmx54id) ([raw file](https://github.com/tensorflow/tfjs/blob/54525da43ed220cee522889e9516f4395d0beed8/tfjs-backend-wasm/src/cc/pool3d_impl.h#L120)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

does Xnnpack have pooling op?
</blockquote></details>

XNNPACK has 2D Pooling ops. I don't know if they could be used as part of a 3D pooling implementation. Also, I don't know if they have a general pooling utility like the one in this PR.

https://github.com/google/XNNPACK#operator-coverage

**Comment by chunnienc** [comment]
tflite has its own implementation of pooling3d (/lite/kernels/pooling3d.cc), and there is no xnnpack delegate for it. But I think it's more because MaxPool3D and AvgPool3D are not yet built-in ops there.

Similarly, conv3d is a built-in op in tflite but xnnpack delegate does not have it either. So I assume 3d implementation with xnnpack 2d is non-trivial. I will revisit this topic (using xnnpack for 3d ops) later if there is a need.

**Comment by mattsoulanille** [comment]
> tflite has its own implementation of pooling3d (/lite/kernels/pooling3d.cc), and there is no xnnpack delegate for it. But I think it's more because MaxPool3D and AvgPool3D are not yet built-in ops there.
> 
> Similarly, conv3d is a built-in op in tflite but xnnpack delegate does not have it either. So I assume 3d implementation with xnnpack 2d is non-trivial. I will revisit this topic (using xnnpack for 3d ops) later if there is a need.

SGTM. Feel free to merge this whenever. I didn't mean to block it.

**Pull request merged**
