### PR TITLE
[e2e] Add pose-detection models to e2e benchmark

### PR DESCRIPTION
**Pull request by haoyunfeix**
FEATURE

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5147)

### CODE REVIEW

**Review by qjia7 — APPROVED** [review]
LGTM
@lina128 @pyu10055 @jinjingforever take a look, thanks.

Two issues:
For WebGL backend, test correctness is false for BlazePose when the input type is image or imageBitmap. While it's true when the input type is tensor. 
For WASM backend, it throws runtime error `memory access out of bounds`.

**Comment by qjia7** [comment]
A weird thing for me: For blazepose model, if the input is image/imageBitmap, it doesn't go to `Conv2DBackpropInput`. However, if the input is tensor, it will call `Conv2DBackpropInput`. Should all of them go to call `Conv2DBackpropInput`? @lina128

**Review by lina128 — COMMENTED** [review]
This pipeline has two models, it only runs the detector model once to get the region of interest (roi), and then runs the landmark model in followup runs. The result from previous landmark model will be used to calculate new roi. The detector model is slow to run, using this setup, it helps the model to run in real-time. To be able to benchmark the pipeline running both models, you need to reset the pipeline between each run, there's an API, `model.reset()`.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5147#-:-Mb8v9vR3BalYQqJsWjn:b-4x4pra)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @haoyunfeix, @jinjingforever, and @pyu10055)

___
*[e2e/benchmarks/model_config.js, line 360 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5147#-Mb8slNC-t1eplrcGXc-:-Mb8slNC-t1eplrcGXc0:bjf82fq) ([raw file](https://github.com/tensorflow/tfjs/blob/646b495ed866a4387671142d08c63222d3128502/e2e/benchmarks/model_config.js#L360)):*
> ```
> true
> ```
enableSmoothing should be false. This option is for video.
___
*[e2e/benchmarks/model_config.js, line 367 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5147#-Mb8t4Q_3rWJhQGDQjKh:-Mb8t4Q_3rWJhQGDQjKi:b-pyb5g) ([raw file](https://github.com/tensorflow/tfjs/blob/646b495ed866a4387671142d08c63222d3128502/e2e/benchmarks/model_config.js#L367)):*
> ```
> tf.zeros([inputResolution, inputResolution, 3]);
> ```
Can we use the imageTensor from 'tennis_standing.jpg'? Can we use `tf.browser.fromPixels`?

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5147#-:-MbgTOk03HcPN2bHJ_ps:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @haoyunfeix, @jinjingforever, and @pyu10055)

**Pull request merged**
