### PR TITLE
webgpu: Fix the delayed mode memory leak issue

### PR DESCRIPTION
**Pull request by qjia7**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4836)

### CODE REVIEW

**Comment by qjia7** [comment]
@gyagp @axinging @haoyunfeix Please take a look, thanks.

**Comment by qjia7** [comment]
+ @xhcao

**Comment by xhcao** [comment]
LGTM

**Comment by qjia7** [comment]
@lina128 @jinjingforever Please take a look, thanks.

**Review by jinjingforever — APPROVED** [review]

**Pull request merged**
