### PR TITLE
[wasm] add elu kernel

### LINKED ISSUE #5434: [WASM] elu missing kernel
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow.js version (you are using): v3.8.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Until now, elu op has not yet been implemented in the WASM backend. WASM backend should support this op.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Anyone who needs to use this op inside wasm backend.

**Any Other info.**
This missing kernel is part of [TFJS WASM missing kernels project](https://github.com/tensorflow/tfjs/projects/18#card-56957190).

### PR DESCRIPTION
**Pull request by raffizulvian**
This missing kernel is part of [TFJS WASM missing kernels project](https://github.com/tensorflow/tfjs/projects/18#card-56957190).
Fixes #5434 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5435)

### CODE REVIEW

**Review by lina128 — CHANGES_REQUESTED** [review]
Thanks for the contribution, @raffizulvian! Can you also add ELU = 6 to the FusableActivation enum in src/cc/backend.h, also add corresponding enum in kernels/types.ts

Can you also add Elu support to all fused kernels in batch_mat_mul_impl.cc, conv2d_impl.cc.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5435#-:-MgNZArRBThwaz4cvXNA:b26chw0)* status: 0 of 1 approvals obtained (waiting on @raffizulvian)

___
*[tfjs-backend-wasm/src/cc/kernels/Elu.h, line 24 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5435#-MgNYVz7-aD9rWdGa0oU:-MgNYVz7-aD9rWdGa0oV:b4mbfzm) ([raw file](https://github.com/tensorflow/tfjs/blob/431eee582824e9d7f3c91ae38cc3bb8d7b83df7f/tfjs-backend-wasm/src/cc/kernels/Elu.h#L24)):*
> ```
> E
> ```
Should this be lowercase?

**Review by raffizulvian — COMMENTED** [review]
Sure! I thought earlier that I should create a separate PR for this.
After adding support for fused kernels and run tests locally, one test for fused mat-mul failing. This test is not related to ELU, but RELU. I'm not quite sure why this test fails after I remove test exclusion for ELU.

The line I remove:
https://github.com/tensorflow/tfjs/blob/9a2bbc3e448e80172591eeb2addec5d6ce2dd4ae/tfjs-backend-wasm/src/setup_test.ts#L106-L107

Here is the log:
image

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5435#-:-MgQQXnF2fKsqKbnc-mE:bpo0n79)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-backend-wasm/src/cc/kernels/Elu.h, line 24 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5435#-MgNYVz7-aD9rWdGa0oU:-MgQQk7D1Il7ZfZ2SM_T:bl5n6dv) ([raw file](https://github.com/tensorflow/tfjs/blob/431eee582824e9d7f3c91ae38cc3bb8d7b83df7f/tfjs-backend-wasm/src/cc/kernels/Elu.h#L24)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> E
> ```
Should this be lowercase?
</blockquote></details>

https://github.com/tensorflow/tfjs/blob/9a2bbc3e448e80172591eeb2addec5d6ce2dd4ae/tfjs-backend-wasm/src/cc/kernels/Prelu.h#L24
https://github.com/tensorflow/tfjs/blob/9a2bbc3e448e80172591eeb2addec5d6ce2dd4ae/tfjs-backend-wasm/src/cc/kernels/Sigmoid.h#L24
It seems other kernels using uppercase. Please let me know if I'm missing something.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5435)* status: 0 of 1 approvals obtained (waiting on @raffizulvian)

___
*[tfjs-backend-wasm/src/cc/kernels/Elu.h, line 24 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5435#-MgNYVz7-aD9rWdGa0oU:-MgRONtz-Kg9jP6vSaE_:bjtx16r) ([raw file](https://github.com/tensorflow/tfjs/blob/431eee582824e9d7f3c91ae38cc3bb8d7b83df7f/tfjs-backend-wasm/src/cc/kernels/Elu.h#L24)):*
<details><summary><i>Previously, raffizulvian (Raffi Zulvian Muzhaffar) wrote…</i></summary><blockquote>

https://github.com/tensorflow/tfjs/blob/9a2bbc3e448e80172591eeb2addec5d6ce2dd4ae/tfjs-backend-wasm/src/cc/kernels/Prelu.h#L24
https://github.com/tensorflow/tfjs/blob/9a2bbc3e448e80172591eeb2addec5d6ce2dd4ae/tfjs-backend-wasm/src/cc/kernels/Sigmoid.h#L24
It seems other kernels using uppercase. Please let me know if I'm missing something.

</blockquote></details>

Sorry, I was looking at the wrong cc file. Your Elu.cc does have uppercase, I was looking at the elu_impl. Please ignore my comment earlier.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5435)* status: 0 of 1 approvals obtained (waiting on @raffizulvian)

___
*[tfjs-backend-wasm/src/setup_test.ts, line 251 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5435#-MgRQY7h2rmGaEhJldFo:-MgRQY7h2rmGaEhJldFp:b-7cb56u) ([raw file](https://github.com/tensorflow/tfjs/blob/431eee582824e9d7f3c91ae38cc3bb8d7b83df7f/tfjs-backend-wasm/src/setup_test.ts#L251)):*
> ```
> 'broadcasted bias',  // Not yet implemented.
> ```
Please also remove this line.

**Review by raffizulvian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5435)* status: 0 of 1 approvals obtained (waiting on @lina128 and @raffizulvian)

___
*[tfjs-backend-wasm/src/setup_test.ts, line 251 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5435#-MgRQY7h2rmGaEhJldFo:-MgRSF87C6_rE_GlnVvE:b-j0ph7v) ([raw file](https://github.com/tensorflow/tfjs/blob/431eee582824e9d7f3c91ae38cc3bb8d7b83df7f/tfjs-backend-wasm/src/setup_test.ts#L251)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> 'broadcasted bias',  // Not yet implemented.
> ```
Please also remove this line.
</blockquote></details>

Working, will do.
___
*[tfjs-backend-wasm/src/cc/kernels/Elu.h, line 24 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5435#-MgNYVz7-aD9rWdGa0oU:-MgRS0yb3T_UOqnVXyDr:b-1ijlhk) ([raw file](https://github.com/tensorflow/tfjs/blob/431eee582824e9d7f3c91ae38cc3bb8d7b83df7f/tfjs-backend-wasm/src/cc/kernels/Elu.h#L24)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Sorry, I was looking at the wrong cc file. Your Elu.cc does have uppercase, I was looking at the elu_impl. Please ignore my comment earlier.
</blockquote></details>

It's okay

**Review by raffizulvian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5435)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-backend-wasm/src/setup_test.ts, line 251 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5435#-MgRQY7h2rmGaEhJldFo:-MgRYzx4BSNUtteRvPpc:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/431eee582824e9d7f3c91ae38cc3bb8d7b83df7f/tfjs-backend-wasm/src/setup_test.ts#L251)):*
<details><summary><i>Previously, raffizulvian (Raffi Zulvian Muzhaffar) wrote…</i></summary><blockquote>

Working, will do.
</blockquote></details>

Done.

**Review by lina128 — APPROVED** [review]
LGTM, thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5435#-:-MgRZOLh6pRcZRgPUBpr:b2c0zcb)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
