### PR TITLE
[webgl] Fixed split issue with negative axis.

### PR DESCRIPTION
**Pull request by BruceDai**
BUG

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4478)

### CODE REVIEW

**Comment by BruceDai** [comment]
@tafsiri @lina128 PTAL, thanks

**Comment by tafsiri** [comment]
@BruceDai thanks for this, the change looks good but it would be great to have a test with a negative axes param to catch regressions across backends. Would you be able to add one to split_test.ts?

**Review by lina128 — COMMENTED** [review]
Nice catch, thank you Bruce! LGTM. +1 to Yannick's suggestion.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4478#-:-MQK1cPn6SG2mTLhehZH:byab7lc)* status: 0 of 1 approvals obtained

**Comment by BruceDai** [comment]
@tafsiri @lina128 Please take another look, thanks.

**Comment by lina128** [comment]
The test failed because of this line, can you also update this line to use $axis? https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-wasm/src/kernels/SplitV.ts#L33

**Comment by BruceDai** [comment]
@lina128 Done. PTAL, thanks.

**Review by lina128 — APPROVED** [review]
Thank you! LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4478#-:-MQLazo20aZHCWbVdWFT:b-tbpm15)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
