### PR TITLE
Don't rebuild core when running test-snippets in CI

### PR DESCRIPTION
**Pull request by mattsoulanille**
Prevent test-snippets from rebuilding tfjs-core in CI and instead have it wait for core to be built by its own cloudbuild step.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4399)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
Thank you, looks like the other packages that contains snippet tests (layers, data, converter), do not have test-snippets-ci target, maybe keep consistent with those or update those to have ci suffix. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4399#-:-MOX5CZG7QioPg9Fjiln:bhm1v0o)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4399)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4399)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-core/cloudbuild.yml, line 68 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4399#-MOXF6RfBWB1UFKgrEVd:-MOXF6Rg73FyYhLfnWsD:b-dds4hc) ([raw file](https://github.com/tensorflow/tfjs/blob/d40e391a82dae3450a696e745d4a1c3953799539/tfjs-core/cloudbuild.yml#L68)):*
> ```YAML
>   entrypoint: 'yarn'
>   args: ['test-snippets-ci']
>   waitFor: ['yarn', 'build']
> ```

you might need to update the cloudbuild test golden file

**Review by mattsoulanille — COMMENTED** [review]
I'll update layers, data, and converter in this PR too. Commits coming in a moment.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4399#-:-MOXF_FKD8FO0eXSnNfa:b-cndtmf)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-core/cloudbuild.yml, line 68 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4399#-MOXF6RfBWB1UFKgrEVd:-MOXFRY60vKEXrBxxFvS:bkqo1z) ([raw file](https://github.com/tensorflow/tfjs/blob/d40e391a82dae3450a696e745d4a1c3953799539/tfjs-core/cloudbuild.yml#L68)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you might need to update the cloudbuild test golden file
</blockquote></details>

Yep, definitely. Nice catch!

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4399)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Pull request merged**
