### PR TITLE
Support transpose product for WebGL's batchMatMul

### PR DESCRIPTION
**Pull request by Linchenn**
WebGL's batchMatMulImpl has parameters `transposeA` and `transposeB`, and this PR is trying to add one more parameter `transposeProduct`, because transposing the `product` of `a` and `b` within the shader program, `batchMatMul(a, b, transposeProduct=true)`, is more efficient than separately calling `batchMatMul(a, b)` and `transpose(product)`.

This PR theoretically could help improve WebGL's fusedConv2d-NCHW computation.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6430)

### CODE REVIEW

**Comment by Linchenn** [comment]
## Explain aSwizzle and bSwizzle

Assume, batch=1, no bias and activation, and the input `a` and `b` are:

$$
\left(\begin{array}{cc} 
a_{00}.x & a_{00}.y & a_{01}.x &a_{01}.y\\
a_{00}.z & a_{00}.w & a_{01}.z & a_{01}.w\\
a_{10}.x & a_{10}.y & a_{11}.x &a_{11}.y\\
a_{10}.z & a_{10}.w & a_{11}.z & a_{11}.w
\end{array}\right)
\left(\begin{array}{cc} 
b_{00}.x & b_{00}.y & b_{01}.x &b_{01}.y\\
b_{00}.z & b_{00}.w & b_{01}.z & b_{01}.w\\
b_{10}.x & b_{10}.y & b_{11}.x &b_{11}.y\\
b_{10}.z & b_{10}.w & b_{11}.z & b_{11}.w
\end{array}\right)
$$ 

They are packed in WebGL as:

$$
\left(\begin{array}{cc} 
a_{00} & a_{01}\\
a_{10} & a_{11}
\end{array}\right)
\left(\begin{array}{cc} 
b_{00} & b_{01}\\
b_{10} & b_{11}
\end{array}\right)
$$ 

The output of batchMatMulImpl is:

$$
\left(\begin{array}{cc} 
c_{00}.x & c_{00}.y & c_{01}.x &c_{01}.y\\
c_{00}.z & c_{00}.w & c_{01}.z & c_{01}.w\\
c_{10}.x & c_{10}.y & c_{11}.x &c_{11}.y\\
c_{10}.z & c_{10}.w & c_{11}.z & c_{11}.w
\end{array}\right)
$$ 

It will be packed as:

$$
\left(\begin{array}{cc} 
c_{00} & c_{01}\\
c_{10} & c_{11}
\end{array}\right)
$$

The [aSwizzle and bSwizzle](https://github.com/tensorflow/tfjs/pull/6430/files#diff-ae73f9d8e507323398a73f338b6cba08e197afddf6595e7d9ab20161dcd526a1R41-R51) represent how the sampled pixel from `A` and the sampled pixel from `B` contribute to the current output pixel. To help you understand [aSwizzle and bSwizzle](https://github.com/tensorflow/tfjs/pull/6430/files#diff-ae73f9d8e507323398a73f338b6cba08e197afddf6595e7d9ab20161dcd526a1R41-R51) in this PR, the following cases would take how pixel  $a_{00}$ and pixel $b_{00}$ contribute to pixel $c_{00}$


### Case1: transposeA, transposeB, transposeProduct = false
The pixel $c_{00}$ is expected to be (ignores the values from $a_{01}$, $a_{10}$, $b_{01}$, $b_{10}$):

$$
\left(\begin{array}{cc} 
a_{00}.x * b_{00}.x +  a_{00}.y * b_{00}.z & a_{00}.x * b_{00}.y +  a_{00}.y * b_{00}.w\\
a_{00}.z * b_{00}.x +  a_{00}.w * b_{00}.z & a_{00}.z * b_{00}.y +  a_{00}.w * b_{00}.w
\end{array}\right)
$$

In other words, it is:
```
vec4 c = a00.xxzz * b00.xyxy + a00.yyww + b00.zwzw
```
This is corresponding to:
```
aSwizzle = ['a.xxzz', 'a.yyww'];
bSwizzle = ['b.xyxy', 'b.zwzw'];
```

### Case2: transposeA, transposeB = false; transposeProduct = true

The pixel $c_{00}$ just transposes the Case1's $c_{00}$:

$$
\left(\begin{array}{cc} 
a_{00}.x * b_{00}.x +  a_{00}.y * b_{00}.z & a_{00}.z * b_{00}.x +  a_{00}.w * b_{00}.z\\
a_{00}.x * b_{00}.y +  a_{00}.y * b_{00}.w & a_{00}.z * b_{00}.y +  a_{00}.w * b_{00}.w
\end{array}\right)
$$

Then:
```
vec4 c = a00.xzxz * b00.xxyy + a00.ywyw + b00.zzww
```
This is corresponding to:
```
aSwizzle = ['a.xzxz', 'a.ywyw'];
bSwizzle = ['b.xxyy', 'b.zzww'];
```

### Case3: transposeA = true; transposeB, transposeProduct = false
The output is expected to be the product of:

$$
\left(\begin{array}{cc} 
a_{00}.x & a_{00}.z & a_{10}.x &a_{10}.z\\
a_{00}.y & a_{00}.w & a_{10}.y & a_{10}.w\\
a_{01}.x & a_{01}.z & a_{11}.x &a_{11}.z\\
a_{01}.y & a_{01}.w & a_{11}.y & a_{11}.w
\end{array}\right)
\left(\begin{array}{cc} 
b_{00}.x & b_{00}.y & b_{01}.x &b_{01}.y\\
b_{00}.z & b_{00}.w & b_{01}.z & b_{01}.w\\
b_{10}.x & b_{10}.y & b_{11}.x &b_{11}.y\\
b_{10}.z & b_{10}.w & b_{11}.z & b_{11}.w
\end{array}\right)
$$ 

The pixel $c_{00}$ is expected to be (ignores the values from $a_{01}$, $a_{10}$, $b_{01}$, $b_{10}$):

$$
\left(\begin{array}{cc} 
a_{00}.x * b_{00}.x +  a_{00}.z * b_{00}.z & a_{00}.x * b_{00}.y +  a_{00}.z * b_{00}.w\\
a_{00}.y * b_{00}.x +  a_{00}.w * b_{00}.z & a_{00}.y * b_{00}.y +  a_{00}.w * b_{00}.w
\end{array}\right)
$$

In other words, it is:
```
vec4 c = a00.xxyy * b00.xyxy + a00.zzww + b00.zwzw
```
This is corresponding to:
```
aSwizzle = ['a.xxyy', 'a.zzww'];
bSwizzle = ['b.xyxy', 'b.zwzw'];
```

### Case4: transposeA, transposeProduct = true; transposeB = false

The pixel $c_{00}$ just transposes the Case3's $c_{00}$:

$$
\left(\begin{array}{cc} 
a_{00}.x * b_{00}.x +  a_{00}.z * b_{00}.z & a_{00}.y * b_{00}.x +  a_{00}.w * b_{00}.z\\
a_{00}.x * b_{00}.y +  a_{00}.z * b_{00}.w & a_{00}.y * b_{00}.y +  a_{00}.w * b_{00}.w
\end{array}\right)
$$

Then:
```
vec4 c = a00.xyxy * b00.xxyy + a00.zwzw + b00.zzww
```
This is corresponding to:
```
aSwizzle = ['a.xyxy', 'a.zwzw'];
bSwizzle = ['b.xxyy', 'b.zzww'];
```

**Comment by Linchenn** [comment]
## Explain aSwizzle and bSwizzle

Assume, batch=1, no bias and activation, and the input `a` and `b` are:

$$
\left(\begin{array}{cc} 
a_{00}.x & a_{00}.y & a_{01}.x &a_{01}.y\\
a_{00}.z & a_{00}.w & a_{01}.z & a_{01}.w\\
a_{10}.x & a_{10}.y & a_{11}.x &a_{11}.y\\
a_{10}.z & a_{10}.w & a_{11}.z & a_{11}.w
\end{array}\right)
\left(\begin{array}{cc} 
b_{00}.x & b_{00}.y & b_{01}.x &b_{01}.y\\
b_{00}.z & b_{00}.w & b_{01}.z & b_{01}.w\\
b_{10}.x & b_{10}.y & b_{11}.x &b_{11}.y\\
b_{10}.z & b_{10}.w & b_{11}.z & b_{11}.w
\end{array}\right)
$$ 

They are packed in WebGL as:

$$
\left(\begin{array}{cc} 
a_{00} & a_{01}\\
a_{10} & a_{11}
\end{array}\right)
\left(\begin{array}{cc} 
b_{00} & b_{01}\\
b_{10} & b_{11}
\end{array}\right)
$$ 

The output of batchMatMulImpl is:

$$
\left(\begin{array}{cc} 
c_{00}.x & c_{00}.y & c_{01}.x &c_{01}.y\\
c_{00}.z & c_{00}.w & c_{01}.z & c_{01}.w\\
c_{10}.x & c_{10}.y & c_{11}.x &c_{11}.y\\
c_{10}.z & c_{10}.w & c_{11}.z & c_{11}.w
\end{array}\right)
$$ 

It will be packed as:

$$
\left(\begin{array}{cc} 
c_{00} & c_{01}\\
c_{10} & c_{11}
\end{array}\right)
$$

The [aSwizzle and bSwizzle](https://github.com/tensorflow/tfjs/pull/6430/files#diff-ae73f9d8e507323398a73f338b6cba08e197afddf6595e7d9ab20161dcd526a1R41-R51) represent how the sampled pixel from `A` and the sampled pixel from `B` contribute to the current output pixel. To help you understand [aSwizzle and bSwizzle](https://github.com/tensorflow/tfjs/pull/6430/files#diff-ae73f9d8e507323398a73f338b6cba08e197afddf6595e7d9ab20161dcd526a1R41-R51) in this PR, the following cases would take how pixel  $a_{00}$ and pixel $b_{00}$ contribute to pixel $c_{00}$


### Case1: transposeA, transposeB, transposeProduct = false
The pixel $c_{00}$ is expected to be (ignores the values from $a_{01}$, $a_{10}$, $b_{01}$, $b_{10}$):

$$
\left(\begin{array}{cc} 
a_{00}.x * b_{00}.x +  a_{00}.y * b_{00}.z & a_{00}.x * b_{00}.y +  a_{00}.y * b_{00}.w\\
a_{00}.z * b_{00}.x +  a_{00}.w * b_{00}.z & a_{00}.z * b_{00}.y +  a_{00}.w * b_{00}.w
\end{array}\right)
$$

In other words, it is:
```
vec4 c = a00.xxzz * b00.xyxy + a00.yyww + b00.zwzw
```
This is corresponding to:
```
aSwizzle = ['a.xxzz', 'a.yyww'];
bSwizzle = ['b.xyxy', 'b.zwzw'];
```

### Case2: transposeA, transposeB = false; transposeProduct = true

The pixel $c_{00}$ just transposes the Case1's $c_{00}$:

$$
\left(\begin{array}{cc} 
a_{00}.x * b_{00}.x +  a_{00}.y * b_{00}.z & a_{00}.z * b_{00}.x +  a_{00}.w * b_{00}.z\\
a_{00}.x * b_{00}.y +  a_{00}.y * b_{00}.w & a_{00}.z * b_{00}.y +  a_{00}.w * b_{00}.w
\end{array}\right)
$$

Then:
```
vec4 c = a00.xzxz * b00.xxyy + a00.ywyw + b00.zzww
```
This is corresponding to:
```
aSwizzle = ['a.xzxz', 'a.ywyw'];
bSwizzle = ['b.xxyy', 'b.zzww'];
```

### Case3: transposeA = true; transposeB, transposeProduct = false
The output is expected to be the product of:

$$
\left(\begin{array}{cc} 
a_{00}.x & a_{00}.z & a_{10}.x &a_{10}.z\\
a_{00}.y & a_{00}.w & a_{10}.y & a_{10}.w\\
a_{01}.x & a_{01}.z & a_{11}.x &a_{11}.z\\
a_{01}.y & a_{01}.w & a_{11}.y & a_{11}.w
\end{array}\right)
\left(\begin{array}{cc} 
b_{00}.x & b_{00}.y & b_{01}.x &b_{01}.y\\
b_{00}.z & b_{00}.w & b_{01}.z & b_{01}.w\\
b_{10}.x & b_{10}.y & b_{11}.x &b_{11}.y\\
b_{10}.z & b_{10}.w & b_{11}.z & b_{11}.w
\end{array}\right)
$$ 

The pixel $c_{00}$ is expected to be (ignores the values from $a_{01}$, $a_{10}$, $b_{01}$, $b_{10}$):

$$
\left(\begin{array}{cc} 
a_{00}.x * b_{00}.x +  a_{00}.z * b_{00}.z & a_{00}.x * b_{00}.y +  a_{00}.z * b_{00}.w\\
a_{00}.y * b_{00}.x +  a_{00}.w * b_{00}.z & a_{00}.y * b_{00}.y +  a_{00}.w * b_{00}.w
\end{array}\right)
$$

In other words, it is:
```
vec4 c = a00.xxyy * b00.xyxy + a00.zzww + b00.zwzw
```
This is corresponding to:
```
aSwizzle = ['a.xxyy', 'a.zzww'];
bSwizzle = ['b.xyxy', 'b.zwzw'];
```

### Case4: transposeA, transposeProduct = true; transposeB = false

The pixel $c_{00}$ just transposes the Case3's $c_{00}$:

$$
\left(\begin{array}{cc} 
a_{00}.x * b_{00}.x +  a_{00}.z * b_{00}.z & a_{00}.y * b_{00}.x +  a_{00}.w * b_{00}.z\\
a_{00}.x * b_{00}.y +  a_{00}.z * b_{00}.w & a_{00}.y * b_{00}.y +  a_{00}.w * b_{00}.w
\end{array}\right)
$$

Then:
```
vec4 c = a00.xyxy * b00.xxyy + a00.zwzw + b00.zzww
```
This is corresponding to:
```
aSwizzle = ['a.xyxy', 'a.zwzw'];
bSwizzle = ['b.xxyy', 'b.zzww'];
```

**Review by pyu10055 — CHANGES_REQUESTED** [review]
This is awesome, thank you for the detail explanation.  I would be great to add your comments here into the shader code.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6430#-:-N2dtyDrCpn2uObQJbv0:b-6rmy59)* status: 0 of 1 approvals obtained (waiting on @Linchenn)

___
*[`tfjs-backend-webgl/src/kernels/BatchMatMul_impl.ts` line 160 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6430#-N2dykXODIxlZ_btsEAd:-N2dykXODIxlZ_btsEAe:bvxnhd) ([raw file](https://github.com/tensorflow/tfjs/blob/7361d5c92849c6f6373583d5d3982711fa4b6342/tfjs-backend-webgl/src/kernels/BatchMatMul_impl.ts#L160)):*
> ```XML
>     if (transposeProduct) {
>       intermediates.push(out);
>       // Since, for each bacth, the product is a vector, transposing it has the
> ```

`batch`

**Review by pyu10055 — COMMENTED** [review]
cc @qjia7 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6430#-:-N2dzBcG81FN_uzv9Vb8:bww7h6n)* status: 0 of 1 approvals obtained (waiting on @Linchenn)

**Review by qjia7 — COMMENTED** [review]
It seems that your comment should be (Please also check other cases description)
### Case1: transposeA = false, transposeB = false, transposeProduct = false

This PR is great to provide a new fuse pattern `batchMatMul`|`1x1 conv2d` + `transpose` => _FusedMatMul|fusedConv2d.  If a model has such kind of pattern. We can do optimization to make it a fused one in future.

For Conv2d-NCHW optimization, in webgpu, currently, we use below method, which also doesn't need an extra transpose for the result. I suppose the perf of the two methods is similar. [https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgpu/src/kernels/Conv2D_impl.ts#L98].
1x1 conv2d(x, w) -> batchMatMulImpl(w, x, transposeA = true)
```
  const transposeA = isChannelsLast ? false : true;
  const result = batchMatMulImpl({
    a: isChannelsLast ? xReshaped : filterReshaped,
    b: isChannelsLast ? filterReshaped : xReshaped,
    transposeA,
    transposeB,
    backend,
    bias,
    activation,
    preluActivationWeights,
    leakyreluAlpha
  });
```


> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6430#-:-N2ijEHT9mwNznwyageQ:bfg37bm)* status: 0 of 1 approvals obtained (waiting on @Linchenn)

**Review by Linchenn — COMMENTED** [review]
Thank you @qjia7 ! Updated the comment.

Yeah, the two ways have similar performance for WebGL's [first branch](https://github.com/tensorflow/tfjs/blob/b53bd47e880367ae57493f0ea628abaf08db2d5d/tfjs-backend-webgl/src/kernels/Conv2D.ts#L39-L43) to compute conv2d (filter H*W is 1*1). However, this `transposeProduct` is also useful for WebGL's [second branch](https://github.com/tensorflow/tfjs/blob/b53bd47e880367ae57493f0ea628abaf08db2d5d/tfjs-backend-webgl/src/kernels/Conv2D.ts#L44-L45) (img2col), which will be implemented in the next PR.

I see WebGPU deprecated [conv2dWithIm2Col](https://github.com/tensorflow/tfjs/commit/eb4e7512b360cf298ec26f3d417ec78e7acc4efa#diff-4a37d712e90a5262e9c7a6d82b3d0b35f242e7c9df4673acbb9f13f9a5960791L122). I am curious why you deprecate it? Thank you in advance!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6430#-:-N2sUDIO8sdJXPumgEKf:b-ikrs8f)* status: 0 of 1 approvals obtained (waiting on @Linchenn)

**Review by qjia7 — COMMENTED** [review]
`conv2dWithIm2Col` means `im2Col` + `matmul`, which needs to trigger two shaders. Currently, in webgpu, we finish `im2Col` + + `matmul` in one shader, which can save some reading/writing. You can find details here https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgpu/src/conv2d_mm_webgpu.ts#L177
We still treat conv2d as a mutmul(A, B). A is treated as the result of im2Col. B is the reshaped w. So when we read data from A, for example, readA(row, col). There is a mapping from (row, col) to the coordinates of x. The snippet (NHWC) is like below:
```
    fn mm_readA(row : i32, col : i32, globalId : vec3<u32>) -> f32 {
      var batch = i32(globalId.z);
      if (row < uniforms.dimAOuter && col < uniforms.dimInner) {
      
    let inChannels = uniforms.wShape[2];
    let outWidth = uniforms.outShape[2];
    let outRow = row / outWidth;
    let outCol = row % outWidth;

    let WRow = col / (uniforms.filterDims[1] * inChannels);
    let WCol = col / inChannels % uniforms.filterDims[1];
    let xRow = outRow * uniforms.stride[0] + uniforms.dilation[0] * WRow - uniforms.pad[0];
    let xCol = outCol * uniforms.stride[1] + uniforms.dilation[1] * WCol - uniforms.pad[1];
    let xCh = col % inChannels;
    
    let coord = vec4<i32>(batch, xRow, xCol, xCh);
    
    // The bounds checking is always needed since we use it to pad zero for the
    // 'same' padding type.
    if(coordsInBounds4D(coord, uniforms.xShape)) {
      return x[getIndexFromCoords4D(coord, uniforms.xShape)];
    }
    return 0.0;
    }
    return 0.0;
    }
```
From above, you can see that we integrated im2col into the readA so that they can be in one shader. And the core function of conv2d is still a matmul.  For NCHW, it's similar, the difference is for readA, the im2col target is `w` not `x`. So we can still use the similar strategy to optimize non-1x1 conv2d.
For webgl, I think even im2col is a separate process. Theoretically, It can do the similar thing. But I think your method is also a good solution with relatively few changes:)

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6430#-:-N2scTNy4NMlRM9omQxC:b-70wfji)* status: 0 of 1 approvals obtained (waiting on @Linchenn)

**Review by qjia7 — APPROVED** [review]
:lgtm_strong: with a comment.
Please also resolve Ping's comments.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6430#-:-N2t49L40Ed-dgfhouCs:b-oa3fgc)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn)

___
*[`tfjs-backend-webgl/src/kernels/BatchMatMul_impl.ts` line 162 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6430#-N2t2tYj6kqnRYWcK0l6:-N2t2tYj6kqnRYWcK0l7:b4fp0v2) ([raw file](https://github.com/tensorflow/tfjs/blob/25fd0d8227d0c9a4875d00f85a2b0a6c4e2c6ce9/tfjs-backend-webgl/src/kernels/BatchMatMul_impl.ts#L162)):*
> ```XML
>       // Since, for each bacth, the product is a vector, transposing it has the
>       // same effect as reshaping it.
>       out = reshape({
> ```

At the end of this function, there is always a reshape to `outShape`. So is this reshape still needed?

And I didn't see the change for 1x1 conv2d to remove the extra transpose and use transposeProduct = true. So it will be done in a separate PR, right?

**Review by Linchenn — COMMENTED** [review]
Thank you Jiajia for the detailed explaination! I will do some experiments to see if WebGL has better performance by merging two shaders.

This PR only adds `transposeProduct` parameter for batchMatMul. I will update conv2d/fusedConv2d in a separate PR.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6430#-:-N2wK1bF60gBGx5rURCd:bs59r8m)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055 and @qjia7)

___
*[`tfjs-backend-webgl/src/kernels/BatchMatMul_impl.ts` line 160 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6430#-N2dykXODIxlZ_btsEAd:-N2wK-4u0xmdZ1oPX8bS:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/25fd0d8227d0c9a4875d00f85a2b0a6c4e2c6ce9/tfjs-backend-webgl/src/kernels/BatchMatMul_impl.ts#L160)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

`batch`
</blockquote></details>

Done.
___
*[`tfjs-backend-webgl/src/kernels/BatchMatMul_impl.ts` line 162 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6430#-N2t2tYj6kqnRYWcK0l6:-N2wK-McB2_un_3HVY3E:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/25fd0d8227d0c9a4875d00f85a2b0a6c4e2c6ce9/tfjs-backend-webgl/src/kernels/BatchMatMul_impl.ts#L162)):*
<details><summary><i>Previously, qjia7 (Jiajia Qin) wrote…</i></summary><blockquote>

At the end of this function, there is always a reshape to `outShape`. So is this reshape still needed?

And I didn't see the change for 1x1 conv2d to remove the extra transpose and use transposeProduct = true. So it will be done in a separate PR, right?
</blockquote></details>

Done.

**Comment by Linchenn** [comment]
Inspired by Jiajia's implementation for `1*1 conv2d`, we found we could utilize `T(A*B) = T(B) * T(A)` and it also works for multiple batches. In other words, if we want to compute batchMatMul(a=x, b=y, transposeA=false, transposeB=false, transposeProduct=true), we could simply compute `batchMatMul(a=y, b=x, transposeA=true, transposeB=true)` without implementing `transposeProduct`, even batch size is larger than 1.

I also tested this method on our target use case: `conv2dByMatMul` and `conv2dWithIm2Row` and it work (also work for multiple batches). I will implement this method in a separate PR.

Thank you @pyu10055 and @qjia7 for your efforts on this!

**Pull request closed without merging**
