### PR TITLE
e2e: Put profileMemoryAndKernelTime after measureAveragePredictTime

### PR DESCRIPTION
**Pull request by qjia7**
This PR removes the sleep time and puts profileMemoryAndKernelTime after
measureAveragePredictTime so that the sum of profiling kernel time is
close to the average CPU time. This is because that after many iterators
the CPU/GPU frequnecy has reached to the highest. And at that point to
query the kernel time, it is more reflective of the real ops time in the
model.

This PR also adds CHECK_COMPUTATION_FOR_ERRORS flag to get more accurate
profiling result when disabling it.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4929)

### CODE REVIEW

**Comment by qjia7** [comment]
@haoyunfeix @axinging @xhcao @gyagp  Please take a look, thanks.

**Review by haoyunfeix — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4929#-:-MYEocEn4Miuz4hQp7aJ:b-jbsf8z)* status: 0 of 1 approvals obtained

**Comment by qjia7** [comment]
@lina128 @jinjingforever Please take a look, thanks.

**Review by jinjingforever — APPROVED** [review]

**Comment by qjia7** [comment]
Add a small change to clear the shown message at the end profileMemoryAndKernelTime. Please take a look and help to merge it after your approval.

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4929#-:-MYLL9KbAHrGXBUg1HnV:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
