### PR TITLE
Add cache for parseNodeName

### PR DESCRIPTION
**Pull request by chunnienc**
This PR adds cache for parseNodeName - an expensive string manipulation function in graph executor. The time saved is around 2% to 3% for MobileNetV3 (tested on my laptop, may be imprecise).

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7391)

### CODE REVIEW

**Review by mattsoulanille — APPROVED** [review]
LGTM. I was going to recommend using a closure to memoize `parseNodeName` instead of adding it to `context` but it looks like you need to pass this context to other functions like `getParamValue`.

**Comment by chunnienc** [comment]
Yeah. I think the context is suitable since it covers calls from parseNodeName itself and also getTensor and getParamValue, and it associate the lifecycle of the string with the graph, so that these string keys can be gc'ed with the graph.

**Comment by Linchenn** [comment]
Thanks! I think this approach would benefit small models a lot, by introducing cache and cache lookup to avoid string operations.

Have you benchmarked some large models? For large models, the number of nodes may be significant, so I am not sure, when the cache is very large, whether the cache lookup is still faster than string operations?

**Comment by chunnienc** [comment]
> Thanks! I think this approach would benefit small models a lot, by introducing cache and cache lookup to avoid string operations.
> 
> Have you benchmarked some large models? For large models, the number of nodes may be significant, so I am not sure, when the cache is very large, whether the cache lookup is still faster than string operations?

(Discussed offline) Yes it's always faster.
Benchmark: https://jsbench.me/8eleeumdpi/1

**Review by Linchenn — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
