### PR TITLE
WebGPU: Add computeWorkGroupSizeForMatMul helper function

### PR DESCRIPTION
**Pull request by qjia7**
PERF

Bring computeWorkGroupSizeForMatMul for dynamically adjusting the work group size
based on input shapes.

See 40% improvement for input shapes with dimInner and dimBOuter both less than 192
and can't be divisible by 64.
Input: dimAOuter = 66049, dimInner = 24, dimBOuter = 48
Before: 3.546 ms
After: 2.121 ms

Tested on UHD 630.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4532)

### CODE REVIEW

**Comment by qjia7** [comment]
@kainino0x @lina128 Please take a look, thanks.

There are some shapes in MobileNet satisfied the condition. I see ~6% improvement for it.

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4532#-:-MR5wYWi0apY5LeRsou5:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @kainino0x)

**Comment by qjia7** [comment]
@kainino0x Merge it now. I will follow up them in separate PRs if you have other concerns. Thanks.

**Review by kainino0x — COMMENTED** [review]
No worries, sorry for the delay. LGTM.

**Pull request merged**
