### PR TITLE
Add deep image prior to gallery

### PR DESCRIPTION
**Pull request by RobinKa**
Link: https://warlock.ai/deepimageprior/
Source code: https://github.com/RobinKa/web-deep-image-prior
Original project page containing a descrption of the algorithm: https://dmitryulyanov.github.io/deep_image_prior

image
image

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/1801)

### CODE REVIEW

**Comment by RobinKa** [comment]
@googlebot I signed it!

**Comment by GantMan** [comment]
how many iterations should it take before you can see results?

**Comment by RobinKa** [comment]
With 512x512 and rest default settings using the cat sample image and inpainting it takes around 15 iterations to become decent. Here's an image showing this:


image

It depends on the task but usually after 20 iterations the results should be decent.

**Comment by nsthorat** [comment]
Is this your project? On the demo it would be good to have a quick paragraph about how to use the tool. I got a little confused :)

Once you do that I can merge this!

**Comment by jenperson** [comment]
Thank you for your contribution! It looks like a description was not added to the demo, so this PR is being closed. If you are still interested in adding your project to the gallery, please update the demo to include a description.

**Pull request closed without merging**
