### PR TITLE
Improve release prompt.

### PR DESCRIPTION
**Pull request by lina128**
Because the release e2e doesn't run the whole unit tests, only the commit from a successful nightly build guarantees the unit tests all pass.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3923)

### CODE REVIEW

**Comment by tafsiri** [comment]
Sorry I missed this earlier. About picking a commit, isn't it more important that the release PR itself passes? I'm under the assumption that it runs everything nightly does and more. The last successful nightly commit is still a good candidate to release though, but I just want to understand if there is a danger in picking HEAD.

**Review by lina128 — COMMENTED** [review]
Yes, there is a danger in picking HEAD. The release e2e only runs test suites in e2e folder, it doesn't run everything nightly does. Running nightly can be expensive during the day (draining Browserstack), or waiting on nightly pass is time consuming. If unit test pass for nightly, there's no reason why it doesn't pass during release. Because of these reasons, we just skip the nightly and ask to only release commit that passed nightly build.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3923#-:-MHOJsn8EKC9Jsiy4cqN:be4x3tl)* status: 0 of 1 approvals obtained (waiting on @tafsiri)

**Comment by tafsiri** [comment]
interesting. the last release test run i did took as long as I expect nightly does (unless i have a poor estimation of how long it take nightly to run). It took 56 mins

**Review by tafsiri — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3923)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @tafsiri)

**Review by lina128 — COMMENTED** [review]
The majority of the time spent in bundling and publishing packages, in terms of tests, it ran 43 tests in one holder and 14 tests in another folder. Here's the log for 2.4.0 release: https://pantheon.corp.google.com/cloud-build/builds/ccad3ec8-266e-4970-b9a3-64d999214008;step=0?project=learnjs-174218

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3923#-:-MHT9e2v0ydW4DWVwNph:b-8f45sg)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by tafsiri** [comment]
oh wow good to know!

**Pull request merged**
