### PR TITLE
chore: checkout last 5 commits

### PR DESCRIPTION
**Pull request by DanielRuf**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/274)

### CODE REVIEW

**Comment by DanielRuf** [comment]
I signed it!

**Comment by dsmilkov** [comment]
Thanks! What is the effect of this change? Does it reduce the clone time? If yes, why not checking out only the last one?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/274#-:-LC4F4knBomrRFd7LFC6:b3mza4y)*

**Comment by DanielRuf** [comment]
> Thanks! What is the effect of this change? Does it reduce the clone time?

Exactly. By default Travis clones the last 50 commits.

> If yes, why not checking out only the last one?

https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth
> Please note that if you use a depth of 1 and have a queue of jobs, Travis CI won’t build commits that are in the queue when you push a new commit.

**Comment by dsmilkov** [comment]
:lgtm_strong: Thank you and sorry for the delay. I was traveling. There is a merge conflict, after which I'm happy to commit this. Also, would you mind doing the same change for the other repos where we have Travis (tfjs-core, tfjs-layers, tfjs-converter)?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/274#-:-LCMYYX1CCfgGgX5odqj:b-65en1n)*

**Comment by DanielRuf** [comment]
No problem and thanks for the review. I will do the other PRs later today.

**Comment by DanielRuf** [comment]
Rebased.

I schedule the other repos for Monday probably.

**Comment by DanielRuf** [comment]
> tfjs-core, tfjs-layers, tfjs-converter

Done.

**Pull request merged**
