### PR TITLE
webgpu: Allow non-square work group size for vec4 matmul

### PR DESCRIPTION
**Pull request by qjia7**
PERF

This patch allows non-square work group size for vec4 matmul so that
the algorithm becomes more flexible to adjust the work group size.

This patch also considers if the output is a vector, we should only dispatch
one dimension and keep other dimensions as 1.

This patch also uses flat displatch layout to optimize naive conv2d.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4666)

### CODE REVIEW

**Comment by qjia7** [comment]
@haoyunfeix @xhcao @axinging Please take a look, thanks.

**Comment by haoyunfeix** [comment]
LGTM.

**Comment by qjia7** [comment]
@kainino0x @lina128 Please take a look, thanks.

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4666#-:-MUA9GJj-rqAn6qlYfN9:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @kainino0x)

**Review by kainino0x — APPROVED** [review]

**Pull request merged**
