### PR TITLE
[webgl] Texture to tensor API.

### PR DESCRIPTION
**Pull request by annxingyuan**
This fixes https://github.com/tensorflow/tfjs/issues/4080
This fixes https://github.com/tensorflow/tfjs/issues/3937

#### Changes
- Add a new method to the API: `tf.webgl.createTensorFromTexture` that allows users to create tensors from textures.
- Export methods in `gpgpu_util` that enumerate the texture properties for different environments (WebGL 1 vs 2, Float32 supported vs disabled, etc.)
- Add method to the WebGL texture manager that allows registering an externally created texture to the internal registry of textures so it can be made available for reuse just like an internally create texture.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4376)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
Thank you Ann! It would be great to provide an example or examples of usage in the doccomment of createTensorFromTexture. As someone who is not very familiar with the use case, I have below questions:
1. Is the use case to reuse a texture for other purpose, e.g. rendering, or is the use case to reuse the data in the texture for other purpose? What's the benefit, is it save data downloading time, is it reusing the canvas?
2. Is the tensor created from the texture used as input for model or a copy of the output of model?
3. Who owns the texture and who should dispose the texture, is it tfjs or the application or both (like registered in two places)?
4. What does a comprehensive usage of this api look like?

It would be great to get an answer from the doccomment.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4376#-:-MObfcqn5iwEEHqSMbXT:b-uguupk)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, @pyu10055, and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl_test.ts, line 153 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4376#-MObeDntCRFt2Zqf0Rrd:-MObeDnu1vQlgPs7g-qF:bbuesht) ([raw file](https://github.com/tensorflow/tfjs/blob/700f1aa177887503d503b90ccb774179d43cd05a/tfjs-backend-webgl/src/backend_webgl_test.ts#L153)):*
> ```XML
>         'WEBGL_RENDER_FLOAT32_ENABLED', webglRenderF32EnabledFlagSaved);
>     tf.env().set('WEBGL_PACK', webglPackedFlagSaved);
>     tf.engine().startScope();
> ```

endScope?

**Review by pyu10055 — CHANGES_REQUESTED** [review]
thank you Ann, this will be very useful for advance users. I think Na suggestions are great, we need to promote this so people are aware this is possible. 
One more question, when converting the physical shape to logical shape, are there any layout requirement when they don't match?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4376#-:-MOltKGK7RLsNX9qWsWp:b-5lkt9f)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @pyu10055, and @tafsiri)

___
*[tfjs-backend-webgl/src/webgl.ts, line 45 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4376#-MOlsuQnAM2fLDEA-YlS:-MOlsuQnAM2fLDEA-YlT:b-wmg72e) ([raw file](https://github.com/tensorflow/tfjs/blob/da88ba5911a190f6596842e319f2f36d01e54d15/tfjs-backend-webgl/src/webgl.ts#L45)):*
> ```XML
>   dtype: DataType,
>   texShapeRC: [number, number],
>   internalFormat: number,
> ```

for these three params internalFormat, textureFormat and textureType, are there enum or type to restrict the values?

**Review by annxingyuan — COMMENTED** [review]
Thanks for the feedback Ping and Na. Please take another look.

Ping - regarding your question about physical shape requirements - I added some tests wherein physicalShape !== logicalShape, and I added a description in the docs about the constraints for physical shape. Let me know if any of it is unclear.

Na - regarding your questions about usage - I added some more detail to the docs - please let me know if any of it is still unclear. 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4376#-:-MP59WCyE0gJtSlAUjjH:b-beucjs)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, @pyu10055, and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl_test.ts, line 153 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4376#-MObeDntCRFt2Zqf0Rrd:-MP59U_2Cq6qNUxViSJY:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/da88ba5911a190f6596842e319f2f36d01e54d15/tfjs-backend-webgl/src/backend_webgl_test.ts#L153)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

endScope?
</blockquote></details>

Done
___
*[tfjs-backend-webgl/src/webgl.ts, line 45 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4376#-MOlsuQnAM2fLDEA-YlS:-MP59VFn1SpMhpVaCUZe:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/da88ba5911a190f6596842e319f2f36d01e54d15/tfjs-backend-webgl/src/webgl.ts#L45)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

for these three params internalFormat, textureFormat and textureType, are there enum or type to restrict the values?
</blockquote></details>

Done

**Review by lina128 — APPROVED** [review]
Thank you for the doccomment Ann, LGTM. I have another question, is the second use case in the issue (#3937) (post-processing after tfjs computation, keep everything in gpu) fulfilled or will there be a separate PR for that or is that not feasible? https://github.com/tensorflow/tfjs/issues/3937

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4376#-:-MP6Iidk-RYhanX0YG3F:b-or4op0)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @lina128, @pyu10055, and @tafsiri)

**Comment by annxingyuan** [comment]
Hi Na - regarding the second use case of post-processing in TF.js without leaving the GPU, this is possible today as long as the model can return tensors rather than output values (e.g. `faceLandmarksDetection.estimateFaces` via the [returnTensors](https://github.com/tensorflow/tfjs-models/blob/master/face-landmarks-detection/src/mediapipe-facemesh/index.ts#L42) argument). 

In this case, the user can retrieve the texture backing the tensor by calling `MathBackendWebGL.getTexture`. This is what I'm doing in one of the newly introduced tests: https://github.com/tensorflow/tfjs/pull/4376/files#diff-9eafc72e191f4188b8e6556cb7f753645212ec3a97d0ed9f5d0fbcc97aa0f611R232

**Review by lina128 — COMMENTED** [review]
Thank you for the context Ann, this is great!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4376#-:-MPBcy4m5IzKrKcnwVhN:brrugve)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @lina128, @pyu10055, and @tafsiri)

**Review by pyu10055 — APPROVED** [review]
For tensor output, how do user get the texture handle for the tensor?

> Reviewed 4 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4376#-:-MPgJU6Q5zra6SNEXME6:b-4901sa)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

**Comment by annxingyuan** [comment]
@pyu10055 - users can retrieve the texture backing a tensor like so:

`const tex = (tf.backend() as MathBackendWebGL).getTexture(someTensor.dataId);`

**Review by pyu10055 — APPROVED** [review]
cool, is this documented somewhere, if not, would be good to add to jsdoc of this method.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4376#-:-MPjU0fz15S3IKZlJXus:b1ax0ke)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

**Comment by annxingyuan** [comment]
@pyu10055 good idea - done.

**Comment by annxingyuan** [comment]
@pyu10055 Hey Ping - sorry just getting back to this PR now. I'm trying to remember the changes we discussed making to this PR. Correct me if I'm wrong, but were we discussing adding functionality to `fromPixels` to accept a texture as input as well? If so, I was thinking about it more and it actually doesn't feel like that belongs in `fromPixels`, since the other acceptable inputs to `fromPixels` are more straightforwardly categorizable as images.

Let me know if you agree, or if there was something else we wanted to change about this PR. Otherwise I will merge it!

**Review by pyu10055 — COMMENTED** [review]
Thank you Ann, I think this is fine. One question on texture retrieval for post processing, do users need to do unpacking specifically? If so, how does the users know if the tensor is packed in the texture? Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4376#-:-MTD9Ipd-y2Xh0kSKZU-:b3v9yot)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

**Comment by annxingyuan** [comment]
Hi @pyu10055 - this change should not affect the API for downloading textures. But to answer your question, the `TextureData` associated with each dataId in the WebGL backend contains a `isPacked` property.

**Comment by markmckenna** [comment]
@annxingyuan thank you for this! We had planned to work on it but haven't been able to allocate time toward it thus far. Seeing it move into main hopefully prompts deeper interest here :)

**Comment by sebavan** [comment]
@annxingyuan This is great !!! thanks a lot

**Comment by NataliaDSmirnova** [comment]
Hi guys! 
Are there any updates about the feature? 
Does any other way to create a tensor from texture exist? 
The feature would be very useful for those who utilizes TFJS with any other WebGL-based lib in one WebGL context because it removes a necessity of redundant CPU/GPU sync.

**Comment by pyu10055** [comment]
cc @lina128

**Comment by NataliaDSmirnova** [comment]
sorry @pyu100552, I has moved my question to https://github.com/tensorflow/tfjs/issues/3937.

**Pull request merged**
