### PR TITLE
Run Verdaccio tests in nightly

### PR DESCRIPTION
**Pull request by mattsoulanille**
Currently, we run Verdaccio tests only when we do a release. Since they're only tested after choosing a release commit from nightly CI, they are often a point of failure. This PR makes them run during nightly tests, so we can identify issues with them before creating a release PR.

This PR also enables Bazel sandboxing, which fixes the rules_nodejs linker issue.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6660)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
This is awesome, do you have a log for this run?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6660#-:-N7Y6y7Q8gRgaYq-kh_X:bli7bdw)* status: 0 of 1 approvals obtained

**Comment by mattsoulanille** [comment]
The run is failing due to rules_nodejs linker issues. I'm investigating the cause of it, so I converted this PR to a draft until I've fixed the linker issues.

**Comment by mattsoulanille** [comment]
[Here's a log](https://pantheon.corp.google.com/cloud-build/builds/93d4fde6-9901-48ea-a6b6-b076422b642c?project=learnjs-174218) of nightly tests running on this branch, including the nightly verdaccio tests. It looks like it will probably pass. I'll edit this tomorrow.

**Comment by mattsoulanille** [comment]
[New run with 2 hr timeout](https://pantheon.corp.google.com/cloud-build/builds/2d6e6888-d036-401d-9a71-f16147e5e725?project=learnjs-174218).

**Review by jinjingforever — APPROVED** [review]

**Pull request merged**
