### PR TITLE
Fixed typos in documentation string.

### PR DESCRIPTION
**Pull request by shmishra99**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

### CODE REVIEW

**Review by pyu10055 — APPROVED** [review]

**Review by Linchenn — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @shmishra99 Your branch is out of date, can you please update your branch? Thank you!

**Comment by gbaned** [comment]
Hi @shmishra99 Your branch is out of date, can you please update your branch? Thank you!

**Comment by gbaned** [comment]
Hi @shmishra99 Your branch is out of date, can you please update your branch? Thank you!

**Comment by gbaned** [comment]
Hi @shmishra99 Your branch is out of date, can you please update your branch? Thank you!

**Pull request merged**
