### PR TITLE
Localize BrowserStack dependencies, add build-deps capability

### PR DESCRIPTION
**Pull request by ClaireXP**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5195)

### CODE REVIEW

**Comment by ClaireXP** [comment]
@mattsoulanille @lina128 @keithlwill

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5195)* status: 0 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/index.html, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5195#-Mbldggw6U4HAR7QBMxA:-Mbldggw6U4HAR7QBMxB:bn58lxi) ([raw file](https://github.com/tensorflow/tfjs/blob/325caecf25804b17d4aae05bae6856c13da64546/e2e/benchmarks/browserstack-benchmark/index.html#L22)):*
> ```
>         <script src="https://unpkg.com/@tensorflow/tfjs/dist/tfjs.min.js"> </script>
>         <script src="https://unpkg.com/@tensorflow/tfjs-vis/dist/tfjs-vis.umd.min.js"></script>
> ```

This is not actually loading the local versions of tfjs and tfjs-vis. unpkg.com is another content delivery network like cdnjs, so this is still loading a tfjs version from another website. What we want to do instead is to load the local version we have in `node_modules`. 

Take a look at the `runServer` function to see how `app.js` serves files. As an example,  take a look above this comment for the line
```html
<link href="./main.css" rel="stylesheet">
```
This line uses `href` to say it loads the url [localhost:8001/main.css](http://localhost:8001/main.css). When you request this url, app.js serves you the `main.css` file in the `browserstack-benchmark` directory. See if you can find the urls for the local tfjs and tfjs-vis bundles located in `node_modules` and use them instead of the unpkg urls (you can use just the part of the url after the port, 8001, like with the the `href` in the css line above).
___
*[e2e/benchmarks/browserstack-benchmark/package.json, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5195#-MblnalN-KnIOyXsaxh2:-MblnalOEX6L-JmLXYuJ:bpil7wm) ([raw file](https://github.com/tensorflow/tfjs/blob/325caecf25804b17d4aae05bae6856c13da64546/e2e/benchmarks/browserstack-benchmark/package.json#L22)):*
> ```
>     "build-deps": "yarn build-tfjs && yarn build-tfjs-vis",
>     "build-tfjs": "cd ../../../tfjs && yarn && yarn build-deps && yarn build-npm",
>     "build-tfjs-vis": "cd ../../../tfjs-vis && yarn && yarn build"
> ```
This looks great!

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5195)* status: 0 of 1 approvals obtained (waiting on @ClaireXP and @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/index.html, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5195#-Mbldggw6U4HAR7QBMxA:-MbqK-HCClfwEzbkDS-4:bnyaxy9) ([raw file](https://github.com/tensorflow/tfjs/blob/325caecf25804b17d4aae05bae6856c13da64546/e2e/benchmarks/browserstack-benchmark/index.html#L22)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>         <script src="https://unpkg.com/@tensorflow/tfjs/dist/tfjs.min.js"> </script>
>         <script src="https://unpkg.com/@tensorflow/tfjs-vis/dist/tfjs-vis.umd.min.js"></script>
> ```

This is not actually loading the local versions of tfjs and tfjs-vis. unpkg.com is another content delivery network like cdnjs, so this is still loading a tfjs version from another website. What we want to do instead is to load the local version we have in `node_modules`. 

Take a look at the `runServer` function to see how `app.js` serves files. As an example,  take a look above this comment for the line
```html
<link href="./main.css" rel="stylesheet">
```
This line uses `href` to say it loads the url [localhost:8001/main.css](http://localhost:8001/main.css). When you request this url, app.js serves you the `main.css` file in the `browserstack-benchmark` directory. See if you can find the urls for the local tfjs and tfjs-vis bundles located in `node_modules` and use them instead of the unpkg urls (you can use just the part of the url after the port, 8001, like with the the `href` in the css line above).
</blockquote></details>

With the new changes, this looks good! Thanks!
___
*[e2e/benchmarks/browserstack-benchmark/package.json, line 18 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5195#-MbqKSgNBbYYmo-e3-tI:-MbqKSgNBbYYmo-e3-tJ:b9d19wu) ([raw file](https://github.com/tensorflow/tfjs/blob/bcf4681d8c15c946e10aedf705c2e283e607d9ee/e2e/benchmarks/browserstack-benchmark/package.json#L18)):*
> ```
> ····
> ```
Looks like some extra spaces were added at the end of this line.

**Review by mattsoulanille — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5195)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/package.json, line 18 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5195#-MbqKSgNBbYYmo-e3-tI:-MbqbakC12XJ69TaO8Cn:b-85i648) ([raw file](https://github.com/tensorflow/tfjs/blob/bcf4681d8c15c946e10aedf705c2e283e607d9ee/e2e/benchmarks/browserstack-benchmark/package.json#L18)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> ····
> ```
Looks like some extra spaces were added at the end of this line.
</blockquote></details>

LGTM!

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5195#-:-MbqfIfi4py9qJBnXB7G:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
