### PR TITLE
Add tensorListConcatV2 support.

### PR DESCRIPTION
**Pull request by lina128**
Add tensorListConcatV2 support.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6351)

### CODE REVIEW

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6351)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`tfjs-converter/docs/supported_ops.md` line 99 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6351#-N0cCbRD58LN3tn5YGRa:-N0cCbRD58LN3tn5YGRb:b-6apipu) ([raw file](https://github.com/tensorflow/tfjs/blob/bcd5f5a4b5953a9c17fd50a5c870ae3f2c5ee299/tfjs-converter/docs/supported_ops.md#L99)):*
> ```Markdown
> |TensorArrayV3|TensorArrayV3|
> |TensorArrayWriteV3|TensorArrayWriteV3|
> |TensorListConcatV2|TensorListConcatV2|
> ```

Just to confirm, we only list latest version ops as supported even though in the code we still allow V1?

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6351)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[`tfjs-converter/docs/supported_ops.md` line 99 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6351#-N0cCbRD58LN3tn5YGRa:-N0cH0PKC5Y2ZIf9GxUg:b-yr9kb8) ([raw file](https://github.com/tensorflow/tfjs/blob/bcd5f5a4b5953a9c17fd50a5c870ae3f2c5ee299/tfjs-converter/docs/supported_ops.md#L99)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

Just to confirm, we only list latest version ops as supported even though in the code we still allow V1?
</blockquote></details>

we should keep the TensorListConcat op
___
*[`tfjs-converter/src/operations/executors/control_executor_test.ts` line 968 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6351#-N0cHCOLDOU1JCTewfDy:-N0cHCOLDOU1JCTewfDz:b-tenwv7) ([raw file](https://github.com/tensorflow/tfjs/blob/05a114e7d2a84f36af29e667d3397e5b5e2a57b3/tfjs-converter/src/operations/executors/control_executor_test.ts#L968)):*
> ```XML
>       });
>     });
>     describe('TensorListSplit', () => {
> ```

why the above several tests seem to have been deleted? You might need to sync to the head first.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6351)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[`tfjs-converter/docs/supported_ops.md` line 99 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6351#-N0cCbRD58LN3tn5YGRa:-N0fwsqUBJEcvZvzyf0E:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/bcd5f5a4b5953a9c17fd50a5c870ae3f2c5ee299/tfjs-converter/docs/supported_ops.md#L99)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

we should keep the TensorListConcat op
</blockquote></details>

Done.
___
*[`tfjs-converter/src/operations/executors/control_executor_test.ts` line 968 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6351#-N0cHCOLDOU1JCTewfDy:-N0fwxhb6vsF_5ugu_9d:b3gngm7) ([raw file](https://github.com/tensorflow/tfjs/blob/05a114e7d2a84f36af29e667d3397e5b5e2a57b3/tfjs-converter/src/operations/executors/control_executor_test.ts#L968)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why the above several tests seem to have been deleted? You might need to sync to the head first.
</blockquote></details>

They are nested wrong, should be in top level of the file, but was nested inside another describe. I reformatted in this same PR.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6351)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

**Pull request merged**
