### PR TITLE
[E2E] Set WebGL as baseline for pose-detection correctness test

### PR DESCRIPTION
**Pull request by haoyunfeix**
As CPU backend doesn't support on pose-detection demo, we compare results between WebGL and WebGPU backend.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5875)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
@lina128 @pyu10055 PTAL

**Comment by qjia7** [comment]
@lina128 @pyu10055 How's your opinions on this?

**Review by pyu10055 — CHANGES_REQUESTED** [review]
@lina128 do we know the reason why cpu does not support pose-detection model?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5875#-:-MqHh1AH5SzyVCFx8uKg:b-ben1en)* status: 0 of 1 approvals obtained (waiting on @haoyunfeix and @lina128)

___
*[e2e/benchmarks/local-benchmark/index.html, line 232 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5875#-MqHgrJt4j_z0CLSrTqD:-MqHgrJt4j_z0CLSrTqE:b-ywgmnp) ([raw file](https://github.com/tensorflow/tfjs/blob/e92e9aa1cac0b96dc4593309a0ab32121b3b184a/e2e/benchmarks/local-benchmark/index.html#L232)):*
> ```HTML
> 
>           let inferenceInput;
>           await showMsg('Runing on cpu');
> ```

this should be removed if the message has been shown previously.

**Comment by haoyunfeix** [comment]
Not valid, closed.

**Pull request closed without merging**
