### PR TITLE
Upgrade release docker node to 16

### PR DESCRIPTION
**Pull request by mattsoulanille**
Base the release docker off of the Debian (buster) node 16 image instead of the base Debian image.

CI presubmit runs for this PR are meaningless (they don't use the new image), so I will post nightly runs with the new image.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6076)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
[Nightly run 1](https://console.cloud.google.com/cloud-build/builds/8bee5548-911e-4f34-b93c-792f28e6d62d;step=0?project=834911136599)

**Comment by mattsoulanille** [comment]
[Nightly run 2](https://console.cloud.google.com/cloud-build/builds/ba1dfa9c-4471-486e-ba8d-78c403e83d6d?project=834911136599)

**Comment by mattsoulanille** [comment]
[Nightly run 3](https://console.cloud.google.com/cloud-build/builds/e4e35aa6-e25c-4f55-bce3-9a308d530bbd?project=834911136599)

**Comment by mattsoulanille** [comment]
[Release test](https://console.cloud.google.com/cloud-build/builds/e0b171d1-8c7b-45f3-a6a6-7693d3c74074?project=834911136599)

**Comment by mattsoulanille** [comment]
[Nightly run 4](https://console.cloud.google.com/cloud-build/builds/1e46ff14-aebf-4f42-9c6d-7e51b0341eee?project=834911136599)

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6076#-:-MuI2i2d0TunudUukUPX:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille and @pyu10055)

___
*[dockers/release-docker/Dockerfile, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6076#-MuI2m2lEyR4AoZryoQS:-MuI2m2lEyR4AoZryoQT:b-9h81uh) ([raw file](https://github.com/tensorflow/tfjs/blob/3756957adf3004bea2f454aae1a2556c83bc7024/dockers/release-docker/Dockerfile#L1)):*
> ```Dockerfile
> FROM node:lts-buster
> ```

nit: Add node version to annotation



_Code quote:_
```Dockerfile
FROM node:lts-buster
```

**Comment by mattsoulanille** [comment]
[Nightly run 5](https://console.cloud.google.com/cloud-build/builds/fffedd0c-e9ba-49a9-a1e3-872af8226cea?project=834911136599)

**Comment by mattsoulanille** [comment]
[Release test 2](https://console.cloud.google.com/cloud-build/builds/050b2913-13d1-48d3-85d0-139ed8dabdba?project=834911136599)

**Review by pyu10055 — APPROVED** [review]

**Pull request merged**
