### PR TITLE
Add iPhone 12 support for e2e browserstack benchmark

### PR DESCRIPTION
**Pull request by ClaireXP**
Added iPhone12 to broser_list compatibility.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5178)

### CODE REVIEW

**Comment by ClaireXP** [comment]
@lina128 @mattsoulanille @KeithLWill

**Review by mattsoulanille — APPROVED** [review]
Looks good to me!

**Review by lina128 — APPROVED** [review]
LGTM

**Comment by Linchenn** [comment]
Good job!

**Pull request merged**
