### PR TITLE
Strengthen frame readiness while testing fromPixels with video element

### PR DESCRIPTION
**Pull request by hujiajie**
This fixes the error in WebGPU-backed unit tests:

  OperationError: Failed to execute 'importExternalTexture' on 'GPUDevice': Failed to import texture from video element that doesn't have back resource.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6751)

### CODE REVIEW

**Comment by hujiajie** [comment]
`replaceHTMLVideoElementSource()` in tfjs-data is exempted at the moment because it cannot be built on top of the proposed utils here. It might deserve a separate PR to deal with that.

**Comment by gyagp** [comment]
Can we further simplify the usage, like "await createAndWaitForVideo(src)"? Then you may hide all the details behind this function. Also for simplicity, we may not need to support multiple sources.

**Comment by hujiajie** [comment]
The unit test removes the video element when it's finished, so for symmetry `document.body.appendChild(video)` also lives at the top level. Meanwhile, it reads the autoplay policy may cause `video.play()` to fail if the element is not yet on screen. I feel it inevitably breaks `createAndWaitForVideo()` apart.

**Review by gyagp — APPROVED** [review]
According to browserstack tests, I think it's safe to use a single function. But anyway, it's already a good improvement comparing with exsiting code, so LGTM.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6751)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)

**Review by pyu10055 — APPROVED** [review]
thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6751#-:-N9dEPG_DW9MkKngbaGf:bd5l6mr)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
