### PR TITLE
[core] ResizeBilinear add support for halfCenterPixel=True.

### PR DESCRIPTION
**Pull request by annxingyuan**
Adds support for `halfCenterPixel` being true in resizeBilinear kernel. Not implemented in WASM because XNNPACK kernel does not support halfCenterPixel being true.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4152)

### CODE REVIEW

**Review by pyu10055 — APPROVED** [review]
Thanks for fixing this. Looking at the 1.15 TF doc, seems it supports half_pixel, I think the node uses 1.15 TF core lib, does the test fail in node.js?

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4152#-:-MLhoD0MAPfm4qqlNlHe:bdkfcsg)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

**Review by tafsiri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4152)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-node/src/kernels/ResizeBilinear.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4152#-MLiVoZ4BfAp1fGmHTs_:-MLiVoZ51hdDcKeRdQLy:b-stnu3f) ([raw file](https://github.com/tensorflow/tfjs/blob/8df552c840845bae4fa0d41e3608b63cb4a6ba50/tfjs-node/src/kernels/ResizeBilinear.ts#L31)):*
> ```XML
>         args.attrs as {} as ResizeBilinearAttrs;
> 
>     if (halfPixelCenters) {
> ```

Pretty much the same question as Ping would like to know more about the error here, ops.pbtxt suggests that ResizeBilinear does support `half_pixel_centers` bool attribute.

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4152)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @tafsiri)

___
*[tfjs-node/src/kernels/ResizeBilinear.ts, line 31 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4152#-MLiVoZ4BfAp1fGmHTs_:-MLmcGNpCDhtzhCwGSYR:b-djpxqv) ([raw file](https://github.com/tensorflow/tfjs/blob/8df552c840845bae4fa0d41e3608b63cb4a6ba50/tfjs-node/src/kernels/ResizeBilinear.ts#L31)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Pretty much the same question as Ping would like to know more about the error here, ops.pbtxt suggests that ResizeBilinear does support `half_pixel_centers` bool attribute.
</blockquote></details>

Done

Thanks for the catch.

**Review by tafsiri — APPROVED** [review]
> Reviewed 6 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4152)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @tafsiri)

**Comment by rohanmuplara** [comment]
hey @annxingyuan this fix is very helpful as we were having problems with resize_bilinear differing from tfjs. Is there an way o build tensorflowjs and the converter to use this now?

**Pull request merged**
