### PR TITLE
[webgpu] Fix alignment missing for 5D and 6D

### LINKED ISSUE #6699: WebGPU fails where WebGL does not
**System information**
- TensorFlow.js installed from (npm or script link): npm
- TensorFlow.js version (use command below): 3.19.0
- Browser version: Chrome Canary
- Tensorflow.js Converter Version: 3.18.0

**Describe the current behavior**
While using `WebGL`, the model works, with `WebGPU` it fails.

**Describe the expected behavior**
Previous models (actually, also a previous iteration with a little different architecture of this model) worked perfectly with webgl.

**Standalone code to reproduce the issue**
Use https://tensorflow.github.io/tfjs/e2e/benchmarks/local-benchmark/index.html
With this model: https://drive.google.com/file/d/1PV9JQ0g0m5RJLNmrNmrLSXLCJP71oS86/view?usp=sharing
Select `webgpu` (on a supported chrome version)
and shape `1,1,256,256,3`

**Other info / logs**
Console:
```
Tint WGSL reader failure: :75:50 error: the offset of a struct member of type 'vec5' in storage class 'uniform' must be a multiple of 16 bytes, but 'start' is currently at offset 100. Consider setting @align(16) on this member
         outShapeStrides: vec4<i32>, size : i32, start : vec5, };
                                                 ^^^^^

:74:1 note: see layout of struct:
/*             align(16) size(128) */ struct Uniforms {
/* offset(  0) align( 4) size(  4) */   NAN : f32;
/* offset(  4) align( 1) size( 12) */   // -- implicit field alignment padding --;
/* offset( 16) align(16) size( 20) */   sourceShape : vec5;
/* offset( 36) align( 1) size( 12) */   // -- implicit field alignment padding --;
/* offset( 48) align(16) size( 20) */   outShape : vec5;
/* offset( 68) align( 1) size( 12) */   // -- implicit field alignment padding --;
/* offset( 80) align(16) size( 16) */   outShapeStrides : vec4<i32>;
/* offset( 96) align( 4) size(  4) */   size : i32;
/* offset(100) align( 4) size( 20) */   start : vec5;
/* offset(120) align( 1) size(  8) */   // -- implicit struct size padding --;
/*                                 */ };
struct Uniforms { NAN : f32, @align(16) sourceShape : vec5, @align(16) outShape : vec5, @align(16) 
^^^^^^

:2:3 note: and layout of struct member:
/*            align(4) size(20) */ struct vec5 {
/* offset( 0) align(4) size( 4) */   x : i32;
/* offset( 4) align(4) size( 4) */   y : i32;
/* offset( 8) align(4) size( 4) */   z : i32;
/* offset(12) align(4) size( 4) */   w : i32;
/* offset(16) align(4) size( 4) */   u : i32;
/*                              */ };
  struct vec5 {x: i32, y: i32, z: i32, w: i32, u: i32};
  ^^^^^^

:83:42 note: see declaration of variable
      @group(0) @binding(2) var<uniform> uniforms: Uniforms;
                                         ^^^^^^^^


 - While validating [ShaderModuleDescriptor "SliceProgram"]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor "SliceProgram"]).

localhost/:1 Tint WGSL reader failure: :75:50 error: the offset of a struct member of type 'vec5' in storage class 'uniform' must be a multiple of 16 bytes, but 'start' is currently at offset 100. Consider setting @align(16) on this member
         outShapeStrides: vec4<i32>, size : i32, start : vec5, };
                                                 ^^^^^

:74:1 note: see layout of struct:
/*             align(16) size(128) */ struct Uniforms {
/* offset(  0) align( 4) size(  4) */   NAN : f32;
/* offset(  4) align( 1) size( 12) */   // -- implicit field alignment padding --;
/* offset( 16) align(16) size( 20) */   sourceShape : vec5;
/* offset( 36) align( 1) size( 12) */   // -- implicit field alignment padding --;
/* offset( 48) align(16) size( 20) */   outShape : vec5;
/* offset( 68) align( 1) size( 12) */   // -- implicit field alignment padding --;
/* offset( 80) align(16) size( 16) */   outShapeStrides : vec4<i32>;
/* offset( 96) align( 4) size(  4) */   size : i32;
/* offset(100) align( 4) size( 20) */   start : vec5;
/* offset(120) align( 1) size(  8) */   // -- implicit struct size padding --;
/*                                 */ };
struct Uniforms { NAN : f32, @align(16) sourceShape : vec5, @align(16) outShape : vec5, @align(16) 
^^^^^^

:2:3 note: and layout of struct member:
/*            align(4) size(20) */ struct vec5 {
/* offset( 0) align(4) size( 4) */   x : i32;
/* offset( 4) align(4) size( 4) */   y : i32;
/* offset( 8) align(4) size( 4) */   z : i32;
/* offset(12) align(4) size( 4) */   w : i32;
/* offset(16) align(4) size( 4) */   u : i32;
/*                              */ };
  struct vec5 {x: i32, y: i32, z: i32, w: i32, u: i32};
  ^^^^^^

:83:42 note: see declaration of variable
      @group(0) @binding(2) var<uniform> uniforms: Uniforms;
                                         ^^^^^^^^


 - While validating [ShaderModuleDescriptor "SliceProgram"]
 - While calling [Device].CreateShaderModule([ShaderModuleDescriptor "SliceProgram"]).

[Invalid ShaderModule "SliceProgram"] is invalid.
 - While calling [Device].CreateComputePipeline([ComputePipelineDescriptor "SliceProgram"]).

51[Invalid ComputePipeline "SliceProgram"] is invalid.
 - While Validating GetBindGroupLayout (0) on [Invalid ComputePipeline "SliceProgram"]

51[Invalid BindGroupLayout] is invalid.
 - While validating [BindGroupDescriptor] against [Invalid BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

localhost/:1 [Invalid ShaderModule "SliceProgram"] is invalid.
 - While calling [Device].CreateComputePipeline([ComputePipelineDescriptor "SliceProgram"]).

51[Invalid ComputePipeline "SliceProgram"] is invalid.
 - While Validating GetBindGroupLayout (0) on [Invalid ComputePipeline "SliceProgram"]

51[Invalid BindGroupLayout] is invalid.
 - While validating [BindGroupDescriptor] against [Invalid BindGroupLayout]
 - While calling [Device].CreateBindGroup([BindGroupDescriptor]).

1 error(s) generated while compiling the shader:
:75:50 error: the offset of a struct member of type 'vec5' in storage class 'uniform' must be a multiple of 16 bytes, but 'start' is currently at offset 100. Consider setting @align(16) on this member
         outShapeStrides: vec4<i32>, size : i32, start : vec5, };
                                                 ^^^^^

:74:1 note: see layout of struct:
/*             align(16) size(128) */ struct Uniforms {
/* offset(  0) align( 4) size(  4) */   NAN : f32;
/* offset(  4) align( 1) size( 12) */   // -- implicit field alignment padding --;
/* offset( 16) align(16) size( 20) */   sourceShape : vec5;
/* offset( 36) align( 1) size( 12) */   // -- implicit field alignment padding --;
/* offset( 48) align(16) size( 20) */   outShape : vec5;
/* offset( 68) align( 1) size( 12) */   // -- implicit field alignment padding --;
/* offset( 80) align(16) size( 16) */   outShapeStrides : vec4<i32>;
/* offset( 96) align( 4) size(  4) */   size : i32;
/* offset(100) align( 4) size( 20) */   start : vec5;
/* offset(120) align( 1) size(  8) */   // -- implicit struct size padding --;
/*                                 */ };
struct Uniforms { NAN : f32, @align(16) sourceShape : vec5, @align(16) outShape : vec5, @align(16) 
^^^^^^

:2:3 note: and layout of struct member:
/*            align(4) size(20) */ struct vec5 {
/* offset( 0) align(4) size( 4) */   x : i32;
/* offset( 4) align(4) size( 4) */   y : i32;
/* offset( 8) align(4) size( 4) */   z : i32;
/* offset(12) align(4) size( 4) */   w : i32;
/* offset(16) align(4) size( 4) */   u : i32;
/*                              */ };
  struct vec5 {x: i32, y: i32, z: i32, w: i32, u: i32};
  ^^^^^^

:83:42 note: see declaration of variable
      @group(0) @binding(2) var<uniform> uniforms: Uniforms;
                                         ^^^^^^^^

48[Invalid ComputePipeline "SliceProgram"] is invalid.
 - While encoding [ComputePassEncoder].SetPipeline([Invalid ComputePipeline "SliceProgram"]).

localhost/:1 1 error(s) generated while compiling the shader:
:75:50 error: the offset of a struct member of type 'vec5' in storage class 'uniform' must be a multiple of 16 bytes, but 'start' is currently at offset 100. Consider setting @align(16) on this member
         outShapeStrides: vec4<i32>, size : i32, start : vec5, };
                                                 ^^^^^
...
```

### PR DESCRIPTION
**Pull request by haoyunfeix**
BUG
Fixes #6699
Use regExp to match and insert alignment to uniform declaration.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6701)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
@qjia7 @xhcao @axinging @gyagp PTAL

**Review by qjia7 — APPROVED** [review]
LGTM, thanks!

**Review by gyagp — APPROVED** [review]
LGTM

**Comment by haoyunfeix** [comment]
Use `capture groups` instead of `lookbehind assertions` in RegExp to satisfy Safari's compatibility.

**Review by qjia7 — APPROVED** [review]
Thanks for the continuous efforts on this. LGTM.

**Pull request merged**
