### PR TITLE
Revert "Build tfjs-backend-webgl with Bazel (#5339)"

### LINKED ISSUE #5418: WebGL tests are running incorrectly
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below):
- Browser version:
- Tensorflow.js Converter Version:

**Describe the current behavior**
WebGL tests are running core tests using the CPU backend, and the WebGL tests themselves are not actually being run.

**Describe the expected behavior**
WebGL runs core tests using the webgl backend and runs its own tests.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.
1. In `tfjs-backend-webgl`, run `yarn bazel run :tfjs-backend-webgl_test`.
2. Click `debug` on the Chrome window that opens.
3. Open the chrome debug tools.
4. Search for a webgl test name in the logs, e.g. `fromPixels + regular math opfromPixels + regular math op` from `webgl_ops_test.ts`. It does not appear in the logs, meaning that test was not run.
5. Open a `tfjs-core` test, e.g. `mat_mul_test.ts`, and pause in a spec. Then, look at `_tfengine.backendName`. It is `cpu`.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by mattsoulanille**
This reverts commit 86ad5e0ab69952fea3e910f2bae474a80812f6e8 and resolves conflicts. The WebGL Bazel PR had an issue that wasn't caught in code review (my bad!) that prevents tests from running correctly. Reverting it for now is likely the fastest way to unblock the next release.

Fixes #5418 
Reopens #5277 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5476)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
I fixed the issue that was causing CI to fail. `conv_packed_gpu_depthwise.ts` was using `%` instead of `imod` in a shader, and `%` is not supported in webgl1. No issues remain in this PR, so once it's merged, we can release (barring any other release blockers).

**Review by pyu10055 — COMMENTED** [review]
awesome, thank you for fixing that!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5476#-:-MgwFGVJ6sKkTUzLY9w6:bj2oiv)* status: 0 of 1 approvals obtained

**Review by pyu10055 — APPROVED** [review]

**Comment by mattsoulanille** [comment]
[New nightly run](https://console.cloud.google.com/cloud-build/builds/90e9746b-09e0-434f-b22a-ab08989ccc8e?project=834911136599)

**Comment by mattsoulanille** [comment]
Thanks for the review!

**Comment by mattsoulanille** [comment]
Nightly is failing due to strict equality checks (instead of within ε) in conv2d tests.
```
Mobile Safari 11.0 (iOS 11.2) Conv2D WebGL Implementation  webgl1 {"WEBGL_VERSION":1,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} should work when width is odd and called multiple times. FAILED
	Error: Arrays differ: actual[0] = 907.9994506835938, expected[0] = 908.
	Actual:   907.9994506835938,669,987.9999389648438,728.9995727539062,1067.999755859375,788.9998779296875,1707.9990234375,1268.9996337890625,1787.9993896484375,1328.9998779296875,1867.9991455078125,1388.9998779296875,2507.999267578125,1868.9996337890625,2587.99951171875,1928.9996337890625,2667.99853515625,1988.9986572265625.
	Expected: 908,669,988,729,1068,789,1708,1269,1788,1329,1868,1389,2508,1869,2588,1929,2668,1989. in /tmp/karma-typescript-bundle--61-wiS1AI2EeACv-.js (line 186940)
```

```
Mobile Safari 11.0 (iOS 11.2) Conv2D WebGL Implementation  webgl1 {"WEBGL_VERSION":1,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} image is packed and isChannelFirst. FAILED
	Error: Arrays differ: actual[0] = 10.999998092651367, expected[0] = 11.
	Actual:   10.999998092651367,11.999999046325684,13,20.999998092651367,21.99999237060547,22.99999237060547,30.99999237060547,32,32.999996185302734.
	Expected: 11,12,13,21,22,23,31,32,33. in /tmp/karma-typescript-bundle--61-wiS1AI2EeACv-.js (line 186940)
```

```
Mobile Safari 11.0 (iOS 11.2) Conv2D WebGL Implementation  webgl1 {"WEBGL_VERSION":1,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} image is unpacked and isChannelFirst. FAILED
	Error: Arrays differ: actual[0] = 10.999998092651367, expected[0] = 11.
	Actual:   10.999998092651367,11.999999046325684,13,20.999998092651367,21.99999237060547,22.99999237060547,30.99999237060547,32,32.999996185302734.
	Expected: 11,12,13,21,22,23,31,32,33. in /tmp/karma-typescript-bundle--61-wiS1AI2EeACv-.js (line 186940)
```

```
Mobile Safari 11.0 (iOS 11.2) Conv2D WebGL Implementation  webgl1 {"WEBGL_VERSION":1,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} image is packed and isChannelLast. FAILED
	Error: Arrays differ: actual[0] = 10.999998092651367, expected[0] = 11.
	Actual:   10.999998092651367,11.999999046325684,13,20.999998092651367,21.99999237060547,22.99999237060547,30.99999237060547,32,32.999996185302734.
	Expected: 11,12,13,21,22,23,31,32,33. in /tmp/karma-typescript-bundle--61-wiS1AI2EeACv-.js (line 186940)
```

```
Mobile Safari 11.0 (iOS 11.2) Conv2D WebGL Implementation  webgl1 {"WEBGL_VERSION":1,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} image is unpacked and isChannelLast. FAILED
	Error: Arrays differ: actual[0] = 10.999998092651367, expected[0] = 11.
	Actual:   10.999998092651367,11.999999046325684,13,20.999998092651367,21.99999237060547,22.99999237060547,30.99999237060547,32,32.999996185302734.
	Expected: 11,12,13,21,22,23,31,32,33. in /tmp/karma-typescript-bundle--61-wiS1AI2EeACv-.js (line 186940)
```

**Comment by mattsoulanille** [comment]
[Third nightly run](https://console.cloud.google.com/cloud-build/builds/b634d7e6-4b93-46b4-b484-1a5c5f99d578?project=834911136599)

**Comment by mattsoulanille** [comment]
There are still some nightly webgl failures, but it's better than not running tests, so I'm merging this.

**Pull request merged**
