### PR TITLE
Add TFDF implementation

### PR DESCRIPTION
**Pull request by ahmedsabie**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6926)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6926)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @jinjingforever)

___
*[`tfjs-tfdf/scripts/download-tfdf-web-api.sh` line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE801W58Czl-LleeliK:-NE801W58Czl-LleeliL:b9khty6) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/scripts/download-tfdf-web-api.sh#L25)):*
> ```Shell
> 
> # Download the zipped lib to the output dir.
> cd "${OUTPUT_DIR}" && { curl -O https://storage.googleapis.com/tfjs-testing/ydf-lib/ydf.zip; cd -; }
> ```

should we download tfdf web api from their github repo and with version control?
___
*[`tfjs-tfdf/src/tfdf_model.ts` line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE80ZA82YYLnwwtBuFJ:-NE80ZA82YYLnwwtBuFK:b-a5y7qe) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model.ts#L26)):*
> ```XML
> 
> /**
>  * A model representing both a TFJS graph model, and a TFDF instance.
> ```

the doc does not match the function
___
*[`tfjs-tfdf/src/tfdf_model.ts` line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE81Tfn791uMu_5rsHD:-NE81Tfo4ksbfPnZ67Km:b-63k800) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model.ts#L89)):*
> ```XML
>   }
> 
>   // Needs to be called before every inference since registerOp sets operations
> ```

why the ops implementation is not generic across models?
should these ops only depends on the input from the nodes?
___
*[`tfjs-tfdf/src/tfdf_model_test.ts` line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE82NvF9BMdttBcysBN:-NE82NvF9BMdttBcysBO:b-88m3bq) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model_test.ts#L22)):*
> ```XML
> import {loadTFDFModel, TFDFModel} from './tfdf_model';
> 
> describe('TFDFModel ', () => {
> ```

how the tests are triggered? are you using bazel build files?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6926)* status: 0 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[`tfjs-tfdf/scripts/download-tfdf-web-api.sh` line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE801W58Czl-LleeliK:-NEB67NTEKBYY7qzhN6u:b-lar1yd) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/scripts/download-tfdf-web-api.sh#L25)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should we download tfdf web api from their github repo and with version control?
</blockquote></details>

They haven't released it yet with the new API
___
*[`tfjs-tfdf/src/tfdf_model.ts` line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE81Tfn791uMu_5rsHD:-NEB6FRe3Xgtp5AXXUC_:bmp0alk) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model.ts#L89)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why the ops implementation is not generic across models?
should these ops only depends on the input from the nodes?
</blockquote></details>

The input is a path to the tensorflow asset which we can't use here so we set the asset manually
___
*[`tfjs-tfdf/src/tfdf_model_test.ts` line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE82NvF9BMdttBcysBN:-NEB6RoQ5P8Ks_tmPFOD:bcdhu82) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model_test.ts#L22)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

how the tests are triggered? are you using bazel build files?
</blockquote></details>

yes I didn't add them in the PR so its readable

**Review by jinjingforever — APPROVED** [review]

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6926)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfjs-tfdf/scripts/download-tfdf-web-api.sh` line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE801W58Czl-LleeliK:-NEH9T-bDF4Va_P3XSMI:box2qw8) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/scripts/download-tfdf-web-api.sh#L25)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

They haven't released it yet with the new API
</blockquote></details>

got it, add a TODO to indicate we need to change when the TFDF release is ready.
___
*[`tfjs-tfdf/src/tfdf_model.ts` line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE81Tfn791uMu_5rsHD:-NEHAjwF55ZxpJMTA8dA:bkz493g) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model.ts#L89)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

The input is a path to the tensorflow asset which we can't use here so we set the asset manually
</blockquote></details>

I meant the creator/inferencer/loader functions should not need to recreated on each registration, right?
even if multiple TFDF models exist at once, for example the loader function of each model will on refer to the asset variable of the owner model, and it should be isolated from each other?
I feel there is no need to re-register on each inference.

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6926)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfjs-tfdf/src/tfdf_model.ts` line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE81Tfn791uMu_5rsHD:-NEHOgdg7QMB7T2n9753:bpcu9kr) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model.ts#L89)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I meant the creator/inferencer/loader functions should not need to recreated on each registration, right?
even if multiple TFDF models exist at once, for example the loader function of each model will on refer to the asset variable of the owner model, and it should be isolated from each other?
I feel there is no need to re-register on each inference. 
</blockquote></details>

Since registerOp is global it has to be set each inference. Say we didn't do that, then if we load model A then load model B, then call inference on model A, the SimpleMLInferenceOpWithHandle function will call the inference handler of model B since it wasn't re-registered on A's inference which is incorrect.

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6926)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfjs-tfdf/src/tfdf_model.ts` line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE81Tfn791uMu_5rsHD:-NEHPs3e6yBqJJp6Ykhn:b-kqj6me) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model.ts#L89)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

Since registerOp is global it has to be set each inference. Say we didn't do that, then if we load model A then load model B, then call inference on model A, the SimpleMLInferenceOpWithHandle function will call the inference handler of model B since it wasn't re-registered on A's inference which is incorrect.
</blockquote></details>

The other way is to create a global object that holds the current running model's assets, and have the handlers refer to that global object, so before an inference we update the global object instead of re-registering. Is that what you mean by not re-registering?

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6926)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfjs-tfdf/src/tfdf_model.ts` line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE81Tfn791uMu_5rsHD:-NEJfPbs00O1mds8N4tW:b-ityb9j) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model.ts#L89)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

The other way is to create a global object that holds the current running model's assets, and have the handlers refer to that global object, so before an inference we update the global object instead of re-registering. Is that what you mean by not re-registering?
</blockquote></details>

if the ops are pure function, meaning all data needed are passed in, two model can share the same function.
If the op contains references to the model it is associated with, then it cannot be share. I hope our TFDF ops can be pure function.

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6926)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfjs-tfdf/src/tfdf_model.ts` line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE81Tfn791uMu_5rsHD:-NEN1piH5RDK2PGURc7E:b-v5ewm0) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model.ts#L89)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

if the ops are pure function, meaning all data needed are passed in, two model can share the same function.
If the op contains references to the model it is associated with, then it cannot be share. I hope our TFDF ops can be pure function.
</blockquote></details>

Its not possible to have a side effect free function since resources are by definition mutable states. Static hash table ops for example modify a shared map. I changed the implementation to have one copy of the functions, that depend on a shared variable instead

**Review by pyu10055 — APPROVED** [review]
Thanks Ahmed, this looks great.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6926#-:-NEN8ak44Jl9ypziVo7c:b-1pd2c8)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfjs-tfdf/src/tfdf_model.ts` line 89 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6926#-NE81Tfn791uMu_5rsHD:-NEN8XUBDYY8_Ux17cws:b-s47mct) ([raw file](https://github.com/tensorflow/tfjs/blob/065d3e29be902b3dced5c8b9f46820d3101418ef/tfjs-tfdf/src/tfdf_model.ts#L89)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

Its not possible to have a side effect free function since resources are by definition mutable states. Static hash table ops for example modify a shared map. I changed the implementation to have one copy of the functions, that depend on a shared variable instead
</blockquote></details>

Looks good, thanks for the improvement.

**Pull request merged**
