### PR TITLE
Update GALLERY.md

### PR DESCRIPTION
**Pull request by Mmasoud1**
For  TFJS example #5924 

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5925)

### CODE REVIEW

**Comment by Mmasoud1** [comment]
I signed for CLA, but still shows "Missing CLA"

**Comment by rthadur** [comment]
Probably you need to use the same email used for Github signup , I see your CLA looks good here

image
updating manually.

**Review by rthadur — APPROVED** [review]

**Comment by rthadur** [comment]
@Mmasoud1 can you sign cla with email registered to your github id.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5925)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Mmasoud1)

___
*[GALLERY.md, line 72 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5925#-MqQHP1DDR-DsZM1wMw_:-MqQHP1E7K5_720ZSBVv:b-30iwoa) ([raw file](https://github.com/tensorflow/tfjs/blob/8afbf92b651b3d0faace350118812a2d74563cf2/GALLERY.md#L72)):*
> ```Markdown
> - [audiate](https://cjbayron.github.io/audiate/) - Ear training game using Pitch Transcription model in the browser - By CJ Bayron [[demo](https://www.youtube.com/watch?v=VZ3i4V7i7Iw&t=2s)][[repo](https://github.com/cjbayron/audiate)]
> - [Plant AI](https://github.com/Rishit-dagli/Greenathon-Plant-AI) - This web app identifies diseases in plants across 38 healthy and unhealthy plant categories by species and diseases all in the browser - By Rishit Dagli, Rishabh Singh and Rucha Yagnik. [[demo](https://www.plant-ai.tech/)][[repo](https://github.com/Rishit-dagli/Greenathon-Plant-AI)]
> - [Brainchop.org](www.brainchop.org) - Brings automatic 3D MRI segmentation  capability to neuroimaging  by running a deep learning model in the web-browser on the user side.  - By Mohamed Masoud and Sergey Plis. [[demo](www.brainchop.org)][[repo](https://github.com/neuroneural/neuroneural.github.io)][[wiki](https://github.com/neuroneural/neuroneural.github.io/wiki)]
> ```

thanks, please clean up the spaces

**Review by Mmasoud1 — COMMENTED** [review]
Thank you

**Comment by Mmasoud1** [comment]
> @Mmasoud1 can you sign cla with email registered to your github id.

Done.

**Review by Mmasoud1 — COMMENTED** [review]
Ok

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5925)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Mmasoud1)

___
*[GALLERY.md, line 72 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5925#-MqQHP1DDR-DsZM1wMw_:-MqR4tbh-77dlLEla9kE:b-fagljb) ([raw file](https://github.com/tensorflow/tfjs/blob/8afbf92b651b3d0faace350118812a2d74563cf2/GALLERY.md#L72)):*
> ```
> segmentation  capability 
> ```
There are some double spacing with the sentence, for example between `segmentation` and `capability`

**Pull request closed without merging**
