### PR TITLE
[browserstack benchmark tool] Use stream to write to outfile

### PR DESCRIPTION
**Pull request by Linchenn**
Previously, if `outfile` is set and run benchmarks for multiple models, the output file records the benchmark results only for the last one model, because the program keeps overwriting the output file.

This PR:
1. Adds initialize writing and finalize writing functions for writing output files. (Adds `Ctrl+C` listener to make sure `finalize writing function` is always executed.)
2. Use `JSONStream` to append benchmark results whenever receiving results from BrowserStack.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6750)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
Great job identifying the hard to find bug and fix it! LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6750#-:-N9Iykrd1YSuIuqxETSR:b-47oj9b)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6750)* status: :shipit: complete! 2 of 1 approvals obtained

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6750)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @Linchenn)

___
*[`e2e/benchmarks/browserstack-benchmark/app.js` line 400 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6750#-N9dDmVxA2c27rTYcvzv:-N9dDmVxA2c27rTYcvzw:br53q9d) ([raw file](https://github.com/tensorflow/tfjs/blob/7636e2081b68b097c8e7a4ade81cce0070948b1f/e2e/benchmarks/browserstack-benchmark/app.js#L400)):*
> ```JavaScript
>   let file;
>    if (cliArgs?.outfile === 'html') {
>      await fs.writeFile('./benchmark_results.js', 'const a = ', 'utf8', err => {
> ```

why writing `const a =` to the file?

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6750)* status: :shipit: complete! 2 of 1 approvals obtained

**Review by Linchenn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6750)* status: :shipit: complete! 2 of 1 approvals obtained

___
*[`e2e/benchmarks/browserstack-benchmark/app.js` line 400 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6750#-N9dDmVxA2c27rTYcvzv:-N9dHJEZ17RiAnJ_o-Mq:b-t8v1na) ([raw file](https://github.com/tensorflow/tfjs/blob/7636e2081b68b097c8e7a4ade81cce0070948b1f/e2e/benchmarks/browserstack-benchmark/app.js#L400)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why writing `const a =` to the file?
</blockquote></details>

This has been updated to `const benchmarkResults = `.

**Pull request merged**
