### PR TITLE
Add kernel SparseSegmentSum for CPU and WebGL backend

### PR DESCRIPTION
**Pull request by ahmedsabie**
ref #4838
TensorFlow python version is defined  [here](https://www.tensorflow.org/api_docs/python/tf/sparse/segment_sum)
c++ kernel definition (SparseSegmentReductionSumOp) is  [here](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/core/kernels/segment_reduction_ops_impl.h)

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5018)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thanks, great work!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5018#-:-MZf_gfeApJBGPVhI8YS:bpqfb7f)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZfXPdi-bCuo7C096TA:-MZcl58SDNGo3VNoWAKX:bwnm7r3) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts#L22)):*
> ```XML
> export function sparseSegmentReductionImpl(
>     input: TypedArray, inputShape: number[], inputDType: DataType,
>     indices: TypedArray, segmentIds: TypedArray, isMean = false,
> ```

parameters isMean is not used ?
___
*[tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts, line 61 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZf_J8h6y6BERq1O0Wl:-MZf_J8h6y6BERq1O0Wm:b-5hgye) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts#L61)):*
> ```XML
>   const outputLength =
>       outputShape.reduce((product, value) => product * value, 1);
>   const output = util.getArrayFromDType(inputDType, outputLength) as TypedArray;
> ```

Please comment that the output type array is initialized with 0 by default.
___
*[tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts, line 117 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZf_Wf78xkhfi-N1ddW:-MZf_Wf78xkhfi-N1ddX:bs4flbe) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts#L117)):*
> ```XML
>       }
>     }
>     // const badOffset =
> ```

removed here?
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum.ts, line 32 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZchSZy7UTU1c3Tipd6:-MZchSZy7UTU1c3Tipd7:bxv9f33) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum.ts#L32)):*
> ```XML
>  * // Select two rows, one segment.
>  * const result1 = tf.sparse.sparseSegmentSum(c,
>  *                                           tf.tensor1d([0, 1], 'int32),
> ```

missing right `'` across all examples
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZchccK5qwb1M4ivvhG:-MZchccK5qwb1M4ivvhH:bv9ooxu) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum.ts#L34)):*
> ```XML
>  *                                           tf.tensor1d([0, 1], 'int32),
>  *                                           tf.tensor1d([0, 0], 'int32);
>  * console.log(result1);
> ```

`console.log()` is duplicated with  tensor.print() method`
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum.ts, line 35 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZch2hWAYKQJWcGGslG:-MZch2hX5tegqTaw9JNu:b-lo6otj) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum.ts#L35)):*
> ```XML
>  *                                           tf.tensor1d([0, 0], 'int32);
>  * console.log(result1);
>  * result1['output'].print(); // [[0 0 0 0]]
> ```

the method only returns a single tensor, it should be `result1.print()` 
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum.ts, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZcht2HA2TSqhXzVloQ:-MZcht2HA2TSqhXzVloR:b-ybshte) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum.ts#L67)):*
> ```XML
>       convertToTensor(segmentIds, 'segmentIds', 'sparseSegmentSum');
> 
>   if ($data.rank < 1) {
> ```

does data need to be 2D tensor or at least 1D tensor? The jsDoc says 2D?
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts, line 38 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZciE4b5dKxDC0YYp3y:-MZciE4b5dKxDC0YYp3z:b4wjiy5) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts#L38)):*
> ```XML
> }
> 
> // function sparseTensorValue2x3x4() {
> ```

delete this method if it is not used.
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZcigrMBdfzX0V5JQ9j:-MZcigrMBdfzX0V5JQ9k:bbej2hg) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts#L69)):*
> ```XML
>     const result =
>         tf.sparse.sparseSegmentSum(TensorValue10(), [8, 3, 0, 9], [0, 1, 2, 2]);
>     expectArraysClose(await result.data(), [9, 4, 11]);
> ```

should this be [9, 4, 10]?
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts, line 148 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZcj4Xf2jfCshlDsNXN:-MZcj4Xf2jfCshlDsNXO:bdxz0v6) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts#L148)):*
> ```XML
>   });
> 
>   it('segments invalid 7', async () => {
> ```

can you add tests for invalid input ranks?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5018)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZfXPdi-bCuo7C096TA:-MZk2eJZ7bpkcsm-Jae8:bbuvx9q) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-backend-cpu/src/kernels/SparseSegmentReduction_impl.ts#L22)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

parameters isMean is not used ?
</blockquote></details>

good catch I will add it back in for the SparseSegmentMean
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum.ts, line 67 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZcht2HA2TSqhXzVloQ:-MZk2kDbAH7JYKYMDF2r:b-4al7y5) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum.ts#L67)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

does data need to be 2D tensor or at least 1D tensor? The jsDoc says 2D?
</blockquote></details>

fixed it should be at least 1D
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZcigrMBdfzX0V5JQ9j:-MZk2pEk8QewVSQTkyqY:b-nohzem) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts#L69)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should this be [9, 4, 10]?
</blockquote></details>

the array has values 1 through 10 so indices 0 and 9 in segment 2 means value is 1 + 10 i believe
___
*[tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts, line 148 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZcj4Xf2jfCshlDsNXN:-MZk2w5K2zHQBeO3sUMJ:bb7f2mf) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts#L148)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you add tests for invalid input ranks?
</blockquote></details>

done

**Review by pyu10055 — APPROVED** [review]
Thanks!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5018#-:-MZn7iJg7wob7na4fYNU:b-ucfknh)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts, line 69 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5018#-MZcigrMBdfzX0V5JQ9j:-MZn7bCD8Ks5SiIANFHz:b-q8jzb0) ([raw file](https://github.com/tensorflow/tfjs/blob/1ea3de48d8c7cc0b7540313932f9a49f4d5f3d55/tfjs-core/src/ops/sparse/sparse_segment_sum_test.ts#L69)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

the array has values 1 through 10 so indices 0 and 9 in segment 2 means value is 1 + 10 i believe
</blockquote></details>

got it

**Review by pyu10055 — COMMENTED** [review]
Looks like you need to disable the tests for WASM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5018#-:-MZn81MM7wHukpqY3FTW:b-x35i0b)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

**Pull request merged**
