### PR TITLE
Fix tfjs-core .d.ts files missing webgpu refrence types

### LINKED ISSUE #6385: Reference types missing from tensor.d.ts
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
Master tfjs branch on any system.

**Describe the current behavior**
Reference types for `@webgpu/types` are missing when compiling `tfjs-core/src/tensor.ts`. These types are necessary because #6329 added the `GPUBuffer` type to `tensor.ts`, and their absence causes downstream packages to fail to compile (#6329 passed presubmits and was merged because of #6384).

**Describe the expected behavior**

`tensor.d.ts` contains the following triple slash reference types at the top of the file:
```typescript
/// <reference types="@webgpu/types" />
```

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

`yarn bazel build //tfjs-core:tfjs-core_pkg` and then check `dist/bin/tfjs-core/tfjs-core_pkg/dist/tensor.d.ts`

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

```
tfjs-backend-wasm$ yarn build
$ rimraf dist/ && tsc && ./scripts/build-wasm.sh
../link-package-core/node_modules/@tensorflow/tfjs-core/dist/tensor.d.ts:77:14 - error TS2304: Cannot find name 'GPUBuffer'.

77     buffer?: GPUBuffer;
                ~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
```

### PR DESCRIPTION
**Pull request by mattsoulanille**
Fixes #6385

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6386)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
[Nightly run](https://pantheon.corp.google.com/cloud-build/builds/429b7d8b-c4fc-4fed-99c7-a7259f57db04?project=learnjs-174218) because PR presubmits are untrustworthy at the moment due to #6384.

**Review by lina128 — APPROVED** [review]
Thank you Matt!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6386#-:-N1f1NA75SQDQpqdQblU:b-t3m4wf)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille and @pyu10055)

___
*[`tfjs-core/src/tensor.ts` line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6386#-N1f1Jrc64ODBclCicaU:-N1f1Jrc64ODBclCicaV:b-putx1o) ([raw file](https://github.com/tensorflow/tfjs/blob/aae5d5dd92fb4dd5edd9ae46fd381784a166d64b/tfjs-core/src/tensor.ts#L18)):*
> ```XML
>  */
> 
> // Workaround for: https://github.com/bazelbuild/rules_nodejs/issues/1265
> ```

Do we need this comment here?



_Code quote:_
```XML
// Workaround for: https://github.com/bazelbuild/rules_nodejs/issues/1265
/// <reference types="@webgpu/types/dist" />
```

**Review by pyu10055 — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6386)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @mattsoulanille)

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6386)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)

___
*[`tfjs-core/src/tensor.ts` line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6386#-N1f1Jrc64ODBclCicaU:-N1f1gZs5Ln31NrBKlJi:bfpk8eh) ([raw file](https://github.com/tensorflow/tfjs/blob/aae5d5dd92fb4dd5edd9ae46fd381784a166d64b/tfjs-core/src/tensor.ts#L18)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Do we need this comment here?
</blockquote></details>

Yes. Strangely enough, the second line is actually not a comment. It's a [triple slash directive](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-types-) that tells the typescript compiler to include those types.

**Comment by mattsoulanille** [comment]
Do not merge until nightly tests pass

**Pull request merged**
