### PR TITLE
fix converter node build

### PR DESCRIPTION
**Pull request by tafsiri**
Fixes regression tests in nightly build.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3878)

### CODE REVIEW

**Comment by tafsiri** [comment]
Can confirm that this fixes e2e #REGRESSION tests.

Reverting back to regular tests.

**Review by lina128 — APPROVED** [review]
Nice catch!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3878#-:-MGJtoN52gMB_giRs3ki:b-73m6vw)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

**Comment by tafsiri** [comment]
haha, well I did introduce the bug :). Nice catch to the e2e tests!

**Review by pyu10055 — APPROVED** [review]
Thanks!

**Pull request merged**
