### PR TITLE
Fixes JSDoc display in IDEs

### PR DESCRIPTION
**Pull request by archie-swif**
Hi! 

This PR fixes a conflict in JSDoc (https://github.com/tensorflow/tfjs/issues/2542), so that IDE help popup windows show the actual docs.

webstorm-jsdoc

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3780)

### CODE REVIEW

**Comment by archie-swif** [comment]
@googlebot I signed it!

**Comment by tafsiri** [comment]
@archie-swif Thanks for doing this! And for pinging me again about reviewing. I will take a look at this before the end of the week (its just a lot of files to look at), but overall looks like the right kind of thing. We can continue discussion of this fix here. Thanks for testing this with the website build, i'll double check that and also see how it interacts with vscode.

**Comment by tafsiri** [comment]
pinging @nsthorat in case he remembers any other historical reason we couldn't combine doc annotations into the main jsdoc block (that said tscompiler has changed since then).

**Comment by nsthorat** [comment]
@tafsiri I don't remember. If the API docs build and parse correctly, this is good to go in my eyes.

**Review by tafsiri — APPROVED** [review]
@archie-swif This is a fantastic change! Thanks for taking the time to do this, a lot of people will be really happy! LGTM. Will merge after syncing to master and CI running.

> Reviewed 219 of 254 files at r1, 64 of 64 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3780#-:-MGtLNbfBz2_mN9nodwo:b97hu8r)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @tafsiri)

**Comment by archie-swif** [comment]
Thank you @tafsiri and @nsthorat!

**Pull request merged**
