### PR TITLE
Runs preconfigured BrowserStack benchmark through GCP

### PR DESCRIPTION
**Pull request by ClaireXP**
Preset to run 7 (was 3, updated to 7) benchmarks at a time-- may change depending on tests using full browser list and consistency once retry benchmark capabilities are implemented.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5323)

### CODE REVIEW

**Review by mattsoulanille — COMMENTED** [review]
This looks like it's almost ready to be merged. Feel free to ping me when it's ready and I'll take another look.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5323#-:-MeVibUe-qKY0gojBTuv:b-f8vlnb)* status: 0 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 139 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5323#-MeVfJgVE_O4oK3g8a9k:-MeVfJgVE_O4oK3g8a9l:bpokptb) ([raw file](https://github.com/tensorflow/tfjs/blob/b93d7f9676b49992f4bdffa1527a7c950b749b8f/e2e/benchmarks/browserstack-benchmark/app.js#L139)):*
> ```
>  if (cliArgs?.outfile && cliArgs.outfile) {
> ```
Optional chaining (i.e. `?.`) in `cliArgs?.outfile` is a shorthand for `cliArgs && cliArgs.outfile`. When you write `cliArgs?.outfile`, js checks if `cliArgs` exists. If it doesn't, then `cliArgs?.outfile` equals `undefined`. If `cliArgs` does exist, then `cliArgs?.outfile` equals `cliArgs.outfile`.  
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 232 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5323#-MeV_lWF92v5eJDEQuug:-MeV_lWG36MBqYKpnY3u:b-duyh17) ([raw file](https://github.com/tensorflow/tfjs/blob/b93d7f9676b49992f4bdffa1527a7c950b749b8f/e2e/benchmarks/browserstack-benchmark/app.js#L232)):*
> ```
> cloud interface
> ```
Nit (maybe?): `ci` stands for continuous integration.
___
*[e2e/benchmarks/browserstack-benchmark/cloudbuild.yml, line 10 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5323#-MeV_AT_1kH2f6z3MjWX:-MeV_AT_1kH2f6z3MjWY:b-by353u) ([raw file](https://github.com/tensorflow/tfjs/blob/b93d7f9676b49992f4bdffa1527a7c950b749b8f/e2e/benchmarks/browserstack-benchmark/cloudbuild.yml#L10)):*
> ```
> # Test.
> ```
Nit: This is not exactly a test. It's more about running the benchmarks.
___
*[e2e/benchmarks/browserstack-benchmark/package.json, line 28 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5323#-MeVZDhOBtUf290FxqZ7:-MeVZDhZ1kgq5-bnz33v:b11se60) ([raw file](https://github.com/tensorflow/tfjs/blob/b93d7f9676b49992f4bdffa1527a7c950b749b8f/e2e/benchmarks/browserstack-benchmark/package.json#L28)):*
> ```
> "test-ci": "node app.js --benchmark='./preconfigured_browser.json' --webDeps --ci --maxBenchmarks=3",
> ```
We probably shouldn't call this `test-ci` since it's less of a test and more of actually running the benchmarks. `test-ci` is used for when running unit tests requires different settings on GCP vs on your local machine (such as using browserstack for karma instead of a local browser).

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Looks good! Just one change needed before merging.

> Reviewed 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5323#-:-MeeqF6NB4Jw0gXWcCxF:bnp36v2)* status: 0 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/benchmarks/browserstack-benchmark/karma.conf.js, line 96 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5323#-MeepSQIAooPeVngjdqH:-MeepSQIAooPeVngjdqI:brq43uw) ([raw file](https://github.com/tensorflow/tfjs/blob/278256bb5aafe35a6e75251ae718465d5f3b2fcc/e2e/benchmarks/browserstack-benchmark/karma.conf.js#L96)):*
> ```
>     browserDisconnectTolerance: 2,
> ```
I forgot to mention this earlier, but we can't use browserDisconnectTolerance due to this issue:

https://github.com/karma-runner/karma/issues/3077

**Comment by ClaireXP** [comment]
@keithlwill

**Comment by ClaireXP** [comment]
Force push was to get rid of prior commit-- will work on switching cloudbuild to nightly in another PR

**Review by mattsoulanille — APPROVED** [review]
LGTM! Thanks!

> Reviewed 1 of 1 files at r4, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5323#-:-Mf3QWQ59BuF2TniaRIp:b3is8u8)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
