### PR TITLE
[converter] Support Einsum

### LINKED ISSUE #2349: Unsupported Op: Einsum
#### Describe the problem or feature request
When converting the Albert_base model, I saw:
ValueError: Unsupported Ops in the model before optimization
Einsum
#### Code to reproduce the bug
tensorflowjs_converter --signature_name tokens --input_format=tf_hub 'https://tfhub.dev/google/albert_base/2' ./web_model
@annxingyuan

### PR DESCRIPTION
**Pull request by caisq**
Towards fixing #2349 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4914)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4914)* status: 0 of 1 approvals obtained (waiting on @caisq)

___
*[tfjs-converter/src/operations/executors/matrices_executor.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4914#-MXmK1dM7ckBr4V1Rggf:-MXmK1dM7ckBr4V1Rggg:brq7twe) ([raw file](https://github.com/tensorflow/tfjs/blob/93203bed88b1eddffb35cbab05b3f04821237283/tfjs-converter/src/operations/executors/matrices_executor.ts#L34)):*
> ```XML
>         case 'BatchMatMul':
>         case 'BatchMatMulV2':
>         case 'Einsum':
> ```

I think this is fall through location for batchMatMul ops, can you move einsum after MatMul case. thanks

**Review by pyu10055 — APPROVED** [review]
Thanks one minor comment, LGTM.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4914#-:-MXmKGtx7bfdMewY0JgD:bc89j2)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @caisq)

**Review by caisq — COMMENTED** [review]
Thanks for the review, @pyu10055 ! 

I'll address your comment. But I want to do a manual test on my end with a SavedModel with einsum in it to make sure it can be converted correctly and can run correctly in the browser. Is there doc on how to do this? If not, I can try to figure it out myself based on my memory of how things worked in the past :)

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4914#-:-MXmKVrp12etglq9iBO7:b-xcfhxd)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @caisq)

**Review by caisq — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4914)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-converter/src/operations/executors/matrices_executor.ts, line 34 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4914#-MXmK1dM7ckBr4V1Rggf:-MXmLLFE9ZgPmfegrogt:b7k7pe6) ([raw file](https://github.com/tensorflow/tfjs/blob/93203bed88b1eddffb35cbab05b3f04821237283/tfjs-converter/src/operations/executors/matrices_executor.ts#L34)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I think this is fall through location for batchMatMul ops, can you move einsum after MatMul case. thanks
</blockquote></details>

Good catch. Fixed. Thanks.

**Review by pyu10055 — COMMENTED** [review]
I am not aware there is a detail description on how to make it work. but here are some basic steps:
1. load your venv with TF and go to convert python directory to 
`export PYTHONPATH=".:${PYTHONPATH}"`
2. python tensorflowjs/converters/converter.py --input_format=tf_saved_model saved_model_dir web_model
3. yarn build-npm in tfjs-converter, tfjs-core and tfjs-backend-webgl
4. create a html file that load and run the model with the js files from above package.

I think this is bit complicated, the better way might be to create a e2e test in e2e/integration_tests/convert_predict.py file

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4914#-:-MXmNM2K-PqKe2RTCDzp:bp2yx3v)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by caisq — COMMENTED** [review]
OK. Thanks! Let me try this. Please hold off merging this PR until I'm done with the testing.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4914#-:-MXmPxvKAdejim9Lvad7:b8wcjx8)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Comment by morozig** [comment]
Hello! Will it be possible to use einsum in tfjs without converter? I have a hard time implementing it myself.

**Comment by caisq** [comment]
@morozig If I understand your question correctly - after the issue is fixed and the next version of tensorflowjs is released, you will be able to use einsum from the JavaScript API directly (`tf.einsum`), without the converter.

**Comment by morozig** [comment]
@caisq thanks for your reply, that would be really great! I thought you needed to reimplement everything in js. Is it still necessary to implement layers in js, like MultiHeadAttention?

**Comment by caisq** [comment]
@morozig Depends on what users want to do. Note that the gradient of einsum is yet to be implemented in tensorflow.js Without the gradient, you won't be able to *train* any models with the einsum op in it (including models with the MultiHeadAttention layer) in *JavaScript*. The implementation of the gradient is also a big chunk of work. I don't have a plan to work on that immediately.

**Comment by morozig** [comment]
@caisq oh, I see. Thanks anyway great job!

**Pull request merged**
