### PR TITLE
Adds JAX-->TFjs converter

### PR DESCRIPTION
**Pull request by marcvanzee**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6744)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thanks Marc, can you add a section for JAX conversion in the README file  https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/README.md#python-to-javascript

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6744#-:-N9Cx9py7bUEbWBUhe9h:bkc6m5p)* status: 0 of 1 approvals obtained (waiting on @marcvanzee)

___
*[`tfjs-converter/python/requirements.txt` line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6744#-N9DW9zd5N_30bnsv16v:-N9DW9zd5N_30bnsv16w:b-eaqtqp) ([raw file](https://github.com/tensorflow/tfjs/blob/f06078f6b5cf1b6d66350ef2482066494a85ff4b/tfjs-converter/python/requirements.txt#L3)):*
> ```help
> flax>=0.5.3
> jax>=0.3.15
> importlib_resources>=5.9.0
> ```

I am wondering if the order matters, can you put importlib_resources to the top?

**Review by pyu10055 — CHANGES_REQUESTED** [review]
to run the python tests, you need to following
```
cd tfjs-converter && yarn run-python-tests
```

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6744#-:-N9FMb0K0jBspzo-Fz3J:b35xh63)* status: 0 of 1 approvals obtained (waiting on @marcvanzee)

___
*[`tfjs-converter/python/tensorflowjs/BUILD` line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6744#-N9FMCnN5GKJ-Qhxw-EC:-N9FMCnN5GKJ-Qhxw-ED:b-d7r1pi) ([raw file](https://github.com/tensorflow/tfjs/blob/f06078f6b5cf1b6d66350ef2482066494a85ff4b/tfjs-converter/python/tensorflowjs/BUILD#L53)):*
> ```Starlark
>     # We expect JAX to already be installed on the system, e.g. via
>     # `pip install jax`.
>     deps = [requirement("jax")],
> ```

add `requirement("importlib_resources")` to the deps list, this should remove the test error.
___
*[`tfjs-converter/python/tensorflowjs/converters/jax_conversion.py` line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6744#-N9FMpN59TZ1MkjuXWYJ:-N9FMpN59TZ1MkjuXWYK:b-pv275k) ([raw file](https://github.com/tensorflow/tfjs/blob/f06078f6b5cf1b6d66350ef2482066494a85ff4b/tfjs-converter/python/tensorflowjs/converters/jax_conversion.py#L22)):*
> ```Python
> from jax.experimental.jax2tf import shape_poly
> import tensorflow as tf
> from tensorflowjs.converters import convert_tf_saved_model
> ```

I am not sure about this, but importing from the __init__.py file does not seem to work with the bazel

**Review by pyu10055 — COMMENTED** [review]
The jax tests failed with a shape check
https://source.cloud.google.com/results/invocations/b8b3019a-5630-43b6-92c0-a0f15b2235c6/targets/%2F%2Ftfjs-converter%2Fpython%2Ftensorflowjs%2Fconverters:jax_conversion_test/tests;group=__main__.JaxConversionTest;test=test_convert_flax_bn;row=1

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6744#-:-N9IE566Dv01tnnmWgF-:b-dsdhhp)* status: 0 of 1 approvals obtained (waiting on @marcvanzee)

**Comment by marcvanzee** [comment]
> The jax tests failed with a shape check https://source.cloud.google.com/results/invocations/b8b3019a-5630-43b6-92c0-a0f15b2235c6/targets/%2F%2Ftfjs-converter%2Fpython%2Ftensorflowjs%2Fconverters:jax_conversion_test/tests;group=__main__.JaxConversionTest;test=test_convert_flax_bn;row=1
> 
> > Reviewed 8 of 8 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6744#-:-N9IE566Dv01tnnmWgF-:b-dsdhhp)_ status: 0 of 1 approvals obtained (waiting on @marcvanzee)

Indeed, I made a recent change to jax2tf that causes average pooling to fail, see: https://github.com/google/jax/issues/11804

I am currently working on a fix, and once that it in and JAX has rolled out a new version, we can proceed with this PR.

Apologies for the delay!

**Comment by marcvanzee** [comment]
@pyu10055 I fixed the bug and everything is passing now.
Note I am now installing JAX from the github since the fix will only be in in the next release, and they just released a new version. Is this okay with you? Given that we are writing a blog post that we want to publish soon (1-2 weeks), it would be great if we could have this code ready. I'm happy to update the import once JAX releases a new version.

**Review by pyu10055 — APPROVED** [review]
thanks I will merge this first.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6744#-:-N9dC86a4_ZMP47r52Kw:byundw3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @marcvanzee)

**Review by pyu10055 — COMMENTED** [review]
But we won't be able to release a new version of tfjs converter before the jax release is available.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6744#-:-N9dCLcdE03nh2h2cMFx:bmmpan4)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @marcvanzee)

**Review by pyu10055 — COMMENTED** [review]
the github dep is not recommended for our pip package.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6744#-:-N9dCW-sBNzTAh9n3SV7:b-37k652)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @marcvanzee)

**Review by Linchenn — APPROVED** [review]

**Comment by marcvanzee** [comment]
I will ask the JAX team when they are planning to release a new version, and if they would consider doing this soon.

**Comment by marcvanzee** [comment]
@pyu10055 after our offline discussion, I've now changed it so that we install the latest JAX release and disabled the test with a TODO. I also realized that I forgot to add content to the README, which I did as well. I also made a few minor changes to the section headers, so please take a look and make sure you are okay with it.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6744)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @marcvanzee)

**Comment by pyu10055** [comment]
Very excited about this new feature, thank you Marc!

**Pull request merged**
