### PR TITLE
allow user update the variable shape for custom model benchmark

### PR DESCRIPTION
**Pull request by pyu10055**
You can try out the demo [here](https://storage.googleapis.com/tfjs-testing/custom-shape-benchmark/benchmarks/local-benchmark/index.html) with following steps:

1. select custom model type
2. use mobilenet model https://storage.googleapis.com/learnjs-data/mobilenet_v2_100_fused/model.json
3. click benchmark button
3. update the shape with your own
4. click benchmark button again

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4161)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
Thank you Ping! Left some nit comments.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4161#-:-MKuiRxG76q8rJCz9fsB:b-xhlyjx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[e2e/benchmarks/benchmark_util.js, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKueLqP3yTd3c8KpvpL:-MKueLqP3yTd3c8KpvpM:b-j1xgka) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/benchmark_util.js#L47)):*
> ```JavaScript
>   }
> 
>   const inputDefs = model.inputs.map((inputNode, inputNodeIndex) => {
> ```

Remove unnecessary indentation.
___
*[e2e/benchmarks/benchmark_util.js, line 72 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKuegiz1HQWKdaxaMpM:-MKuegiz1HQWKdaxaMpN:b4phwet) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/benchmark_util.js#L72)):*
> ```JavaScript
>  * ```
>  *
>  * @param inputDefs The input definition that is used to generated the input.
> ```

to generate
___
*[e2e/benchmarks/benchmark_util.js, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKufXng1sQdmplkCdQA:-MKufXnh5DSryJHXma-F:b-29zu7b) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/benchmark_util.js#L73)):*
> ```JavaScript
>  *
>  * @param inputDefs The input definition that is used to generated the input.
>  * @param outputMap flag for determine output array or map of the tensors
> ```

This name is confusing. Should it be named isNamedTensorMap? Also this was a implementation detail in this method, why do we want to expose it and have another method handle the logic?
___
*[e2e/benchmarks/local-benchmark/index.html, line 303 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKugmeW-AFqI6ak7VdK:-MKugmeW-AFqI6ak7VdL:b-hm93s0) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/local-benchmark/index.html#L303)):*
> ```HTML
>               shapeInput.addEventListener('focusout', () => {
>                 state.inputs[inputIndex].shape =
>                     shapeInput.value.split(',').map(x => +x);
> ```

Do we need to trim?
___
*[e2e/benchmarks/local-benchmark/README.md, line 60 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKuhyNsBc-3EFKji5g9:-MKuhyNsBc-3EFKji5gA:b-c7ey8z) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/local-benchmark/README.md#L60)):*
> ```Markdown
> 
> ### Variable input shapes
> If input shapes for you model contain variable dimension (i.e. value = -1), you are
> ```

If input shapes for your model contain dynamic dimension (i.e. shape = [-1, -1]), you are required

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4161)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[e2e/benchmarks/benchmark_util.js, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKueLqP3yTd3c8KpvpL:-MKvKU-CDpv3slJizM7_:bot0stw) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/benchmark_util.js#L47)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Remove unnecessary indentation.
</blockquote></details>

not sure which indentation you are referring to?
___
*[e2e/benchmarks/benchmark_util.js, line 72 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKuegiz1HQWKdaxaMpM:-MKvKYGy5Wl95homPe7x:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/benchmark_util.js#L72)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

to generate
</blockquote></details>

Done.
___
*[e2e/benchmarks/benchmark_util.js, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKufXng1sQdmplkCdQA:-MKvJYio2e5xgyGUMTJt:b5ggd8c) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/benchmark_util.js#L73)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This name is confusing. Should it be named isNamedTensorMap? Also this was a implementation detail in this method, why do we want to expose it and have another method handle the logic?
</blockquote></details>

renamed to isForGraphModel, basically if generating input for GraphModel it needs to be in the map format.
___
*[e2e/benchmarks/local-benchmark/index.html, line 303 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKugmeW-AFqI6ak7VdK:-MKvFSiv--HyfBbri0OO:b-78k0pu) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/local-benchmark/index.html#L303)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Do we need to trim?
</blockquote></details>

space is handled automatically by +x
___
*[e2e/benchmarks/local-benchmark/README.md, line 60 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKuhyNsBc-3EFKji5g9:-MKvFY4O63VsZoKnDBnV:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/local-benchmark/README.md#L60)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

If input shapes for your model contain dynamic dimension (i.e. shape = [-1, -1]), you are required
</blockquote></details>

Done.

**Comment by lina128** [comment]
LGTM, thank you!

**Review by lina128 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4161)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[e2e/benchmarks/benchmark_util.js, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKueLqP3yTd3c8KpvpL:-MKvPhzl4wIKWTxx2nHL:byys4nb) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/benchmark_util.js#L47)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

not sure which indentation you are referring to?
</blockquote></details>

Ah, my mistake, looks good.

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4161)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[e2e/benchmarks/benchmark_util.js, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKueLqP3yTd3c8KpvpL:-ML6b4FXEvMvSguDn3Dr:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/benchmark_util.js#L47)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Ah, my mistake, looks good.
</blockquote></details>

Done.
___
*[e2e/benchmarks/benchmark_util.js, line 73 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKufXng1sQdmplkCdQA:-ML6b67ZEoE_5Chfu3Ne:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/benchmark_util.js#L73)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

renamed to isForGraphModel, basically if generating input for GraphModel it needs to be in the map format.
</blockquote></details>

Done.
___
*[e2e/benchmarks/local-benchmark/index.html, line 303 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4161#-MKugmeW-AFqI6ak7VdK:-ML6b7wHBEBLfLgruTvK:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/902cc11e30042f56ac2b7804bc1a692234f5b91b/e2e/benchmarks/local-benchmark/index.html#L303)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

space is handled automatically by +x
</blockquote></details>

Done.

**Pull request merged**
