### PR TITLE
Update broken link for MacOS Catalina guide in README.md

### PR DESCRIPTION
**Pull request by gaikwadrahul8**
I have updated broken link on this [page](https://github.com/tensorflow/tfjs/tree/master/tfjs-node) for `this guide` hyperlink  on this line **"For Mac OS Catalina please follow [this guide](https://github.com/nodejs/node-gyp/blob/master/macOS_Catalina.md#installing-node-gyp-using-the-xcode-command-line-tools-via-manual-download) to install node-gyp."**

I checked `node-gyp` [official documentation ](https://github.com/nodejs/node-gyp/tree/main)and it seems like they've removed `macOS_Catalina.md` file so either we can remove that hyperlink or point to the normal MacOS instructions to install `node-gyp `, What do you think please guide me on this. Thank you.

### CODE REVIEW

**Review by mattsoulanille — APPROVED** [review]

**Comment by mattsoulanille** [comment]
@pyu10055 Please take a look when you get a chance. Thanks!

**Comment by gbaned** [comment]
Hi @pyu10055 Any update on this PR? Please. Thank you!

**Review by Linchenn — APPROVED** [review]

**Comment by gbaned** [comment]
Hi @gaikwadrahul8 Can you please rebase your branch? Thank you!

**Comment by gbaned** [comment]
Hi @gaikwadrahul8 Your branch is out of date, can you please update your branch? Thank you!

**Pull request merged**
