### PR TITLE
Implement greater and greaterEqual

### PR DESCRIPTION
**Pull request by axinging**
Fix https://github.com/tensorflow/tfjs/issues/1700

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2028)

### CODE REVIEW

**Comment by math3d** [comment]
@annxingyuan PTAL.

**Comment by axinging** [comment]
@annxingyuan  PTAL.

**Comment by axinging** [comment]
Hi @annxingyuan,  I submit a fix for your comments.
But the checks reminds me that "Some checks were not successful". And I have no access right for the details failures.

**Comment by annxingyuan** [comment]
Hi @axinging - it looks like there are 2 lint errors remaining. Try running `yarn lint` in the webgpu directory. The errors are:

ERROR: (prefer-const) /workspace/tfjs-backend-webgpu/src/backend_webgpu.ts[253, 11]: Identifier 'dataAsTypedArray' is never reassigned; use 'const' instead of 'let'.

ERROR: (triple-equals) /workspace/tfjs-backend-webgpu/src/backend_webgpu.ts[269, 20]: != should be !==

One more small change request - rather than adding a class method `convertInt32ToUint8`, could you add a method to `webgpu_util` called `float32ToTypedArray` that takes the result of `this.getBufferData` and converts it appropriately? This would make the WebGPU `read` method look more like the WebGL backend. 

Thank you!

**Comment by axinging** [comment]
@annxingyuan , PTAL.
The input is ArrayBuffer, so I named it ArrayBufferToTypedArray instead of float32ToTypedArray.

**Comment by annxingyuan** [comment]
Thank you @axinging !

By the way, would you mind downloading the [clang](https://clang.llvm.org/docs/ClangFormat.html) extension to your code editor? You can find more details about the linting extensions we use here: https://github.com/tensorflow/tfjs/blob/master/DEVELOPMENT.md (see the "Code editor" section)

These tools will auto-format your code upon save according to some style guidelines we've set. This way we won't have whitespace-related changes in the future if I edit the files you created.

**Comment by axinging** [comment]
That's great! I will try.

**Pull request merged**
