### PR TITLE
[tfjs] integrate_tests: Update npm and Python dependencies

### PR DESCRIPTION
**Pull request by caisq**
- Update all tfjs-* npm dependencies to 1.2.11
- Update tf-nightly version to the latest available

DEV

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2145)

### CODE REVIEW

**Comment by caisq** [comment]
Gentle ping @annxingyuan @pyu10055 . Let's get this checked in first. There is an issue that prevents the tfjs-node-gpu benchmarks from running properly (see https://github.com/tensorflow/tfjs/issues/2156). But this PR will at least unblock the browser and tfjs-node (CPU) benchmarks.

**Comment by rthadur** [comment]
@caisq this branch is out of date , can you please update it

**Comment by caisq** [comment]
@rthadur Done. @annxingyuan @pyu10055  Ping again?

**Comment by caisq** [comment]
With the latest pushes, the benchmark script is using the latest JS and Python dependencies and both the tfjs-node and tfjs-node-gpu benchmarks are running. 

PTAL.

**Pull request merged**
