### PR TITLE
Change dependency from saved_model_cli to saved_model_utils

### PR DESCRIPTION
**Pull request by BlaziusMaximus**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7039)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Hi @blaziusmaximus Is the saved_model_cli file deprecating and recommend way is to use saved_model_utils?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7039#-:-NH14yos9MKIsNyGB5cD:b-aafswz)* status: 0 of 1 approvals obtained (waiting on @BlaziusMaximus)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 46 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7039#-NH157tJ-jBPa4yqpviL:-NH157tJ-jBPa4yqpviM:bn7ve53) ([raw file](https://github.com/tensorflow/tfjs/blob/f682a76372919dffea84c1f858626670a905b1f8/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L46)):*
> ```Python
> from tensorflow.python.saved_model.load import load
> from tensorflow.python.saved_model import loader
> from tensorflow.python.tools import saved_model_utils
> ```

`from tensorflow.python.tools.saved_model_utils import get_meta_graph_def` ?



_Code quote:_
```Python
from tensorflow.python.tools import saved_model_utils
```

**Comment by BlaziusMaximus** [comment]
Yes, exactly. See cl/487288548 for more details.

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7039)* status: 0 of 1 approvals obtained (waiting on @BlaziusMaximus)

**Review by pyu10055 — APPROVED** [review]
thanks

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7039#-:-NI-4IipDRvAjVcVfwh0:b-k73z76)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @BlaziusMaximus)

**Review by mattsoulanille — APPROVED** [review]

**Pull request merged**
