### PR TITLE
Modularize conv2D, fusedConv2D

### PR DESCRIPTION
**Pull request by lina128**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4059)

### CODE REVIEW

**Review by jinjingforever — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4059)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-cpu/src/register_all_kernels.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJTAXOZBtgltdRJveM5:-MJTAXOZBtgltdRJveM6:bpnfrhz) ([raw file](https://github.com/tensorflow/tfjs/blob/cba53d7a17bf487b91434141220afc920385cd92/tfjs-backend-cpu/src/register_all_kernels.ts#L22)):*
> ```XML
> import {KernelConfig, registerKernel} from '@tensorflow/tfjs-core';
> 
> import {_fusedConv2DConfig} from './kernels/_FusedConv2D';
> ```

Just curious: is this a convention to prefix fused op related names with "_"?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4059)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-backend-cpu/src/register_all_kernels.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJTAXOZBtgltdRJveM5:-MJVmpbL9KU0_OGiituc:b436x4x) ([raw file](https://github.com/tensorflow/tfjs/blob/cba53d7a17bf487b91434141220afc920385cd92/tfjs-backend-cpu/src/register_all_kernels.ts#L22)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

Just curious: is this a convention to prefix fused op related names with "_"?
</blockquote></details>

Hi Jing, that's a good question. I saw Yannick used the underscore for _FusedMatMul, so I follow the same pattern. I think we want to use tfName (https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/metadata/kernel2op.json#L531)  consistently, for kernel name constant and kernel file name, so that custom bundle tool can connect the dots easily. Is that right, Yannick? @tafsiri

**Review by annxingyuan — APPROVED** [review]
awesome thanks na! lgtm but curious to hear yannick's thoughts on underscores in the naming

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4059#-:-MJXG96j6G10ZRzE2-by:b9pr0rc)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/Conv2D.ts, line 36 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJXFfkc87sDD-QoqNB3:-MJXFfkc87sDD-QoqNB4:b-n43ljm) ([raw file](https://github.com/tensorflow/tfjs/blob/acf6376b83e9645ff3f52826f125723052344266/tfjs-backend-cpu/src/kernels/Conv2D.ts#L36)):*
> ```XML
>       x.shape as [number, number, number, number],
>       filter.shape as [number, number, number, number], strides, dilations, pad,
>       dimRoundingMode, false, $dataFormat);
> ```

annotate `false`
___
*[tfjs-backend-cpu/src/kernels/Conv2D.ts, line 70 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJXEGiu-cdEiTZ1Q5w_:-MJXEGiu-cdEiTZ1Q5wa:bz0mrat) ([raw file](https://github.com/tensorflow/tfjs/blob/acf6376b83e9645ff3f52826f125723052344266/tfjs-backend-cpu/src/kernels/Conv2D.ts#L70)):*
> ```XML
>       const yOffset2 = yOffset1 + yR * yRowStride;
>       const xRCorner = yR * convInfo.strideHeight - padTop;
>       for (let wR = 0; wR < filterHeight; wR++) {
> ```

maybe convert to ++wR for consistency? same with ++wC below

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4059)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever and @lina128)

___
*[tfjs-backend-cpu/src/register_all_kernels.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJTAXOZBtgltdRJveM5:-MJXuGVaD9hAEjonFCa1:b-3g83wd) ([raw file](https://github.com/tensorflow/tfjs/blob/cba53d7a17bf487b91434141220afc920385cd92/tfjs-backend-cpu/src/register_all_kernels.ts#L22)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Not exactly. _FusedMatMul already had that name so i just used it. I would say it is the exception to the pattern for naming fused ops/kernels (see the other for comparison). So I am not in favor of adding the _ here. 

With regard to custom build tooling the _ required special handling.
</blockquote></details>

Ah, got it. Why _FusedMatMul is an exception? Should we remove the underscore?

**Review by tafsiri — APPROVED** [review]
LGTM, there are just a couple of comments from Ann that may have gotten overlooked.

> Reviewed 5 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4059#-:-MJXyaKl3zpnu4i5cTxZ:bxrnk69)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @annxingyuan, @lina128, and @tafsiri)

___
*[tfjs-backend-cpu/src/register_all_kernels.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJTAXOZBtgltdRJveM5:-MJXxtg5A39t41GjdBaS:bitk5xz) ([raw file](https://github.com/tensorflow/tfjs/blob/cba53d7a17bf487b91434141220afc920385cd92/tfjs-backend-cpu/src/register_all_kernels.ts#L22)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Ah, got it. Why _FusedMatMul is an exception? Should we remove the underscore?
</blockquote></details>

I don't really know :). Good question for @annxingyuan, I would be okay with a rename to remove the underscore, but maybe there was a name collision with something (in tf/tflite)? 
___
*[tfjs-backend-cpu/src/kernels/Conv2D.ts, line 36 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJXFfkc87sDD-QoqNB3:-MJXyNKZ6IIooju8pYV2:b-2ahskb) ([raw file](https://github.com/tensorflow/tfjs/blob/acf6376b83e9645ff3f52826f125723052344266/tfjs-backend-cpu/src/kernels/Conv2D.ts#L36)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

annotate `false`
</blockquote></details>

@lina128 see Ann's comment here
___
*[tfjs-backend-cpu/src/kernels/Conv2D.ts, line 70 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJXEGiu-cdEiTZ1Q5w_:-MJXyRJu4XB-fAHvBFwi:b-2ahskb) ([raw file](https://github.com/tensorflow/tfjs/blob/acf6376b83e9645ff3f52826f125723052344266/tfjs-backend-cpu/src/kernels/Conv2D.ts#L70)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

maybe convert to ++wR for consistency? same with ++wC below
</blockquote></details>

@lina128 see Ann's comment here

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4059)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @jinjingforever and @lina128)

___
*[tfjs-backend-cpu/src/register_all_kernels.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJTAXOZBtgltdRJveM5:-MJY3x8p7HAktrljE-xl:b-sb6c9u) ([raw file](https://github.com/tensorflow/tfjs/blob/cba53d7a17bf487b91434141220afc920385cd92/tfjs-backend-cpu/src/register_all_kernels.ts#L22)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

I don't really know :). Good question for @annxingyuan, I would be okay with a rename to remove the underscore, but maybe there was a name collision with something (in tf/tflite)? 
</blockquote></details>

I would be fine with removing the underscore as long as there are no name collisions with tf! I think the original motivation was that tf has some "fused*" op names so we wanted to make sure there was no confusion.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4059)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @jinjingforever and @lina128)

___
*[tfjs-backend-cpu/src/register_all_kernels.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJTAXOZBtgltdRJveM5:-MJY6ENr-gruL2spnpUb:bfn5moy) ([raw file](https://github.com/tensorflow/tfjs/blob/cba53d7a17bf487b91434141220afc920385cd92/tfjs-backend-cpu/src/register_all_kernels.ts#L22)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

I would be fine with removing the underscore as long as there are no name collisions with tf! I think the original motivation was that tf has some "fused*" op names so we wanted to make sure there was no confusion.
</blockquote></details>

I remember that discussion! And that's when we discussed whether tfjs fused ops should have an underscore or tfjs suffix/prefix to differentiate. So what's the conclusion then?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4059)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @annxingyuan and @jinjingforever)

___
*[tfjs-backend-cpu/src/kernels/Conv2D.ts, line 36 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJXFfkc87sDD-QoqNB3:-MJY6wt_62lN0IKyQLDs:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/acf6376b83e9645ff3f52826f125723052344266/tfjs-backend-cpu/src/kernels/Conv2D.ts#L36)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

@lina128 see Ann's comment here
</blockquote></details>

Done.
___
*[tfjs-backend-cpu/src/kernels/Conv2D.ts, line 70 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJXEGiu-cdEiTZ1Q5w_:-MJY78qLAcFCu0dl-xVy:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/acf6376b83e9645ff3f52826f125723052344266/tfjs-backend-cpu/src/kernels/Conv2D.ts#L70)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

@lina128 see Ann's comment here
</blockquote></details>

Done.
___
*[tfjs-core/src/kernel_names.ts, line 821 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4059#-MJXMIgl89CYNJLs0Mmq:-MJY7Ca_-oK0jiSxi9FK:b1mm5aa) ([raw file](https://github.com/tensorflow/tfjs/blob/acf6376b83e9645ff3f52826f125723052344266/tfjs-core/src/kernel_names.ts#L821)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Let's not rename this.
</blockquote></details>

It's reverted back. Maybe reviewable didn't propagate the change? It happened frequently recently.

**Pull request merged**
