### PR TITLE
Add asset zipping functionality to TFJS converter

### PR DESCRIPTION
**Pull request by ahmedsabie**
The asset files are used for the TFDF library. Does not change behavior of existing models.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6915)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6915)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6915#-NE1fhJp60o9UEsUzBfB:-NE1fhJp60o9UEsUzBfC:besemfp) ([raw file](https://github.com/tensorflow/tfjs/blob/3d0d72fe8298c42b8f7049a05a0d3e9832f1714e/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L25)):*
> ```Python
> import shutil
> import tempfile
> from zipfile import ZipFile
> ```

does the zipfile library have any python version requirement?
___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 428 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6915#-NE1fD2l7_UQ6ItozIKm:-NE1fD2l7_UQ6ItozIKn:b-pioxgz) ([raw file](https://github.com/tensorflow/tfjs/blob/3d0d72fe8298c42b8f7049a05a0d3e9832f1714e/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L428)):*
> ```Python
>                                             saved_model.signatures.keys()))
> 
> def _copy_assets(saved_model_dir, output_dir):
> ```

should this function only trigger if the user specify the need to copy assets? (i.e. tfdf model).
This should be controlled by a parameter on the tfjs-converter command line.
___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 437 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6915#-NE1fw3Q6tz441nSAfM6:-NE1fw3Q6tz441nSAfM7:bk0jela) ([raw file](https://github.com/tensorflow/tfjs/blob/3d0d72fe8298c42b8f7049a05a0d3e9832f1714e/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L437)):*
> ```Python
> 
>     with ZipFile(zip_path, 'w') as archive:
>       for (input_dir_path, _, file_names) in tf.io.gfile.walk(input_assets_path):
> ```

does this copy nested directories too?

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6915)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6915#-NE1fhJp60o9UEsUzBfB:-NE28ScuCjvCAFShivaR:bpc9tf5) ([raw file](https://github.com/tensorflow/tfjs/blob/3d0d72fe8298c42b8f7049a05a0d3e9832f1714e/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L25)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

does the zipfile library have any python version requirement?
</blockquote></details>

No its builtin
___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 428 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6915#-NE1fD2l7_UQ6ItozIKm:-NE28ZTu3XObdDUn3_Rd:b-vk4oia) ([raw file](https://github.com/tensorflow/tfjs/blob/3d0d72fe8298c42b8f7049a05a0d3e9832f1714e/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L428)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should this function only trigger if the user specify the need to copy assets? (i.e. tfdf model).
This should be controlled by a parameter on the tfjs-converter command line.
</blockquote></details>

Assets are defined as "arbitrary files that are needed for model use". If we don't support the asset then the model wouldn't run anyways so it should never be a useless copy, and I don't think its good user experience for users to have to know that TFDF uses assets under the hood
___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 437 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6915#-NE1fw3Q6tz441nSAfM6:-NE29IE66MuQe1n8AXmX:b-hvw1wy) ([raw file](https://github.com/tensorflow/tfjs/blob/3d0d72fe8298c42b8f7049a05a0d3e9832f1714e/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L437)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

does this copy nested directories too?
</blockquote></details>

walk is recursive

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6915)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 428 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6915#-NE1fD2l7_UQ6ItozIKm:-NE2b3HO3vL4KW91Upl9:b-vo9m5c) ([raw file](https://github.com/tensorflow/tfjs/blob/3d0d72fe8298c42b8f7049a05a0d3e9832f1714e/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L428)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

Assets are defined as "arbitrary files that are needed for model use". If we don't support the asset then the model wouldn't run anyways so it should never be a useless copy, and I don't think its good user experience for users to have to know that TFDF uses assets under the hood
</blockquote></details>

good point, form the convert_tf_save_model() method perspective, it should be a parameter flag, since for non-tfdf model it should not zip the assets.

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6915)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 428 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6915#-NE1fD2l7_UQ6ItozIKm:-NE5xUOn5QGOhWY_S3oT:b-mznmtr) ([raw file](https://github.com/tensorflow/tfjs/blob/3d0d72fe8298c42b8f7049a05a0d3e9832f1714e/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L428)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

good point, form the convert_tf_save_model() method perspective, it should be a parameter flag, since for non-tfdf model it should not zip the assets.
</blockquote></details>

How about checking if the model is a TFDF model after loading and if so add the assets? That way no one calling needs to know what the model they are passing in

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6915)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 428 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6915#-NE1fD2l7_UQ6ItozIKm:-NE7hX-72CTgqaadB8LZ:b-yd7nr0) ([raw file](https://github.com/tensorflow/tfjs/blob/3d0d72fe8298c42b8f7049a05a0d3e9832f1714e/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L428)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

How about checking if the model is a TFDF model after loading and if so add the assets? That way no one calling needs to know what the model they are passing in
</blockquote></details>

agree, thanks

**Pull request merged**
