### PR TITLE
Use googleapis.com instead of tfhub.dev for models

### PR DESCRIPTION
**Pull request by axinging**
Currently most e2e read models from googleapis.com, except handdetector, handskeleton, blazeface, which use tfhub.dev.
However, for model files, tfhub.dev is redirected to googleapis.com. For example:
```
https://tfhub.dev/mediapipe/tfjs-model/handskeleton/1/default/1/model.json?tfjs-format=file
=>
https://storage.googleapis.com/tfhub-tfjs-modules/mediapipe/tfjs-model/handskeleton/1/default/1/model.json
```
So change these to googleapis.com.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5098)

### CODE REVIEW

**Comment by axinging** [comment]
@qjia7 @haoyunfeix @xhcao @gyagp PTAL

**Comment by qjia7** [comment]
No background about this. It seems that the original url is shorter. @lina128 @jinjingforever take a look, thanks.

**Review by jinjingforever — APPROVED** [review]

**Comment by axinging** [comment]
@lina128, two considerations for this changes are: 1. most use googleapis.com; 2. tfhub.dev is redirected to googleapis.com.

**Review by lina128 — COMMENTED** [review]
Does this change help your work?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5098#-:-Maaw2Go6a4xTuKkupYm:bqcwjhs)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by axinging** [comment]
> Does this change help your work?
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5098#-:-Maaw2Go6a4xTuKkupYm:bqcwjhs)_ status: :shipit: complete! 1 of 1 approvals obtained

@lina128, I think you got it, :)
Indeed we have trouble to access tfhub.dev behind certain proxy. While with googleapis.com, it is ok.

**Review by lina128 — APPROVED** [review]
Got it. Thanks for the explanation.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5098#-:-MajWvS5AFfAFFWu0tXn:b-qon1vo)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
