### PR TITLE
Add structured_outputs support in TFJS converter

### PR DESCRIPTION
**Pull request by ahmedsabie**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6559)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
thank you for implementing this important feature, should this feature be guard by a flag in the converter?
looks like the //tfjs-converter:tfjs-converter_test failed to build, might be related to python lint error for the method being too long.
you can run `pylint` in the converter python directory.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6559#-:-N5gGNKQ9wRgog_li8O2:b-w11w1n)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[`tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py` line 638 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6559#-N5gEmqXDf_6kuIfZj7t:-N5gEmqXDf_6kuIfZj7u:b-vzy9c1) ([raw file](https://github.com/tensorflow/tfjs/blob/e079c6338efd6fb4cd3546bdecb31eb339b40837/tfjs-converter/python/tensorflowjs/converters/tf_saved_model_conversion_v2.py#L638)):*
> ```Python
>   if structured_outputs is not None:
>     if type(structured_outputs) is not dict:
>       raise Exception('Converter only supports dict structured_outputs.')
> ```

should this be guarded by a flag or use a warning instead, given that not everyone would need this structured outputs?

**Review by ahmedsabie — COMMENTED** [review]
Added the flag

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6559#-:-N5l6Iy8C5tgMN4bm3z3:bfllidc)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6559)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

**Review by lina128 — APPROVED** [review]
Very useful feature, thank you Ahmed!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6559#-:-N6K_rJXECssCTfWudMj:br5a8u0)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ahmedsabie)

___
*[`tfjs-converter/src/executor/graph_model.ts` line 51 at r3](https://reviewable.io/reviews/tensorflow/tfjs/6559#-N6K_Gbr0WIxbqFNCM4T:-N6K_Gbr0WIxbqFNCM4U:bhk398i) ([raw file](https://github.com/tensorflow/tfjs/blob/44ba4f57a30b98524729b684b87a523f14686236/tfjs-converter/src/executor/graph_model.ts#L51)):*
> ```XML
>   private resourceManager: ResourceManager;
>   private signature: tensorflow.ISignatureDef;
>   private structuredOutputKeys_: string[];
> ```

nit: We don't use trailing underscore for private variable anymore, remove.



_Code quote:_
```XML
structuredOutputKeys_
```

**Pull request merged**
