### PR TITLE
Add release notes script.

### PR DESCRIPTION
**Pull request by nsthorat**
Generates a draft release notes markdown file for a release. This script
takes a start version of the union package, and optionally an end version.
It then finds the matching versions for all the dependency packages, and
finds all commit messages between those versions.

The release notes are grouped by repository, and then bucketed by a set of
tags which committers can use to organize commits into sections. See
DEVELOPMENT.md for more details on the available tags.

Usage:
```sh
   # Release notes for all commits after tfjs union version 0.9.0.
   yarn release-notes --startVersion 0.9.0 --out ./draft_notes.md

   # Release notes for all commits after version 0.9.0 up to and including
   # version 0.10.0.
   yarn release-notes --startVersion 0.9.0 --endVersion 0.10.3 --out ./draft_notes.md
```

Available tags:
- FEATURE (when new functionality / API is added)
- BREAKING (when there is API breakage)
- BUG (bug fixes)
- PERF (performance improvements)
- DEV (development flow changes)
- DOC (documentation changes)

If no tag is specified, will be put under a "MISC" tag.

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/228)

### CODE REVIEW

**Comment by nsthorat** [comment]
@ewilderj just curious what kind of commits are you thinking would go under SECURITY? We haven't really had any security-related commits lately.

**Comment by nsthorat** [comment]
Sounds good, I added the tag. Thanks!

**Comment by caisq** [comment]
Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---

*[DEVELOPMENT.md, line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/228#-LAzkKJeCNwW1zFgpJ-g:-LAzkKJeCNwW1zFgpJ-h:b-4pvar3) ([raw file](https://github.com/tensorflow/tfjs/blob/288527a1a2288a7b146eb4f4ff155d4684a6c85c/DEVELOPMENT.md#L3)):*
> ```
> tensorflow/tfjs-layers
> ```

Add github links?

---

*[DEVELOPMENT.md, line 60 at r1](https://reviewable.io/reviews/tensorflow/tfjs/228#-LAzkd6c5sffz-qMQFCC:-LAzkd6c5sffz-qMQFCD:b-k1d2s7) ([raw file](https://github.com/tensorflow/tfjs/blob/288527a1a2288a7b146eb4f4ff155d4684a6c85c/DEVELOPMENT.md#L60)):*
> ```
>  Add
> ```

nit: You sometimes use imperative (e.g., "Add") and sometimes use descriptive (e.g., "Adds") in these examples. Some authors may prefer past tense (e.g., "Added"). I think it would be good to set a standard here,  at least in these examples. It makes it easier to unify the language style in the final release notes. 

---

*[scripts/release_notes/release_notes.ts, line 30 at r1](https://reviewable.io/reviews/tensorflow/tfjs/228#-LAznmT5DW6odok-y9dH:-LAznmT5DW6odok-y9dI:bec7s0j) ([raw file](https://github.com/tensorflow/tfjs/blob/288527a1a2288a7b146eb4f4ff155d4684a6c85c/scripts/release_notes/release_notes.ts#L30)):*
> ```
> Usage:
> ```

This doc should describe what a GitHub token is, when it'll be asked for and how to get one.

---

*[scripts/release_notes/release_notes.ts, line 50 at r1](https://reviewable.io/reviews/tensorflow/tfjs/228#-LAzn2JuCFIhtoSUUJ8X:-LAzn2JuCFIhtoSUUJ8Y:b-qm0tn5) ([raw file](https://github.com/tensorflow/tfjs/blob/288527a1a2288a7b146eb4f4ff155d4684a6c85c/scripts/release_notes/release_notes.ts#L50)):*
> ```
> TMP_DIR = '/tmp/tfjs-release-notes';
> ```

Instead of this, which is risky because someone may inadvertently store something of value there, can we call `mktemp` or the equivalent of that in node.js to create a temp directory?

---

*[scripts/release_notes/run_tests.ts, line 1 at r3](https://reviewable.io/reviews/tensorflow/tfjs/228#-LAzqmuI6H-yDPXVEyCX:-LAzqmuI6H-yDPXVEyCY:b6vfnax) ([raw file](https://github.com/tensorflow/tfjs/blob/94d5fb94dd053c5edc659ef1ce2f39e57ec0ce31/scripts/release_notes/run_tests.ts#L1)):*
> ```
> #!/usr/bin/env node
> ```

Add this script to travis?

---

*[scripts/release_notes/util.ts, line 23 at r1](https://reviewable.io/reviews/tensorflow/tfjs/228#-LAzo8ln1i7dyHXtcHmy:-LAzo8ln1i7dyHXtcHmz:b-j7cx6t) ([raw file](https://github.com/tensorflow/tfjs/blob/288527a1a2288a7b146eb4f4ff155d4684a6c85c/scripts/release_notes/util.ts#L23)):*
> ```
> @param
> ```

Document @returns also.

---

*[scripts/release_notes/util.ts, line 77 at r1](https://reviewable.io/reviews/tensorflow/tfjs/228#-LAzoNoN48RtEGamjbb4:-LAzoNoN48RtEGamjbb5:b-3ajcbb) ([raw file](https://github.com/tensorflow/tfjs/blob/288527a1a2288a7b146eb4f4ff155d4684a6c85c/scripts/release_notes/util.ts#L77)):*
> ```
> getReleaseNotesDraft
> ```

Add doc string to this function.

---

*[scripts/release_notes/util.ts, line 83 at r1](https://reviewable.io/reviews/tensorflow/tfjs/228#-LAzog_J9JT2flYMSP4O:-LAzog_J9JT2flYMSP4P:bxd9ljk) ([raw file](https://github.com/tensorflow/tfjs/blob/288527a1a2288a7b146eb4f4ff155d4684a6c85c/scripts/release_notes/util.ts#L83)):*
> ```
> getUsernameForCommit
> ```
How slow is this? Is there a batch way to get the results for all commits in one request to speed things up?

---

*[scripts/release_notes/util.ts, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/228#-LAzpBH82sCLPE6RxAJa:-LAzpBH82sCLPE6RxAJb:b-mlq049) ([raw file](https://github.com/tensorflow/tfjs/blob/288527a1a2288a7b146eb4f4ff155d4684a6c85c/scripts/release_notes/util.ts#L101)):*
> ```
> line.startsWith(tag)
> ```

Probably should be `line.split(/(\s+)/)[0] === tag` to take into account the possibility of something like "DEVELOPING..." being confused as a "DEV" tag. Also, the double loop here can be simplified into one to reduce complexity.

```
const items = line.split(/(\s+)/);
if (items && items.length > 0 && SECTION_TAGS.indexOf(items[0]) !== -1) {
  // ...
  tagsFound.push([items[0], tagMessage]);
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/228)*

**Comment by caisq** [comment]
:lgtm_strong:

---

Review status: 0 of 9 files reviewed at latest revision, 9 unresolved discussions.

---

*[DEVELOPMENT.md, line 72 at r4](https://reviewable.io/reviews/tensorflow/tfjs/228#-LB22sOV2eICA30JBMmP:-LB22sOV2eICA30JBMmQ:b-3eff6b) ([raw file](https://github.com/tensorflow/tfjs/blob/9ff055b125ec591c9fe11fde405a5bce27e7aa24/DEVELOPMENT.md#L72)):*
> ```
> Improves
> ```

s/Improves/Improve/

---

*[DEVELOPMENT.md, line 79 at r4](https://reviewable.io/reviews/tensorflow/tfjs/228#-LB2312D8pqA6ZPWVlMR:-LB2312D8pqA6ZPWVlMS:b-3eff6b) ([raw file](https://github.com/tensorflow/tfjs/blob/9ff055b125ec591c9fe11fde405a5bce27e7aa24/DEVELOPMENT.md#L79)):*
> ```
> Improves
> ```

s/Improves/Improve/

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/228#-:-LB23hNK6yl4duxPv71x:b-jbsf8z)*

**Comment by dsmilkov** [comment]
:lgtm_strong:

---

Review status: 0 of 9 files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/228#-:-LB2a2V47F1dllIidMtd:b-jbsf8z)*

**Comment by nsthorat** [comment]
Review status: 0 of 9 files reviewed at latest revision, 11 unresolved discussions.

---

*[DEVELOPMENT.md, line 72 at r4](https://reviewable.io/reviews/tensorflow/tfjs/228#-LB22sOV2eICA30JBMmP:-LB6K1555hrHwcVRRtFy:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/9ff055b125ec591c9fe11fde405a5bce27e7aa24/DEVELOPMENT.md#L72)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> Improves
> ```

s/Improves/Improve/
</blockquote></details>

Done.

---

*[DEVELOPMENT.md, line 79 at r4](https://reviewable.io/reviews/tensorflow/tfjs/228#-LB2312D8pqA6ZPWVlMR:-LB6K1QY-nt-uZZk_8BN:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/9ff055b125ec591c9fe11fde405a5bce27e7aa24/DEVELOPMENT.md#L79)):*
<details><summary><i>Previously, caisq (Shanqing Cai) wrote…</i></summary><blockquote>

> ```
> Improves
> ```

s/Improves/Improve/
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/228)*

**Pull request merged**
