### PR TITLE
[tfjs-node] upgrade tensorflow deps to 2.5 and built raspberry pi 2.5 binary

### PR DESCRIPTION
**Pull request by pyu10055**
ref https://github.com/tensorflow/tfjs/issues/4514
ref https://github.com/tensorflow/tfjs/issues/5173
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5204)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5204#-:-MbluUGCBGzQuQDdPTpu:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained

**Comment by mandokid** [comment]
HI, Why not update the npm package version? the latest version is 3.7.1 that not include these change.

**Comment by lina128** [comment]
Hi @mandokid , this is published in 3.8.0: https://github.com/tensorflow/tfjs/releases/tag/tfjs-v3.8.0

**Comment by franckOL** [comment]
I try tfjs-node 3.8.0.
I always get a Wrong ELFCLASS64 error on my raspberry 3.

**Pull request merged**
