### PR TITLE
Fix CPU fusedConv2d (activation) for NCHW format

### PR DESCRIPTION
**Pull request by Linchenn**
ISSUE https://github.com/tensorflow/tfjs/issues/6368

For NCHW format, if fusedConv2d has a 1-D PReLU activation weights, CPU-backend does not apply it to the channel dimension, while currently just applying it to the last dimension of the input. 
 
This PR does:
1. For CPU-backend, properly reshape PReLU activation weights to align with the NCHW format to compute fusedConv2d
2. Moves the shape check of PReLU activation weights from WebGL-backend to tfjs-core, because this checking is general for all backends.

I have manually tested the PReLU activation logics in this PR, using the tests from the PR https://github.com/tensorflow/tfjs/pull/6373. These tests will be added when the PR https://github.com/tensorflow/tfjs/pull/6373 is merged.

@lina128 , FYI, this is the twin PR with the PR https://github.com/tensorflow/tfjs/pull/6379.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6400)

### CODE REVIEW

**Review by Linchenn — COMMENTED** [review]
Before moving the tests to tfjs-core, we have to enable tfjs-core's fusedConv2d-NCHW and ban some backend's  fusedConv2d-NCHW. This involves many codes, so we could do it separately in another PR (https://github.com/tensorflow/tfjs/pull/6373 is in progress).

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6400#-:-N1tKxAO7kS6ZriVwxiY:b49aexb)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille and @pyu10055)

___
*[`tfjs-backend-cpu/src/kernels/FusedConv2D.ts` line 87 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6400#-N1tJ23w-ZgKwHhhgS1c:-N1tLXUt3_y_8pgY9wL4:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/fbe6ea06bbe7a827a044a2f9e9cf14cdb19c5b7b/tfjs-backend-cpu/src/kernels/FusedConv2D.ts#L87)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

remove the log here.
</blockquote></details>

Done.

**Review by mattsoulanille — APPROVED** [review]
LGTM, and moving the tests in a separate PR sounds good.

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6400#-:-N1tOvc29kktV-SQrMPp:b-aw35ga)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6400)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6400)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
