### PR TITLE
Update saved_model.ts

### LINKED ISSUE #2698: Error: Unsupported tensor DataType: DT_INT64
#### TensorFlow.js version
"@tensorflow/tfjs-node": "^1.5.1"

#### Browser version
NA

#### Describe the problem or feature request
When I load a saved model that is saved by `tf.keras`, `Error: Unsupported tensor DataType: DT_INT64` error is thrown in node v10.15.0.

#### Code to reproduce the bug / link to feature request
https://colab.research.google.com/drive/13GNsRCVtiS3r-VcupZGC2aZo-gSueMEV#revisionId=0BwoZu2uBQcUZTUFQNDBIdURHaUJsR3VMK2c2OWhxZVg4LytzPQ saves the `tf.keras` model using `model.save("saved_model/3_table_model")`

and

```js
const tf = require("@tensorflow/tfjs-node");
async function main() {
    const modelInfo = await tf.node.getMetaGraphsFromSavedModel("./saved_model/3_table_model")    
}
main();
```
tries to load the meta graph.

And here is the stack trace from the run,
```
node-pre-gyp info This Node instance does not support builds for N-API version 4
node-pre-gyp info This Node instance does not support builds for N-API version 5
node-pre-gyp info This Node instance does not support builds for N-API version 4
node-pre-gyp info This Node instance does not support builds for N-API version 5
2020-01-24 23:17:13.039164: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-24 23:17:13.069065: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x109651400 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-01-24 23:17:13.069096: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
(node:16643) UnhandledPromiseRejectionWarning: Error: Unsupported tensor DataType: DT_INT64
    at mapTFDtypeToJSDtype (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:464:19)
    at Object.<anonymous> (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:162:57)
    at step (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:48:23)
    at Object.next (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:29:53)
    at fulfilled (<PROJECT_PATH>/node_modules/@tensorflow/tfjs-node/dist/saved_model.js:20:58)
(node:16643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16643) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I'm running this on a Mac OS 10.15.1 with `Python 2.7.17 :: Anaconda, Inc.`

### PR DESCRIPTION
**Pull request by rthadur**
Fixes #2698

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2700)

### CODE REVIEW

**Comment by Nithanaroy** [comment]
Wow! So fast. Thank you.
Do we need a similar mapping for other types supported by Python Tensorflow (e.g `float64`)? https://www.tensorflow.org/api_docs/python/tf/dtypes/DType

**Comment by kangyizhang** [comment]
@rthadur thanks for the PR. But this will not work because int64 is not supported in TensorFlow.js (same as other unmentioned datatypes). What we need to do is to mention this in documentation. Can you add a PR to list supported datatypes in the jsdoc (https://github.com/tensorflow/tfjs/blob/master/tfjs-node/src/saved_model.ts#L357), and also update the error message saying that users can modify their model in python to convert the datatype.

**Comment by Nithanaroy** [comment]
Hi Kangiyi, just for my knowledge why doesn't tfjs support 64 bit computation?
Is it because of no native support in JS (saw from https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/js-ctypes_reference/Int64)? Are there plans to in near future?

**Comment by rthadur** [comment]
@kangyizhang will submit a new PR soon. Thank you

**Comment by rthadur** [comment]
@kangyizhang I have update this PR , can you please review

**Pull request merged**
