### PR TITLE
Fix WebGL tests to use webgl backend instead of cpu

### PR DESCRIPTION
**Pull request by ahmedsabie**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5425)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5425)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @mattsoulanille)

___
*[tfjs-backend-webgl/src/BUILD.bazel, line 30 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5425#-MgRSNTw7vaY-fMVwL_B:-MgRSNTw7vaY-fMVwL_C:b-8qs61z) ([raw file](https://github.com/tensorflow/tfjs/blob/13de3e0a5312fe10270f7521b9b4da1881c1b01f/tfjs-backend-webgl/src/BUILD.bazel#L30)):*
> ```
> backends/**/*
> ```
Is this folder in webgl?
___
*[tfjs-backend-webgl/src/setup_test.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5425#-MgRUbdy9Ej2wIhbcvFs:-MgRUbdy9Ej2wIhbcvFt:b-mwzlug) ([raw file](https://github.com/tensorflow/tfjs/blob/13de3e0a5312fe10270f7521b9b4da1881c1b01f/tfjs-backend-webgl/src/setup_test.ts#L56)):*
> ```
> import './tests';
> ```
Why do you need to import tests here if karma includes all files including tests here: https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/karma.conf.js#L57

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5425)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-backend-webgl/src/BUILD.bazel, line 30 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5425#-MgRSNTw7vaY-fMVwL_B:-MgR_iZq99wR4qRIX4j1:bu8orw1) ([raw file](https://github.com/tensorflow/tfjs/blob/13de3e0a5312fe10270f7521b9b4da1881c1b01f/tfjs-backend-webgl/src/BUILD.bazel#L30)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> backends/**/*
> ```
Is this folder in webgl?
</blockquote></details>

No. This can be removed.
___
*[tfjs-backend-webgl/src/setup_test.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5425#-MgRUbdy9Ej2wIhbcvFs:-MgR_pHn5l88TYkWALqQ:b-rq683p) ([raw file](https://github.com/tensorflow/tfjs/blob/13de3e0a5312fe10270f7521b9b4da1881c1b01f/tfjs-backend-webgl/src/setup_test.ts#L56)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> import './tests';
> ```
Why do you need to import tests here if karma includes all files including tests here: https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/karma.conf.js#L57
</blockquote></details>

`tfjs-backend-webgl/karma.conf.js` is no longer used and should be removed. The actual config file is generated based off of https://github.com/tensorflow/tfjs/blob/master/tools/karma_template.conf.js

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5425)* status: 0 of 1 approvals obtained (waiting on @lina128 and @mattsoulanille)

___
*[tfjs-backend-webgl/src/setup_test.ts, line 56 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5425#-MgRUbdy9Ej2wIhbcvFs:-MgRba3q5ppc4HnQx0KZ:b9op67o) ([raw file](https://github.com/tensorflow/tfjs/blob/13de3e0a5312fe10270f7521b9b4da1881c1b01f/tfjs-backend-webgl/src/setup_test.ts#L56)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

`tfjs-backend-webgl/karma.conf.js` is no longer used and should be removed. The actual config file is generated based off of https://github.com/tensorflow/tfjs/blob/master/tools/karma_template.conf.js
</blockquote></details>

Ah, you are right. Thanks for the pointer. Either remove karma config in this folder in this PR, or remove all karma configs once migration is done. Either way is fine with me.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5425)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @mattsoulanille)

___
*[tfjs-backend-webgl/package.json, line 64 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5425#-MgRcAPz-0-BbR-9_pOi:-MgRcAPz-0-BbR-9_pOj:b-6pkhas) ([raw file](https://github.com/tensorflow/tfjs/blob/c7aebac6eba899f1b68f1cd7ec9790e2343a2dea/tfjs-backend-webgl/package.json#L64)):*
> ```JSON
>     "publish-npm": "bazel run :tfjs-backend-webgl_pkg.publish",
>     "lint": "tslint -p . -t verbose",
>     "test": "bazel test :tfjs-backend-webgl_test --test_output=streamed",
> ```

Do we know why headless chrome doesn't have access to GPU?

**Pull request closed without merging**
