### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by etiennedupont**
Solves #2761

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/2762)

### CODE REVIEW

**Comment by etiennedupont** [comment]
@googlebot I signed it!

**Comment by etiennedupont** [comment]
Hi @lina128,
as discussed in #2761, this way of making transitive dependencies not only makes it impossible to use `tfjs-node` with Yarn pnp v1, but is also prone to bugs (see https://github.com/tensorflow/tfjs/issues/2761#issuecomment-588140891).  Including this additional line in the `package.json` would not mean to include the package again but to build correct hoistings.

**Comment by nsthorat** [comment]
The CI is failing because we have a little script that makes sure tfjs-node and tfjs-node-gpu package.json line up, can you make the change there as well?

https://github.com/tensorflow/tfjs/blob/master/tfjs-node-gpu/package.json#L57

Thanks so much! This change is great :)

**Comment by etiennedupont** [comment]
Hi @nsthorat, thank you for your answer, I made the required change!

**Pull request merged**
