### PR TITLE
Add implementation for inputs and outputs getters to SavedModel 

### PR DESCRIPTION
**Pull request by patlevin**
## Motivation

`SavedModel` currently lacks implementations for the `inputs` and `outputs` getters (see Issue #4035).

The model signature already contains all necessary information and invoking `getMetaGraphsFromSavedModel()` to get the information might result in redundant file I/O and -parsing.

## Implementation

This implementation extracts the `ModelTensorInfo` from the model's signature and removes channel information from the tensor names (e.g. "*output:0*" is returned as just "*output*").

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4036)

### CODE REVIEW

**Comment by patlevin** [comment]
@googlebot I signed it!

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for the contribution, overall looks great, just a minor comment. Also can you added test to these methods? 

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4036#-:-MJ5NF5G2m7NQeHW2bPd:b9h0vpg)* status: 0 of 1 approvals obtained (waiting on @patlevin)

___
*[tfjs-node/src/saved_model.ts, line 213 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4036#-MJ5Mvod0cS2oNrTPWH6:-MJ5Mvod0cS2oNrTPWH7:b2qj9it) ([raw file](https://github.com/tensorflow/tfjs/blob/40f2d905d8ba84503162ac4f7dc2db6395d8e1a9/tfjs-node/src/saved_model.ts#L213)):*
> ```XML
>     const results = Object.keys(entries).map((key: string) => entries[key]);
>     results.forEach((info: ModelTensorInfo) => {
>       info.name = info.name.replace(/:\d+$/, '');
> ```

the index number should be kept unless it is 0, it represents the which output of the node is designated for the model output.

**Comment by patlevin** [comment]
@pyu10055 Thanks for the quick feedback! I added tests and changed the name-handling so indices other than zero are kept in the returned input- and output names.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4036)* status: 0 of 1 approvals obtained (waiting on @patlevin)

___
*[tfjs-node/src/saved_model_test.ts, line 523 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4036#-MJD0IjO15J53ziLD-Ee:-MJD0IjO15J53ziLD-Ef:b1khr6f) ([raw file](https://github.com/tensorflow/tfjs/blob/385ec32e985dc50655a77238cc8dcb15561f3a9d/tfjs-node/src/saved_model_test.ts#L523)):*
> ```XML
>         './test_objects/saved_model/model_multi_output', ['serve'],
>         'serving_default');
>     expect(model.inputs.length).toBe(2)
> ```

missing semicolons here and below

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4036)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Pull request merged**
