### PR TITLE
Fix tfjs-inference python not throwing error

### PR DESCRIPTION
**Pull request by mattsoulanille**
Fix a bug where tfjs-inference does not propagate errors from JavaScript to Python.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6984)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
thanks, LGTM with a question.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6984#-:-NFW-Vsh5o1YDYyk9DvB:brlcy1l)* status: 0 of 1 approvals obtained (waiting on @lina128 and @mattsoulanille)

___
*[`tfjs-inference/python/inference_test.py` line 110 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6984#-NFW-QDD1zOVfpU6qANt:-NFW-QDD1zOVfpU6qANu:bxo1pi5) ([raw file](https://github.com/tensorflow/tfjs/blob/aca0b77684467deabda8406b9c257bc5ce978070/tfjs-inference/python/inference_test.py#L110)):*
> ```Python
>     with self.assertRaises(FileNotFoundError):
>       with open(os.path.join(tmp_dir, 'data.json'), 'rt') as f:
>         json.load(f)
> ```

not checking for data.json anymore?

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6984)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`tfjs-inference/python/inference_test.py` line 110 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6984#-NFW-QDD1zOVfpU6qANt:-NFabu_j7_OUHjKLTi_n:b8kmnzr) ([raw file](https://github.com/tensorflow/tfjs/blob/aca0b77684467deabda8406b9c257bc5ce978070/tfjs-inference/python/inference_test.py#L110)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

not checking for data.json anymore?
</blockquote></details>

I don't think it's necessary to check that the file is not created, since the new behavior is to throw an error instead of just not create a file, but it doesn't hurt. I'll add it back in.

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6984#-:-NFgDeIb3kV3eqxTIHPJ:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Comment by mattsoulanille** [comment]
@pyu10055 Please take a look. Thanks!

**Review by pyu10055 — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6984)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
