### PR TITLE
Add TFJS TFDF API

### PR DESCRIPTION
**Pull request by ahmedsabie**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6916)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
thanks overall the API looks good, just couple minor comments.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6916#-:-NE1jVx_8eJQg3msm5BB:b312muk)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @jinjingforever)

___
*[`tfjs-tfdf/README.md` line 13 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6916#-NE1gi1b3zzsN4QWsAVL:-NE1gi1b3zzsN4QWsAVM:b-b8bug4) ([raw file](https://github.com/tensorflow/tfjs/blob/986cf64fb3a17daa1e1de2877293ad01e2d7553e/tfjs-tfdf/README.md#L13)):*
> ```Markdown
> ## Import the packages
> 
> To use this package, you will need JSZip, and a TFJS backend installed. We recommend the CPU backend.
> ```

are there particular reason we would recommend CPU backend? can WASM or WebGL backend work too?
___
*[`tfjs-tfdf/README.md` line 62 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6916#-NE1h-ys9OCeDszdqkHb:-NE1h-ys9OCeDszdqkHc:b-2jwzg1) ([raw file](https://github.com/tensorflow/tfjs/blob/986cf64fb3a17daa1e1de2877293ad01e2d7553e/tfjs-tfdf/README.md#L62)):*
> ```Markdown
> 
> // Run inference and get output tensors.
> let outputTensorPromise = tfdfModel.executeAsync(input) as Promise<tf.Tensor>;
> ```

use `await` for better readability
___
*[`tfjs-tfdf/src/tfdf_model.ts` line 152 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6916#-NE1j9QT4FBX-cr40GvU:-NE1j9QT4FBX-cr40GvV:bu1xne8) ([raw file](https://github.com/tensorflow/tfjs/blob/986cf64fb3a17daa1e1de2877293ad01e2d7553e/tfjs-tfdf/src/tfdf_model.ts#L152)):*
> ```XML
>  * const tfdfModel = await tfdf.loadTFDFModel(
>  *     'https://storage.googleapis.com/tfjs-testing/adult_gbt_no_regex/model.json');
>  * const inputs = {
> ```

simplify the input section of the doc to focus on the loader API.

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6916)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @jinjingforever)

**Review by pyu10055 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6916)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever)

**Review by jinjingforever — APPROVED** [review]
This is great! Thank you!

**Pull request merged**
