### PR TITLE
 Add synchronous --outfile option to BrowserStack benchmark

### PR DESCRIPTION
**Pull request by ClaireXP**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5229)

### CODE REVIEW

**Comment by ClaireXP** [comment]
@mattsoulanille

**Review by lina128 — APPROVED** [review]
Great work, Claire!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5229#-:-McoZMT97JRi0Sw8nFd7:bkhrv0g)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP and @mattsoulanille)

___
*[e2e/benchmarks/browserstack-benchmark/benchmark_results.json, line 1 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5229#-McoYXw5DC7Jl0mC6gcS:-McoYXw5DC7Jl0mC6gcT:b-3o4t5c) ([raw file](https://github.com/tensorflow/tfjs/blob/1d0f2d7b78e65592b75db37aacf1bb6a3d4fefdf/e2e/benchmarks/browserstack-benchmark/benchmark_results.json#L1)):*
> ```
> [{"status":"fulfilled"
> ```
This file should be ignored by git. Add a rule in .gitignore

**Review by mattsoulanille — COMMENTED** [review]
Great work factoring out `runOneBenchmark`! I've written a few comments, and I'll take another look when the tests are ready.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5229#-:-McpKQGDAQpF3zwuP9JM:bnz8zu3)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 119 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5229#-McpK8cE4jXHs8Xuonx5:-McpK8cE4jXHs8Xuonx6:bg2uimq) ([raw file](https://github.com/tensorflow/tfjs/blob/1d0f2d7b78e65592b75db37aacf1bb6a3d4fefdf/e2e/benchmarks/browserstack-benchmark/app.js#L119)):*
> ```
> let
> ```
Nit: Can be `const` because `results` is never reassigned.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 126 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5229#-McpIXZz60f6OL3bZ-1r:-McpIX_-DgrBLOnghnns:b2rkx8y) ([raw file](https://github.com/tensorflow/tfjs/blob/1d0f2d7b78e65592b75db37aacf1bb6a3d4fefdf/e2e/benchmarks/browserstack-benchmark/app.js#L126)):*
> ```
>  Promise.allSettled(results).then(results => {
> ```
We should return this promise so that other code that uses `benchmark` can tell when `benchmark` is finished. This is also important for writing tests, since the tests need to know that `benchmark` is finished before they can check the output file.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 126 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5229#-McpJR6T1cfbXMCrXZeA:-McpJR6T1cfbXMCrXZeB:b-i3k1co) ([raw file](https://github.com/tensorflow/tfjs/blob/1d0f2d7b78e65592b75db37aacf1bb6a3d4fefdf/e2e/benchmarks/browserstack-benchmark/app.js#L126)):*
> ```
> process.argv.includes('--outfile')
> ```
Instead of checking `process.argv`, we should use the argparse results from `parser.parse_args()`. See more details on [their documentation page](https://www.npmjs.com/package/argparse#example). I recommend copying their example to a `test.js` file and running it with `node test.js --foo hello`.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 148 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5229#-McpIy8o5M2wymnlQ0yq:-McpIy8o5M2wymnlQ0yr:b-50wn81) ([raw file](https://github.com/tensorflow/tfjs/blob/1d0f2d7b78e65592b75db37aacf1bb6a3d4fefdf/e2e/benchmarks/browserstack-benchmark/app.js#L148)):*
> ```
> execFile('yarn', args, (error, stdout, stderr) => {
> ```
Nicely done converting this callback to a function.

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
I meant to request changes and block merging on my last review. Oops.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5229#-:-McpLKjR8WCWwzgZczbT:b-icqzwp)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP)

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Nice work on the tests and good use of Jasmine mocks. I have just a few nits and some comments on test structure.

> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5229#-:-McuJ9FN3Tv984bURlON:b-bmeak9)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/README.md, line 22 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-MctfdwQCrhteXL84hRJ:-MctfdwQCrhteXL84hRK:b-vukhyn) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/README.md#L22)):*
> ```
> # SMOKE:
> ```
Thanks for fixing this readme!
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 116 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-McuG84F15VcRtLKTUXa:-McuG84F15VcRtLKTUXb:b-vskka4) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app.js#L116)):*
> ```
> benchmarkResult
> ```
Nit: This name sounds like the result of running a benchmark instead of the function to run a benchmark.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 128 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-Mctg8cI5HXUPApmQF3_:-Mctg8cI5HXUPApmQF3a:b-f8eqb) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app.js#L128)):*
> ```
> parser.parse_args()
> ```
Nit: We can call `parser.parse_args()` once and just use the parsed args here, since other functions will need access to the parsed arguments as well. There's no performance concern though, so it's just a nit.
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 174 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-Mcthuqw47cANMrbriTx:-Mcthuqw47cANMrbriTy:b3m705f) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app.js#L174)):*
> ```
> const
> ```
Nice catch!
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 190 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-McuJh0IEb-p5Pds9-0n:-McuJh0IEb-p5Pds9-0o:b-k13obz) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app.js#L190)):*
> ```
> JSON.stringify(msg)
> ```
Nit: If you use `JSON.stringify(msg, null, 2)`, it will pretty print the results on multiple lines. 
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 31 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-Mcti8x29jut_Y09zu5J:-Mcti8x29jut_Y09zu5K:b-g5xvje) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L31)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>   it('runs a command line command', async () => {
>     expect(await exec('echo', ['-n', 'Hello, world!']))
>         .toMatch('Hello');
>   });
>   it('runs a command that takes a while', async () => {
>     expect(await exec('sleep', ['0.1'])).toEqual('');
>   });
>   it('runs a command that fails', async () => {
>     await expectAsync(exec('exit 1')).toBeRejected();
>   });
> });
> ```
</details>


You can remove these if you want. They were just examples.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 36 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-MctkjZL9PFhZX0xPnYd:-MctkjZL9PFhZX0xPnYe:bpx68mc) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L36)):*
> ```
> const mockResults = {
> ```

Nit: It likely doesn't matter in this case, but it's usually best to assign the value of test variables before each test. I'd recommend declaring `mockResults` within `describe` with `let mockResults;`. Then you can use`beforeEach` (which is similar to `beforeAll`) to assign it before each test. More info here: https://jasmine.github.io/tutorials/your_first_suite
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 75 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-MctiTYH8Fs9H_-j4g19:-MctiTYH8Fs9H_-j4g1A:b-dpavf6) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L75)):*
> ```
> describe('tests outfile writing capabilities', () => {
> ```

`describe` is usually used only to declare a new suite of tests for a certain file. For additional tests that test `app.js` with node, you can add new `it()` specs to the existing `describe` above. 
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 87 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-Mctju3GEVr1paQGbB2r:-Mctju3GEVr1paQGbB2s:be0gkd9) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L87)):*
> ```
>     setTimeout(() => fs.readFile(filePath, 'utf8', (err, data) => {
>       expect(data).toEqual(mockResults);
>     }), 1000);
> ```
It's usually not a good idea to set a timeout in tests because we want them to run as quickly as possible. It looks like you're waiting for the mock results file to be written. Instead of waiting for an unknown amount of time, you should change the `write` function so that you know when it's done writing. This can be done by wrapping the callback in a promise like you did with `runOneBenchmark` or by using `fs.writeFileSync`.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 94 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-Mctm83xAKXLADnuL--E:-Mctm83xAKXLADnuL--F:b6ez7cw) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L94)):*
> ```
> const config
> ```

Nit: I recommend changing this to `let config;` and then assigning it before each test with `beforeEach`.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 137 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-Mctn7QD8fKHaib0gRMg:-Mctn7QD8fKHaib0gRMh:b-5mtbc0) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L137)):*
> ```
>   beforeAll(async () => {
>     jasmine.DEFAULT_TIMEOUT_INTERVAL = 1000000;
> ```

Everything after this should probably go in `beforeEach` instead of `beforeAll` so it's run before each test.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 141 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-MctmO6CB7cCbyB9hiSK:-MctmO6D8hJbo3RtUFEt:b-fbn6ja) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L141)):*
> ```
>         jasmine.createSpy('mockRunOneBenchmark').and.callFake((tabId) => {
>           return new Promise((resolve) => {resolve(mockResults[tabId])});
>         });
> ```
Nice use of a jasmine spy
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 142 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-Mctmfix43UUbzVuOkXV:-Mctmfix43UUbzVuOkXW:bt2dnc0) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L142)):*
> ```
> Promise((resolve) => {resolve(mockResults[tabId])})
> ```
Nit: `Promise` provides a `resolve` function for the common case of creating a promise that immediately resolves:`Promise.resolve(mockResults[tabId])`.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 146 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-MctnxEU65oZ5dVdbqBk:-MctnxEU65oZ5dVdbqBl:b-ht5709) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L146)):*
> ```
>     const testResults = await benchmark(config, mockRunOneBenchmark);
> ```
Nice! This is exactly how I hoped we'd be able to use `benchmark`!
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 150 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-Mcto98N9wO9XJWKbaOC:-Mcto98N9wO9XJWKbaOD:b-pbg9xa) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L150)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>     // Receives and formats results from benchmark function call
>     const testResults = await benchmark(config, mockRunOneBenchmark);
>     formattedResults = {};
>     for (let i = 0; i < Object.keys(config.browsers).length; i++) {
>       await new Promise(resolve => {
>         const result = testResults[i]['value'];
>         formattedResults[result['tabId']] = result;
>         return resolve();
>       });
>     }
> ```
</details>

This code is calling the `benchmark` function which we're testing, so it should go in the spec (`it()`) instead of in the setup. That also makes it a bit easier to understand what's being tested IMO.

Also, it's a bit odd that we have all the benchmark results returned in a list instead of an object or a map, where you can get the results by which browser they run on (but I guess that's what `Promise.allSettled` does). We can revisit this if we need to when we start sending results to firebase.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 153 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-MctpgfiA4Xt48J5Mm7G:-MctpgfiA4Xt48J5Mm7H:bn9f8lj) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L153)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     formattedResults = {};
>     for (let i = 0; i < Object.keys(config.browsers).length; i++) {
>       await new Promise(resolve => {
>         const result = testResults[i]['value'];
>         formattedResults[result['tabId']] = result;
>         return resolve();
>       });
>     }
> ```
</details>

This looks odd at first, but I realize it's necessary because of how we return `Promise.allSettled` from `benchmark`. Maybe add a comment explaining why we're doing this.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 162 at r3](https://reviewable.io/reviews/tensorflow/tfjs/5229#-MctoeNN8LofE85wBeHk:-MctoeNN8LofE85wBeHl:bfc7n0x) ([raw file](https://github.com/tensorflow/tfjs/blob/35d7a49427444f41dc9ca590712a0b806c0e62be/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L162)):*
> ```
>             'iPhone_XS_1' || 'Samsung_Galaxy_S20_1' || 'Windows_10_1' ||
>             'OS_X_Catalina_1');
> ```
The `||` operator returns the first truthy value it is 'called' with. In this case, since a non-empty string is truthy, the above is equivalent to writing `iPhone_XS_1`. You'll likely need a copy of `expect(mockRunOneBenchmark).toHaveBeenCalledWith(...)` for each string you want to test, and that's fine since test code does not need to be DRY (Don't Repeat Yourself).

**Review by mattsoulanille — APPROVED** [review]
Thanks! LGTM with just 2 more nits. Re-requesting review from Na since tests were added after she completed her review.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5229#-:-McusnnK6aTXmBUifybT:bijgwhc)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 130 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5229#-McuqV5a2VgEqvL2yIbk:-McuqV5a2VgEqvL2yIbl:bv7ed93) ([raw file](https://github.com/tensorflow/tfjs/blob/196ef5923f27a7567b96cdc05c6ea3387daad59d/e2e/benchmarks/browserstack-benchmark/app.js#L130)):*
> ```
>  await write('./benchmark_results.json', results);
> ```
Nice catch
___
*[e2e/benchmarks/browserstack-benchmark/app.js, line 194 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5229#-Mcup3RF-edCDZajT341:-Mcup3RF-edCDZajT342:b6mfmy1) ([raw file](https://github.com/tensorflow/tfjs/blob/196ef5923f27a7567b96cdc05c6ea3387daad59d/e2e/benchmarks/browserstack-benchmark/app.js#L194)):*
> ```
> return reject();
> ```
Really small nit: Call `reject` with the error.
___
*[e2e/benchmarks/browserstack-benchmark/app_node_test.js, line 117 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5229#-McurkNX2a1jmCZ0lkv7:-McurkNX2a1jmCZ0lkv8:bto9ng9) ([raw file](https://github.com/tensorflow/tfjs/blob/196ef5923f27a7567b96cdc05c6ea3387daad59d/e2e/benchmarks/browserstack-benchmark/app_node_test.js#L117)):*
> ```
> formattedResults = {};
> ```
Nit: This should be declared in the current spec's scope as, e.g., `const formattedResults` instead of in `describe` since it should only be accessible by this spec.

**Review by lina128 — APPROVED** [review]
Great work, LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5229#-:-Md-8DXUDRqRZEZwkKfY:bctp4sx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ClaireXP)

**Pull request merged**
