### PR TITLE
Log error caught when creating WebGL context

### PR DESCRIPTION
**Pull request by jameshfisher**
My day today: I spent a _long_ time debugging the error `Initialization of backend webgl failed` on a particular machine. Ultimately, the cause was really obscure: Chrome was returning `null` from `canvas.getContext` when passed [this `failIfMajorPerformanceCaveat` flag](https://github.com/tensorflow/tfjs/blob/c823c1f944fcf97c8070fd75036da8f4bf14c660/tfjs-backend-webgl/src/canvas_util.ts#L27). Another line in TensorFlow assumes that `getContext` cannot return null, and so throws an error `TypeError: Cannot read property 'isContextLost' of null`. This is another bug. But that error was then silently swallowed at the line here.

On restarting the machine, Chrome mysteriously stopped behaving this way. But that underlying issue is a story for another time.

The point is, silently swallowing all thrown errors is a pretty bad practice. To go further, unless we actually _expect_ errors thrown here, I think this `try`/`catch` should be removed - if it fails unexpectedly, just let it fail. If we do expect errors thrown here, that should at least be documented in a comment here.

This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3969)

### CODE REVIEW

**Review by annxingyuan — APPROVED** [review]

**Comment by jameshfisher** [comment]
(I'll follow up with a separate PR fixing the `TypeError: Cannot read property 'isContextLost' of null` error that I found was being silently swallowed)

**Comment by jameshfisher** [comment]
@annxingyuan thanks for the +1 - I see the PR failed [at this URL](https://console.cloud.google.com/cloud-build/builds/ff99cf1c-9656-4d19-8d24-2c90c28ed0dc?project=834911136599), however that page just says "You do not have sufficient permissions to view this page" :-(

**Comment by annxingyuan** [comment]
Hi @jameshfisher - in order to see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

Looks like you figured out the issue :)

**Comment by jameshfisher** [comment]
Thanks - I found that text in my second PR description; I think I mindlessly deleted it the first time!

**Pull request merged**
