### PR TITLE
[webgl] Modularize reshape, add refCounter.

### PR DESCRIPTION
**Pull request by annxingyuan**
#### Changes
- Adds a ref counting mechanism to the WebGL backend modeled off the CPU backend. Paves the way for removing the existing custom slice ref counter in WebGL.
- Modularizes WebGL's reshape kernel. 
- Adds helper for re-registering kernels for a custom backend.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3910)

### CODE REVIEW

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3910)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 287 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNtrW_EHEE3L5H7dTo:-MHNtrW_EHEE3L5H7dTp:b-9gbtil) ([raw file](https://github.com/tensorflow/tfjs/blob/95e2b2b3fff6780e810e9bb047b90fd715309da0/tfjs-backend-webgl/src/backend_webgl.ts#L287)):*
> ```
> TensorData
> ```

nit: update comment (here and decRef below)
___
*[tfjs-backend-webgl/src/kernels/Reshape.ts, line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNu_k0EHJvy5hFtdpt:-MHNu_k0EHJvy5hFtdpu:bu4a6qm) ([raw file](https://github.com/tensorflow/tfjs/blob/95e2b2b3fff6780e810e9bb047b90fd715309da0/tfjs-backend-webgl/src/kernels/Reshape.ts#L37)):*
> ```
> $xSize
> ```

For my education: I see '$' is used many places in our code base. Is it some kind of convention in our team? Thanks!

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3910)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 381 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNuRNt93SxKS7yZgJp:-MHNuRNt93SxKS7yZgJq:bbpy1c) ([raw file](https://github.com/tensorflow/tfjs/blob/95e2b2b3fff6780e810e9bb047b90fd715309da0/tfjs-backend-webgl/src/backend_webgl.ts#L381)):*
> ```XML
>     const {values, shape, slice, dtype, complexTensors, isPacked} = texData;
> 
>     if (slice != null) {
> ```

Can we add some annotation on this special treatment?
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 2446 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNzO2V3mfLZiIm9yg_:-MHNym6w83ePTS3OHzLn:b-o5l2s5) ([raw file](https://github.com/tensorflow/tfjs/blob/96294bf34ddd9b9575d58d1862e96c910e0f6c53/tfjs-backend-webgl/src/backend_webgl.ts#L2446)):*
> ```XML
>   }
> 
>   private packedReshape(input: TensorInfo, afterShape: number[]): TensorInfo {
> ```

Seems that we need to keep this private function to prevent circular dependency.
___
*[tfjs-backend-webgl/src/kernels/Max_impl.ts, line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNwSLz3gwig-1WJhVM:-MHNwSLz3gwig-1WJhVN:btvtrkj) ([raw file](https://github.com/tensorflow/tfjs/blob/95e2b2b3fff6780e810e9bb047b90fd715309da0/tfjs-backend-webgl/src/kernels/Max_impl.ts#L37)):*
> ```XML
>   backend.disposeIntermediateTensorInfo(reshapedInput);
> 
>   return reshape({inputs: {x: reduced}, attrs: {shape: outShape}, backend});
> ```

Should reduced be disposed too?
```
const result = reshape(...);

backend.disposeIntermediateTensorInfo(reduced);

return result;
```
___
*[tfjs-backend-webgl/src/kernels/Reshape.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNzvEp9MTXJU9S2Dhd:-MHNzvEp9MTXJU9S2Dhe:b-8dopgt) ([raw file](https://github.com/tensorflow/tfjs/blob/95e2b2b3fff6780e810e9bb047b90fd715309da0/tfjs-backend-webgl/src/kernels/Reshape.ts#L19)):*
> ```XML
> 
> import {KernelFunc, Reshape, ReshapeAttrs, ReshapeInputs, TensorInfo} from '@tensorflow/tfjs-core';
> import {KernelConfig, util} from '@tensorflow/tfjs-core';
> ```

Merge above two lines.

**Review by tafsiri — CHANGES_REQUESTED** [review]
Excited to see this!

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3910#-:-MHRjmUDAzQf0ODd7HD-:b-k12pfo)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1870 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRfdAtDcHYH5WH_rxM:-MHRfdAtDcHYH5WH_rxN:b-vnv9x7) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L1870)):*
> ```XML
>       const targetShape = isChannelsLast ? xShape[0] * xShape[1] * xShape[2] :
>                                            xShape[0] * xShape[2] * xShape[3];
>       const xReshaped = x.reshape([1, targetShape, convInfo.inChannels]);
> ```

use op instead of chaining api
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1872 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRfgCQ2cZfPenUERFa:-MHRfgCQ2cZfPenUERFb:b-vnv9x7) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L1872)):*
> ```XML
>       const xReshaped = x.reshape([1, targetShape, convInfo.inChannels]);
>       const filterReshaped =
>           filter.reshape([1, convInfo.inChannels, convInfo.outChannels]);
> ```

use op instead of chaining api
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1883 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRfiVE5tgYyajoLtUv:-MHRfiVE5tgYyajoLtUw:b-vnv9x7) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L1883)):*
> ```XML
>         preluActivationWeights
>       });
>       return result.reshape(convInfo.outShape);
> ```

use op instead of chaining api
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1918 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRgupn7gN2zIJ7Te8B:-MHRgupo2n6xWNSxo9ZE:bphwkc2) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L1918)):*
> ```XML
>             xReshaped.shape} isn't free`);
>     const filterReshaped =
>         filter.reshape([1, convInfo.inChannels, convInfo.outChannels]);
> ```

remove chaining api
___
*[tfjs-backend-webgl/src/kernels/Reshape_test.ts, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRjPHuCKksWmUMYcKq:-MHRjPHv52Kz8-UlRgwz:bkav2ec) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/kernels/Reshape_test.ts#L25)):*
> ```XML
> import {describeWithFlags, ALL_ENVS} from '@tensorflow/tfjs-core/dist/jasmine_util';
> 
> describeWithFlags('Reshape.', ALL_ENVS, () => {
> ```

could you add a test(s) that captures that tests usign both slice and reshape and check that memory is as expected.
___
*[tfjs-core/src/kernel_registry.ts, line 203 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRhH4T75RHZpg5FiYG:-MHRhH4U6SpfGQvdOdhb:bwq2lud) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-core/src/kernel_registry.ts#L203)):*
> ```XML
>  * @param newBackendName New backend.
>  */
> export function reregisterKernelsFromExistingToNewBackend(
> ```

naming suggestion: copyRegisteredKernels (reregister... stood out to me as it makes me think the kernels had already been registered on the target backend already and were being reinitialized or something).

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3910)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 287 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNtrW_EHEE3L5H7dTo:-MHRhK8-3uULBfE-cMEJ:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L287)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

> ```
> TensorData
> ```

nit: update comment (here and decRef below)
</blockquote></details>

Done
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 381 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNuRNt93SxKS7yZgJp:-MHRk6Tj8iyEJ9CEPnJn:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L381)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can we add some annotation on this special treatment?
</blockquote></details>

Done
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1870 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRfdAtDcHYH5WH_rxM:-MHRvGUDEyLqve21Fox9:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L1870)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

use op instead of chaining api
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1872 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRfgCQ2cZfPenUERFa:-MHRvGrDDLSHF9gYCwQk:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L1872)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

use op instead of chaining api
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1883 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRfiVE5tgYyajoLtUv:-MHRvHV49uT-lPfBihyc:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L1883)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

use op instead of chaining api
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1918 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRgupn7gN2zIJ7Te8B:-MHRvRlDCkMtqSS0cOlY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/backend_webgl.ts#L1918)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

remove chaining api
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 2446 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNzO2V3mfLZiIm9yg_:-MHRxbtq8B0eBPj0Wk8M:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/30d5b02ab127e0798df359e2533743d2fcdcb926/tfjs-backend-webgl/src/backend_webgl.ts#L2446)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Seems that we need to keep this private function to prevent circular dependency.
</blockquote></details>

Done
___
*[tfjs-backend-webgl/src/kernels/Max_impl.ts, line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNwSLz3gwig-1WJhVM:-MHRzYZm46gjbdsH8Wcg:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/kernels/Max_impl.ts#L37)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should reduced be disposed too?
```
const result = reshape(...);

backend.disposeIntermediateTensorInfo(reduced);

return result;
```
</blockquote></details>

Done
___
*[tfjs-backend-webgl/src/kernels/Reshape.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNzvEp9MTXJU9S2Dhd:-MHS-4C7EcjgDCfEXJ4E:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/kernels/Reshape.ts#L19)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Merge above two lines.
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/kernels/Reshape.ts, line 37 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHNu_k0EHJvy5hFtdpt:-MHS-6QE8MkMuBK2qRwr:bpgf0v8) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/kernels/Reshape.ts#L37)):*
<details><summary><i>Previously, jinjingforever (Jing Jin) wrote…</i></summary><blockquote>

> ```
> $xSize
> ```

For my education: I see '$' is used many places in our code base. Is it some kind of convention in our team? Thanks!
</blockquote></details>

Hi Jing, yes it's often used in our op code when trying to avoid reassigning the arguments. I think most of the time it's used to name variables that hold the tensorized version of 'tensor-like' inputs (e.g. `const $a = convertToTensor(a);`. 
___
*[tfjs-backend-webgl/src/kernels/Reshape_test.ts, line 25 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRjPHuCKksWmUMYcKq:-MHXKL-a9poVfARVdOd3:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-backend-webgl/src/kernels/Reshape_test.ts#L25)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

could you add a test(s) that captures that tests usign both slice and reshape and check that memory is as expected.
</blockquote></details>

Done
___
*[tfjs-core/src/kernel_registry.ts, line 203 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRhH4T75RHZpg5FiYG:-MHS0CkzEamafyVjOlud:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-core/src/kernel_registry.ts#L203)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

naming suggestion: copyRegisteredKernels (reregister... stood out to me as it makes me think the kernels had already been registered on the target backend already and were being reinitialized or something).
</blockquote></details>

Done.

**Review by lina128 — APPROVED** [review]
This is great! Thank you Ann!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3910#-:-MHXOJLl3CwPf-Qd0eiI:b-9b4nq)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

**Review by tafsiri — APPROVED** [review]
Thanks Ann! Great stuff. (left one naming suggestion) 

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3910#-:-MHlHDse1XHw8oDX6hLn:bl5fnvn)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-core/src/kernel_registry.ts, line 203 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRhH4T75RHZpg5FiYG:-MHlGz1g-IxEEKDXZfHS:b-am995q) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-core/src/kernel_registry.ts#L203)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you can drop the "FromExistingToNewBackend" suffix.

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3910)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @tafsiri)

___
*[tfjs-core/src/kernel_registry.ts, line 203 at r1](https://reviewable.io/reviews/tensorflow/tfjs/3910#-MHRhH4T75RHZpg5FiYG:-MHlHrae8IYv3ZX3ySr1:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/e11c56fb58ca07172afdc89110a3e893a522c4e1/tfjs-core/src/kernel_registry.ts#L203)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

I think you can drop the "FromExistingToNewBackend" suffix. 
</blockquote></details>

Done

**Pull request merged**
