### PR TITLE
[webgpu] Detach dependencies from master.

### PR DESCRIPTION
**Pull request by annxingyuan**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4209)

### CODE REVIEW

**Review by tafsiri — CHANGES_REQUESTED** [review]
Thanks for looking into this! I think you also need to update cloudbuild.yaml

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4209#-:-MLmgonkAs_7WKLHsH-L:b7uc6ho)* status: 0 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-backend-webgpu/src/kernels/Div.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4209#-MLmgGZcCl41j17h_YPM:-MLmgGZcCl41j17h_YPN:b-b5zl8u) ([raw file](https://github.com/tensorflow/tfjs/blob/f1e9618900c73fc2b9bf5749f0c90ef815b9b24e/tfjs-backend-webgpu/src/kernels/Div.ts#L18)):*
> ```XML
>  */
> 
> import {RealDiv, RealDivInputs} from '@tensorflow/tfjs-core';
> ```

I wouldn't have expected this change as it should match whatever was released in 2.7.0, does this pass locally?

**Comment by tafsiri** [comment]
Also adding Matthew as this may intersect with his other PR on running CI from one cloud machine.

**Comment by tafsiri** [comment]
This PR may need to go in before Matthew's will ping you both on chat.

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4209)* status: 0 of 1 approvals obtained (waiting on @lina128, @mattsoulanille, and @tafsiri)

___
*[tfjs-backend-webgpu/src/kernels/Div.ts, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4209#-MLmgGZcCl41j17h_YPM:-MLmhcK7-ely2TVGcPyZ:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/f1e9618900c73fc2b9bf5749f0c90ef815b9b24e/tfjs-backend-webgpu/src/kernels/Div.ts#L18)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

I wouldn't have expected this change as it should match whatever was released in 2.7.0, does this pass locally?
</blockquote></details>

Done

**Review by tafsiri — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4209)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @mattsoulanille)

**Review by mattsoulanille — APPROVED** [review]
Seems like FromPixels.ts needed to be reformatted since most of its changes are indentation-related. LGTM.

**Comment by mattsoulanille** [comment]
Oops. Didn't see this was already reviewed :P. My bad!

**Pull request merged**
