### PR TITLE
[tfjs-layers] Bazel migration

### PR DESCRIPTION
**Pull request by pyu10055**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5672)

### CODE REVIEW

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5672)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-layers/BUILD.bazel, line 33 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknadCEBBSCfSEzilCv:-MknadCEBBSCfSEzilCw:ba7mad7) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/BUILD.bazel#L33)):*
> ```
> nodejs_test(
>     name = "test_snippets_test",
> ```
We could perhaps define a rule or macro that tests snippets if we have multiple packages that need it. Not in this PR though.
___
*[tfjs-layers/BUILD.bazel, line 60 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknbGvd3QIf7d1vzzvC:-MknbGvd3QIf7d1vzzvD:bl86zyj) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/BUILD.bazel#L60)):*
> ```
>     random = "false",
> ```
Did this end up working?
___
*[tfjs-layers/BUILD.bazel, line 64 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MkncO4E8p5ce70jJid8:-MkncO4E8p5ce70jJid9:b-5hogqq) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/BUILD.bazel#L64)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         "//tfjs-backend-cpu:tf-backend-cpu.min.js",
>         "//tfjs-backend-cpu:tf-backend-cpu.min.js.map",
>         "//tfjs-backend-webgl:tf-backend-webgl.min.js",
>         "//tfjs-backend-webgl:tf-backend-webgl.min.js.map",
>         "//tfjs-core:tf-core.min.js",
>         "//tfjs-core:tf-core.min.js.map",
> ```
</details>

Are these bundles needed? The tfjs-layers test bundle should include everything needed for the test, including tfjs-core and the backends.
___
*[tfjs-layers/cloudbuild.yml, line 18 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknTnsb5AGE3zb-s-XY:-MknTnsb5AGE3zb-s-XZ:buc4hwz) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/cloudbuild.yml#L18)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> # Lint.
> - name: 'gcr.io/learnjs-174218/release'
>   dir: 'tfjs-layers'
>   entrypoint: 'yarn'
>   id: 'lint'
>   args: ['lint']
>   waitFor: ['yarn']
> ```
</details>


We should have a global lint script. I can write that in a different PR.
___
*[tfjs-layers/package.json, line 16 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknSxZOEpBGZiC1B8_V:-MknSxZOEpBGZiC1B8_W:bk01krp) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/package.json#L16)):*
> ```
>     "@bazel/ibazel": "^0.15.10",
> ```
You should also add @bazel/bazelisk for when this is build for release.
___
*[tfjs-layers/package.json, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknSu2U3KFnhMRcAMub:-MknSu2V7VpPgQv0d4fd:b5wtxtk) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/package.json#L48)):*
<details><summary><i alt="summary">Quoted 22 lines of code…</i></summary>

> ```
>     "prep": "yarn install && yarn build-ci",
>     "build": "tsc && yarn bundle",
>     "build-ci": "tsc && yarn bundle-ci",
>     "bundle": "rollup -c",
>     "bundle-ci": "rollup -c --ci",
>     "build-backend-webgl": "cd ../tfjs-backend-webgl && yarn && yarn build",
>     "build-backend-webgl-ci": "cd ../tfjs-backend-webgl && yarn && yarn build-ci",
>     "build-link-package": "cd ../link-package && yarn build",
>     "build-deps": "yarn build-link-package && yarn build-backend-webgl",
>     "build-deps-ci": "yarn build-link-package && yarn build-backend-webgl-ci",
>     "build-npm": "./scripts/build-npm.sh",
>     "format": "./tools/clang_format_ts.sh",
>     "link-local": "yalc link",
>     "publish-local": "yarn build-npm && yalc push",
>     "publish-npm": "bazel run :tfjs-layers_pkg.publish",
>     "coverage": "KARMA_COVERAGE=1 karma start --browsers='Chrome' --singleRun",
>     "test": "yarn && yarn build-deps && karma start",
>     "test-dev": "karma start",
>     "test-ci": "./scripts/test-ci.sh",
>     "test-snippets": "yarn && yarn build-deps && yarn build && ts-node --skip-ignore -s ./scripts/test_snippets.ts",
>     "test-snippets-ci": "ts-node --skip-ignore -s ./scripts/test_snippets.ts",
>     "run-browserstack": "karma start --browsers='bs_chrome_mac' --singleRun --reporters='dots,karma-typescript'",
> ```
</details>

I think some of these scripts should be updated / removed for the bazel build. `build-npm` will need to be updated since [the release script uses it](https://github.com/tensorflow/tfjs/blob/bazel_layers/scripts/publish-npm.ts#L102).

You can probably also remove a few of the files in the `scripts` directory, like build-npm, test-ci, and tsconfig.
___
*[tfjs-layers/src/model_save_test.ts, line 300 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknniWG3TKbTsF1HqRv:-MknniWH00fDmhbpF6fR:b6vljie) ([raw file](https://github.com/tensorflow/tfjs/blob/7b08f081414504a5bbaf96cb52e452d0a9d7629a/tfjs-layers/src/model_save_test.ts#L300)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     // Assert that orthogonal initializer hasn't been obtained during
>     // the model loading.
>     expect(getInitSpy).toHaveBeenCalledWith('zeros');
>     expect(gramSchmidtSpy).not.toHaveBeenCalled();
> ```
</details>

Nit: The diff shows this file having only deletions. Just checking if that's intentional.
___
*[tfjs-layers/src/engine/training_test.ts, line 2454 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknpeE393SP-oiibYQQ:-MknpeE393SP-oiibYQR:b-pkgs1b) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/src/engine/training_test.ts#L2454)):*
> ```XML
>   // resolveScalarsInLogs, it will be better to test result instead of internal
>   // code structure.
>   // tslint:disable-next-line: ban
> ```

Sounds good to me
___
*[tools/karma_template.conf.js, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknrbkoDZiL3JdUeu0w:-MknrbkoDZiL3JdUeu0x:b8sea5o) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tools/karma_template.conf.js#L101)):*
> ```
> jasmine: {random: TEMPLATE_random}
> ```
Did this end up working?
___
*[tools/tfjs_web_test.bzl, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknrhBC8AXFePFBitmt:-MknrhBC8AXFePFBitmu:b-84xp10) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tools/tfjs_web_test.bzl#L47)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         "random": attr.string(
>             default = "true",
>             doc = "Jasmine tests run in random",
>         ),
> ```
</details>

Same question here. Does this work, or does Bazel override the argument?

**Comment by mattsoulanille** [comment]
One more thing, which esbuild found:

```
 > bazel-out/k8-fastbuild/bin/tfjs-layers/src/layers/normalization.mjs:343:30: warning: Comparison using the "!==" operator here is always true
    343 │                     this.axis !== [nDims - 1]) {
```

[LayerNormalization might have a bug.](https://github.com/tensorflow/tfjs/blob/master/tfjs-layers/src/layers/normalization.ts#L586) We can fix this in a different PR, though.

**Review by pyu10055 — COMMENTED** [review]
thanks for the review, fixed this error.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5672#-:-Mko-Aaf-J3gV4_OxJ6Y:bz574go)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-layers/BUILD.bazel, line 60 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknbGvd3QIf7d1vzzvC:-MknyQi26RluD96a88PZ:b2xadvr) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/BUILD.bazel#L60)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     random = "false",
> ```
Did this end up working?
</blockquote></details>

removed, I don't think this change has an effects.
___
*[tfjs-layers/BUILD.bazel, line 64 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MkncO4E8p5ce70jJid8:-Mknuz0J3eiazgzWbESi:bnadiln) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/BUILD.bazel#L64)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>         "//tfjs-backend-cpu:tf-backend-cpu.min.js",
>         "//tfjs-backend-cpu:tf-backend-cpu.min.js.map",
>         "//tfjs-backend-webgl:tf-backend-webgl.min.js",
>         "//tfjs-backend-webgl:tf-backend-webgl.min.js.map",
>         "//tfjs-core:tf-core.min.js",
>         "//tfjs-core:tf-core.min.js.map",
> ```
Are these bundles needed? The tfjs-layers test bundle should include everything needed for the test, including tfjs-core and the backends.
</blockquote></details>

tfjs-layers run tests on cpu and webgl backends.
___
*[tfjs-layers/package.json, line 16 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknSxZOEpBGZiC1B8_V:-MknvLCS0Ua3MAAkabj4:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/package.json#L16)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     "@bazel/ibazel": "^0.15.10",
> ```
You should also add @bazel/bazelisk for when this is build for release.
</blockquote></details>

Done.
___
*[tfjs-layers/package.json, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknSu2U3KFnhMRcAMub:-MknwxMn7rKjp0xulO47:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/package.json#L48)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     "prep": "yarn install && yarn build-ci",
>     "build": "tsc && yarn bundle",
>     "build-ci": "tsc && yarn bundle-ci",
>     "bundle": "rollup -c",
>     "bundle-ci": "rollup -c --ci",
>     "build-backend-webgl": "cd ../tfjs-backend-webgl && yarn && yarn build",
>     "build-backend-webgl-ci": "cd ../tfjs-backend-webgl && yarn && yarn build-ci",
>     "build-link-package": "cd ../link-package && yarn build",
>     "build-deps": "yarn build-link-package && yarn build-backend-webgl",
>     "build-deps-ci": "yarn build-link-package && yarn build-backend-webgl-ci",
>     "build-npm": "./scripts/build-npm.sh",
>     "format": "./tools/clang_format_ts.sh",
>     "link-local": "yalc link",
>     "publish-local": "yarn build-npm && yalc push",
>     "publish-npm": "bazel run :tfjs-layers_pkg.publish",
>     "coverage": "KARMA_COVERAGE=1 karma start --browsers='Chrome' --singleRun",
>     "test": "yarn && yarn build-deps && karma start",
>     "test-dev": "karma start",
>     "test-ci": "./scripts/test-ci.sh",
>     "test-snippets": "yarn && yarn build-deps && yarn build && ts-node --skip-ignore -s ./scripts/test_snippets.ts",
>     "test-snippets-ci": "ts-node --skip-ignore -s ./scripts/test_snippets.ts",
>     "run-browserstack": "karma start --browsers='bs_chrome_mac' --singleRun --reporters='dots,karma-typescript'",
> ```
I think some of these scripts should be updated / removed for the bazel build. `build-npm` will need to be updated since [the release script uses it](https://github.com/tensorflow/tfjs/blob/bazel_layers/scripts/publish-npm.ts#L102).

You can probably also remove a few of the files in the `scripts` directory, like build-npm, test-ci, and tsconfig.
</blockquote></details>

Done.
___
*[tfjs-layers/src/model_save_test.ts, line 300 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknniWG3TKbTsF1HqRv:-MknyuJnEcOaajxW1VkO:b-wfg42x) ([raw file](https://github.com/tensorflow/tfjs/blob/7b08f081414504a5bbaf96cb52e452d0a9d7629a/tfjs-layers/src/model_save_test.ts#L300)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>     // Assert that orthogonal initializer hasn't been obtained during
>     // the model loading.
>     expect(getInitSpy).toHaveBeenCalledWith('zeros');
>     expect(gramSchmidtSpy).not.toHaveBeenCalled();
> ```
Nit: The diff shows this file having only deletions. Just checking if that's intentional.
</blockquote></details>

This is the work around for the spyOn calls, assuming the data is correct instead of verifying internal method has been called.
___
*[tools/karma_template.conf.js, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknrbkoDZiL3JdUeu0w:-MknyM8z8UKOCNvS0eAK:bm7xf29) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tools/karma_template.conf.js#L101)):*
> removed, I don't think this change has an effects.
___
*[tools/tfjs_web_test.bzl, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknrhBC8AXFePFBitmt:-MknyI4hEP7Zd6zpAEhh:b2xadvr) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tools/tfjs_web_test.bzl#L47)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
>         "random": attr.string(
>             default = "true",
>             doc = "Jasmine tests run in random",
>         ),
> ```
Same question here. Does this work, or does Bazel override the argument?
</blockquote></details>

removed, I don't think this change has an effects.

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
Thanks for the fixes! I have a few more comments.

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5672#-:-Mko7tLLBtxK1zhPGxDw:b-kjaqib)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-layers/BUILD.bazel, line 64 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MkncO4E8p5ce70jJid8:-Mko5NLj8N7tswGlt9NA:b-c7y3qd) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/BUILD.bazel#L64)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

tfjs-layers run tests on cpu and webgl backends.
</blockquote></details>

I tested without them, and the tests passed. I think Bazel bundles them in the test bundle, and we can skip adding them here and avoid the extra dependency. 
___
*[tfjs-layers/package.json, line 48 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknSu2U3KFnhMRcAMub:-Mko6sCR4W6bIpA8eIQ4:bd9pifs) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/package.json#L48)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! Looks good.
___
*[tfjs-layers/src/model_save_test.ts, line 300 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknniWG3TKbTsF1HqRv:-Mko7Tun0nOZY6RZmyUn:bil7lsi) ([raw file](https://github.com/tensorflow/tfjs/blob/7b08f081414504a5bbaf96cb52e452d0a9d7629a/tfjs-layers/src/model_save_test.ts#L300)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

This is the work around for the spyOn calls, assuming the data is correct instead of verifying internal method has been called.
</blockquote></details>

Sounds good. Thanks!
___
*[tools/karma_template.conf.js, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknrbkoDZiL3JdUeu0w:-Mko57RiB2Er32OvVGvP:b-ghrm35) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tools/karma_template.conf.js#L101)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> removed, I don't think this change has an effects.
</blockquote></details>

I think this file was missed in your latest push.
___
*[tools/tfjs_web_test.bzl, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknrhBC8AXFePFBitmt:-Mko5BapEh12uhW3PzIQ:b-xph3n5) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tools/tfjs_web_test.bzl#L47)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

removed, I don't think this change has an effects.
</blockquote></details>

I think this was missed in the latest push.

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5672)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[tfjs-layers/BUILD.bazel, line 64 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MkncO4E8p5ce70jJid8:-Mkrc5MS1SenemliJi65:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tfjs-layers/BUILD.bazel#L64)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

I tested without them, and the tests passed. I think Bazel bundles them in the test bundle, and we can skip adding them here and avoid the extra dependency. 
</blockquote></details>

Done.
___
*[tools/karma_template.conf.js, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknrbkoDZiL3JdUeu0w:-MkrcjOR1VPUURc2UM3Q:b-l5cpsa) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tools/karma_template.conf.js#L101)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

I think this file was missed in your latest push.
</blockquote></details>

sorry, just added.
___
*[tools/tfjs_web_test.bzl, line 47 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5672#-MknrhBC8AXFePFBitmt:-MkreQ1D3e_2EDvEkA5n:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/0bd9afa9c07b0caf980b1fe7681b81e167bf25bb/tools/tfjs_web_test.bzl#L47)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

I think this was missed in the latest push.
</blockquote></details>

Done.

**Review by mattsoulanille — APPROVED** [review]
Thanks for the fixes. No more comments on them, but I found something else. The new bundle contains the `long` package while the old one does not. Is that intentional? You can see this if you check the visualization at `dist/bin/tfjs-layers/tf-layers.min_stats.html` against the original build's visualization file, which can be generated with `yarn build-npm` and appears in `tfjs-layers/dist/tf-layers.min.js.html`. The new bundle also seems to be ~40Kb (~13%) larger, but this might be acceptable.

> Reviewed 3 of 3 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5672#-:-MkryNCv3oUEVz8c2vBH:bqsvb1l)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by SidBlack — COMMENTED** [review]
> Reviewed 29 of 36 files at r1, 4 of 7 files at r2, 2 of 3 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5672)* status: :shipit: complete! 1 of 1 approvals obtained

**Review by SidBlack — COMMENTED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5672#-:-Ml81nHrB7XgDggn6NIC:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
