### PR TITLE
webgpu: add mean and prod operators

### PR DESCRIPTION
**Pull request by xhcao**
FEATURE

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4782)

### CODE REVIEW

**Comment by xhcao** [comment]
@qjia7 @haoyunfeix @axinging @gyagp, please take a look, thank you.

**Comment by qjia7** [comment]
@xhcao all reduce related ops `'max'|'mean'|'min'|'prod'|'sum'` are very similar. Can you refactor them into a common function like `Reduce_impl.ts`? then you can call `reduceImpl` in these 5 operators *Config file.

**Comment by xhcao** [comment]
Please take a look, thank you.

**Comment by kainino0x** [comment]
sorry, my review load is too high right now. I don't think I have any expertise here that you don't have, so personally I'd be happy to rely on your review. @lina128, as a maintainer, what do you think of this?

**Review by lina128 — APPROVED** [review]
@kainino0x SGTM.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4782#-:-MVbmWS2Drfwm5ilGOo7:bcwt19)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @kainino0x)

**Comment by kainino0x** [comment]
thanks, I will drop myself from the review list then :)

**Pull request merged**
