### PR TITLE
[wasm] Workaround sin/cos bug with ios11/12, and use tensor4d as image related test source to reduce flakyness

### PR DESCRIPTION
**Pull request by jinjingforever**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4738)

### CODE REVIEW

**Review by mattsoulanille — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4738)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @pyu10055)

___
*[tfjs-backend-wasm/src/cc/sin_cos_workaround.h, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4738#-MULEWz75W8dCXZ5MPf9:-MULEWz75W8dCXZ5MPfA:b-3sbazc) ([raw file](https://github.com/tensorflow/tfjs/blob/4c2e3df3819553991a64aa9da6c850509a0be6de/tfjs-backend-wasm/src/cc/sin_cos_workaround.h#L36)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
> inline float sin_broken(float x) {
>   if (x < 0 || x >= M_PI_4) {
>     tfjs::util::warn("broken sin given %f", x);
>     exit(1);
>   }
>   return sin(x);
> }
> inline float cos_broken(float x) {
>   if (x < 0 || x >= M_PI_4) {
>     tfjs::util::warn("broken cos given %f", x);
>     exit(1);
>   }
>   return cos(x);
> }
> ```
</details>


This was just for the test to make sure I didn't accidentally call sin or cos outside of the [0, pi/4) range. It's not necessary in production.
___
*[tfjs-backend-wasm/src/cc/sin_cos_workaround.cc, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4738#-MULElDl90ssbtTBCD4O:-MULElDl90ssbtTBCD4P:b-ya3w6a) ([raw file](https://github.com/tensorflow/tfjs/blob/4c2e3df3819553991a64aa9da6c850509a0be6de/tfjs-backend-wasm/src/cc/sin_cos_workaround.cc#L26)):*
> ```cpp
> 
>   if (zero_to_2pi < M_PI_4) {
>     return sin_broken(zero_to_2pi);
> ```

This should just be `sin(zero_to_2pi)` since `sin_broken` was just for testing.
___
*[tfjs-backend-wasm/src/cc/sin_cos_workaround.cc, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4738#-MULEt1m0tYGqcZIoE4v:-MULEt1m0tYGqcZIoE4w:bmbakw0) ([raw file](https://github.com/tensorflow/tfjs/blob/4c2e3df3819553991a64aa9da6c850509a0be6de/tfjs-backend-wasm/src/cc/sin_cos_workaround.cc#L29)):*
> ```cpp
>   } else if (zero_to_2pi < M_PI_2) {
>     auto past_pi_4 = zero_to_2pi - M_PI_4;
>     return cos_broken(M_PI_4 - past_pi_4);
> ```

Same here. This should just be `cos`.

**Review by lina128 — APPROVED** [review]
Great work, thank you Jing and @mattsoulanille !

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4738#-:-MULFTmT3mt9IhKGdV26:b513z5g)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[tfjs-core/src/ops/image/rotate_with_offset_test.ts, line 50 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4738#-MULFDHWAGR55N9qUWYW:-MULFDHWAGR55N9qUWYX:btv4a38) ([raw file](https://github.com/tensorflow/tfjs/blob/4c2e3df3819553991a64aa9da6c850509a0be6de/tfjs-core/src/ops/image/rotate_with_offset_test.ts#L50)):*
> ```XML
>     ];
> 
>     expectArraysClose(expected, rotatedPixelsData, 10);
> ```

Nit: we can change from 10 to 0. But can be follow up, non-blocker.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4738)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @mattsoulanille, and @pyu10055)

___
*[tfjs-backend-wasm/src/cc/sin_cos_workaround.h, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4738#-MULEWz75W8dCXZ5MPf9:-MULFrwu8kVkf7FiAHOk:b2nxb4f) ([raw file](https://github.com/tensorflow/tfjs/blob/4c2e3df3819553991a64aa9da6c850509a0be6de/tfjs-backend-wasm/src/cc/sin_cos_workaround.h#L36)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

> ```
> inline float sin_broken(float x) {
>   if (x < 0 || x >= M_PI_4) {
>     tfjs::util::warn("broken sin given %f", x);
>     exit(1);
>   }
>   return sin(x);
> }
> inline float cos_broken(float x) {
>   if (x < 0 || x >= M_PI_4) {
>     tfjs::util::warn("broken cos given %f", x);
>     exit(1);
>   }
>   return cos(x);
> }
> ```

This was just for the test to make sure I didn't accidentally call sin or cos outside of the [0, pi/4) range. It's not necessary in production.
</blockquote></details>

+1, this naming was very confusing to me.

**Comment by mattsoulanille** [comment]
Actually, maybe it's fine to leave sin_broken and cos_broken as is, since we definitely don't want to accidentally call outside the [0, pi/4) range. I'll ask this in chat.

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4738)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @mattsoulanille and @pyu10055)

___
*[tfjs-backend-wasm/src/cc/sin_cos_workaround.h, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4738#-MULEWz75W8dCXZ5MPf9:-MULH5BgA5TBkbLdhd5z:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/4c2e3df3819553991a64aa9da6c850509a0be6de/tfjs-backend-wasm/src/cc/sin_cos_workaround.h#L36)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

+1, this naming was very confusing to me.
</blockquote></details>

Done.
___
*[tfjs-backend-wasm/src/cc/sin_cos_workaround.cc, line 26 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4738#-MULElDl90ssbtTBCD4O:-MULH5oL7zuI9lNS43xa:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/4c2e3df3819553991a64aa9da6c850509a0be6de/tfjs-backend-wasm/src/cc/sin_cos_workaround.cc#L26)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

This should just be `sin(zero_to_2pi)` since `sin_broken` was just for testing.
</blockquote></details>

Done.
___
*[tfjs-backend-wasm/src/cc/sin_cos_workaround.cc, line 29 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4738#-MULEt1m0tYGqcZIoE4v:-MULH68K-Gztbwn18QF0:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/4c2e3df3819553991a64aa9da6c850509a0be6de/tfjs-backend-wasm/src/cc/sin_cos_workaround.cc#L29)):*
<details><summary><i>Previously, mattsoulanille (Matthew Soulanille) wrote…</i></summary><blockquote>

Same here. This should just be `cos`.
</blockquote></details>

Done.

**Review by mattsoulanille — COMMENTED** [review]
Thanks! Looks great!

> Reviewed 2 of 10 files at r1, 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4738#-:-MULHP0t4L_ovhMUZlpK:b-es8gvn)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by mattsoulanille — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4738#-:-MULHX9L8DzPHguoIpf6:b-jbsf8z)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @pyu10055)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4738)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

___
*[tfjs-core/src/ops/image/rotate_with_offset_test.ts, line 50 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4738#-MULHn1S-K2s5vcMNhrN:-MULHn1TEFbfQpwArkZN:baqy1tz) ([raw file](https://github.com/tensorflow/tfjs/blob/10d12f9b45be63965b85a1a8c08e3943c6afb835/tfjs-core/src/ops/image/rotate_with_offset_test.ts#L50)):*
> ```XML
>     ];
> 
>     expectArraysClose(expected, rotatedPixelsData);
> ```

Sorry, I was just referring to flipLeftRight, rotate may still need some wiggle room. We'll see whether test can pass.

**Pull request merged**
