### PR TITLE
Localize BrowserStack Karma config

### PR DESCRIPTION
**Pull request by ClaireXP**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5239)

### CODE REVIEW

**Comment by ClaireXP** [comment]
@mattsoulanille

**Review by mattsoulanille — APPROVED** [review]
LGTM with one nit (i.e. a thing you can fix if you want to, but not that important). Nice!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5239#-:-MckUzu0-L7pZUVKRhG3:b-bfaszg)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

___
*[e2e/benchmarks/browserstack-benchmark/package.json, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5239#-MckTLZqApIWjBFauvA9:-MckTLZr66KLKcMXA5MC:bq37u3x) ([raw file](https://github.com/tensorflow/tfjs/blob/2391261ef399681042fa8617723f72120e9753e9/e2e/benchmarks/browserstack-benchmark/package.json#L36)):*
> ```
> yarn build-deps
> ```

Nit (which means you don't have to fix this):

While running `yarn build-deps` for each dependency is technically correct and, imo, how the tfjs repo should work, it can take a long time. We don't support incremental builds well yet, so if a package occurs multiple times in the `build-deps` of other packages, it will be rebuilt each time and will likely take the same amount of time to build for each occurrence.

If you build packages in order, making sure no package comes before one of its dependencies, you can avoid calling each package's build-deps.

If you end up doing this, it can be another PR.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5239)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/benchmarks/browserstack-benchmark/package.json, line 11 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5239#-MckW9L76xdhD-w9FRZm:-MckW9L76xdhD-w9FRZn:b8isbmc) ([raw file](https://github.com/tensorflow/tfjs/blob/2391261ef399681042fa8617723f72120e9753e9/e2e/benchmarks/browserstack-benchmark/package.json#L11)):*
> ```
> "@tensorflow/tfjs": "link:../../../tfjs",
> ```
If you use individual packages, then you should remove the union pkg.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5239)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ClaireXP)

___
*[e2e/benchmarks/browserstack-benchmark/package.json, line 11 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5239#-MckW9L76xdhD-w9FRZm:-Md-6xMs48chGw4eZNEt:bge4nd8) ([raw file](https://github.com/tensorflow/tfjs/blob/ca218bf3b3c4315fbac55ddf75660cedd035e35b/e2e/benchmarks/browserstack-benchmark/package.json#L11)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

> ```
> "@tensorflow/tfjs": "link:../../../tfjs",
> ```
If you use individual packages, then you should remove the union pkg.
</blockquote></details>

Please remove above line.

**Comment by ClaireXP** [comment]
Thanks for the review and feedback @lina128! I've made a few commits to remove the extraneous dependencies. Let me know if this was what you had in mind!

**Review by lina128 — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5239#-:-MdNZUC8AapNi47oKsih:bb6ywmx)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @ClaireXP)

**Pull request merged**
