### PR TITLE
webgl: Add shapes uniforms to reduce shader compilation time

### LINKED ISSUE #5205: [perf] improve shader compilation for WebGL with KHR_parallel_shader_compile extension
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow.js):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow.js installed from (npm or script link):
- TensorFlow.js version (use command below): 3.7.0
- Browser version: NA
- Tensorflow.js Converter Version: NA

**Describe the current behavior**
The initial inference on current TFJS webGL backend is much slower, which is caused by shader compilation and texture allocation.

**Describe the expected behavior**
With the latest extension KHR_parallel_shader_compile, there is a chance to speed up the shader compilation and reduce the initial inference time.
**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/CodePen/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

### PR DESCRIPTION
**Pull request by qjia7**
PERF
Fix #5205

This PR adds the shapes uniforms support and enables it for unary/binary
ops.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5240)

### CODE REVIEW

**Comment by qjia7** [comment]
@pyu10055 @lina128 @jinjingforever Please take a look, thanks.

Currently, the shapes uniforms are supported. This PR only enables it for unary/binary ops.  And one limitation is only rank<=4 can go to the uniform path.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
This is awesome, Thank you! One high level question, the limitation of rank <= 4 is caused by the uniform vector size? can matrix be used here to support up to rank 6?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5240#-:-McrJv9l9jt_RAwoQFT3:b-qiok1n)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @qjia7)

___
*[tfjs-backend-webgl/src/binaryop_packed_gpu.ts, line 83 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrAOvyBm-ybGJe06I5:-McrAOvyBm-ybGJe06I6:b-3c9omc) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/binaryop_packed_gpu.ts#L83)):*
> ```XML
>           }
>         } else {
>           const channels = getChannels('coords', rank);
> ```

is the channel variable still making the shader dynamic by the output shape?
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 229 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrBl5SCZksmLkpKqWV:-McrBl5SCZksmLkpKqWW:bilomfj) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L229)):*
> ```XML
>       switch (uniformShape.length) {
>         case 1:
>           gpgpu.gl.uniform1iv(varShapeLoc, new Int32Array(uniformShape));
> ```

should unsigned int be used here? `uniform1uiv`?
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 240 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrCP4J0hDT7WhQYRPT:-McrCP4K95ZWNmo7hF7O:b-3ez00o) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L240)):*
> ```
> default
> ```
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrCQ4a253Exq1ucPMN:-McrCQ4a253Exq1ucPMO:b-anh0tz) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L291)):*
> ```XML
>         gpgpu.gl.uniform4iv(outShapeLoc, new Int32Array(output.shape));
>         break;
>       default:
> ```

is it possible to use two uniform variables for larger than rank 4 tensors?
or use two uniform variables, one for the rank value and the other 3x2 uniform matrix for the shapes? this could give us up to rank 6.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 332 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrEFl15Q-bIwRRzAeO:-McrEFl15Q-bIwRRzAeP:b-4dpfkl) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L332)):*
> ```XML
>     const hasOffset = x.texData != null && x.texData.slice != null &&
>         x.texData.slice.flatOffset > 0;
>     if (program.enableShapeUniforms && !x.isUniform) {
> ```

can you add some comments to explain why it needs to build the input key this way.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 368 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrEujD8wHQDYhY7qlD:-McrEujD8wHQDYhY7qlE:b-22ufx1) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L368)):*
> ```XML
>   // Fast string concat. See https://jsperf.com/string-concatenation/14.
>   key +=
>       '_' + keyInputs + '_' + keyUserCode + `env().getNumber('WEBGL_VERSION')`;
> ```

With this new key scheme, the shape is no longer part of the key, but there are other information added. Can explain what type of duplicated shaders it can reduce?

**Review by qjia7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5240)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @jinjingforever, @lina128, @pyu10055, and @qjia7)

___
*[tfjs-backend-webgl/src/binaryop_packed_gpu.ts, line 83 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrAOvyBm-ybGJe06I5:-McwQiUQAVb5ungplTgm:bx9xa31) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/binaryop_packed_gpu.ts#L83)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is the channel variable still making the shader dynamic by the output shape?
</blockquote></details>

No. It only depends on the outShape.length, which has been added to the key in the makeShaderKey.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 229 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrBl5SCZksmLkpKqWV:-McwRDtb6rU_srxIllsI:bgpmry8) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L229)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should unsigned int be used here? `uniform1uiv`?
</blockquote></details>

Currently, all shapes are used as int instead of uint in shader_compiler. Do you want to change this way?
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrCQ4a253Exq1ucPMN:-McwRZoNCIAW0XbiXhqA:bgvekn3) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L291)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

is it possible to use two uniform variables for larger than rank 4 tensors?
or use two uniform variables, one for the rank value and the other 3x2 uniform matrix for the shapes? this could give us up to rank 6.
</blockquote></details>

Yes, it's a method. But I don't plan to implement it in this PR.
In this PR, I hope we can provide a basic uniform support and enable ops step by step so that we can observe the perf impact by different ops.
For 5d/6d support, we can do it in future. I think it won't bring big changes for current framework.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 332 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrEFl15Q-bIwRRzAeO:-McwSUNa1eWge5o5cfHj:b-vooxfo) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L332)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can you add some comments to explain why it needs to build the input key this way.
</blockquote></details>

Done. But I don't have a good solution to keep the consistent between here and `shader_compiler`. All these conditions are required because we go to a special(optimized) path in shader_compilar, which will results the shader diversity. 
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 368 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrEujD8wHQDYhY7qlD:-McwT_PPD_csw1TrisI3:b57s564) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L368)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

With this new key scheme, the shape is no longer part of the key, but there are other information added. Can explain what type of duplicated shaders it can reduce?
</blockquote></details>

The additional info in shader key are mainly for some special cases. Besides that, all kinds of inputs can share the same shader code. For example, for 4d tensors a + b, we can use the same shader binary, no matter the shape value. However, previously, it will generate one shader binary for one input combination if the inputs value are not exactly same. 
For example,
Relu6 4D[1,17,17,192]
Relu6 4D[1,33,33,48]
Relu6 4D[1,9,9,384]
They all use the same shader code and just compile once. However, previously, it will compile three times.

**Comment by qjia7** [comment]
> One high level question, the limitation of rank <= 4 is caused by the uniform vector size? can matrix be used here to support up to rank 6?
> 
Yes, that's doable. See my reply in code review. I prefer we do it later not in this PR since I don't think it will bring big code change in current framework.

And we don't have any android device to test if it will bring any prediction time perf regression. Can you help check that?
I can test the perf data on intel windows CFL and send you later. Thanks.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thanks, I will do a quick benchmark test on android devices.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5240#-:-Mcz7Er3Bklr0cFphEoc:b-bh0l4m)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @jinjingforever, @lina128, @pyu10055, and @qjia7)

___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 229 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrBl5SCZksmLkpKqWV:-McyYBns9aIyaV13zEmg:boaas0x) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L229)):*
<details><summary><i>Previously, qjia7 (Jiajia Qin) wrote…</i></summary><blockquote>

Currently, all shapes are used as int instead of uint in shader_compiler. Do you want to change this way?
</blockquote></details>

it is fine to use int for the consistency here.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 291 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrCQ4a253Exq1ucPMN:-McyYPV517uy7LrzhCvR:b2nic6t) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L291)):*
<details><summary><i>Previously, qjia7 (Jiajia Qin) wrote…</i></summary><blockquote>

Yes, it's a method. But I don't plan to implement it in this PR.
In this PR, I hope we can provide a basic uniform support and enable ops step by step so that we can observe the perf impact by different ops.
For 5d/6d support, we can do it in future. I think it won't bring big changes for current framework.
</blockquote></details>

sg.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 368 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5240#-McrEujD8wHQDYhY7qlD:-Mcz3k6_-2ZXPhxEnTI4:bfk241q) ([raw file](https://github.com/tensorflow/tfjs/blob/8dab150abaf72bee27b515d947bef4ba9ef8c737/tfjs-backend-webgl/src/gpgpu_math.ts#L368)):*
<details><summary><i>Previously, qjia7 (Jiajia Qin) wrote…</i></summary><blockquote>

The additional info in shader key are mainly for some special cases. Besides that, all kinds of inputs can share the same shader code. For example, for 4d tensors a + b, we can use the same shader binary, no matter the shape value. However, previously, it will generate one shader binary for one input combination if the inputs value are not exactly same. 
For example,
Relu6 4D[1,17,17,192]
Relu6 4D[1,33,33,48]
Relu6 4D[1,9,9,384]
They all use the same shader code and just compile once. However, previously, it will compile three times.

</blockquote></details>

thanks for explanation.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 352 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5240#-Mcz5Z6E-Ubo9x2dxGHV:-Mcz5Z6E-Ubo9x2dxGHW:b-um7d5z) ([raw file](https://github.com/tensorflow/tfjs/blob/8eb5af4a59b96688d9769a607d498c2b692738e1/tfjs-backend-webgl/src/gpgpu_math.ts#L352)):*
> ```
> getBroadcastDims
> ```
the shader_compiler seems to computing broadcastDims based on the texture logic shape, is it the same as the shape here?
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 356 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5240#-Mcz2YdjBDdIDfg7T_H2:-Mcz2YdjBDdIDfg7T_H3:b-veze1w) ([raw file](https://github.com/tensorflow/tfjs/blob/8eb5af4a59b96688d9769a607d498c2b692738e1/tfjs-backend-webgl/src/gpgpu_math.ts#L356)):*
> ```XML
>           x.shape.length === output.shape.length &&
>           util.arraysEqual(xTexShape, output.texData.texShape);
>       // |x.shape.length| is used to determin the coords length. See
> ```

there is a typo `determine`, can you provide a summary saying:
These keys are needed due to shader_compiler is embedding them in the shader.

also can you style the comment a bit, making each key component a separate line.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 367 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5240#-Mcz3a1-DS1EtslWX9HF:-Mcz3a1-DS1EtslWX9HG:b-l7f7m8) ([raw file](https://github.com/tensorflow/tfjs/blob/8eb5af4a59b96688d9769a607d498c2b692738e1/tfjs-backend-webgl/src/gpgpu_math.ts#L367)):*
> ```XML
>       // getOutputPacked1DCoords. |rank2| is used in getOutput2DCoords. |rank34|
>       // is used in getSampler3D/getSampler4D. |xTexShape[0] > 1, xTexShape[1] >
>       // 1| is used in getSampler[Scalar|1D|2D].
> ```

another question is can all of these parameters become uniform as well? If so, has webGPU done that, what is the estimated amount of effort?

**Review by qjia7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5240)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @jinjingforever, @lina128, @pyu10055, and @qjia7)

___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 352 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5240#-Mcz5Z6E-Ubo9x2dxGHV:-Md1Bod-3dh5W1YSRrYQ:b-m1s59p) ([raw file](https://github.com/tensorflow/tfjs/blob/8eb5af4a59b96688d9769a607d498c2b692738e1/tfjs-backend-webgl/src/gpgpu_math.ts#L352)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> getBroadcastDims
> ```
the shader_compiler seems to computing broadcastDims based on the texture logic shape, is it the same as the shape here?
</blockquote></details>

Yes, it's the shape. You can find the logic shape definition in L75 in this file.
```
  const inputInfos: InputInfo[] = inputs.map((input, i) => {
    const shapeInfo: ShapeInfo = {
      logicalShape: input.shape,
      texShape: input.isUniform ? null : input.texData.texShape,
      isUniform: input.isUniform,
      isPacked: input.isUniform ? false : input.texData.isPacked,
      flatOffset: null
    };
```
You can see that the `logicalShape` is the `input.shape`.  
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 356 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5240#-Mcz2YdjBDdIDfg7T_H2:-Md1CRwA9yVY4PL7aDDW:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/8eb5af4a59b96688d9769a607d498c2b692738e1/tfjs-backend-webgl/src/gpgpu_math.ts#L356)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

there is a typo `determine`, can you provide a summary saying:
These keys are needed due to shader_compiler is embedding them in the shader.

also can you style the comment a bit, making each key component a separate line.

</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 367 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5240#-Mcz3a1-DS1EtslWX9HF:-Md1Cf-XAUVitcx5CpwF:bgnhqem) ([raw file](https://github.com/tensorflow/tfjs/blob/8eb5af4a59b96688d9769a607d498c2b692738e1/tfjs-backend-webgl/src/gpgpu_math.ts#L367)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

another question is can all of these parameters become uniform as well? If so, has webGPU done that, what is the estimated amount of effort?
</blockquote></details>

Maybe, but it may hurt the performance if you bring too many if else. I can give a look if we need to further decouple the dependence on these conditions.
For webgpu it still depends on the in/outshape rank and the `broadcastDims`. There is no so many limitations for webgpu since it uses buffer instead of texture. Many limitations here are due to texture shape. Another reason may be that webgpu hasn't done many detailed optimizations for some special logical shape.

**Review by pyu10055 — COMMENTED** [review]
Thank you Jiajia, I think we should have the flag default to false, and add a integration test (with the flag on) in the tfjs-backed-webgl/scripts/test-ci.sh file. I will LGTM after these changes.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5240#-:-MdN7-lT1okpyEasA_7k:b-r0mpoz)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @jinjingforever, @lina128, @pyu10055, and @qjia7)

**Review by pyu10055 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5240#-:-MdVNI9933T_nAhYV72N:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie, @jinjingforever, @lina128, @pyu10055, and @qjia7)

**Pull request merged**
