### PR TITLE
[wasm] Add atan kernel

### PR DESCRIPTION
**Pull request by chunnienc**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7252)

### CODE REVIEW

**Review by mattsoulanille — APPROVED** [review]
LGTM. Thanks for the contribution!

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thanks you for ramping up so quickly. a minor nitpick on the PR.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7252#-:-NL7RHtz--8X3Qk22pK3:b-naln0h)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @chunnienc)

___
*[`tfjs-backend-wasm/src/setup_test.ts` line 405 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7252#-NL7R28r-6pbINBwU-rS:-NL7R28r-6pbINBwU-rT:b-sc2tkt) ([raw file](https://github.com/tensorflow/tfjs/blob/6289ad07ec9f5ffae9bcb262f6be833d2b95efd7/tfjs-backend-wasm/src/setup_test.ts#L405)):*
> ```XML
>   {include: 'reciprocal'},
>   {include: 'isNaN'},
>   {include: 'atan '},
> ```

please remove the trailing space, I think the description of atan tests only contains 'atan'.

**Comment by chunnienc** [comment]
> Thanks you for ramping up so quickly. a minor nitpick on the PR.
> 
> > _[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7252#-:-NL7RHtz--8X3Qk22pK3:b-naln0h)_ status: :shipit: complete! 1 of 1 approvals obtained (waiting on @chunnienc)
> 
> _[`tfjs-backend-wasm/src/setup_test.ts` line 405 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7252#-NL7R28r-6pbINBwU-rS:-NL7R28r-6pbINBwU-rT:b-sc2tkt) ([raw file](https://github.com/tensorflow/tfjs/blob/6289ad07ec9f5ffae9bcb262f6be833d2b95efd7/tfjs-backend-wasm/src/setup_test.ts#L405)):_
> 
> > ```
> >   {include: 'reciprocal'},
> >   {include: 'isNaN'},
> >   {include: 'atan '},
> > ```
> 
> please remove the trailing space, I think the description of atan tests only contains 'atan'.

The test filter applies on the resolved/expanded test name e.g. [https://github.com/tensorflow/tfjs/blob/3647d7e89521c0590d3e31bd7848ba2b0f208662/tfjs-core/src/ops/atan_test.ts#L23](this test's name for matching) would be `"atan basic"`, so it matches the filter with the trailing space.

Besides:
1. The current filter with trailing space could fail with my intended incorrect implementation, which means the atan tests are properly included.
2. The filter without trailing space failed since it includes other tests for 'atan2' and 'atanh'.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7252)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @chunnienc)

___
*[`tfjs-backend-wasm/src/setup_test.ts` line 405 at r1](https://reviewable.io/reviews/tensorflow/tfjs/7252#-NL7R28r-6pbINBwU-rS:-NL7Wc5YDvvky0Kh1Qbo:b61zdc4) ([raw file](https://github.com/tensorflow/tfjs/blob/6289ad07ec9f5ffae9bcb262f6be833d2b95efd7/tfjs-backend-wasm/src/setup_test.ts#L405)):*
<details><summary><i>Previously, chunnienc wrote…</i></summary><blockquote>

The test filter applies on the resolved/expanded test name e.g. [this test's name for matching](https://github.com/tensorflow/tfjs/blob/3647d7e89521c0590d3e31bd7848ba2b0f208662/tfjs-core/src/ops/atan_test.ts#L23) would be `"atan basic"`, so it matches the filter with the trailing space.

Besides:
1. The current filter with trailing space could fail with my intended incorrect implementation, which means the atan tests are properly included.
2. The filter without trailing space failed since it includes other tests for 'atan2' and 'atanh'.

</blockquote></details>

awesome, thank you for the clarification, trailing space would be a good way to avoid other ops.

**Pull request merged**
