### PR TITLE
Modularize gatherV2

### PR DESCRIPTION
**Pull request by lina128**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4263)

### CODE REVIEW

**Review by tafsiri — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4263)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, @mattsoulanille, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/GatherV2.ts, line 88 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4263#-MMaP7o8BndyLk4VPCJ3:-MMaP7o8BndyLk4VPCJ4:b-w4ne31) ([raw file](https://github.com/tensorflow/tfjs/blob/001f4e02468ed864f4f59d81d9198ae3fb88ca5b/tfjs-backend-cpu/src/kernels/GatherV2.ts#L88)):*
> ```XML
>   const indicesBuf = backend.bufferSync(flattenIndex);
>   const xBuf = backend.bufferSync(flattenX);
>   const outBuf = buffer(flattenOutputShape, x.dtype);
> ```

Could we create `outBuf` in the `gatherV2Impl` function? I think we have relatively few functions that manipulate an out param passed to them (and returning void). I think it would make using it more similar to other impl functions. wdyt?

**Review by tafsiri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4263)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @lina128, and @mattsoulanille)

___
*[tfjs-backend-cpu/src/kernels/GatherV2.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4263#-MMaQeAe7ZZyWNF3JNUo:-MMaQeAe7ZZyWNF3JNUp:b-aod4ob) ([raw file](https://github.com/tensorflow/tfjs/blob/001f4e02468ed864f4f59d81d9198ae3fb88ca5b/tfjs-backend-cpu/src/kernels/GatherV2.ts#L24)):*
> ```XML
> import {reshape} from './Reshape';
> 
> export function gatherV2Impl<R extends Rank, D extends DataType>(
> ```

one more comment: I think you've generally been putting these impl functions into their own file. any particular reason to keep this one here?

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4263)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @mattsoulanille, and @tafsiri)

___
*[tfjs-backend-cpu/src/kernels/GatherV2.ts, line 24 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4263#-MMaQeAe7ZZyWNF3JNUo:-MN0tgIT8b5caIsQRkp5:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/001f4e02468ed864f4f59d81d9198ae3fb88ca5b/tfjs-backend-cpu/src/kernels/GatherV2.ts#L24)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

one more comment: I think you've generally been putting these impl functions into their own file. any particular reason to keep this one here?
</blockquote></details>

Done.
___
*[tfjs-backend-cpu/src/kernels/GatherV2.ts, line 88 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4263#-MMaP7o8BndyLk4VPCJ3:-MN0uj_iARLvRagV52XL:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/001f4e02468ed864f4f59d81d9198ae3fb88ca5b/tfjs-backend-cpu/src/kernels/GatherV2.ts#L88)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Could we create `outBuf` in the `gatherV2Impl` function? I think we have relatively few functions that manipulate an out param passed to them (and returning void). I think it would make using it more similar to other impl functions. wdyt?
</blockquote></details>

Done.

**Review by lina128 — COMMENTED** [review]
Thank you for the comments Yannick, PTAL.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4263#-:-MN0vZzi1oFj7OCbsAz6:b2u68b0)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @mattsoulanille, and @tafsiri)

**Review by tafsiri — APPROVED** [review]
Thanks

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4263#-:-MNOsTgE8LrOWvH81yvs:b-zcjvte)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @jinjingforever, @mattsoulanille, and @tafsiri)

**Pull request merged**
