### PR TITLE
webgpu: Use fma to fuse add and mul

### PR DESCRIPTION
**Pull request by qjia7**
PERF

FusedConv2D in stable diffusion model: 82ms -> 74ms

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7572)

### CODE REVIEW

**Review by gyagp — APPROVED** [review]
LGTM

**Comment by hujiajie** [comment]
@qjia7 I find FXC is smart enough to optimize `a * b + c` to a `mad` instruction without this patch, but probably you are using a different tensor shape or Chrome release. Can you double check the DXBC dump of FXC?

**Comment by qjia7** [comment]
> @qjia7 I find FXC is smart enough to optimize `a * b + c` to a `mad` instruction without this patch, but probably you are using a different tensor shape or Chrome release. Can you double check the DXBC dump of FXC?

Offline synced with Jiajie. Tint removed FXC's optimizations recently. That's why I can see the perf improvement by this PR. Anyway, the changes are still necessary since we can't depend on the underlying compiler for us to do the optimization.

**Review by xhcao — APPROVED** [review]
LGTM

**Pull request merged**
