### PR TITLE
Allow undefined element shape for TensorList

### PR DESCRIPTION
**Pull request by pyu10055**
fix https://github.com/tensorflow/tfjs/issues/4641

TensorList can have element_shape defined as following [-1, -1, 1], which is not supported by our reshape.
This would auto calculate the output element shape from the ArrayList and input elementShape param, as well as the tensors within the list.

 
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4657)

### CODE REVIEW

**Review by lina128 — COMMENTED** [review]
Hi Ping, can you give more context on the problem, how come there is [-1, -1, 1], could there be a case where tensor shape was [3, 3, 3], and elementShape is [-1, -1, 1], if so, what should the new tensor shape be?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4657#-:-MT33q7h-cQFE__OkxJG:b-pqq2im)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[tfjs-converter/src/executor/tensor_list.ts, line 212 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3-DpXEqCLrC5d1HNn:-MT3-DpXEqCLrC5d1HNo:b-yauu19) ([raw file](https://github.com/tensorflow/tfjs/blob/7ff0e1d6df249a655351fe62b997da3957b7b131/tfjs-converter/src/executor/tensor_list.ts#L212)):*
> ```XML
>         'TensorList shape mismatch: ');
>     const outputElementShape = findElementShape(this, elementShape);
>     return reshape(this.tensors[elementIndex], outputElementShape);
> ```

Will this cause memory leak? Should the reshaped tensor be stored and the original tensor be disposed?
___
*[tfjs-converter/src/executor/tensor_list_test.ts, line 227 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT32AXF-PdFM6EkPC_O:-MT32AXF-PdFM6EkPC_P:bd63dpo) ([raw file](https://github.com/tensorflow/tfjs/blob/7ff0e1d6df249a655351fe62b997da3957b7b131/tfjs-converter/src/executor/tensor_list_test.ts#L227)):*
> ```XML
>       test_util.expectArraysClose(await concat.data(), [1, 2]);
>     });
>     it('should fail for wildcard shape', async () => {
> ```

should not fail?
___
*[tfjs-converter/src/executor/tensor_list_test.ts, line 267 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT327idDKJmXIa6tmcv:-MT327idDKJmXIa6tmcw:bd63dpo) ([raw file](https://github.com/tensorflow/tfjs/blob/7ff0e1d6df249a655351fe62b997da3957b7b131/tfjs-converter/src/executor/tensor_list_test.ts#L267)):*
> ```XML
>       expect(memory().numTensors).toEqual(numTensors + 1);
>     });
>     it('should fail for wildcard shape', async () => {
> ```

should not fail?
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT31wF77_xhvQARBqXO:-MT31wF77_xhvQARBqXP:bonkv67) ([raw file](https://github.com/tensorflow/tfjs/blob/7ff0e1d6df249a655351fe62b997da3957b7b131/tfjs-converter/src/executor/tensor_utils.ts#L66)):*
> ```XML
>  */
> export function findElementShape(
>     list: TensorList, elementShape: number|number[]): number[] {
> ```

Why this doesn't apply to TensorArray?

**Review by pyu10055 — COMMENTED** [review]
tensor shape [3,3, 1] works with element shape [-1, -1, 1], the shape will be [3, 3, 1]. basically, users can set the element shape to don't care, and the output shape is the tensor shape itself.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4657#-:-MT3AV_x6nIJsOi8obe3:b-4e5zko)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-converter/src/executor/tensor_list.ts, line 212 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3-DpXEqCLrC5d1HNn:-MT3BSPQDBHEg7Z7hbxq:b-gty65m) ([raw file](https://github.com/tensorflow/tfjs/blob/2a30f5b69846749d8c22ea3d05ca7e7631426eda/tfjs-converter/src/executor/tensor_list.ts#L212)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Will this cause memory leak? Should the reshaped tensor be stored and the original tensor be disposed?
</blockquote></details>

the original tensor should not be disposed, since it is kept. Returned intermediate tensor should be disposed automatically by graph executor.
___
*[tfjs-converter/src/executor/tensor_list_test.ts, line 227 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT32AXF-PdFM6EkPC_O:-MT3B52aEPKM0Dnd5gUm:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/2a30f5b69846749d8c22ea3d05ca7e7631426eda/tfjs-converter/src/executor/tensor_list_test.ts#L227)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

should not fail?
</blockquote></details>

Done.
___
*[tfjs-converter/src/executor/tensor_list_test.ts, line 267 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT327idDKJmXIa6tmcv:-MT3B5TFCeJQpDRex6tA:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/2a30f5b69846749d8c22ea3d05ca7e7631426eda/tfjs-converter/src/executor/tensor_list_test.ts#L267)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

should not fail?
</blockquote></details>

Done.
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT31wF77_xhvQARBqXO:-MT3C4a66chHvFrKCk3U:b-mabblz) ([raw file](https://github.com/tensorflow/tfjs/blob/2a30f5b69846749d8c22ea3d05ca7e7631426eda/tfjs-converter/src/executor/tensor_utils.ts#L66)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Why this doesn't apply to TensorArray?
</blockquote></details>

TensorArray has no input elementShape, always use list elementShape and there is no reshape needed.

**Review by lina128 — COMMENTED** [review]
Can we have test cases for [-1, -1, 1]? The test cases below all use [-1, 1], which is handled by reshape anyway.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4657#-:-MT3MHZb7wMYx4cTFEaL:b-w8insq)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-converter/src/executor/tensor_list.ts, line 212 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3-DpXEqCLrC5d1HNn:-MT3M68A793nCkJSVU5H:b-seetin) ([raw file](https://github.com/tensorflow/tfjs/blob/2a30f5b69846749d8c22ea3d05ca7e7631426eda/tfjs-converter/src/executor/tensor_list.ts#L212)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

the original tensor should not be disposed, since it is kept. Returned intermediate tensor should be disposed automatically by graph executor.
</blockquote></details>

Can you add a test case to make sure it is disposed?
___
*[tfjs-converter/src/executor/tensor_list.ts, line 53 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3Mkv24bQdxT2c8jOm:-MT3Mkv36Kx5PlGysK4X:b6331x2) ([raw file](https://github.com/tensorflow/tfjs/blob/4705d4498e814d9f29b08ce743d91c0ddec70216/tfjs-converter/src/executor/tensor_list.ts#L53)):*
> ```XML
>    */
>   constructor(
>       readonly tensors: Tensor[], readonly elementShape: number|number[],
> ```

Is there actually elementShape of type number, not number[] passed to this constructor? If so, can you update doccomment above, with explanation on what does single number mean for elementShape?
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT31wF77_xhvQARBqXO:-MT3NgCECn0cBKLVkDLF:b-4hvi0m) ([raw file](https://github.com/tensorflow/tfjs/blob/2a30f5b69846749d8c22ea3d05ca7e7631426eda/tfjs-converter/src/executor/tensor_utils.ts#L66)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

TensorArray has no input elementShape, always use list elementShape and there is no reshape needed.
</blockquote></details>

Got it.
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 62 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3NzJX2BNT5ymBN2BN:-MT3NzJX2BNT5ymBN2BO:b4tougl) ([raw file](https://github.com/tensorflow/tfjs/blob/4705d4498e814d9f29b08ce743d91c0ddec70216/tfjs-converter/src/executor/tensor_utils.ts#L62)):*
> ```XML
>  * Generate the output element shape from the list and input param.
>  * @param list
>  * @param elementShape
> ```

Update doccomment for listElementShape, tensors and elementShape. Update method description.
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 64 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3NOZk5G4zzYaJMw6T:-MT3NOZk5G4zzYaJMw6U:b-jq45yq) ([raw file](https://github.com/tensorflow/tfjs/blob/4705d4498e814d9f29b08ce743d91c0ddec70216/tfjs-converter/src/executor/tensor_utils.ts#L64)):*
> ```XML
>  * @param elementShape
>  */
> export function findElementShape(
> ```

It's better to be named inferElementShape to be consistent with inferFromImplicitShape.
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 67 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3OdAl-Nl1qqGu1nyO:-MT3OdAl-Nl1qqGu1nyP:bj3l2kb) ([raw file](https://github.com/tensorflow/tfjs/blob/4705d4498e814d9f29b08ce743d91c0ddec70216/tfjs-converter/src/executor/tensor_utils.ts#L67)):*
> ```XML
>     listElementShape: number|number[], tensors: Tensor[],
>     elementShape: number|number[]): number[] {
>   let partialShape = mergeElementShape(listElementShape, elementShape);
> ```

Why do we need this step? Why not just jump to the if(notFullDefinedShape) code block directly?

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4657)* status: 0 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-converter/src/executor/tensor_list.ts, line 212 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3-DpXEqCLrC5d1HNn:-MT3RebUDAvjHQVVhBSY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/2a30f5b69846749d8c22ea3d05ca7e7631426eda/tfjs-converter/src/executor/tensor_list.ts#L212)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can you add a test case to make sure it is disposed?
</blockquote></details>

Done.
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 64 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3NOZk5G4zzYaJMw6T:-MT3Qhsk1qjb_G340PVr:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/4705d4498e814d9f29b08ce743d91c0ddec70216/tfjs-converter/src/executor/tensor_utils.ts#L64)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

It's better to be named inferElementShape to be consistent with inferFromImplicitShape.
</blockquote></details>

Done.
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 67 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3OdAl-Nl1qqGu1nyO:-MT3QxJe3tY4phb44kA_:bt656y9) ([raw file](https://github.com/tensorflow/tfjs/blob/4705d4498e814d9f29b08ce743d91c0ddec70216/tfjs-converter/src/executor/tensor_utils.ts#L67)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Why do we need this step? Why not just jump to the if(notFullDefinedShape) code block directly?
</blockquote></details>

it first merge the list elementShape with input elementShape, if it is fully defined it would used that, otherwise use the shape of tensors from the list.

**Review by pyu10055 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4657)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[tfjs-converter/src/executor/tensor_list.ts, line 53 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3Mkv24bQdxT2c8jOm:-MT3Tu6r1Q5BCB2Ajh92:bdo6yxc) ([raw file](https://github.com/tensorflow/tfjs/blob/4705d4498e814d9f29b08ce743d91c0ddec70216/tfjs-converter/src/executor/tensor_list.ts#L53)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Is there actually elementShape of type number, not number[] passed to this constructor? If so, can you update doccomment above, with explanation on what does single number mean for elementShape?
</blockquote></details>

both number and number[] can be passed to the constructor. updated the description.
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 66 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT31wF77_xhvQARBqXO:-MT3U0IHCSgAMyussVFz:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/2a30f5b69846749d8c22ea3d05ca7e7631426eda/tfjs-converter/src/executor/tensor_utils.ts#L66)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Got it.
</blockquote></details>

Done.
___
*[tfjs-converter/src/executor/tensor_utils.ts, line 62 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3NzJX2BNT5ymBN2BN:-MT3U2O7CzFotnSGMhjA:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/4705d4498e814d9f29b08ce743d91c0ddec70216/tfjs-converter/src/executor/tensor_utils.ts#L62)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Update doccomment for listElementShape, tensors and elementShape. Update method description.
</blockquote></details>

Done.

**Review by lina128 — APPROVED** [review]
Thank you for the fix, Ping!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4657#-:-MT3bNNE4xr11LT585v-:btco1bc)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[tfjs-converter/src/executor/tensor_list.ts, line 53 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4657#-MT3Mkv24bQdxT2c8jOm:-MT3aju-09717DkDHnK8:b-k6hnn7) ([raw file](https://github.com/tensorflow/tfjs/blob/4705d4498e814d9f29b08ce743d91c0ddec70216/tfjs-converter/src/executor/tensor_list.ts#L53)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

both number and number[] can be passed to the constructor. updated the description.
</blockquote></details>

Can you provide an example for each, because this is still not very clear to me as a reader. Thank you!

**Comment by luke-iqt** [comment]
Thanks for a super fast turn around @lina128 and @pyu10055 !!  I will keep an eye on NPM for the next version to drop.

**Comment by umitkacar** [comment]
How do I convert this update to a package?
I am using ` tf.min.js`
`<script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs@3.0.0/dist/tf.min.js"></script>`

**Comment by AlexAndrascu** [comment]
@lina128 / @pyu10055 unsure how this fixes #4641 ? Maybe that issue should stay open for now until a fix is documented ?   
Can you please detail how to convert TF2 Saved Models to TFJS 3.0.0 ?

**Comment by mihaelagrigore** [comment]
> 
> 
> @lina128 / @pyu10055 unsure how this fixes #4641 ? Maybe that issue should stay open for now until a fix is documented ?
> Can you please detail how to convert TF2 Saved Models to TFJS 3.0.0 ?

@AlexAndrascu If you use this tool https://github.com/tensorflow/tfjs/tree/master/tfjs-converter and follow the instructions in th readme, you'll have an evironment with Python 3.6.8, tensorflow 2.4.1 and tensorflowjs 3.1.0 where you run the converter to get a tfjs from SavedModel.

**Comment by AlexAndrascu** [comment]
> > @lina128 / @pyu10055 unsure how this fixes #4641 ? Maybe that issue should stay open for now until a fix is documented ?
> > Can you please detail how to convert TF2 Saved Models to TFJS 3.0.0 ?
> 
> @AlexAndrascu If you use this tool https://github.com/tensorflow/tfjs/tree/master/tfjs-converter and follow the instructions in th readme, you'll have an evironment with Python 3.6.8, tensorflow 2.4.1 and tensorflowjs 3.1.0 where you run the converter to get a tfjs from SavedModel.

Thank you Mihaela, I managed to convert it fine but just like others I was getting the shape mismatch error. 
It seems that error is fixed in 3.1.0 indeed.

**Pull request merged**
