### PR TITLE
Add kernel StringToHashBucketFast for CPU and WebGL backend

### PR DESCRIPTION
**Pull request by ahmedsabie**
ref #4838
TensorFlow python version is defined  [here](https://www.tensorflow.org/api_docs/python/tf/strings/to_hash_bucket_fast)
c++ kernel definition is  [here](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/core/kernels/string_to_hash_bucket_op.h)

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5052)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5052)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-backend-cpu/src/kernels/StringToHashBucketFast.ts, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_MzBmh7imYW-zaWoqe:-M_MzBmiCqZkNW7nU8H5:b-rf7vqz) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-backend-cpu/src/kernels/StringToHashBucketFast.ts#L36)):*
> ```XML
>     throw new Error('Input must be of datatype string');
>   }
>   if (numBuckets <= 0 || numBuckets > 2147483648) {
> ```

you might want to consider use built-in constant `Number.MAX_SAFE_INTEGER`, but practically we probably should only allow much smaller bucket size if it affects the memory footprint.
___
*[tfjs-backend-cpu/src/kernels/StringToHashBucketFast_impl.ts, line 20 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_MzjrkDi4J2s1t1RQw:-M_MzjrkDi4J2s1t1RQx:b-pj5d8x) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-backend-cpu/src/kernels/StringToHashBucketFast_impl.ts#L20)):*
> ```XML
> import {TypedArray, util} from '@tensorflow/tfjs-core';
> 
> // import {fingerPrint64} from '@tensorflow/tfjs-core/dist/hash_util';
> ```

remove this import?
___
*[tfjs-backend-webgl/src/kernels/StringToHashBucketFast.ts, line 35 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_MzrUO0ZEj67TUUQ9B:-M_MzrUO0ZEj67TUUQ9C:b-phqdlp) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-backend-webgl/src/kernels/StringToHashBucketFast.ts#L35)):*
> ```XML
>     throw new Error('Input must be of datatype string');
>   }
>   if (numBuckets <= 0 || numBuckets > 2147483648) {
> ```

similar to CPU op, use `Number.MAX_SAFE_INTEGER`
___
*[tfjs-core/src/hash_util.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N-NrDD2qvopbqSy35:-M_N-NrDD2qvopbqSy36:b-55q4un) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util.ts#L19)):*
> ```XML
> 
> // tslint:disable-next-line:no-require-imports variable-name
> const Long = require('long');
> ```

you can add the type definition  https://www.npmjs.com/package/@types/long  for long package in the package.json and use import statement instead of require.
___
*[tfjs-core/src/hash_util.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N5ops1wUPOL1-iqyX:-M_N5ops1wUPOL1-iqyY:b2m3fpj) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util.ts#L21)):*
> ```XML
> const Long = require('long');
> 
> export function hexToLong(hex: string): Long {
> ```

looks like tensorflow uses farmhash for the fingerprint, can you use this package https://www.npmjs.com/package/farmhash ?
___
*[tfjs-core/src/hash_util.ts, line 138 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N13H6EXYbRRPeOnJi:-M_N13H6EXYbRRPeOnJj:b-734j6c) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util.ts#L138)):*
> ```XML
> }
> 
> export function fingerPrint64(s: Uint8Array, len = s.length): Long {
> ```

do you have the link to the hash function in TF?
___
*[tfjs-core/src/hash_util_test.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N1Kqa-edsOnm9cpCi:-M_N1Kqa-edsOnm9cpCj:b-lzv50w) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util_test.ts#L21)):*
> ```XML
> import {ALL_ENVS, describeWithFlags} from './jasmine_util';
> 
> class ACMRandom {
> ```

give a short description on the purpose of this class.
___
*[tfjs-core/src/hash_util_test.ts, line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N-lVH4uLbtAwc8Sr-:-M_N-lVH4uLbtAwc8Sr0:b-nsqsw7) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util_test.ts#L22)):*
> ```XML
> 
> class ACMRandom {
>   static readonly M = 2147483647;
> ```

give a more descriptive name for the constant, and keep it all uppercased.
For example, MAX_INT32
___
*[tfjs-core/src/hash_util_test.ts, line 60 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N1gSp5cz4L4MY0hHQ:-M_N1gSp5cz4L4MY0hHR:b-4bcxrg) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util_test.ts#L60)):*
> ```XML
> 
> describeWithFlags('hash_util', ALL_ENVS, () => {
>   it('check incremental hashes', () => {
> ```

how long does this test take?
___
*[tfjs-core/src/hash_util_test.ts, line 111 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N1oPqAbHkSkI492Ul:-M_N1oPqAbHkSkI492Um:bh3o6fy) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util_test.ts#L111)):*
> ```XML
>     // char that is also a hash of h.  Neither hash needs to be particularly
>     // good.
> ```

remove empty line

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5052)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-core/src/hash_util.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N5ops1wUPOL1-iqyX:-M_OWQTC0bSNcTp9fbzQ:b-u85m7m) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util.ts#L21)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

looks like tensorflow uses farmhash for the fingerprint, can you use this package https://www.npmjs.com/package/farmhash ?
</blockquote></details>

The package uses C++ bindings it looks like and says "The hash methods are platform dependent. Different CPU architectures, for example 32-bit vs 64-bit, Intel vs ARM, SSE4.2 vs AVX might produce different results for a given input." I am having some issues running it right now but i'll let you know what results I get once its working v.s. the Long implementation which is native JS
___
*[tfjs-core/src/hash_util.ts, line 138 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N13H6EXYbRRPeOnJi:-M_OXK2w03bPD5uIWDdG:b-niyfzi) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util.ts#L138)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

do you have the link to the hash function in TF?
</blockquote></details>

It's called from here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/fingerprint.h and I believe this is the farmhash header its using https://github.com/google/farmhash/blob/master/dev/farmhash.h

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5052)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-core/src/hash_util.ts, line 21 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N5ops1wUPOL1-iqyX:-M_RXwcX2nZjOWVzcDab:b-9lvvhi) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util.ts#L21)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

The package uses C++ bindings it looks like and says "The hash methods are platform dependent. Different CPU architectures, for example 32-bit vs 64-bit, Intel vs ARM, SSE4.2 vs AVX might produce different results for a given input." I am having some issues running it right now but i'll let you know what results I get once its working v.s. the Long implementation which is native JS
</blockquote></details>

I see, then it should not be used. sorry for the wrong direction.

**Review by ahmedsabie — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5052)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie, @lina128, and @pyu10055)

___
*[tfjs-backend-cpu/src/kernels/StringToHashBucketFast.ts, line 36 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_MzBmh7imYW-zaWoqe:-M_TFHJo-mkDyQBbi8st:bz0g6aq) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-backend-cpu/src/kernels/StringToHashBucketFast.ts#L36)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you might want to consider use built-in constant `Number.MAX_SAFE_INTEGER`, but practically we probably should only allow much smaller bucket size if it affects the memory footprint.
</blockquote></details>

I looked into the existing tfjs functions and calling with values above 2^31 simply get modded so I removed the check to keep the consistent overflow behavior

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5052)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[tfjs-core/src/hash_util.ts, line 19 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_N-NrDD2qvopbqSy35:-M_WeStx3JREp6eA53EQ:biojjgp) ([raw file](https://github.com/tensorflow/tfjs/blob/51f021736c40918ce3ccccf7a4bfdb90207502b4/tfjs-core/src/hash_util.ts#L19)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you can add the type definition  https://www.npmjs.com/package/@types/long  for long package in the package.json and use import statement instead of require.
</blockquote></details>

Fixed by importing the default export using above syntax.
___
*[tfjs-core/src/hash_util_test.ts, line 40 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5052#-M_WehTV-vRgjcSZgQXI:-M_WehTV-vRgjcSZgQXJ:basho06) ([raw file](https://github.com/tensorflow/tfjs/blob/3b5db5d886454e8889b605023a5a6af012d2dfde/tfjs-core/src/hash_util_test.ts#L40)):*
> ```XML
> 
>   private next() {
>     const A = hexToLong('41A7');  // bits 14, 8, 7, 5, 2, 1, 0
> ```

update the constant `A` name  here similar to `MAX_INT32`

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5052)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

**Pull request merged**
