### PR TITLE
[webgpu] Add WGSL shader for Tanh

### PR DESCRIPTION
**Pull request by haoyunfeix**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5647)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
@qjia7 @axinging @xhcao @gyagp, PTAL

**Comment by axinging** [comment]
LGTM. Please make sure the unit test for tanh is added into https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgpu/src/setup_test.ts.

**Review by qjia7 — APPROVED** [review]
LGTM after adding tests

**Review by qjia7 — APPROVED** [review]
LGTM

**Pull request merged**
