### PR TITLE
Fix webgl backend memory leak in firefox

### PR DESCRIPTION
**Pull request by jinjingforever**
In #3319, users reported that there is significant memory leak in firefox when running the bodypix demo with the webgl backend. I tracked down the problem which was caused by calling `<tensor>.data()` [here](https://github.com/tensorflow/tfjs-models/blob/master/body-pix/src/body_pix_model.ts#L549). Looks like in the webgl backend's `read()` method, we created a WebGLBuffer to read data but we never deleted the buffer. This didn't cause issues in Chrome because (I guess) the buffer might get automatically deleted which is not the case in firefox.

I added the deleteBuffer call and the memory leak was gone from my local testing. Will update the demo after this PR is merged.

BTW, we also use `<tensor>.data()` in some other places (like in blazepose with tfjs-webgl backend). It has [memory leak in firefox](https://drive.google.com/file/d/1a8rJNMgkC0u2M21A4orlYihvV7buziLd/view?usp=sharing) too. This should also fix that. 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5193)

### CODE REVIEW

**Review by lina128 — APPROVED** [review]
Thank you Jing!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5193#-:-MbgtMffCipZIPRk24ap:b-t54jjn)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055)

**Review by pyu10055 — APPROVED** [review]
Thank you Jing for tracking this down.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5193#-:-Mbgyh4N89p8Q3PBi3pk:b-aoomts)* status: :shipit: complete! 2 of 1 approvals obtained

**Review by pyu10055 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5193#-:-MbgynZo5rlHzQOCvlHa:b-jbsf8z)* status: :shipit: complete! 2 of 1 approvals obtained

**Comment by danrossi** [comment]
I just discovered this was about to report with tests.

**Comment by danrossi** [comment]
Not released. I guess we have to build the project and looks difficult.

**Comment by jinjingforever** [comment]
Hi @danrossi, sorry for the delay. We plan to do a release this week or next week. Thanks!

**Pull request merged**
