### PR TITLE
[webgl] Modularize Conv2D and FusedConv2D.

### PR DESCRIPTION
**Pull request by annxingyuan**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4162)

### CODE REVIEW

**Review by tafsiri — APPROVED** [review]
LGTM. What a history of optimization on conv2Ds!

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4162#-:-ML9ovLK-9dS-mwKvOqQ:b-t8h1m9)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Conv2D_impl.ts, line 40 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4162#-ML9oVM-AfgycfJAO1DL:-ML9oVM-AfgycfJAO1DM:b-l0ib7v) ([raw file](https://github.com/tensorflow/tfjs/blob/a3d44c894cb18031b2c33866d60b0db4b1e8fbed/tfjs-backend-webgl/src/kernels/Conv2D_impl.ts#L40)):*
> ```XML
> };
> 
> export function conv2dByMatMul({
> ```

any references to the algorithmic approach used here that could be added in a doc comment for future reference?
___
*[tfjs-backend-webgl/src/kernels/Conv2D_impl.ts, line 172 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4162#-ML9oL8-8jqSJh2PiEcM:-ML9oL8-8jqSJh2PiEcN:b1rvhxg) ([raw file](https://github.com/tensorflow/tfjs/blob/a3d44c894cb18031b2c33866d60b0db4b1e8fbed/tfjs-backend-webgl/src/kernels/Conv2D_impl.ts#L172)):*
> ```XML
> }
> 
> export function conv2dWithIm2Row({
> ```

any references to the im2row algorithm approach that could be added in a doc comment for future reference?

**Comment by tafsiri** [comment]
I'm also sticking to this interface in my conv pr for node, matches the approach in cpu as well. cc @lina128

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4162)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Conv2D_impl.ts, line 40 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4162#-ML9oVM-AfgycfJAO1DL:-MLDg_EA9KWoqKPmcqJK:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/4826e935a592366e2c51d2f76fdcc94d9b51a9e3/tfjs-backend-webgl/src/kernels/Conv2D_impl.ts#L40)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

any references to the algorithmic approach used here that could be added in a doc comment for future reference?
</blockquote></details>

Done
___
*[tfjs-backend-webgl/src/kernels/Conv2D_impl.ts, line 172 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4162#-ML9oL8-8jqSJh2PiEcM:-MLDiIkJ0NvtGGIqVPaX:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/4826e935a592366e2c51d2f76fdcc94d9b51a9e3/tfjs-backend-webgl/src/kernels/Conv2D_impl.ts#L172)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

any references to the im2row algorithm approach that could be added in a doc comment for future reference?
</blockquote></details>

Done

**Review by lina128 — COMMENTED** [review]
Love the doccomments!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4162#-:-MLEYnX32u9ACTyzEmJt:b-x2sh1v)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @tafsiri)

**Pull request merged**
