### PR TITLE
webgpu: Support 2x4 output for Conv2DBackpropInput

### PR DESCRIPTION
**Pull request by qjia7**
Conv2DBackpropInput in ArPortraitDepth
26.32ms -> 14.17ms on CFL
6.91ms -> 4.70ms on TGL
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7371)

### CODE REVIEW

**Comment by qjia7** [comment]
With the second commit [a734dd8](https://github.com/tensorflow/tfjs/pull/7371/commits/a734dd89ff8ccc4a21345ecfe03b2afc9ea6956a), the time of Conv2DBackpropInput  is further reduced (26.32ms -> 14.17ms -> 10.27ms on CFL)

**Review by xhcao — APPROVED** [review]
LGTM, please take care of WGSL code typeset.

**Review by Linchenn — APPROVED** [review]
LGTM, great finding!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7371#-:-NOQkIew6HMi0UiWG6DW:b-21ykmg)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @gyagp and @qjia7)

___
*[`tfjs-backend-webgpu/src/conv_backprop_webgpu.ts` line 142 at r2](https://reviewable.io/reviews/tensorflow/tfjs/7371#-NOQSy-543zjjXB7cbHb:-NOQSy-543zjjXB7cbHc:bnqk2mu) ([raw file](https://github.com/tensorflow/tfjs/blob/d9c9ad9e241f1c43efe6d300dbe580739542c4fc/tfjs-backend-webgpu/src/conv_backprop_webgpu.ts#L142)):*
> ```XML
>               dotProd[0] = dotProd[0] + tmpval;
>             }
>           } else if (bDyCVal2) {
> ```

We may not need ` if (bDyCVal2)` because we have checked `(bDyCVal == false &&  bDyCVal2 == false)` before. Or we could remove `if (bDyCVal == false &&  bDyCVal2 == false)` above.

**Review by qjia7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7371)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @gyagp and @Linchenn)

___
*[`tfjs-backend-webgpu/src/conv_backprop_webgpu.ts` line 142 at r2](https://reviewable.io/reviews/tensorflow/tfjs/7371#-NOQSy-543zjjXB7cbHb:-NOSB8GL8xEZtt8p6NwP:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/d9c9ad9e241f1c43efe6d300dbe580739542c4fc/tfjs-backend-webgpu/src/conv_backprop_webgpu.ts#L142)):*
<details><summary><i>Previously, Linchenn wrote…</i></summary><blockquote>

We may not need ` if (bDyCVal2)` because we have checked `(bDyCVal == false &&  bDyCVal2 == false)` before. Or we could remove `if (bDyCVal == false &&  bDyCVal2 == false)` above.
</blockquote></details>

Done.

**Pull request merged**
