### PR TITLE
Migrate from dat.gui to lil.gui for local benchmark tool

### PR DESCRIPTION
**Pull request by Linchenn**
Since Dat.gui is updated a year ago and migration to Lil.gui is almost drop-in, this PR does:
1. Changes API usage according to API changes, https://lil-gui.georgealways.com/#Migrating.
2. Tuned the style for new UI.

New UI would be like:
image

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7538)

### CODE REVIEW

**Review by mattsoulanille — APPROVED** [review]
LGTM

**Comment by Linchenn** [comment]
cc @qjia7 @gyagp This change would update HTML elements of the local benchmark tool, so it may cause problems for your testing platform. Please let me know if it really cause a problem.

**Comment by gyagp** [comment]
Thanks for the heads-up! Our daily test framework is based on Puppeteer (I changed to it from Playwright as the latter caused some problems recently), and I don't expect big challenge to adapt to Lil.gui. So feel free to merge this:)

**Comment by Linchenn** [comment]
This PR would only changes the elements in the control panel. Thanks Yang!

**Pull request merged**
