### PR TITLE
[webgl] merge CumProdProgram and CumSumProgram

### PR DESCRIPTION
**Pull request by axinging**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6325)

### CODE REVIEW

**Comment by axinging** [comment]
@qjia7 @haoyunfeix @xhcao @gyagp , PTAL

**Comment by qjia7** [comment]
Thanks for the refactor. LGTM and add @lina128 @pyu10055 to review it. Thanks.

**Review by pyu10055 — APPROVED** [review]
@axinging @qjia7 Great work, thank you for the refactoring!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6325#-:-N-cy7YbATSN-zM0cdjy:b-gu9d7i)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128)

**Comment by axinging** [comment]
@pyu10055 @lina128 , Please help to merge, thanks

**Comment by axinging** [comment]
@pyu10055 @lina128 , Please help to merge. 
Sorry to ping you again, in case you miss this PR.

**Review by lina128 — APPROVED** [review]
Thank you for the refactor!

**Pull request merged**
