### PR TITLE
[E2E] Fix test correctness issue

### PR DESCRIPTION
**Pull request by haoyunfeix**
Set backend before benchmark.load() to avoid move data between two
backends

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5315)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
When run correctness test for WebGPU backend, current logic is
**setBackend('webgpu') => generate model.inputs => setBackend('cpu')** => predict => setBackend('webgpu') => predict => compare
We generate inputs data on webgpu but consume on cpu backend, data has to moveData between two backends, it will invoke readSync method on WebGPU backend which not supported well.

So change the order to:
**setBackend('webgpu') => setBackend('cpu') => generate model.inputs** => predict => setBackend('webgpu') => predict => compare

**Comment by haoyunfeix** [comment]
@qjia7 @axinging @xhcao @gyagp, PTAL

**Review by qjia7 — COMMENTED** [review]
It's just a workaround to resolve the failures in our automated testing to make sure the test can get correct result. However, it didn't resolve the issue essentially (see bug #5092 ).

Let's see other reviewers attitude for this. Thanks.

@lina128 @pyu10055 @jinjingforever take a look, thanks.

**Review by lina128 — APPROVED** [review]
SG to me to unblock you. LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5315#-:-Mf47BM_6BA-Ov43ghwh:bqflp9a)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @pyu10055)

**Pull request merged**
