### PR TITLE
webgpu: Use uniform for pad/fill constants

### PR DESCRIPTION
**Pull request by qjia7**
This is a follow-up for PR:4779 for webgpu backend.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4781)

### CODE REVIEW

**Comment by qjia7** [comment]
@gyagp @xhcao @axinging @haoyunfeix Please take a look, thanks.

**Review by haoyunfeix — COMMENTED** [review]
LGTM

**Comment by qjia7** [comment]
@lina128 @kainino0x take a look, thanks.

Previously, it only supported uint/int uniform values. This pr also makes it support float uniform value.

**Review by kainino0x — APPROVED** [review]
LGTM, sorry for the delay

**Pull request merged**
