### PR TITLE
Refactor type conversion for read back

### PR DESCRIPTION
**Pull request by axinging**
Bug: https://github.com/tensorflow/tfjs/issues/6965

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7044)

### CODE REVIEW

**Comment by axinging** [comment]
@qjia7 @xhcao @haoyunfeix @gyagp  PTAL

**Review by qjia7 — COMMENTED** [review]
Based on #6965's description, it seems that [ResizeNearestNeighbor ](https://github.com/tensorflow/tfjs/blob/2eafff718d6df2ab5571f9778a1e09c6a517499d/tfjs-backend-cpu/src/kernels/ResizeNearestNeighbor.ts#L39)doesn't create the right TypedArray buffer based on `dType`. Should we fix it there or do the post processing to cast the data to the right type when reading data back like other backends? @pyu10055 @mattsoulanille

**Comment by axinging** [comment]
@pyu10055 @mattsoulanille, PTAL

**Comment by axinging** [comment]
@pyu10055 @mattsoulanille, PTAL

This PR can fix  DeepLabV3(in e2e) failure.

**Review by mattsoulanille — APPROVED** [review]
Thanks for the ping @axinging, and sorry for not seeing this earlier. This approach looks good to me.

I think we should also fix `ResizeNearestNeighbor`. Like you said in #6965, it's incorrectly handling the dtype. I can do this in another PR.

**Comment by axinging** [comment]
Thanks @mattsoulanille.
@pyu10055 , Do you have any idea about this change?

**Review by pyu10055 — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/7044)* status: :shipit: complete! 2 of 1 approvals obtained

**Pull request merged**
