### PR TITLE
webgl: Refactor the custom uniforms support

### PR DESCRIPTION
**Pull request by qjia7**
This PR moves all uniform operations into gpgpu_math file. The program
only process the uniforms and data. With this change, it's convenient to
support a new custom uniform.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5258)

### CODE REVIEW

**Comment by qjia7** [comment]
@pyu10055 @lina128 @jinjingforever Please take a look, thanks.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for the great refactoring!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5258#-:-MdNDHIT-gHcTR5aZ4LM:b-cxrdvu)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @qjia7)

___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 43 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdN8aPY8f0e9fWI56wk:-MdN8aPY8f0e9fWI56wl:blmsaml) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L43)):*
> ```XML
>    */
>   outPackingScheme?: PackingScheme;
>   customUniforms?: Array<{name: string; type: string;}>;
> ```

you should defined a typescript type  `type UniformType ='float' | 'vec2' | 'vec3'  ....`, this would ensure type checking.
Also good to define a type for customUniforms
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 113 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdNCmdP-w092e9EIlgc:-MdNCmdQ-eF6LyOsPkxO:brxzh6g) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L113)):*
> ```XML
>   }
> 
>   const customUniformLocations: WebGLUniformLocation[] = [];
> ```

it is will be good use a map for the location, so callers of the program can use a mapped uniformValues instead of an array.
since the order of indexing for might be difference on difference system, the callers might not know the correct order to provide the values.
With a map, the order is not needed.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 117 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdN9mO13Ydumr4Y0L0X:-MdN9mO13Ydumr4Y0L0Y:b-tblf92) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L117)):*
> ```XML
>     program.customUniforms.forEach((d, i) => {
>       const location = gpgpu.getUniformLocation(
>           webGLProgram, d.name.split('[')[0], shouldThrow);
> ```

why it need to spit the name string by '['? good to add a comment here
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 231 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdN93Ak6TwAkCFPHAvd:-MdN93Ak6TwAkCFPHAve:bqd5slj) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L231)):*
> ```XML
>         gpgpu.gl.uniform1fv(
>             binary.customUniformLocations[i], customUniformValues[i]);
>       } else if (d.type === 'vec4') {
> ```

should we exhaust the uniform variable types here (`vec2`, 'vec3`, ...)
___
*[tfjs-backend-webgl/src/shader_compiler.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdNAALo7joKWGxFzAxZ:-MdNAALo7joKWGxFzAx_:b-1l8xtf) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/shader_compiler.ts#L39)):*
> ```XML
>   userCode: string;
>   packedInputs?: boolean;
>   customUniforms?: Array<{name: string; type: string;}>;
> ```

should the customUniforms use the defined type?

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5258)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @qjia7)

**Review by qjia7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5258)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @pyu10055)

___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 43 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdN8aPY8f0e9fWI56wk:-MdQeyjr8kxNTM_E7ZEI:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L43)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

you should defined a typescript type  `type UniformType ='float' | 'vec2' | 'vec3'  ....`, this would ensure type checking.
Also good to define a type for customUniforms
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 113 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdNCmdP-w092e9EIlgc:-MdQg6gs0gfCYJrPwgRY:b-z38eda) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L113)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

it is will be good use a map for the location, so callers of the program can use a mapped uniformValues instead of an array.
since the order of indexing for might be difference on difference system, the callers might not know the correct order to provide the values.
With a map, the order is not needed.
</blockquote></details>

Is your concern that the push sequence may be different with `i` in `customUniforms`? Will `customUniformLocations[i] = location;` resolve the issue? Anyway, I have changed `customUniformLocations` type into a map.
About the issue that you said `the order of indexing for might be difference on difference system`, I am a little confused. If I have an array A = ['a' , 'b', 'c'], and B is generated based on A index B = ['aa', 'bb', 'cc'], I expect B[0] will be 'aa', B[1] will be [bb] and B[2] will be 'cc' on all platforms. But in your point, on different platform, B[0] will print different value?

For using a mapped uniformValues， do you want me to change `customUniformValues: number[][]` -> `customUniformValues: {[name: string]: number[]}`?
One concern in my opinion is that if we use type `{[name: string]: number[]}`,
the name string will be explicitly declared in two places. One is in the src/kernels/xxx.ts, the other is in src/xxx_gpu.ts. It's easy to have typo in two places. 
 for example, the `customValues` in `src/kernels/ClipByValue.ts`
before:
```
const customValues = [[clipValueMin], [clipValueMax]];
```
After
```
const customValues = {'minVal': [clipValueMin], 'maxVal': [clipValueMax]};
```

And in the clip_gpu.ts, we use uniform name string as below:
```
  customUniforms = [
    {name: 'minVal', type: 'float' as UniformType},
    {name: 'maxVal', type: 'float' as UniformType}
  ];
```

But if you think it's not a problem, I can change it as you said.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 117 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdN9mO13Ydumr4Y0L0X:-MdR4sv83u4omUFtZ-GY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L117)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why it need to spit the name string by '['? good to add a comment here
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 231 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdN93Ak6TwAkCFPHAvd:-MdR4w1S0SUkEMLAYA1A:biq7u5y) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L231)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should we exhaust the uniform variable types here (`vec2`, 'vec3`, ...)
</blockquote></details>

Done.
Previously, I just wanted to reduce some if checking since some types are never used in current webgl.
___
*[tfjs-backend-webgl/src/shader_compiler.ts, line 39 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdNAALo7joKWGxFzAxZ:-MdR5DvzB9g_YeFipyg-:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/shader_compiler.ts#L39)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should the customUniforms use the defined type?
</blockquote></details>

Done.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5258)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @qjia7)

___
*[tfjs-backend-webgl/src/fill_gpu.ts, line 25 at r2](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdVPvZ6-FROvUwqQS4B:-MdVPvZ6-FROvUwqQS4C:b-uoduw7) ([raw file](https://github.com/tensorflow/tfjs/blob/8a29a6125f9978d97b3541f6e3476fabe4a4c605/tfjs-backend-webgl/src/fill_gpu.ts#L25)):*
> ```XML
>   outputShape: number[] = [];
>   userCode: string;
>   customUniforms = [{name: 'value', type: 'float' as UniformType}];
> ```

does it throw error if `float` is not casted to `UniformType`?
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 113 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdNCmdP-w092e9EIlgc:-MdVP7wu7F3WwJSpf876:b-jdk8z4) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L113)):*
<details><summary><i>Previously, qjia7 (Jiajia Qin) wrote…</i></summary><blockquote>

Is your concern that the push sequence may be different with `i` in `customUniforms`? Will `customUniformLocations[i] = location;` resolve the issue? Anyway, I have changed `customUniformLocations` type into a map.
About the issue that you said `the order of indexing for might be difference on difference system`, I am a little confused. If I have an array A = ['a' , 'b', 'c'], and B is generated based on A index B = ['aa', 'bb', 'cc'], I expect B[0] will be 'aa', B[1] will be [bb] and B[2] will be 'cc' on all platforms. But in your point, on different platform, B[0] will print different value?

For using a mapped uniformValues， do you want me to change `customUniformValues: number[][]` -> `customUniformValues: {[name: string]: number[]}`?
One concern in my opinion is that if we use type `{[name: string]: number[]}`,
the name string will be explicitly declared in two places. One is in the src/kernels/xxx.ts, the other is in src/xxx_gpu.ts. It's easy to have typo in two places. 
 for example, the `customValues` in `src/kernels/ClipByValue.ts`
before:
```
const customValues = [[clipValueMin], [clipValueMax]];
```
After
```
const customValues = {'minVal': [clipValueMin], 'maxVal': [clipValueMax]};
```

And in the clip_gpu.ts, we use uniform name string as below:
```
  customUniforms = [
    {name: 'minVal', type: 'float' as UniformType},
    {name: 'maxVal', type: 'float' as UniformType}
  ];
```

But if you think it's not a problem, I can change it as you said.
</blockquote></details>

I think your original design of array is good, I was not paying enough attention, I thought it is a map.
___
*[tfjs-backend-webgl/src/gpgpu_math.ts, line 117 at r1](https://reviewable.io/reviews/tensorflow/tfjs/5258#-MdN9mO13Ydumr4Y0L0X:-MdVQkFuAXRnOIq9kyBG:bncipf7) ([raw file](https://github.com/tensorflow/tfjs/blob/60d15733ad34fdea99dafa757e9352effb785dcb/tfjs-backend-webgl/src/gpgpu_math.ts#L117)):*
<details><summary><i>Previously, qjia7 (Jiajia Qin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I did not see and uniformName ends with `[ ]`, can you share a link to the shader?
what is the purpose of having the index suffix at the end? is it possible to rename those to be consistent across?

**Comment by qjia7** [comment]
> > ```
> >   outputShape: number[] = [];
> >   userCode: string;
> >   customUniforms = [{name: 'value', type: 'float' as UniformType}];
> > ```
> 
> does it throw error if `float` is not casted to `UniformType`?

Yes, it will report error. `Property 'customUniforms' in type 'FillProgram' is not assignable to the same property in base type 'GPGPUProgram'.
  Type '{ name: string; type: string; }[]' is not assignable to type '{ name: string; type: UniformType; }[]'.`

> 

> I did not see and uniformName ends with `[ ]`, can you share a link to the shader?
> what is the purpose of having the index suffix at the end? is it possible to rename those to be consistent across?

You may miss my comment 
```
 // d.name may be a uniform array. For example, start[4] in slice_gpu.ts.
 // In this case, we should use 'start' instead of 'start[4]' to get the
 // uniform location.
```
See https://github.com/tensorflow/tfjs/blob/master/tfjs-backend-webgl/src/slice_packed_gpu.ts#L72
`uniform int start[${this.rank}]` is a uniform array. So we should support array case. We don't have to use the array. But there is always a place to process the extra overhead so we don't use an array. For example, if we use `uniform ${this.rank >1 ? `ivec${this.rank}` : int} start`, when use start in shader, we always need to check if this.rank > 1.

**Review by pyu10055 — COMMENTED** [review]
sorry if have miss anything here, I thought the names in customUniforms are declared by the program, it can be float or vec4 for example. But the name can be any string, my question is whether we should `start[4]` or something like `startArray` with vec4 as type?

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5258#-:-MdXNZym89-RMSC4MKn9:bifnhgi)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @qjia7)

**Comment by qjia7** [comment]
> sorry if have miss anything here, I thought the names in customUniforms are declared by the program, it can be float or vec4 for example. But the name can be any string, my question is whether we should `start[4]` or something like `startArray` with vec4 as type?
> 

Like we have synced, add an additional field arrayIndex to customUniforms for uniform array. Please take another look, thanks.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5258)* status: 0 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @qjia7)

___
*[tfjs-backend-webgl/src/shader_compiler.ts, line 120 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5258#-Md_gVXO3jgXdfKfTnN8:-Md_gVXO3jgXdfKfTnN9:b-6lmyxq) ([raw file](https://github.com/tensorflow/tfjs/blob/fa59c4a8625b8f6d348010039f41bde340456834/tfjs-backend-webgl/src/shader_compiler.ts#L120)):*
> ```XML
> 
>   const inputSamplingSnippet = inputsInfo
>                                    .map(
> ```

seem there is a bit of styling issue here, should this line be combined with previous line?
___
*[tfjs-backend-webgl/src/slice_gpu.ts, line 26 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5258#-Md_iOgqCQpknCQvY3O4:-Md_iOgr6qmo-jVUFied:bxuv8mg) ([raw file](https://github.com/tensorflow/tfjs/blob/fa59c4a8625b8f6d348010039f41bde340456834/tfjs-backend-webgl/src/slice_gpu.ts#L26)):*
> ```XML
>   userCode: string;
>   rank: number;
>   customUniforms: Array<{name: string; arrayIndex: number; type: UniformType;}>;
> ```

since these fields (`customUniforms, userCode, outputShape`) are defined in the GPGPUProgram interface, you don't need to re-declare them again?
same for the SlicePackedProgram.

**Review by pyu10055 — APPROVED** [review]
thanks, LGTMed with just a couple of minor comments.  

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5258#-:-Md_ikfREOut7_h54Rm1:b-s8f4la)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @lina128, and @qjia7)

**Review by qjia7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5258)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever, @lina128, @pyu10055, and @qjia7)

___
*[tfjs-backend-webgl/src/shader_compiler.ts, line 120 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5258#-Md_gVXO3jgXdfKfTnN8:-Md_n2n-2zwChoBnngJw:b-6ih49q) ([raw file](https://github.com/tensorflow/tfjs/blob/fa59c4a8625b8f6d348010039f41bde340456834/tfjs-backend-webgl/src/shader_compiler.ts#L120)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

seem there is a bit of styling issue here, should this line be combined with previous line?
</blockquote></details>

The format are done automatically when I save the change. It doesn't combined the above two lines. If I manually change it, it will be reverted again by the format tool.
___
*[tfjs-backend-webgl/src/slice_gpu.ts, line 26 at r4](https://reviewable.io/reviews/tensorflow/tfjs/5258#-Md_iOgqCQpknCQvY3O4:-Md_nud95MVTEG7MvCT6:b-2b2kdz) ([raw file](https://github.com/tensorflow/tfjs/blob/fa59c4a8625b8f6d348010039f41bde340456834/tfjs-backend-webgl/src/slice_gpu.ts#L26)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

since these fields (`customUniforms, userCode, outputShape`) are defined in the GPGPUProgram interface, you don't need to re-declare them again?
same for the SlicePackedProgram.
</blockquote></details>

No, I can't do that, otherwise, it will explain that `Class SliceProgram incorrectly implements interface GPGPUProgram. Type SliceProgram is missing the following properties from type GPGPUProgram: outputShape, useCode`.

**Pull request merged**
