### PR TITLE
Run e2e browserstack tests with an allowance for flakiness

### PR DESCRIPTION
**Pull request by mattsoulanille**
Write `scripts/run_flaky.js`, which runs a script until it succeeds or until it fails a specified number of times. Any successful run is considered a pass even if there were failures before. 

Run e2e browserstack tests with a flakiness allowance of 3 runs (the default for run_flaky).

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4655)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
See line 7588 of test-e2e of [this cloudbuild run](https://console.cloud.google.com/cloud-build/builds/1d9fd6c3-96f5-493d-849c-622f3d8f40c0;step=35?project=834911136599) for an example of the flaky test runner rerunning a flaky test.

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thanks, this is great. Can you try to enable android e2e tests with this change? thanks

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4655#-:-MT39fKb2mOMm976HNFJ:bhwmuy9)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

___
*[scripts/cloudbuild_tfjs_core_expected.yml, line 16 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4655#-MT37rLuBpiyQ8khbPjl:-MT37rLuBpiyQ8khbPjm:b-2s5jbv) ([raw file](https://github.com/tensorflow/tfjs/blob/52e4a3a840de22b3f2b7ca7eb56c7376be329e93/scripts/cloudbuild_tfjs_core_expected.yml#L16)):*
> ```YAML
>       - yarn-common
>   - name: 'node:10'
>     id: test-run-flaky
> ```

why this test is added to both core and node cloud build? currently only e2e is affected, right? Should it be only added to e2e first?
___
*[scripts/run_flaky.js, line 34 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4655#-MT353nx9gH-3szLDC3C:-MT353nyEXen2a-9Zpeo:b-f6g4xt) ([raw file](https://github.com/tensorflow/tfjs/blob/52e4a3a840de22b3f2b7ca7eb56c7376be329e93/scripts/run_flaky.js#L34)):*
> ```JavaScript
>     console.log(`Flaky run ${i + 1} of a potential ${times} for '${command}'`);
>     const exitCode = exec(command).code;
>     exitCodes.push(exitCode)
> ```

missing semi-colon

**Review by pyu10055 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4655)* status: 0 of 1 approvals obtained (waiting on @mattsoulanille)

**Review by mattsoulanille — COMMENTED** [review]
Thanks for the review! I re-enabled the tests disabled by #4336. [Here's another run of e2e with _NIGHTLY=true](https://console.cloud.google.com/cloud-build/builds/15ef0e8f-25a1-438c-89f4-f43e365df1a4?project=834911136599).

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4655#-:-MT6OcTO6i1g6R39jpKu:b6e9gkh)* status: 0 of 1 approvals obtained (waiting on @pyu10055)

___
*[scripts/cloudbuild_tfjs_core_expected.yml, line 16 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4655#-MT37rLuBpiyQ8khbPjl:-MT6LzKQ9ICOmA6VhoXN:b-lci1q5) ([raw file](https://github.com/tensorflow/tfjs/blob/52e4a3a840de22b3f2b7ca7eb56c7376be329e93/scripts/cloudbuild_tfjs_core_expected.yml#L16)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why this test is added to both core and node cloud build? currently only e2e is affected, right? Should it be only added to e2e first?
</blockquote></details>

This is the test of `run_flaky.js` to make sure it correctly runs flaky tests. 
___
*[scripts/run_flaky.js, line 34 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4655#-MT353nx9gH-3szLDC3C:-MT6MHrK2vQhqqXR4emu:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/52e4a3a840de22b3f2b7ca7eb56c7376be329e93/scripts/run_flaky.js#L34)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

missing semi-colon
</blockquote></details>

Done.

**Review by pyu10055 — APPROVED** [review]
awesome, all passed on the first run!

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4655#-:-MT7KP0P-En_wkmRuC66:b-jft7d5)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
