### PR TITLE
Fix webgpu backend build fail on Windows and Linux

### PR DESCRIPTION
**Pull request by axinging**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5414)

### CODE REVIEW

**Comment by axinging** [comment]
@pyu10055， With this PR, the build passed on Windows and Linux. But I donot understand why bots failed, do you have any hints? https://github.com/tensorflow/tfjs/pull/5414/checks?check_run_id=3218617145
Thanks!

**Comment by mattsoulanille** [comment]
This may have been fixed in #5416. I've been able to build and test on Mac, and I can build on Linux. Haven't tried on Windows yet, so I'm not completely sure it's fixed.

**Comment by axinging** [comment]
Yes, with https://github.com/tensorflow/tfjs/pull/5416, the before issue is gone. But there are still tow issues on Windows:
1. The command line is too long
```
ERROR: /build/tfjs/tfjs-core/src/BUILD.bazel:44:16: Action tfjs-core/src/tests.ts failed: (Exit 1): enumerate_tests_bin.bat failed: error executing command bazel-out/host/bin/tools/enumerate_tests_bin.bat -r tfjs-core/src -o bazel-out/x64_windows-fastbuild/bin/tfjs-co
re/src/tests.ts tfjs-core/src/browser_util_test.ts tfjs-core/src/buffer_test.ts ... (remaining 244 argument(s) skipped)
The command line is too long.
Target //tfjs-core:tfjs-core_pkg failed to build
Use --verbose_failures to see the command lines of failed build steps.
```
2.  however, it seems there is a typo here:
+++ b/link-package/package.json
@@ -6,7 +6,7 @@
   "license": "Apache 2.0",
   "private": true,
   "scripts": {
-    "build": "yarn build-backend-cpu && yarn build-backend-webgo && yarn build-core && yarn build-tflite && yarn reinstall",
+    "build": "yarn build-backend-cpu && yarn build-backend-webgl && yarn build-core && yarn build-tflite && yarn reinstall",

**Comment by lina128** [comment]
Hi @axinging , it seems all the issues mentioned in this PR is fixed. Can we close this PR?

**Comment by axinging** [comment]
Yes， Thanks!

**Pull request closed without merging**
