### PR TITLE
core: Disable checkComputationForErrors for webgpu backend.

### PR DESCRIPTION
**Pull request by qjia7**
BUG

Add a flag shouldCheckComputationForErrors to control checkComputationForErrors.
Disable checkComputationForErrors for webgpu backend sine it may result the tensor
is disposed before it is read.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4303)

### CODE REVIEW

**Comment by qjia7** [comment]
@annxingyuan @tafsiri Please take a look. Thanks.

**Comment by tafsiri** [comment]
I agree there is a bug/issue here, i'm not sure this is the right fix (though we might want to put the checkComputationForErrors behind a flag so it can be disabled), as there would be a similar issue in the `logKernelProfile` function reight below this one which also is not async. In webgls `disposeData` i believe we do not dispose the data if there are pending reads on a tensor, i don't see similar logic in `disposeData`. Maybe similar logic is needed there to resolve this?

@qjia7 just as a heads up, because of the holiday we won't really be able to dig into until next week. 

With regard to performance i think we expect a perf hit when profiling is on, but that it would generally be fairly consistent across kernels as long as that is true, while it is slower than true execution time it still allows for identifying bottlenecks and measuring improvements. Are you finding that is not the case?

**Comment by qjia7** [comment]
@tafsiri Thanks for your comment. 
>In webgls disposeData i believe we do not dispose the data if there are pending reads on a tensor, i don't see similar logic in disposeData. Maybe similar logic is needed there to resolve this?

Yes, it can resolve this issue. Thanks. Since there are still some profile cases fail, I need more time to figure out the reason. Will ping you again when it's ready for review.

>With regard to performance i think we expect a perf hit when profiling is on, but that it would generally be fairly consistent across kernels as long as that is true, while it is slower than true execution time it still allows for identifying bottlenecks and measuring improvements. Are you finding that is not the case?

Agree with your opinion. I just want to express that we should try to reduce unnecessary overhead when profiling. But if `checkComputationForErrors` is wanted for each kernel function. We should leave it there.

**Comment by qjia7** [comment]
> > In webgls disposeData i believe we do not dispose the data if there are pending reads on a tensor, i don't see similar logic in disposeData. Maybe similar logic is needed there to resolve this?
> 
> Yes, it can resolve this issue. Thanks. Since there are still some profile cases fail, I need more time to figure out the reason. Will ping you again when it's ready for review.
> 

Sorry for taking back my previous rely.  I find it still can't resolve the issue by caching pending reads in the backend. See my draft PR #4314 . I think it uses the same logic with webgl. However, the [profile test case](https://github.com/tensorflow/tfjs/blob/master/tfjs-core/src/engine_test.ts#L426) still explains that 'Buffer is destroyed before the mapping is resolved'. My guess is that if we put the cache logic in the backend, it's already in two different threads. You can't make sure that caching pending read is executed before disposeTensor (there are always race condition). Maybe we should cache the pending read tensor in frontend before divarication.

**Comment by qjia7** [comment]
@tafsiri Could you help guild me how to further resolve this issue?

**Comment by tafsiri** [comment]
One idea that comes to mind is to clone the tensors in the outputs array before entering that block.

Something like 

```ts
let outputsToCheck = []
for (let i = 0; i < outputs.length; i++) {
	outputsToCheck.push(outputs[i].clone());
}

for (let i = 0; i < outputsToCheck.length; i++) {
	const output = outputsToCheck[i];
	// Dangling promise here because we don't want to propagate up
	// asynchronicity.
	output.data().then(tensorVals => {
		checkComputationForErrors(tensorVals, output.dtype, kernelName);
		output.dispose();
	});
}
```

That should allow safe disposal of the actual output while allowing deferred checking of the output results.

@qjia7 could you give that a try and see if it solves the issue in the webgpu backend?

@annxingyuan what do you think of this approach?

**Comment by qjia7** [comment]
> One idea that comes to mind is to clone the tensors in the outputs array before entering that block.
> 
> Something like
> 
> ```ts
> let outputsToCheck = []
> for (let i = 0; i < outputs.length; i++) {
> 	outputsToCheck.push(outputs[i].clone());
> }
> 
> for (let i = 0; i < outputsToCheck.length; i++) {
> 	const output = outputsToCheck[i];
> 	// Dangling promise here because we don't want to propagate up
> 	// asynchronicity.
> 	output.data().then(tensorVals => {
> 		checkComputationForErrors(tensorVals, output.dtype, kernelName);
> 		output.dispose();
> 	});
> }
> ```
> 
> That should allow safe disposal of the actual output while allowing deferred checking of the output results.
> 
> @qjia7 could you give that a try and see if it solves the issue in the webgpu backend?
> 
> @annxingyuan what do you think of this approach?

In fact, it will cause below errors both for webgl and webgpu:
```
FAILED profile webgl1 {"WEBGL_VERSION":1,"WEBGL_CPU_FORWARD":false,"WEBGL_SIZE_UPLOAD_UNIFORM":0} squaring
tensor.ts:272 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Array.slice (<anonymous>)
    at new Tensor (tensor.ts:272)
    at Engine.makeTensorFromDataId (engine.ts:780)
    at engine.ts:604
    at Array.map (<anonymous>)
    at kernelFunc (engine.ts:596)
    at engine.ts:659
    at holdResultWrapperFn (profiler.ts:43)
    at MathBackendWebGL.<anonymous> (backend_webgl.ts:526)
    at step (backend_webgl.ts:16)
    at Object.next (backend_webgl.ts:16)
    at backend_webgl.ts:16
    at new Promise (<anonymous>)
    at __awaiter (backend_webgl.ts:16)
    at MathBackendWebGL.time (backend_webgl.ts:513)
    at Profiler.profileKernel (profiler.ts:45)
    at engine.ts:658
    at Engine.scopedRun (engine.ts:453)
    at Engine.runKernelFunc (engine.ts:653)
    at clone_ (clone.ts:50)
    at Object.clone__op [as clone] (operation.ts:51)
    at Tensor.clone (tensor.ts:421)
    at Profiler.profileKernel (profiler.ts:49)
    at engine.ts:658
    at Engine.scopedRun (engine.ts:453)
    at Engine.runKernelFunc (engine.ts:653)
    at clone_ (clone.ts:50)
    at Object.clone__op [as clone] (operation.ts:51)
    at Tensor.clone (tensor.ts:421)
    at Profiler.profileKernel (profiler.ts:49)
    at engine.ts:658
    at Engine.scopedRun (engine.ts:453)
    at Engine.runKernelFunc (engine.ts:653)
    at clone_ (clone.ts:50)
    at Object.clone__op [as clone] (operation.ts:51)
    at Tensor.clone (tensor.ts:421)
    at Profiler.profileKernel (profiler.ts:49)
    at engine.ts:658
    at Engine.scopedRun (engine.ts:453)
    at Engine.runKernelFunc (engine.ts:653)
... ...

**Comment by tafsiri** [comment]
Thanks for trying that. I'll sync with @annxingyuan over video chat and get back to you. The other idea I had to unblock this would be to put that section behind a flag that the webgpu backend could set to false.

**Comment by annxingyuan** [comment]
Hi @qjia7 - apologies for the delay in getting back to you on this - I just spoke with @tafsiri, and we were thinking of this approach:

1. Before checking the output of the computation for errors, check to make sure the tensor is not disposed.
2. Add an argument to `profileKernel` - shouldCheckComputationForErrors - that defaults to `true`, but that is set to `false` for WebGPU.

Hopefully this would address the issue!

**Comment by qjia7** [comment]
> 1. Before checking the output of the computation for errors, check to make sure the tensor is not disposed.
> 2. Add an argument to `profileKernel` - shouldCheckComputationForErrors - that defaults to `true`, but that is set to `false` for WebGPU.
> 

Done for step 2. 
For 1, I think it's not necessary. Once checkComputationForErrors is called, it means you already get the tensor data. All the check should happen on the backend.

@tafsiri @annxingyuan Please take another look. Thanks.

**Comment by annxingyuan** [comment]
Thanks @qjia7 - however it would be ideal if core did not contain this logic. So perhaps the easiest thing would be to add an environment flag controlling whether to check computation for errors. Sorry for the back and forth :)

**Comment by qjia7** [comment]
> Thanks @qjia7 - however it would be ideal if core did not contain this logic. So perhaps the easiest thing would be to add an environment flag controlling whether to check computation for errors. Sorry for the back and forth :)

Done. Please take another look. Thanks.

**Comment by qjia7** [comment]
@tafsiri @annxingyuan Could you please take another look? It blocks us to enable the profiling mode in webgpu backend. Thanks.

**Review by tafsiri — COMMENTED** [review]
Left a comment but I'll leave the final review with @annxingyuan as I think she has more context on this.

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4303#-:-MO9mVoN8TuhaVw7C9vj:b-f5me1h)* status: 0 of 1 approvals obtained (waiting on @qjia7)

___
*[tfjs-core/src/flags.ts, line 75 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4303#-MO9m-xM3CAt4DXyI6aA:-MO9m-xM3CAt4DXyI6aB:b-729vhc) ([raw file](https://github.com/tensorflow/tfjs/blob/068ac4ca64dce162d16f14aeb9ea65986355b606/tfjs-core/src/flags.ts#L75)):*
> ```XML
> /** Whether to check computation result for errors. */
> ENV.registerFlag(
>     'CHECK_COMPUTATION_FOR_ERRORS', () => ENGINE.backendName !== 'webgpu');
> ```

@annxingyuan did you want this to check for webgpu here?

I would have thought this can default to `true` but in the the WebGPU backend it explicitly does

`env().setFlags({'CHECK_COMPUTATION_FOR_ERRORS': false});`

that way core doesn't explicitly know about webgpu and it can be enabled in future without changing core.

**Comment by qjia7** [comment]
> I would have thought this can default to `true` but in the the WebGPU backend it explicitly does
> 
> `env().setFlags({'CHECK_COMPUTATION_FOR_ERRORS': false});`
> 
> that way core doesn't explicitly know about webgpu and it can be enabled in future without changing core.

Agree with you. Done. Thanks.

**Review by annxingyuan — APPROVED** [review]
LGTM - thanks @qjia7 !

**Pull request merged**
