### PR TITLE
webgpu: simplify shader key of depthwise_conv2d

### PR DESCRIPTION
**Pull request by xhcao**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5848)

### CODE REVIEW

**Comment by xhcao** [comment]
This pull request is copied from https://github.com/tensorflow/tfjs/pull/5836, please take a look, thank you.
@qjia7 @axinging @haoyunfeix @gyagp

**Comment by axinging** [comment]
LGTM, please check the warmup and perf data.

**Comment by xhcao** [comment]
I had tested on `mesh_128` model, which ran `DepthwiseConv2DProgram` 8 times, and there is no performance loss.

**Review by qjia7 — APPROVED** [review]
LGTM

**Comment by qjia7** [comment]
@mattsoulanille @lina128 @pyu10055 Please help merge it, thanks.

**Pull request merged**
