### PR TITLE
[webgpu] Relu function returns NaN when input is NaN

### PR DESCRIPTION
**Pull request by haoyunfeix**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5965)

### CODE REVIEW

**Comment by haoyunfeix** [comment]
@qjia7 @xhcao @axinging @gyagp PTAL

**Review by qjia7 — COMMENTED** [review]
LGTM after the bots become green.

**Comment by haoyunfeix** [comment]
Done.

**Review by qjia7 — APPROVED** [review]
LGTM, thanks.

cc @lina128 @pyu10055

**Pull request merged**
