### PR TITLE
Run CI on a single machine by generating cloudbuild files.

### PR DESCRIPTION
**Pull request by mattsoulanille**
Instead of running each CI test on a separate Google Cloud machine, generate a cloudbuild.yml file to test all affected packages on a single machine. The benifits of this strategy include the following:
* Fewer machines are required for a single test (2 instead of up to 12), so queuing should happen much less often.
* Packages only need to be built once, instead of once per machine.
* Multithreaded steps have access to more cores.

When CI is run, the root cloudbuild.yml is launched on Google Cloud. This file has only three steps: Install yarn dependencies, run `yarn generate-cloudbuild-for-packages`, and run `run-build.sh`. The second step finds what packages were affected by the change and combines their cloudbuild.yml files into a single `cloudbuild_generated.yml` file, and the third step launches the generated build on Google Cloud. The steps in the generated build are set to `waitFor` each other according to the dependency tree `scripts/package_dependencies.json`, and each package's `build-deps` step is removed in favor of waiting for its dependencies to be built.

Each package's cloudbuild file still works as expected, and there are two new yarn commands at the root: 
* `yarn test-packages` tests all packages affected by a change. It performs the same steps as CI.
* `yarn generate-cloudbuild-for-packages [PACKAGE]...` generates the cloudbuild file to test each `PACKAGE` and packages it might affect. If given no packages, it detects what packages have been changed in the current PR.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4147)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Awesome work Matt! can you try to run nightly with this setup? You can trigger that in the cloud build UI, let me know if you need help on that.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4147#-:-MKjrmcB2y5UOZIcCH58:bv18w1z)* status: 0 of 1 approvals obtained (waiting on @lina128, @mattsoulanille, and @tafsiri)

___
*[scripts/generate_cloudbuild.js, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKju9yTCYtYKHz_P6Qz:-MKju9yU1xKi_tSQ08js:bqpo07d) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/generate_cloudbuild.js#L101)):*
> ```JavaScript
>     for (const directSubnode of directSubnodes) {
>       if (!subnodes.has(directSubnode)) {
> 	subnodes.add(directSubnode);
> ```

I think maybe you are using tab for indentation? Our rule is using two spaces for indentation. wondering why our lint did not catch this.
___
*[scripts/package_dependencies.json, line 14 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKjvCog18O2PYrnOw0w:-MKjvCog18O2PYrnOw0x:bkdw1zw) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/package_dependencies.json#L14)):*
> ```JSON
>   "tfjs-backend-webgl": ["tfjs-core", "tfjs-backend-cpu"],
>   "tfjs-backend-webgpu": ["tfjs-core", "tfjs-backend-cpu", "tfjs-backend-webgl", "tfjs-converter"],
>   "tfjs-inference": [],
> ```

should the inference depends on core, converter?
___
*[scripts/package_dependencies.json, line 16 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKjvGw3EtIeoBFGl54h:-MKjvGw3EtIeoBFGl54i:bl83rdo) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/package_dependencies.json#L16)):*
> ```JSON
>   "tfjs-inference": [],
>   "tfjs-react-native": ["tfjs-core", "tfjs-backend-cpu", "tfjs-backend-webgl"],
>   "tfjs-vis": [],
> ```

I think vis has dependencies on core at least?

**Review by mattsoulanille — COMMENTED** [review]
I haven't quite figured out how to do trigger the nightly build. Sent you a message in Chat.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4147#-:-MKkc6SC1RCC1D25sQt5:bi0kuxf)* status: 0 of 1 approvals obtained (waiting on @lina128, @pyu10055, and @tafsiri)

___
*[scripts/generate_cloudbuild.js, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKju9yTCYtYKHz_P6Qz:-MKkW38F1e_45gOhQIV7:b-p6eukv) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/generate_cloudbuild.js#L101)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I think maybe you are using tab for indentation? Our rule is using two spaces for indentation. wondering why our lint did not catch this.
</blockquote></details>

My editor was misconfigured and wasn't automatically linting files. I've made my editor automatically lint, but I haven't found a way to manually trigger lints. Is there a command I missed?
___
*[scripts/package_dependencies.json, line 14 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKjvCog18O2PYrnOw0w:-MKkX3Da23oKWfi6RFtx:bf4vi0s) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/package_dependencies.json#L14)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should the inference depends on core, converter?
</blockquote></details>

I forgot to check peer dependencies in package.json. tfjs-inference lists core, converter, and bakend-cpu, so I've added those.
___
*[scripts/package_dependencies.json, line 16 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKjvGw3EtIeoBFGl54h:-MKkXn-IEpuqYPFx0w3G:b-ndqvs3) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/package_dependencies.json#L16)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

I think vis has dependencies on core at least?
</blockquote></details>

Just checked peer dependencies, which I had forgotten to check. Added a dependency on the "tfjs" union package.

**Review by lina128 — APPROVED** [review]
Hi Matt, this is awesome! Great work! Looking forward to the new CI flow :) I left some nit comments on details and testing. But overall, the design look great to me.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4147#-:-MKlZJYT9gSv3-F3p269:beqgdqj)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128, @mattsoulanille, @pyu10055, and @tafsiri)

___
*[cloudbuild.yml, line 9 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKkwbmA4ByjT33nzQqe:-MKkwbmA4ByjT33nzQqf:byt9ub3) ([raw file](https://github.com/tensorflow/tfjs/blob/aed1587da917b2b35d856887626f87fff1e538ab/cloudbuild.yml#L9)):*
> ```YAML
> 
> # Generate cloudbuild_generated.yml,
> # which builds and tests all modified packages.
> ```

which builds and tests all affected packages.
___
*[package.json, line 22 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKl2Mb705kAQCDj_gob:-MKl2Mb705kAQCDj_goc:brqvghz) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/package.json#L22)):*
> ```JSON
>   },
>   "scripts": {
>     "test-packages": "yarn generate-cloudbuild-for-packages && ./scripts/run-build.sh",
> ```

test-packages-ci for naming consistency.
___
*[package.json, line 23 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKl2kNvDXMHAuD2FmpE:-MKl2kNvDXMHAuD2FmpF:bs4r0ta) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/package.json#L23)):*
> ```JSON
>   "scripts": {
>     "test-packages": "yarn generate-cloudbuild-for-packages && ./scripts/run-build.sh",
>     "generate-cloudbuild-for-packages": "./scripts/test_affected_packages.js",
> ```

Should the naming be consistent, maybe generate_cloudbuild_for_packages.js
___
*[scripts/generate_cloudbuild.js, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKju9yTCYtYKHz_P6Qz:-MKl1o536mwHX-tfdrUn:blw4q3) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/generate_cloudbuild.js#L101)):*
<details><summary><i>Previously, mattsoulanille (Matthew Elliott Soulanille) wrote…</i></summary><blockquote>

My editor was misconfigured and wasn't automatically linting files. I've made my editor automatically lint, but I haven't found a way to manually trigger lints. Is there a command I missed?
</blockquote></details>

Are you using Visual Studio Code and import the project as Workspace?
___
*[scripts/generate_cloudbuild.js, line 90 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlNT3z0fo5sWcNzJWb:-MKlNT3z0fo5sWcNzJWc:b22et4d) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L90)):*
> ```JavaScript
> // Topologically sort the dependency tree and arrange
> // steps in dependency order.
> const DEPENDENCY_ORDER = topologicalSort(DEPENDENCY_GRAPH);
> ```

Can we move "constants" to the top of the file? Hoisting should allow it.
___
*[scripts/generate_cloudbuild.js, line 128 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlAUIB6CBMvccULG-0:-MKlAUIC3B4UE0zFtS2g:bj53330) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L128)):*
> ```JavaScript
> }
> 
> const excludeSteps = new Set(['build-deps', 'yarn-common']);
> ```

If this doesn't change, can we put it in the top of the file and use capital snake case?
___
*[scripts/generate_cloudbuild.js, line 136 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlLW816Ox76a4YUnWu:-MKlLW822u5AXaaqK213:b-2tp822) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L136)):*
> ```JavaScript
>  * 3. Builds and tests all the reverse dependnecies of `packages`
>  */
> function generateCloudbuild(packages, writeTo = 'cloudbuild_generated.yml') {
> ```

This is great! Given the complexity of the implementation, can we have a unit test to check the output for (1) packages=[tfjs-core] (2) packages=[tfjs-node]. And have golden files stored with the test. You can just compare the output with the golden files.
___
*[scripts/generate_cloudbuild.js, line 137 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlKjkv2omMlt2WNCiI:-MKlKjkv2omMlt2WNCiJ:b-9vu5z0) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L137)):*
> ```JavaScript
>  */
> function generateCloudbuild(packages, writeTo = 'cloudbuild_generated.yml') {
>   // Make sure all packages are declared in package_dependencies.json.
> ```

Only monorepo packages (each package symlinked) are declared in package_dependencies.json, we probably need to add e2e. We need to special handle tfjs-vis, tfjs-react-native, and tfjs-inference, and tfjs-webgpu(in the very near future), because they use pinned version. For these packages, can just kick off the cloudbuild.yml file in their directory. 
___
*[scripts/generate_cloudbuild.js, line 149 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKl8NuV6nIfSqi4eHRy:-MKl8NuV6nIfSqi4eHRz:bocxfy2) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L149)):*
> ```JavaScript
>   const reverseDeps = findReverseDeps(packages);
> 
>   toBuild = new Set([...deps, ...packages, ...reverseDeps]);
> ```

This is very clean, appreciate it!
___
*[scripts/generate_cloudbuild.js, line 241 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlSN1p18-V_6Q2Rli5:-MKlSN1p18-V_6Q2Rli6:b-4kkiy6) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L241)):*
> ```JavaScript
>   }
> 
>   // Remove unused secrets. Cloudbuild fails if extra secrets are included.
> ```

Nice catch :)
___
*[scripts/generate_cloudbuild.js, line 263 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlUatJ1xnqAI_WQeCG:-MKlUatJ1xnqAI_WQeCH:bpxonnf) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L263)):*
> ```JavaScript
> 
> function isTestStep(id) {
>   // Some steps have no ID, so we assume they're test steps.
> ```

This assumption is not reliable and can break in the future. Should we add an id for each step?
___
*[scripts/package_dependencies.json, line 14 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKjvCog18O2PYrnOw0w:-MKlHZnJAFT3bXe8x9bn:bxrhra4) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/package_dependencies.json#L14)):*
<details><summary><i>Previously, mattsoulanille (Matthew Elliott Soulanille) wrote…</i></summary><blockquote>

I forgot to check peer dependencies in package.json. tfjs-inference lists core, converter, and bakend-cpu, so I've added those.
</blockquote></details>

tfjs-inference, vis, and react-native should not be included in PR test, because they are not part of the monorepo. They use pinned version, so they are similar to tfjs-models and tfjs-examples packages. This means that their behavior won't change for PR change. We should handle these package testing differently.
___
*[scripts/package_dependencies.json, line 4 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlY2D77iV3nrLtecZQ:-MKlWxvV2f13BRLHkiSx:b-ixbggd) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/package_dependencies.json#L4)):*
> ```JSON
> {
>   "tfjs-core": [],
>   "tfjs-converter": ["tfjs-core", "tfjs-backend-cpu"],
> ```

I realized this file is now changed to be consistent with build-deps rules, that's fine. For context, we didn't include cpu in converter and layers because they are not peerDependency or dependency, it is only devDependency and is only used in testing. So we don't want cpu change to trigger converter and layers testing. But that's probably fine. layers may be a problem, because it uses 1 browserstack instance and is generally running longer. We can keep an eye on this.
___
*[scripts/test_affected_packages.js, line 26 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlJSNn08x3on-KP9JQ:-MKlJSNn08x3on-KP9JR:b-nyigz8) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/test_affected_packages.js#L26)):*
> ```JavaScript
> 
> let packages;
> if (process.argv.length > 2) {
> ```

Can we use argparse?
___
*[tfjs-backend-cpu/src/backend_cpu.ts, line 300 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlIEOnBn5caQ1WU8NE:-MKlIEOnBn5caQ1WU8NF:b-7rxd15) ([raw file](https://github.com/tensorflow/tfjs/blob/3b9c24489d9632647d9125da9ed0eb07839af186/tfjs-backend-cpu/src/backend_cpu.ts#L300)):*
> ```XML
>     return result.toTensor() as T;
>   }
> ```

These are not relevant to this PR.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 11 of 14 files at r1, 3 of 3 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4147)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128, @mattsoulanille, @pyu10055, and @tafsiri)

___
*[scripts/generate_cloudbuild.js, line 36 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKpAzKrAPo8ZUp_2TZ6:-MKpAgil7G2johUCqQ6q:b5qb63p) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L36)):*
> ```
> transposed
> ```
there is one extra tab.
___
*[scripts/generate_cloudbuild.js, line 149 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKl8NuV6nIfSqi4eHRy:-MKpD-gN5vEypC2F66TQ:b-9df8k0) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L149)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This is very clean, appreciate it!
</blockquote></details>

nit, I feel it would easier to understand if they are named as [...parent_packages, ...packages, ...child_packages]. But this is great, and the logs it produces look really nice.

**Review by mattsoulanille — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4147)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128, @pyu10055, and @tafsiri)

___
*[cloudbuild.yml, line 9 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKkwbmA4ByjT33nzQqe:-MKpNjY351oTH8Wp4Byd:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/aed1587da917b2b35d856887626f87fff1e538ab/cloudbuild.yml#L9)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

which builds and tests all affected packages.
</blockquote></details>

Done.
___
*[package.json, line 22 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKl2Mb705kAQCDj_gob:-MKpNkKpCJKKPfDwFkqO:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/package.json#L22)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

test-packages-ci for naming consistency.
</blockquote></details>

Done.
___
*[package.json, line 23 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKl2kNvDXMHAuD2FmpE:-MKphq3mCzrr6dX-Mwmm:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/package.json#L23)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Should the naming be consistent, maybe generate_cloudbuild_for_packages.js
</blockquote></details>

Done.
___
*[scripts/generate_cloudbuild.js, line 101 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKju9yTCYtYKHz_P6Qz:-MKp4Gjo-0Paz_g83JUi:bxv8yv2) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/generate_cloudbuild.js#L101)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Are you using Visual Studio Code and import the project as Workspace?
</blockquote></details>

I was using emacs. I've re-linted and formatted everything in VSCode.
___
*[scripts/generate_cloudbuild.js, line 36 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKpAzKrAPo8ZUp_2TZ6:-MKphtdY2H5GVp5bMlMq:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L36)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> transposed
> ```
there is one extra tab.
</blockquote></details>

Done.
___
*[scripts/generate_cloudbuild.js, line 90 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlNT3z0fo5sWcNzJWb:-MKpNJSk8BRqqekYd_iY:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L90)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can we move "constants" to the top of the file? Hoisting should allow it.
</blockquote></details>

Done.
___
*[scripts/generate_cloudbuild.js, line 128 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlAUIB6CBMvccULG-0:-MKpMvmx--kXYJ4INFxU:bvue1ho) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L128)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

If this doesn't change, can we put it in the top of the file and use capital snake case?
</blockquote></details>

Oops. Missed that one. Done
___
*[scripts/generate_cloudbuild.js, line 136 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlLW816Ox76a4YUnWu:-MKqInKlBA3PfdicrXgt:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L136)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This is great! Given the complexity of the implementation, can we have a unit test to check the output for (1) packages=[tfjs-core] (2) packages=[tfjs-node]. And have golden files stored with the test. You can just compare the output with the golden files.
</blockquote></details>

Done.
___
*[scripts/generate_cloudbuild.js, line 137 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlKjkv2omMlt2WNCiI:-MKp9OEx1Dom8xYMTkEF:bg654bh) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L137)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Only monorepo packages (each package symlinked) are declared in package_dependencies.json, we probably need to add e2e. We need to special handle tfjs-vis, tfjs-react-native, and tfjs-inference, and tfjs-webgpu(in the very near future), because they use pinned version. For these packages, can just kick off the cloudbuild.yml file in their directory. 
</blockquote></details>

I wasn't aware some packages are not part of the monorepo yet. I added everything to package_dependencies.json. 

I think it might still be a good idea to include the non-monorepo pakages in the generated cloudbuild file since then they won't take up an entire cloud machine. We can list them in package_dependencies.json but with no dependencies so they get build immediately. For their dependencies, as long as they list a version in package.json instead of a link, they should all use their pinned versions. 
___
*[scripts/generate_cloudbuild.js, line 149 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKl8NuV6nIfSqi4eHRy:-MKp9ApwElTmszLiOEXb:b-ucfknh) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L149)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This is very clean, appreciate it!
</blockquote></details>

Thanks!
___
*[scripts/generate_cloudbuild.js, line 241 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlSN1p18-V_6Q2Rli5:-MKp98lwAHaOhvW7De8k:b-ucfknh) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L241)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Nice catch :)
</blockquote></details>

Thanks!
___
*[scripts/generate_cloudbuild.js, line 263 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlUatJ1xnqAI_WQeCG:-MKp4e_f2Q_EFALBDGtM:b-2fvjzb) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/generate_cloudbuild.js#L263)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

This assumption is not reliable and can break in the future. Should we add an id for each step?
</blockquote></details>

It's probably a good idea for every step to have an id. Done.
___
*[scripts/package_dependencies.json, line 14 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKjvCog18O2PYrnOw0w:-MKkgiXm2GxS5MAc7qcV:brxjyd8) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/package_dependencies.json#L14)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

tfjs-inference, vis, and react-native should not be included in PR test, because they are not part of the monorepo. They use pinned version, so they are similar to tfjs-models and tfjs-examples packages. This means that their behavior won't change for PR change. We should handle these package testing differently.
</blockquote></details>

Since they're using pinned versions, I will list them as not depending on any other packages. That will make them only be tested iff there have been changes directly to them, and they'll ignore changes that happen in other packages.
___
*[scripts/package_dependencies.json, line 4 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlY2D77iV3nrLtecZQ:-MKpRJS5BVE_TRxLgVAZ:bmh6eu9) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/package_dependencies.json#L4)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

I realized this file is now changed to be consistent with build-deps rules, that's fine. For context, we didn't include cpu in converter and layers because they are not peerDependency or dependency, it is only devDependency and is only used in testing. So we don't want cpu change to trigger converter and layers testing. But that's probably fine. layers may be a problem, because it uses 1 browserstack instance and is generally running longer. We can keep an eye on this.
</blockquote></details>

Okay. Thanks for the context! I'll make sure to watch layers and see if it's contributing to total test time.
___
*[tfjs-backend-cpu/src/backend_cpu.ts, line 300 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlIEOnBn5caQ1WU8NE:-MKqIdWU1XMg9oaZ_un7:bd49v5l) ([raw file](https://github.com/tensorflow/tfjs/blob/3b9c24489d9632647d9125da9ed0eb07839af186/tfjs-backend-cpu/src/backend_cpu.ts#L300)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

These are not relevant to this PR.
</blockquote></details>

I'm not sure why these are here. I think I rebased on master incorrectly. I'll take a look.
___
*[scripts/test_affected_packages.js, line 26 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlJSNn08x3on-KP9JQ:-MKphVEz0WsIgaAGhp-t:bjg6x97) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/test_affected_packages.js#L26)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Can we use argparse?
</blockquote></details>

Yep. Done.

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4147)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128, @mattsoulanille, and @tafsiri)

___
*[scripts/cloudbuild.yml, line 1 at r5](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKsHYJU2356DwEiJjuD:-MKsHYJU2356DwEiJjuE:bfa2jm0) ([raw file](https://github.com/tensorflow/tfjs/blob/fa35d6a3089bba75a8ba959cab358f03bd6aece8/scripts/cloudbuild.yml#L1)):*
> ```YAML
> steps:
> ```

This is just for my understanding, how is this build file triggered?
___
*[scripts/package_dependencies.json, line 14 at r1](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKjvCog18O2PYrnOw0w:-MKsF4PI6VLqL5vHkp6X:b32w49) ([raw file](https://github.com/tensorflow/tfjs/blob/62d9a139fc410dfa172dfbed96b79fa38015f76d/scripts/package_dependencies.json#L14)):*
<details><summary><i>Previously, mattsoulanille (Matthew Elliott Soulanille) wrote…</i></summary><blockquote>

Since they're using pinned versions, I will list them as not depending on any other packages. That will make them only be tested iff there have been changes directly to them, and they'll ignore changes that happen in other packages.
</blockquote></details>

SG
___
*[scripts/package_dependencies.json, line 18 at r5](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKsFD0RD3lX8yl0zeEF:-MKsFD0RD3lX8yl0zeEG:b-j6ssjm) ([raw file](https://github.com/tensorflow/tfjs/blob/fa35d6a3089bba75a8ba959cab358f03bd6aece8/scripts/package_dependencies.json#L18)):*
> ```JSON
>   "tfjs-vis": [],
>   "scripts": [],
>   "e2e": ["tfjs-backend-wasm", "tfjs", "tfjs-node"]
> ```

Doesn't e2e depend on all monorepo packages?
___
*[tfjs-backend-wasm/src/kernels/Prod.ts, line 1 at r5](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKsI565CVFt-tshp8-k:-MKsI5667qeXRNVCZ4JW:b-sn8dhe) ([raw file](https://github.com/tensorflow/tfjs/blob/fa35d6a3089bba75a8ba959cab358f03bd6aece8/tfjs-backend-wasm/src/kernels/Prod.ts#L1)):*
> ```XML
> /**
> ```

Do we know why these files are included and are they the same from the head of master?
___
*[scripts/find_packages_with_diff.js, line 23 at r5](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKsHvS60uHF5P9GQoZk:-MKsHvS60uHF5P9GQoZl:bm06xmb) ([raw file](https://github.com/tensorflow/tfjs/blob/fa35d6a3089bba75a8ba959cab358f03bd6aece8/scripts/find_packages_with_diff.js#L23)):*
> ```JavaScript
> 
> 
> const filesAllowlistToTriggerBuild = [
> ```

Should we add scripts/generate_cloudbuild.js here?
___
*[scripts/generate_cloudbuild_for_packages.js, line 38 at r5](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKsEgiMAOTs7RGkI84z:-MKsEgiMAOTs7RGkI85-:b-oi4rkl) ([raw file](https://github.com/tensorflow/tfjs/blob/fa35d6a3089bba75a8ba959cab358f03bd6aece8/scripts/generate_cloudbuild_for_packages.js#L38)):*
> ```JavaScript
> });
> 
> const args = parser.parseArgs(process.argv.slice(2));
> ```

I think this line can be just `const args = parser.parseArgs();`
___
*[scripts/test_affected_packages.js, line 26 at r3](https://reviewable.io/reviews/tensorflow/tfjs/4147#-MKlJSNn08x3on-KP9JQ:-MKsEdt14d4x1vErGSsg:b-rarndm) ([raw file](https://github.com/tensorflow/tfjs/blob/ffe3dd898bbcd7be5433d32e176e1dcb4dc4adfc/scripts/test_affected_packages.js#L26)):*
<details><summary><i>Previously, mattsoulanille (Matthew Elliott Soulanille) wrote…</i></summary><blockquote>

Yep. Done.
</blockquote></details>

Shouldn't it be args.packages?

**Comment by mattsoulanille** [comment]
I realize this has already been merged, but I just wanted to explain why there are so many commits repeated in it. While developing, I would periodically rebase my changes on top of the master TFJS branch. Apparently, I did this incorrectly, or perhaps GitHub doesn't support this workflow, so several irrelevant commits were added to this PR and several more were repeated. I was going to try to sort everything out with a force-push, but that's now moot.

**Comment by pyu10055** [comment]
I did a git diff before and after this PR, I don't see any obvious changes beyond the work here.
@mattsoulanille can you double check? thanks
`git diff 69f58037eae4c67ea977b264a9867470236e0bb0 cfa756f814eb7b4cb1494dca5d1bd70eb5e6d5b8`

**Pull request merged**
