### PR TITLE
Modularize "Cos" for webgl backend.

### PR DESCRIPTION
**Pull request by jinjingforever**
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3921)

### CODE REVIEW

**Comment by jinjingforever** [comment]
After this PR, I should be able to add the rest of the ops in batches:) Thanks for all the help

**Review by annxingyuan — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3921#-:-MHGg0lr-K25EGpUEQoi:bb6ywmx)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan and @tafsiri)

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3921)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @jinjingforever and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Cos.ts, line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3921#-MHHlsaQ0k3B1O8Zowpz:-MHHlsaQ0k3B1O8Zowq-:biorqb5) ([raw file](https://github.com/tensorflow/tfjs/blob/aacfb849522e3716bdc6024cc5f470234748c1f4/tfjs-backend-webgl/src/kernels/Cos.ts#L26)):*
> ```XML
>   kernelName: Cos,
>   backendName: 'webgl',
>   kernelFunc: ({inputs, backend}) => {
> ```

Hi Jing, please also export cos's kernel function, this will allow other kernels to call the kernel func directly. If calling through cosConfig.kernelFunc, it only has generic type, i.e. NamedTensorMap, as oppose to CosInputs. Because of this and less code to type, we should always export two things for each kernel, one kernelFunc and one config.

**Review by jinjingforever — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3921)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @tafsiri)

___
*[tfjs-backend-webgl/src/kernels/Cos.ts, line 26 at r2](https://reviewable.io/reviews/tensorflow/tfjs/3921#-MHHlsaQ0k3B1O8Zowpz:-MHHncgA6D33k_vA8FKD:ba0dyvm) ([raw file](https://github.com/tensorflow/tfjs/blob/aacfb849522e3716bdc6024cc5f470234748c1f4/tfjs-backend-webgl/src/kernels/Cos.ts#L26)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Hi Jing, please also export cos's kernel function, this will allow other kernels to call the kernel func directly. If calling through cosConfig.kernelFunc, it only has generic type, i.e. NamedTensorMap, as oppose to CosInputs. Because of this and less code to type, we should always export two things for each kernel, one kernelFunc and one config.
</blockquote></details>

ah got it. Thanks! Will fix this in my upcoming PRs.

**Pull request merged**
