### PR TITLE
Added mirrorPad kernel

### PR DESCRIPTION
**Pull request by AbdallaGomaa**
FEATURE

Implemented 'REFLECT' and 'SYMMETRIC' modes of tf.pad in mirrorPad (https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/mirror-pad)

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951)

### CODE REVIEW

**Comment by AbdallaGomaa** [comment]
@googlebot I signed it!

**Comment by AbdallaGomaa** [comment]
@googlebot I fixed it

**Review by pyu10055 — CHANGES_REQUESTED** [review]
Thank you for the contribution, it looks good to me for most part just a couple minor comments.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951#-:-MIV6RJi2Nh0VD-2CDT2:b-fnaxv4)* status: 0 of 1 approvals obtained (waiting on @AbdallaGomaa and @tafsiri)

___
*[tfjs-backend-webgl/src/mirror_pad_gpu.ts, line 1 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIV--uT7E7xrEnZrQKT:-MIV--uT7E7xrEnZrQKU:b-7wh9e9) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_gpu.ts#L1)):*
> ```XML
> import {GPGPUProgram} from './gpgpu_math';
> ```

please make sure license header is added to all new files.
___
*[tfjs-backend-webgl/src/mirror_pad_gpu.ts, line 31 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIV7BEW9hBWyWwd06tA:-MIV7BEW9hBWyWwd06tB:b89idpc) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_gpu.ts#L31)):*
> ```XML
>       void main() {
>         ${type} coords = getOutputCoords();
>         ${type} lt = ${type}(${lessThan});
> ```

wondering if the behavior of bvec multiplication can be driver dependent. Would be if more safe to use condition logic? 
___
*[tfjs-core/src/ops/mirror_pad.ts, line 46 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIUwlEcBAcXFdkTkf4u:-MIUwlEcBAcXFdkTkf4v:b-kqzdit) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/ops/mirror_pad.ts#L46)):*
> ```XML
>  * then both `paddings[D, 0]` and `paddings[D, 1]` must be no greater than
>  * `x.shape[D]`
>  * @param mode Optional string from `'reflect' | 'symmetric'`,
> ```

It would be good to give an example for each value:
In reflect mode the padded regions do not include the borders, while in symmetric mode the padded regions do include the borders. For example, if input is [1, 2, 3] and paddings is [0, 2], then the output is [1, 2, 3, 2, 1] in reflect mode, and it is [1, 2, 3, 3, 2] in symmetric mode.
___
*[tfjs-core/src/ops/mirror_pad.ts, line 70 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIUyk_t1QrHPB8TLX9D:-MIUyk_uBEYlQXLhxn2c:b-78toem) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/ops/mirror_pad.ts#L70)):*
> ```XML
>         () => `Invalid number of paddings. Must be length of 2 each.`);
>     util.assert(
>         paddings[i][0] < $x.shape[i] + offset &&
> ```

it should be <= $x.shape[i] - offset. Also it should be greater than 0

**Review by annxingyuan — CHANGES_REQUESTED** [review]
This is an amazing contribution! Thank you!

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951#-:-MIVumfy9M3fSTwLB4OG:b-g2wbrw)* status: 0 of 1 approvals obtained (waiting on @AbdallaGomaa, @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1016 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVru_h2p1mbh_Fb8OR:-MIVru_h2p1mbh_Fb8OS:b2sn3zq) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/backend_webgl.ts#L1016)):*
> ```XML
>   }
> 
>   mirrorPad<T extends Tensor>(
> ```

Could you add this kernel in the modularized style, as you did with the CPU backend?
___
*[tfjs-backend-webgl/src/mirror_pad_gpu.ts, line 15 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVs9I07VQ6R_WPrPF3:-MIVs9I07VQ6R_WPrPF4:bspo61x) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_gpu.ts#L15)):*
> ```XML
>         (p, i) => p[0] /* beforePad */ + xShape[i] + p[1] /* afterPad */);
>     const rank = xShape.length;
>     const type = getCoordsDataType(rank);
> ```

our convention is to name this `dtype` rather than `type`
___
*[tfjs-backend-webgl/src/mirror_pad_gpu.ts, line 31 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIV7BEW9hBWyWwd06tA:-MIVsOJP5NFHSNpNfcnk:b32v57) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_gpu.ts#L31)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

wondering if the behavior of bvec multiplication can be driver dependent. Would be if more safe to use condition logic? 
</blockquote></details>

+1
___
*[tfjs-backend-webgl/src/mirror_pad_packed_gpu.ts, line 21 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVsq3aBBoS8wsMC8Ev:-MIVsq3aBBoS8wsMC8Ew:b-5ynt9a) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_packed_gpu.ts#L21)):*
> ```XML
> import {getChannels} from './packing_util';
> import {getCoordsDataType} from './shader_compiler';
> ```

I realize we haven't been doing this elsewhere :) but it would be super helpful if you could include the generated shader code for a sample input here in a comment.
___
*[tfjs-backend-webgl/src/mirror_pad_packed_gpu.ts, line 63 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVtOHs2WcJQSGOKGAS:-MIVtOHs2WcJQSGOKGAT:bb1qmnm) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_packed_gpu.ts#L63)):*
> ```XML
> 
>     let mainLoop = '';
>     for (let i = 0, j = rank === 1 ? 2 : 4; i < j; i++) {
> ```

Could you separate this into an if / else block depending on the rank? I think it will be a bit more readable that way.
___
*[tfjs-backend-webgpu/src/backend_webgpu.ts, line 521 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVu7yG5RzuGISe4V23:-MIVu7yG5RzuGISe4V24:b62ytdz) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgpu/src/backend_webgpu.ts#L521)):*
> ```XML
>   }
> 
>   mirrorPad<T extends Tensor>(
> ```

Could you add this kernel in the modular style instead?
___
*[tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts, line 33 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVtdzBCTpWS9lNoD9s:-MIVtdzBCTpWS9lNoD9t:b-o0b8zl) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts#L33)):*
> ```XML
>   variableNames = ['x'];
>   workPerThread = 8;
>   workGroupSize: [number, number, number] = [16, 1, 1];
> ```

Curious whether you arrived at these numbers through benchmarking?
___
*[tfjs-core/src/backends/backend.ts, line 584 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVuIpoESrgQnUb71Nr:-MIVuIpoESrgQnUb71Ns:b-103frv) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/backends/backend.ts#L584)):*
> ```XML
>   }
> 
>   mirrorPad<T extends Tensor>(
> ```

You might not need to add this if you're adding a fully modularized kernel.
___
*[tfjs-core/src/ops/mirror_pad.ts, line 83 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVuOkZ7mh7NAh4CAeu:-MIVuOkZ7mh7NAh4CAev:b-wt3fo) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/ops/mirror_pad.ts#L83)):*
> ```XML
>   const attrs: MirrorPadAttrs = {paddings, mode};
>   const inputs: MirrorPadInputs = {x: $x};
>   return ENGINE.runKernelFunc(
> ```

If you ensure that all the kernels are written in the modular style, you should just be able to call runKernel here instead - see our `dilation2d` op as an example.

**Review by tafsiri — CHANGES_REQUESTED** [review]
This is a really thorough PR, great work. Left a few comments.

> Reviewed 24 of 26 files at r1, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951#-:-MIWyULMDs_lYalByJP8:bk7jqj)* status: 0 of 1 approvals obtained (waiting on @AbdallaGomaa, @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-core/src/backends/backend.ts, line 584 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVuIpoESrgQnUb71Nr:-MIWs9O3CugMXb5IiLBJ:b28d3ok) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/backends/backend.ts#L584)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

You might not need to add this if you're adding a fully modularized kernel.
</blockquote></details>

+1 to this. we should not add new kernels to the backend interface.
___
*[tfjs-core/src/ops/mirror_pad.ts, line 83 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVuOkZ7mh7NAh4CAeu:-MIWtXjaA78hMH4Nr1Q3:b32v57) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/ops/mirror_pad.ts#L83)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

If you ensure that all the kernels are written in the modular style, you should just be able to call runKernel here instead - see our `dilation2d` op as an example.
</blockquote></details>

+1
___
*[tfjs-core/src/ops/mirror_pad.ts, line 53 at r4](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIWxEBeD9NKvKohiy9Q:-MIWxEBeD9NKvKohiy9R:b56v3od) ([raw file](https://github.com/tensorflow/tfjs/blob/ac008515408b6690d29a36807211f1435e534130/tfjs-core/src/ops/mirror_pad.ts#L53)):*
> ```XML
>     x: T|TensorLike, paddings: Array<[number, number]>,
>     mode?: 'reflect'|'symmetric'): T {
>   mode = mode || 'reflect';
> ```

Why make mode optional/default to reflect? I think we should make it required to align with https://www.tensorflow.org/api_docs/python/tf/raw_ops/MirrorPad?hl=en
___
*[tfjs-core/src/ops/mirror_pad_test.ts, line 38 at r4](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIWwb9e4QfOUtil4wMv:-MIWwb9e4QfOUtil4wMw:bt7giln) ([raw file](https://github.com/tensorflow/tfjs/blob/ac008515408b6690d29a36807211f1435e534130/tfjs-core/src/ops/mirror_pad_test.ts#L38)):*
> ```XML
>     // 2, 1, 2, 3, 2
>     // 5, 4, 5, 6, 5
>     // 2, 1, 2, 3, 2
> ```

these diagrams are great. Could you add assertions for the expected shape (e.g. [4,5] in this case) in all these tests
___
*[tfjs-node/src/nodejs_kernel_backend.ts, line 1347 at r4](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIWyC4LDhZ-s3oiScYW:-MIWyC4LDhZ-s3oiScYX:b-krjvwt) ([raw file](https://github.com/tensorflow/tfjs/blob/ac008515408b6690d29a36807211f1435e534130/tfjs-node/src/nodejs_kernel_backend.ts#L1347)):*
> ```XML
>   }
> 
>   mirrorPad<T extends Tensor>(
> ```

You should also be able to implement this in the 'modular' style. See Dilation2D or SquaredDifference in tfjs-node/src/kernels

**Review by AbdallaGomaa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-backend-webgl/src/backend_webgl.ts, line 1016 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVru_h2p1mbh_Fb8OR:-MIZSctaCwLQNLQHhtrD:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/backend_webgl.ts#L1016)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Could you add this kernel in the modularized style, as you did with the CPU backend?
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/mirror_pad_gpu.ts, line 1 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIV--uT7E7xrEnZrQKT:-MIZSf_J6WEoqtwp9gnI:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_gpu.ts#L1)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

please make sure license header is added to all new files.
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/mirror_pad_gpu.ts, line 15 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVs9I07VQ6R_WPrPF3:-MIZSovy6Ra53BuhxK-z:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_gpu.ts#L15)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

our convention is to name this `dtype` rather than `type`
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/mirror_pad_gpu.ts, line 31 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIV7BEW9hBWyWwd06tA:-MIZSqVI0K_sWCykfqJ0:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_gpu.ts#L31)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[tfjs-backend-webgl/src/mirror_pad_packed_gpu.ts, line 21 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVsq3aBBoS8wsMC8Ev:-MIZStZl6UlCnixDKrDf:b-pyzlk8) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_packed_gpu.ts#L21)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

I realize we haven't been doing this elsewhere :) but it would be super helpful if you could include the generated shader code for a sample input here in a comment.
</blockquote></details>

Done. :) 
___
*[tfjs-backend-webgl/src/mirror_pad_packed_gpu.ts, line 63 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVtOHs2WcJQSGOKGAS:-MIZSw0K9NlA6-_yLdto:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgl/src/mirror_pad_packed_gpu.ts#L63)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Could you separate this into an if / else block depending on the rank? I think it will be a bit more readable that way.
</blockquote></details>

Done.
___
*[tfjs-backend-webgpu/src/backend_webgpu.ts, line 521 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVu7yG5RzuGISe4V23:-MIZSz3g7Zq-pyPjT3o5:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgpu/src/backend_webgpu.ts#L521)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Could you add this kernel in the modular style instead?
</blockquote></details>

Done.
___
*[tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts, line 33 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVtdzBCTpWS9lNoD9s:-MIZT0Wl3RDSZ3mTyqoC:b-ybc34x) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-backend-webgpu/src/kernels/mirror_pad_webgpu.ts#L33)):*
<details><summary><i>Previously, annxingyuan (Ann Yuan) wrote…</i></summary><blockquote>

Curious whether you arrived at these numbers through benchmarking?
</blockquote></details>

I just copied this from `pad_webgpu.ts`
___
*[tfjs-core/src/backends/backend.ts, line 584 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVuIpoESrgQnUb71Nr:-MIZTP8QEgmMP5sLvcGE:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/backends/backend.ts#L584)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

+1 to this. we should not add new kernels to the backend interface.
</blockquote></details>

Done.
___
*[tfjs-core/src/ops/mirror_pad.ts, line 46 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIUwlEcBAcXFdkTkf4u:-MIZTStw6_taqhgWda5o:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/ops/mirror_pad.ts#L46)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

It would be good to give an example for each value:
In reflect mode the padded regions do not include the borders, while in symmetric mode the padded regions do include the borders. For example, if input is [1, 2, 3] and paddings is [0, 2], then the output is [1, 2, 3, 2, 1] in reflect mode, and it is [1, 2, 3, 3, 2] in symmetric mode.
</blockquote></details>

Done.
___
*[tfjs-core/src/ops/mirror_pad.ts, line 70 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIUyk_t1QrHPB8TLX9D:-MIZT_7Y2P2uHC5061ns:bw1v9kz) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/ops/mirror_pad.ts#L70)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

it should be <= $x.shape[i] - offset. Also it should be greater than 0
</blockquote></details>

It actually can be 0 if you don't want to pad along that dimension or on that side but you're right it can't be negative. Updated it to be greater than or equal to 0
___
*[tfjs-core/src/ops/mirror_pad.ts, line 83 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIVuOkZ7mh7NAh4CAeu:-MIZTjwy0FQnpNcyU6Pj:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/ops/mirror_pad.ts#L83)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[tfjs-core/src/ops/mirror_pad.ts, line 53 at r4](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIWxEBeD9NKvKohiy9Q:-MIZTVNg3LtHAGJ2gpR3:b-hahdnl) ([raw file](https://github.com/tensorflow/tfjs/blob/ac008515408b6690d29a36807211f1435e534130/tfjs-core/src/ops/mirror_pad.ts#L53)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

Why make mode optional/default to reflect? I think we should make it required to align with https://www.tensorflow.org/api_docs/python/tf/raw_ops/MirrorPad?hl=en
</blockquote></details>

Changed it to required! 
___
*[tfjs-core/src/ops/mirror_pad_test.ts, line 38 at r4](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIWwb9e4QfOUtil4wMv:-MIZTkrqBCfHbsNvvzDI:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/ac008515408b6690d29a36807211f1435e534130/tfjs-core/src/ops/mirror_pad_test.ts#L38)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

these diagrams are great. Could you add assertions for the expected shape (e.g. [4,5] in this case) in all these tests
</blockquote></details>

Done.
___
*[tfjs-node/src/nodejs_kernel_backend.ts, line 1347 at r4](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIWyC4LDhZ-s3oiScYW:-MIZU0wD5d7NJ2EuDj7u:b5e12pw) ([raw file](https://github.com/tensorflow/tfjs/blob/ac008515408b6690d29a36807211f1435e534130/tfjs-node/src/nodejs_kernel_backend.ts#L1347)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

You should also be able to implement this in the 'modular' style. See Dilation2D or SquaredDifference in tfjs-node/src/kernels
</blockquote></details>

I've updated this to be in the modular style but I seem to have an issue with the tests. I'm getting `Error: Backend 'tensorflow' has an internal memory leak (1 data ids) after running 'MirrorPad'` for pretty much every test and I am not entirely sure what causes this. Would be great if you can help me with this!

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951)* status: 0 of 1 approvals obtained (waiting on @AbdallaGomaa, @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-core/src/ops/mirror_pad.ts, line 70 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIUyk_t1QrHPB8TLX9D:-MIZi8Bu6yUVhgEHVvvp:b-dl9320) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/ops/mirror_pad.ts#L70)):*
> ```
> offset = mode === 'reflect' ? 0 : 1;
> ```
offset = mode === 'reflect' ? 1 : 0;
I think the offset here need to be reversed.
___
*[tfjs-core/src/ops/mirror_pad.ts, line 77 at r6](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIZhRaWBpWoC8YmkQ8N:-MIZhRaWBpWoC8YmkQ8O:b-y8ou5y) ([raw file](https://github.com/tensorflow/tfjs/blob/a5a302cc89777681c8b5e0a011c58b6548cc0bcf/tfjs-core/src/ops/mirror_pad.ts#L77)):*
> ```XML
>             paddings[i][1] >= 0 && paddings[i][1] <= $x.shape[i] - offset,
>         () => `Padding in dimension ${i} cannot be greater than or equal ` +
>             `to ${$x.shape[i] + offset} for input of shape ${$x.shape}`);
> ```

please update the error message to reflect the >=0 check, also correct the  ${$x.shape[i] - offset}

**Review by AbdallaGomaa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-core/src/ops/mirror_pad.ts, line 70 at r3](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIUyk_t1QrHPB8TLX9D:-MItAOjo8WV_HRMBQely:b-o7vuhc) ([raw file](https://github.com/tensorflow/tfjs/blob/13b2b7dc41c0f554c4dc6fb702d446cddc2b49cc/tfjs-core/src/ops/mirror_pad.ts#L70)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

> ```
> offset = mode === 'reflect' ? 0 : 1;
> ```
offset = mode === 'reflect' ? 1 : 0;
I think the offset here need to be reversed.
</blockquote></details>

Good catch! Done.
___
*[tfjs-core/src/ops/mirror_pad.ts, line 77 at r6](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIZhRaWBpWoC8YmkQ8N:-MItAQpD63lecb6QuYi5:bkp9u60) ([raw file](https://github.com/tensorflow/tfjs/blob/a5a302cc89777681c8b5e0a011c58b6548cc0bcf/tfjs-core/src/ops/mirror_pad.ts#L77)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

please update the error message to reflect the >=0 check, also correct the  ${$x.shape[i] - offset}
</blockquote></details>

Done. Also updated tests to check these edge cases.

**Review by pyu10055 — APPROVED** [review]
> Reviewed 17 of 26 files at r1, 1 of 4 files at r4, 12 of 16 files at r5, 2 of 2 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

**Review by annxingyuan — APPROVED** [review]

**Review by tafsiri — CHANGES_REQUESTED** [review]
Added a suggestion for fixing the memory leak.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951#-:-MIykAgiE8afa-76enMH:b-tcdf35)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @AbdallaGomaa, @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-core/src/ops/mirror_pad.ts, line 57 at r8](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIyjvrfB0kHGoJHes_0:-MIyjvrfB0kHGoJHes_1:b-tgh6up) ([raw file](https://github.com/tensorflow/tfjs/blob/1d168592748002c1dbeede2e46870b94ebec1fad/tfjs-core/src/ops/mirror_pad.ts#L57)):*
> ```XML
>     x: T|TensorLike, paddings: Array<[number, number]>,
>     mode: 'reflect'|'symmetric'): T {
>   mode = mode || 'reflect';
> ```

remove the default assignement, add an assertion that it is reflect or symettric.
___
*[tfjs-node/src/kernels/MirrorPad.ts, line 31 at r8](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIyiyGLCVRPwnDUC0In:-MIyixDLBppqa2_2wYfB:b-q29rh5) ([raw file](https://github.com/tensorflow/tfjs/blob/1d168592748002c1dbeede2e46870b94ebec1fad/tfjs-node/src/kernels/MirrorPad.ts#L31)):*
> ```XML
>     const nodeBackend = backend as NodeJSKernelBackend;
> 
>     const paddingsTensor = tensor2d(paddings, [paddings.length, 2], 'int32');
> ```

I think this is the cause of the memory leak. Modular kernels are generally expected to clean up their own memory (and we are moving to system where kernels don't create 'tensors' they just allocate memory as needed). But for now I think this tensor just needs to be disposed after calling executeSingleOutput. You can save the result of the backend execution to a variable so that you can dispose this before returning the result.

**Review by AbdallaGomaa — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-core/src/ops/mirror_pad.ts, line 57 at r8](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIyjvrfB0kHGoJHes_0:-MJ1menf6IzZYY_6AuRt:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/1d168592748002c1dbeede2e46870b94ebec1fad/tfjs-core/src/ops/mirror_pad.ts#L57)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

remove the default assignement, add an assertion that it is reflect or symettric.
</blockquote></details>

Done.
___
*[tfjs-node/src/kernels/MirrorPad.ts, line 31 at r8](https://reviewable.io/reviews/tensorflow/tfjs/3951#-MIyiyGLCVRPwnDUC0In:-MJ21MMdBYVbYYRC2Dtd:bqlg1iw) ([raw file](https://github.com/tensorflow/tfjs/blob/1d168592748002c1dbeede2e46870b94ebec1fad/tfjs-node/src/kernels/MirrorPad.ts#L31)):*
<details><summary><i>Previously, tafsiri (Yannick Assogba) wrote…</i></summary><blockquote>

I think this is the cause of the memory leak. Modular kernels are generally expected to clean up their own memory (and we are moving to system where kernels don't create 'tensors' they just allocate memory as needed). But for now I think this tensor just needs to be disposed after calling executeSingleOutput. You can save the result of the backend execution to a variable so that you can dispose this before returning the result. 
</blockquote></details>

That fixed the issue. Thanks! Done.

**Review by tafsiri — APPROVED** [review]
> Reviewed 1 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3951)* status: :shipit: complete! 3 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

**Pull request merged**
