### PR TITLE
Update converter TF version to 2.12.0

### PR DESCRIPTION
**Pull request by mattsoulanille**
Update tfjs-converter python dependencies to use tensorflow>=2.12.0. This is required for protobuf versions above 3.20.x. Otherwise, it throws `TypeError: Descriptors cannot not be created directly.` See [this stackoverflow](https://stackoverflow.com/questions/72441758/typeerror-descriptors-cannot-not-be-created-directly) for more details.

Orbax requires at least python 3.8.0. Update the CI docker from buster to bullseye, which uses python 3.9.

Additionally, make the converter python nightly tests cloudbuild file use the release docker when running tests. 

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

### CODE REVIEW

**Comment by mattsoulanille** [comment]
[Nightly tests](https://console.cloud.google.com/cloud-build/builds/8c9524a9-2474-438b-9377-3381f4f83cb6?project=834911136599)

https://console.cloud.google.com/cloud-build/builds/8c9524a9-2474-438b-9377-3381f4f83cb6?project=834911136599

**Comment by mattsoulanille** [comment]
[Nightly tests](https://console.cloud.google.com/cloud-build/builds/f73b89bc-3f77-4807-872b-d5a2b1397418?project=834911136599)

[Converter python nightly tests](https://console.cloud.google.com/cloud-build/builds/90eee9a9-f77e-4e51-be5f-5e897aeb12d1?project=834911136599)

**Comment by mattsoulanille** [comment]
[Converter python nightly tests](https://console.cloud.google.com/cloud-build/builds/c2ed44c8-196e-498a-a64e-2ba1043501fb?project=834911136599)

**Comment by mattsoulanille** [comment]
This is failing presubmits because tf 2.12.0 requires python>=3.8.0, and the docker container changes in this PR have not been published yet.

**Review by pyu10055 — COMMENTED** [review]
Thanks Matt, interestingly the python nightly test passed with this change, since it depends on the python3_wheel target.
https://github.com/tensorflow/tfjs/blob/master/tfjs-converter/python/BUILD.bazel#L68

I believe this part needs to reflect the same change you made to requirements.txt

**Comment by mattsoulanille** [comment]
Good catch, @pyu10055. I've changed the dependencies listed in the BUILD target to match requirements.txt.

[Converter python nightly tests](https://console.cloud.google.com/cloud-build/builds/46fd4930-5e72-4bf0-b442-9dbe5d688fd1?project=834911136599)

**Review by pyu10055 — APPROVED** [review]

**Review by Linchenn — APPROVED** [review]

**Pull request merged**
