### PR TITLE
Add support for converting models with ImageProjectiveTransformV3 op

### PR DESCRIPTION
**Pull request by maciej3031**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

This PR covers the following issue [#6204](https://github.com/tensorflow/tfjs/issues/6204)

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6206)

### CODE REVIEW

**Review by lina128 — CHANGES_REQUESTED** [review]
This is great, thank you for your contribution, @maciej3031 ! I only have some minor comments, then the PR should be ready to merge.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6206#-:-My8XRV6CiFDmjopFOg2:b7gr332)* status: 0 of 1 approvals obtained (waiting on @maciej3031)

___
*[tfjs-converter/python/tensorflowjs/op_list/image.json, line 114 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6206#-My8W9Zu06Wh7WqTtG2M:-My8W9Zu06Wh7WqTtG2N:b-62yhsu) ([raw file](https://github.com/tensorflow/tfjs/blob/bd919193fcc8bfaafa74c002db67a52c8a696f85/tfjs-converter/python/tensorflowjs/op_list/image.json#L114)):*
> ```JSON
>       {
>         "start": 0,
>         "name": "image",
> ```

images, ref: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt#L21603-L21650



_Code quote:_
```JSON
image
```
___
*[tfjs-converter/python/tensorflowjs/op_list/image.json, line 124 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6206#-My8WIKZ9j32u9s5Ziw-:-My8WIKZ9j32u9s5Ziw0:b-s0chx0) ([raw file](https://github.com/tensorflow/tfjs/blob/bd919193fcc8bfaafa74c002db67a52c8a696f85/tfjs-converter/python/tensorflowjs/op_list/image.json#L124)):*
> ```JSON
>       {
>         "start": 2,
>         "name": "outputShape",
> ```

Also add tfName: "output_shape", ref: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt#L21603-L21650



_Code quote:_
```JSON
outputShape
```
___
*[tfjs-converter/python/tensorflowjs/op_list/image.json, line 129 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6206#-My8WPWNCHm-OkIetvKx:-My8WPWNCHm-OkIetvKy:bax1r1a) ([raw file](https://github.com/tensorflow/tfjs/blob/bd919193fcc8bfaafa74c002db67a52c8a696f85/tfjs-converter/python/tensorflowjs/op_list/image.json#L129)):*
> ```JSON
>       {
>         "start": 3,
>         "name": "fillValue",
> ```

Also add tfName: "fill_value", ref: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt#L21603-L21650



_Code quote:_
```JSON
fillValue
```
___
*[tfjs-converter/src/operations/executors/image_executor.ts, line 82 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6206#-My8WrMf4exSflyoQDpT:-My8WrMf4exSflyoQDpU:b-2n2vhn) ([raw file](https://github.com/tensorflow/tfjs/blob/bd919193fcc8bfaafa74c002db67a52c8a696f85/tfjs-converter/src/operations/executors/image_executor.ts#L82)):*
> ```XML
>         }
>         case 'ImageProjectiveTransformV3': {
>           const image =
> ```

images, it's a 4D, may take a batch of images.



_Code quote:_
```XML
image
```

**Comment by maciej3031** [comment]
Hi @lina128 , I addressed your comments except from these two:
```
- Also add tfName: "output_shape", ref: [...]
- Also add tfName: "fill_value", ref: [...]
```
I'm not very familiar with the tfjs repo but it seems to me that `tfName` does not exist in `InputParamMapper` so it cannot be used there. It's only present in `AttrParamMapper` 🤔

**Comment by lina128** [comment]
Ah, you are right.

**Review by lina128 — APPROVED** [review]
:lgtm_strong:

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6206#-:-MyDhUCs1QC7XNBfYpCQ:b-jbsf8z)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @maciej3031)

**Pull request merged**
