### PR TITLE
Add euclideanNorm op.

### PR DESCRIPTION
**Pull request by lina128**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6366)

### CODE REVIEW

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6366)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @lina128)

___
*[`tfjs-converter/src/operations/executors/normalization_executor_test.ts` line 52 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6366#-N1F0VJw1tVjqTkR1nhH:-N1F0VJw1tVjqTkR1nhI:b-qtz0sd) ([raw file](https://github.com/tensorflow/tfjs/blob/7130da8e337554161698a3c797ac2381a105ce06/tfjs-converter/src/operations/executors/normalization_executor_test.ts#L52)):*
> ```XML
>         node.inputParams['axis'] = createNumericArrayAttrFromIndex(1);
>         node.attrParams.keepDims = createBoolAttr(false);
>         node.inputNames = ['input1', 'input2', 'input3'];
> ```

should be only two inputs?
___
*[`tfjs-core/src/ops/euclidean_norm.ts` line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6366#-N1F0dTc085irHXgWXfc:-N1F0dTc085irHXgWXfd:bb6ht37) ([raw file](https://github.com/tensorflow/tfjs/blob/7130da8e337554161698a3c797ac2381a105ce06/tfjs-core/src/ops/euclidean_norm.ts#L3)):*
> ```XML
> /**
>  * @license
>  * Copyright 2021 Google LLC. All Rights Reserved.
> ```

2022

**Review by ahmedsabie — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6366)* status: 0 of 1 approvals obtained (waiting on @lina128)

___
*[`tfjs-core/src/ops/euclidean_norm_test.ts` line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6366#-N1FYr1V9iUan9gRsxxL:-N1FYr1V9iUan9gRsxxM:bocmemu) ([raw file](https://github.com/tensorflow/tfjs/blob/7130da8e337554161698a3c797ac2381a105ce06/tfjs-core/src/ops/euclidean_norm_test.ts#L22)):*
> ```XML
> import {expectArraysClose} from '../test_util';
> 
> // Because euclidean is the default norm option, the norm_test covers
> ```

I recommend adding the euclidean specific norm_tests here because it's not guaranteed that in the future euclidean implementation will always be dependent on norm

**Review by lina128 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6366)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @pyu10055)

___
*[`tfjs-converter/src/operations/executors/normalization_executor_test.ts` line 52 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6366#-N1F0VJw1tVjqTkR1nhH:-N1dvEseBzOCIiK-Iqoq:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/7130da8e337554161698a3c797ac2381a105ce06/tfjs-converter/src/operations/executors/normalization_executor_test.ts#L52)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

should be only two inputs?
</blockquote></details>

Done.
___
*[`tfjs-core/src/ops/euclidean_norm.ts` line 3 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6366#-N1F0dTc085irHXgWXfc:-N1dvHU7DTYEdQ3eX5Pv:b-896fix) ([raw file](https://github.com/tensorflow/tfjs/blob/7130da8e337554161698a3c797ac2381a105ce06/tfjs-core/src/ops/euclidean_norm.ts#L3)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

2022
</blockquote></details>

Done.
___
*[`tfjs-core/src/ops/euclidean_norm_test.ts` line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6366#-N1FYr1V9iUan9gRsxxL:-N1dvhAy0x6ykiln5Srl:bcto08r) ([raw file](https://github.com/tensorflow/tfjs/blob/7130da8e337554161698a3c797ac2381a105ce06/tfjs-core/src/ops/euclidean_norm_test.ts#L22)):*
<details><summary><i>Previously, ahmedsabie wrote…</i></summary><blockquote>

I recommend adding the euclidean specific norm_tests here because it's not guaranteed that in the future euclidean implementation will always be dependent on norm
</blockquote></details>

Right now, the euclidean_norm directly calls into norm, there's no other logic in the euclidean_norm.ts, so the only thing we want to test for that code is if the API can be called correctly. If we are going to change the implementation in that file, we should definitely change tests in the same PR when that change happens.

**Review by ahmedsabie — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6366)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @lina128 and @pyu10055)

___
*[`tfjs-core/src/ops/euclidean_norm_test.ts` line 22 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6366#-N1FYr1V9iUan9gRsxxL:-N1eDiHy7T0Q2GV8Yv8-:b-y44xvh) ([raw file](https://github.com/tensorflow/tfjs/blob/7130da8e337554161698a3c797ac2381a105ce06/tfjs-core/src/ops/euclidean_norm_test.ts#L22)):*
<details><summary><i>Previously, lina128 (Na Li) wrote…</i></summary><blockquote>

Right now, the euclidean_norm directly calls into norm, there's no other logic in the euclidean_norm.ts, so the only thing we want to test for that code is if the API can be called correctly. If we are going to change the implementation in that file, we should definitely change tests in the same PR when that change happens.
</blockquote></details>

Hmm my main concern is assuming that the next person changing the code will know that the test file has this assumption in it, although it is a small chance fair enough

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6366)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @lina128)

**Pull request merged**
