### PR TITLE
[webgpu] Update EQUAL,GREATER,GREATER_EQUAL,LESS,LESS_EQUAL

### PR DESCRIPTION
**Pull request by hujiajie**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

### CODE REVIEW

**Review by gyagp — COMMENTED** [review]
Can we reuse the code here as the only diff among them is comparison symbol?

**Comment by hujiajie** [comment]
I don't feel it's worth another level of nesting.

Floral_matryoshka_set_2_smallest_doll_nested

**Review by gyagp — APPROVED** [review]
LGTM

**Comment by xhcao** [comment]
Jiajie, I also agree with Yang's comments to reuse the similar code, I like the code as below,
const ZERO = `(sign(a) * 0 + 0)`;
const ONE = `(sign(b) * 0 + 1)`;
const EQUAL = `
  let resultTemp = select(${ZERO}, ${ONE}, a == b);
`;
const GREATER = `
  let resultTemp = select(${ZERO}, ${ONE}, a > b);
`;
...

But I am OK if you want to keep your code style.

**Review by xhcao — APPROVED** [review]

**Comment by hujiajie** [comment]
> Jiajie, I also agree with Yang's comments to reuse the similar code, I like the code as below,
> const ZERO = `(sign(a) * 0 + 0)`;
> const ONE = `(sign(b) * 0 + 1)`;
> const EQUAL = `let resultTemp = select(${ZERO}, ${ONE}, a == b);`;
> const GREATER = `let resultTemp = select(${ZERO}, ${ONE}, a > b);`;
> ...
> 
> But I am OK if you want to keep your code style.

I have mixed feeling atm, but let me know if anyone has a strong preference. I may consider making that a separate PR afterwards.

**Pull request merged**
