### PR TITLE
Support benchmarking custom models performance

### PR DESCRIPTION
**Pull request by Linchenn**
This PR does the following:

1. Enables users to benchmark custom GraphModel or LayersModel models performance
2. Adds the benchmarking parameter table and the input table to the webpage

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/3469)

### CODE REVIEW

**Comment by Linchenn** [comment]
You can temporarily view the new tool from this:
https://Linchenn.github.io/tfjs/e2e/benchmarks/index.html.

**Comment by Linchenn** [comment]
## Use cases 
### Different model types
- GraphModel: 
https://storage.googleapis.com/tfjs-models/savedmodel/mobilenet_v2_1.0_224/model.json
- LayersModel: https://storage.googleapis.com/tfjs-models/tfjs/iris_v1/model.json

### Different sources
- TF Hub: https://tfhub.dev/google/tfjs-model/imagenet/resnet_v2_50/feature_vector/1/default/1
- Storage: https://storage.googleapis.com/tfjs-models/savedmodel/mobilenet_v2_1.0_224/model.json
- LocalStorage
- IndexDB

#### LocalStorage
Store the model in LocalStorage at first:
```javascript
const localStorageModel = tf.sequential(
     {layers: [tf.layers.dense({units: 1, inputShape: [3]})]});
const saveResults = await localStorageModel .save('localstorage://my-model-1');
```
Then use "localstorage://my-model-1" as the custom model URL.

#### IndexDB
Store the model in IndexDB at first:
```javascript
const indexDBModel = tf.sequential(
     {layers: [tf.layers.dense({units: 1, inputShape: [3]})]});
const saveResults = await indexDBModel .save('indexeddb://my-model-1');
```
Then use "indexeddb://my-model-1" as the custom model URL.

**Comment by lina128** [comment]
Hi Lin, this is a great start! Thank you for making this happen!

**Comment by Linchenn** [comment]
You can see it at https://Linchenn.github.io/tfjs/e2e/benchmarks/index.html
Thanks!

**Pull request merged**
