### PR TITLE
[e2e] Run regression tests in PR presubmits

### PR DESCRIPTION
**Pull request by mattsoulanille**
Regression tests don't take too long to run, and they can catch more errors. This PR enables them for PR presubmits.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

- - -
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6896)

### CODE REVIEW

**Comment by mattsoulanille** [comment]
Depends on https://github.com/tensorflow/tfjs/pull/6895

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6896)* status: 0 of 1 approvals obtained (waiting on @ahmedsabie and @mattsoulanille)

___
*[`e2e/scripts/test-ci.sh` line 53 at r1](https://reviewable.io/reviews/tensorflow/tfjs/6896#-ND_OH0C4ki8pYmJmnDs:-ND_OH0C4ki8pYmJmnDt:b-vmh9pj) ([raw file](https://github.com/tensorflow/tfjs/blob/4d25e6389a0d352e74afcc21f4059935f4126b28/e2e/scripts/test-ci.sh#L53)):*
> ```Shell
> 
> node ../scripts/run_flaky.js "yarn run-browserstack --browsers=win_10_chrome --tags '$TAGS'"
> node ../scripts/run_flaky.js "yarn run-browserstack --browsers=bs_safari_mac --tags '$TAGS' --testEnv webgl --flags '{"\""WEBGL_VERSION"\"": 1, "\""WEBGL_CPU_FORWARD"\"": false, "\""WEBGL_SIZE_UPLOAD_UNIFORM"\"": 0}'"
> ```

remove this test given WebGL1 is not by default after safari 15

**Review by pyu10055 — APPROVED** [review]
> Reviewed 5 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6896)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @ahmedsabie and @mattsoulanille)

**Review by ahmedsabie — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/6896)* status: :shipit: complete! 2 of 1 approvals obtained (waiting on @mattsoulanille)

**Pull request merged**
