### PR TITLE
[webgl]Refactor GPGPUBinary.

### PR DESCRIPTION
**Pull request by lina128**
Refactor GPGPUBinary's data structure to include fragmentShader, so that we can retrieve it from the GPGPUBinary cache.

This refactor allows us to check compilation status of fragmentShaders in a batch, rather than in serial order.

To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5796)

### CODE REVIEW

**Review by pyu10055 — COMMENTED** [review]
where will the fragment shader be used? the code in the PR does not explain why the change is needed.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5796#-:-MnE5O2S3pVo4WhZEz8p:b-an3thm)* status: 0 of 1 approvals obtained

**Review by lina128 — COMMENTED** [review]
This will be used in parallel compilation. I updated the PR description.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5796#-:-MnHLZt_3kxMQHCpUq_P:b-jhaql7)* status: 0 of 1 approvals obtained

**Review by pyu10055 — COMMENTED** [review]
Thanks looking at the related code, seems we can just support fragment shader as the single type, the string compilation can be move up to the caller. 
Feels this way the api is cleaner.

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5796#-:-MnIa6VP65qkGmvPdHC6:bfvvi1)* status: 0 of 1 approvals obtained

**Review by lina128 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5796#-:-MnRPaR0EYJ0_H2pV8Z8:bb6un1j)* status: 0 of 1 approvals obtained

**Review by pyu10055 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/5796)* status: :shipit: complete! 1 of 1 approvals obtained

**Pull request merged**
