### PR TITLE
[core] MatMul broadcasting.

### PR DESCRIPTION
**Pull request by annxingyuan**
To see the logs from the Cloud Build CI, please join either our [discussion](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs) or [announcement](https://groups.google.com/a/tensorflow.org/forum/#!forum/tfjs-announce) mailing list.

---
This change is [Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4100)

### CODE REVIEW

**Comment by tafsiri** [comment]
hey @annxingyuan, looks like tests don't pass for this on node do you want to take a look at that before we review?

**Comment by annxingyuan** [comment]
yes @tafsiri sorry i thought it was flaking at first - removed reviewers and will re-add when ready

**Review by pyu10055 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 8 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4100)* status: 0 of 1 approvals obtained (waiting on @annxingyuan, @pyu10055, and @tafsiri)

___
*[tfjs-core/src/ops/mat_mul.ts, line 89 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4100#-MKDyQd10SKxKdyyeedg:-MKDyQd10SKxKdyyeedh:b-de5r2b) ([raw file](https://github.com/tensorflow/tfjs/blob/6c923ff31615322791334839dc5fecb02ca49eb8/tfjs-core/src/ops/mat_mul.ts#L89)):*
> ```XML
> 
>     const outShapeOuterDims =
>         batchDimA > batchDimB ? $a.shape.slice(0, -2) : $b.shape.slice(0, -2);
> ```

can these be replaced with variables: outerDimsA and outerDimsB?
___
*[tfjs-node/src/run_tests.ts, line 84 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4100#-MKDwL7R4NYSA7bIwieK:-MKDwL7R4NYSA7bIwieL:bbjwsb6) ([raw file](https://github.com/tensorflow/tfjs/blob/6c923ff31615322791334839dc5fecb02ca49eb8/tfjs-node/src/run_tests.ts#L84)):*
> ```XML
>   'maxPoolWithArgmax', 'rotate', 'flipLeftRight', 'unique',
>   // libtensorflow does not yet support tf.matmul with broadcast
>   'broadcast with unequal batch dims', 'broadcast with unequal ranks'
> ```

why tests for tfjs-node need to be skipped?

**Review by annxingyuan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4100)* status: 0 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

___
*[tfjs-core/src/ops/mat_mul.ts, line 89 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4100#-MKDyQd10SKxKdyyeedg:-MKEqWYP7Cn5ras-VjD4:bb6un1j) ([raw file](https://github.com/tensorflow/tfjs/blob/75f44b9c12630ef44a17f37dda26b87cb050d5b7/tfjs-core/src/ops/mat_mul.ts#L89)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

can these be replaced with variables: outerDimsA and outerDimsB?
</blockquote></details>

Done
___
*[tfjs-node/src/run_tests.ts, line 84 at r2](https://reviewable.io/reviews/tensorflow/tfjs/4100#-MKDwL7R4NYSA7bIwieK:-MKEqXBk2PtnK7b3iOPT:b107bgt) ([raw file](https://github.com/tensorflow/tfjs/blob/75f44b9c12630ef44a17f37dda26b87cb050d5b7/tfjs-node/src/run_tests.ts#L84)):*
<details><summary><i>Previously, pyu10055 (Ping Yu) wrote…</i></summary><blockquote>

why tests for tfjs-node need to be skipped?
</blockquote></details>

Broadcasting support was recently added in tensorflow 2.0 - libtensorflow does not yet support it.

**Review by pyu10055 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/tensorflow/tfjs/4100)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @pyu10055 and @tafsiri)

**Pull request merged**
